### ISSUE TITLE
Spyder hangs if you open the Issue reporter while Preferences is open

### ISSUE THREAD

**Issue by rlabbe** [spyder-ide/spyder#10138]
### What steps will reproduce the problem?

1. Open Spyder
2. Open the Preferences dialog
3. Open the Issue reporter via the help menu

At this point Spyder hangs. The Issue reporter dialog doesn't appear, you can't close preferences or Spyder, or otherwise interact with Spyder in any way.

If I perform only steps 1 and 3 then the Issue reporter dialog appears and Spyder is responsive. 

## Versions

* Spyder version: 4.0.0b4 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
pyls >=0.27.0     :  0.28.2 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.5.2 :  4.5.4 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
@goanpeca, this is caused by Preferences appearing on top of everything else and our error report dialog being modal.

I think the problem with our Preferences was introduced here:

https://github.com/spyder-ide/spyder/pull/9740/files#diff-0218c339b4429cfe6796ab926aacb433R151

(which was made in one of your PRs), so I think perhaps we should revert it?

**Comment by ccordoba12** [comment]
By the way, that change also makes that our Preferences stay on top of any other window on Linux even if Spyder's main window loses focus (which I find very annoying).
