### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by Mihretu** [spyder-ide/spyder#10322]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
I was trying to upgrade to 3.36 from 3.28 and after that after checking for the requirements satisfaction it gave an error "can not unstall spyder : it is  adistutil installed project and thus we can not accurately determine ..."

**Comment by ccordoba12** [comment]
Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.
