### ISSUE TITLE
Decreasing automatic_completions_after_ms setting causes lag when typing

### ISSUE THREAD

**Issue by its-dhung** [spyder-ide/spyder#10457]
## Problem Description
Changing the setting `automatic_completions_after_ms` to a low but reasonable (from user's point of view) number causes noticeable lag when editing code.

### What steps reproduce the problem?

1. Change the `automatic_completions_after_ms` setting to 50ms:
![image](https://user-images.githubusercontent.com/3752225/67116621-a7d9ca00-f195-11e9-9a72-dad3d62562ed.png)
2. Try editing a Python file e.g. type out:
```python
import numpy as np
import matplotlib.pyplot as plt
```

### What is the expected output? What do you see instead?
__Expected__
As a user, I would expect minimal lag.

__Actual__
There is noticeable lag in between typing a character and it being inserted into the buffer. This happens regardless of what completions engines are enabled and the value of the setting `automatic_completions_after_chars`. It appears as though something is blocking the UI thread in between keystroke → completion request → buffer update in UI.

## Versions

* Spyder version: 4.0.0.dev0 (Commit: c2b7673b1)
* Python version: 3.7.4 64-bit
* Qt version: Qt 5.9.6
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Darwin 18.7.0

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.6.0 (OK)
sphinx >=0.6.6               :  2.2.0 (OK)
pylint >=0.25                :  2.4.2 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.5.0;<2.0.0:  1.6.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.8.0 (OK)
matplotlib >=2.0.0           :  None (NOK)
pandas >=0.13.1              :  None (NOK)
numpy >=1.7                  :  None (NOK)
scipy >=0.17.0               :  None (NOK)
pyls >=0.28.2;<0.29.0        :  0.28.3 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by dalthviz** [comment]
Note: seems like this behavior is related with the size of the file (at least on Windows)

**Comment by dalthviz** [comment]
@metalogical its going to help with this one

**Comment by CAM-Gerlach** [comment]
> Note: seems like this behavior is related with the size of the file (at least on Windows)

Yep, I've noticed this as well, and it indeed scales directly with file length and inversely with OTF completion delay. 

To note, this would also be generally consistent with similar typing lag I've observed on Windows as well since at least the time of Beta 2 that scales with file length and is particularly noticeable on files >=~ 500-1000 lines with indent guides/code folding enabled, as I reported on #8864 (whereas here it is of course triggered by on the fly completion). In order to generate the code folding levels, does Spyder send the file text back and forth over the TCP/IP stack to LSP (like it presumably does for OTF completion)? If so, then the ultimate root cause could come down to the same issue.

There was another earlier issue where I reported, tested and documented a substantial performance hit in typing lag, etc (up to several times in tests). between Spyder 3 and 4 even without this enabled but not sure its related.
