### ISSUE TITLE
Variable explorer not showing data

### ISSUE THREAD

**Issue by sts77** [spyder-ide/spyder#10562]
### What steps will reproduce the problem?

tried to read data using pandas but variable explorer is not showing the data

### Traceback
```python-traceback
  File "/home/sysg/anaconda3/envs/Py36/lib/python3.6/site-packages/spyder/widgets/variableexplorer/importwizard.py", line 633, in process
    self.clip_data = self._get_table_data()
  File "/home/sysg/anaconda3/envs/Py36/lib/python3.6/site-packages/spyder/widgets/variableexplorer/importwizard.py", line 613, in _get_table_data
    return array(data)
NameError: name 'array' is not defined
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.6.9
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-66-generic

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
psutil >=0.3      :  5.6.3 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  None (OK)
numpy >=1.7       :  None (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.9.0 (OK)
matplotlib >=2.0.0:  None (OK)
pylint >=0.25     :  2.4.3 (OK)
```

**Comment by ccordoba12** [comment]
Please explain how you're trying to read the data.

**Comment by CAM-Gerlach** [comment]
Per the traceback, the user is attempting to read data via the Spyder importwizard; it sounds like they are specifically trying to do so using the "i Naturally, this fails because

> pandas >=0.13.1   :  None (OK)

pandas is not installed. Presuming this is the case, Spyder should show a user-interpretable error (e.g. a QDialog with "Pandas must be installed in Spyder's environment to import data as a Pandas dataframe. Please install pandas or try importing data into a different format instead."); assuming that importing data into a simple list without pandas, numpy etc. is even possible; if not then an error dialog with an appropriate message should be shown immediately on the user triggering the importwizard.
