### ISSUE TITLE
Go to definition in editor not working for files in user PYTHONPATH

### ISSUE THREAD

**Issue by rhkarls** [spyder-ide/spyder#10646]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The "Go to definition" feature in the editor context menu, or CTRL+G, does not work on files that are in my own PYTHONPATH. It does however work on installed libraries and files I place myself in site-packages (on windows with Anaconda \AppData\Local\Continuum\anaconda3\Lib\site-packages).

### What steps reproduce the problem?

1. Create a file "myfileinpythonpath.py" with a method mymethod(), place it in a PYTHONPATH included path
2. "from myfileinpythonpath import mymethod" works, but I can not use Go to definition to access the file/method
3. Works as expected (opens the .py file) if I place the file in site-packages or try on another library, for example "import pathlib" and use Go to definition on pathlib

## Versions
* Spyder version: 4.0.0rc1 (same problem also in b7)
* Python version: 3.7.4 64-bit
* Qt version: Qt 5.12.5
* PyQt version: PyQt5 5.12.3
* Operating System name/version: Windows 10

Running Kite if that matters.

**Comment by ccordoba12** [comment]
@goanpeca is working on this right now. It should be ready next week.

**Comment by skudekar** [comment]
Hi, 

I have a similar problem. I updated to spyder 4 and now the right-click "Go to definition" doesn't work anymore. I have windows 10 and anaconda environment. I also tried putting my project directory in the PYTHONPATH manager and it still doesn't work. Is there a solution for this issue? My project files are big and not having this feature is making it impossible to work. Any help would be greatly appreciated. Do I need to uninstall and re-install spyder 4?

**Comment by rhkarls** [comment]
@skudekar Are other things like linting also not working? See #11026

**Comment by skudekar** [comment]
Thanks @rhkarls for getting back. I'm not sure I know what is linting. Sorry I'm new to the spyder environment. So I reset the spyder settings and it works, but only ONCE and then it stops working again. I'll have a look at #11026 and check it out and see if it works. Thanks again!

**Comment by skudekar** [comment]
@rhkarls I tried the solution mentioned in #11026 but it seems that parso is already installed for me. See below:
```conda install parso=0.5.2
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.```

How do I check the version of parso installed? And can I simply ```conda uninstall parso``` and then again ```conda install parso=0.5.2```? Thanks again for your help!

**Comment by NicoRicardi** [comment]
Dear All, 
I updated spyder3 (had issues with arrays in the variable explorer with older versions) and the "go to definition" never works (neither stuff in python stuff nor stuff in my .local/lib/python3.6/site-packages
).
I tried _spyder --reset_ and jedi and parso are the suggested versions (0.17.0 and 0.5.2, respectively).

Any suggestion?

**Comment by ccordoba12** [comment]
Please remove this directory

    .local/lib/python3.6/site-packages

and install Anaconda instead.

**Comment by NicoRicardi** [comment]
I am using pip and that is the location where all my packages are. I cannot remove it.

**Comment by NicoRicardi** [comment]
Dear Carlos Cordoba,
is it possible to use pip instead of Anaconda? I was doing so until spyder3.
If so, how can I make sure the ctrl+click goes to definition?

**Comment by ccordoba12** [comment]
> is it possible to use pip instead of Anaconda? I was doing so until spyder3.

@NicoRicardi, no, it's not.

**Comment by enricovara** [comment]
Hi All,

Unless I'm doing something wrong, there still seems to be an intermittent issue with "Go to definition" in editor not working (simply does nothing).

Spyder version(s): issue is present and identical in Spyder 4.2.3 standalone for Mac and in 4.2.1 installed using Conda.
Python: 3.8
Intermittent: works for installed packages (eg clicking "Go to definition" on `rnd` in `import random as rnd` opens random.py), doesn't work for my own modules (eg clicking "Go to definition" on `my_mod` in `import something as my_mod` where `something.py` is a module in the `pwd` or in some directory I added using `sys.path.append(some_dir)`). Also note that the issue isn't that Python can't find the module because `import something as my_mod` itself works.
How to reproduce: no idea - I have two folders with two projects and it works in one and not the other, regardless of where 'I am' (in the sense of what os.getcwd() returns. The only difference is that in the case where it works, the imported module is in a separate folder from the project while in the case where it doesn't the imported module is in a daughter folder inside the project folder.
Hacky fix: it works if I add the path to the folder containing the `something.py` file to the PYTHONPATH using the GUI PYTHONPATH manager.

Anyone have any idea what's going on?

Anyone know how I can  add the path to the folder containing the `something.py` file to the PYTHONPATH in the editor without having to do so manually by using the GUI PYTHONPATH manager?

Please let me know if you need more info.

Many thanks,
Enrico

**Comment by ccordoba12** [comment]
Hey @enricovara, this is a known bug but (unfortunately) we haven't had time to fix it. We'll try to do it in the next couple of months.

**Comment by enricovara** [comment]
Oh many thanks @ccordoba12!

**Comment by Vaderv** [comment]
This might be related to when the number of lines of code in the editor exceeds a certain threshold and the editor slows down.

**Comment by enricovara** [comment]
@ccordoba12, any updates (I've been out of the loop apologies) or comments on @Vaderv's message?

**Comment by ccordoba12** [comment]
I think your problem was fixed some months ago. Please try with our latest version (5.3.0) and let us know.

**Comment by fazelehh** [comment]
I have the same problem with the updated version of spyder. I am using:
# Name                    Version                   Build  Channel
pyls-spyder               0.4.0              pyhd8ed1ab_0    conda-forge
spyder                    5.3.0            py39hcbf5309_0    conda-forge
spyder-kernels            2.3.0            py39hcbf5309_0    conda-forge
