### ISSUE TITLE
Kernel cannot start after updating pip

### ISSUE THREAD

**Issue by junxuwdc** [spyder-ide/spyder#10668]
### What steps will reproduce the problem?

create a virtual environment
install ipykernel
update pip
link the new virtual env to jupyter

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\introspection\plugin_client.py", line 189, in _heartbeat
    def _heartbeat(self):
KeyboardInterrupt
Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.6.4
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Windows 7

### Dependencies

```
pyflakes >=0.6.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  1.6.6 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
nbconvert >=4.0   :  None (NOK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  7.9.0 (OK)
matplotlib >=2.0.0:  2.1.2 (OK)
pylint >=0.25     :  1.8.2 (OK)
```

**Comment by ccordoba12** [comment]
> install ipykernel

You need to install spyder-kernels version 0.5.2 for things to work correctly.

Besides that, please stop using pip if you're using Anaconda to install those packages. That's because pip and conda packages are binary incompatible. So if things don't work after installing spyder-kernels, I'm afraid you'll have to reinstall Anaconda because you corrupted it by using pip.
