### ISSUE TITLE
Spyder closes unexpectedly when trying to change plain text font

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#10893]
## Problem Description

Trying to change plain text font make Spyder crash.

### What steps reproduce the problem?

1. Try to change plain text font
2. Wait for Spyder to crash

![spyder_crash](https://user-images.githubusercontent.com/10170372/69907320-4a928480-13a1-11ea-8045-d872b6647953.gif)

### Paste Traceback/Error Below (if applicable)

This is what is written in my Windows Terminal.
```python-traceback
QBackingStore::endPaint() called with active painter on backingstore paint device
```
This is what I managed to retrieve one time in my internal console:
```python-traceback
DirectWrite: CreateFontFaceFromHDC() failed (Indique une erreur dans un fichier d’entrée, tel qu’un fichier de polices.) for QFontDef(Family="Fixedsys", pointsize=12, pixelsize=15, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("Fixedsys", lfWidth=0, lfHeight=-15) dpi=96
```

If I understand https://bugreports.qt.io/browse/QTBUG-57180 correctly, the `DirectWrite: CreateFontFaceFromHDC() [...]` should be a harmless warning and shouldn't make Spyder crash. So I digged a little bit and found out that indeed, Spyder was crashing because of the Internal console and more specifically because of the call to `QCoreApplication.processEvents()` here :

https://github.com/spyder-ide/spyder/blob/73f958425ecc0d79788a413ce4c13fad5b29146e/spyder/plugins/console/widgets/shell.py#L561-L566

If I remove this line, then the warning appears in the internal console, but Spyder doesn't crash anymore.

I've also noticed for a bit that Spyder was crashing often when adding temporarily `print` within the code while debugging and developing.

## Versions

* Spyder 4.0.0.dev0 (Commit: 8357c073c) 
* Python 3.7.3 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.6.0            :  4.7.0.dev0 (OK)
nbconvert >=4.0              :  5.6.0 (OK)
sphinx >=0.6.6               :  2.2.1 (OK)
pylint >=0.25                :  2.4.3 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0.dev0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.0;<2.0.0:  1.9.0.dev0 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.13 (OK)
IPython >=4.0                :  7.9.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.2 (OK)
numpy >=1.7                  :  1.17.2 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.31.1;<0.32.0        :  0.31.1 (OK)
rtree >=0.8.3                :  0.8.3 (OK)

```

**Comment by ccordoba12** [comment]
I can't reproduce this on Windows 7. @CAM-Gerlach, are you able to reproduce this error?

**Comment by jnsebgosselin** [comment]
I can reproduce this bug also by adding a `print` in the code of Spyder. If the `print` is called at some critical time during runtime, Spyder crash.

**Comment by jnsebgosselin** [comment]
So basically, I think this is not a bug with the preferences, but with the internal console. Anything that send a message to the internal console  during runtime can possibly cause this bug

**Comment by CAM-Gerlach** [comment]
I couldn't repro this either on 8.1 and Qt/PyQt 5.9.7/5.9.2; I can load the font menu and switch fonts fine. It would seem your system may have a problem font that triggers the interaction with the internal console that then in turn causes the error.

**Comment by ccordoba12** [comment]
@CAM-Gerlach, but did you add a print that can be triggered while changing fonts takes effect?

**Comment by CAM-Gerlach** [comment]
No, I just tested in my currently running that I'm working in right now. I guess it was unclear from the above, but what I meant was that presumably @jnsebgosselin 's system has some front that triggers (A) the Qt error, which then triggers (B) the print to the internal console, which then triggers (C) the error as he explained. Given B, I presume C can be reproduced reliably; I was simply confirming my system does not have the initial trigger A to cause B.

However, now that I think of it, I _have_ reproduced something similar in the past; when I enabled the new indent guides during testing and got the issues described [here](https://github.com/spyder-ide/spyder/issues/8864#issuecomment-555804188). If enabled from the Source menu, as the repaint is triggered I get the Windows console error as here and only the first line of the error gets printed to the Internal Console and then it stops responding, while if I do the same from preferences, Spyder prints the full error to the Internal Console (possibly due to race/timing differences).

If you want me to confirm I can repro this with an arbitrary print statement somewhere, just let me know you want me to stick it exactly where it consistently repros the error for you. Thanks.

**Comment by jnsebgosselin** [comment]
I will find a place in the code where to put the print that trigger the error consistently and report back. I have encountered this issue recently while working on the keyboard shortcuts preferences.

**Comment by jnsebgosselin** [comment]
Ok, adding a print after `painter = QPainter(self)` trigger the crash 100% of the time for me when `Show indent guide` is checked.

https://github.com/spyder-ide/spyder/blob/2d5d450fdcef232fb7f38e7fefc27f0e7f704c9a/spyder/plugins/editor/panels/indentationguides.py#L40-L47

As for the case I reported in the OP, I also get the following error:

```python
QBackingStore::endPaint() called with active painter on backingstore paint device
```
I have encountered this issue a couple of time while developing Spyder, but it is the first time that I've encountered it as a user, thus the reason why I decided to report it.

**Comment by jnsebgosselin** [comment]
To prevent the crash, I need to remove the call to `QCoreApplication.processEvents()` and replace `repaint` by `update` in the internal console.

https://github.com/spyder-ide/spyder/blob/73f958425ecc0d79788a413ce4c13fad5b29146e/spyder/plugins/console/widgets/shell.py#L561-L566

**Comment by CAM-Gerlach** [comment]
@jnsebgosselin Confirmed, if I add the print I get very similar behavior to when indent guides weren't working, and the same two messages in the system console, except a full on crash instead of the UI just going crazy.

**Comment by maliozer** [comment]
When I tried to change font size with mouse whell, spyder is closed unexpectedly! It also does not save anything if you didnt, very ciritical :/

**Comment by CAM-Gerlach** [comment]
@maliozer Thanks; as discussed here the Spyder team is aware of the problem, and they're working on a fix. Also, in Spyder 4 (due out any day now), the new autosave feature will prevent you loosing any unsaved work if Spyder does crash for any reason.

**Comment by ccordoba12** [comment]
> To prevent the crash, I need to remove the call to QCoreApplication.processEvents() and replace repaint by update in the internal console.

This could have some unexpected side effects when running code on the internal console, so please leave the current code `if not DEV`, so the core team doesn't have problems due to this.

And thanks for finding the solution to this nasty crash @jnsebgosselin!

**Comment by ccordoba12** [comment]
@jnsebgosselin, I'm going to take care of this one.

**Comment by jnsebgosselin** [comment]
> 
> 
> @jnsebgosselin, I'm going to take care of this one.

Ok thanks!

**Comment by hsauro** [comment]
The bug is still present in spyder Spyder 4.1.3. Go to tool->preference->appearance and change the font size under plain text, hit apply button and the following error appears (running on Windows 10) 

  File "C:\Tellurium-Winpython-3.7\python-3.7.7.amd64\lib\site-packages\spyder\preferences\configdialog.py", line 236, in button_clicked
    configpage.apply_changes()
  File "C:\Tellurium-Winpython-3.7\python-3.7.7.amd64\lib\site-packages\spyder\preferences\configdialog.py", line 99, in apply_changes
    self.apply_callback()
  File "C:\Tellurium-Winpython-3.7\python-3.7.7.amd64\lib\site-packages\spyder\preferences\configdialog.py", line 282, in <lambda>
    self.apply_settings(self.changed_options))
  File "C:\Tellurium-Winpython-3.7\python-3.7.7.amd64\lib\site-packages\spyder\preferences\appearance.py", line 236, in apply_settings
    self.main.apply_settings()
  File "C:\Tellurium-Winpython-3.7\python-3.7.7.amd64\lib\site-packages\spyder\app\mainwindow.py", line 3111, in apply_settings
    self.apply_panes_settings()
  File "C:\Tellurium-Winpython-3.7\python-3.7.7.amd64\lib\site-packages\spyder\app\mainwindow.py", line 3126, in apply_panes_settings
    plugin._update_margins()
  File "C:\Tellurium-Winpython-3.7\python-3.7.7.amd64\lib\site-packages\spyder\plugins\base.py", line 230, in _update_margins
    self._default_margins = layout.getContentsMargins()
AttributeError: 'NoneType' object has no attribute 'getContentsMargins'

then spyder exits.

**Comment by jnsebgosselin** [comment]
I think this is not the same bug as the one originally reported in this Issue. Please open a new bug report.
