### ISSUE TITLE
Different icon for syntax error and undefined name (Spyder 4.0.0)

### ISSUE THREAD

**Issue by skjerns** [spyder-ide/spyder#11073]
First of all great work on Spyder 4! Great new features.

Currently the linting displays icons at the side of the code.
'invalid syntax' and 'undefined name' have the same icon.

However, it would be useful to immediately know whether to look for a syntax error or a missing var, without hovering over the icon.

Might it be an idea to separate the two icons?

**Comment by goanpeca** [comment]
>'invalid syntax' and 'undefined name'

Well they are both errors so it would mean giving different meaning to "error" which could lead us to more and more requests for specific icons.

**Comment by ccordoba12** [comment]
Perhaps they are reported differently by Pylint. We plan to add support for Pylint as a linting backend for 4.1, so please wait until that version is out (in a month and a half or two months) and report back.

If that's not the case, then there's really nothing we can do about this because we can't control the kind of icons and messages reported by the linting libraries we depend on (i.e. Pyflakes, which is the current one, and Pylint).

**Comment by skjerns** [comment]
> > 'invalid syntax' and 'undefined name'
> 
> Well they are both errors so it would mean giving different meaning to "error" which could lead us to more and more requests for specific icons.

they had different icons in spyder 3!

**Comment by ccordoba12** [comment]
Code completion and linting changed completely for Spyder 4. Now we're not using an in-house architecture, but the [Language Server Protocol](https://microsoft.github.io/language-server-protocol/), designed by Microsoft for VSCode.
