### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by hikerguy** [spyder-ide/spyder#11196]
### What steps will reproduce the problem?

I was in the Internal console window and got a traceback error when entering w <enter> and q <enter>. I mistyped pwd on the first one, and just tried q for grins and got this traceback message. 

### Traceback
```python-traceback
  File "C:\Users\hikerguy\Anaconda3\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 2, in <module>
NameError: name 'q' is not defined
```

## Versions

* Spyder version: 4.0.0 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.3.0 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.5 (OK)
cython >=0.21                :  0.29.14 (OK)
IPython >=4.0                :  7.10.2 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
numpy >=1.7                  :  1.17.4 (OK)
scipy >=0.17.0               :  1.3.2 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment]
Any error generated in the internal console shows the error report dialog, which can be reported here. That's by design.

If you don't want that to happen, please check the option called "Hide all future errors during the current session" in that dialog:

![Selección_073](https://user-images.githubusercontent.com/365293/71566554-872bcb80-2a86-11ea-8be2-8b4e8f15dcff.png)

*Note*: The internal console is not meant to run any kind of code really, just to inspect the internal of Spyder programmatically. Just so you know.
