### ISSUE TITLE
Improvements to the Help panel

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#11267]
## Problem Description

- [x] Change `Note` sections colors on the dark them
- [x] Change default snippets colors on the dark theme (from `Monokai` to `Spyder Dark`)
- [x] Add loading page
- [x] Unify `hover and click` vs `Ctrl + I` results (for example with `spyder/spyder/app/restart.py` doing `Ctrl+I` when the cursor is just before a parenthesis)
- [x] Change table style

**Comment by ccordoba12** [comment]
@dalthviz, as part of this effort, please also change the style of "Note" sections (which is the same of "See also" ones, I think):

![Selección_078](https://user-images.githubusercontent.com/365293/71999565-a7d6ec80-320f-11ea-8076-89e0851d3574.png)

This is the docstring of `plt.plot`.

**Comment by ccordoba12** [comment]
@dalthviz, please also take a look at this other bug. If you press `Ctrl+I` next to this function:

https://github.com/spyder-ide/spyder/blob/62de40c4005c9ca30be5c83bdbd6f366a3fccd42/spyder/app/restart.py#L62-L71

you'll get as a result in the Help pane:

![Selección_080](https://user-images.githubusercontent.com/365293/72019358-8be74100-3237-11ea-9310-b24b6bd4e1f3.png)

However, when you hover on the function and make a click on that hover, you'll get:

![Selección_081](https://user-images.githubusercontent.com/365293/72019418-a7524c00-3237-11ea-93bc-b7588445271f.png)

As you can see, the second result is the right one because it includes the header and the function signature, whereas the first one is missing those elements.

**Comment by ccordoba12** [comment]
@dalthviz, let's take this opportunity to also improve the style of tables in both the dark and light themes:

![Selección_083](https://user-images.githubusercontent.com/365293/72280791-27492f00-3607-11ea-93f2-150c5ee6f8ca.png)

These are my suggestions:

* Add a line to bottom border of the table.
* Please align the the table headers (i.e. `character` and `description` in the screenshot above) to the left.
* Please reduce the top and bottom padding around text in each cell by two or three pixels (please post screenshots here to see how it looks with different paddings).

**Comment by dalthviz** [comment]
@ccordoba12 a preview of the tables with the changes suggested above:

![image](https://user-images.githubusercontent.com/16781833/72282449-a9872280-360a-11ea-8502-f3eab64e5be8.png)

![image](https://user-images.githubusercontent.com/16781833/72282548-dd624800-360a-11ea-8bc4-2c3883dee7c5.png)

**Comment by ccordoba12** [comment]
Things look much better now, thanks @dalthviz! But please reduce the top/bottom padding in each cell a bit more.
