### ISSUE TITLE
No more custom docking?

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#11333]
In Spyder 3, I can dock any one window into any other window (/ container) - this no longer seems to be the case in 4; for example, I'd much prefer the documentation and project windows to be docked along the IPython console, but dragging them there does nothing. Ability to do so again would be quite helpful.

**Comment by MuellerSeb** [comment]
You can unlock the panes under ``view->lock panes and toolbars`` if they are locked.

**Comment by OverLordGoldDragon** [comment]
@MuellerSeb Didn't work; still unable to dock panes to other than their original spots

**Comment by goanpeca** [comment]
@OverLordGoldDragon could you post a small video using licecap or similar to see what you mean?

**Comment by OverLordGoldDragon** [comment]
@goanpeca Sure: [s3vs4_demo.mp4](https://www.dropbox.com/s/6y1snj00ghbf4zn/s3vs4_demo.mp4?dl=0)

**Comment by impact27** [comment]
I have the same issue on macos

**Comment by ccordoba12** [comment]
> Didn't work; still unable to dock panes to other than their default spots

In your video you have this option enabled (as it can be clearly seen in minute 0:29). When you uncheck it, you'll see a handle on top of each plugin, like this:

![Selección_089](https://user-images.githubusercontent.com/365293/72618108-6b3e7b80-3908-11ea-8038-350e72c34124.png)

So to create a custom layout you need to drag the pane from that handle and drop it in your preferred location, like this:

![Selección_091](https://user-images.githubusercontent.com/365293/72619640-bdcd6700-390b-11ea-8a08-0971d1711010.png)

We decided to change this so that the undock option creates a new window that can be moved to a different monitor. That's what most people wanted to do in Spyder 3 but it was not working very well because undocking in that version only separated a pane from the main window to position it in a different location of the same window.

**Comment by OverLordGoldDragon** [comment]
Oh, so it should be dragged BY the new handle - alright, great

Thanks
