### ISSUE TITLE
Imports hang after debugging (Spyder 4)

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#11477]
[steps_to_reproduce.mp4](https://www.dropbox.com/s/v2ytdb6chj0g5gb/hang_steps.mp4?dl=0). Closing spyder and re-opening (again via Anaconda PowerShell Prompt) fixes the issue.

Unsure if this occurs if launching directly via `spyder` (not `--new-instance`), but currently running a TensorFlow session I rather not interrupt.

**Comment by ccordoba12** [comment]
@impact27, could this be related to issue #11137?

**Comment by impact27** [comment]
It looks like the kernel doesn't like to be restarted while debugging. Steps to reproduce:
 - debug a file
 - when the `ipdb>` prompt is present, restart the kernel
 - the kernel is now broken

workaround: close and open a new kernel instead of restarting it.

Question: Why do we have logic to restart the kernel when the logic could be: close the kernel, open a new one?

**Comment by goanpeca** [comment]
>Question: Why do we have logic to restart the kernel when the logic could be: close the kernel, open a new one?

Restart will use the same port, close and open will create a new (and different port)
