### ISSUE TITLE
Cannot use mouse in Editor in Spyder4 (only with sudo), no problems in Spyder3

### ISSUE THREAD

**Issue by agustinvo** [spyder-ide/spyder#11571]
## Problem Description
I have recently upgraded to Spyder 4, and I was not able to select text, click on the Editor text. I downgraded to Spyder3, and I could do it.

Then I tried to run Spyder4 with sudo, and I was able to use the mouse on the Editor

### What steps reproduce the problem?

1. Install Spyder 4 with pip3
2. Try to use editor with no results
3. Install Spyder 3
4. Use the editor succesfully
### What is the expected output? What do you see instead?
Click on the editor text, select it... But I am not able to do it

**Comment by ccordoba12** [comment]
> Install Spyder 4 with pip3

Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.

**Comment by agustinvo** [comment]
Hi,

I found that I had PyQt5 with version 5.12. Downgrading to 5.9 solved the problem.
