### ISSUE TITLE
Cache searches in the Find pane

### ISSUE THREAD

**Issue by m-bouville** [spyder-ide/spyder#11669]
I sometimes do a search in files, typing the beginning of the name of a variable, subroutine, etc. When I get too many results, I use a longer input (just like anybody). Then the search restarts from scratch, taking several seconds even though it could just treat the results of the previous search as a short list of candidates.

**Comment by goanpeca** [comment]
Hi @m-bouville it does sound like a reasonable request, however due to the way the plugin is written it would probably require more than just some simple changes to get this working properly/

---

@impact27 what do you think about this?

**Comment by impact27** [comment]
I am not familiar with this plugin, but I could see a 
`if old_request in new_request:`

**Comment by ccordoba12** [comment]
We talked with @andfoy about it a couple of months ago. I think this would be a really nice enhancement to the Find plugin.

We'll take a look at it for 4.2

**Comment by ccordoba12** [comment]
I remember we thought about this back in the day and concluded that it's not so easy to implement. A better solution would be to make searches really fast, so that the user don't see any delay between consecutive ones.

We could do that with `ripgrep`, as described on issue #20595. So, I'm going to close this issue in favor of that one.
