### ISSUE TITLE
Open/edit variable 'object' in new tab rather than new window

### ISSUE THREAD

**Issue by gmanville** [spyder-ide/spyder#11973]
#11950  Problem Description
This is not so much an issue as a question about functionality within Spyder 3.3.6. I've searched the issues on here and also elsewhere online before raising this issue, but apologies if I've missed it!

Quite simply, double-clicking on an 'object' in the variable explorer used to open the 'object' as a new tab within the same window. Now however when I double click on an 'object' it opens as a new window. Is there a way of reverting back to opening/editing variables in a new tab, please?

Again, apologies if I've not followed the required procedure for raising an issue - I'm fairly new to Spyder and these forums!

Cheers

Version: Anaconda Navigator 1.9.12, Spyder 3.3.6

**Comment by ccordoba12** [comment]
> Quite simply, double-clicking on an 'object' in the variable explorer used to open the 'object' as a new tab within the same window.

That has never the case, at least we don't provide that functionality in Spyder itself.

I think I saw something like that in macOS, but that depends on how its window manager handles Spyder windows and when it thinks it can group them together. However, I don't know if that functionality is still available because I don't use macOS.

**Comment by zhizhenw** [comment]
We have the same issue in mac as shown below. Afterwards is solved by `sudo spyder`. Just post here if anyone has the same issue.

![image (2)](https://user-images.githubusercontent.com/58783520/135487775-9594e557-feb1-4396-aac5-7ee8e7045ab6.jpg)

**Comment by vikyathshirva** [comment]
@zhizhenw did you get it to open in a new window? how did you do it?

**Comment by TylerHext** [comment]
> @zhizhenw did you get it to open in a new window? how did you do it?

I had this issue when I switched to a new laptop, macOS Monterey, Spyder preferred to open DataFrames in a tab rather than a window which would resize my entire window. Basically the opposite of this topic, but posting the solution as I ended up here while trying to solve it. 

**System Preferences** -> **General** -> **Prefer tabs: Never**

**Comment by ananvodo** [comment]
Hi @TylerHext, Your option did not work for me. I set it up as always, given that I want the opposite you want.
Any suggestions? For some reason variables opening in windows and not in tabs, just started happening. I have the last spyder version 5.3.3, and my MacOS is  Monterrey version 12.6
