### ISSUE TITLE
spyder-kernels dependency not correctly detected for dev version

### ISSUE THREAD

**Issue by trougnouf** [spyder-ide/spyder#12002]
Dependencies are not correctly detected when the installed version has a string after the last number. 
In this case I am trying to use the git version of spyder and spyder_kernels, the required version of spyder_kernels is ">=1.9.0;<1.10.0" and it is not satisfied by "2.0.0.dev0".

I believe this has to do with utils/programs/check_version.

Reproducible w/ Arch AUR packages python-spyder-kernels-git and spyder3-git (there are no official spyder4 packages on Arch atm.)

**Comment by sylvain-bougnoux** [comment]
I had the same issue, it is because spyder imports spyder_kernel from `external-deps/spyder-kernels` and not from the pip installation (which for me is 1.9.0). 

It is definitely not the good solution but removing the folder `external-deps/spyder-kernels` & all `__pycache__`  work for me... until the next git pull.

**Comment by ccordoba12** [comment]
> Dependencies are not correctly detected when the installed version has a string after the last number.

I haven't had time to update our git subrepo, that's all.

> It is definitely not the good solution but removing the folder external-deps/spyder-kernels

If you want to use Spyder from git, please **do not** do that ever again. It's there for a reason. Then people wonder why things break so badly.
