### ISSUE TITLE
Dynamic sizing makes TextEditor windows too small

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder#12202]
It seems that the dynamic sizing introduced in PR #10976 makes some TextEditor windows too small. In PR #12094 and spyder-ide/spyder-unittest#139 we need to resize the TextEditor window. On the other hand, TextEditor windows opened by the Variable Explorer does seem to get the proper size. I don't know what causes the difference.

**Comment by ccordoba12** [comment]
I agree that this is very odd @jitseniesen.

@dalthviz, please take a look at this one.

**Comment by StefRe** [comment]
In order to get the dynamic sizing you'll have to explicitely call the `show()` method on the text editor (in  spyder-ide/spyder-unittest#139 I wrote that this wouldn't work but that was just a silly error of mine - I had commented it out in `BaseDialog` for testing purposes and then forgot about it). So everything works fine when you call `show()`.

**Comment by dalthviz** [comment]
Thanks for the clarification @StefRe ! 

@ccordoba12 @jitseniesen can we close this one then?

**Comment by jitseniesen** [comment]
>  can we close this one then?

I think so.
