### ISSUE TITLE
View variable explorer supported objects in the object explorer

### ISSUE THREAD

**Issue by eervin123** [spyder-ide/spyder#12215]
## Problem Description
Currently there is no way to view the `dtypes` of `DataFrame` in `Object Explorer` for example in read only mode to see the `dtypes` of each of the columns of a `DataFrame`.  Because `Object Explorer` only populates attributes about objects without a specific editor inside Spyder, and `DataFrame` has the `DataFrameEditor` there is no way to view object attributes using the `Object Explorer`.  This could be a helpful addition to the `Object Explorer`.  

[Here is an example](https://www.spyder-ide.org/blog/spyder-variable-explorer/view-object-explorer.png) of what you can see about a `DataFrame`  If the `DataFrame` is selected the wonderful `DataFrameEditor` comes up. but the user is not able to simply see the `dtypes` of the columns. [Here is the editor view. ](https://www.spyder-ide.org/blog/spyder-variable-explorer/multi-index-support.png)

This was my first "issue" posted, @dalthviz suggested I post.  Hopefully, it was helpful and cogent.

## Versions

* Spyder version: Spyder 4.1.1
* Python version: 3.7
* Qt version: 
* PyQt version: 
* Operating System name/version: Mac OS 10.15.3

**Comment by ccordoba12** [comment]
@dalthviz, @eervin123, I don't understand very well how to add this functionality. Could you explain better how and/or in what viewer we should add it?

**Comment by dalthviz** [comment]
@ccordoba12 I think the petition is to enable showing for example the `dtypes` in the object explorer when a `DataFrame` is open using it. Currently, when you open a`DataFrame` the only thing you see is an entry for the `DataFrame` but no its attributes (like the `dtypes`):

Example `DataFrame` snippet:

```python
import pandas as pd
df = pd.DataFrame({'float': [1.0],

                   'int': [1],

                   'datetime': [pd.Timestamp('20180310')],

                   'string': ['foo']})
```

![image](https://user-images.githubusercontent.com/16781833/78820087-da25f080-799c-11ea-8009-f7ac8ecbf015.png)

This could be caused since we are only adding the attributes of the object if Spyder doesn't have an editor for the object type:

https://github.com/spyder-ide/spyder/blob/f04d357dc0d19fa8ece25b1d922e8245cb20452a/spyder/plugins/variableexplorer/widgets/objectexplorer/tree_model.py#L286-L290

If I remove the validation I can navigate through the attributes of the `DataFrame` and see, for example, the `dtypes` of the columns:

![image](https://user-images.githubusercontent.com/16781833/78821333-ed39c000-799e-11ea-980d-ab7976742e8f.png)

**Comment by eervin123** [comment]
Thank you @dalthviz much more articulate than I could have been.

**Comment by ccordoba12** [comment]
> This could be caused since we are only adding the attributes of the object if Spyder doesn't have an editor for the object type

Ok, I see. Then I think we should remove that restriction, given that it's useful to show the attributes of our currently supported objects, as @eervin123 pointed out.
