### ISSUE TITLE
Does Spyder 4.1.2 has incompatibility with Pyqt5 5.14? 

### ISSUE THREAD

**Issue by LuisAzabache** [spyder-ide/spyder#12238]
I got this issue trying to install pyqt5 5.14.
![image](https://user-images.githubusercontent.com/55934486/78862708-9d3e1600-79fd-11ea-9136-1801e78f026d.png)

**Comment by ccordoba12** [comment]
No, it's not. Spyder is compatible with PyQt 5.12, not 5.14, sorry.

**Comment by stonebig** [comment]
a simple option to block spyder from generate unwanted issue report when using a not the  "supported" list of package/distro would be cool.

current option otherwise seems to comment lines 379 to 382


![image](https://user-images.githubusercontent.com/4312421/79040676-6e38c780-7bea-11ea-934f-a6949f7b0a9e.png)
