### ISSUE TITLE
No works select mouse text and no work scroll mouse wheel in editor. Dark theme has problems.

### ISSUE THREAD

**Issue by fianitnz** [spyder-ide/spyder#12367]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
No works select mouse text and no work scroll mouse wheel when cursor over text. 
Scrolling mouse wheel over scrollbar and line numbers bar works.
Can make select text if you fall into the pixel between numbersbar and text area.
![spy iss](https://user-images.githubusercontent.com/11841530/79560070-89567c00-80af-11ea-826a-9342847fe425.png)
![spy iss2](https://user-images.githubusercontent.com/11841530/79560073-89ef1280-80af-11ea-9c39-14232617e86a.png)
![spy iss3](https://user-images.githubusercontent.com/11841530/79560075-8a87a900-80af-11ea-9bd5-d724f4629d88.png)
![spy iss4](https://user-images.githubusercontent.com/11841530/79560079-8bb8d600-80af-11ea-8a86-00d8095de366.png)

### What steps reproduce the problem?

1. Select text in editor text area
2. Try to scroll text in text area(if the text is large)

### What is the expected output? What do you see instead?

Select text.
Scroll text.
Nothing.

## Versions

* Spyder version:  4.1.2 4.1.1 4.1.0 4.0.1 4.0.0 (3.3.6 works)
* Python version: 3.7.5
* Qt version: 5.12.4
* PyQt version: 5.12.3
* Operating System name/version: Linux 5.3.0-46-generic, Ubuntu 19.10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.2.2 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.6.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.6.5 (OK)
pygments >=2.0                 :  2.4.2 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.6.0 (OK)
qtconsole >=4.6.0              :  4.6.0 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
sphinx >=0.6.6                 :  2.2.1 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  1.18.0 (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by fianitnz** [comment]
Preferences >> Appearance >> Main interface: interface theme "Light" fix this. Dark theme brings the problem back.

**Comment by ccordoba12** [comment]
This looks like a problem with the pip PyQt5 packages or your Linux distro, because I can assure the dark theme is working as expected in Anaconda.

Since we don't have a way to even reproduce this, we only have two recommendations for you:

1. Keep using the light theme with a dark syntax highlighting theme for the editor.
2. Switch to Anaconda.

**Comment by danhamill** [comment]
I also have this problem on windows 10.0.17134 Build 17134

```
# Name                    Version                   Build  Channel
spyder                    4.1.4                    py37_0
spyder-kernels            1.9.2                    py37_0
pyqt5                     5.12                     pypi_0    pypi
pyqt5-sip                 4.19.19                  pypi_0    pypi
python                    3.7.4                h5263a28_0
```

**Comment by 60south** [comment]
Same problem, researched the heck out of it. Running WSL2 on Windows 11, the mouse works on fresh install of Spyder, or after using --reset, but otherwise does not work.

The problem seems to be centered around the configuration line "Windows/State" in the file 'transient.ini', which generally lives in ~/.config/spy-py3/config. The value for the windows state is updated when you exit Spyder, presumably so it will restart in the same state when you fire it up again. But something about it disables the mouse. If you edit transient.ini and delete the Windows/State content, Spyder restarts fine and the mouse works, although you lose all your preferences and settings.

My Solution: Put Spyder in full screen mode, then back out of full screen. This can be done with either a menu option (the keyboard still works, use the Alt key and arrows) or, easier, the 'f11' button on the keyboard.

YMMV.

**Comment by crevicehates** [comment]
> The problem is centered around the configuration line "Windows/State" in the file 'transient.ini', which generally lives in ~/.config/spy-py3/config. The value for the windows state is updated when you exit Spyder, presumably so it will restart in the same state when you fire it up again. But something about it disables the mouse. If you edit transient.ini and delete the Windows/State content, Spyder restarts fine and the mouse works, although you lose all your preferences and settings.
> 

I'm using wsl too and I figured it out because of your comment. For me, it was the window/position updating to (-32,-32) on exit. I fixed it by running a bash script that changes it back to (0,0) before running spyder.


First I changed the name of `spyder` to `spyder01`
```
mv ~/miniconda3/envs/<your env name>/bin/spyder ~/miniconda3/envs/<your env name>/bin/spyder01
```

Then I made a bash script named `spyder`
```
#!/bin/sh

#makes the value (0,0), I'm not sure if it works without sudo
sudo sed -i '/window\/position = (.*)/c\window/position = (0,0)' ~/.config/spyder-py3/config/transient.ini ;

#runs the original spyder
exec ~/miniconda3/envs/<your env name>/bin/spyder01 ;
```

Then I made the new 'spyder' executable
```
sudo chmod u+x /miniconda3/envs/<your env name>/bin/spyder
```

If you use this, you will need use it in every environment.
