### ISSUE TITLE
Autosave interval setting doesn't take effect at all.

### ISSUE THREAD

**Issue by hongyi-zhao** [spyder-ide/spyder#12422]
Hi,

Git master spyder version running directly without installation. I set the  Autosave interval = 2 secs,
but it seems it doesn't take effect at all.  After the duration, I still need to click on the save button to save the file?

Any hints?

Regards

**Comment by jitseniesen** [comment]
Hi, as it says in the Preferences, what the autosave feature does is to "automatically save a copy of files with unsaved changes". This means that it does not overwrite the file that you opened. Instead, it saves a copy of the file in a different directory so that it can be recovered after a crash. Spyder will only save to the file that you opened if you save it manually (or if you run the file).

**Comment by hongyi-zhao** [comment]
Thanks, got it.
