### ISSUE TITLE
HPC install with pip

### ISSUE THREAD

**Issue by Mon-ius** [spyder-ide/spyder#12542]
I am currently working with HPC.  Unfortunately, the HPC node with GPU doesn't have the anaconda module to load. So I would like to know the pip version requirement for it to install spyder.

**Comment by ccordoba12** [comment]
I think your pip version needs to be at least 19.0.2 to install Spyder correctly.

**Comment by Mon-ius** [comment]
pip 19.2.3 from /rds/bear-apps/2019b/EL7-power9/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/site-packages/pip-19.2.3-py3.7.egg/pip (python 3.7)

**Comment by Mon-ius** [comment]
ERROR: Could not find a version that satisfies the requirement pyqtwebengine<5.13; python_version >= "3" (from spyder) (from versions: 5.14.0)
ERROR: No matching distribution found for pyqtwebengine<5.13; python_version >= "3" (from spyder)

**Comment by Mon-ius** [comment]
Also, tried the miniconda to install the requirements. The pyqt doesn't support the `linux-ppc64le ` architecture.

**Comment by ccordoba12** [comment]
Right, you can't install Spyder in that architecture, either using Miniconda or pip, sorry. It's simply not supported.

**Comment by Mon-ius** [comment]
But, it's IBM power9, I found it could install pyqt5 with pip while loaded the qt5 module. And there is only one error that PyQtWebEngine. It's separately installed with PyQt5. 

I first installed the PyQt5, then the PyQtWebEngine.
```

Collecting PyQtWebEngine
  Using cached PyQtWebEngine-5.14.0.tar.gz (47 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /rds/homes/y/yxz1148/.conda/envs/cc/bin/python /rds/homes/y/yxz1148/.conda/envs/cc/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp05uhajpm
         cwd: /tmp/pip-install-9hboqzn1/PyQtWebEngine
    Complete output (6 lines):
    Querying qmake about your Qt installation...
    /rds/bear-apps/2019b/EL7-power9/software/Qt5/5.13.1-GCCcore-8.3.0/bin/qmake -query
    These bindings will be built: QtWebEngineCore, QtWebEngine, QtWebEngineWidgets.
    Generating the QtWebEngineCore bindings...
    _in_process.py: Unable to find file "QtCore/QtCoremod.sip"
```

**Comment by ccordoba12** [comment]
> But, it's IBM power

That architecture is only partially supported by Anaconda.

> I first installed the PyQt5, then the PyQtWebEngine.

There are no wheels for PyQtWebEngine, therefore pip is trying to compile that package in your computer and fails. Unfortunately that's not possible because that package can't be compiled in PowerPC.

----

If it's really critical for you to have Spyder in PowerPC and are willing to pay for support to have it, you could talk to @rgommers, from Quansight Labs, about it. He could set up a [community work order](https://labs.quansight.org/blog/2019/05/community-driven-opensource-funded-development/) with us so we can make Spyder work without PyQtWebEngine.
