### ISSUE TITLE
Spyder Launch Error (ERROR:network_change_notifier_win.cc(156)] WSALookupServiceBegin failed with: 8)

### ISSUE THREAD

**Issue by meiji477** [spyder-ide/spyder#12731]
Problem Description

Hi

I have installed the latest 64 bit anaconda navigator version on my laptop with windows 10 pro as a operating system. Whenever I launch spyder from the anaconda navigator following message shows up

[740:6504:0514/000841.771:ERROR:network_change_notifier_win.cc(156)] WSALookupServiceBegin failed with: 8

Even after that, spyder can still run and it seemed fine. This happens every time when I launch the spyder. I have also reinstall anaconda navigator multiple times but the issue persists. The prompt message picture is as follows

![Spyder Launch error](https://user-images.githubusercontent.com/65309765/81858825-c19d8d00-957d-11ea-95aa-ae89628f0f8e.jpg)

Please help if any one has any recommendation to resolve this error

Thanks.

**Comment by dalthviz** [comment]
Hi @meiji477 this seems like a duplicated of #11252  we haven't manage to reproduce this but seems like it doesn't affect the Spyder functionality.

However, just to check if we can get more info and understand was going on here:

* What version of Spyder are you running? Maybe an update could help (current release version is `4.1.3`)
* Could you try to run Spyder from the Anaconda Prompt? Run `spyder --debug-info verbose` activating the corresponding env before.
* After running from the Anaconda Prompt, do you see any error message different from the one Anaconda Navigator shows?
* You could also try to run Spyder from the shortcut (maybe to check if you experience a different behavior).

Any new info in order to understand this is greatly appreciated :)

Note aside, seems like the error message is common in games that are being run from Wine, quite strange that starting Spyder is causing this kind of error message

**Comment by dalthviz** [comment]
Closing due to lack of response.
