### ISSUE TITLE
Move IO plugins to Variable explorer new API

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#12761]
- [ ] remove [spyder imports](https://github.com/spyder-ide/spyder-kernels/blob/506a25ca78de0175694f652bb2617fba5fb98ac5/spyder_kernels/utils/iofuncs.py#L497)
- [ ] Add plugin registration on spyder-kernels

**Comment by impact27** [comment]
There is two main ways to add code to spyder kernel to interact with a plugin:
 - change the code of spyder-kernels (have spyder-kernels plugins that corresponds to the spyder counterpart)
 - "Inject" code into ipython kernel 
I think the injection is not the nicest way to do this and we should probably think about an API to do that.

**Comment by goanpeca** [comment]
>change the code of spyder-kernels (have spyder-kernels plugins that corresponds to the spyder counterpart)

## IO Plugins (Variable explorer)
The need from plugins comes specifically for how the variable explorer deals with new types (install networkx on the kernel and be able to have a quick `Plot` when right clicking.

Since this is tied to installing new packages, that is why the "code inject" may fall short, users actually need to install things that will most likely install new dependencies on the kernel.

## Other control stuff

For "control" things, injecting should be ok, and and API would make things cleaner.

## Spyder side dependencies.

So on the Spyder side a new Type must be added to handle the UI (like displaying new menus based on new types, but it should not be necessary to install networkx (following the example above)

## The workflow

How would a user do this? have 1 package and two install methods using extras (for pip)?

Ideas 🙃 ?

**Comment by impact27** [comment]
The kernel and spyder might not be on the same machine, so the code should be installed independently. As you note, code injection is quite limited and can not have any dependency.
I think the solution is to split the plugin into two, so you would have to run on your local machine:
`pip install spyder-pluginA`
and on the machine where spyder-kernels is running:
`pip install spyder-kernels-pluginA`
Then the frontends check if the correct version of the kernel plugin is installed. If not it informs the user that he needs to install the correct version of the kernel plugin (probably need a 1-1 correspondence.)

**Comment by goanpeca** [comment]
>pip install spyder-pluginA
>and on the machine where spyder-kernels is running:
>pip install spyder-kernels-pluginA

Yeah that seems like the cleanest way moving forward. Having two packages is a bit annoying so trying to come up with ideas how this could be simplified.

with pip one could do

To put an example:

`pip install spyder-networkx`
`pip install spyder-networkx[kernel]`

Spyder will always have spyder-kernels installed locally + maybe on another machine, right?

I can think to make just one package, we could detect stuff on the env?

if `spyder` and `spyder-kernels` is found, install both kernel side and frontend side. If only `spyder-kernel` is found install only `kernel side part``

Maybe a bit of magic, but that would make writing these extensions way easier.

**Comment by ccordoba12** [comment]
> To put an example:
>
> pip install spyder-networkx
> pip install spyder-networkx[kernel]

That won't work because conda packages don't have this functionality.

A much better way to solve this is simply by asking people to add some methods with metadata to their objects, like `__repr_spyder__` to display a representation of the object in the Variable Explorer, or `__plot_spyder__` with the code necessary to generate a plot. So objects will tell Spyder that extra info is available in the dictionary generated by `nsview` and Spyder will decide what to do about it (e.g. show an extra `Plot` entry in the context menu of an object).

However, none of that is necessary right now to solve this issue. Instead, @goanpeca please simply move their code to Spyder-kernels and make it work with the `get_3rd_party_funcs` (present in `utils/iofuncs.py`) on it. Perhaps the right solution is for objects to also declare how Spyder can load and save the data associated with them (by adding `__load__spyder__` and `__save_spyder__` to them), but that's something that requires more discussion.

**Comment by ccordoba12** [comment]
This was done already, so closing.
