### ISSUE TITLE
Conflict python between Spyder, Octave and TensorFlow

### ISSUE THREAD

**Issue by IvanGas** [spyder-ide/spyder#12899]
Hello,
I am very new of python environment.
After some time spent learning python through Anaconda on Windows PC (in particular with Spyder), I also decided to learn Tensorflow, always in Spyder. So, I created a new dedicated environment for TF with the v3.6.9 and v1.17.2, respectively, for python and numpy.

I have never had problems running codes that require TF import with this configuration.
However, after some time, to use the Octave symbolic library I had to download Python from Microsoft Store. The downloaded version were 3.8.3 and I also installed the pip package from cmd. The symbolic package in Octave works, but from that moment when I run a code in Spyder that requires the import of tensorflow, I get the following error:

```
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devd_ocs/user/trou_bleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.6 from "C:\Users\ivang\.conda\envs\tensorflow_cpu\python.exe"
  * The NumPy version is: "1.18.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named `'numpy.core._multiarray_umath_'
```

As suggested, checking my PATH and PYTHONPATH environment variables I obtained the paths in the attached picture. 
![PATHS](https://user-images.githubusercontent.com/47055464/83285629-d5342f00-a1de-11ea-9b45-663aa8ab36b7.png)
These environment variables were not created by me, but by Python at the time of its stand-alone installation.

I understand that the problem is related to the different versions of python installed, but why this conflict happens if I created a dedicated environment in Anaconda, as explained at the beginning of the post? How can I solve this conflict using both TF in Spyder and the library in Octave on the same PC?

I tried to uninstall Python 3.8 but the environment variables remain and also the directory in C:\Program Files\Python38\ where site packages are installed.

Thank you so much for the help,
IG

**Comment by juanis2112** [comment]
Hi @IvanGas. Thanks for reporting this. The last 2 entries in your PATH belong to the Python in your Octave installation and are the ones causing the issue. I recommend checking this link https://www.computerhope.com/issues/ch000549.htm so you can manually edit your PATH and remove them. However, this might break your Octave.

**Comment by juanis2112** [comment]
Another possible solution might be creating a file with this code:

```python
import os 
path = os.environ['PATH'].split(os.pathsep)
path = path[:-2]
os.environ['PATH'] = os.pathsep.join(path)
```

and add it here:

![Screen Shot 2020-05-29 at 5 11 36 PM](https://user-images.githubusercontent.com/18587879/83309685-8cc14500-a1cf-11ea-8b03-4e557bb65081.png)

so that the two last entries are deleted (locally) every time you open spyder.

**Comment by juanis2112** [comment]
In any of the two cases, you need to restart spyder so that the changes are applied.

**Comment by IvanGas** [comment]
Dear @juanis2112, thank you for your reply.
I tried the solution #2 before, but it doesn't work. So I tried to manually delete the two paths which can cause the problem from the "PATH" environment variable but I noticed a very strange thing. As you can see from the image shown here, the paths of the environment variable "PATH" are different from what I ask Spyder to print (see the first picture reported in the issue above).

![Environmental_variables](https://user-images.githubusercontent.com/47055464/83349458-5bfb2000-a335-11ea-805c-834187e576cb.png)


There are not, for instance:
`C:\Program Files\Python38\Lib\site-packages\numpy\.libs`!!!

**Comment by IvanGas** [comment]
Instead i see that there is an environment variable called "PYTHONPATH" with value:

`C:\Program Files\Python38\Lib\site-packages`

Is it possible that this variable creates the conflict?

**Comment by juanis2112** [comment]
Yes, it seems that the path ``C:\Program Files\Python38\Lib\site-packages`` is what is breaking spyder.  Try deleting it from your PATH, along with ``C:\Program Files\Python38\`` and``C:\Program Files\Python38\Scripts``

**Comment by IvanGas** [comment]
Dear @juanis2112, thanks for your help. I confirm that the problem was related to PYTHONPATH environment variable... However, as expected, Octave's symbolic package can no longer be used. Is there a way or configuration to use both TF in Spyder and symbolic in Octave?

**Comment by juanis2112** [comment]
If the problem was with the PYTHONPATH, I suggest adding back the paths you deleted and change the code I sent you for the startup to:
```
import os
os.environ[‘PYTHONPATH’] = “”
```
so whenever spyder starts, it deletes the value of this variable locally and hopefully your Octave still works.

**Comment by juanis2112** [comment]
Let me know if this works, or if there is something else I can help you with

**Comment by IvanGas** [comment]
Octave works if the PYTHONPATH variable is present whereas TF does not work.

So, I tried to add back PYTHONPATH at my env. variables and change the startup code for Spyder, as suggested, but unfortunately tensorflow does not work yet.

**Comment by juanis2112** [comment]
Okay, so I think if we join both approaches it might fix it, but as we have been back and forth I'm not sure it will work. So I suggest this:

Try the following code in the startup code
```
import os
os.environ['PYTHONPATH'] = ""
path = os.environ['PATH'].split(os.pathsep)
path =  [ x for x in path if "38" not in x ]
os.environ['PATH'] = os.pathsep.join(path)
```

So that we delete locally not only the PYTHONPATH but also the paths related to the Python that belongs to the OCTAVE installation. 

In the meantime, I will get a new environment with your set up to see if I can reproduce the error, in case this doesn't work and figure out a new approach.

**Comment by IvanGas** [comment]
Thanks for your help and especially for you time. Nevertheless, the same error appears; but in this last case I see that when I start spyder a variable called path is present (in the previous attempts was not present) and its value is:
![path](https://user-images.githubusercontent.com/47055464/83779813-b2959080-a68c-11ea-9747-d4a516dfa07b.png)

A clarification: I know that for evaluation of some tensorflow scripts I need to allow for the OpenMP library to be loaded multiple times. 
To do this, I add at the beginning of each script:

```
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'
```

Can it be the reason of the problem?
If you are interested in my setup, I can send you my tensorflow environment's folder (e.g. through e-mail).

**Comment by juanis2112** [comment]
I don't think sending your environment's folder will work, but it would be really helpful if you send me the .txt of your environment. To do this, please run the following in your anaconda prompt after activating your environment:
``conda env export > environment.txt``
This will generate a file called environment.txt in the folder where you are located while running this command. You can drag that file to upload it here in one of the comments.

**Comment by IvanGas** [comment]
As requested, you can find the .txt of my environment in attacched.

[environment.txt](https://github.com/spyder-ide/spyder/files/4742291/environment.txt)

**Comment by CAM-Gerlach** [comment]
Hey, so this is a pretty tricky issue that us Spyder developers struggle with too. As @juanis2112 explained, Spyder is using your Anaconda Python (as you intend), but then tries to load the Numpy 1.18 installed alongside Octive due to the `PYTHONPATH`, which takes precedence over the `PATH`. The Octave-Python-related entries in your `PATH` actually don't directly contribute to the problem because they are at the end, and the Anaconda entries at the beginning override them (which you don't see in your system `PATH` variable outside of Spyder since Anaconda adds them dynamically).

However, in your case there is a pretty straightforward solution, which I've confirmed works with Octave, Symbolic, and Anaconda: Uninstall the Python you installed and just point Symbolic to Anaconda's own Python and SymPy instead, following [Symbolic's recommended install procedure](https://github.com/cbm755/octsympy/wiki/Notes-on-Windows-installation).

----

To do this:

1. Uninstall the Python 3.8 you installed from the Windows store, and any other stray Pythons on your system
2. Delete the `PYTHONPATH` environment variable and the Python38-related `PATH` entries from Windows control panel
3. Delete the directories `%ProgramFiles%/Python38` and `%appdata%/python` if they still exist.
4. Reboot your machine
5. In Octave, enter the command `setenv PYTHON C:/ProgramData/Anaconda3/python.exe` to point Symbolic to your Anaconda Python
6. Start and use Symbolic as you normally would (`pkg load symbolic` then `syms x`)

To avoid having to repeat step 5 every time you start Octave, in Control Panel create/set the `PYTHON` system environment variable to `C:\ProgramData\Anaconda3\python.exe` (or whatever path worked in Step 5) and reboot your machine, and you'll be good to go. Thanks, and best of luck!
