### ISSUE TITLE
Multiple qt versions 

### ISSUE THREAD

**Issue by aourednik** [spyder-ide/spyder#12983]
## Problem Description

Spyder stopped working on MacOS (High Sierra, then Mojave).
Error report in terminal :
"You might be loading two sets of Qt binaries into the same process."

Several classes failed to load. Example: 

"objc[56211]: Class QMacAutoReleasePoolTracker is implemented in both /usr/local/opt/qt/lib/QtCore.framework/Versions/5/QtCore (0x11edd5060) and /usr/local/lib/python3.7/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (0x12886d200). One of the two will be used. Which one is undefined."

### What steps reproduce the problem?

1. Install python 3.7 with Hombrew
2. Install spyder with pip3 (pip3 install spyder)
3. Launch spyder from terminal with spyder3 command

### What is the expected output? What do you see instead?

Spyder interface should launch. Instead, terminal throws errors

**Comment by steff456** [comment]
Hi @aourednik,

Right now it seems that you have a problem with your installation. We don't support pip installation, instead we recommend to use anaconda, for further information please see https://docs.spyder-ide.org/installation.html
Please note that you can download the latest anaconda version from the official webpage instead of using homebrew
