### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by shallyboy** [spyder-ide/spyder#13152]
console not loading even after installation of ipykernel and cloudpickle in venv. interpreter of venv different from that use by spyder.
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by ccordoba12** [comment]
Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.
