### ISSUE TITLE
The current file cannot be closed because it is in debug mode. 

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#13189]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

When trying to close a file, The file doesn't close, and the following message appears:
`The current file cannot be closed because it is in debug mode. `

But I am not debugging. Even if I was, I find it annoying to not be allowed to close a file if I want to.

### What steps reproduce the problem?

I am not sure, I will update if I find a way.

### What is the expected output? What do you see instead?
I expect the file to close when I press the cross.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: master
* Python version:  3.7
* Qt version: 
* PyQt version: 
* Operating System name/version: macOS

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by impact27** [comment]
@dalthviz what is the rationale behind preventing a file from closing? I think this was introduced in PR #10610

**Comment by impact27** [comment]
PS: with PR #13190, you can always go to the current position

**Comment by dalthviz** [comment]
Hi @impact27 I guess we did this to be more clear about the state of the file, something like "hey, this file is being debugged" (maybe @ccordoba12 can give some more reasons about the new behavior).

However, seems like this is affecting any file instead of just the one that is actually being debugged, so we need to at least fix that (I could give it a check).

Also, taking into account your feedback, actually such behavior could feel kind of intrusive for some users so should we maybe leave it as an optional feature?

**Comment by impact27** [comment]
> However, seems like this is affecting any file instead of just the one that is actually being debugged, so we need to at least fix that (I could give it a check).

I will try to replicate this behaviour, I think I used post mortem

> Also, taking into account your feedback, actually such behavior could feel kind of intrusive for some users so should we maybe leave it as an optional feature?

I think this is a great suggestion. What do you think the default should be?

**Comment by dalthviz** [comment]
> I will try to replicate this behaviour, I think I used post mortem

Awesome, thanks for the help @impact27 !

> I think this is a great suggestion. What do you think the default should be?

Probably the default could be showing the message indicating that the file is being debugged (and also informing there how to change the behavior in the preferences if needed). What do you thing @ccordoba12 ?

**Comment by ccordoba12** [comment]
> and also informing there how to change the behavior in the preferences if needed

I really don't think we should add an option in Preferences for this. If you want to close the file, you simply need to stop debugging it. That way the user removes the connection between the debugging console and that file, so they can use it for other purposes.

I decided to do things like that because users can have the same file being debugged in different consoles, and being located in different lines in each of them. So when they move to one of those consoles, Spyder will correctly update the blue arrow that indicates the line Pdb is placed in.

This is a UX problem most other IDEs don't have (because they use a single console), but I think it's important to maintain the current design in our case.

**Comment by impact27** [comment]
> > and also informing there how to change the behavior in the preferences if needed
> 
> I really don't think we should add an option in Preferences for this. If you want to close the file, you simply need to stop debugging it. That way the user removes the connection between the debugging console and that file, so they can use it for other purposes.
> 
> I decided to do things like that because users can have the same file being debugged in different consoles, and being located in different lines in each of them. So when they move to one of those consoles, Spyder will correctly update the blue arrow that indicates the line Pdb is placed in.
> 
> This is a UX problem most other IDEs don't have (because they use a single console), but I think it's important to maintain the current design in our case.

In my case, the problem I have is that I only need to infrequently check on the file, and that I tend to leave the console open while debugging. It is nice to have the file open but not necessary. It can be frustrating to try to close a file and be told no without a good reason. If closing the file would create a loss of data it makes sense to ask if the file should be closed first. But in this case I want to close the file and I am being told no in a discreet way in the console. I am not necessarily looking at the console when working with the editor. 

So my point of view is that If I am primarily using the console for debugging, having the file open in the editor is a nice to have, but preventing me from closing it is very frustrating. I don't see a good reason for preventing me from closing it even if I am debugging it.

**Comment by impact27** [comment]
Closed in #12134
