### ISSUE TITLE
The arrow indicates indent？

### ISSUE THREAD

**Issue by 33RoboTcan** [spyder-ide/spyder#13362]
## Problem Description
After i make the Indent Line visible

My tab is "...",but the code that i copy is "->"，if i want to make some change,it must be "...",and consle will show "IndentationError: unindent does not match any outer indentation level".
So I want to know if spyder have any function can change "->" to "..."

Thank you!

### What steps reproduce the problem?

maybe this code can have "->"

class Button():
	def __init__(self, screen, text, x, y, color, enable):
		self.screen = screen
		self.width = BUTTON_WIDTH
		self.height = BUTTON_HEIGHT
		self.button_color = color
		self.text_color = (255, 255, 255)
		self.enable = enable
		self.font = pygame.font.SysFont(None, BUTTON_HEIGHT*2//3)
		      
		self.rect = pygame.Rect(0, 0, self.width, self.height)
		self.rect.topleft = (x, y)
		self.text = text
		self.init_msg()

### Paste Traceback/Error Below (if applicable)
![图片](https://user-images.githubusercontent.com/50979817/88270319-0a08c200-cd08-11ea-843e-54e124466aa0.png)
![图片](https://user-images.githubusercontent.com/50979817/88270042-9e265980-cd07-11ea-909a-61af7bf26c2e.png)
![图片](https://user-images.githubusercontent.com/50979817/88270031-9961a580-cd07-11ea-9dab-128e7b0dea80.png)

## Versions

* Spyder version: 3.2.6
* Python version: 3.6
* Operating System name/version: win10

**Comment by andfoy** [comment]
Hi @33RoboTcan, from your screenshots, it seems that your are mixing Tabs (shown as ``→``) with Spaces, which is not allowed in any Python file (even outside Spyder). If you want to use Tabs instead of spaces to indent your code, you can set the option ``Tabulations`` in ``Preferences  → Editor → Source Code → Indentation characters``, otherwise, you'll need to convert your tabs into spaces.
