### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by MMS413** [spyder-ide/spyder#13478]
### What steps reproduce the problem?
These commands:
import pandas
import numpy

data = pandas.read_csv("nesarc_pds.csv", low_memory=False)

print(len(data))
print(len(data.columns))
### Paste Traceback/Error Below (if applicable)
Produced the following response:
In [2]: print(len(data.columns))
Traceback (most recent call last):

File "<ipython-input-2-edddc1643118>", line 1, in <module>
  print(len(data.columns))
  
NameError: name 'data' is not defined

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: Spyder (Python 3.7)
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by dalthviz** [comment]
Hi @MMS413 how did you run your code? Seems like you are running it line by line (in which case you need to run the previous lines too in order to execute correctly that line or at least have in the namespace of your console the variable `data`).

For a full file run you can use the `F5` shortcut or clicking the ![image](https://user-images.githubusercontent.com/16781833/89472886-1993fc00-d747-11ea-9a42-da0e25a4c0a7.png) in the toolbar.

Hope the little explanation above helps :)

**Comment by MMS413** [comment]
Thanks, @dalthviz !

**Comment by dalthviz** [comment]
Where you able to run your code @MMS413 ?

**Comment by MMS413** [comment]
Yes, thank you @dalthviz

**Comment by dalthviz** [comment]
Awesome closing this one then :+1:
