### ISSUE TITLE
Builtins can still be shadowed, causing kernel startup to fail, when a project is open

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#13519]
## Problem Description

Opened per discussion with @ccordoba12 . In Python 3.7+, the cwd is added to the `PATH` from which modules are imported, such that Python files named the same as standard library ones shadow them, which results in the kernel not being able to start if it requires it. This is a common error for new users and was partially fixed by removing the home directory, but this evidently does not work when a project is active, as Python modules in the project's root directory will still shadow standard library ones.

### What steps reproduce the problem?

1. Open a project
2. Create a file in the project directory with a name shadowing a stdlib module that the kernel uses, e.g. `code.py`
3. Restart the kernel

### What is the expected output? What do you see instead?

Kernel fails to start. Instead, working directory should be at the bottom of the `PATH` search order so that modules with conflicting names don't shadow builtins.

Example:

![image](https://user-images.githubusercontent.com/17051931/89961771-6163c900-dc08-11ea-9d71-28de047db1c2.png)

**Comment by jitseniesen** [comment]
I'm not sure this is a bug rather than a (Python) design choice ("we're all adults"). It does break things for users that intentionally shadow the standard library, though this is not a common use case. 

I definitely agree that this is confusing for new users. How about instead, we warn the user if they use a file name which shadows a standard library?

Did something change in Python 3.7 that you refer to this version?

**Comment by ccordoba12** [comment]
> How about instead, we warn the user if they use a file name which shadows a standard library?

i think that's hard because there are a lot modules in the standard library. Besides, it'd force us to keep track of new modules added in each release.
