### ISSUE TITLE
Kernel showing as connecting when spyder is launched. Issue gets fixed after closing and re launching it.

### ISSUE THREAD

**Issue by HariGovindSatheesan** [spyder-ide/spyder#13577]
Issue is when starting spyder , it is not connecting to kernel at times. Have to re launch spyder. Starting another kernel window or refreshing the kernel is not fixing the issue. Spyder is launched from anaconda.
![image](https://user-images.githubusercontent.com/29809037/90704813-1b190480-e2af-11ea-8e55-77805128382b.png)

**Comment by dalthviz** [comment]
Hi @HariGovindSatheesan could you provide more info about your installation (OS, dependencies, Spyder and Python version, etc)? Also, is any traceback being generated (in the internal console) or other place? Please provide as much info as you can since if we can´t reproduce the issue is difficult for us to help you.

Just in case you can check out [Troubleshooting Guide & FAQ](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) that could help too

**Comment by dalthviz** [comment]
Since no reply was done after a week I'm closing this one. If the issue persist feel free to reopen.
