### ISSUE TITLE
ValueError: `bins` should be a positive integer 

### ISSUE THREAD

**Issue by MMS413** [spyder-ide/spyder#13573]
#13570 Problem Description

Hello, I am using Python 3.7 via Spyder 3.3.6 (as part of the Anaconda suite) as part of a class I'm currently taking. (I'm new to Python, so I apologize in advance if the answer to resolving this error seems obvious.)
How do I move past this error?

### What steps reproduce the problem?

import pandas
import numpy
import seaborn
import matplotlib.pyplot as plt
data = pandas.read_csv('classdata_pds.csv', low_memory=False)

sub2['PACKSPERMONTH']=sub2['NUMCIGMO_EST'] / 20
c12 = sub2.groupby('PACKSPERMONTH').size()
print(c12)

sub2['PACKCATEGORY']=pandas.cut(sub2.PACKSPERMONTH, 0, 5, 10, 20, 30, 147)

### What is the expected output? What do you see instead?

Expect to see new bins for PACKSPERMONTH as defined above.
Instead receiving:  ValueError: `bins` should be a positive integer 

Thank you!
```

**Comment by dalthviz** [comment]
Hi @MMS413 seems like your error isn't related with Spyder but rater with the code you are trying to run. Seeing your code I don't see where you are defining the `sub2` variable neither you provide the whole traceback of the error.

However, seems like you are passing as the `bins` param  in the `cut` function the value `0` instead of a sequence of scalars (which maybe is what you are trying to do) like `[0, 5, 10, 20, 30, 147]`. For more info about the params that `pandas.cut` has, you can check the pandas docs: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.cut.html

I will close this one since is not related with Spyder but hope the info above helps :)
