### ISSUE TITLE
Find pane issues and details

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#13657]
Some issues and details that needed to be worked out in the Find pane

- [ ] The hamburger menu is not the same as in 4.x (some actions are not being listed)
- [ ] The label of the directory was changed (from `Search in:` to `Location`).
- [ ] A label that says `Search` was added to the combobox used to type search terms but the button already says `Search` on the right (so it is kind of redundant).
- [ ] In the Editor having a word selected and hitting `Cmd + Shift + F`/`Ctrl + Shift  + F` doesn’t automatically start a search.

**Comment by dalthviz** [comment]
@goanpeca could you look into the listed elements? Thanks!

**Comment by goanpeca** [comment]
Thanks for the feedback @dalthviz, will work on the fixes.

However for this one:
>In the Editor having a word selected and hitting Cmd + Shift + F/Ctrl + Shift + F doesn’t automatically start a search.

It cannot be fixed to behave as 4.x, since on 4.x it is merging 2 different actions under the same shortcut and the new API does not allow for these hacks to work. It is not a matter of the new API not being able to do something and more of a case that things in 4.x (and before since this probably goes back to 2.x ...) 

### On 4.x:
- There is the `Switch to Find in Files`  and that is set `Cmd + Shift + F` by default.
![image](https://user-images.githubusercontent.com/3627835/91765425-98d9eb80-eb9e-11ea-9b1e-844e5897c540.png)

![image](https://user-images.githubusercontent.com/3627835/91765435-9d060900-eb9e-11ea-9007-c4b65cddd73e.png)

- Another completely different action that is added to the `Search Menu` is taking the selected text from the Editor, pasting on the Find in Files plugin, showing it if it hidden and then running the search.
![image](https://user-images.githubusercontent.com/3627835/91765441-a0999000-eb9e-11ea-9872-b3c02e8ba0f5.png)

- This completely different action is also using the same `Cmd + Shift + F` shortcut.

### On master:

- There is the `Switch to Find in Files`  and that is set `Cmd + Shift + F` by default. Triggering this action will show the pane, as expected
- There is the `Find in Files` action that will show the plugin if not visible and start running the `find in files plugin`if there is text in it. It is not copying the text and pasting it on the plugin (This I will fix)
- This separate action is available now on the shortcut preferences and can be configured, but cannot use the same shortcut. 

So:
1. I can have the menu do the expected action, but not use the same shortcut as another action (Switch to Find in files).
2. I can add a default shortcut (whatever is decided?) or this action will not have a shortcut by default
3. I can fix the `selected text` behavior so it does the same thing on master
