### ISSUE TITLE
Differences in online help pane toolbar

### ISSUE THREAD

**Issue by steff456** [spyder-ide/spyder#13684]
## Problem Description
The toolbar of the Online Help pane has some differences in master and 4.x,

1. First the buttons are in a complete different order
**Master**
![image](https://user-images.githubusercontent.com/20992645/91904898-4ca8ad00-ec6b-11ea-8f97-719f08dd7428.png)

**4.x**
![image](https://user-images.githubusercontent.com/20992645/91904918-5500e800-ec6b-11ea-96e4-c9aac469935c.png)

2. Placeholder text is different
**Master**
![image](https://user-images.githubusercontent.com/20992645/91904977-6d710280-ec6b-11ea-939b-2aded6233fdd.png)

**4.x**
![image](https://user-images.githubusercontent.com/20992645/91904998-75c93d80-ec6b-11ea-909f-5285b20c5d78.png)

### What is the expected output? What do you see instead?
The online help pane should look the same as 4.x

**Comment by goanpeca** [comment]
Hi, @steff456 thanks for the feedback.

>1. First the buttons are in a complete different order

This was a deliberate change and goes in line with the change in the `Find in Files` plugin where the button for starting and stopping is the same since those actions are mutually exclusive.

Browsers (Like Chrome and Firefox) provide that interface, where the stop and refresh button are one and the same. Since this plugin is basically a "specialized" browser, it should provide an interface that is already familiar to users.

### Chrome
<img width="633" alt="Screen Shot 2020-09-01 at 15 59 07" src="https://user-images.githubusercontent.com/3627835/91905386-10c21780-ec6c-11ea-82b9-2a21d319b1eb.png">

### Firefox
<img width="495" alt="Screen Shot 2020-09-01 at 15 58 17" src="https://user-images.githubusercontent.com/3627835/91905295-f2f4b280-ec6b-11ea-919a-98b81addb552.png">

I would like to hear what @isabela-pf thinks of this?

>2. Placeholder text is different

I can restore the original text.

**Comment by steff456** [comment]
> This was a deliberate change and goes in line with the change in the Find in Files an Pylint plugin where the button for starting and stopping is the same since those actions are mutually exclusive.

Ok, we can keep the change of the order in the toolbar. Maybe we can unify the refresh button with the stop one, as the changes you already made in the `Find in files` and `Pylint` plugin.

> I can restore the original text.

Thanks!

Please take into account that for this plugin migration the idea is to maintain as closely as we can the interface so then we can make the changes we are studying in meetings with Isabella and that's why some of my comments are more related to how things are looking in the 4.x branch.

**Comment by ccordoba12** [comment]
> Since this plugin is basically a "specialized" browser, it should provide an interface that is already familiar to users

We discussed your proposed changes with the rest of team and agreed that they make sense.

However, please do not introduce any additional changes to the UX/UI of the plugins that have not been migrated yet to the new API. You're conflating the migration process with those changes, which are unrelated tasks.

Besides, you're introducing a lot of changes without discussing them with anyone else in the team, which not only makes our task of reviewing your PRs harder (because we need to verify very carefully what has changed between 4.x and master); but we also consider that's not the proper way to approach that task.

Instead, we're reviewing pane by pane with Isabella in weekly meetings with her, and deciding how to improve their UX/UI with her.

**Comment by goanpeca** [comment]
Hi @steff456 thanks for the feedback.

>Ok, we can keep the change of the order in the toolbar. Maybe we can unify the refresh button with the stop one, as the changes you already made in the Find in Files and Pylint plugin.

Thanks for the understanding, but to clarify the unifying of the Search/Stop, Find/Stop buttons is something @ccordoba12 agreed from the beginning.

I just took a decision based on a similar change. Unifying buttons, moving the button was a necessary change because it would not have made much sense leaving the button to the far right, so that was just a consequence of unifying the buttons.

>Please take into account that for this plugin migration the idea is to maintain as closely as we can the interface so then we can make the changes we are studying in meetings with Isabella and that's why some of my comments are more related to how things are looking in the 4.x branch.

Agreed, @steff456, and there have been several issues that appeared due to how the API changed how things were made, or some are just the result of having to rebase PRs that have stayed without revision for many months, and when rebasing them against master sometimes I did not check with 4.x.

@spyder-ide/core-developers please take into account that the new API completely restructures how the top buttons in a Pane are created and laid out, so replicating the same things that 4.x does, is not something that always makes sense. Like was the case for unifying the mutually exclusive buttons.

**Comment by ccordoba12** [comment]
@goanpeca, we agreed with the rest of the team that for the next PRs on queue in the new API migration process (starting with the Pylint one) you need to leave their layout and UI/UX as close as possible, or even better the same, as the one currently displayed in 4.x.

In case that's not possible, you need to clearly justify the technical reasons that don't allow you to do that. As I said above, it's not part of this process to also introduce UI/UX changes. Instead, that's part of the project we're working on with Isabella.

**Comment by goanpeca** [comment]
>@goanpeca, we agreed with the rest of the team that for the next PRs on queue in the new API migration process (starting with the Pylint one) you need to leave their layout and UI/UX as close as possible, or even better the same, as the one currently displayed in 4.x.

Sounds good.

>In case that's not possible, you need to clearly justify the technical reasons that don't allow you to do that. As I said above, it's not part of this process to also introduce UI/UX changes. Instead, that's part of the project we're working on with Isabella

I have always technically justified why changes are needed and will continue to do so.
