### ISSUE TITLE
can not load the file in the same filefolder

### ISSUE THREAD

**Issue by MrCrazyCrab** [spyder-ide/spyder#13856]
### What the problem?

the same code git from the network, it's Ok to run the code with pycharm, but the spyder did'nt make it. 
For example:
"    from util import util
ImportError: cannot import name 'util'
"
However, the util filefolder is just at the same directory. But if i change the util into Util, and do the same change in the python file, it would run well. Fell puzzled about the problem.
## Versions

* Spyder version: 4.1.15
* Python version: 3.6.7
* Qt version: /
* PyQt version:/ 
* Operating System name/version: windows10

**Comment by juanis2112** [comment]
Hi @MrCrazyCrab. Can you please post a screenshot of the directory where you have your files and one of spyder when trying to run it?

**Comment by MrCrazyCrab** [comment]
@juanis2112 OK， the picture is just as follows!
![QQ截图20200927085458](https://user-images.githubusercontent.com/52489106/94353053-45749380-009f-11eb-9823-1e102f17e497.png)

**Comment by juanis2112** [comment]
It seems that the problem is that you are trying to import the "util" module from a module called "Options" because your "base_options.py" file is inside of this directory. However I see that your util folder is outside of this Options directory. 

You can try doing a relative import by adding ".." at the beginning of your import. In line 3 of the base_options.py file try:

```
from ..util import util
```

**Comment by juanis2112** [comment]
Closing for no response.
