### ISSUE TITLE
Saving layout doesn't store the right sizes.

### ISSUE THREAD

**Issue by juanis2112** [spyder-ide/spyder#13882]
## Problem Description
When saving a custom layout in spyder and trying to restore it, it shows different sizes for the panes.

### What steps reproduce the problem?

1. Save a layout

<img width="1440" alt="Screenshot 2020-09-29 at 2 58 54 PM" src="https://user-images.githubusercontent.com/18587879/94609379-4efb2880-0264-11eb-80aa-2c45b33e6408.png">

2. Close spyder
3. Load saved layout from the Window layouts list.

### What is the expected output? What do you see instead?

The layout that it loads is different from the one I saved.

Also:

I saved a layout called "Layout" without changing anything after loading the "Default Spyder Layout". Taking a look at the transient.ini file where the layouts are stored. I see that the parameters of these two are different when they should be the same. 

<img width="908" alt="Screenshot 2020-09-29 at 3 03 15 PM" src="https://user-images.githubusercontent.com/18587879/94609869-055f0d80-0265-11eb-97a8-38da9452b750.png">

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by wuhp06** [comment]
I find this bug too, and the newest version did not fix it.

If you maximize the Spyder window and then close it, and reopen it.  Spyder cannot restore the window position and size of the former window( normal state ).

I checked the source code, the bug is located in "plugins\layout.py" save_current_window_settings method of Layout class, and "app\mainwindow.py", the resizeEvent and  moveEvent method of MainWindow class seem useless, because self.isMaximized() return False when double clicking the window to maximize it.
