### ISSUE TITLE
Web-based Spyder for Anaconda Enterprise Edition ?

### ISSUE THREAD

**Issue by CoteDave** [spyder-ide/spyder#14072]
Hi there,

For now, according to the Anaconda team, Spyder can only be used with Anaconda Open-source because the IDE is not web-based. Soo Anaconda "Enterprise edition" does not offer the possibility to create virtual environnement with Spyder (IDE), only Jupyter/JupyterLab, RStudio, or VSCode are supported ... 

This is very sad because Spyder is hell of a good IDE !!!

Is there any ways we can bypass this problem ? 

Is there a web-based version planned in the futur to make it possible to "easy-use" it with Anaconda Enterprise edition ?

Thanks!

**Comment by ccordoba12** [comment]
Hey @CoteDave, thanks for reporting. You said

> Soo Anaconda "Enterprise edition" does not offer the possibility to create virtual environnement with Spyder (IDE), only Jupyter/JupyterLab, RStudio, or VSCode are supported ...

We don't have control over that because we're are not directly related to Anaconda.

> This is very sad because Spyder is hell of a good IDE !!!

Thanks a lot for your kind words!

> Is there any ways we can bypass this problem ?

Not right now, sorry.

> Is there a web-based version planned in the futur to make it possible to "easy-use" it with Anaconda Enterprise edition ?

We're working on it. Please click on the link below to see Spyder running in your browser:

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/spyder-ide/binder-environments/4.x?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fspyder-ide%252Fspyder%26urlpath%3Ddesktop%252F%26branch%3D4.x)

Once that's stabilized and works a bit better, we'll talk to the Anaconda guys to see if they can add an option to use Spyder in Anaconda Enterprise Edition.
