### ISSUE TITLE
multiprocessing

### ISSUE THREAD

**Issue by Tan-95** [spyder-ide/spyder#14128]
Every time I use concurrent.futures for multiprocessing. Spyder reports an internal problem. And indeed I find that the multiprocessing may not iterate over the whole list. It sometimes omits elements which leads to incorrect outcomes. I can't figure out why this could possibly happen. 
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by steff456** [comment]
Hi @Tan-95,

Can you please provide your code in order to try to reproduce this issue? Also if you can upload the error that Spyder is showing you will help us a lot to know what we are trying to reproduce. In case that you cannot get the error, please upload a gif shoring the behavior that you are experiencing.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
