### ISSUE TITLE
Spyder doesn't work with Python 3.9

### ISSUE THREAD

**Issue by hannahbus** [spyder-ide/spyder#14129]
## Problem Description
I created a new conda environment via 

`conda create -c conda-forge python=3.9 -n foo`

But then I do not get Spyder working in the new conda environment. 

### Paste Traceback/Error Below (if applicable)

UnsatisfiableError: The following specifications were found to be incompatible with each other:
 
Output in format: Requested package -> Available versions
 
Package python conflicts for:
python=3.9
spyder=4.1.5 -> atomicwrites[version='>=1.2.0'] -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.9,<3.10.0a0|>=3.5|>=3|3.4.*|>=3.6|3.7.*|3.8.*']
spyder=4.1.5 -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']

## Versions

* Spyder version: 4.1.5
* Python version: 3.9
* Operating System name/version: Windows 10

**Comment by ccordoba12** [comment]
Hey @hannahbus, thanks for reporting. The migration in conda-forge to create packages for Python 3.9 is in process. It could two or three months until it's finished and there are Spyder packages available for 3.9, so please be patient.

Until then, there's nothing we can do about that here because conda-forge is an independent project from us.

**Comment by hannahbus** [comment]
Hi @ccordoba12! Thanks for letting me know so quickly. Best of luck then for the ongoing developing process.

**Comment by AHHEISS** [comment]
Same problem for Python 3.10 and using Spyder in Anaconda Navigator.
Any idea when this might be available?

**Comment by ccordoba12** [comment]
Probably a couple of months.
