### ISSUE TITLE
Search shortcut by hotkey combination

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#14153]
I seek to press `Ctrl + Shift + I`, but press `Ctrl + Shift + O`, and something else happens. I don't know what, I don't know how to look it up, but I don't want it to happen - so to unbind it I must scroll through all hotkeys in Preferences or guess the functionality. It'd help if I could just search e.g. `"Ctrl + Shift + I"` and it shows the assignment.

Can add the following to context menu: `Search by Shortcut via quotations, e.g. "Ctrl + O"` (alternatively use separate search box).

**Comment by ccordoba12** [comment]
Nice suggestion. Instead of having a separate search, we could add searching by shortcut to our `Preferences > Keyboard shortcuts` table.

Unfortunately, we don't have time to implement this, sorry. However, you're welcome to submit a pull request for it. If you don't have time for that either, please feel free to close this issue.

**Comment by OverLordGoldDragon** [comment]
@ccordoba12 Fair.

**Comment by ccordoba12** [comment]
Thanks for understanding. You make very nice suggestions, if only the days would have 36 hours!

**Comment by OverLordGoldDragon** [comment]
@ccordoba12 Glad to hear; not all my suggestions/reports are important but I figure "better post anyway" and let you take it from there. (Though, never had a post I deemed important turned down.)
