### ISSUE TITLE
the spyder and anaconda won't lunch or open

### ISSUE THREAD

**Issue by ibo-py** [spyder-ide/spyder#14303]
## Problem Description
**please help!** 
I can't open any of anaconda or spyder it's like it will open but then close again 
I've tried 
'spyder --reset' or 'anaconda-navigator --reset'
and all of the solutions on the internet, but all failed.
thanks from now **:)**
### What steps reproduce the problem?

1. whenever I tried to install or uninstall anaconda/spyder or almost doing anything in the terminal
2. it gives me this error (this is the last lines)
`    from .compat import is_py2, builtin_str, str
  File "C:\Users\Kudus - Hamed\anaconda3\lib\site-packages\requests\compat.py", line 59, in <module>
    from urllib.request import parse_http_list, getproxies, proxy_bypass, proxy_bypass_environment, getproxies_environment
  File "C:\Users\Kudus - Hamed\anaconda3\lib\urllib\request.py", line 87
    except Exception, err:
                    ^
SyntaxError: invalid syntax`

**Comment by dalthviz** [comment]
Hi @ibo-py sorry to heard that, maybe it could be worthy to try to install Spyder using our new Windows installer. You can found it in our [release page](https://github.com/spyder-ide/spyder/releases/tag/v4.2.0) or through our [website](https://www.spyder-ide.org/) (which also have some links to our documentation regarding ways to install Spyder and a troubleshooting guide too).

Hope this info helps and let us know of you manage to fix your setup :)

**Comment by ibo-py** [comment]
doing that could make any problems?

**Comment by dalthviz** [comment]
I don't think so :) The Windows installer lets you make a per user install and you can uninstall it as with any other application from the control panel. The reason we wanted to make them is for installation issues as yours that we can't manage to help since are too specific or that are related with other setup aspects besides Spyder itself

**Comment by ibo-py** [comment]
@dalthviz 
I did  `pip install -U spyder` it seems like working for the first 3 or 4 min but then it makes this **Error** at the end of the lines:

>
![image](https://user-images.githubusercontent.com/74714927/100279735-2ba8dd00-2f78-11eb-8124-40505056fb6d.png)

and how I can solve the anaconda problem **thanks for your response**.

**Comment by dalthviz** [comment]
@ibo-py seems like you have a mix of an Anaconda installation and other Python installation in your machine. I would suggest for you to do a clean install of Python (removing the Anaconda install and the other Python install you have) and choose one of them. There is not much we can do in our side with this type of issues since they aren't directly related with Spyder but hope the info above helps :)

**Comment by ibo-py** [comment]
@dalthviz  I have python idle and a long time ago I did install visual studio but then I deleted could those make the problems?
and if there is no solution for this what should I do?

**Comment by ibo-py** [comment]
@dalthviz 
_I am a beginner and want help_
**thanks a lot for your help again** :D

**Comment by dalthviz** [comment]
This maybe of help @ibo-py: 

https://www.reddit.com/r/learnpython/comments/d5unwv/clean_python_installation/

As suggested I would say that you should try to clean/remove any Python installation done in your system (the link above could be useful for that) since seems like you have Anaconda installed but also other Python installation and usually that kind of setup only leads to errors. After that, choose a Python distribution you want to stick with (for example Anaconda) and then use only that distribution as well as environments to manage the things you want to do (in order to isolate the packages and versions you need to use and prevent errors).

Also, as part of the Spyder docs we have some info regarding Spyder installation options, Here is the link in case you want to give it a read after figuring out your Python installation :)

https://docs.spyder-ide.org/current/installation.html

**Comment by ibo-py** [comment]
@dalthviz  thank you very much that worked, it takes time but worked thanks again. :D
