### ISSUE TITLE
Fail to open dataframe in variable explorer

### ISSUE THREAD

**Issue by Ian19890607** [spyder-ide/spyder#14317]
## Problem Description

Fail to open dataframe in variable explorer

### What steps reproduce the problem?

1. To download and install standalone Spyder 4.2, not through Anaconda.
2. To download and install official python 3.7.6 32bit 
3. To change python interpreter path to "C:\Users\User\AppData\Local\Programs\Python\Python37-32\python.exe" in Spyder preferences 
4. To close the Spyder
5. To apply "pip install spyder-kernels"、"pip install pandas" in the command prompt.
6. To open Spyder and apply below python code
`import pandas as pd
a=[1,2,3]
a_pd=pd.DataFrame(a)`
7. After running it, open variable explorer 
8. click a_pd this variable.
9. It will show the error kernel is dead...
screenshot link: https://upload.cc/i1/2020/11/25/j1ZrDe.png

### What is the expected output? What do you see instead?
screenshot link: https://upload.cc/i1/2020/11/26/0WvRa3.png

## Versions

* Spyder version: Spyder 4.2.0
* Python version: 3.7.6 32bit
* Qt version: can't find in  pip list
* PyQt version: can't find in  pip list
* Operating System name/version:  win10 20H2

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Please read our

http://docs.spyder-ide.org/current/first-steps.html

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.

**Comment by ccordoba12** [comment]
Or if you want Spyder 4.2, please use conda-forge instead. For that, after installing Anaconda, you need to run

    conda create -n spyder-42
    conda activate spyder-42
    conda install -c conda-forge spyder
    spyder
