### ISSUE TITLE
BUG for running code

### ISSUE THREAD

**Issue by listenha** [spyder-ide/spyder#14310]
### What steps will reproduce the problem?

import math
print(math.pi)

The two lines above are a simple test code. Firstly, I run this code one time, the system print me 3.1415926…… , everything is ok; Then, I delete the first line (which is import math) and run the code again, the system still print me 3.1415926…… . All my running with the code is using the keyboard shortcut shift+enter, if I use the green Run file button on the top, the system will report me an error. But the Run file button also has a bug, it will repeat the result of the previous time I run the code. This only happen when I modify the code and run it, if I run a same code several time, it won't repeat the previous result.

## Versions

* Spyder version: 4.1.4 
* Python version: 3.8.3
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.1 (OK)
```

**Comment by dalthviz** [comment]
Hi @listenha if you run your file with `Shift+Enter` you run it using a `cell run` (which basically runs the lines you have in the file one by one). With the first `cell run` you import the `math` module and make it available in the console namespace so another `cell run` will yield an execution without errors.

However, if you do a `file run` (using the green arrow in the toolbar) by default the code runs in an empty namespace (previously loaded modules in the console aren't taken into account) which ends in an error if you remove the `math` module import. If you want to change this behavior you can modify the config to run files in `Run > Configuration per file... > General settings > Run in console's namespace instead of an empty one`

Hope this info clarifies a little how things work and how you can modify the behavior :)

**Comment by listenha** [comment]
thanks!@dalthviz I see how it works now

**Comment by dalthviz** [comment]
Awesome @listenha ! closing this one then
