### ISSUE TITLE
Multiline editor feature

### ISSUE THREAD

**Issue by Jaycobe** [spyder-ide/spyder#14373]
I've found a couple of questions about multiline editor feature (from 2015 and 2017) and it was told that it would be added in Spyder 4. It's out but I cannot find a way to edit multiple strings at once. Was the feature added?

**Comment by ccordoba12** [comment]
Hey @Jaycobe, thanks for opening this issue. Unfortunately, multiline edition has not been added to Spyder yet, but it's high on our todo list so hopefully it will be added at some point next year.

To track progress of that, please follow issue #2112. Also, I'm going to close this issue in favor of that one because all the discussion around this topic has happened there.
