### ISSUE TITLE
Matching bracket highlighting index error

### ISSUE THREAD

**Issue by hengin** [spyder-ide/spyder#14374]
## Problem Description
When the final closing bracket (`)`, `]` or `}`) of a bracket pair is the first character in its line, any empty lines between the bracket pair are discarded during the search for the opening bracket leading to an indexing error of what character is being highlighted.

The error and a method of reproduction should be apparent from this image:
![spyder-highlight-bug](https://user-images.githubusercontent.com/17409078/101279560-56d6cc00-37c3-11eb-8dfe-ef09e9f3eb47.png)

## Versions
This happens in 4.2.0. See permalinks to code below for more details.

## Root cause
The bracket finder searches text that it gets from `BaseEditMixin.get_text` (lines 286 and 291)
https://github.com/spyder-ide/spyder/blob/436290ba71bb16c5928676467a358b70f4f38c10/spyder/plugins/editor/widgets/base.py#L282-L293

However, `BaseEditMixin.get_text` removes newlines under some conditions, resulting in the aberrant behaviour (lines 907-912)
https://github.com/spyder-ide/spyder/blob/436290ba71bb16c5928676467a358b70f4f38c10/spyder/widgets/mixins.py#L900-L913

## Possible fixes
I encountered this bug while working on #1354 and I plan to include a fix for this issue in the same pull request. But there are several alternatives for fixing it and I'd like some input on which is best.

1. Remove lines 907-912 from `BaseEditMixin.get_text`. I've tested it and it solves the problem, but it will cause other errors if the line removal behaviour is depended on elsewhere.
2. Make `all_text` an optional parameter with default value `None`. If `None`, it will be computed as previously.
3. Write a new function identical to `get_text` except without the line removal.

Ideally I would like to go with option 1, but that requires figuring out why the newlines are removed in the first place. If this behaviour is relied on elsewhere I think the newline removal should be moved there instead of kept in `get_text`. I don't think it's suitable to have a function called `get_text` that filters the text before returning it without having any parameters to control that behaviour.

Option 2 is safer and requires no investigation into side effects. So that's my second choice.

And while I'm here: How would I go about writing a regression test for a GUI feature like this? Where should I look for examples?

**Comment by ccordoba12** [comment]
Hey @hengin, thanks for opening this issue. You said:

> Ideally I would like to go with option 1, but that requires figuring out why the newlines are removed in the first place

You can get the commit associated to a given line by using `git blame` (or clicking the `Blame` button on Github's interface):

https://github.com/spyder-ide/spyder/blame/436290ba71bb16c5928676467a358b70f4f38c10/spyder/widgets/mixins.py#L900-L913

So the reasons for removing newlines seem unclear (and were introduced 9 years ago). The only thing that can be concluded for sure is that I introduced `all_text` in commit https://github.com/spyder-ide/spyder/commit/e37288263dcc6cadf096c3ba9dd9afc9c5d54ce6 to avoid an issue with Python 3, so it seems it's important.

Given that changing something that has remain like that for so long can introduced bugs, my suggestion is for you to go with something similar to option 2. But instead of using `all_text` as parameter, please add a different one called `remove_newlines=True` so you can set it to `False` in the case you need.

**Comment by ccordoba12** [comment]
> And while I'm here: How would I go about writing a regression test for a GUI feature like this? Where should I look for examples?

Thanks for thinking about that! We have lots of those tests around for you to take a look at.

@CAM-Gerlach, could you explain @hengin how to create tests with pytest-qt?
