### ISSUE TITLE
`atexit` fails with `runfile`

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#14495]
```python
# file.py
import atexit
def f():
    print("Ran f successfully")
atexit.register(f)
```

I may be misunderstanding how `runfile` works, but I expect it to function similar to `python file.py` from terminal. Above prints successfully per latter but not former; tried below to force an "exit" to no avail (though program execution _does_ stop, as evident from failed followup `print`):

```python
sys.exit(0)
# raise SystemExit  # try one at a time
print("Couldn't exit")  # <-- won't execute
```
Can we "exit" `runfile` such that `f()` is called?

**Comment by ccordoba12** [comment]
@OverLordGoldDragon, please read the [Python docs](https://docs.python.org/3/library/atexit.html) before reporting issues like this (firsr sentence of the `atexit` docs):

> The atexit module defines functions to register and unregister cleanup functions. Functions thus registered are automatically executed upon normal interpreter termination

The relevant words here are `interpreter termination`: since our IPython consoles are interactive interpreters (not regular Python processes), they don't terminate after `runfile`. Well, they don't terminate unless you restart their kernels. In that case, I think `atexit` should take place.

**Comment by OverLordGoldDragon** [comment]
`runfile` resembled a pure terminal in some respects, I figured maybe it ran as such and simply redirected output to the IPython console; thanks for clarifying. Tested restarting kernel, `atexit` doesn't execute (no longer needed regardless):

```python
import atexit
def f():
    with open('ran.txt', 'w') as f: 
        f.write('')
atexit.register(f)
```
