### ISSUE TITLE
Spyder-4.2.1 starts up error

### ISSUE THREAD

**Issue by beew** [spyder-ide/spyder#14491]
When start spyder, the issue reporter window pops up

The "details" says

```
 File "/home/bernard/opt/python38/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 2198, in update_source_menu
    self.editor.refresh_formatter_name()
AttributeError: 'NoneType' object has no attribute 'refresh_formatter_name'
```
* Spyder version:  4.2.1
* Python version: 3.8.7
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: Ubuntu 16.04/Ubuntu 20.04

P.S  Last working version of spyder is 4.1.5 (for 4.1.6 get incompatible pylint and astorid :

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 4.1.6 requires pylint<=1.9.5,>=1.0, but you have pylint 2.6.0 which is incompatible.
```
But pylint 2.6.0 is needed for astroid 2.4.2 which is required for spyder-4.1.5 or 4.1.6, lower version get 
```AttributeError: module '_ast' has no attribute 'Str'```

pylint2.6.0 + astroid2.4.2 work for spyder 4.1.5)

**Comment by ccordoba12** [comment]
Hey @beew, thanks for reporting. Please read our Troubleshooting Guide:

http://docs.spyder-ide.org/current/first-steps.html

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.

**Comment by seyeeet** [comment]
@beew did you solve this issue? I also have the same problem
