### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by asadbuzdar264** [spyder-ide/spyder#14623]
Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed (>= 1.9.4 and < 1.10.0). Without this module is not possible for Spyder to create a console for you.

You can install it by running in a system terminal:

conda install spyder‑kernels

or

pip install spyder‑kernels

**Comment by dalthviz** [comment]
Hi @asadbuzdar264 seems like you don't have the correct version of `spyder-kernels` installed for your Spyder version. Please try to install the minimum version that the message describes for `spyder-kernels` with something like:

* If you are using conda:
    conda install spyder-kernels=1.9.4
* If you are using pip:
    pip install spyder-kernels==1.9.4

You can also check out our docs where this message is further explained: https://docs.spyder-ide.org/current/common-illnesses.html 

Otherwise, please provide information about your setup (at least: Spyder version, dependencies list, and how did you installed Spyder - conda, pip, etc.).

Let us know if something of the above helps :)

**Comment by dalthviz** [comment]
Closing due to lack of response
