### ISSUE TITLE
logging library doesn't seem to work well with spyder

### ISSUE THREAD

**Issue by Ian19890607** [spyder-ide/spyder#14651]
Hello,

I'm trying to run a script using python standard library 'logging' module. This script works fine from Python IDE but when run from Spyder, it can't adjust the level and save log.
======================================
import logging
logging.basicConfig(level=logging.WARNING)
 
logging.debug('Hello debug!')
logging.info('Hello info!')
logging.warning('Hello warning!')
logging.error('Hello error!')
logging.critical('Hello critical!')

=====================================
import logging
logging.basicConfig(filename='example.log',level=logging.DEBUG)   #level is not workable
logging.debug('This message should go to the log file')
logging.info('So should this')
logging.warning('And this, too')

======================================

**Comment by dalthviz** [comment]
Hi @Ian19890607 thanks for the feedback! I think the problem is that is not possible to dynamically re-config the logging once you have call `baseConfig` (basically you can only call `baseConfig` one time to setup the params of the logging). Checking, seems like starting from Python 3.8 a `force` argument was added to enable recalling the `baseConfig` and overwriting the previously setup params.

For more info you can check:
* https://stackoverflow.com/q/12158048
* https://docs.python.org/3.8/library/logging.html?highlight=logging#logging.basicConfig (basicConfig -> _This function does nothing if the root logger already has handlers configured, unless the keyword argument force is set to `True`._)

Since seems like this is not directly related with Spyder so I'm closing the issue. I hope the info above helps you :)

**Comment by Ian19890607** [comment]
@dalthviz   Thank you for your quick reply. But I didn't call basicConfig twice.  Sorry to confuse you, previous posts are two example codes.
I should say, "basicConfig " is invalid for spyder, but it is workable on Python official IDE.  Maybe you can trial un on two example codes (I provided previously) in spyder IDE and modify the parameters in the "basicConfig", you will find out what I want to express.

**Comment by dalthviz** [comment]
Oh I see @Ian19890607 I'm reopening this one then. However, testing I was able to correctly set the config calling `basicConfig`. Just in case, how are you running the snippets you mention? and what is the version of Spyder that you are using? (the current release and the version I checked this is `4.2.1`). Also, if you can, please submit here a GIF or video to check the way this behavior is being trigger in your side (since I'm being unable to reproduce it).

Also, take into account that running a file multiple times will make him run in the same IPython Console (current one or dedicated depending in your per file run configurations) so the values that set the config of the logging will be the ones in the initial run of the file unless you restart your IPython Console or pass the `force` argument (as mentioned if you have Python 3.8+).

Any new info to reproduce this is greatly appreciated :)

**Comment by dalthviz** [comment]
Closing due to lack of response
