### ISSUE TITLE
osx-arm64 conda feedstock

### ISSUE THREAD

**Issue by sourestdeeds** [spyder-ide/spyder#14670]
I noticed that there were updates for spyder to function on the m1 chip, yet with the conda and conda-forge feedstock there appear to be no arm64 versions.

Is this still the case or has it just not been added to the list yet? These are my current channels:
```
 - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch
 ```

**Comment by juanis2112** [comment]
Hi @sourestdeeds thanks for reporting this.

I think it will take about 6 months or more to have the Spyder packages for M1 in conda-forge because most of them are very hard to compile. Sorry about that.

However one possible solution is to download Spyder with our standalone installers from here https://www.spyder-ide.org/#section-download and then creating a conda forge environment that contains Spyder-kernels along with the libraries that you need and connecting this environment to Spyder. 

To do the latter, you only have to change the python interpreter following the instructions here:
https://docs.spyder-ide.org/current/faq.html#using-existing-environment

**Comment by juanis2112** [comment]
Closing for no reply

**Comment by sourestdeeds** [comment]
The latter installs spyder under rosetta, alas.
