### ISSUE TITLE
PyQt dependency upper bound for version

### ISSUE THREAD

**Issue by ma-sadeghi** [spyder-ide/spyder#14717]
Is there a reason why Spyder has an upper bound for PyQt version. I've been getting some conflicts recently as I'm trying to install another package which relies on `paraview` which seems to conflict w/ Spyder's dependencies. Is it possible to relax it?

**Comment by ccordoba12** [comment]
Hey @ma-sadeghi, thanks for reporting. Unfortunately, that's not possible at the moment because some of our tests are failing for more recent versions of PyQt.

We'll try to do that for Spyder 5, to be released in April. For now, the only workaround is to use separate environments for Spyder and Paraview, sorry.
