### ISSUE TITLE
How to Get Rid of Yellow Triangle Warnings

### ISSUE THREAD

**Issue by BillLe2000** [spyder-ide/spyder#14741]
Hello, 
[
![image](https://user-images.githubusercontent.com/39404927/107812563-7c3d0480-6d35-11eb-82a8-0f864da3c9e9.png)
](url)

## Problem Description
I executed the code above and the output came out as what I expected.  However, the yellows triangles exist.  Could someone please point out where I got wrong in the code? Also when I hove to the yellow triangle, I see a warning message below:

[
![image](https://user-images.githubusercontent.com/39404927/107813934-b529a900-6d36-11eb-9b81-b7e7e7797812.png)
](url)

Thank you !!!
### What steps reproduce the problem?

N/A

### What is the expected output? What do you see instead?

N/A

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

N/A
```

## Versions

* Spyder version: 4.2.1
* Python version: 3.7
* Qt version: ``
* PyQt version: 
* Operating System name/version: Window 10 Home [version](url)

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by juanis2112** [comment]
Hi @BillLe2000. When doing `from tkinter import *` Spyder's linter doesn't know where are the Tk, RadioButton, IntVar and Label objects that you are using. To avoid this, I suggest changing your first line of code to `from tkinter import Tk, RadioButton, IntVar, Label`. 

If you want to leave your code as it is, you can also disable Linting warnings in the preferences dialog

<img width="1041" alt="Screenshot 2021-02-12 at 5 49 39 PM" src="https://user-images.githubusercontent.com/18587879/107831236-9689d900-6d5b-11eb-84f1-993e7dccf9ea.png">

We do not recommend this, because this will also hide the errors shown by our linter but this way you won't see the yellow warnings.

**Comment by BillLe2000** [comment]
Hello,
Thank you so much! It works.  I kept the code as it is and just unchecked
the "Enable basic linting" button; all the yellow triangles gone.
Thank you again!
Ben

**Comment by juanis2112** [comment]
Grad to help!

**Comment by lunatila** [comment]
I have the same problem, but I just want to warnings to disappear, not the real errors. How can I get rid of the yellow triangles keeping the red ones?

**Comment by ccordoba12** [comment]
@lunatila, you need to add a comment like `# noqa` to the right of the line whose error you don't want to see. Like this

```python
from numpy import * # noqa
```
