### ISSUE TITLE
python interpreter - invalid file path

### ISSUE THREAD

**Issue by mmohaqeqf** [spyder-ide/spyder#14818]
### What steps will reproduce the problem?

1. tools.
2. preferences.
3. python interpret
4. try to use a different python interpreter than the default.
5. gives error: invalid file path.
spyder version 4.2.2 windows 10

## Versions

* Spyder version: 4.2.2 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree                    :  None (OK)
IPython >=7.6.0                 :  7.20.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.0.1 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.0 (OK)
pylint >=1.0                    :  2.7.0 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  53.0.0 (OK)
sphinx >=0.6.6                  :  3.5.1 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog                        :  1.0.2 (OK)
zmq >=17                        :  22.0.3 (OK)

# Optional:
cython >=0.21                   :  0.29.22 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.19.3 (OK)
pandas >=1.1.1                  :  1.2.2 (OK)
scipy >=0.17.0                  :  1.6.1 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)
```

**Comment by juanis2112** [comment]
Hi @mmohaqeqf thanks for reporting this. Can you please tell me how are you specifying the path for this interpreter. Are you typing it manually? Or are you selecting it from the dropdown displayed?

<img width="1047" alt="Screenshot 2021-02-26 at 4 04 18 PM" src="https://user-images.githubusercontent.com/18587879/109354757-48d99a00-784c-11eb-9fb7-ec0705d775cb.png">

**Comment by mmohaqeqf** [comment]
Hi @juanis2112 ;
I click on the "Select Folder" icon, and navigate to where python exe file is located in my hard drive.
I used to select the py.exe file located in my C:\Windows\py.exe ; which was not working. Then I changed it to C:\Users\Mohammad\AppData\Local\Programs\Python\Python39\python.exe, and it picked it up without error.
So, my issue is resolved now.
Thanks for your time.

**Comment by real-yfprojects** [comment]
Please change the title to 

> Python interpreter - invalid file path

**Comment by real-yfprojects** [comment]
Most say, there is no such word _interpretor_. It is called **interpreter**. Other say, _interpretor_ is archaic.

**Comment by vdveen** [comment]
Hi! I have been struggling with this issue, and I do think it is Spyder's fault. I have downloaded multiple versions of Spyder 5, first through a standalone WinPython download, and now via the Windows executable installer. It does not matter if I select it from the dropdown menu, or type it on my own. It does not matter if I use forward or backslashes while typing on my own. It might be interesting to note that no Python envs appear in the dropdown menu, but that might be because they're not under my PYTHONPATHs. 

Here's my attempt to add my actual Python.exe location:

![afbeelding](https://user-images.githubusercontent.com/9057117/151578852-b40bf3dd-f967-4594-b1d9-eac346684fc9.png)

If I create a copy python.exe (just to test it out) in the ROOT folder of my C: disk and point it there, it also does not work:

![afbeelding](https://user-images.githubusercontent.com/9057117/151579077-c545523b-f542-4e00-bef7-4e20fde48ca2.png)

I was worried it might be a permissions issue on my C: disk, so I tried the same on an external usb drive, but no luck:

![afbeelding](https://user-images.githubusercontent.com/9057117/151579309-444c8aea-fbc3-48f0-8b99-99601dc43eb5.png)

For comparison, VS Code has no issues finding said Python interpreter:
![afbeelding](https://user-images.githubusercontent.com/9057117/151579956-b1925237-af17-40dd-86fd-adb975f3138a.png)

**Comment by vdveen** [comment]
Small update: when installing Spyder through Anaconda, I have the same issue as above. 

* Spyder version: 5.1.5 None
* Python version: 3.9.7 64-bit
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

**BUT**! That instance of Spyder does 'allow' me to select the Anaconda Python path. On all the above testing, I was not able to get a single path working without the 'invalid file path' error. 

![afbeelding](https://user-images.githubusercontent.com/9057117/151764275-1167d090-f2ca-46cf-869c-5140ee706190.png)

I really don't know why Spyder can see this folder, but not any other. My hypothesis is that it's because I checked the 'add Anaconda to PATH environment variable'. I'm going to try adding the above env to my system path to see if that works.

**Comment by UsualNoise** [comment]
Just dropping in to say I just encountered this bug as well.  I followed all the steps here:

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder

So that I could switch my Spyder 5.1.5 over to using Python 3.10 (it is currently on 3.8.12).  However, I get the same Invalid path error others have reported.  I have no idea why, I installed the spyder-kernels package as instructed in that environment first, but I cannot switch the executable in Spyder.  Any help would be greatly appreciated.

**Comment by felipekbernardi** [comment]
I think the problem is the folder organization created by Python 3.9 or newer when the venv is created. 
I had this plroblem and change the python version from 3.9.7 to 3.8.10. The venv produced by Py3.8 set the python.exe in a folder named Scripts and Py 3.9 set in bin folder with 3 versions of python.exe. For me, Spyder worked out of Anaconda path only with 3.8 version!
I used a pyenv (https://github.com/pyenv/pyenv)  to manage the python.

**Comment by dalthviz** [comment]
Hi!

@UsualNoise if you are trying to use Python 3.10 please try with an env created with the conda-forge channel version (Python 3.10.2) instead of the default ananconda channel (Python 3.10.0). 

Here is the more specific issue for reference where we are discussing the case of Python 3.10 as custom interpreter: https://github.com/spyder-ide/spyder/issues/17380

Interesting findings @felipekbernardi , just in case the current way we use to validate the interpreter selected is described here: https://github.com/spyder-ide/spyder/issues/17380#issuecomment-1051387371 which could be somehow not passing in cases where the Python version in a venv is changed. If you have more info regarding this please post it at https://github.com/spyder-ide/spyder/issues/17380
