### ISSUE TITLE
Crash to Desktop

### ISSUE THREAD

**Issue by Richardk2n** [spyder-ide/spyder#14821]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder used to crash with no error given occasionally, after I updated to 4.2.2 it crashes 3 times per hour. It seems to happen if I am at full speed (type rapidly, use autocomplete...). First it hangs for around 4 to 5 seconds, then it crashes. It should be stated, that I am doing this on a PC not really suited for the workload (RAM usage is constantly > 100% and some CPU cores are also at 100%). The crashing first started after a recent windows update (version 2004), which briefly caused all QT based applications on my PC to render incorrectly. Since then my own PyQt based applications is practically unusable due to constant crashing. Further investigating with the windows event log showed, that the spider crash is caused by an error 0xc0000409 in site-packages\PyQt5\Qt\bin\Qt5Core.dll wich interestingly is not where my own application crashes (that would be site-packages\PyQt5\Qt\bin\Qt5Gui.dll with 0xc0000005). Still this feels highly related as the misbehavior started at the same time. The two PyQt installations are sperate and I already tried reinstalling, so it shoul not be some kind of dll corruption. I know, that this is probably not the fault of spyder, but I hope you can help me get further debug information and maybe you experienced such a problem before.

### What steps reproduce the problem?

1. Start spyder
2. Use it
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.2.2
* Python version: 3.9.2
* Qt version: 5.12.10
* PyQt version: 5.12.3
* Operating System name/version: Windows 10 20H2

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by juanis2112** [comment]
Hi @Richardk2n, thanks for reporting this. 
This issue might be related to this one https://github.com/pyinstaller/pyinstaller/issues/4293 so maybe this can give you some more information.
For the moment, let's try to see if the problem is DLL. Can you please open your Anaconda Prompt and paste here the output of the commands `where qtgui.dll` and `where qtcore.dll`.

**Comment by Richardk2n** [comment]
Sorry for the late reply.
The issue you linked seems to talk about not finding the dll. In my case the dll is found but a crash is caused by (handling) it. Not sure how that is related?

I am not using anaconda.

**Comment by CAM-Gerlach** [comment]
@Richardk2n Hey, we apologize for the confusion over the previous message. We meant to say to try the indicated commands in your Anaconda prompt, if you're using Anaconda, or otherwise the standard Windows command prompt (with your Spyder environment active, if you've installed it in such). Further, we did not mean to imply the issues were directly related; while it occurred with the specific PyQt version you were using; as you note, the error is different and it is with Pyinstaller, not Pyinst as we use.

To explain a little more, the reason we were asking you to run the indicated commands is due to a common problem we have seen in the past (that our installers and other changes have mostly eliminated), due to multiple Python/Qt installs or other conflicting incompatible DLLs that are installed in `system32` or elsewhere on the `PATH`, even with separate/reinstalled installations, due to how Windows and Python handles DLL loading. Therefore, could you provide the output of the indicated commands, and explain how you installed Spyder (e.g. via our recommended standalone installation packages, or via another method), so we can try to narrow down if there's anything we can do about it on our end? Thanks!

**Comment by Richardk2n** [comment]
I do not have spyder installed in an environment (I installed it with pip from an admin cmd).
`where qtgui.dll` as well as `where qtcore.dll` does not find anything. If you meant `where Qt5Gui.dll` and `where Qt5Core.dll` that returns
```
C:\Program Files\MiKTeX 2.9\miktex\bin\x64\Qt5Gui.dll
C:\Program Files (x86)\Paragon Software\LinuxFS for Windows\Qt5Gui.dll
```
and
```
C:\Program Files\MiKTeX 2.9\miktex\bin\x64\Qt5Core.dll
C:\Program Files (x86)\Paragon Software\LinuxFS for Windows\Qt5Core.dll
```

**Comment by ccordoba12** [comment]
Those programs could be causing the errors you're seeing if they are in your PATH.

**Comment by CAM-Gerlach** [comment]
Sorry for the delay in replying; this one got away from me.

@ccordoba12 They are in their `PATH`, otherwise `where` (same as `which` on *nix) wouldn't show them. Assuming the errors shown in the OP are correct, though, the actual DLLs being used are the ones apparently installed with PyQt in `site-packages`, which I assume should be higher on Python's internal `PATH` than the two other ones (the problem we had before was due to DLLs installed in `System32`, which override the locations in the `PATH`, which these aren't. However, there could be other DLLs/binaries that are getting picked up.


@Richardk2n Sorry, I didn't realize you had manually installed via `pip`, which per our install guide is intended for advanced users familiar with resolving what appear to be machine-specific dependency problems such as this that appear to be outside our control or ability to reproduce. Its possible another DLL or binary these were trying to call out to had a problem, there's an incompatibility between the version of Qt bundled with your version of PyQt and the latest OS or something else on your machine (security software, etc), or there's something else going on behind the scenes. Also, if you've installed or updated any other Python packages lately, since Spyder isn't installed in its own environment as we recommend, that could have broken something, or there could have been permissions issues due to unnecessarily installing as admin.

As we now have official standalone installer packages available, could you [download](https://github.com/spyder-ide/spyder/releases/latest/download/Spyder_64bit_full.exe) and install the latest version for Windows and see if you can reproduce the problem? This ensures Spyder installs in an isolated, self-contained environment with a known-good set of working dependencies, avoids most install and startup-related problems that would otherwise be outside of our direct control, and doesn't break if you install, update or remove other packages on your machine; of course, you can still use Spyder with any of your existing environments/Python installs by simply selecting them under Preferences -> Python interpreter. At the very least, it should hopefully allow us to isolate the problem to determine if it is reproducible/fixable on our end. Thanks!

**Comment by dalthviz** [comment]
Closing due to lack of response
