### ISSUE TITLE
Problem encountered when I log in with the "Restart Kernel" option

### ISSUE THREAD

**Issue by RenatoWolf** [spyder-ide/spyder#14869]
I ran a simple program, just checking the collections module and checking named tuples.
The program ran normally, with no problems.
I clicked on the icon to "delete the messages" (it looks like an eraser for erasing written with a pencil) - it ran without problems.
Then, it entered the option for "restarting the kernel", the spyder performed the restart and at the end of the process the spyder displays the error message, asking us to describe the problem.

**Comment by ccordoba12** [comment]
Hey @RenatoWolf, thanks for reporting. You said:

> at the end of the process the spyder displays the error message, asking us to describe the problem.

The idea is for you to use that error message dialog to send us the problem, because it contains all the information necessary for us to understand it.

What you have posted here (unfortunately) can't help us to do that. So next time the error message appears, please use it to submit your report. Thanks!
