### ISSUE TITLE
Latex rendering with dark theme is broken

### ISSUE THREAD

**Issue by moux233** [spyder-ide/spyder#14895]
When I use Astropy quantities, they are rendered as black-text latex in Spyder's ipython console. This is fine when the console has a light background, but unreadable when I choose a dark theme for Spyder. There is a similar issue with pint.
I was not able to find settings anywhere in Astropy/ipython/Spyder to fix this.
Astropy defines a _repr_latex_ method. The only workaround I could find was to delete the method.

**Comment by steff456** [comment]
Hi @moux233,

Can you give me a set of steps to reproduce your issue? Also if you can post an image of the console?

**Comment by moux233** [comment]
Hi @steff456 

![image](https://user-images.githubusercontent.com/56129128/110511322-65a38680-8104-11eb-9a4b-6d3fe5180ce9.png)

import astropy.units as u
x = 2 << u.m

and then display x at the console

**Comment by steff456** [comment]
Thanks for the example! Right now all the team is working really hard on Spyder 5, but once it is out we will work in this issue.

Thanks for reporting!

**Comment by Kshitij-rgb** [comment]
![image](https://user-images.githubusercontent.com/84018859/118206516-4d434580-b480-11eb-8f2e-5eb3ac3e697f.png)
I just wanted to give another example using SymPy. Perhaps a way to change the colour of the LaTeXed text would be helpful.

**Comment by ccordoba12** [comment]
@Kshitij-rgb, if you want Latex expressions to be properly rendered when using dark themes, you need to use our Sympy consoles. You can open one by going the menu

    Consoles > New special console > New SymPy console

If you don't want to use them, you need to import first [`init_printing`](https://docs.sympy.org/latest/modules/interactive.html?highlight=init_printing#sympy.interactive.printing.init_printing) and pass the appropriate parameters to it.

**Comment by bnavigator** [comment]
Hi!

> if you want Latex expressions to be properly rendered when using dark themes, you need to use our Sympy consoles

This is not solved by using a SymPy console, because SymPy's LaTeX rendering is not involved in the given example. Astropy returns objects with `_repr_latex_()` methods, which are rendered by QtConsole.

![image](https://user-images.githubusercontent.com/4623504/144723848-6e5d0d77-fea0-4215-9de9-08ec9edb203c.png)


I made a set of fixes for it, because we run into the same problem with python-control:

- #16957
- jupyter/qtconsole#512
- ipython/ipython#13372

Unfortunately, for the full experience, all 3 packages need an update.
