### ISSUE TITLE
macOS shortcuts produce strange behavior in editor

### ISSUE THREAD

**Issue by max3-2** [spyder-ide/spyder#15069]
## Problem Description
In the editor, navigation shortcuts are not in order with system shortcuts on macOS. The most used ones are using CMD+<- or CMD+-> to navigate lines or ALT+ arrows to navigate lines. What makes this confusing is that combining this with SHIFT for selection reverts to the default OS behavior.

### What steps reproduce the problem?

1. Open spyder editor
2. Type some lines. Either try to use CMD + arrow to go to end or beginning or ALT + arrow to navigate words. ALT does not work and CMD navigates words. This is not expected - in the OS based editors its CMD for lines (or page with up down) and ALT for words 
3. Try the same with SHIFT to select. Now it works as expected.

### What is the expected output? What do you see instead?
Have the OS behavior with CMD being lines and ALT being words all the time, or at least have one behavior all the time.

## Versions

* Spyder version: 4.2.4

`Python 3.7.6 64-bit | Qt 5.12.8 | PyQt5 5.12.3 | Darwin 20.2.0 `

**Comment by steff456** [comment]
Hi @max3-2,

We need to standardize the shortcuts in the editor because I'm having the same behavior that you are getting. Right now, `Alt+arrow` will move to the next/previous cursor position maybe that's why you are getting different positions in the cursor by using that shortcut. 

We will work on this for a future release, if you want to see it fixed soon please consider to contribute to the project, we can give you all the guidance you need.

Thanks for reporting!

**Comment by steff456** [comment]
It depends on which shortcuts are you looking for, normally if they are bound to an action we are using the `create_action` method with the shortcut combination as a parameter. So, basically each plugin creates its own shortcuts, in this case you will need to look in the editor plugin to see where they are defined.

**Comment by 7hx1e** [comment]
duplicate? https://github.com/spyder-ide/spyder/issues/10854

**Comment by ccordoba12** [comment]
Thanks for pointing that out @7hx1e! Closing then.
