### ISSUE TITLE
History size increase

### ISSUE THREAD

**Issue by keeper90** [spyder-ide/spyder#15145]
What happened to the option to increase history log size in Spyder? I cannot find this option anywhere anymore

**Comment by steff456** [comment]
Hi @keeper90,

Which history log size are you searching for? Can you please let me know which plugin?

**Comment by keeper90** [comment]
@steff456 Thank you for the reply. The history.py tab (next to the IPython console tab), the one that lists all your previous commands. I remember being able to set its max size (in lines) under preferences, but can no longer find such an option.

**Comment by ccordoba12** [comment]
This option was removed in our 4.2.1. The explanation for that change is here: https://github.com/spyder-ide/spyder/pull/14443.

Now the default is `1000` lines. If you consider it should be higher, please suggest a new value.

**Comment by keeper90** [comment]
@ccordoba12  Thank you for the explanation. I went ahead and modified the spyder source code locally to make it work. To be honest, I find it hard to believe that "this option doesn't add much value". The value is tremendous for people who code a lot and have dozens of scripts per project (as things work in research) and just want a way to quickly find some parts of code they coded n days ago. I'm sure a big part of python community is content with 1000 lines, but obviously some are not and it's always best to let the end user decide what such values should be.

**Comment by ccordoba12** [comment]
@keeper90, I understand your points, but for us history is easily retrievable using IPython.

In any case, our plan is to improve that pane in Spyder 6 by using IPython history mechanism. When we do that, we could restore this option because it'd easy to make changes be applied instantly.

**Comment by nsn88** [comment]
I agree with @keeper90. I've been using Spyder for the past 6 years for my research work which involves a lot of prototyping and as a result my history log (set to the maximum of 10,000 entries) gets filled within 6 months. This is mainly because I use F9 a lot, for example, to re-define a function with slight modifications instead of running the whole script.

The history log also provides an overview/timeline of the work one has done over the past few months. I usually take backups of the history log every 6 months, but now with just 1000 entries, I'll have to take backups every week, which is not practical.

Today, I updated from Spyder `4.1.4` to `5.0.3` and found about this new history limit (1000 entries). I have no option but to revert back to `4.1.4` or maybe `4.2.0`, which I think is the last Spyder version with maximum history limit as 10,000.

@ccordoba12 I think 1000 is a good default value, but as @keeper90 said, it's best to let the end user decide these values, to the extent that they don't crash/slowdown the application. If you'd ask me, I would prefer a maximum limit of 50,000 or 100,000, if that's possible.

**Comment by xiaoyuejin** [comment]
Hi @keeper90 May I ask you where to change to modify the 1000 line limit? My 1000 lines fill up in a few days or a week at most. I can't understand the motive behind limiting it to 1000 at all...

> @ccordoba12 Thank you for the explanation. I went ahead and modified the spyder source code locally to make it work. To be honest, I find it hard to believe that "this option doesn't add much value". The value is tremendous for people who code a lot and have dozens of scripts per project (as things work in research) and just want a way to quickly find some parts of code they coded n days ago. I'm sure a big part of python community is content with 1000 lines, but obviously some are not and it's always best to let the end user decide what such values should be.

**Comment by weixu02** [comment]
> @ccordoba12 Thank you for the explanation. I went ahead and modified the spyder source code locally to make it work. To be honest, I find it hard to believe that "this option doesn't add much value". The value is tremendous for people who code a lot and have dozens of scripts per project (as things work in research) and just want a way to quickly find some parts of code they coded n days ago. I'm sure a big part of python community is content with 1000 lines, but obviously some are not and it's always best to let the end user decide what such values should be.

I totally agree the option to increase history buffer is important for many users. Can anyone please share the workaround to change the source code locally to increase the history buffer? Thanks!
