### ISSUE TITLE
run line keyboard shortcut

### ISSUE THREAD

**Issue by jasonebox** [spyder-ide/spyder#15189]
I love keyboard shortcuts, use run cell and run all --- all the time. ...Can we please get ability to run at line where cursor is without having to select text and run selection? 

merci,

Jason

**Comment by ccordoba12** [comment]
Hey @jasonebox, thanks for reporting. If the line is a complete Python statement (e.g. `a = 10`), that's certainly possible.

If that's not the case, like the first line in this block:

```python
for i in range(10):
    print(i)
```

You have to select the two lines in order to run a piece of code that is complete.

However, we'll try to improve that in the future.
