### ISSUE TITLE
Scrolling down through arrays from object inspector is very slow.

### ISSUE THREAD

**Issue by seanysull** [spyder-ide/spyder#15474]
Trying to scroll down to bottom of an array opened from object inspector is a very tedious process requiring one to scroll to the bottom, then past with the mouse for a bit then the scroller goes back to the middle, rinse and repeat until finally the whole array is covered by the scroll bar. It affects the newest version of spyder and previous versions. Is there any way to avoid this behaviour?

**Comment by juanis2112** [comment]
Hi @seanysull. Thanks for opening this issue. We are sorry to tell you that this is something we can't fix, since this is the best we can do it to avoid performance issues. When having very large objects, we need to load a limited number of rows at a time in order not to block the interface while doing it.
