### ISSUE TITLE
Please provide a way to disable dependencies version checks.

### ISSUE THREAD

**Issue by trougnouf** [spyder-ide/spyder#15577]
Spyder is wonderful, and after years of thoroughly enjoying using it I have to turn to another IDE.

Once again it won't start; Arch updated a library that Spyder will specifically refuse to start with, likely because it has been marked incompatible after failing to pass a test. 

The Arch Linux packager's fix is typically to remove the dependency check from the source, but it hasn't been done yet.

My options are to dig into Spyders' source to disable the check, or as I guess the developers would like fix the broken test. However, I have a job or research to be doing so that's not an option and I can only allocate so much unscheduled time to hacking around my IDE.

There is no **flag** to **turn dependencies checks into warning**, nor documentation on how to ignore them. Not even a stern warning against reporting bugs with such monstruous configuration, or a donation request to support said fixes.

My only solution to this perpetual planned obsolescence is to adapt my workflow to a different IDE, which I am doing now by moving my files around (because only Spyder allows to have many results files in the same root as my source code).

So long and thanks for all the happier coding.

**Comment by ccordoba12** [comment]
Hey @trougnouf, thanks for reporting. You said

> The Arch Linux packager's fix is typically to remove the dependency check from the source, but it hasn't been done yet.

This is really bad because it forces Spyder to work with versions it hasn't been tested with. I understand it's an issue for Linux maintainers because they always want to be using the latest versions of everything, but it's not something we can really do something about.

If you install Spyder using Anaconda or pip in a virtualenv, you won't encounter this problem at all.

> There is no flag to turn dependencies checks into warning, nor documentation on how to ignore them. Not even a stern warning against reporting bugs with such monstruous configuration, or a donation request to support said fixes.

We warn about missing/incorrect dependencies so that users know Spyder will fail to work with the ones the user has installed at the moment (even if it manages to start). There are even dependencies for which we can't use the latest version because they simply don't work with Spyder (right now that's the case for pyls-spyder 0.4.0).

So, it's not a matter of us not doing our job (so that we need donations to fix things here). It's simply that the Linux distros model of packaging projects doesn't work for us. Anaconda or pip don't have this problem because both install the right versions of our dependencies every time.

> My only solution to this perpetual planned obsolescence is to adapt my workflow to a different IDE, which I am doing now by moving my files around (because only Spyder allows to have many results files in the same root as my source code).

Sorry to hear that, but this is not something we can fix. To me, it's really the fault of Arch maintainers: if they want to force Spyder to work with whatever dependencies they want, they should inform that to their users and turn off our dependencies check mechanism. Or, even better, they should stop distributing Spyder because I'm sure some of our functionality is broken there.

> So long and thanks for all the happier coding.

Ok, I'm also going to close this one because we don't plan to address it. If you want to keep using Spyder, please ditch Arch packages and use Anaconda or pip instead.
