### ISSUE TITLE
TypeError: type 'types.GenericAlias' is not an acceptable base type

### ISSUE THREAD

**Issue by pedro-acunha** [spyder-ide/spyder#15612]
## Problem Description
Unable to start Spyder after Python update.

### What steps reproduce the problem?

1. Initiating spyder via terminal
2. Unable to initiate. Rises a TypeError

### Paste Traceback/Error Below (if applicable)

```python-traceback

Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/Users/pedrocunha/miniconda3/lib/python3.9/site.py", line 73, in <module>
    import os
  File "/Users/pedrocunha/miniconda3/lib/python3.9/os.py", line 29, in <module>
    from _collections_abc import _check_methods
  File "/Users/pedrocunha/miniconda3/lib/python3.9/_collections_abc.py", line 416, in <module>
    class _CallableGenericAlias(GenericAlias):
TypeError: type 'types.GenericAlias' is not an acceptable base type

```

## Versions

* Spyder version: 5.0.0
* Python version: 3.9.4
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: macOS Big Sur version 11.2.3

**Comment by andfoy** [comment]
Hi @pedro-acunha, thanks for opening this issue. By looking at the stacktrace, it would seem that your anaconda environment is corrupted, have you tried to install Spyder on a fresh environment to see if it fixes your issue? If not, please try to reinstall your anaconda distribution. Since you are using Mac, you can also use one of our standalone installers, which isolate all the Spyder requirements, which is less error-prone than Anaconda installations: https://github.com/spyder-ide/spyder/releases/download/v5.0.2/Spyder.dmg

**Comment by pedro-acunha** [comment]
Hi @andfoy , thank you for the answer.
Installing the standalone installer solved the problem. I did tried to install in a fresh environment and reinstalling the anaconda distribution. The problems appears after updates, probably corrupting the environment. It is solved now. Thank you again.
