### ISSUE TITLE
the warning of "from sympy import *"

### ISSUE THREAD

**Issue by Vincent0706** [spyder-ide/spyder#15728]
## Problem Description
When I use Spyder write the code, I found there are too many warnings, like this
![image](https://user-images.githubusercontent.com/82581024/120092890-e5138580-c148-11eb-81db-1bb7a3ebc4d2.png)

How to explain this situation?

### What steps reproduce the problem?
```
from sympy import *
t = Symbol('t')
x = Symbol('x')
m = integrate(sin(t) / (pi - t), (t, 0, x))
print(m)
ans = (integrate(m, (x, 0, pi)))
print(ans)
```

* Spyder version: 5.0.3
* Python version: 3.9
* Qt version: 
* PyQt version: 
* Operating System name/version: win10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @Vincent0706, thanks for reporting. You said

> When I use Spyder write the code, I found there are too many warnings, like this

To avoid those warnings, you need to change your initial import to

```python
from sympy import Symbol, pi, integrate, sin
```

Otherwise, Spyder will report that those objects don't seem to be properly defined. The problem is that it's impossible for Spyder to tell what objects have been imported when you do star imports, i.e. imports of the form

```python
from sympy import *
```

If you don't want to see those warnings and keep using star imports, please go to the menu

    Tools > Preferences

then to the section

    Code completion > Linting

and disable the option called

    Enable basic linting

We don't recommend you to do that because you will lose the ability of seeing warnings and errors reported in the editor, but it's up to you.
