### ISSUE TITLE
Editor slow when editing any code

### ISSUE THREAD

**Issue by dbau** [spyder-ide/spyder#15747]
### What steps will reproduce the problem?

Hi, 

I know this issue have already been reported in the past, but I still don't know how to fix it.
I have four files opened with more than 1000 lines of code each. The console works fine, but the editor hangs for a couple of seconds whenever I change some code. Code completion does not work (or it is so slow that it rarely completes anything).

What parameters should I change to improve usability?

Thanks a lot,
Davide

**Comment by ccordoba12** [comment]
Hey @dbau, thanks for reporting. This problem is being tracked on issue #15631.

To workaround the problem for large files, please disable folding in the menu `Source > Show code folding`. That should avoid it for now, until we can properly fix it later this year (that requires a huge refactoring in the editor).

**Comment by analyticssolvers** [comment]
Hi,
Install anaconda. Then apply conda update anaconda. Then conda install spyder = 5.0.4.
I started to use it perfectly and within the day, it started to be extremely slow with sudden freezes of 3 seconds and returned to working normally. It goes from normal to super slow operation every minute. I do not know what to do. I'm looking for a solution and I can't find it. I am about to move to another IDE. Is there a solution? 

Thanks a lot,
Martin
