### ISSUE TITLE
UI has icons overlapping text

### ISSUE THREAD

**Issue by Jrcarand** [spyder-ide/spyder#15770]
### What steps will reproduce the problem?

All dropdown menus have their icons on top of the text for me. I use 150% scaling on a 1440p monitor. Had no problems in v4.

**Comment by Jrcarand** [comment]
w10, OS build 19042.985, if that is of any help.

**Comment by Effervex** [comment]
Same issue here.

**Comment by ccordoba12** [comment]
Thanks for reporting. This error is already fixed in our latest version (5.0.3).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows or Mac installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

**Comment by Jrcarand** [comment]
Thanks!!
