### ISSUE TITLE
Traceback output in console does not link to position

### ISSUE THREAD

**Issue by Jrcarand** [spyder-ide/spyder#15772]
### What steps will reproduce the problem?

When I have an Error exception, the typical "*file*, line XX, in <module>" does not link to the position indicated. The mouse cursor still changes to a "link type", but nothing happens when pressing.

**Comment by ccordoba12** [comment]
Hey @Jrcarand, thanks for reporting. This error is already fixed in our latest version (5.0.3).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder
