### ISSUE TITLE
Error when trying to open a new window on Spyder 

### ISSUE THREAD

**Issue by dkobayas-cyber** [spyder-ide/spyder#15794]
### What steps will reproduce the problem?

After I updated Spyder to the newest version, I get an error everytime I try to open my code in a new window. 

Moreover, some icons in the tool bar looks strange. For example, when you open a pulldown of 'Run', you can see 'Run' in the first row, and there is a triangular icon next to the text 'Run'. In my case, however, the icon and the text 'Run' is overlapping. I have the same issues for all the menus in the pulldowns. 

Could you tell me how to fix this problem?

**Comment by dkobayas-cyber** [comment]
Here is a screenshot of
![error](https://user-images.githubusercontent.com/85417498/120906403-27e0cc00-c627-11eb-977c-3cc00b7ec805.png)
 the UI error I mentioned above.

**Comment by ccordoba12** [comment]
Hey @dkobayas-cyber, thanks for reporting. This error is already fixed in our latest version (5.0.3).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder
