### ISSUE TITLE
"Please verify that your firewall or antivirus allows Python processes to open ports in your system"

### ISSUE THREAD

**Issue by TimurKhan** [spyder-ide/spyder#15863]
Yes, I am aware that this duplicates similar questions. But I strongly ask, no, I demand that until you give a clear answer to what I must do to get your program back into service, this question is open. None of the threads that were closed have an answer or solution.
I understand very well that the main enemy of a developer is the user. But still...
Spider 5.0.1 Windows 10 Python 3.8

**Comment by ccordoba12** [comment]
Hey @TimurKhan, thanks for reporting. You said

> I demand that until you give a clear answer to what I must do to get your program back into service

We can't give a straight answer about how to fix what this message is asking you to do, because there are several antivirus and firewalls out there, each one with its own way to set policies and blacklist/whitelist other programs.

So you need to check your what current antivirus/firewall is and look for tutorials in Youtube or elsewhere on how to change rules for it. Those rules need to be applied to the Python executable of your installation (i.e. `python.exe` under `C:\Users\<username>\Anaconda\` if you're using Anaconda), not to Spyder, because Spyder is really a Python application.

Finally, we weed to open several ports in users' computers to run code in the IPython console and to provide code completion and linting in the editor. Those things work in external processes, so we need those ports to establish a two-way communication with them.

**Comment by ccordoba12** [comment]
Please try to do that and let us know if it works for you.

**Comment by TimurKhan** [comment]
Close! I must working. And I reinstall all.

пн, 14 июн. 2021 г., 19:58 Carlos Cordoba ***@***.***>:

**Comment by ccordoba12** [comment]
So, is Spyder working for you now? Or you simply prefer not to keep looking at this?

**Comment by gepcel** [comment]
I'm facing this issue for a very long time. I totally disable the firewall, and restart the spyder, the same message still shows up. And may I ask what are those ports that need to be opened?

**Comment by TimurKhan** [comment]
I wasted a lot of time. Neither antiviruses and firewalls have anything to do with the problem. The reason is the anaconda updates and the very unstable Spider core. By the way, during work, failures constantly occur and error notifications pop up, as a rule, when saving a file. 
I've gotten used to the Spider over the years. And I don't like Charm. Yes, it happens. But this kind of work is exhausting.

As for the problem, one of the methods described in one of the closed requests helped. Demolish Anaconda and reinstall it. A hell of a solution.

**Comment by ccordoba12** [comment]
@gepcel, we show this message in case our code completion and linting machinery in the editor fails to start. The most common cause is due firewall or antivirus, but it could also happen due to a mix of conda and pip packages. That's why, if you're having that problem, you could try to reinstall Anaconda (as @TimurKhan did) or install in another conda environment, by running the following commands in the Anaconda Prompt:

        conda create -n spyder-env spyder
        conda activate spyder-env
        spyder

**Comment by ccordoba12** [comment]
@TimurKhan, you said:

> The reason is the anaconda updates and the very unstable Spider core

That's why we created installers for Windows and macOS, you can download from here:

https://github.com/spyder-ide/spyder/releases

**Comment by ccordoba12** [comment]
I'm going to close this issue because I don't think there's something else I can help with here.

**Comment by TimurKhan** [comment]
Yes, of course!
Thanks for link!
