### ISSUE TITLE
When I update the spyder, I must delete the old config file, otherwise the spyder won't open.

### ISSUE THREAD

**Issue by Vincent0706** [spyder-ide/spyder#15882]
When I update the spyder, I must delete the old config file, otherwise the spyder won't open. How can I solve the problem?

**Comment by dalthviz** [comment]
Hi @Vincent0706 could you be more specific regarding your setup and the from what version to what version are you doing the update?

Without that there is not much we can do sorry :/

Let us know!

**Comment by Vincent0706** [comment]
I setup spyder with pip. 
My python version is 3.9
I updata my spyder from 5.0.3 to 5.0.4
I use the command "pip install --upgrade spyder"

**Comment by dalthviz** [comment]
Sorry to hear that @Vincent0706 , did you saw any traceback after the update? Maybe you could run `spyder` from the console using the `--debug-info verbose` flag to check for any traceback. Also, you can try instead of deleting the `.spyder-py3` folder to run spyder with the `--reset` flag. I could be wrong but maybe some sort of permission error is causing the previous preferences to not be available after doing the update with pip.

Let us know if you are able to get more info about the error by doing something of the above any new info in order to reproduce this in our side is greatly appreciated :)

**Comment by Vincent0706** [comment]
https://user-images.githubusercontent.com/82581024/122585229-db1cdc80-d08d-11eb-894f-48497d6ce106.mp4


This is my operation video. I have upgrade to 5.0.4. You can find that I can't open the spyder. It only show the symbol.

**Comment by dalthviz** [comment]
Thanks for the video @Vincent0706 is really strange what is happening to you :/ Could you try to run from a console with admin rights just to be sure is not a permissions problem while reading the preferences or something like that? Also, what happens if you run `spyder --reset` ?

Let us know!

**Comment by Vincent0706** [comment]
https://user-images.githubusercontent.com/82581024/122628027-2f53ab00-d0e6-11eb-9072-e9937452dbe0.mp4


It has the same situation.

**Comment by dalthviz** [comment]
Still not sure what could be causing this @Vincent0706 . Maybe you could try our installers and check if something in our documentation and troubleshooting guide helps: https://docs.spyder-ide.org/current/troubleshooting/first-steps.html#where-to-go-from-here

Also, you could give it a try to our installers: https://github.com/spyder-ide/spyder/releases/latest

Otherwise I'm not sure what else to try to help you or how to get more information sorry :/

Let us know if something of the above helps

**Comment by Vincent0706** [comment]
Thanks a lot. But I think I'd better use the old version before the spyder become more stable. And I think the installers always install a new python in my computer, so I don't want to use the installers.
Thank you for your help. Hope spyder can become better.

**Comment by dalthviz** [comment]
@Vincent0706 last thing to check, can you try to run `spyder --debug-info verbose --debug-output file` and check for a `spyder-debug.log` file in the current working directory where the console is ? Let us know

**Comment by Vincent0706** [comment]
A good news, my problem seems to have been solved in version 5.0.5.
If I meet my problem again, I can check for the `spyder-debug.log` to report my problem.

**Comment by dalthviz** [comment]
Awesome, glad is working now for you!

Then I will close this one but yes please, if you face a similar issue open a new issue with the details :+1:
