### ISSUE TITLE
spyder was unables to retrieve the value of this variable from the console

### ISSUE THREAD

**Issue by BarryLiu97** [spyder-ide/spyder#15937]
### What steps will reproduce the problem?

Hi, I was using mne package, and when I created a instance of BaseRaw or other class, spyder said
```
spyder was unables to retrieve the value of this variable from the console
```
after I clicking the name of the variable in Variable Explorer, but there is nothing in console. It seems that Spyder doesn't support display complex class attribution?

**Comment by ccordoba12** [comment]
Hey @BarryLiu97, thanks for reporting. How did you install Spyder? And what package BaseRaw belongs to?

**Comment by BarryLiu97** [comment]
I installed Spyder using an exe file for windows10, and the class BaseRaw belongs to package MNE.
You could just ```pip install mne```
If you need a sample data ,here it is https://drive.google.com/file/d/1NV_su464M4ZWogLTouU2QT5kN0JiWuCE/view?usp=sharing.
The code is 
```
import mne
fpath = 'sample.fif'
data = mne.io.read_raw_fif(fpath)
```

**Comment by ccordoba12** [comment]
> I installed Spyder using an exe file for windows10

Ok, then the problem is that Spyder is unable to inspect mne objects because mne is not part of our exe installer.

So for that to work (until we can address that problem), you need to install Spyder in the same environment where you installed mne and run it from there.

Please do that and let us know if it works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
