### ISSUE TITLE
CREATING A POP UP

### ISSUE THREAD

**Issue by STORMREPPER** [spyder-ide/spyder#16048]
### What steps will reproduce the problem?

###WHEN I OPEN MY SPYDER IT CREATES A POP-UP 
THE POP SAYS:
THE CODE EXECUTION CANNOT PROCEED BECAUSE VCRUNTIME140.dll missing whereas i check in files it was present, and i reintsalled spyder around 5-6 TIMES

**Comment by steff456** [comment]
Hi @STORMREPPER,

How are you installing Spyder? 

If you are working on Mac or Windows I recommend you to use the installers available here: https://github.com/spyder-ide/spyder/releases/tag/v5.0.5. You can also install it with conda, but please remember to try to avoid mixing pip with conda because that could damage your environment.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
