### ISSUE TITLE
kernel restars 

### ISSUE THREAD

**Issue by MuhammadRRahman** [spyder-ide/spyder#16082]
### What steps will reproduce the problem?

During execution of any program, kernel restarts and deletes all variables.

**Comment by ccordoba12** [comment]
Hey @MuhammadRRahman, thanks for reporting. Please open the Anaconda Prompt, run the following command there

    conda list

and post its output here.

**Comment by MuhammadRRahman** [comment]
[Condalist.txt](https://github.com/spyder-ide/spyder/files/6882604/Condalist.txt)
Hi 
Many thanks, here's the conda list output.
Look forward to hearing from you.

**Comment by ccordoba12** [comment]
Ok, I can see how you have a mix of conda, conda-forge and pip packages, which is really not good because packages from those different sources are incompatible.

My only advice is for you to remove and reinstall Anaconda. Please see the second part of [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to understand how to properly do that. The video also explains what to do to use pip and conda-forge packages without causing conflicts.

**Comment by MuhammadRRahman** [comment]
Hi Thanks, I have followed steps. However, now Spyder shows:
**h5py package not avilable -- using ascii conversion**

Any thoughts?
Many thanks
