### ISSUE TITLE
5.1.1 : omitted indentation when pasting with the editor

### ISSUE THREAD

**Issue by texadactyl** [spyder-ide/spyder#16159]
Installed 5.1.1 and reset to factory defaults.
Then, I created a small function:
```
def f():
    x = 1
    y = 2
```
I wanted to add another assignment just after ```x = 1```.  So, I copied that entire line and pasted it.  This was the result:
```
def f():
    x = 1
x = 1
    y = 2
```
Uninstalled 5.1.1 and installed 5.0.5.  Then, I reset to factory defaults and created the same small function:
```
def f():
    x = 1
    y = 2
```
Then, I copied that entire ```x = 1``` line and pasted it.  This was the result:
```
def f():
    x = 1
    x = 1
    y = 2
```

IMO, the 5.0.5 editor behaved correctly but the 5.1.1 editor neglected to paste in the indentation.

**Comment by ccordoba12** [comment]
Hey @texadactyl, thanks for reporting. I can reproduce this error.

@impact27, could you take a look at this?

**Comment by impact27** [comment]
The expected behaviour is that it will correct the indentation to where your cursor is. If you add a line below `x = 1` you should get (`|` is the cursor):
```
def f():
    x = 1
    |
    y = 2
```
If you then paste you should get:
```
def f():
    x = 1
    x = 1
    y = 2
```
If instead you want to de-dent, you should, from:
```
def f():
    x = 1
    |
    y = 2
```
Press delete:
```
def f():
    x = 1
|
    y = 2
```
Then paste:
```
def f():
    x = 1
x = 1
    y = 2
```
The new logic tries pastes the code in the clipboard on the indentation your cursor is.

**Comment by ccordoba12** [comment]
@impact27, if the first line a user is trying to paste contains some indentation, I think we should preserve it, and adjust the indentation of all other lines according to that.

What do you think?

**Comment by texadactyl** [comment]
Folks are used to the spyder editor as it was through 5.0.5.  The 5.1.1 editor-paste behaviour will require a lot of users to re-think the way they do copy/cut and paste of large blocks of code.  Small segments are no big deal.

I do not copy/cut and paste a large block of code spanning multiple lines the way you showed.  I'd much rather do a large collection of lines in a line-oriented fashion (cursor on first column).  Less chance of a mess.  If I need to indent or unindent afterwards, I can plan for that.

However, there must be some benefit for this change or you would not have made it.  I'll try to figure that out.

**Comment by impact27** [comment]
What should happen in the case when pasting `    x = 1`:
```
def f():
    x = 1
    |
    y = 2
```
I think:
```
def f():
    x = 1
    x = 1
    y = 2
```
if more helpful than:
```
def f():
    x = 1
        x = 1
    y = 2
```
But the case in this issue is more debatable. Maybe we could only de-dent if it would result in a non-valid code?

**Comment by impact27** [comment]
I think a sound logic would be for pasting to do:

 1. When pasting multiline text, it keeps the following lines at the same indentation as the first line. Exception: The following lines maximum de-dent is the smallest indentation in the clipboard.
 2. For python code, it tries to avoid creating over-indented lines (created because of auto-indentation). To achieve this, it will de-dent until reaching a valid indentation. The resulting indentation can not be smaller than either:
     - The current cursor position
     - The copied indentation

Opened a PR https://github.com/spyder-ide/spyder/pull/16164

**Comment by impact27** [comment]
For example, pasitng `    x = 1` would result in:
```
def f():
    x = 1
|
    y = 2
```
```
def f():
    x = 1
    x = 1
    y = 2
```
or:
```
def f():
    x = 1
    |
    y = 2
```
```
def f():
    x = 1
    x = 1
    y = 2
```
or:

**Comment by impact27** [comment]
@ccordoba12 Do you think this is reasonable? Alternatively we can turn off the point 2 completely.

**Comment by sphh** [comment]
This new behaviour also puzzled me and it took me some time to figure out the logic behind it.

https://github.com/spyder-ide/spyder/issues/16159#issuecomment-894166399 sounds logic to me.

There might be another solution, based on my current workflow:

1. I paste some lines
2. I select those pasted lines
3. I indent them with TAB and SHIFT-TAB to the position I want them to be in

So my suggestion would be to paste them according to any of the two policies but select the pasted lines automatically after pasting. That way you are immediately able to adjust the indentation level after pasting.

What do you think?

**Comment by impact27** [comment]
The problem with selecting is that if you paste and then write it would remove the lines. The challenge is to do something usefull but try to avoid messing up with the expectations of the user. I don't think the user would expect to have the pasted text selected, even it it could be useful.

**Comment by sphh** [comment]
I also just noticed a problem: If you past text inside some existing text, it might not be such a good idea, if it becomes selected.

Hence I would like to update my proposal, to select it only, if the selected text contains at least one newline character. Then only blocks would get selected after pasting.

Yes, it is impossible to make it right for everyone in every use case!!

Alternatively, if that is not an option, a way to select the just-pasted content with a hot key would improve the workflow massively …

**Comment by texadactyl** [comment]
Your users have a variety of habits and concepts if convenience. Cannot please them all. If it were me doing this, I would emphasize safety and consistency.

**Comment by sphh** [comment]
Yes, indeed!

I believe that @impact27's suggestion is a good solution. If that is not acceptable there is always my suggestion, either with autoselecting the pasted block or adding a keyboard hotkey to select it after pasting, to be able to adjust the indentation quickly (this hotkey can also be added in addition to @impact27's solution and might improve it even further!)

**Comment by ccordoba12** [comment]
> @ccordoba12 Do you think this is reasonable?

Yeah, that sounds quite reasonable to me.

**Comment by sphh** [comment]
If I apply the changes from https://github.com/spyder-ide/spyder/commit/48065f03dc7edb04093425032f9c69f0a26dda25 (I double checked it) I get this error:

```python3
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/spyder/plugins/editor/widgets/codeeditor.py", line 2836, in paste
    max_dedent = min(
ValueError: min() arg is an empty sequence
```

What I did?
1. I started Spyder, which opened a couple of files, because they belonged to a project I was working before.
2. In the file:
```python3
#!/usr/bin/env python3
"""
Blabla

"""

import sys
import argparse
import ast

try:
    import colored_traceback
except ImportError:
    pass
else:
    colored_traceback.add_hook()

...
```
I positioned the cursor at the start of the line `   import coloured_traceback` and selected that line with `Shift+LineDown`.
3. I pressed `Ctrl+X`.
4. I pressed `Ctrl-V`
and got the above error.

**Comment by ccordoba12** [comment]
I can't reproduce this error. Could you upload an animated gif that shows exactly how to generate it?

**Comment by sphh** [comment]
Just in case, I messed something up, I copied this file (https://raw.githubusercontent.com/spyder-ide/spyder/48065f03dc7edb04093425032f9c69f0a26dda25/spyder/plugins/editor/widgets/codeeditor.py) over the existing `codeeditor.py`.

In the following screencast I use `Ctrl-X` and `Ctrl-V` after having selected the line:
https://user-images.githubusercontent.com/4856462/129401521-0c276e40-c1e2-409d-aa14-e52ebeb03055.mp4

**Comment by sphh** [comment]
I might have an idea, what is going on:

The selected text is
```
    import colored_traceback

```
(note the empty line at the end).

https://github.com/spyder-ide/spyder/blob/48065f03dc7edb04093425032f9c69f0a26dda25/spyder/plugins/editor/widgets/codeeditor.py#L2803 splits this into
```
["    import colored_traceback", ""]
```
`remaining_lines` hence becomes `[""]`

Finally https://github.com/spyder-ide/spyder/blob/48065f03dc7edb04093425032f9c69f0a26dda25/spyder/plugins/editor/widgets/codeeditor.py#L2830 evaluates to `True`, because `len[""]` is >0.

But https://github.com/spyder-ide/spyder/blob/48065f03dc7edb04093425032f9c69f0a26dda25/spyder/plugins/editor/widgets/codeeditor.py#L2838 removes the only entry (`if line.strip() !=n ""`), hence the list for the call of `min()` is empty!

**Comment by sphh** [comment]
I solved this by changing the statement https://github.com/spyder-ide/spyder/blob/48065f03dc7edb04093425032f9c69f0a26dda25/spyder/plugins/editor/widgets/codeeditor.py#L2836
to
```python3
            indentations = [
                self.get_line_indentation(line)
                for line in remaining_lines if line.strip() != ""]
            if indentations:
                max_dedent = min(indentations)
                lines_adjustment = max(lines_adjustment, -max_dedent)
```
