### ISSUE TITLE
You have missing dependencies!   # Mandatory: pyls_spyder >=0.4.0 : 0.3.2 (NOK)

### ISSUE THREAD

**Issue by fabianofrank** [spyder-ide/spyder#16160]
The quote below was the closest answer I've found for missing dependencies on Spyder 6.0.0dev0 (https://github.com/spyder-ide/spyder/releases/tag/v5.1.0) which is not available for update through Anaconda. Does anybody know how solve this?

"Hey @norbmett, thanks for reporting. You probably installed that version with pip, which is picked up before the conda one.

To see where that other version is coming from, please open Spyder, go to the menu `View > Panes > Internal console` and write there the following commands

```python
import parso
parso.__file__
```

as shown below

![imagen](https://user-images.githubusercontent.com/365293/127518940-d7aec15c-a107-4d96-be47-4e599306cf4f.png)

That will show you where the other Parso is installed.

After that, please post the result here so I can tell you how to fix the problem. " 

_Originally posted by @ccordoba12 in https://github.com/spyder-ide/spyder/issues/16100#issuecomment-889236323_"

**Comment by dalthviz** [comment]
Hi @fabianofrank sorry for the late response. Did you follow the instructions that the referenced comment describes (check for the `parso` path)? If so then please submit here the path that is being retrieved.

Other than that, I would suggest for you to create a new env and install there the latest Spyder version. Since seems like you use anaconda, you could run something like this (using the `conda-forge` channel):
    
     conda create -n spyder_env python=3.9 spyder=5.1.5 -c conda-forge

Let us know if that helps

**Comment by dalthviz** [comment]
Closing due to lack of response

**Comment by itscarlo-nobnos** [comment]
If I may, I had a similar issue after installing via conda.  I am a new entrant to this environment ----- I ran the:

import parso
parso.__file__

With this result:
'/usr/lib/python3.11/site-packages/parso/__init__.py'

What am I missing?j This came up on an error window on:
* Spyder version: 5.4.0  (pip)
* Python version: 3.11.0 64-bit
* Qt version: 5.15.7
* PyQt5 version: 5.15.6
* Operating System: Linux 6.0.12-300.fc37.x86_64

Thanks for any insight!!!!! Cheers!

**Comment by dalthviz** [comment]
Hi @itscarlo-nobnos , from your setup info seems like you installed spyder using pip? Maybe the problem comes from mixing conda installed packages with pip installed packages in your env? Also, is the issue you are experiencing the same as in the OP here (`You have missing dependencies! # Mandatory: pyls_spyder >=0.4.0 : 0.3.2 (NOK)`)? Maybe it could be worthy to open a new issue with the specific message/behavior description you are experiencing, sharing there your full conda environment details and adding a reference to this issue if you thing is related.

Also, the suggestion above could be useful (creating a new environment only using the conda-forge channel and conda packages). A more general command to do that (to get the latest Spyder version available will using Python 3.9) would be:

    conda create -n spyder_env python=3.9 spyder -c conda-forge

**Comment by itscarlo-nobnos** [comment]
Thanks @dalthviz , I will pursue your suggestions. I could have sworn that I followed the conda instructions but may have inadvertently mixed them up somehow. I will give it a try and post the results here and if necessary, start a new thread and reference this post like you suggested.  Thanks again!!!!!!

**Comment by itscarlo-nobnos** [comment]
Update*****

After your advice, I ran:

conda activate spyder_env

That command worked beautifully! A cleaner environment for sure!
