### ISSUE TITLE
translation <hu>

### ISSUE THREAD

**Issue by dabzse** [spyder-ide/spyder#16175]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I wrote you an e-mail about the Hungarian translation I made offline on my machine. Still not completed.... Did you read it?
You can find it on that place, just upload here, overwrite the existing one. And add that to the online place. I will register there and continue there when I will have time for it!
I'm so sorry about the inconvenience!
Thank you!

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @dabzse, thanks a lot for your help with this! You said:

> I wrote you an e-mail about the Hungarian translation I made offline on my machine. Still not completed.... Did you read it?

Unfortunately, this is not the way we handle translations in Spyder. I mean, we don't touch `po` files directly but instead use Crowdin to update our translations:

https://crowdin.com/project/spyder

So, I'm afraid you'll have to copy/paste the contents of the file you sent us there. Then your translation will be automatically updated here and after that we'll enable Hungarian in our interface.

It's also important that you're part of our translators team in Crowdin because when new versions are about to be released, I ask the team to give us a hand with new strings.

It's very unfortunate that you haven't contacted us before about this, but I hope you won't have too much trouble using Crowdin.

**Comment by ccordoba12** [comment]
Let us know if you need something else from us.

**Comment by ccordoba12** [comment]
I just approved your request to be part of our team on Crowdin, so I guess you're ok with updating your translation there.

Thanks for your help again and sorry for the extra job of using Crowdin. However, I hope in the long run you'll find it much more useful.
