### ISSUE TITLE
Spyder does not launch QWidget: Must construct a QApplication before a QWidget

### ISSUE THREAD

**Issue by HaoSun1** [spyder-ide/spyder#16281]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder does not launch QWidget: Must construct a QApplication before a QWidget

### What steps reproduce the problem?

1.  Open Anaconda CMD
2.   spyder
3.   

### What is the expected output? What do you see instead?
Expect spyder to launch  instead get  Must construct a QApplication before a QWidget

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version:  5.0.5
* Python version:   3.8.11
* Qt version:   5.12.9
* PyQt version:  5.12.3
* Operating System name/version:   Windows 10

### Dependencies

```
Cannot launch Spyder
```

Okay Spyder can launch in new virtual environment which I guess is good enough.

**Comment by dalthviz** [comment]
Hi @HaoSun1 sorry for the late reply, could you try to update to our latest release and check again? If the problem persist could you try to create a new environment and try again (by running something like `conda create -n spyde_env -c conda-forge python=3.8.11 spyder`)? Let us know!

**Comment by HaoSun1** [comment]
> Hi @HaoSun1 sorry for the late reply, could you try to update to our latest release and check again? If the problem persist could you try to create a new environment and try again (by running something like `conda create -n spyde_env -c conda-forge python=3.8.11 spyder`)? Let us know!

Works now thanks  although can someone explain why installing spyder to base is a problem? 
Also weird quirk I get a message The procedure enty point ?PyWInObject_AsWriteBuffer@@YAHPEAU_object@@PEAPEAXPEAKH@Z could not be located in the dynamic link library C:\WINDOWS\SYSTEM32\python38.dll   on launch

**Comment by dalthviz** [comment]
I guess the problem with installing/updating Spyder and other libraries in the base environment is that you could start experiencing quite tricky issues that either can take you a long time to figure out or you just give up and then end up having to reinstall the whole distribution. Taking that into account, using environments could be better since you isolate possible problems to a specific environment and if it that specific environment doesn't work anymore you can remove it and create a new one without having to do a full reinstallation.

Regarding the message you are getting my guess is that something related with your anaconda installation is most probably broken. Did you already did a reinstallation, right? If not maybe to get rid off any inconsistency you should reinstall anaconda but this time create from the beginning a new environment for Spyder or the packages you want to use
