### ISSUE TITLE
Spyder 5 read files in "Document" automatically

### ISSUE THREAD

**Issue by mIgLLL** [spyder-ide/spyder#16295]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I upload all my files in C:\Users\xxx\Document to OneDrive, and release the space. So, these files will be downloaded into my computer when any software try to read them.
When I update my Spyder to 5.0.5, I find that the Spyder will read my files in "Document" even these files are not related to python. (They are some zip-files.) I notice this because OneDrive show me that my files are downloading because of python!

I think Spyder should pay more attention on user's Privacy!
Spyder 4.2.5 is fine.
### What steps reproduce the problem?

1. upload your files to OneDrive
2. Release the space
3. Run Spyder 5.0.5

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by dalthviz** [comment]
Hi @mIgLLL sorry for the late response and thank you for your feedback! Not totally sure but maybe this is caused since the Current Working Directory set for Spyder contains your `Document` folder. I think by default the working directory is the user/home directory so if that's the case, probably Spyder reading your files is due the Files Pane (a file explorer like pane). To prevent this I would suggest to change your current working directory inside Spyder (top right combobox) to something else. 

Let us know if something of the above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
