### ISSUE TITLE
Spyder slows internet 20mps -> 1mps

### ISSUE THREAD

**Issue by amandamiotto** [spyder-ide/spyder#16318]
Hey team - This has started to happen to me, but in version 5.05 (via anaconda) on Win 10. My internet speed is going from 20ish mps to 1mps . I've killed everything else except Windows Defender (can't as company SOE) and when I try to downgrade Spyder to 4.0 it now has the same issue - despite working on v4 previously. The only thing I can think of is I did an update to v5.03 recently, then today while debugging up to v5.05. Jupyter hub works fine.

_Originally posted by @amandamiotto in https://github.com/spyder-ide/spyder/issues/3601#issuecomment-905057804_

When testing, I was using my personal ISP from home and not using the institute VPN. I have used Spyder previously on that computer with no problems, it seemed to start when I did an update to v5.03 from v4. I had tried rolling back the update but no luck.

**Comment by amandamiotto** [comment]
At work, the speed goes from 240mps-> 200mps (so less of an issue, but still a drop).

**Comment by steff456** [comment]
Hi @amandamiotto,

This seems weird because Spyder doesn't create any process related to networks. Are you trying to download a lot of things in the scripts you are writing?

**Comment by amandamiotto** [comment]
This isn't when I'm running a script- this is literally only while the program spyder is running. It slows down after a second or two of the Spyder application being open and takes about 10 seconds to hit minimum internet speed.
I've tried running while anaconda is in 'offline' mode, no change. Running Jupyter notebooks seems to work fine.

**Comment by steff456** [comment]
This is weird because Spyder doesn't create or depend in any network connection, can you try connecting via cable? I'm afraid we are not able to help you any further because we cannot reproduce this issue on our end.

**Comment by minrk** [comment]
> I think this could be be solved by Pyzmq 22.2

Any version of pyzmq should with with ipc on Windows if libzmq was built to support it. What 22.2 changed is how libzmq is built when it's bundled with pyzmq in a wheel or built from source with bundled libzmq (rare).

> is that support available in conda-forge packages?

it's a libzmq question, and my initial guess is no, because the build needs to be done on a sufficiently recent Windows toolkit and run on a sufficiently recent Windows. I don't know the minimum versions, but based on the [pyzmq issues](https://github.com/zeromq/pyzmq/pull/1574), it seems like vc142 is required (vs2019), and the conda-forge package is built with vs2017. Bumping to vs2019 might work? I don't know what the compatibility implications of that would be.

The quickest way to check is `zmq.has('ipc')`, which you can do at runtime and should be able to use if available. I *don't* know if `has('ipc')` gives the right answer if libzmq was *built* with ipc support, but is running on an old enough Windows that it doesn't have it available. My hunch is it will return True, but binding sockets will raise with EINVAL or similar (hopefully not crash).

This is a pretty wild behavior. I can't imagine how binding a few localhost sockets would change your external network bandwidth so much. Is there a lot of traffic going through the zmq sockets with Spyder, or is it just the fact that sockets are bound? If Jupyter doesn't have this effect, I don't quite understand how Spyder's use of sockets could be different in a relevant way, but this is a big mystery to me so I wouldn't rule anything out. Could Qt also be the culprit?

**Comment by ccordoba12** [comment]
> it's a libzmq question, and my initial guess is no, because the build needs to be done on a sufficiently recent Windows toolkit and run on a sufficiently recent Windows

Thanks for the explanation @minrk.

> My hunch is it will return True, but binding sockets will raise with EINVAL or similar (hopefully not crash).

Ok. But now that I remember IPykernel uses TCP by default, so we'd need to select IPC and (as you mentioned) that's not assured to work because it requires a very recent Windows version.

> This is a pretty wild behavior. I can't imagine how binding a few localhost sockets would change your external network bandwidth so much

This is a wild guess of mine too, but based on the fact that we found that switching VPN's causes this error: https://github.com/spyder-ide/spyder/issues/14355#issuecomment-738947894, which I found avoidable if IPC is used instead of TCP.

> Is there a lot of traffic going through the zmq sockets with Spyder

I think so. I mean, we constantly send the contents of the files being edited to the process them in the Python language server (our LSP client uses Pyzmq for communications). But @amandamiotto said that only by opening Spyder this odd behavior shows up.

>  If Jupyter doesn't have this effect, I don't quite understand how Spyder's use of sockets could be different in a relevant way, but this is a big mystery to me so I wouldn't rule anything out

Right, I haven't heard of anything like that reported for Jupyter, just for Spyder. It's not that frequent though, so it could be caused by a combination of things (VPN + proxy, or something like that).

> Could Qt also be the culprit?

It could, but we use very very little of Qt's network functionality.

**Comment by ccordoba12** [comment]
@amandamiotto, let's try the following things one by one (not all at the same time) to see if which one solves your problem (if any):

1. Go to the menu `Tools > Preferences > Application > Advanced settings` and deactivate `Single instance mode`:

    ![imagen](https://user-images.githubusercontent.com/365293/131895458-c9c833f7-a3ed-4b9f-9434-19e12bee0273.png)

    The close Spyder and reopen it again. If that doesn't work, please activate that option back.

    Note: We use a simple socket server to detect if a previous instance is running and send file name to open them with it.

2. Go to `Tools > Preferences > Completion and linting > General` and deactivate `Enable code completion and linting in the editor`

    ![imagen](https://user-images.githubusercontent.com/365293/131896087-14a5a874-8b5d-4d3f-9d47-975357cdc827.png)

    The close Spyder and reopen it again. If that doesn't work, you need to run in a terminal (i.e. cmd.exe) `spyder --reset` and start it again.

    Note: Our completion architecture uses PyZmq sockets, as I mentioned above.

3. Go to the Options (or hamburger) menu of the IPython console and select `Close`

    ![imagen](https://user-images.githubusercontent.com/365293/131896479-c8344b0c-8a32-4f9e-b307-796ba9520f1d.png)

    The close Spyder and reopen it again.

    Note: That uses the Jupyter frontend-kernel architecture to run code.

One of those three should be the culprit because that's all the inter-process communications we do in Spyder. Good luck with that!

**Comment by amandamiotto** [comment]
Hey team, 
Sorry for the radio silence. I went to test this out at home today and ...... turns out without changing anything on Spyder, it seems to have fixed itself? I'm wondering if there's been a forced update on the OS (we're on an SOE so there's little visibility on what they change). 
Thank you for the time- I'll try to find out what OS updates my organization have pushed and report back.
