### ISSUE TITLE
5.1.2 Mac installer broken?

### ISSUE THREAD

**Issue by gctwnl** [spyder-ide/spyder#16336]
### What steps will reproduce the problem?

I installed the update (my first update after installing and working with Spyder for the last 2 days). In the update, the kernel will not load (macOS Catalina):

NotADirectoryError: [Errno 20] Not a directory: '/Applications/Spyder.app/Contents/Resources/lib/python39.zip/debugpy/_vendored'

**Comment by ccordoba12** [comment]
Hey @gctwnl, thanks for reporting. That's a problem with the Mac installer only.

@mrclary, could you take a look at this one?

**Comment by dkmj** [comment]
installs fine but fails 'cannot load kernel'.

**Comment by mrclary** [comment]
PR #16337 should fix the issue. Note that this only affects IPython consoles that use the internal (same as Spyder) interpreter. External interpreters are not affected.

**Comment by mrclary** [comment]
Your options are: (a) use an external interpreter until 5.1.3 is released or (b) use the artifact from the pull request.

**Comment by ccordoba12** [comment]
Thanks for your help @mrclary! I'll wait a couple of days to see if other major problems appear, otherwise I'll release 5.1.3 with your fix.

However, we should find a way to automatically test our installers to avoid this problem in the future.

**Comment by mrclary** [comment]
> However, we should find a way to automatically test our installers to avoid this problem in the future.

See #14138.
I'd love to figure out a way to run our unit tests inside our macOS application, but I don't know how to do that and it may not be possible.
Another option would be to have a separate set of unit tests specifically for the macOS application, although I don't know how to accomplish that either...
In the short term, probably the best thing is to just download the latest artifact, just prior to release, and perform a cursory verification (does it launch? is there any obvious issues?).

**Comment by IvanLiuTW** [comment]
I'm sorry, could you @ccordoba12  please take a look of my error? I am searching if there is same issue as mine and I read this post. I just updated Spyder 5.1.2 and I run my code and got the error I've never seen and I really don't know how to fix it. My os is Mac(Big Sur 11.5.2) so I'm wondering if this is related to the @gctwnl 's problem.

the error as follows:

<------ 
An error ocurred while starting the kernel
2021󈚭󈚧 14:58:48.561 python[2147:49580] ‑[NSApplication macMinorVersion]: unrecognized selector sent to instance 0x7fbdad2f1dc0
2021󈚭󈚧 14:58:48.567 python[2147:49580] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '‑[NSApplication macMinorVersion]: unrecognized selector sent to instance 0x7fbdad2f1dc0'
*** First throw call stack:
(
0 CoreFoundation 0x00007fff205ed45f __exceptionPreprocess + 242
1 libobjc.A.dylib 0x00007fff20325bbb objc_exception_throw + 48
2 CoreFoundation 0x00007fff2066ff78 ‑[NSObject(NSObject) __retain_OA] + 0
3 CoreFoundation 0x00007fff205555cd ___forwarding___ + 1448
4 CoreFoundation 0x00007fff20554f98 _CF_forwarding_prep_0 + 120
5 libtk8.6.dylib 0x000000010b7ccdb9 SetCGColorComponents + 265
6 libtk8.6.dylib 0x000000010b7cd67a TkpGetColor + 250
7 libtk8.6.dylib 0x000000010b707aa9 Tk_GetColor + 153
8 libtk8.6.dylib 0x000000010b6f78e6 Tk_Get3DBorder + 134
9 libtk8.6.dylib 0x000000010b6f774f Tk_Alloc3DBorderFromObj + 127
10 libtk8.6.dylib 0x000000010b708fad DoObjConfig + 941
11 libtk8.6.dylib 0x000000010b708ae5 Tk_InitOptions + 357
12 libtk8.6.dylib 0x000000010b7089c5 Tk_InitOptions + 69
13 libtk8.6.dylib 0x000000010b739b5c CreateFrame + 1548
14 libtk8.6.dylib 0x000000010b739e37 TkListCreateFrame + 151
15 libtk8.6.dylib 0x000000010b7317f8 Initialize + 2168
16 _tkinter.cpython󈛋‑darwin.so 0x000000010b2f664b Tcl_AppInit + 91
17 _tkinter.cpython󈛋‑darwin.so 0x000000010b2f630e Tkapp_New + 590
18 _tkinter.cpython󈛋‑darwin.so 0x000000010b2f60ae _tkinter_create_impl + 222
19 _tkinter.cpython󈛋‑darwin.so 0x000000010b2f5b96 _tkinter_create + 182
20 python 0x0000000100b340d3 cfunction_vectorcall_FASTCALL + 99
21 python 0x0000000100c06a2c call_function + 172
22 python 0x0000000100c0455a _PyEval_EvalFrameDefault + 44362
23 python 0x0000000100bf8120 _PyEval_EvalCode + 528
24 python 0x0000000100ad7361 _PyFunction_Vectorcall + 433
25 python 0x0000000100ad634d _PyObject_FastCallDictTstate + 109
26 python 0x0000000100b5f520 slot_tp_init + 192
27 python 0x0000000100b6e950 type_call + 272
28 python 0x0000000100ad6078 _PyObject_MakeTpCall + 136
29 python 0x0000000100c06ab7 call_function + 311
30 python 0x0000000100c0455a _PyEval_EvalFrameDefault + 44362
31 python 0x0000000100bf8120 _PyEval_EvalCode + 528
32 python 0x0000000100bf25c2 builtin_exec + 370
33 python 0x0000000100b340d3 cfunction_vectorcall_FASTCALL + 99
34 python 0x0000000100c06a2c call_function + 172
35 python 0x0000000100c04590 _PyEval_EvalFrameDefault + 44416
36 python 0x0000000100bf8120 _PyEval_EvalCode + 528
37 python 0x0000000100ad7361 _PyFunction_Vectorcall + 433
38 python 0x0000000100c06a2c call_function + 172
39 python 0x0000000100c0464d _PyEval_EvalFrameDefault + 44605
40 python 0x0000000100bf8120 _PyEval_EvalCode + 528
41 python 0x0000000100ad7361 _PyFunction_Vectorcall + 433
42 python 0x0000000100c06a2c call_function + 172
43 python 0x0000000100c04590 _PyEval_EvalFrameDefault + 44416
44 python 0x0000000100bf8120 _PyEval_EvalCode + 528
45 python 0x0000000100bf25c2 builtin_exec + 370
46 python 0x0000000100b340d3 cfunction_vectorcall_FASTCALL + 99
47 python 0x0000000100c06a2c call_function + 172
48 python 0x0000000100c04590 _PyEval_EvalFrameDefault + 44416
49 python 0x0000000100af07f4 gen_send_ex + 180
50 python 0x0000000100bfe5b9 _PyEval_EvalFrameDefault + 19881
51 python 0x0000000100af07f4 gen_send_ex + 180
52 python 0x0000000100bfe5b9 _PyEval_EvalFrameDefault + 19881
53 python 0x0000000100af07f4 gen_send_ex + 180
54 python 0x0000000100ae5435 method_vectorcall_O + 117
55 python 0x0000000100c06a2c call_function + 172
56 python 0x0000000100c044b4 _PyEval_EvalFrameDefault + 44196
57 python 0x0000000100ad72a8 _PyFunction_Vectorcall + 248
58 python 0x0000000100c06a2c call_function + 172
59 python 0x0000000100c04590 _PyEval_EvalFrameDefault + 44416
60 python 0x0000000100ad72a8 _PyFunction_Vectorcall + 248
61 python 0x0000000100c06a2c call_function + 172
62 python 0x0000000100c044b4 _PyEval_EvalFrameDefault + 44196
63 python 0x0000000100bf8120 _PyEval_EvalCode + 528
64 python 0x0000000100ad7361 _PyFunction_Vectorcall + 433
65 python 0x0000000100ada72e method_vectorcall + 158
66 python 0x0000000100ad6e03 PyVectorcall_Call + 163
67 python 0x0000000100c0479f _PyEval_EvalFrameDefault + 44943
68 python 0x0000000100bf8120 _PyEval_EvalCode + 528
69 python 0x0000000100ad7361 _PyFunction_Vectorcall + 433
70 python 0x0000000100ada72e method_vectorcall + 158
71 python 0x0000000100c06a2c call_function + 172
72 python 0x0000000100c0464d _PyEval_EvalFrameDefault + 44605
73 python 0x0000000100af07f4 gen_send_ex + 180
74 python 0x0000000100bf3467 builtin_next + 71
75 python 0x0000000100b340d3 cfunction_vectorcall_FASTCALL + 99
76 python 0x0000000100c28a22 _PyObject_VectorcallTstate.4567 + 82
77 python 0x0000000100c288c1 context_run + 81
78 python 0x0000000100b34231 cfunction_vectorcall_FASTCALL_KEYWORDS + 81
79 python 0x0000000100c06a2c call_function + 172
80 python 0x0000000100c04590 _PyEval_EvalFrameDefault + 44416
81 python 0x0000000100bf8120 _PyEval_EvalCode + 528
82 python 0x0000000100ad7361 _PyFunction_Vectorcall + 433
83 python 0x0000000100c06a2c call_function + 172
84 python 0x0000000100c044b4 _PyEval_EvalFrameDefault + 44196
85 python 0x0000000100af07f4 gen_send_ex + 180
86 python 0x0000000100bf3467 builtin_next + 71
87 python 0x0000000100b340d3 cfunction_vectorcall_FASTCALL + 99
88 python 0x0000000100c28a22 _PyObject_VectorcallTstate.4567 + 82
89 python 0x0000000100c288c1 context_run + 81
90 python 0x0000000100b34231 cfunction_vectorcall_FASTCALL_KEYWORDS + 81
91 python 0x0000000100c06a2c call_function + 172
92 python 0x0000000100c04590 _PyEval_EvalFrameDefault + 44416
93 python 0x0000000100bf8120 _PyEval_EvalCode + 528
94 python 0x0000000100ad7361 _PyFunction_Vectorcall + 433
95 python 0x0000000100ada72e method_vectorcall + 158
96 python 0x0000000100c06a2c call_function + 172
97 python 0x0000000100c04590 _PyEval_EvalFrameDefault + 44416
98 python 0x0000000100af07f4 gen_send_ex + 180
99 python 0x0000000100bf3467 builtin_next + 71
100 python 0x0000000100b340d3 cfunction_vectorcall_FASTCALL + 99
101 python 0x0000000100c28a22 _PyObject_VectorcallTstate.4567 + 82
102 python 0x0000000100c288c1 context_run + 81
103 python 0x0000000100b34231 cfunction_vectorcall_FASTCALL_KEYWORDS + 81
104 python 0x0000000100c06a2c call_function + 172
105 python 0x0000000100c04590 _PyEval_EvalFrameDefault + 44416
106 python 0x0000000100bf8120 _PyEval_EvalCode + 528
107 python 0x0000000100ad7361 _PyFunction_Vectorcall + 433
108 python 0x0000000100ada7fb method_vectorcall + 363
109 python 0x0000000100c0479f _PyEval_EvalFrameDefault + 44943
110 python 0x0000000100af07f4 gen_send_ex + 180
111 python 0x0000000100ae5435 method_vectorcall_O + 117
112 python 0x0000000100c06a2c call_function + 172
113 python 0x0000000100c044b4 _PyEval_EvalFrameDefault + 44196
114 python 0x0000000100ad72a8 _PyFunction_Vectorcall + 248
115 python 0x0000000100ada8ce method_vectorcall + 574
116 python 0x0000000100c28a22 _PyObject_VectorcallTstate.4567 + 82
117 python 0x0000000100c288c1 context_run + 81
118 python 0x0000000100b34231 cfunction_vectorcall_FASTCALL_KEYWORDS + 81
119 python 0x0000000100c06a2c call_function + 172
120 python 0x0000000100c0455a _PyEval_EvalFrameDefault + 44362
121 python 0x0000000100bf8120 _PyEval_EvalCode + 528
122 python 0x0000000100ad7361 _PyFunction_Vectorcall + 433
123 python 0x0000000100cd3621 partial_vectorcall + 385
124 python 0x0000000100c06a2c call_function + 172
125 python 0x0000000100c04590 _PyEval_EvalFrameDefault + 44416
126 python 0x0000000100ad72a8 _PyFunction_Vectorcall + 248
127 python 0x0000000100c06a2c call_function + 172
128 python 0x0000000100c044b4 _PyEval_EvalFrameDefault + 44196
129 python 0x0000000100bf8120 _PyEval_EvalCode + 528
130 python 0x0000000100ad7361 _PyFunction_Vectorcall + 433
131 python 0x0000000100c28a22 _PyObject_VectorcallTstate.4567 + 82
132 python 0x0000000100c288c1 context_run + 81
133 python 0x0000000100b34231 cfunction_vectorcall_FASTCALL_KEYWORDS + 81
134 python 0x0000000100c0479f _PyEval_EvalFrameDefault + 44943
135 python 0x0000000100ad72a8 _PyFunction_Vectorcall + 248
136 python 0x0000000100c06a2c call_function + 172
137 python 0x0000000100c044b4 _PyEval_EvalFrameDefault + 44196
138 python 0x0000000100ad72a8 _PyFunction_Vectorcall + 248
139 python 0x0000000100c06a2c call_function + 172
140 python 0x0000000100c044b4 _PyEval_EvalFrameDefault + 44196
141 python 0x0000000100ad72a8 _PyFunction_Vectorcall + 248
142 python 0x0000000100c06a2c call_function + 172
143 python 0x0000000100c044b4 _PyEval_EvalFrameDefault + 44196
144 python 0x0000000100ad72a8 _PyFunction_Vectorcall + 248
145 python 0x0000000100c06a2c call_function + 172
146 python 0x0000000100c044b4 _PyEval_EvalFrameDefault + 44196
147 python 0x0000000100ad72a8 _PyFunction_Vectorcall + 248
148 python 0x0000000100c06a2c call_function + 172
149 python 0x0000000100c044b4 _PyEval_EvalFrameDefault + 44196
150 python 0x0000000100ad72a8 _PyFunction_Vectorcall + 248
151 python 0x0000000100c06a2c call_function + 172
152 python 0x0000000100c0455a _PyEval_EvalFrameDefault + 44362
153 python 0x0000000100bf8120 _PyEval_EvalCode + 528
154 python 0x0000000100bf25c2 builtin_exec + 370
155 python 0x0000000100b340d3 cfunction_vectorcall_FASTCALL + 99
156 python 0x0000000100c06a2c call_function + 172
157 python 0x0000000100c04590 _PyEval_EvalFrameDefault + 44416
158 python 0x0000000100bf8120 _PyEval_EvalCode + 528
159 python 0x0000000100ad7361 _PyFunction_Vectorcall + 433
160 python 0x0000000100c06a2c call_function + 172
161 python 0x0000000100c04590 _PyEval_EvalFrameDefault + 44416
162 python 0x0000000100bf8120 _PyEval_EvalCode + 528
163 python 0x0000000100ad7361 _PyFunction_Vectorcall + 433
164 python 0x0000000100c93ba2 pymain_run_module + 258
165 python 0x0000000100c935e8 pymain_run_python + 840
166 python 0x0000000100c93245 Py_RunMain + 37
167 python 0x0000000100c949c1 pymain_main + 49
168 python 0x0000000100a646c8 main + 56
169 libdyld.dylib 0x00007fff20495f3d start + 1
170 ??? 0x0000000000000005 0x0 + 5
)
libc++abi: terminating with uncaught exception of type NSException
/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/ipythonconsole/scripts/conda‑activate.sh: line 14: 2147 Abort trap: 6 $CONDA_ENV_PYTHON ‑m spyder_kernels.console ‑f $SPYDER_KERNEL_SPEC

<--- the end

I don't use anaconda to install Spyder, but I use miniconda as the Spyder envrionment. 

Another question, I have installed rtree packages for many times, but I still got the error everytime I start Spyder.
<img width="422" alt="截圖 2021-09-03 下午3 20 45" src="https://user-images.githubusercontent.com/88217916/131966714-73622dbf-5243-48d6-829f-735f2c84ecb4.png">

**Comment by IvanLiuTW** [comment]
Thanks for taking a look of my problem.

**Comment by ccordoba12** [comment]
@IvanLiuTW, please open a new issue about your problem because it's different from this one.

**Comment by IvanLiuTW** [comment]
ok, got it. Thanks for reply!
