### ISSUE TITLE
Ignore Package Version

### ISSUE THREAD

**Issue by JohnRobson** [spyder-ide/spyder#16495]
Is complicated to work with Spyder on Arch / Manjaro Linux (or other rolling release distros) because the packages are updated to the new version often and Spyder always limits some packages max version.

Now I have this error "pkg_resources.DistributionNotFound: The 'decorator<5' distribution was not found and is required by spyder-kernels"

I don't want to downgrade packages.  What about you add an IGNORE option and let me launch Spyder with my current packages versions?

**Comment by ccordoba12** [comment]
Hey @JohnRobson, thanks for reporting. You said

> Now I have this error "pkg_resources.DistributionNotFound: The 'decorator<5' distribution was not found and is required by spyder-kernels"

This constrain was removed months ago. Please upgrade or inform the Arch/Manjaro maintainers to update their packages.

> What about you add an IGNORE option and let me launch Spyder with my current packages versions?

Sorry, we can't do that because that will lead to broke functionality due to users not having the specific package versions that we require.

In my opinion, the Linux distro model of trying to support the latest versions of everything is not well suited for projects like Spyder. That's because we have many components and sometimes one package version doesn't work with another. We're also a small team and don't have time to support everything.

That's why I recommend you to use pip or Anaconda instead.

**Comment by JohnRobson** [comment]
I understand and agree with you, but what about allow ignoring the max version for the user risk? If Spyder breaks, it's my fault, but if work, I can report that Spyder is still stable even with the package version X.XX.

what about:  $ spyder --ignore packagename

**Comment by ccordoba12** [comment]
Sorry, that would make things harder for us just to make things simpler for Linux distro users, whose model (as I said) doesn't work well for projects with many interrelated dependencies.

If you want to avoid those problems, simply use pip in a virtualenv. Or if you feel confident enough, you could also run `sudo pip` to install Spyder system-wide. The experience would be exactly the same as if you installed it with your package manager.
