### ISSUE TITLE
LSP Python starting

### ISSUE THREAD

**Issue by wdksf** [spyder-ide/spyder#16536]
### What steps will reproduce the problem?

LSP can not start, general linting function doesn't work. LSP python is alwarys starting. Ubuntu 20.04, install spyder using pip, thanks

**Comment by ccordoba12** [comment]
Hey @wdksf, thanks for reporting. Please read our Troubleshooting Guide:

http://docs.spyder-ide.org/current/first-steps.html

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.
