### ISSUE TITLE
Spyder not available in search always need to use the terminal to open it

### ISSUE THREAD

**Issue by gmmkmtgk** [spyder-ide/spyder#16681]
![Screenshot from 2021-10-31 00-00-53](https://user-images.githubusercontent.com/51493190/139554333-b3c5bdcd-6bdd-4793-984d-282d590427de.png)
![Screenshot from 2021-10-31 00-01-09](https://user-images.githubusercontent.com/51493190/139554334-97d83580-3385-4b76-830d-981136ebfc05.png)
![Screenshot from 2021-10-31 00-01-44](https://user-images.githubusercontent.com/51493190/139554335-3e09f631-987f-4308-b4b1-571053714b34.png)
In the show applications search bar (Ubuntu version 20) I cannot find Spyder I always need to use the terminal to open spyder. I have attached screenshots 
KIndly provide a way to see in the search bar 
Kudos to our fast reply and support 
Thanks and regards 
Keshav Maheshwari

**Comment by ccordoba12** [comment]
Hey @gmmkmtgk, thanks for reporting. Unfortunately, it's not possible for us to solve this problem on Linux because when a package is installed with pip you can't run any extra commands (which in this case are necessary to register Spyder as a graphical application).

So the only solution is to copy our desktop file from here:

https://github.com/spyder-ide/spyder/blob/master/scripts/spyder.desktop

and paste it in the right location (it seems you already did that for the Jupyter notebook).
