### ISSUE TITLE
Cannot connect to WSL2 Kernel from Spyder running in windows

### ISSUE THREAD

**Issue by bubalis** [spyder-ide/spyder#16727]
### Issue Report Checklist

* [ X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [X ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I have anaconda installed on my wsl2 virtual machine, and I am trying to connect to spyder in windows. 

I followed all of the steps as described in the faq: 
https://docs.spyder-ide.org/current/faq.html#install-wsl2  

When I try to connect to the kernel, the console shows "connecting to the kernel" but never  progresses past this point. 

I uninstalled and re-installed spyder, and updated spyder-kernels on both WSL2 and windows it had not impact on the problem.

The problem relates to connecting between WSL2 and windows: when I create a kernel in one, I can connect to it within the same machine, but not between machines. 

### What steps reproduce the problem?

1. Install spyder
2. Create new test environment in conda on WSL2
3. start a python kernel in the activated environment: 
python -m spyder_kernels.console --matplotlib="inline" --ip=127.0.0.1 -f=~/remotemachine.json &
4. In the consoles menu, select the kernel and click ok.

### What is the expected output? What do you see instead?
Spyder connects to the kernel.
A new console opens. 
Spyder gets stuck on "connecting to the kernel" forever. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.1.5
* Python version: 3.9 (WSL2) 3.10 (Windows)
* Qt version: 5.12.10
* PyQt version:  5.12.3
* Operating System name/version: Windows 10 (WSL2: Ubuntu 20.04)

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.27.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.2.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.2 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.11.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  2.1.5 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.3.3 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.8 (OK)

```

**Comment by dalthviz** [comment]
Hi @bubalis thank you for the feedback! My guess is that you need some sort of port forwarding or basically to let your WSL2 Ubuntu instance bind with the IP address of you host Windows machine so other machines in your network can access the running kernel (as weel as config your host machine to allow connections thorugh his firewall probably).

Checking a little bit maybe this could be useful: https://stackoverflow.com/a/63781351/15954282

Let us know if something of the above helps!

**Comment by bubalis** [comment]
Hi @dalthviz ! Thanks for your response. 
I should clarify that I *think* this issue is specific to spyder / spyder-kernels, not coming from the connection between wsl2 and windows.
I do not have this problem at all when running a jupyter notebook kernel or rstudio-server from wsl2. I am also able to run an xserver properly between wsl and windows.  (Though I haven't found this setup satisfactory for running the spyder IDE).

**Comment by dalthviz** [comment]
Thanks for the new info @bubalis ! Then maybe you are right and currently we are not supporting such a connection setup. Pinging @ccordoba12 just in case (maybe he knows better the current capabilities regarding remote connection that we have with `spyder-kernels`).

**Comment by dalthviz** [comment]
Maybe this is related to https://github.com/spyder-ide/spyder/issues/3323

**Comment by bubalis** [comment]
``Hi @dalthviz !! 
I put this away for a while (it was frustrating) and I just came back to it. 

For reasons I cannot determine I cannot connect to the kernel from windows when I make it this way:
`python -m spyder_kernels.console --ip=127.0.0.1 -f=~/remotemachine.json `

but I can if I make it this way:
`ipython kernel -f~/remote_machine.json`

It may be helpful to add this method as a suggestion in the FAQ here:
https://docs.spyder-ide.org/current/faq.html#install-wsl2 

Thanks so much for your help.

**Comment by dalthviz** [comment]
Hi again @bubalis thank you for your patience figuring a way to make things work!

However I think that the kernel you are connecting using `ipython kernel -f~/remote_machine.json` will have limited functionality (you will not be able to see the declared variables, modules, etc with the Variable Explore for example).

Just in case, what happens if you try to launch a kernel with `python -m spyder_kernels.console -f~/remote_machine.json`? 

Anyhow, extending the current documentation regarding this usage with wsl2 and remote Windows machines seems important, what do you think @spyder-ide/core-developers ?

**Comment by ccordoba12** [comment]
Yeah, that's a good idea.

**Comment by CAM-Gerlach** [comment]
The current documentation on this was generously contributed by @hyamanieu to address this case in response to #13023 (see discussion in spyder-ide/spyder-docs#297 ), and it presumably worked for them on their Win 10 WSL2 machine with those steps, including using a full Spyder kernel, so perhaps we can figure out why its not working in this case. Its possible that something we added may have introduced the issue. @hyanmanieu , any insight here?

My naive suspicion would be a firewall, security or network configuration issue that interferes with the Spyder connection, but not that to plain IPython, or otherwise due to one using the default local-only `ip` setting and the other using an IP for remote access, resulting in the IPython kernel getting accessed locally, while the Spyder kernel is going over the network interface. In addition to the kernel invocation @dalthviz suggested, you could try specifying `--ip=127.0.0.1` in the IPython invocation, and seeing if it stops working when you try to connect to it again. Also, when specifying `--ip=127.0.0.1` invocation, you could also try checking the `Remote kernel` checkbox of the `Connect to kernel` dialog and entering the details there to connect to your VM over SSH. Finally, there could be an issue binding the ports for the kernel when running as non-admin process on Windows. You can try running either the kernel invocation, Spyder or both as sudo/admin and seeing if that makes any difference.

We look forward to hearing what works for you, and updating our FAQ question accordingly. Thanks!
