### ISSUE TITLE
Release the memory

### ISSUE THREAD

**Issue by MatParr** [spyder-ide/spyder#16800]
### What steps will reproduce the problem?

Hi I cannot reproduce steps but i am running some image processing code on a gpu mac i9 32gig mem processing and this is killing this computer. so much so till I cannot type code to be initialised.

Is there anyhing that I can do? I m sure that there is something but I am not accessing the right documentation.
Please help me!

**Comment by ccordoba12** [comment]
Hey @MatParr, thanks for reporting. You said

>  i am running some image processing code on a gpu mac i9 32gig mem processing and this is killing this computer. so much so till I cannot type code to be initialised.

This is not something we can fix here nor can help you to fix it because it's not related to Spyder but to the code you're running with it.

> Is there anyhing that I can do?

Perhaps breaking your code in stages so you can save intermediate results that you can use as the input of the next stage. That way your code won't run all at once but in pieces.

> Please help me!

This is the best advice we can give you, sorry.
