### ISSUE TITLE
Outdated wording in Kite tutorial

### ISSUE THREAD

**Issue by nerdfever** [spyder-ide/spyder#16836]
In Part 0, the Kite tutorial says: 

`You can change this behavior by opening settings, clicking on...`

It's not called "settings" any more (if it ever was). Now it's called "Preferences" and is under Tools, so it should read:

`You can change this behavior with Tools>Preferences, clicking on...`

Later the tutorial says:

`clicking on  "Completion and linting", "Advanced", and then changing Kite's "Start Kite Engine on editor startup" setting.`

There is no such "**Start Kite Engine on editor startup**" in Spyder 5.0.5. Perhaps this is now at Tools>Preferences>CompletionAndLinting>General>EnableKiteProvider ??? (Not sure if this is the same thing.)

There are some other minor things that need updating.

The attached file shows my suggested version.

[kite_tutorial.zip](https://github.com/spyder-ide/spyder/files/7549186/kite_tutorial.zip)

* Spyder version: 5.0.5
* Operating System name/version: Windows 10

**Comment by steff456** [comment]
Hi @nerdfever,

Thanks for pointing this out, can you please create a PR with the changes you are suggesting so we can review them and merge them in the project? Please let me know if you need any type of help doing this!

**Comment by nerdfever** [comment]
@steff456 I'd be happy to, but I confess I don't know how. Where is kite_tutoral.py stored in the distribution (it was in my temp folder when I found it...)?

I get as far as you see in the screenshot below - which branch should I be pulling, which file?

![image](https://user-images.githubusercontent.com/9833299/142243692-9ee6ce3e-b845-4268-beff-c9f776fe1ff2.png)

**Comment by steff456** [comment]
It seems you found one file that Kite generates in the Spyder directory but we don't have any access to modify 😅. I think we are unable to change it because Kite is no longer maintained, so if you are using Kite is in their latest stable version, but there will not be any further release. 

Sorry, I think we were going to be able to change it, but for now I think the only options we have are changing your local instructions or just omitting them 😕. I'm going to close this issue because we cannot change this. 

Thanks for reporting!
