### ISSUE TITLE
Spyder freezes when uninstalling 

### ISSUE THREAD

**Issue by msh855** [spyder-ide/spyder#16868]
Spyder launched via anaconda it freezes when I am trying to uninstall a package through its console 

I am using this method: 

`pip uninstall sos`

![image](https://user-images.githubusercontent.com/26636184/142654761-7d984424-103a-4f25-9e4b-d22122da0e65.png)

**Comment by dalthviz** [comment]
Hi @msh855 thank you for the feedback! Did you install `sos` using pip? Seems like you are using a conda env. Also, I would recommend to try to install/uninstall your package through the terminal first and then launch Spyder.

Let us know if something of the above helps

**Comment by msh855** [comment]
with conda it worked but with pip doesn't. This is not specific to this package but whenever I am trying to uninstall any package

**Comment by dalthviz** [comment]
Is there any reason for you to use pip instead of conda to uninstall conda packages?

**Comment by msh855** [comment]
Sadly, cannot remember the reason. I think something was not working with conda because I was using Jupyter notebook and then I fixed this with pip install.

**Comment by dalthviz** [comment]
When checking this seems like running `pip uninstall ...` or `conda uninstall ... ` directly in the console can take a long time for the client to show output. The client shows that is doing an execution but not freezing Spyder (the red stop execution button gets enable) at least on Windows.

Not totally sure if there is something we can do about this @msh855 , maybe @ccordoba12 or @impact27 have any suggestion?

The only thing I would suggest as I say is to first setup you env packages through a terminal and then launch Spyder

**Comment by msh855** [comment]
Thanks. But I think is a freeze, because as I show in the snapshot I am asked to proceed with Y/n and does nothing when I press Y ( neither stops when I press n)

**Comment by ccordoba12** [comment]
> Not totally sure if there is something we can do about this @msh855 , maybe @ccordoba12 or @impact27 have any suggestion?

Nop, unfortunately there isn't. Our IPython console is not a real terminal (i.e. like cmd.exe or xterm) although it looks like one. So it's unable to deal with keyboard interaction like in this case, and that's something we can't fix, sorry.

Therefore, your options are:

1. As @dalthviz said

    > first setup you env packages through a terminal and then launch Spyder

    In other words, do package installation using a terminal.

2. Run `pip uninstall -y` to avoid pip asking for confirmation. However, be aware that we will soon remove support for installing packages in the IPython console using pip or conda because that's not the right way to do it (it can lead to additional errors). So it's better that you start using a terminal to install packages.
