### ISSUE TITLE
Cannot debug FastAPI

### ISSUE THREAD

**Issue by mikhailo** [spyder-ide/spyder#16888]
### What steps will reproduce the problem?

Whene trying to call my code containing FastAPI

the execution of 
if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)

Fails and raises:

RuntimeError: asyncio.run() cannot be called from a running event loop

This problem does not exit on VSCode nor on PyCharm. Please, solve

**Comment by ccordoba12** [comment]
Hey @mikhailo, thanks for reporting. I'm going to ask you to open a new issue with all the information requested by our issue template filled, so we can know what are the versions of Spyder and its dependencies you're using. That's necessary for us to understand what's happening in your case. You can find that information in the menu `Help > About Spyder`.

Since that information is not available in this issue, I'm going to close it.

**Comment by mikhailo** [comment]
> Hey @mikhailo, thanks for reporting. I'm going to ask you to open a new issue with all the information requested by our issue template filled, so we can know what are the versions of Spyder and its dependencies you're using. That's necessary for us to understand what's happening in your case. You can find that information in the menu `Help > About Spyder`.
> 
> Since that information is not available in this issue, I'm going to close it.

Sure, will create a new one.
By the way, why don't you append this info automatically while creating a bug from Spyder interface?

**Comment by ccordoba12** [comment]
> By the way, why don't you append this info automatically while creating a bug from Spyder interface?

It is appended automatically.

**Comment by ccordoba12** [comment]
> It is appended automatically.

Sorry, I thought it was. That's a bug and we'll fix it our next release.
