### ISSUE TITLE
Question: extend Spyders possibilities to Update

### ISSUE THREAD

**Issue by tony-pythony** [spyder-ide/spyder#16912]
Good day together,

first a big THANK YOU for Spyder and the time, work and knowledge invested into its development by all contributors! Love you guys! 

A observation of mine:
I use conda for my python environments. So, its also used for updating Spyder. I'm on Spyder = 5.1.5.

Earlier v4.0, it was a struggle to update it by means of conda's default repository. It took felt several months to get the update pushed into the repository. The same I'm experiencing with the conda-forge. Its being faster with delivering the updated versions, but i have a mess right now with both repositories mixed up and getting one part of that, one part of this...
and still:
Its already like 5 days the 5.2.0 version has been released - and still no possibility to update with conda. Yesterday I just encountered the problem with the qtconsole > 5.1.1 as I updated a few things. Spyder suddenly stopped running the debugger. Without the Issue-submitted (https://github.com/spyder-ide/spyder/issues/16901#issue-1064336852)  I wouldn't even know its the qtconsole.

So at first I went to look up the changelog. I saw a lot of fixes and pull-request merged into the new version. Also saw the fixed "debugger on qtconsole ..." 
I would not realize this is the fix for my problem, but in the hope that something broken will be fixed within this update - I needed to get the updated version- FAST! As I have the problem emerged right now and don't really know why and how to resolve this.

So, how can I get the fixes if I'm on conda with default/conda-forge channels enabled don't list the update? A possible revert to the supported versions of other things updated by conda - not really possible, as quite a lot of other things have dependencies which might interfere with Spyders needings. 

I think I'm not the only one with this problem. Possibilities I see:
- get the installer package for windows / mac -> I would break the conda env with this, but the installers (it seems) are available as soon the new version is publicly announced (?)
- doin' some hacking and manual patching -> way to dangerous
- installing github and self rebuilding from the sources is not possible, as my technical background is not as deep as it would be needed

Ideas:
- analogue to the installers for the win/mac systems, could it be possible to have a file patcher that patches just the files fixed?
- windows/mac installers that can be used to update the conda-setup'ed installations without touching the necessary config-files of conda? So, one basically get the things uptodate and as soon conda/conda-forge have the new versions pushed into its repository, another step of "proper" updating will be done - for conda's needs.
- having just the zip files provided for "portable" update of Spyder? just putting the contents of the zip-archive into the installation directory?
I see some problems with this, but this could be circumvented with constraints like "5.4->5.5 ONLY!" written somewhere. Batchfile?
It would not work with major changes when deep changes of system-settings or similar are done, I understand, but small fixes can be applied as soon a new updated version is released without having to wait for them.

how do you think about this? May be you can already show some ways to do the update manually on conda managed envs?

Thank you for your brainwork on this!

tony pythony

**Comment by dalthviz** [comment]
Hi @tony-pythony thank you for the feedback!!

Regarding the conda default channel we know about that and even us ended up moving to use conda-forge for the CI. There is not much we can do on that front.

From the conda-forge channel side we have more options to do things but usually there is some time of difference between the PyPI release and the one on conda-forge (being the best scenario at least a couple of hours of difference).

Specifically with Spyder 5.2.0, we encounter a blocker since a new dependency was added but it was unavailable for `aarch64` so we had to check with the maintainers of the package feedstock and just until now we trigger the update to have [Spyder 5.2.0 on conda-forge](https://github.com/conda-forge/spyder-feedstock/pull/120) (which should be available tomorrow or later today on the conda-forge channel if you want to check it :) ).

However, besides this, I believe too that we should provide a way for a more stable ways to update. Part of the initial idea behind creating the Windows/MacOS installers was that, but for sure there is a lot of room for improvements in that aspect. Some of the ideas we have go in a similar path as you propose here with somehow providing a way for the installers to autoupdate or patch the current installed version with only the necessary files (although for the moment this is a future project idea).

If you want to have the latest version of Spyder without using pip in the fastest way possible I would suggest using the installers and using custom interpreters (in case you need to use specific libraries besides the ones that are bundled with the installers like `numpy`, `matplotlib` and `pandas`). For more info regarding that we have some docs here: https://docs.spyder-ide.org/current/installation.html#running-from-a-standalone-install and https://docs.spyder-ide.org/current/faq.html#using-packages-installer

So following the use of the installers, you will only need to update in your conda managed envs `spyder-kernels` (which is always released before Spyder) and then update the standalone version you are using (here is were we have some work to do since currently I'm not totally sure if you can directly overwrite the installation by running the latest installer or if you need to uninstall and then install the new version - at least on Windows).

If you have anyother question or something of the above helped let us know!

**Comment by dalthviz** [comment]
Thank you for sharing your ideas @tony-pythony ! And if you have more questions/suggestions let us know :+1:
