### ISSUE TITLE
List comprenhension

### ISSUE THREAD

**Issue by Alejandro58581** [spyder-ide/spyder#16929]
### What steps will reproduce the problem?

When i try to create a list by comprehension in the kerner it stop.

The code that I use was:

squares=[i*i for i in range(5)]

**Comment by dalthviz** [comment]
Hi @Alejandro58581 thank you for the feedback. What Spyder version are you using and how did you install it? Testing the code provided seems like is working in the latest version (5.2.0): 
 
![imagen](https://user-images.githubusercontent.com/16781833/144454404-53b8c7ad-b7d4-43f7-8bc7-17b096801d43.png)

Also, did you saw any traceback or message related with the issue?

Any new info in order to reproduce this in our side is greatly appreciated, let us know!

**Comment by Alejandro58581** [comment]
Hello, @dalthviz I am using spyder 5.0.5 and anaconda navigator. I can´t upgrade spyder using the prompt it never connects. Any message appears when I run the code only the kernel stops working.

![image](https://user-images.githubusercontent.com/82003215/144485071-bd3ee403-a4fc-4eeb-93b6-038e6a668bc0.png)

**Comment by ccordoba12** [comment]
@Alejandro58581, did you change the graphics backend in `Preferences > IPython console > Graphics` to something other than `Inline`?

**Comment by Alejandro58581** [comment]
@ccordoba12 thank you. I changed the graphics backend because matplotlib also didn´t work and the spyder bot helped me and I forgot to change it.

**Comment by ccordoba12** [comment]
Ok, just so you know, this is a bug and it should be fixed in our 5.2.0 version, released a few days ago. So, as soon as it's part of Anaconda and you can update to it, we encourage you to do it.
