### ISSUE TITLE
No possibility to select yapf as auto-formatter in preferences

### ISSUE THREAD

**Issue by Firestar-Reimu** [spyder-ide/spyder#16964]
```
autopep8                  1.5.7
black                     19.10b0
yapf                      0.31.0
```

But I can only choose autopep8 or black in auto-formatter. I use spyder on Linux

```
spyder                    5.1.5
```

**Comment by steff456** [comment]
Hi @Firestar-Reimu,

We decided to not include yapf in the auto formatter options because the server doesn't support changing the maximum line length and other options that are in the preferences dialog. This made really hard to include it and made the current UI work for it. We are waiting for them to add these options into the server so we can add it smoothly in Spyder.

For now, we are unable to add it to Spyder.

**Comment by Firestar-Reimu** [comment]
1. Sorry, because I see that you wrote "Spyder can use autopep8, yapf or black to reformat your code" in the settings
2. You say server, what about in the local environment (in my own computer)?

**Comment by ccordoba12** [comment]
Hey @Firestar-Reimu, you're right: in our preferences we say that support Yapf, but it's not available for selection:

![imagen](https://user-images.githubusercontent.com/365293/144956942-2e5cea81-c311-4f67-baf0-fc75578414d2.png)

The truth is we can't support Yapf at the moment because it doesn't allow us to set the maximum line length. We'll try to fix that in the future, but for now we'll change that message to say that we only support Black and Autopep8.
