### ISSUE TITLE
Missing dependencies: rtree

### ISSUE THREAD

**Issue by mczakk** [spyder-ide/spyder#17040]
Every time I start spyder oit tells me that there are mising dependencies. rtree 0.9.7 is missing.

conda install rtree says that it is installed

workarounds on this poage are either ineffectual or too complicated

PASTE TRACEBACK HERE

```

## Versions

Spyder 5.2.1
Python 3.8.8 64-bit | 
Qt 5.12.9 | 
PyQt5 5.12.3 |
 Windows 10 

### Dependencies
<!--- Please go to the menu entry Help > Dependencies,
press the Copy to clipboard button and paste below --->

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.6.0 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  7.30.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.8.9 (OK)
jsonschema >=3.2.0            :  4.3.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.3.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.1 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  1.11.3 (OK)
rtree >=0.9.7                 :  None (NOK)
setuptools >=49.6.0           :  59.6.0 (OK)
sphinx >=0.6.6                :  4.3.1 (OK)
spyder_kernels >=2.2.0;<2.3.0 :  2.2.0 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.21.3 (OK)
pandas >=1.1.1                :  1.3.4 (OK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)

```

**Comment by dalthviz** [comment]
Hi @mczakk thank for the feedback. Could you try to reinstall `rtree` using something like `conda install rtree -c conda-forge --force-reinstall` Let us know if that helps!

**Comment by mczakk** [comment]
No, that has no effect. I also have another problem with spyder on my windows machine, would you be able to help with that?

 

 

Matt Cooper

**Comment by dalthviz** [comment]
This is quite strange @mczakk , could you check what happens when you import `rtree` and check the path to the module from the Spyder Internal Console (to make the Internal Console visible go to `View > Panes > Internal Console`)? 

You can do the above running something like this from the Internal Console:

    import rtree
    rtree
    rtree.__file__


Also, if you are having troubles with the conda installation/update of Spyder, maybe you could try using the [standalone installer available for Spyder 5.2.1 on Windows](https://github.com/spyder-ide/spyder/releases/download/v5.2.1/Spyder_64bit_full.exe) and check the [docs in case you use specific packages outside of the ones bundled with that](https://docs.spyder-ide.org/current/faq.html#using-packages-installer).

Besides that, are you by any chance mixing pip installed packages with conda installed packages or channels in your env?

If you have any other problem or something of the above helps let us know

**Comment by mczakk** [comment]
Hi Daniel,

I tried your commands, and got the result shown in the screenshot:

 

I did notice that I have three instances of rtree in c:/Program Data/Anaconda/pkgs (see second attachment) so I guess the package is there!

 

In answer to your other comments, I use anaconda and normal updates seem to work fine, I have never used pip to install anything, and the standalone spyder installer for windows was awful when I tried it!

 

Cheers

 

Matt

 

Matt Cooper

**Comment by dalthviz** [comment]
@mczakk could you resubmit your screenshots directly on GitHub please? When you send the responses by email the attachements get lost.

Also, could you share with us your thoughts regarding the installer, please? There are room for improvements in that aspect for sure.

Let us know!

**Comment by mczakk** [comment]
No problem:
![Screenshot 2021-12-17 160626](https://user-images.githubusercontent.com/6179722/146581973-7bb603e8-a6dd-4a55-8138-d0627a09d4ea.jpg)
![exp](https://user-images.githubusercontent.com/6179722/146581994-74ea7dd7-53fc-4c31-b411-9870b457a55d.jpg)

Ill be honest, I can't remember what the issue with the installer was. But it was enough that I reinstalled anaconda to be able to use spyder again!

**Comment by dalthviz** [comment]
Checking the traceback in the screenshot seems like the issue is indeed a faulty `rtree` installation (since the `spatialindex-c_64.dll` is somehow missing). Maybe to fix this, since reinstalling `rtree` is not helping  you could try to find the missing .dll and manually copy it in the `/site-packages/rtree` dir (although keep in mind that that is something not recommended due to possible issues when trying to update in the future as discussed here: https://github.com/spyder-ide/spyder/issues/14466).

Besides that, maybe creating a new env for the spyder installation and using the custom interpreter preference to link your base env could be a workaround for the `rtree` faulty install while being able to use other packages installed in your base env: https://docs.spyder-ide.org/current/faq.html#using-existing-environment

I think there is not much else we can do from the Spyder side but let us know if something of the above helps!

>Ill be honest, I can't remember what the issue with the installer was. But it was enough that I reinstalled anaconda to be able to use spyder again!

Tricky thing to check then. I wonder what happened for something like that to be needed, but thank you anyway for the feeback :+1:

**Comment by mczakk** [comment]
I tried the trick of copying the spatialindex-c_64.dll file into the rtree directory (all three of them) and still no good!
As for your suggestion -
Besides that, maybe creating a new env for the spyder installation and using the custom interpreter preference to link your base env could be a workaround for the rtree faulty install while being able to use other packages installed in your base env-
I'm sorry but I really don't understand all this env stuff, I just use python to do my dats analysis and produce pretty graphs for my PhD. Spyder is the easiest IDE I've found and the easiest in which to swap from Linux to Windows machines. I don't get the same error on my Linux machine BTW, but that's running 5.1, not 5.2

**Comment by t-wojciech** [comment]
> I'm sorry but I really don't understand all this env stuff, I just use python to do my dats analysis and produce pretty graphs for my PhD.

@mczakk, I also encountered a lot of problems with dependencies in Python when I was doing my PhD. Through constant troubleshooting, I finally gave up and switched to R and RStudio. In data analysis and visualization these languages are very similar, but however R is smoother and less problematic. Sorry for the offtopic, but maybe someone is also feeling overwhelmed and this tip might be helpful.

**Comment by dalthviz** [comment]
> I tried the trick of copying the spatialindex-c_64.dll file into the rtree directory (all three of them) and still no good!

As a last though from copying the dlls , could you restart your machine?

> I'm sorry but I really don't understand all this env stuff, I just use python to do my dats analysis and produce pretty graphs for my PhD. Spyder is the easiest IDE I've found and the easiest in which to swap from Linux to Windows machines. I don't get the same error on my Linux machine BTW, but that's running 5.1, not 5.2

No worries, all the concept of managing envs can be quite overwhelming at first ! Maybe then downgrading with something like `conda install spyder=5.1.5` could help?

> I also encountered a lot of problems with dependencies in Python when I was doing my PhD. Through constant troubleshooting, I finally gave up and switched to R and RStudio. In data analysis and visualization these languages are very similar, but however R is smoother and less problematic. Sorry for the offtopic, but maybe someone is also feeling overwhelmed and this tip might be helpful.

I think partially for this kind of things is that we came with the idea of the standalone installers although we need to keep improving them and improve also the way they support setups with custom packages for sure. Thank you for sharing your experience @t-wojciech !

**Comment by Hawxxer** [comment]
I have the same problem. Lately conda / conda-forge has been very unreliable for me when it comes to installing packages. It just installs dependencies which do not work together. Maybe someone smarter can tell me what I am doing wrong or if it's a general problem with conda. 
For now installing spyder with "pip install spyder" in a fresh conda enviroment fixes the rtree problem for me, even if you not supposed to use pip with conda..

**Comment by Hawxxer** [comment]
Further testing, creating conda env with 
`conda create --name spyder-env **-c conda-forge** python=3.9`
`conda activate spyder-env`
`conda install -c conda-forge spyder`
works fine, while 
`conda create --name spyder-env python=3.9`
`conda activate spyder-env`
`conda install -c conda-forge spyder`
does not work, I can't tell which package from conda main channel causes the problems, maybe someone can test or just install python with conda-forge

**Comment by dalthviz** [comment]
> Further testing, creating conda env with
> conda create --name spyder-env -c conda-forge python=3.9
> conda activate spyder-env
> conda install -c conda-forge spyder
> works fine, while
> conda create --name spyder-env python=3.9
> conda activate spyder-env
> conda install -c conda-forge spyder
> does not work, I can't tell which package from conda main channel causes the problems, maybe someone can test or just install python with conda-forge for now

Hi @Hawxxer thank you for your input here! I think the problem is that installing from different conda channels (defaults vs conda-forge for example) can lead to binary incompatibilities which then can lead then to problems like the one here.  I would say that the best approach is to use always the conda-forge channel for everything (so you can get the up-to-date versions of the packages).

Also, just in case, @mczakk are you mixing in your setup packages channels (e.g defaults vs conda-forge)?

**Comment by ccordoba12** [comment]
> I'm sorry but I really don't understand all this env stuff, I just use python to do my dats analysis and produce pretty graphs for my PhD. Spyder is the easiest IDE I've found and the easiest in which to swap from Linux to Windows machines

@mczakk, that's why we created our Windows and Mac [installers](https://github.com/spyder-ide/spyder/releases), i.e. to give our users an installation method that just works. Please try it and let us know how it works for you.

**Comment by ccordoba12** [comment]
As far as we know, this is a problem with Rtree wheels and it should be solved once their maintainers release a new version. Until then, there's nothing we can do about it, sorry.
