### ISSUE TITLE
How does Spyder populate autocomplete?

### ISSUE THREAD

**Issue by ma-sadeghi** [spyder-ide/spyder#17043]
I'm subclassing numpy's `ndarray` and adding some more functionality to it. The issue is that I don't want autocomplete to show stuff related to numpy's `ndarray`. I already modified the `__dir__` method of the new class, but that doesn't seem to fix it.

**Comment by steff456** [comment]
Hi @ma-sadeghi,

I'm not sure how we can help you with this, I know that the completion will take everything that is installed in your environment. I think the only way to avoid completion will be disabling the whole feature in Spyder :/

**Comment by ma-sadeghi** [comment]
Hi, @steff456. Thanks for your reply. I don't want to disable the entire completion feature. I'm just trying to find out how Spyder pulls the list of methods/attributes. For instance, when I type `np.` and then press `tab`, Spyder lists a bunch of methods attributes that are exclusive to `numpy`'s namespace. I just want to know how Spyder compiles this "list". Thanks.

**Comment by steff456** [comment]
If you want to modify something inside our code base, that is being populated in this function in the codeeditor, https://github.com/spyder-ide/spyder/blob/404449b38153b02e7c6aa0d3c4538a2eff12955c/spyder/plugins/editor/widgets/codeeditor.py#L1390

**Comment by ccordoba12** [comment]
> I just want to know how Spyder compiles this "list". Thanks.

@ma-sadeghi, we don't do it directly. Instead, we rely for that on [Jedi](https://github.com/davidhalter/jedi), which is being used through the Python language server (PyLSP) interface.

This is the specific Jedi method used for completions:

https://jedi.readthedocs.io/en/latest/docs/api.html#jedi.Script.complete

called here in the PyLSP:

https://github.com/python-lsp/python-lsp-server/blob/develop/pylsp/plugins/jedi_completion.py

The only way I think you could override that would be by writing your own PyLSP plugin for completions to filter those returned by Jedi that you don't want to see. And then turn off the regular Jedi completions we offer, so that the PyLSP use your plugin (we had an option for that in Spyder 4 and we need to restore it for version 5).

**Comment by ma-sadeghi** [comment]
@ccordoba12 Thank you for your detailed response, I really appreciate it!

What about the completion in IPython console? Is it also coming from Jedi?

**Comment by ccordoba12** [comment]
Completions in the IPython console are handled by IPython:

https://github.com/ipython/ipython/blob/master/IPython/core/completerlib.py

I'm not too familiar with its completion machinery but I know you can use Jedi for that (which is slow for big objects) and in-house completions (which we use by default).

**Comment by ma-sadeghi** [comment]
Great, thanks!
