### ISSUE TITLE
Autocomplete not working on Fedora 35

### ISSUE THREAD

**Issue by jamesturner246** [spyder-ide/spyder#17086]
### What steps will reproduce the problem?

Python 3.10.1 64-bit | Qt 5.15.2 | PyQt5 5.15.6 | Linux 5.15.10-200.fc35.x86_64 

Fedora 35

Try autocompletion in ipython console, e.g. type l for len, then press tab to autocomplete.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.10/site-packages/qtconsole/jupyter_widget.py", line 178, in _handle_complete_reply
    self._complete_with_items(cursor, matches)
  File "/usr/lib/python3.10/site-packages/qtconsole/console_widget.py", line 1072, in _complete_with_items
    self._completion_widget.show_items(cursor, items,
  File "/usr/lib/python3.10/site-packages/qtconsole/completion_widget.py", line 107, in show_items
    point = self._get_top_left_position(cursor)
  File "/usr/lib/python3.10/site-packages/qtconsole/completion_widget.py", line 171, in _get_top_left_position
    point.setY(point.y() + y)
TypeError: setY(self, int): argument 1 has unexpected type 'float'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.10.1
* Qt version: 5.15.2
* PyQt5 version: 5.15.6
* Operating System: Linux 5.15.10-200.fc35.x86_64

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.26.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  21.8.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=2.5.0                :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.2 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.11.2 (OK)
rtree >=0.9.4                 :  0.9.4 (OK)
setuptools >=49.6.0           :  57.4.0 (OK)
sphinx >=0.6.6                :  4.1.2 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.1 (OK)
textdistance >=4.2.0          :  4.2.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.1 (OK)
pandas >=1.1.1                :  1.3.3 (OK)
scipy >=0.17.0                :  1.7.0 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by ccordoba12** [comment]
Hey @jamesturner246, thanks for reporting. This was fixed in https://github.com/jupyter/qtconsole/pull/513, part of qtconsole **5.2.2** (qtconsole is one of our dependencies). Please note that you need Spyder 5.2.0+ to use qtconsole 5.2.0+.

As a general advice, and if possible, please stop using the Spyder packages supplied by your Linux and use pip (in a virtualenv) or Anaconda instead. Distro packages will always be outdated or incorrectly packaged because distro maintainers are not aware of the intricate and brittle relations between the many dependencies (and their dependencies) we rely on. 

My apologies if they read this, but (for instance) if they're forcing Spyder to work with PyQt 5.15 (as Fedora or Arch), then that's certainly the case because Spyder crashes with a segfault at close with that version. And that's not only my experience as a maintainer. As a user, I've seen Lyx generating odd errors and crashes in Ubuntu because their maintainers forced it to work with Qt 5 (I had to recompile it with Qt 4).

**Comment by jamesturner246** [comment]
Hi @ccordoba12. That's good to know. I Will use the venv pip route in future. Thanks for the fast response.

**Comment by ccordoba12** [comment]
No problem, thanks for understanding.
