### ISSUE TITLE
Spyder-Terminal not working.  It appears blank and does not respond at all to any commands

### ISSUE THREAD

**Issue by richlysakowski** [spyder-ide/spyder#17114]
### What steps will reproduce the problem?

Installed Spyder:
    conda install -c spyder-ide spyder-ide

install Spyder-Notebook: 
    conda install spyder-terminal -c spyder-ide

Restart Spyder

See Spyder-Terminal blank and unresponsive. 

## Versions

* Spyder version: 4.2.5 
* Python version: 3.9.7
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  2.0.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.0.2 (OK)
IPython >=7.6.0                 :  7.29.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  4.2.1 (OK)
keyring >=17.0.0                :  23.4.0 (OK)
nbconvert >=4.0                 :  6.3.0 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.8.1 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.10.0 (OK)
pylint >=1.0                    :  2.12.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.1.1 (OK)
qtconsole >=5.0.3               :  5.2.2 (OK)
qtpy >=1.5.0                    :  2.0.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  59.2.0 (OK)
sphinx >=0.6.6                  :  4.3.2 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.2 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  22.3.0 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.5.0 (OK)
numpy >=1.7                     :  1.21.4 (OK)
pandas >=1.1.1                  :  1.3.4 (OK)
scipy >=0.17.0                  :  1.7.2 (OK)
sympy >=0.7.3                   :  None (NOK)

# Spyder plugins:
spyder_notebook                 :  0.3.2 (OK)
spyder_terminal                 :  0.3.1 (OK)
```

**Comment by richlysakowski** [comment]
### What steps will reproduce the problem?



Installed Spyder:
    conda install -c spyder-ide spyder-ide

install Spyder-Notebook: 
    conda install spyder-terminal -c spyder-ide

Restart Spyder

See Spyder-Terminal blank and unresponsive. 

I will try to uninstall and reinstall again.

**Comment by ccordoba12** [comment]
Hey @richlysakowski, thanks for reporting. There are two issues here:

1. Spyder-terminal was significantly improved in the last months and shouldn't show the problem you mentioned with a version compatible with Spyder 5 (i.e. any version greater than 1.0.0).
2. We don't support Spyder 4 anymore, so it's possible for us to fix problems with that version.

I understand you want to use both Spyder-terminal and Spyder-notebook at the same time, and for that you need to fall back to Spyder 4. But that I'm afraid that's not possible due to the fast pace of open source (a lot of things has changed in the last year).

So the only thing you can for now do is to install Spyder-terminal along with Spyder 5 and wait until we release a new version of Spyder-notebook that is compatible with Spyder 5. We'll try to do that in coming months (we relied on a volunteer contributor for the maintenance of Spyder-notebook, but sadly he stopped helping us since a year ago).
