### ISSUE TITLE
Where in the IDE can I find config for lsp plugins?

### ISSUE THREAD

**Issue by Greedquest** [spyder-ide/spyder#17152]
I am trying to configure a 3rd party python lsp server plugin. I know _Spyder plugins_ can register config settings in the preferences menu, and confusingly I believe the language server is itself a Spyder plugin. However I'm not sure how to edit the json style config for lsp plugins:

E.g. 
```json
{
    "enabled": True,
    "live_mode": False,
    "dmypy": True,
    "strict": False
}
```
For the [pylsp-mypy](https://github.com/Richardk2n/pylsp-mypy) plugin.

Also I'm not sure if this is a question to ask in the plugin repo, the Spyder lsp server fork, the main python-lsp-server repo or here - To me this was a question of where in Spyder specifically I can find this config so I asked here.

**Comment by ccordoba12** [comment]
Hey @Greedquest, thanks for reporting. We build and send our configuration to the Python language server (PyLSP) dynamically here:

https://github.com/spyder-ide/spyder/blob/e29db93e2a67ca98cd9e7da4b356bb685bf53a29/spyder/plugins/completion/providers/languageserver/provider.py#L695

Unfortunately, it's not possible for third-party plugins of the PyLSP to access or extend that mechanism, and I can't think of an easy way to allow for that.

However, reading the pylsp-mypy source code, it seems you can configure it with files named `pylsp-mypy.cfg`, `mypy-ls.cfg`, `mypy_ls.cfg`, `mypy.ini`, `.mypy.ini` in your project directory:

https://github.com/Richardk2n/pylsp-mypy/blob/0c61489c896bf5eae708f77e7ca5b48cc6f2da44/pylsp_mypy/plugin.py#L308

> Also I'm not sure if this is a question to ask in the plugin repo, the Spyder lsp server fork, the main python-lsp-server repo or here - To me this was a question of where in Spyder specifically I can find this config so I asked here.

Please put in contact with the pylsp-mypy for additional advice because this is not something we can solve here, as I said above.

Eventually, we plan to integrate that plugin in Spyder, and then we'll offer an easy way to configure it.
