### ISSUE TITLE
Hash (#) Comments Don't Nest in Outline Window

### ISSUE THREAD

**Issue by ba05** [spyder-ide/spyder#17246]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Previous Spyder versions (not sure exactly, maybe pre-version 5?) nested hash (#) comments in the outline pane. By this I mean #### would be level 1, ### would be level 2, ## would be level 3, and so on. This allowed the code to be better organized and allowed for navigation between code comment sections via the outline viewer. Currently only #### preceded comments show in the outline pane.

**Comment by dalthviz** [comment]
Hi @ba05 thank you for the feedback! I was able to reproduce this. I think that when moving to use the LSP to populate the outline explorer this functionality changed to use instead of the `####` convention the `# %%` cells convention (although not totally sure, maybe @ccordoba12 or @andfoy know better about this). Testing using the cells convention I was able to organize the code in levels/sections like this:

![imagen](https://user-images.githubusercontent.com/16781833/151189962-926278b0-9edc-41b0-afa6-b29ac4ede73b.png)

Where you will need to add an extra `%` for each new level you want to create. For more info regarding the cells functionality you can check here: https://docs.spyder-ide.org/current/faq.html?highlight=cells#using-code-cells

Let us know if that helps!

**Comment by dalthviz** [comment]
Also, just in case, the example code I used:

```python

# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""

# %% Section 1
def test():
    pass

# %%% Section 1 - Subsection 1 
def test2():
    pass

# %%% Section 1 - Subsection 2
def test3():
    pass


# %% Section 2
def test4():
    pass

# %%% Section 2 - Subsection 1
def test5():
    pass

# %%% Section 2 - Subsection 2
def test6():
    pass


```

**Comment by ba05** [comment]
Thanks. I was not aware of the `%` syntax. This solves my issue.

**Comment by ba05** [comment]
The `%` comment syntax as well as `#` syntax appears broken again in 5.3.0. Possibly related to #16634. Comments do not appear in the Outline pane.

**Comment by dalthviz** [comment]
Hi again @ba05  I checked locally with my installed version of Spyder 5.3.0 and seems like the Outline pane is working for me (at least with the example code I posted before):

![imagen](https://user-images.githubusercontent.com/16781833/162474840-6f38a1c8-f451-4635-8d36-ec1c7f052882.png)

Or maybe you are trying to use the Outline pane undocked as in #16634 ?
