### ISSUE TITLE
Spyder uses  up CPU (through Python process on Task Manager) even when idle

### ISSUE THREAD

**Issue by ioChris** [spyder-ide/spyder#17275]
### What steps will reproduce the problem?

As soon as Spyder is launched and used to run at least one script, then a Python process in the Task Manager is constantly active and takes up CPU even when SPyder is idle.

* Spyder version: 5.1.5 None
* Python version: 3.8.8 64-bit
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

**Comment by ioChris** [comment]
Hi @ccordoba12, thank you for following up on this. 
I'm attaching a capture from the task manager. I have done the following to reproduce the issue:
-launch Spyder
-run a python script through Spyder and wait until it finishes
-minimize Spyder and wait a bit more

The Python process shows a ~10% CPU usage even when Spyder is idle and minimized.

![Capture](https://user-images.githubusercontent.com/35302025/152010275-24404ccc-d5dc-4290-b6c1-d3e10802cc52.PNG)

**Comment by ccordoba12** [comment]
This is normal. Those extra processes are:

1. The IPython console's kernel, which is the external Python instance necessary to run your code when you press F5 or Shift+Enter.
2. The Python language server, which is a server we use to get code completion, linting, and folding for the editor. 

Unfortunately, it's not possible to get rid of them because they are needed for Spyder to work. We understand this is an issue for systems with a small amount of RAM, but there's nothing we can do about it, sorry.

**Comment by ioChris** [comment]
I understand, RAM is not actually a problem here but the CPU overhead that is taken up, is (~10% permanent load is not insignificant). The weird thing is that this does not happen in other computers of mine (same OSs and same Spyder versions, slightly different Python versions but all 3.x), it might be due to some particular module.

Thanks for having a look at it.

**Comment by ccordoba12** [comment]
CPU usage should be improved in future versions (we know that's an issue right now but the fix is not simple).
