### ISSUE TITLE
Spyder 5.2.1 for Python 3.6

### ISSUE THREAD

**Issue by pfvideo** [spyder-ide/spyder#17310]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x ] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [x ] Reset preferences with ``spyder --reset``
    * [x ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x ] Tried the other applicable steps from the Troubleshooting Guide
* [x ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Where can I get a release of Spyder 5.2.1 for Python 3.6 for Linux (conda)? Prior versions hang when debugging.

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @pfvideo, thanks for reporting. Unfortunately, Anaconda and conda-forge stopped producing packages for Python 3.6 a long time ago. So your only alternative is using pip, like this:

    conda create -n spyder-env python=3.6
    conda activate spyder-env
    pip install spyder

After that, you need to connect this Spyder instance to the environment where you have your other packages by following these instructions:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment

Please remember that you can't mix pip and conda packages because they are binary incompatible. So either you install everything with pip in the `spyder-env` environment, or use conda to install all packages you need in a separate one.

**Comment by pfvideo** [comment]
Thanks. I've created a conda environment where spyder and all other required packages are installed, and it is working.

If I had to connect spyder to a different environment, will the packages installed in that environment be loaded in spyder? How can it's environment variables be set in spyder? How about if the environment is a virtualenv?

**Comment by ccordoba12** [comment]
> If I had to connect spyder to a different environment, will all the packages installed in that environment be loaded in spyder?

Yes, they will be available both in the console and Editor.

> How can it's environment variables be set in spyder?

There's no way to do that at the moment.

> How about if the environment is a virtualenv?

There's no difference between conda envs and virtualenvs. The only important thing is that any external environment has spyder-kernels installed.
