### ISSUE TITLE
ImportError: cannot import name 'filefind' from 'traitlets.utils' (/usr/lib/python3/dist-packages/traitlets/utils/init.py)

### ISSUE THREAD

**Issue by naloboud** [spyder-ide/spyder#17320]
### What steps will reproduce the problem?

ImportError: cannot import name 'filefind' from 'traitlets.utils' (/usr/lib/python3/dist-packages/traitlets/utils/init.py)

**Comment by ccordoba12** [comment]
Hey @naloboud, thanks for reporting. This is not a problem with Spyder but with your Linux distro, which is using an old version of the traitlets package.

To fix it, simply run

    pip install - U traitlets 

if you installed Spyder in a virtualenv. If you did it with `sudo pip`, please remove everything under `/usr/local/lib/python` and switch to a virtualenv.

Finally, if you're using your distro packages, please report this problem with your distro maintainers about it because they need to fix it.
