### ISSUE TITLE
Debugger not working

### ISSUE THREAD

**Issue by jtmbeta** [spyder-ide/spyder#17385]
### What steps will reproduce the problem?

In Spyder 5.1.5, set a breakpoint and run some code. The debugger launches but there is nowhere to enter commands. It just hangs there.

**Comment by jtmbeta** [comment]
![Screenshot 2022-02-22 at 14 04 06](https://user-images.githubusercontent.com/11196943/155148087-2872be0a-d3fc-493c-b090-26317780c1d2.png)

**Comment by ccordoba12** [comment]
Hey @jtmbeta, thanks for reporting. This error is already fixed in our latest version (5.2.2).

Since it's still not available in Anaconda, you have two options:

1. Use our macOS installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open a terminal and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

After that, you can connect Spyder to your base environment by following these instructions:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment

**Comment by jtmbeta** [comment]
Thanks!
Joel
