### ISSUE TITLE
Variable explorer is not supporting pandas Data Frame

### ISSUE THREAD

**Issue by diegosalinasgonzalez** [spyder-ide/spyder#17417]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by ccordoba12** [comment]
Hey @diegosalinasgonzalez, thanks for reporting. Since you didn't provide any additional information about your problem, I'll have to assume that you're using our Windows or macOS installer and have an external environment in which you installed Pandas.

If that's the case, then you need to downgrade Pandas to its 1.3.5 version to solve the problem. For that you need to run the following commands:

    conda install pandas=1.3.5

if you're using Anaconda/Miniconda; or

    pip install pandas==1.3.5

if you used another method to install Python. Please don't use pip in Anaconda/Miniconda or you'll break your environment.

Finally, you won't need to do this workaround once our next version (5.3.0) is released next month, which will compatible with the latest release of Pandas.
