### ISSUE TITLE
Update to Spyder 5 from linux distribution packages

### ISSUE THREAD

**Issue by hackicodi** [spyder-ide/spyder#17422]
Hello,
i installed spyder on Linux with Terminal. Spyder 4 works perfect. updated to 5.2.2 but system starts only spyder 4. any ideas?

### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by dalthviz** [comment]
Hi @roughneckgermany thank you for the feedback. How did you do the installation and update? We usually suggest to use some sort of env manager like conda to handle the Spyder installation but maybe you are using something different for your setup.

Any new info in order to understand what is happening in your case is greatly appreciated. Let us know!

**Comment by roughneckgermany** [comment]
I installed via terminal and Spyder 4 works great. Update was done with apt install -U spyder

**Comment by dalthviz** [comment]
Oh I see, in that case I think the latest release available as a distribubtion package (at least checking for [ubuntu](https://packages.ubuntu.com/search?keywords=spyder) and [debian](https://packages.debian.org/source/sid/spyder)) is for Spyder 4 (so although you can try to update you will not be able to install a newer version).

If you want to check Spyder 5 I would suggest you to create a python environment (with a python environment manager like conda or virtualenv) and install spyder 5 (if you would like to try with conda be sure to use the conda-forge channel to install the packages).

For more info about the installations methods available you can check these links:

* Via linux distribution packages: https://docs.spyder-ide.org/current/installation.html#linux
* Via Anaconda: https://docs.spyder-ide.org/current/installation.html#anaconda
* Via pip (virtualenv/virtualenvwrapper) https://docs.spyder-ide.org/current/installation.htm#using-pip

Let us know if the info above helps!

**Comment by mateMathieu** [comment]
Hi, 

Ubuntu 22.04 is about to come out.
According to the current state of the repo, the candidate version is 4.2.1, which is the same as the previous version.
Can you please package the current version of Spyder 5 to the upcoming LTS version?

It happen that some of us are not in the need of fully stuffed conda environment. A simple version from the repos is enough. Hence my request.

Thanks

Best
M
https://packages.ubuntu.com/jammy/python/

**Comment by dalthviz** [comment]
Hi @mateMathieu we are not directly responsable to create the Spyder package in the different distributions (we release Spyder through PyPI, conda and by building standalone installers for Windows and MacOS only).

However, there are contributors like @juliangilbey that help with that. I'm not sure about the plan regarding the Ubuntu package (which maybe is related with the efforts that @juliangilbey is doing for Debian - I don't know the life cycle of ubuntu/debian packages to be honest). But we will be releasing Spyder 5.3.0 hopefully this week so maybe that version will be able to make it to a package 🤞🏼 (maybe @juliangilbey could give us a more clear idea of the plans for the debian package, which I think could impact the ubuntu package)

**Comment by juliangilbey** [comment]
Hi @mateMathieu, I imagine that there is very little chance of Ubuntu including Spyder 5.3.0 in 22.04, though having it in 22.10 is likely.  Ubuntu takes its packages from Debian, and it turned out that upgrading from 4.2.1 to 5.2.x was not feasible due to PyQt5 version incompatibilites.  I'm hoping that I will be able to release 5.3.0 in Debian within the next month or two (though real-life and technical challenges might mean that it takes somewhat longer).  Debian also doesn't yet have debugpy, which is proving to be a real headache to sort out, so it may be that we have Spyder without debugpy initially.

Also, as @dalthviz says, `pip install --user -U spyder`, possibly in a virtual environment, will always get you the latest and greatest version.

**Comment by ccordoba12** [comment]
I think the best is to create a virtualenv and then run

    pip install spyder

For issues with running pip with `--user`, see issue #17541.

**Comment by mateMathieu** [comment]
OK thanks for your constructive comments.

**Comment by ccordoba12** [comment]
Closing because I think this is solved now.
