### ISSUE TITLE
Feature: ipympl for plots pane

### ISSUE THREAD

**Issue by esillekens** [spyder-ide/spyder#17423]
Could ipympl be used instead of pngs for the plotting pane.

It is an interactive matplotlib backend https://github.com/matplotlib/ipympl

**Comment by ccordoba12** [comment]
Hey @esillekens, thanks for reporting. Unfortunately, that's not possible because the Plots pane only works with the Inline Matplotlib backend.

However, we're planning to create another pane that will display web content that results from running code. And when that's in place, the output of ipympl will be displayed on it.
