### ISSUE TITLE
spyder editor shows syntax error for match case statement 

### ISSUE THREAD

**Issue by JeepTJU** [spyder-ide/spyder#17436]
After the long awaited addition of the match-case statement in Python 3.10, I eagerly created a 3.10 venv and got spyder using it as the interpreter.  In general all is well, but I have noticed that the Spyder editor does seem to be confused about what is the correct syntax for 'match'.

First:, I am running on a Macbook Air M1 with:
* Spyder version: 5.2.2 None
* Python version: 3.9.5 64-bit ... This is from About Spyder, my python interpreter is a venv of python 3.10.2
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Darwin 21.3.0

Whenever I have a match-case statement e.g.,

`
string = 'alt 2'

match string:
    case 'option 1':
        print('yay 1')
    case 'alt 2':
        print('two')
    case _:
        print('_')
`

The Spyder editor marks the line with 'match' as 'invalid syntax' and puts a red 'x' to the left of the line and a red '-' at the right margin.

Interestingly, there are actually no problems running the script above.  The output in the ipython console is correct and no errors or warnings are given.   This appears to be just a cosmetic problem, but as I do actually use those red indicators to check for typos, or other problems, I would hate to start getting used to ignoring them just because they don't know how to deal with the new syntax.  I didn't find that this has been reported anywhere, nor could I find any solutions online.  Any suggestions?  Is this a known issue?

**Comment by ccordoba12** [comment]
Hey @JeepTJU, thanks for reporting. We use a third-party library called Pyflakes to display errors and warnings in our editor, so this is not something we can solve here.

Since it seems Pyflakes doesn't have support for Python 3.10 yet, please add next to your `match` statement a comment like this to avoid the editor display an error about it:

    match ... # noqa

I don't need if you need to do the same for `case` as well. Sorry for the inconvenience.

**Comment by MonicaGallo** [comment]
thnaksss
