### ISSUE TITLE
Debug does not run to breakpoint

### ISSUE THREAD

**Issue by norbmett** [spyder-ide/spyder#17449]
### What steps will reproduce the problem?

Spyder IDE 5.1.5
Python 3.8.8 64-bit | Qt 5.9.7 | PyQt5 5.9.2 | Windows 7 

Add breakpoint to file with block (""") comments
<ctrl-F5>: stops on second line (first """)
<ctrl-F12>: does not step
F9: steps through comment block and down the file but no data in the Variable explorer: no debugging just stepping

In the console window:
Remove all varialbes: Keyboard Interrupt (there were no variables anyway - but now the Console is frozen

"""Event loop integration for the ZeroMQ-based kernels."""
def process_stream_events():

Add a breakpoint to file with regualar comments
<ctrl-F5>: stops on first line without comments (#)
No statements are executed; attempting all the step 

Appears that Spyder is corrupted.

Submission by:
Norbert Metternich
norbmett@gmail.com

**Comment by ccordoba12** [comment]
Hey @norbmett, thanks for reporting. I think this error is already fixed in our latest version (5.2.2).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

After that, you can connect Spyder to your base environment by following these instructions:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment

Let us know if that works for you.

**Comment by norbmett** [comment]
Carlos, Option 1 worked.  The old 5.1.5 is in C:\Users\Norb\anaconda3 and the new 5.2.2 is in C:\Users\Norb\AppData\Local\Programs\Spyder\Python
