### ISSUE TITLE
Why Spyder 5.1.5 Application Launch Error?

### ISSUE THREAD

**Issue by hasnaaouadoudibelabzioui** [spyder-ide/spyder#17456]
I had problems launching Spyder version 5.1.5 after installing Anaconda navigator. The error is as follows : 
![spyder-error-launch](https://user-images.githubusercontent.com/52696287/157201351-ad39e378-ea12-4b58-8d0e-c80ae9c3867c.PNG)

When I launch Spyder by opening the Anaconda Prompt and running the corresponding command, It launches with the following error:
 
![error-from-anaconda-prompt](https://user-images.githubusercontent.com/52696287/157202010-3d48e8d4-22ec-41e4-8895-a0d5236136b5.PNG)

And After following all the steps outlined by @ccordoba12 which I have listed below:
`conda remove spyder
conda remove python-language-server
conda update anaconda
conda install spyder=5.1.5 `
I had the following errors:
![spyder-version-515-issues](https://user-images.githubusercontent.com/52696287/157202684-3e799d40-78ae-4a6b-9d24-86b0c513f236.PNG)

Anyone knows how I could fix this problem?Thanks for your time and consideration

**Comment by ccordoba12** [comment]
Hey @hasnaaouadoudibelabzioui, thanks for reporting. I'm afraid you'll have to uninstall Anaconda and reinstall it again to fix this problem. That will save you of a lot of headaches because the latest Anaconda comes with our 5.1.5 version.

Please see [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to learn how to do that correctly. And let us know if it works for you.

**Comment by AgamChopra** [comment]
Try to reset Spyder settings. Workes for me :)
