### ISSUE TITLE
Debugging no response

### ISSUE THREAD

**Issue by zhang8xiao2min** [spyder-ide/spyder#17507]
### What steps will reproduce the problem?

my_env
python=3.8.12
spyder=5.1.5
ipykernel=7.29.0
base_env Debug function available
my_env Debugging no response

**Comment by ccordoba12** [comment]
Hey @zhang8xiao2min, thanks for reporting. This error is already fixed in our latest version (5.2.2).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

After that, you can connect Spyder to your base environment by following these instructions:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment
