### ISSUE TITLE
Debugging does not function and then cannot be stopped

### ISSUE THREAD

**Issue by qmcablemodule** [spyder-ide/spyder#17569]
### What steps will reproduce the problem?

Anaconda and Spyder was updated recently (as defined, manually because automatic Anaconda update was not working).
Since then Spyder is not able to Debug and when I start (CTRL+F5) it initializes but freezes and cannot be stopped (by Stop button either), rather indicates:  "--KeyboardInterrupt--
For copying text while debugging, use Ctrl+Shift+C"

**Comment by qmcablemodule** [comment]
ABOUT
Spyder 5.1.5
Spyder IDE 
The Scientific Python Development Environment | [Spyder-IDE.org](https://www.spyder-ide.org/) 
Python 3.8.8 64-bit | Qt 5.9.7 | PyQt5 5.9.2 | Windows 10


DEPENDENCIES

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.2.2 (OK)
qtpy >=1.5.0                  :  1.11.2 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.25 (OK)
matplotlib >=2.0.0            :  3.5.0 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.9 (OK)

**Comment by ccordoba12** [comment]
Hey @qmcablemodule, thanks for reporting. This error is already fixed in our latest version (5.2.2).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

After that, you can connect Spyder to your base environment by following these instructions:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment

**Comment by ccordoba12** [comment]
Great! I'm glad things are working for you now.

**Comment by HanYuanHsu** [comment]
Hello [ccordoba12](https://github.com/ccordoba12),

I had the same problem and followed the instructions of your reply. I downloaded the Windows installer of Spyder 5..3.1 and then connected Spyder to my base environment (Anaconda). But then the IPython Console couldn't start properly and I got the following error message:

The Python environment or installation whose interpreter is located at
   ` C:\Users\a0306\anaconda3\python.exe`
doesn't have the spyder‑kernels module or the right version of it installed (>= 2.3.0 and < 2.4.0). Without this module is not possible for Spyder to create a console for you.

You can install it by activating your environment (if necessary) and then running in a system terminal:
    `conda install spyder‑kernels=2.3`
or
    `pip install spyder‑kernels==2.3.*`

I did conda install spyder‑kernels=2.3 but then I got the error message saying that spyder-kernels=2.3 was also not available in conda yet. Does spyder-kernels also have a Windows installer so that I can set it up manually?

**Comment by ccordoba12** [comment]
@HanYuanHsu, sorry, that doesn't work because Anaconda hasn't uploaded yet packages for Spyder-kernels 2.3.

So, you need to install all packages that you need to use from conda-forge as well. For instance, if you need to use Scikit-learn and Pytorch, you need to close Spyder, open the Anaconda Prompt and run

    conda activate spyder-cf
    conda install -c conda-forge scikit-learn pytorch

**Comment by HanYuanHsu** [comment]
Thank you for your reply! I will try that.

**Comment by qmcablemodule** [comment]
... or if you have a previously/separately installed Python version which includes iPython then you may connect it to Spyder. See the docs: https://docs.spyder-ide.org/5/panes/ipythonconsole.html?highlight=ipython, especially the "Any IPython Console, whether [external](https://docs.spyder-ide.org/5/panes/ipythonconsole.html?highlight=ipython#connecting-external-kernel)" part
