### ISSUE TITLE
Spyder doesnt show definition-source code of functions

### ISSUE THREAD

**Issue by YCAyca** [spyder-ide/spyder#17588]
Hello, I was using Spyder 5.1.5 and I was able to go to the function source code with only right clicking and selecting go to definition (or something like that) I don't know why but now I can't go to the source-definition of anything. I tried ctrl+G as I read in issues but it is not working too. I downgraded spyder to 4.1.3 but it still doesnt work. (In preferences completion and linking is already enabled so its not the problem too) Anyone has any idea?

**Comment by dalthviz** [comment]
Hi @YCAyca thank you for the feedback! Could you provide more info regarding your setup (dependencies, python version, spyder version, OS, etc? Also, maybe the docs related to the LSP could help: https://docs.spyder-ide.org/4/troubleshooting/common-illnesses.html#lsp-has-stopped-working

Besides that, if you are on Windows or MacOS, maybe you can give it a try to our standalone installers to have the latest Spyder version available at the moment (5.3.0): https://github.com/spyder-ide/spyder/releases/latest 

Any new info in order to reproduce this is greatly appreciated. Let us know if something of the above helps

**Comment by YCAyca** [comment]
Hello, Im using Linux Spyder 4.10.3. And when I updated Spyder for another reason to 4.1.5 it solved the problem...
