### ISSUE TITLE
What happened to the "Kite" engine being enabled via preferences.

### ISSUE THREAD

**Issue by AnthonyTheKoala** [spyder-ide/spyder#17587]
**Issue: cannot enable "Kite".**

Spyder version: 5.3
Python version: 3.9.10

Before version 5.3, I was able to use Kite.  Now I cannot enable.

In Spyder, you enable Kite by performing the following:
Preferences > Completion and Linting > Advanced Tab > Select "Providers"

Source article: https://help.kite.com/article/123-kite-cannot-detect-spyder-installation 

BUT in this Spyder 5.3, there is not "Providers" under the "Advanced Tab" and could not enable Kite.

Yes I do have a downloaded version of "Kite" setup that I saved.

Why cannot I use "Kite" which I downloaded.

Thank you,
Anthony of Sydney

### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by dalthviz** [comment]
Hi @AnthonyTheKoala thank you for the feedback! The thing is that in Spyder 5.3.0 we disabled the Kite provider (the PR where we did that is #17465 ) so for the moment if you want to still work with Kite you will need to use Spyder 5.2.2 or lower.

As a little bit of context, the thing is that currently the Kite service is unavailable as seen in their download page https://www.kite.com/kite-is-temporarily-unavailable/?source=download so we opted out for disabling the provider for the moment. Also, we have had some issues from users asking for the complete disable of Kite related support or Kite not working for them (as linked in the mentioned PR).

However, one of the options we have been discussing is to move the code related to an external plugin so in that way people can choose to have or not support for Kite from Spyder.

Pinging @ccordoba12 and @andfoy since they maybe have more insights regarding this.

**Comment by AnthonyTheKoala** [comment]
Thank you for the response.
I am glad I did save the installation executable file for "Kite" because I noticed that the site at https://www.kite.com/kite-is-temporarily-unavailable/?source=download has been saying for several months that the "Kite is temporarily unavailable".

No explanation has been given by the "Kite" site.

The "Kite" can still be used in the Visual Studio Code. 

Nevertheless, I prefer the Spyder IDE where even without the "Kite", I still get auto-completion with Spyder.

I let you close this issue.

Thank you 
Anthony of Sydney

**Comment by ccordoba12** [comment]
Closing because I think there's nothing else to discuss here.

**Comment by shakedAB** [comment]
Hey
After several attempts I could not find a version of Spider where both Kite and debug mode work.
For versions 5.0+ there is no option to run kite
For versions 4.0+ when running debug, an error message is received:
TypeError: runfile() got an unexpected keyword argument 'current_namespace'
How can I download a version where both modes work?
