### ISSUE TITLE
Spyder crash with mouse click on left edit margin 

### ISSUE THREAD

**Issue by vondreele** [spyder-ide/spyder#17599]
### What steps will reproduce the problem?

Do left mouse click with cursor in left margin of the edit window - spyder will exit abruptly with no error messages & no save. This happens most often when trying to paste lines into code.

* Spyder version: 5.1.5 None
* Python version: 3.7.1 64-bit
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

**Comment by ccordoba12** [comment]
Hey @vondreele, thanks for reporting. This error could be fixed in our latest version (5.3.0).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

Let us know if that works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by vondreele** [comment]
Dear Carlos,
Was on vacation. I did install (separately) the most recent spyder. Both issues I reported appear to be fixed. Unfortunately, the code I’m working on uses wx which isn’t included in the spyder install & I’m not sure about compatibilities. Would it be useful for me to patch my older spyder 5.1.5 to fix the issues? Or is that an absurd thing to do?
My old version:
* Spyder version: 5.1.5 None
* Python version: 3.7.1 64-bit
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10
Best,
Bob

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by ccordoba12** [comment]
> Was on vacation

No problem @vondreele. It's just that our policy is to close issues that hasn't seen activity in a week.

> I did install (separately) the most recent spyder. Both issues I reported appear to be fixed.

Great! I'm glad to hear that.

> Would it be useful for me to patch my older spyder 5.1.5 to fix the issues? Or is that an absurd thing to do?

Unfortunately, there have been hundreds of changes since 5.1.5 and I don't know which one fixed your problem (it could have been even the update to PyQt 5.15). So I think that's not feasible, sorry.
