### ISSUE TITLE
Unclosed spyder processes 2

### ISSUE THREAD

**Issue by vondreele** [spyder-ide/spyder#17600]
### What steps will reproduce the problem?

* Spyder version: 5.1.5 None
* Python version: 3.7.1 64-bit
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

Spyder will fail to completely close its Windows processes when closed with the red 'X'. Seems also to generate dead processes during operation.

**Comment by ccordoba12** [comment]
Hey @vondreele, thanks for reporting. This error is already fixed in our latest version (5.3.0).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder
