### ISSUE TITLE
tkinter doesnt work

### ISSUE THREAD

**Issue by MatanEshel** [spyder-ide/spyder#17601]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by ccordoba12** [comment]
Hey @MatanEshel, thanks for reporting. This error should be fixed in our latest version (5.3.0).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows or macOS installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

Since you didn't provide more details, I'm going to close this issue.
