### ISSUE TITLE
Evaluated / QA'ed the IDE, it can re-continue and work just well.

### ISSUE THREAD

**Issue by goodengineer** [spyder-ide/spyder#17628]
How that next errors will not happen / arise again (how to prevent) and how to repair:
...

_ERROR: spyder-kernels 2.3.0 has requirement pyzmq>=22.1.0; python_version >= "3", but you'll have pyzmq 18.1.1 which is incompatible.
ERROR: jupyter-client 7.2.1 has requirement pyzmq>=22.3, but you'll have pyzmq 18.1.1 which is incompatible.
ERROR: black 22.3.0 has requirement click>=8.0.0, but you'll have click 7.0 which is incompatible._

...

https://we.tl/t-UZuPjJTZ7F (after 1 week the file will be not at WeTransfer...)

<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!> ?

**Comment by ccordoba12** [comment]
Hey @goodengineer, thanks for reporting. What you did was a really bad move because you can't mix your Linux distro Python packages with the ones installed by pip. The problems with that are that (i) those packages are binary incompatible (i.e. they are compiled differently); and (ii) Linux distros use Python for a lot of different tasks, so introducing newer versions into your system can break it completely.

Now you need to remove all packages that you installed with pip, remove this directory

    /usr/lib/python3/dist-packages

and install Spyder in a virtual environment (you can follow [these instructions](https://linuxize.com/post/how-to-create-python-virtual-environments-on-ubuntu-18-04/) to learn how to do that).

Finally, if your Linux distro starts to throw random errors, I'm afraid you'll have to reinstall it because you broke it by installing Spyder with pip in root mode.
