### ISSUE TITLE
Can't update to the latest version of Spyder with pip or conda on Ubuntu

### ISSUE THREAD

**Issue by Po-Hsuan-Huang** [spyder-ide/spyder#17640]
### Issue Report Checklist

* [ v] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ v] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ v] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I can't update to the latest Spyder with apt, conda, or pip. 

### What steps reproduce the problem?

1.  conda update conda | conda list spyder
2. pip install --upgrade pip | pip list spyder
3. apt list -a <package name>

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

The latest version of Spyder on conda is 5.1.5
The latest version of Spyder on pip is 5.1.5
The latest version of Spyder on apt is 3.2.6

How do I update to the latest version of Spyder on Ubuntu?

Thanks!

**Comment by ccordoba12** [comment]
Hey @Po-Hsuan-Huang, thanks for reporting. Our latest version (5.3.0) is not available in Anaconda. That's why you can't update it with conda.

To get that version, you need to create a new environment with conda-forge packages. For that, please close Spyder, open a terminal and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

Let us know if that works for you.

**Comment by Po-Hsuan-Huang** [comment]
@ccordorba12
Thanks. It works in the new environment. 
 However, when I try to install the package to the existing environmnet wity 

`conda install -c conda-forge spyder`
I encounter

`conda install -c conda-forge spyder`
`Collecting package metadata (current_repodata.json): done`
`Solving environment: failed with initial frozen solve. Retrying with flexible solve.`
`Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.`
`Collecting package metadata (repodata.json): done`
`Solving environment: failed with initial frozen solve. Retrying with flexible solve.`
`Solving environment: \ / - | - / \ failed`

CondaError: KeyboardInterrupt

It took too long so I interrupt the process.

**Comment by ccordoba12** [comment]
You can't install Spyder in your default environment (otherwise I've advised you to do that from the beginning). That's because it's not possible to mix conda and conda-forge packages since they are binary incompatible (i.e. they are compiled differently).

This means that if you need, for instance, Pandas for your work, you need to reinstall it in your new environment. In other words, you need to run the following commands:

    conda activate spyder-cf
    conda install -c conda-forge pandas

And you need to do the same for any other package that you need.

Sorry for the inconvenience, but this problem happens because Anaconda takes months to update Spyder, so now our users need to install it from conda-forge.

**Comment by ccordoba12** [comment]
I'm going to close this issue because I think your problem is solved now.
