### ISSUE TITLE
Cannot execute any code

### ISSUE THREAD

**Issue by LnSHampton** [spyder-ide/spyder#17681]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
I have a single line of code in my program, which is:

num_of_cards = int(input('Input the number of cards:\n'))

I highlight the line and press F9.

This error appears.

**Comment by LnSHampton** [comment]
Here are the details of the error:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 278, in _handle_input_request
    return super(DebuggingWidget, self)._handle_input_request(msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 512, in _handle_input_request
    self._readline(msg['content']['prompt'], callback=callback, password=msg['content']['password'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\qtconsole\console_widget.py", line 2422, in _readline
    self._show_prompt(prompt, newline=False, separator=False)
TypeError: _show_prompt() got an unexpected keyword argument 'separator'

**Comment by ccordoba12** [comment]
Hey @LnSHampton, thanks for reporting. This error is already fixed in our latest version (5.3.0).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

**Comment by vipul92750** [comment]
@ccordoba12 Thanks.. 
Your said solution solved my problem.
Thank you so much again....!!! :-)

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know @vipul92750.
