### ISSUE TITLE
input exception

### ISSUE THREAD

**Issue by blablalf** [spyder-ide/spyder#17777]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
Every time I call the input() function I got crash from spyder.
Previously I made the mistake of re-defining the input() function. Of course I have reset the console and erased all the variables but now I only got crashes... And my program doesn't work.

**Comment by dalthviz** [comment]
Hi @blablalf thank you for the feedback. Could you share your setup info with us (Spyder version, Python version, dependencies versions, OS, etc)? Also, do you saw any type of traceback when this happened? Without more info there is not much we can do to help, sorry :/

Just in case the latest Spyder version available is 5.3.0. If you are not using it I would recommend you to update. If you use conda you will need to use the conda-forge channel. In order to not mix channels usually the most simple approach is to create a new env using only conda-forge packages with something like:

    conda create -n spyder-env -c conda-forge python=3.9 spyder=5.3.0

Another way to install Spyder 5.3.0 is to use our standalone installers (for Windows and MacOS) available at our release page: https://github.com/spyder-ide/spyder/releases/latest

Let us know if something of the above helps or you have more info

**Comment by dalthviz** [comment]
Closing due to lack of response
