### ISSUE TITLE
missing positional argument 'hidden'

### ISSUE THREAD

**Issue by gizemkar** [spyder-ide/spyder#17780]
I get below error message 
  
 silent_exec_method')
TypeError: __new__() missing 1 required positional argument: 'hidden'
Traceback (most recent call last):

How can I fix it?

Thank you,

**Comment by ccordoba12** [comment]
Hey @gizemkar, thanks for reporting. This error is already fixed in our latest version (5.3.0).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder
