### ISSUE TITLE
Debugger not working

### ISSUE THREAD

**Issue by armenkon** [spyder-ide/spyder#17818]
### What steps will reproduce the problem?

Im just clicking on debug and the blue arrow is not showing up and I cannot exit debuger mode

**Comment by ccordoba12** [comment]
Hey @armenkon, thanks for reporting. This error should be fixed in our latest version (5.3.0).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder
