### ISSUE TITLE
line debugger dose not working

### ISSUE THREAD

**Issue by jason7707** [spyder-ide/spyder#17891]
### What steps will reproduce the problem?

I started debugger(ctrl+F5) then debugger does not working
(I pushed ctrl+F10) <-- does not work

**Comment by ccordoba12** [comment]
Hey @jason7707, thanks for reporting. I think this error is fixed in our latest version (5.3.0).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows or Mac installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

Please try any of those methods and let us know if it works for you.
