### ISSUE TITLE
Debugger not running - only displays first lines of script

### ISSUE THREAD

**Issue by TheLagger1998** [spyder-ide/spyder#17943]
Whenever i try running the debugger, it just displays the first few lines of the scripts and then gets stuck. If i try to terminate the debugger, it gives the message '--KeyboardInterrupt--' but without actually terminating the debugger

**Comment by ccordoba12** [comment]
Hey @TheLagger1998, thanks for reporting. This error could be fixed in our latest version (5.3.0).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows or Mac installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt (Windows) or Terminal (Mac) and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

Let us know if it works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
