### ISSUE TITLE
GB                                

### ISSUE THREAD

**Issue by vaibhavi071** [spyder-ide/spyder#17996]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by dalthviz** [comment]
Hi @vaibhavi071 I'm closing this one since no information was supplied but from the way this was generated I would suggest you to update to the latest Spyder version available (5.3.1). If you are using Windows or MacOS you can install it from the standalone installers available on our release page: https://github.com/spyder-ide/spyder/releases/tag/v5.3.1
