### ISSUE TITLE
python language server not working

### ISSUE THREAD

**Issue by Dan-Patterson** [spyder-ide/spyder#18024]
## Problem Description
No linting and pls just spins on the status line.
I know this issue has been addressed in subsequent releases, but I am stuck with only being able to use packages from Anaconda's main channel, which is woefully slow to update packages to newer versions.

If there were lines of code that needed to be altered or module(s) that needed to be updates, could you please point me to the link that might provide me with a solution so I can try to fix this manually (aka a  backport fix would be appreciated).

Best regards

## Versions

* Spyder version:   5.1.5
* Python version:   3.9.10
* Qt version: 
* PyQt version: 
* Operating System name/version:   Windows 11

### Dependencies
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.21.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  5.6.1 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.7.4 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.3.0 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  60.10.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  None (OK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.20.1 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.9 (OK)

```

**Comment by mrclary** [comment]
@Dan-Patterson, thanks for reporting the issue. I would recommend updating to our latest Windows standalone application: https://github.com/spyder-ide/spyder/releases/download/v5.3.1/Spyder_64bit_full.exe . This will have the latest packages for running Spyder and does not rely on Anaconda's main channel packages.

Let me know if that works better for you.

**Comment by Dan-Patterson** [comment]
The windows standalone won't work for me since I have to install spyder in a specific site-packages location within a distribution that has to be vetted through the Anaconda main channel (very, very long story).  If it was a matter of updating something within the 5.1.5 distribution or even editing code there, I am comfortable doing that.

5.1.5 worked without issue with python 3.7.x and there are no conflicts with other packages between the versions, so it was either an upgrade in one of the packages to a specific version or edits to spyder code.

If this isn't possible, I understand, but I would follow your suggestion if the full development environment I work under were in my control, but it isn't.

PS.  What is up with Anaconda?  There is lots of "action" but it is taking a long time to get new versions updated (spyder and numpy in particular)

**Comment by mrclary** [comment]
@Dan-Patterson, okay, so the standalone application is not an option for you. I understand how frustrating it is to wait for packages to update on the main conda channel; it it possible for you to use the conda-forge channel, even temporarily, instead of the main channel? I'm not familiar with vetting stuff through the Anaconda main channel; I suppose that means all the package must already be available on the main channel, correct?

@spyder-ide/core-developers any ideas?

**Comment by dalthviz** [comment]
I think from Spyder 5.1.5 to the current release 5.3.1 quite some work has been done related with the Python Language Server and not only over the Spyder side but also over the `python-lsp-server` (its current version is 1.4.1) and some plugins like `pyls-black` (its current version is 1.2.1).

Maybe you could try to edit the env where Spyder is intalled setting the minimum required versions for the python language server related packages as they were in the `setup.py` for Spyder 5.1.5: https://github.com/spyder-ide/spyder/blob/v5.1.5/setup.py#L203

Also, if it is possible for you to create a Spyder installation using Python 3.7.x that works without issue maybe doing a diff between the packages version installed with that Python version vs the versions installed when using Python 3.9 could give you some hints about what packages versions could help making the Python language server work.

If you can't use the conda-forge channel or even pip (creating an env with only python from conda and then installing the rest using pip), I think there is not much that we can help, sorry :/

About Anaconda, we don't know either, actually some Spyder dependencies like QtConsole got updated on the default channel and that creates issues too since 5.1.5 is incompatible with recent version of those dependencies a no upper constraint was added so that ends up in issues related with incompatibilities :/

**Comment by Dan-Patterson** [comment]
Many thanks to the two of you.  I will give a few things a try.... besides... who makes coding errors anyway ;)
