### ISSUE TITLE
Spyder code analysis don't access variables in workspace

### ISSUE THREAD

**Issue by udriss** [spyder-ide/spyder#18044]
Is there a way for the code analyzer to take into account the variables present in the workspace?

For example, I run a code that calculates a large variable. Then, I comment this code. Then, I use the big variable in the rest of the code.
When I do this, the parser tells me that the variable has not been defined. Yet it is present in the workspace. With RStudio it is possible to do, I sincerely hope it can also be the case with Spyder. With Pycharm it is not possible hence my arrival on Spyder.

**Comment by ccordoba12** [comment]
Hey @udriss, thanks for reporting. You said:

> Is there a way for the code analyzer to take into account the variables present in the workspace?

Unfortunately, that's not possible. And it's much better that that can't be done because it warns our users that their code won't run outside Spyder and without the current session.

> With RStudio it is possible to do, I sincerely hope it can also be the case with Spyder. With Pycharm it is not possible hence my arrival on Spyder.

I don't know why RStudio allows that but I think it's a very bad programming practice.

**Comment by udriss** [comment]
@ccordoba12, thank you very much for your rapid and clear answer. The best it is to let the coder choose for instance Spyder have an option "Run in console's namespace instead of an empty one" which very great ! 👍 
I'm just guessing, why not an other option like  "Run code analyser in console's namespace instead of an empty one" and let the console do the rest of the job. With RStudio, it's the case.

I'm lit bit confusing, with RStudio there isn't any code analyser, sorry.

**Comment by ccordoba12** [comment]
> I'm just guessing, why not an other option like "Run code analyser in console's namespace instead of an empty one" and let the console do the rest of the job. With RStudio, it's the case.

First, we don't like to add more config options unless it's really necessary. And second, passing the declared variables in the console to the editor is not easy task at all.

> I'm lit bit confusing, with RStudio there isn't any code analyser, sorry.

I don't understand very well what you mean by this but just because RStudio does it does mean that Spyder should do it as well. As I said, I think that's a really bad programming practice and users need to be aware of it.
