### ISSUE TITLE
code is not working

### ISSUE THREAD

**Issue by Dakshina152** [spyder-ide/spyder#18056]
n=input
print(n)
n=input('hello')
<bound method Kernel.raw_input of <spyder_kernels.console.kernel.SpyderKernel object at 0x000001A05CDFB4F0>>

**Comment by ccordoba12** [comment]
Hey @Dakshina152, thanks for reporting. This error is already fixed in our latest version (5.3.1).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder
