### ISSUE TITLE
error when running my code

### ISSUE THREAD

**Issue by alirezabaghi73** [spyder-ide/spyder#18083]
### What steps will reproduce the problem?

when running my code that error appears
my codes run in Python IDLE.

i think input structure in spyder occurs this error

**Comment by ccordoba12** [comment]
Hey @alirezabaghi73, thanks for reporting. This error is already fixed in our latest version (5.3.1).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder
