### ISSUE TITLE
error in function

### ISSUE THREAD

**Issue by bidariyannader** [spyder-ide/spyder#18116]
### What steps will reproduce the problem?

pleas hellp me icant use this function(input()) why ???

**Comment by ccordoba12** [comment]
Hey @bidariyannader, thanks for reporting. This error is fixed in our latest version (5.3.1).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder
