### ISSUE TITLE
Debugging mode is not working

### ISSUE THREAD

**Issue by VinayKillamsetty** [spyder-ide/spyder#18294]
### What steps will reproduce the problem?

When I run the code in debugg mode it simulates 2-3 lines and becomes irresponsive.
I need to restart spyder or reset kernal to use spyder again

**Comment by dalthviz** [comment]
Hi @VinayKillamsetty and @sguysc if you are using conda I would suggest you to create a new environment using only conda-forge packages to get the latest Spyder version. This is necessary since the default channel is stuck in Spyder 5.1.5 (a more than nine month old Spyder version which is broke do new dependencies versions available on the default anaconda channel like qtconsole or jupyter_client) and we don't have control over that unfortunately :/. To create the new env, you should run from an Anaconda  prompt something like this:

    conda create -n spyder-env -c conda-forge spyder

That should get you the latest Spyder version (currently 5.3.1) installed. Also, in general, mixing channels by for example installing things with conda-forge on your base environment can cause issues and mess up your Anaconda installation.

If you use Windows or MacOS I would also suggest to try our standalone installers available at our release page: https://github.com/spyder-ide/spyder/releases/latest

Let us know if something of the above helps.

**Comment by sguysc** [comment]
I installed via your command and got no errors, activated the spyder-env and ran `spyder`. This is what I get:
```
Traceback (most recent call last):
  File "/home/userrr/anaconda3/envs/spyder-env/bin/./spyder", line 7, in <module>
    from spyder.app.start import main
  File "/usr/lib/python3/dist-packages/spyder/app/start.py", line 14, in <module>
    import zmq
  File "/usr/lib/python3/dist-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/usr/lib/python3/dist-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/usr/lib/python3/dist-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/usr/lib/python3/dist-packages/zmq/backend/select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/usr/lib/python3/dist-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name 'constants' from partially initialized module 'zmq.backend.cython' (most likely due to a circular import) (/usr/lib/python3/dist-packages/zmq/backend/cython/__init__.py)
```

**Comment by dalthviz** [comment]
Seems like this error comes from the previous actions you tried (installing Spyder in your base env using  `pip install --user` and using the conda-forge channel on your base env). Maybe check if there are any Python related things at `~./local` and remove them. If that doesn't help, I would suggest to reinstall anaconda and create again a new env with only conda-forge packages to get the updated Spyder version. Besides this suggestions I think there is not much more we can do to help, sorry :/

**Comment by VinayKillamsetty** [comment]
Hi, dalthviz.
Your suggestion helped me to resolve the problem.
But, I am still unable to properly install PyTorch in this environment.

i tried to install pytorch using
conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch

It got successfully installed.
But later I am unable to import pytorch in my code
