### ISSUE TITLE
Hanging on debug mode

### ISSUE THREAD

**Issue by Saubhik-Som** [spyder-ide/spyder#18552]
### What steps will reproduce the problem?

Write any code and debug. It will stay unresponsive even after restarting kernel

**Comment by ccordoba12** [comment]
Hey @Saubhik-Som, thanks for reporting. This error is already fixed in our latest version (5.3.1).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows or Mac installers, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder
