### ISSUE TITLE
kite is not working in spyder

### ISSUE THREAD

**Issue by chaitulucky007** [spyder-ide/spyder#18574]
### What steps will reproduce the problem?

1.after first time installation of spyder i downloaded kite and its plugins for spyder.
2.then restarted both kite and spyder
3.when i go to tools-preferences-completion and linting-advanced settings , i didn't find kite options.
4.i cant able to import kite module.
5.while trying from kiteconnect import kiteconnect it shows yellow caution mark, it gives message kiteconnect.kiteticker is imported but unused(pyflakes E)
6.please help me . i am new to software field

**Comment by ccordoba12** [comment]
Hey @chaitulucky007, thanks for reporting. Kite support is no longer available in Spyder because Kite is no longer developed by the company that created it.

Due to that, we removed our support for it in Spyder 5.3.0, released last March. Older versions could work with Kite, but we don't offer support for them, sorry.
