### ISSUE TITLE
Debugging hangs Ipython

### ISSUE THREAD

**Issue by AllenKll** [spyder-ide/spyder#18608]
### What steps will reproduce the problem?

fresh install of anaconda3 on up to date windows 10
create a file with the following code:
```
print("hello world")
```
press the debug button.
observe console hanging.
pressing stop debug button produces:
```
--KeyboardInterrupt--
For copying text while debugging, use Ctrl+Shift+C
```

only way to stop is to close the console and force reopen another one.
also pressing continue, step or anything does nothing.

Running the file works fine, but debugging is completely broken with no functionality at all.

**Comment by nicholastoddsmith** [comment]
Looks like this was already fixed: https://github.com/spyder-ide/spyder/issues/18552

**Comment by ccordoba12** [comment]
Hey @AllenKll, thanks for reporting. This error should be fixed in our latest version (5.3.1).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows or Mac installers, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

Please do that and let us know if it works for you.

**Comment by AllenKll** [comment]
Number 2 worked. 
 It created a link to spyder in a different directory than the default anaconda install ('Anaconda3' instead of 'Anaconda3 (64-bit)')   but it did work none the less.

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
