### ISSUE TITLE
input not working in vscode 

### ISSUE THREAD

**Issue by 8thmane** [spyder-ide/spyder#18664]
### I type this simple line of code
input = input()
print(input)

**Comment by maurerle** [comment]
By writing `input = input()` you are overwriting the built-in function `input()` with your string from the input.
Therefore it will only work once in your program.

This should be fixed by using a different name for your assigned variable:

```python
input_string = input()
print(input_string)
```

Just to mention: This is the repository from the Spyder IDE and does not focus on general python questions in vscode.
Yet I hope I could have helped.

Best regards

**Comment by dalthviz** [comment]
Thanks for the help with this @maurerle ! @8thmane as explained above this issue is unrelated with Spyder so I'm closing it. Hopefully the explanation above is clear for you
