### ISSUE TITLE
Cannot launch Spyder from Anaconda (Old) #18525

### ISSUE THREAD

**Issue by thomastskng** [spyder-ide/spyder#18674]
This is following up on an old issue #18525.  
hi @ccordoba12 , sorry for delayed reply. 

Which is the recommended way for installing Spyder, 1) via anaconda or 2) window standalone installer ? Because i used option 2 (window standalone installation) before and ran into an issue whereby I cannot double click and open up the dataframe in variable explorer within spyder and i was advised to install spyder via anaconda.

2nd question: for your step 2 above, what is the purpose of Create a new environment with conda-forge packages ?

3rd question: I am confused because you asked me to install the window standalone spyder and then open the Anaconda Prompt and run the following commands below. So, I shall install both the window standalone spyder PLUS anaconda ?

4th question: I intend to use conda install most of the packages. However, sometimes a package might not be available on conda-forge and is only available via pip install. How can I do pip install that particular package without having conflicts with my existing conda-installed packages ?

**Comment by ccordoba12** [comment]
Hey @thomastskng, sorry, I missed this issue. You said

> Because i used option 2 (window standalone installation) before and ran into an issue whereby I cannot double click and open up the dataframe in variable explorer within spyder and i was advised to install spyder via anaconda.

You need to use Pandas >= 1.4 in your external environments, in case your using connecting Spyder to the conda environments. Otherwise, you'll get the error you describe.

> 2nd question: for your step 2 above, what is the purpose of Create a new environment with conda-forge packages ?

This is another way to install the latest Spyder version because packages in Conda-forge are always up tp date. Furthermore, this will give you the advantage of using Spyder with packages that are not part of its installer but are present in Conda-forge (e.g. Scikit-learn).

> 3rd question: I am confused because you asked me to install the window standalone spyder and then open the Anaconda Prompt and run the following commands below. So, I shall install both the window standalone spyder PLUS anaconda ?

You were not clear about what installation method you used. As far as I can read on issue #18525, you said you used Anaconda to install Spyder, not our Windows installer.

> 4th question: I intend to use conda install most of the packages. However, sometimes a package might not be available on conda-forge and is only available via pip install. How can I do pip install that particular package without having conflicts with my existing conda-installed packages ?

This is tricky but my recommendation is for you to check all dependencies of the pip package you want to install to see if they are available in Conda-forge. For that, you need to look for the project you want to install on Github and check its `setup.py`, `setup.cfg` or `pyproject.toml` files.

If some dependencies are available on Conda-forge, then use conda to install them from there. If not, just run `pip install <my-package>`. Otherwise, you'll break your environment.

**Comment by ccordoba12** [comment]
Let me know if you need anything else.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
