### ISSUE TITLE
unexpectly shutdown

### ISSUE THREAD

**Issue by liuhuanku** [spyder-ide/spyder#18775]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by ccordoba12** [comment]
Hey @liuhuanku, thanks for reporting. Please try to install our latest version (5.3.2) to see if that fixes your problem.

Since it's still not available in Anaconda, you have two options:

1. Use our Windows or Mac installers, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

Since you didn't provide any additional option, I'm going to close this issue.
