### ISSUE TITLE
input() is creating problem

### ISSUE THREAD

**Issue by UmaMaheswariGajjarapu-EATON** [spyder-ide/spyder#18834]
### What steps will reproduce the problem?

While I am taking a input the popup window problem reports

**Comment by dalthviz** [comment]
Hi @UmaMaheswariGajjarapu-EATON although you no specify the Spyder version you are using, If you are having troubles with the input function most probably your issue is a duplicate of #17616 . To fix that you will need to update to the latest Spyder version following one of the options described here: https://github.com/spyder-ide/spyder/issues/17616#issuecomment-1088750490

Let us know if something of the above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
