### ISSUE TITLE
Error when trying to plot local variables in variable explorer when using Spyder 5.3.2

### ISSUE THREAD

**Issue by bburne** [spyder-ide/spyder#18856]
my python file:

import numpy as np
def func():
    bb = np.arange(10)
    return bb      # breakpoint here

a = np.arange(5)
cc = func()
put a breakpoint before return bb and debug the file
the program stops before return, and now two variables in the variable explorer:
* global variable a = array([0, 1, 2, 3, 4])
* local variable bb = array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
right click on a and select plot, no problem. BUT, right click on bb and select bb, report ***KeyError: 'bb'

I find version 5.3.1 hasn't this problem. Only appears in 5.3.2.

**Comment by dalthviz** [comment]
Hi @bburne thank you for the feedback! I was able to reproduce this with Spyder 5.3.2:

![imagen](https://user-images.githubusercontent.com/16781833/181808202-c03ee68d-5b5e-45f6-84e7-a5f2f6e31ea5.png)

Pinging @ccordoba12 and @impact27 (maybe they could know what is happening here)

**Comment by impact27** [comment]
Yes so what is happening is:
When the kernel tries to get the value of 'bb', it will look at the current namespace. But what is the current namespace? Usually it is the shell namespace. While debugging however, if we are stopped on a frame, it will return the frame namespace instead. The problem is that when you run a command, the debugger is not stopped at a prompt, and therefore looks at the global user namespace.

**Comment by dalthviz** [comment]
Thanks for the explanation and submitting a fix on spyder-kernels ! 👍🏼

**Comment by ccordoba12** [comment]
@impact27, could a test here to check that plotting from the Vairable Explorer works while debugging? I mean, with the `%varexp` magic?

That way we'll be sure new changes don't break this feature in the future.

**Comment by impact27** [comment]
Yes I could do that
