### ISSUE TITLE
Input Function not working 

### ISSUE THREAD

**Issue by philhoy** [spyder-ide/spyder#18862]
### What steps will reproduce the problem?

input('what is your name')

This will not print anyhting to the conlose when I try to run it?

**Comment by ccordoba12** [comment]
Hey @philhoy, thanks for reporting. This error is already fixed in our latest version (5.3.2).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows or Mac installers, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

**Comment by philhoy** [comment]
This goes in out of working. It worked for a day. Then stoped working. I tried sending another query and it started to work shortly after. Shutting down and restarting. But then the following day it will stop working?
