### ISSUE TITLE
Spyder launch problem

### ISSUE THREAD

**Issue by kindofblue99** [spyder-ide/spyder#18933]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
Spyder launch problem after "conda update --all" and "conda install -f python.app"

**Comment by dalthviz** [comment]
Hi @kindofblue99 , usually running `conda update --all` is not the best. Since you runned to `conda install -f python.app` my guess is that you are running on MacOS? Without any further info about your setup (Spyder version, OS, Python version, dependencies, etc) there is not much we can do to help.

The only suggestion we could give is to either install Spyder from our MacOS standalone installer available at our [release page](https://github.com/spyder-ide/spyder/releases/latest) or create a new conda environment using the conda-forge channel.

To create a new environment you can run from the terminal something like:

    conda create -n spyder-cf -c conda-forge spyder

And then to activate the env and run Spyder, something like:

    conda activate spyder-cf
    spyder

If you have more info maybe we could have more suggestions to help fix your setup. Let us know if something of the above helps!

**Comment by kindofblue99** [comment]
Hi,
I updated my MacOS to Monterey before  "conda update --all" and "conda install -f python.app". 
Anyway, this problem was solved now by doing the following steps. 

> conda create -n spyder-dev python=3
> conda activate spyder-dev
> pip install -U spyder
> conda activate spyder-dev
> export QT_MAC_WANTS_LAYER=1
> spyder

My current python version is Python 3.10.5. 
Thanks!

**Comment by dalthviz** [comment]
Glad to hear that you managed to fix your setup @kindofblue99 ! I will close this one as completed but if you have any other issues or comments let us know 👍🏼
