### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by Kavyarao01** [spyder-ide/spyder#19129]
### What steps will reproduce the problem?

Not able to install flask shows error as 
pip install flask
Note: you may need to restart the kernel to use updated packages.
C:\Users\kavya\anaconda3\python.exe: No module named pip

restarted kernel multiple times

C:\Users\kavya>pip install pip
Requirement already satisfied: pip in c:\users\kavya\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (22.2.2)

**Comment by ccordoba12** [comment]
Hey @Kavyarao01, thanks for reporting. It seems you have two Python installations in your system, which are conflicting among them: an Anaconda installation present in

    C:\Users\kavya\anaconda3\

and one in this directory:

    c:\users\kavya\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0

Please remove the last directory and uninstall and reinstall Anaconda again to solve it.

After that, if you need to install additional packages. please open the Anaconda Prompt and run there:

    conda install flask

Don't try to run that command in Spyder's IPython console because it's not meant for that.

Let us know if that works for you.

**Comment by Kavyarao01** [comment]
Hello,
Thank you  for replying @ccordoba12 .
I have reinstalled Anaconda that fixed the issue

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
