### ISSUE TITLE
Traceback from Editor/Debugger plugin when using same environment to launch different Spyder branches (master vs 5.x)

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#19728]
## Problem Description

When launching from master (previously having launched from 5.x on the same env) I got a traceback on the Anaconda prompt regarding the Debugger actions from the Editor. Maybe a validation is missing there or something is missing on the `bootstrap.py` script when changing branches? 

### What steps reproduce the problem?

1.  Launch Spyder from the master branch on an env that previously was used to launch the 5.x branch

### What is the expected output? What do you see instead?

No traceback

### Paste Traceback/Error Below (if applicable)

```python-traceback
Traceback (most recent call last):
  File "e:\acer\documentos\spyder\spyder\spyder\plugins\editor\plugin.py", line 1585, in setup_other_windows
    action = self.main.debugger.get_action(action_name)
AttributeError: 'NoneType' object has no attribute 'get_action'
```

## Versions

* Spyder version: 6.0.0.dev0 02aeb4d82 (conda)
* Python version: 3.10.5 64-bit
* Qt version: 5.15.3
* PyQt5 version: 5.15.4
* Operating System: Windows 10

**Comment by ccordoba12** [comment]
This happens because the entry point for the Debugger plugin is not installed given that we detect that Spyder is already installed in editable mode. My solution is to run

    pip uninstall spyder
    python bootstrap.py

which reinstalls Spyder and makes the Debugger plugin work. However, that generates a similar traceback when moving back to `5.x`, which requires running the same two commands again.

So, the ideal solution would be to automatically detect that we switched branches to uninstall Spyder automatically before checking/installing it in editable mode. @mrclary, any chance that you could take a look at this one?

**Comment by mrclary** [comment]
I suppose we could write to a file in spyder's config directory that simply records the branch of current bootstrap execution. On bootstrap, the file is read, and if the current branch has changed from master/not-master then spyder is reinstalled.

What do you guys think?
