### ISSUE TITLE
Installing and removing Kite plugin messed everything up 

### ISSUE THREAD

**Issue by sarpsomer** [spyder-ide/spyder#19770]
Time to time for specific tasks I use Spyder. Today I updated Spyder and everything was going smooth. Then a Kite Plugin installer prompt window opened, I was thinking its a new Spyder feature and ended up installing service, login prompt, .... I immediately uninstalled and stopped the service. Now even I reset spyder, it crashes each time.
As an open source developer you shouldn't add this kind of malware plugin to long years of work of your codebase. 
Anyone can suggest me a good ide for conda environment?

**Comment by ccordoba12** [comment]
Hey @sarpsomer, thanks for reporting and sorry for the inconvenience that installing Kite caused to you. We removed support for it six months ago because it stopped being developed, so you're probably using an old Spyder version and need to update it. 

Furthermore, although it's hard to tell, I think it was well received by our community because we got very few bad comments about it.
