### ISSUE TITLE
Working Directory error when changing a drive letter

### ISSUE THREAD

**Issue by mfatih7** [spyder-ide/spyder#19872]
Hello 

In your working environment on WIN10, Let's say that you generate a new drive and call it K.
Then you go

Preferences -> Working Direcory -> New Consoles - > The Following Directory

and assign a folder from drive K to the The Following Directory

Then you decide to close drive K in your PC.
After that, if you want to change The Following Directory to another drive on your PC. Spyder gives an error.
It probably cannot find the old folder on K and therefore does not let to assign a new folder for The Following Directory.

best regards

**Comment by dalthviz** [comment]
Hi @mfatih7 thank you for the feedback! I was unable to reproduce this. Could it be possible for you to share the traceback or error that is being generated when the error is raised in your setup? Also, could it be possible for you to share a video or gif to understand better the steps to reproduce this? Also, what Spyder version are you using and how did you install Spyder (standalone installer, conda, pip, etc)?

Let us know!

**Comment by dalthviz** [comment]
Thanks for the new info! I checked using Spyder 5.3.3 and changing the drive letter with the `Disk management` utility (an external USB from `M:` to `D:`) nd while doing that I got some warnings and messages (my OS is in Spanish) but no error on the Spyder side:

### The current drive is being used and changing the letter could cause problems with the programs using the drive

![imagen](https://user-images.githubusercontent.com/16781833/196747007-2385d283-e429-4ef5-b186-700bb55ceae0.png)


### The drive will be asigned the new letter but it will be available still with the initial letter until restart and a warning about the possible problems related with the change (programs being unable to be launched):

![imagen](https://user-images.githubusercontent.com/16781833/196747725-4383f66f-774c-4d86-ad66-8acb6951cb77.png)

After that the drive letter changes on the Windows Explorer and I'm able to enter the preferences dialog and change the Working directory preference:

![imagen](https://user-images.githubusercontent.com/16781833/196749419-310d30ff-5fd6-4050-8dee-077a123323bf.png)

I would suggest you to try to update Spyder to see if that helps, but any other info in order to reproduce this with the latest Spyder release available is also greatly appreciated
