### ISSUE TITLE
Newly installed Spyder 5.3.3 terminates due to a 'fatal error' immediately after launch

### ISSUE THREAD

**Issue by Kuulest** [spyder-ide/spyder#19914]
## Problem Description

I copied the app from the dmg into /Application, started and it immediately terminated with a _fatal error_. Within the system console the line `22:49:09.977757 +0200	Spyder AEGetDescData of non-desc type 'reco' not a good idea` showed up.

(The final installation by MacPorts (p310-spyder ) crashes in a very similar way! I'll attach the **crash report of the application made by MacPorts**.  Maybe it's somehow useful?)

### What steps reproduce the problem?

1.  restarting the app
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.3.3 (downloaded dmg from this website)
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: macOS X.14.6

### Dependencies

```
PASTE DEPENDENCIES HERE
```
[Python_2022-10-23-223644_MacBookPro15-Martin.txt](https://github.com/spyder-ide/spyder/files/9847579/Python_2022-10-23-223644_MacBookPro15-Martin.txt)

**Comment by ccordoba12** [comment]
Hey @Kuulest, thanks for reporting. You said you're using

> Operating System name/version: macOS X.14.6

Unfortunately, our latest dmg (i.e. the one for Spyder 5.3.3) only works on macOS 11 or higher, and all previous versions worked on 10.15 or higher. We are unable to produce dmg's for older versions because we create them on Github and those are the Mac versions it offers.

> (The final installation by MacPorts (p310-spyder ) crashes in a very similar way! I'll attach the crash report of the application made by MacPorts. Maybe it's somehow useful?)

I guess the problem is the same, but we can't help you with that. So we recommend you to open an issue with them if you want to pursue that path. However, I think your best change is to use Spyder is to download and install Anaconda, which comes with Spyder and according to [this page](https://docs.anaconda.com/anaconda/install/#old-os) supports 10.13 or higher.

**Comment by Kuulest** [comment]
I've downloaded the 5.3.2.dmg from GitHub and it works flawlessly with X.14 (until now 🙂)

**Comment by ccordoba12** [comment]
Ok, thanks for letting us know about it.
