### ISSUE TITLE
Theme does not adapt to OS anymore (Windows)

### ISSUE THREAD

**Issue by maelh** [spyder-ide/spyder#19953]
In Spyder 3 (and possibly 4) the GUI would adapt or mimick the style of the Windows interface and selected theme. Now it looks like a foreign application, which is quite distracting.
The option to select a Windows/Vista etc. theme is gone as well.

UI font has also become smaller (not a high DPI issue), but a theme issue.
Both Spyder 3 and 5 were used on the same Windows version, and the change was directly comparable after updating from 3 to 5.

Especially, relevant GUI items like tabs are layouted differently now (bottom tabs like "help", "variable explorer", "plots", "files" are centered). It was nicer when it was left aligned, since you could unconsciously aim for the border, instead of having to look at the whole window to aim for the middle then readjust to the left or right.

OS consistency across applications is important for good usability. People who want the same look cross plattform could still choose the same theme manually.

While not tragic, the menus look better when they are native as well.

So if possible, please reenable the Windows style that is provided by Qt/was provided previously with Spyder.

Version info:
* Spyder version: 5.3.3  (conda)
* Python version: 3.10.6 64-bit
* Qt version: 5.15.6
* PyQt5 version: 5.15.7
* Operating System: Windows 8.1

**Comment by ccordoba12** [comment]
Hey @maelh, thanks for reporting and for your thoughtful issue. You said:

> UI font has also become smaller (not a high DPI issue), but a theme issue.

That should be fixed in Spyder 6, to be released next year. In that version we'll allow users to set their font of choice for the entire application.

> So if possible, please reenable the Windows style that is provided by Qt/was provided previously with Spyder.

Sadly, that's not possible anymore for technical reasons and because we want Spyder to look the same regardless of the operating system (as you guessed). In addition, after a year and half of this change (included since Spyder 5.0, which was released in April 2021), you're the first person who has complained about it.

**Comment by ccordoba12** [comment]
> Especially, relevant GUI items like tabs are layouted differently now (bottom tabs like "help", "variable explorer", "plots", "files" are centered). It was nicer when it was left aligned, since you could unconsciously aim for the border, instead of having to look at the whole window to aim for the middle then readjust to the left or right.

I missed this: pane tabs will be styled differently in Spyder 6 for easier recognition but they still be centered by default.

**Comment by maelh** [comment]
Thanks for your reply.

Regarding UI themes, aren't they provided by Qt already, and as such, wouldn't it be possible to make it a conditional define such that the Windows theme is included when compliled for Windows? I may be the first person to mention it, but having the choice to make applications really integrate to the OS is a good thing, compared to web-based apps, since it wil follow all the other customizations you set system-wide.

Are there technical reasons not to enable the Windows theme again? I can see the Jupyter notebooks have the same theme, but the menus and the rest look sufficiently different already to not fully blend in, so I wouldn't see it as an issue.

**Comment by ccordoba12** [comment]
> Regarding UI themes, aren't they provided by Qt already

Sure, but we decided to provide our own theme to follow accessibility standards and have a more consistent look and feel, and because we were not happy with the Qt ones.

> but having the choice to make applications really integrate to the OS is a good thing

Right, but it's not always possible.

> Are there technical reasons not to enable the Windows theme again?

Yes, there are (I said it already). We have now a lot of CSS adjustments all over the place to make our theme follow the accessibility standards and have the consistency I mentioned above. And we couldn't make them work with the default Qt theme, that was the reason to drop it.

So, sorry to say it but there's no going back on our decision.

> I can see the Jupyter notebooks have the same theme, but the menus and the rest look sufficiently different already to not fully blend in, so I wouldn't see it as an issue.

I don't understand what you mean by this, unless you're referring to how Spyder-notebook looks in Spyder. If that's the case, I agree it doesn't feel completely integrated in Spyder, but we don't have time right now to improve that. However, you're welcome to help us with it.
