### ISSUE TITLE
pylintgui error

### ISSUE THREAD

**Issue by blancfrederic** [spyder-ide/spyder#20007]
### What steps will reproduce the problem?

Using miniconda I tryed to upgrade spyder to 5.3.3 version
>conda update
>conda install spyder=5.3.3

When opening Spyder 5.3.3 an error occurs

### Traceback
```python-traceback
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder_pylint/widgets/pylintgui.py", line 446, in show_data
    self.treewidget.set_results(filename, results)
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder_pylint/widgets/pylintgui.py", line 82, in set_results
    self.refresh()
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder_pylint/widgets/pylintgui.py", line 106, in refresh
    for module, lineno, message, msg_id in messages:
ValueError: too many values to unpack (expected 4)
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 17.7.0

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
psutil >=0.3      :  5.6.3 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.17.2 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @blancfrederic, thanks for reporting. You said:

> Using miniconda I tryed to upgrade spyder to 5.3.3 version

It seems your attempt was not successful because the error you're reporting is related to Spyder 3.3.6, which we don't support anymore. So, the easiest way to make Spyder work again is to uninstall Anaconda and reinstall its latest version. Please follow the instructions in [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to learn how to do that in the right way.
