### ISSUE TITLE
Spyder-kernels message not shown on Windows after restarting kernels

### ISSUE THREAD

**Issue by leavor** [spyder-ide/spyder#20023]
## Problem Description
I installed  Spyder 5.4.0 with Windows installer
I used conda install a python env, didn't install other python package
```
conda create -n paddle3.8.13 python=3.8.13
```
Then  changed to the interpreter of paddle3.8.13, restart kernel

![image](https://user-images.githubusercontent.com/1759365/201035861-fac4219b-5683-48c0-827c-da8c57426c07.png)

Next, change to the interpreter in a previous Python environment, which has installed spyder using conda, restart kernel,it is ok

### What steps reproduce the problem?

https://user-images.githubusercontent.com/1759365/201037425-2fd073ef-6725-4b02-8916-23e34c2603f2.mp4

## Versions
* Spyder version: 5.4.0  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10
### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.0.0 (OK)
cloudpickle >=0.5.0                  :  2.2.0 (OK)
cookiecutter >=1.6.0                 :  2.1.1 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree                         :  None (OK)
IPython >=7.31.1;<8.0.0              :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.17.0 (OK)
keyring >=17.0.0                     :  23.9.3 (OK)
nbconvert >=4.0                      :  7.2.3 (OK)
numpydoc >=0.6.0                     :  1.5.0 (OK)
paramiko >=2.4.0                     :  2.11.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.3 (OK)
pygments >=2.0                       :  2.13.0 (OK)
pylint >=2.5.0;<3.0                  :  2.15.5 (OK)
pylint_venv >=2.1.1                  :  2.3.0 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.6.0;<1.7.0                 :  1.6.0 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.2.2                    :  0.2.2 (OK)
qtawesome >=1.2.1                    :  1.2.1 (OK)
qtconsole >=5.4.0;<5.5.0             :  5.4.0 (OK)
qtpy >=2.1.0                         :  2.2.1 (OK)
rtree >=0.9.7                        :  1.0.1 (OK)
setuptools >=49.6.0                  :  65.5.1 (OK)
sphinx >=0.6.6                       :  5.3.0 (OK)
spyder_kernels >=2.4.0;<2.5.0        :  2.4.0 (OK)
textdistance >=4.2.0                 :  4.5.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog                             :  2.1.9 (OK)
zmq >=22.1.0                         :  24.0.1 (OK)

# Optional:
cython >=0.21                        :  0.29.32 (OK)
matplotlib >=3.0.0                   :  3.6.2 (OK)
numpy >=1.7                          :  1.22.4 (OK)
pandas >=1.1.1                       :  1.5.1 (OK)
scipy >=0.17.0                       :  1.9.3 (OK)
sympy >=0.7.3                        :  1.11.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)

```

**Comment by rhkarls** [comment]
Did you install `spyder-kernels` in the environment you are attempting to use, `paddle3.8.13`? For `Spyder 5.4.x` you need `spyder-kernels 2.4.x`, which is currently *not* available on Anaconda default channel - so you have to use `conda-forge`. I'm not sure how you have setup conda, but to use conda-forge channel:

    conda create -n paddle3.8.13 -c conda-forge python=3.8.13 spyder-kernels=2.4

or if you already installed python/packages in that env with conda-forge

    conda install -c conda-forge spyder-kernels 

It's best not to mix channels within a conda environment.

Also see https://docs.spyder-ide.org/current/faq.html#using-packages-installer

**Comment by ccordoba12** [comment]
> Did you install spyder-kernels in the environment you are attempting to use, paddle3.8.13?

That's correct @rhkarls, but in PR #19646 I tried to improve the situation by showing the "missing Spyder-kernels" error message when the selected one doesn't have that package.

I added a test for this but only for Linux (because it was easier), but perhaps it's not working for Windows. @dalthviz, could you check if that's not working on Windows, both for the installer and conda? For that, you need to go to `Preferences > Main Interpreter`, select one without Spyder-kernels, go to the IPython console and restart the kernel of the current one.

**Comment by dalthviz** [comment]
I was able to reproduce this (both with conda and with the standalone installer on Windows):

![image](https://user-images.githubusercontent.com/16781833/201412812-5802bf51-f3a6-4ca9-ae67-b0508d3af453.png)

![image](https://user-images.githubusercontent.com/16781833/201413419-0c56b42b-a5b9-4b1b-b505-a6904efdeee6.png)

I guess we should could merge #20024 with this one since the error is not related with the way of installation but the OS support to restart kernels on envs without `spyder-kernels` installed on Windows?

**Comment by ccordoba12** [comment]
Ok, thanks @dalthviz. Will look into it.
