### ISSUE TITLE
Plots no longer show up in new window when setting IPython Graphics backend to Automatic

### ISSUE THREAD

**Issue by austindowney** [spyder-ide/spyder#20051]
IPython graphics backend to "automatic" does not cause plots to pop up in their own windows like before. Plots show up only in the plots pane. Restarted Spyer between changes, restarted the computer, and updated Anaconda. 

* Spyder version: 5.1.5
* Python version: 3.9.15
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

**Comment by ccordoba12** [comment]
Hey @austindowney, thanks for reporting. This problem is fixed in our latest version available in Anaconda (5.3.3). Please update by closing Spyder, opening the Anaconda Prompt and running there the commands mentioned in [our documentation](http://docs.spyder-ide.org/current/installation.html#updating-with-anaconda).
