### ISSUE TITLE
Can't install "fancyimpute" in standalone spyder

### ISSUE THREAD

**Issue by Dongxy1** [spyder-ide/spyder#20099]
I tried in terminal:
conda create -n spyder -env -y
conda activate spyder -env
conda install spyder-kernels fancyimpute -y

But it complains:
PackagesNotFoundError: The following packages are not available from current channels:

  - fancyimpute

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page. 

How can I fix it?

* Spyder version: 5.4.0
* Python version: 3.9
* Qt version: 
* PyQt version: 
* Operating System name/version:

**Comment by ccordoba12** [comment]
Hey @Dongxy1, thanks for reporting. Unfortunately, the `fancyimpute` package is not available in Anaconda, so you need to install it with pip. So, instead of running

    conda install spyder-kernels fancyimpute -y

you need to run

    pip install spyder-kernels fancyimpute

Besides, please take into account that you can't mix pip and conda packages because they are binary incompatible. This is explained in the first part of [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs).
