### ISSUE TITLE
Check that paths are added in the expected order and to expected position in `sys.path` by the Pythonpath manager

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#20129]
As suggested by @dalthviz in https://github.com/spyder-ide/spyder/pull/19937#issuecomment-1331099384

> Also, as a last suggestion, could be nice to have a test that checks that the paths are being added in the correct position to `sys.path` in different circumstances (with a project open, with paths being enable and disabled, etc).

**Comment by jnsebgosselin** [comment]
If I understand correctly, paths from `system PYTHONPATH` are now added at the end of `sys.path` in the IPython Console sys.path?

So it is not possible anymore to override a package installed in your environment `site-packages` simply by adding a new path
to the system PYTHONPATH?

Also note that when running a script in an external console, the system PYTHON paths are still added at the top of the `sys.path`., which is a little bit confusing from a end user perspective. Took some time to understand what was going on there ahah.

I think that you have plans to add an option to allow both behaviours, is that correct? This would be nice because it was really useful to be able to very quickly test changes made to a package, while still keeping the 'official' version installed in the environment simply by checking/unchecking a box in Spyder.

BTW, the PYTHONPATH manager looks really nice, good job!

**Comment by ccordoba12** [comment]
@jnsebgosselin, sorry for the late reply. You said:

> If I understand correctly, paths from system PYTHONPATH are now added at the end of sys.path in the IPython Console sys.path?

Correct.

> So it is not possible anymore to override a package installed in your environment site-packages simply by adding a new path
to the system PYTHONPATH?

Not in Spyder 5.

> Also note that when running a script in an external console, the system PYTHON paths are still added at the top of the sys.path, which is a little bit confusing from a end user perspective. It took me some time to understand what was going on there ahah.

Good point. That's how Python handles PYTHONPATH, so there's nothing we can change about it.

> I think that you have plans to add an option to allow both behaviours, is that correct? This would be nice because it was really useful to be able to very quickly test changes made to a package, while still keeping the 'official pypi' version installed in the environment simply by checking/unchecking a box in Spyder.

Correct. We're working to implement that in Spyder 6 through a toggle button in our Pythonpath manager dialog.

> BTW, the PYTHONPATH manager looks really nice, good job!

Thanks! It'll have some minor additional improvements in Spyder 6 too.
