### ISSUE TITLE
How to update Python version within Spyder?

### ISSUE THREAD

**Issue by NilAtabey** [spyder-ide/spyder#20169]
I'm not trying to update Spyder version, but rather the Python version inside of Spyder.

I've tried conda update spyder and conda update conda

I'm on the latest version of Spyder however the python version within that is 3.8.10

**Comment by ccordoba12** [comment]
Hey @NilAtabey, thanks for reporting. It seems you're using our Windows installer, i.e. the program you can download either from our [webpage](https://www.spyder-ide.org/) or our [releases page](https://github.com/spyder-ide/spyder/releases).

If that's the case, then I'm sorry to say that it's not possible to update the Python version that comes with the installer due to the way it is built. Could you let us know why do you need that?

**Comment by NilAtabey** [comment]
I'm sorry, but me needing Python 3.9 is not something I care to discuss.

Thanks for the answer.

**Comment by dalthviz** [comment]
Just in case, maybe this entry in the Spyder docs FAQ page could be useful for you: https://docs.spyder-ide.org/current/faq.html#using-packages-installer

Basically, you could create a conda environment with the specific python version, along side with the `spyder-kernels` and any other package you want to use, and then set that environment interpreter as the custom interpreter for Spyder

**Comment by ccordoba12** [comment]
@NilAtabey, sorry if my question was not properly framed. The thing is we have very limited resources to work on Spyder, so I wanted to know if this is a critical issue for our users to decide if we need to invest time on it.

Anyhow, as @dalthviz said, you can connect an external Python 3.9 environment to our standalone version and work with it instead.
