### ISSUE TITLE
spyder

### ISSUE THREAD

**Issue by diaarozik** [spyder-ide/spyder#20165]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/diaa/.local/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):
  File "/home/diaa/.local/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.9
* Qt Versions: 5.9.5, PyQt5 5.10.1 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.12.0 (OK)
pandas >=0.13.1  :  1.1.5 (OK)
numpy >=1.7      :  1.19.5 (OK)
sphinx >=0.6.6   :  1.6.7 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.17.2 (OK)
psutil >=0.3     :  5.4.2 (OK)
nbconvert >=4.0  :  6.0.7 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  5.2.2 (OK)
IPython >=4.0    :  7.16.3 (OK)
pylint >=0.25    :  1.8.3 (OK)

```

**Comment by ccordoba12** [comment]
Hey @diaarozik, thanks for reporting. This problem is fixed in our latest version available in Anaconda (5.3.3). Please update by

* Closing Spyder.
* Installing a more recent Python version. That's because Spyder no longer supports Python 3.6. You can use `pyenv` for that.
* Installing Spyder again, but in a virtualenv. That's described in [our documentation](http://docs.spyder-ide.org/current/installation.html#using-pip).
* Remove `/home/diaa/.local/lib/python3.6/` because you don't need it anymore.
