### ISSUE TITLE
Improvements to the Linux installer

### ISSUE THREAD

**Issue by aknight2015** [spyder-ide/spyder#20176]
I installed using the bash file. Since I did that it's not showing as installed anywhere. So, how do I uninstall it?

**Comment by ccordoba12** [comment]
Hey @aknight2015, thanks for reporting. Are you talking about the Linux experimental installer?

**Comment by aknight2015** [comment]
Yes, the experiemental linux installer.

**Comment by ccordoba12** [comment]
Ok, did you install for your user or with `sudo`?

**Comment by aknight2015** [comment]
I used chmod a+x on the bash file, and executed as ./

**Comment by ccordoba12** [comment]
Ok, thanks. After the installer finishes, you should be able to start it using the facilities provided by Gnome shell to start applications. What desktop environment are you using?

Also, could you take a look at this one @mrclary? Perhaps the installer should have a message at the end saying how to run the app and how to uninstall/remove it.

**Comment by mrclary** [comment]
@aknight2015, I'm sorry you're having issues with the Linux installer.
You should find the following on your system if it was installed correctly:
- the file `/home/<user>/.local/share/applications/spyder_Spyder.desktop`
- the directory `/home/<user>/.local/Spyder-5.4.1.dev0`

On Ubuntu, you should be able to launch Spyder by searching in the Activities menu bar
![Screenshot from 2022-12-09 15-51-47](https://user-images.githubusercontent.com/9618975/206813858-396b3771-2808-40d0-966c-6a3edeee98ac.png)
or the Show Applications in the Dock
![Screenshot from 2022-12-09 15-52-42](https://user-images.githubusercontent.com/9618975/206813946-8c93648b-4c4c-430a-9699-a42e74bf9b13.png)

The permissions of the install script is a known issue. Another known issue is that the desktop file name should be `spyder.desktop`, not `spyder_Spyder.desktop`. If you change the name of the file, you should be able to pin Spyder in the Dock.
![Screenshot from 2022-12-09 15-55-08](https://user-images.githubusercontent.com/9618975/206813819-f6fbb0cc-4deb-48cf-88ef-97d9a3c71e74.png)

However, if this was not helpful to you, you should be able to uninstall Spyder by deleting the file and directory listed above. Thank you for reporting any issues that you find with our experimental installer; this will help us make necessary improvements and fixes.

**Comment by ccordoba12** [comment]
@mrclary, according to what you posted above, I have some suggestions for our Linux installer:

* Add a `spyder` script to PATH so that Spyder can be started using a terminal. I'm suggesting this for two reasons:
    1. That's pretty common for Linux apps.
    2. Not all desktop environments (e.g. Fluxbox) have an app launcher, so we need to provide a simple mechanism to launch Spyder.

* Add an `uninstall-spyder` script to PATH to easily uninstall Spyder from the terminal. That will help with the confusion reported by @aknight2015.
* Add a message at the end of the installation process describing these scripts and also how to start Spyder in Gnome/KDE.
* Use [this file](https://github.com/spyder-ide/spyder/blob/master/branding/logo/logomark/spyder-logomark-background.svg) (or its png equivalent) for the app icon, so that it looks good in dark taskbars (as in the screenshot you posted above).
