### ISSUE TITLE
Make Spyder Windows standalone installer extra validations pass with the silent installation flag

### ISSUE THREAD

**Issue by deviAshokkumar** [spyder-ide/spyder#20209]
Hi team,

I am trying to upgrade the spyder application latest version on top of previous version, i am getting below prompt.

![image](https://user-images.githubusercontent.com/108927212/208080445-5c3a133c-9fb7-4203-ad9c-6bbd4b2049b3.png)

But i would like to suppress this window silently (without any prompt) and upgrade it.

Currently using the parameters: /S /allusers.

Please help me to provide the command line to suppress and force upgrade it. i will be waiting for you response.

Regards,
Ashok

**Comment by ccordoba12** [comment]
Hey @deviAshokkumar, thanks for reporting. You need to run a silent command to uninstall Spyder first, then proceed with the silent command to install it again. I think there's no other way to do this because Spyder will refuse to be installed on top of a previous installation to avoid several problems we've seen in the past.

However, I'm going to ask @dalthviz about this because he's the maintainer of our Windows installer. @dalthviz, what do you think?

**Comment by dalthviz** [comment]
Checking I believe the problem is that the silent flag is not being passed to the extra dialogs/validations that we added, so even if you run with the silent option I guess the dialogs are showing up if you have Spyder already installed, right @deviAshokkumar ?

I will need to check but maybe we could detect the silent option and just run all the logic behind the dialogs as if the user accepted all the dialogs/warnings. What do you think @ccordoba12 ?

**Comment by ccordoba12** [comment]
Sounds good to me. Leaving this for 5.4.2 then because 5.4.1 is almost ready.

**Comment by deviAshokkumar** [comment]
Hi [dalthviz] and [ccordoba12],

Appreciate for your quick response. 

I saw that 5.4.1 version released recently and validated as before, i found the same issue as 5.4.0, Also as you mentioned you will be fixing this issue in 5.4.2 version.

Just wanted to remind you again to make this change in 5.4.2 version . so please include in the next latest version.

Regards,
Ashok

**Comment by dalthviz** [comment]
Hi again @deviAshokkumar after some time checking this locally seems like what it is needed to run the installer with the silent install flag is using the `start` command with the `wait` flag so something like:

```
start /wait Spyder_64bit_full.exe /S /allusers
```

Seems like this enables all the validation dialogs to not be shown and updates the previous installation. Could you give it a try and let us know if that helps?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
