### ISSUE TITLE
macOS download link on homepage broken (404)

### ISSUE THREAD

**Issue by core-code** [spyder-ide/spyder#20279]
the download link from the homepage ( https://www.spyder-ide.org/#section-download ) leads nowhere

https://github.com/spyder-ide/spyder/releases/latest/download/Spyder.dmg

does not exist

**Comment by dalthviz** [comment]
Hi @core-code thank you for the feedback! I think this is happened [since the workflow that generates the macOS standalone installer failed for the 5.4.1 release](https://github.com/spyder-ide/spyder/actions/runs/3803939385). For the moment we could put the Spyder 5.4.0 installer on the release while we build and upload the correct version to prevent the broken link.

**Comment by ccordoba12** [comment]
I think we can close this because it's not failing anymore (thanks @dalthviz for your help with that!). It'll be properly fixed when PR #20297 is merged because it'll upload the DMG for 5.4.1 to the release tag.
