### ISSUE TITLE
Switch to Editor hotkey broken (5.3.3)

### ISSUE THREAD

**Issue by theglob** [spyder-ide/spyder#20294]
reopening [https://github.com/spyder-ide/spyder/issues/19374](https://github.com/spyder-ide/spyder/issues/19374)

same issue, win 10

**Comment by ccordoba12** [comment]
Hey @theglob, thanks for reporting. As you can clearly see on issue #19374, this error was fixed in our 5.4.0 version (check the version tag on the right), released two months ago.

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer or macOS installers, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-env -c conda-forge spyder
        conda activate spyder-env
        spyder
