### ISSUE TITLE
Mac installer for 5.4.1 failed to build

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#20291]
There was an issue when code signing the app, as can be seen here:

https://github.com/spyder-ide/spyder/actions/runs/3803939385/jobs/6470903048

In addition, the conda installers failed to build as well:

https://github.com/spyder-ide/spyder/actions/runs/3803939387/jobs/6490799024

(I don't understand the reason why).

@mrclary, could you take a look at this asap? Thanks!

**Comment by ccordoba12** [comment]
I think we also need a way to check that the installers can be actually built for the release because it's very annoying to keep making semi-broken releases.

For that, I'd suggest that the installers are built as if they were going to be released (just not attached to a release tag) when the PR title starts with "Update core dependencies for". That's the last PR we always merge in a release, so we should test on it if everything is in order for it. If that's not the case, then we can safely abort the release until we make everything pass.

**Comment by mrclary** [comment]
The macOS installer failed because the bash command `pcregrep` was not found. While this command is not standard for macOS, it has been available in the past. Nevertheless, I've updated the affected workflows to ensure that the command is available.

The conda-based installer failed because I failed to understand a nuance of Githubs `jobs.<job_id>.if` directive: `success()` is automatically `and`ed unless another status check function is present. I've updated the workflow to correct for this.

**Comment by mrclary** [comment]
> I think we also need a way to check that the installers can be actually built for the release because it's very annoying to keep making semi-broken releases.

Agreed.

> For that, I'd suggest that the installers are built as if they were going to be released (just not attached to a release tag) when the PR title starts with "Update core dependencies for". That's the last PR we always merge in a release, so we should test on it if everything is in order for it. If that's not the case, then we can safely abort the release until we make everything pass.

I agree that some kind of "dress rehearsal" is a good idea. I'm not sure what is the best way to implement it. The principle issue is that the workflow logic differentiates between release events and pull request events. This means that a release event must occur (and version tag created) in order to test properly.

Perhaps we can set the release as pre-release; if workflows succeed then set the release as latest release.
<img width="419" alt="Screen Shot 2023-01-02 at 10 45 22 AM" src="https://user-images.githubusercontent.com/9618975/210269169-d4bc6aeb-9871-4760-aa8e-8b6bfc5dea60.png">
If workflows fail, delete the release (and version tag), submit PRs for fixes, and reattempt the release.

**Comment by ccordoba12** [comment]
> Perhaps we can set the release as pre-release; if workflows succeed then set the release as latest release.

That's a good idea but it'd add noise to our Releases page. What if we create a mirror of this repo where we push the release tag before doing it here, make Github actions build the release artifacts and check if everything is is order?
