### ISSUE TITLE
Execute until first breakpoint when pressing the Debug button

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2034]
_From [robert.p...@mykolab.com](https://code.google.com/u/113841535926527526275/) on 2014-10-30T08:30:46Z_

Often I have already set by breakpoints before starting the script.

Currently, the "Continue execution until next breakpoint" button does nothing when debugging has not been started. I suggest to rename the button to "Execute until next breakpoint" and to additionally make it start debugging if necessary.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2034_

**Comment by spyder-issues-migrator** [comment]
_From [robert.p...@mykolab.com](https://code.google.com/u/113841535926527526275/) on 2014-10-30T06:31:27Z_

'by breakpoints' -> 'my breakpoints'

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-30T16:44:05Z_

Fair enough :-) I'll try to fix it in our next release, if not in 2.3.3

**Status:** Accepted  
  **Labels:** MS-v2.3.2 Cat-Debugger

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-31T15:07:53Z_

**Labels:** -MS-v2.3.2 MS-v2.3.3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-08T15:18:08Z_

**Labels:** -MS-v2.3.3 MS-v2.3.4

**Comment by ccordoba12** [comment]
@jondo, the best I could come up with is making the **Debug** button to continue until the first breakpoint when pressed. It's really hard to associate this functionality to the **Continue** button because I don't know how to tell (from a programmatic point of view) if a console is in debugging mode or not.

Of course, this will work if the user has set at least one breakpoint in the current file. if not, **Debug** will start at the first executable line (as it works right now).

**Comment by ccordoba12** [comment]
I'll push my fix for this one tomorrow.

**Comment by jondo** [comment]
This is still an improvement, thank you.

**Comment by Stretch97** [comment]
Perhaps I am doing something wrong, but I just tried hitting the "debug" button in v2.3.4, and I still have to hit the "continue" button to actually start debugging, just like in v2.3.3.  In case it matters, I installed Spyder using pip with Enthought Canopy.
