### ISSUE TITLE
Response in the console is very slow

### ISSUE THREAD

**Issue by gustafp68** [spyder-ide/spyder#20362]
### What steps will reproduce the problem?

The issue is related to a very slow response when executing simple commands in the console. 
Executing 1+1 takes 5s to echo the result. Similar when printing text strings or variables.
Several people in our departement experience this, all of us having gotten new Lenovo Thinkpad P15 G2 computers. On our old P52 computers, Anaconda/Spyder (console) was quick.
We have tried updating windows and BIOS, but nothing has helped. 

Any suggestions of how we can get around this annoying problem?

**Comment by ccordoba12** [comment]
Hey @gustafp68, thanks for reporting. I'm afraid I'll have to ask you to reopen this issue with all the information we require from our users (i.e. Python, Spyder, Qt/PyQt, operating system versions and installation method).

If you prefer, you can do that directly from Spyder by going to the menu entry

    Help > Report issue

which will attach it the issue is opened here.
