### ISSUE TITLE
When using a custom interpreter spyder should complain about missing `spyder-kernels`

### ISSUE THREAD

**Issue by callegar** [spyder-ide/spyder#20478]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

When you run spyder using the custom interpreter functionality to work in a virtual environment, if the virtual environment misses pieces that are indispensable for spyder to run, spyder should complain and not fail silently.

### What steps will reproduce the problem?

1. Create a blank virtualenv
2. install `ipython` into it
3. Point spyder to use the python interpreter in that virtualenv as a custom interpreter
4. Restart spyder

### What is the expected output? What do you see instead?

Spyder should complain that it cannot find the needed `spyder-kernels` functionality in the environment.

Conversely, spyder starts but fails to show a prompt in the console window.

I think that in this case spyder should not fail silently to start its console. It should complain about the missing `spyder-kernels` piece.

In fact, when using custom interpreter, there is also an issue with  the help page indicating whether the spyder dependencies are satisfied or not. Apparently, this reports the dependencies that are available in the environment from which spyder is run, and say nothing about the dependencies in the environment from which the interpreter is taken. However, if there are pieces that need to be installed in the environment from which the interpreter is picked, it would be useful to have these listed as well.

## Versions

Python 3.10.9 64-bit | Qt 5.15.2 | PyQt5 5.15.8 | Linux 6.1.9-1-MANJARO

**Comment by dalthviz** [comment]
Hi @callegar thank you for the feedback! What happens if you try to open a new console or instead of restarting Spyder try to restart the kernel or after restarting try to open a new console? There is a message that should appear as you suggested:

![image](https://user-images.githubusercontent.com/16781833/218226461-6155ba16-73af-41de-8f35-60dab6b5922a.png)

So this is not showing in your case, right? Maybe is something related with the interpreter being created using virtualenv 🤔 

>  this reports the dependencies that are available in the environment from which spyder is run, and say nothing about the dependencies in the environment from which the interpreter is taken

So you say like adding a section in the dependencies dialog indicating for example the `spyder-kernels` installed or if it is not installed in the env of the custom interpreter selected, right?

Any new info to better understand what could be happening and the ideas you have is greatly appreciated!

**Comment by ccordoba12** [comment]
If the Spyder-kernels message @dalthviz showed above is not visible for you @callegar, but instead you're seeing an empty IPython console (that's not clear from your message, but I guess that's the case), then you're probably affected by issue #20358.

So, all web widgets in Spyder (like the one we use to show kernel issues) are failing to display content for some recent Linux distros and we were not aware of it. However, that will be fixed in our next version (5.4.3), to be released next month.
