### ISSUE TITLE
Proposition: turn runfile / runcell to IPython magics

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#20630]
The functions:
 - `runfile`
 - `runcell`
 - `debugfile`
 - `debugcell`
 
Are now added to the builtins. This is a bit strange because you wouldn't want to be able to call them from deep inside a library.
I suggest replacing them with magic instead. The calling convention would be a bit different,  but it would be cleat that these are no ordinary functions (e.g. you can't really pass any object as an argument, only strings, which is what magics are for)

**Comment by impact27** [comment]
Also this greatly simplifies the handling of the namespace and removes the differences between debugcell / debug selection with the debug magic

**Comment by ccordoba12** [comment]
Do you think we _really_ need this? It's a huge change on the way Spyder has been working since probably it was created (i.e. more than 10 years ago) and I'm sure it would impact all written and video material by teachers about running files in Spyder.

And the way you described it:

> Also this greatly simplifies the handling of the namespace and removes the differences between debugcell / debug selection with the debug magic

sounds like a code convenience that doesn't justify breaking everybody's workflows.

I understand that `runfile/debugfile` shouldn't be exposed as builtin functions. But it took us a long time to only support IPython (before we had a Python console too), so we couldn't use magics for them. And, at this point, I'd say this is not something we should be considering to do, unless there are _very_ strong reasons for it.

**Comment by impact27** [comment]
I mostly dislike the idea of someone adding a random `runcell()` in a library and ending up with code that would only run in spyder and not in python, without the issue being clear to the user. If `runcell` was a magic instead, this would not be possible, because Magics are only usable in the console or in `.ipy` files (well spyder accepts them in the main file but complains about it)

Regarding users workflow, I expect most people to press the buttons on the interface or use keyboard shortcuts, so they would only notice the console printing `%runfile "/path/to/file.py"` instead of `runfile("/path/to/file.py")`, which is not a huge change. What I personnaly do is to press up + enter to rerun a file in the console, but that would work as well with magics.

But I will concede that these are not very strong reasons.

**Comment by ccordoba12** [comment]
@pscobey, since you mentioned you're teaching Python with Spyder to newbies, I'd like to ask you about this proposed change (hope that's ok). So, instead of using a function to run files or cells (i.e. `runfile(...)` or `runcell(...)`), we'd like to use IPython magics instead (i.e. `%runfile`/`%runcell`) for Spyder 6.

As a professor, would you have problems with that change? I mean, perhaps you have some written material or videos explaining students what `runfile` is, which you'd have to modify. Or do you foresee any significant problems for students by using magics?

Thanks for your help!

**Comment by pscobey** [comment]
Hi Carlos,

If I have several short programs in a single
file and I'm looking at that file in Spyder, with
each program in a separate cell, it is very
convenient to be able to run a program/cell
with Ctrl + Enter, or a couple of programs one
after the other with Shift + Enter. That saves a
lot of time as compared to having each of the
programs in its own file, so I would hate to lose
those shortcuts and that facility ... 🙂

Hope that makes sense ...

Porter

Porter Scobey
Department of Mathematics and Computing Science
Saint Mary's University
923 Robie Street
Halifax, NS, Canada
B3H 3C3
Tel: 902-420-5790
Web: http://cs.smu.ca/~porter
________________________________

**Comment by impact27** [comment]
Hi @pscobey ,

Many thanks for your input! To clarify, all the keyboard shortcuts and buttons would stay the same. The modification is that when you press Ctrl + Enter, instead of seeing in the console:

`runcell(0, "script.py")`

You would see:

`%runcell -i 0 "script.py"`

The reason for the change is that we want to make clear that `runcell` is not a python function, but instead a special "magic" command spyder uses to run code. We are however concerned that this modification could be confusing for students.

For example, a tutorial video of spyder could explain that to run a cell, you need to press Ctrl + Enter. If the video was recorded with spyder 5, that would cause the `runcell(0, "script.py")` message to be printed to the console. If the student is using spyder 6 with this modification, he would instead see `%runcell -i 0 "script.py"`.

So the question is: is it worth it to make it clear that `runcell` is not a python function by slightly modifying the way it is printed to the console? The risk would be that this graphical change would of course not be present in existing spyder video tutorials.

Many thanks and have a good day

**Comment by pscobey** [comment]
That's great ... thanks for the clarification!

I'm just speaking for myself, of course, but
I suspect that what actually appears in the
Spyder console to run the code when the
keyboard shortcut is pressed is not even
"noticed" most of the time ... the students
(and I 🙂) are more interested in what the
code has produced than they are in the
command that has run the code (in the
Spyder context).

However, if they are running a file in an iPython
window outside Spyder, then of course they need
to know (or at least should be told) the difference,
so having "magic consistency" inside and outside
Spyder would be a good thing, and thus argue for
the change you are proposing.

I hope that makes sense ... 🙂

Thanks again,
Porter

Porter Scobey
Department of Mathematics and Computing Science
Saint Mary's University
923 Robie Street
Halifax, NS, Canada
B3H 3C3
Tel: 902-420-5790
Web: http://cs.smu.ca/~porter
________________________________
