### ISSUE TITLE
Updating variable explorer dataframes / matrices while they are open - enhancement

### ISSUE THREAD

**Issue by bajhuman** [spyder-ide/spyder#20694]
It would be great to see variables in an open window of the variable explorer update after code is executed. This is for two reasons, firstly each time you click on a variable (e.g. dataframe) a new window pops up even if an older one is already open, meaning that you don't know if you are looking at the latest values unless you close the old one first. Secondly, it is helpful during debugging or running cells to see variables change when lines of code are executed, particularly data frames.

* Spyder version: 5.15.7
* Python version: 3.10.8 64-bit
* Qt version: 5.15.2
* PyQt version: 5.15.7
* Operating System name/version: Windows 10

**Comment by ccordoba12** [comment]
Hey @bajhuman, thanks for reporting. Unfortunately, we can't make this work automatically because it'd consume a lot of memory. Every operation that shows a variable in one of our specialized viewers involves making a copy of it. That copy is cleared once users close the corresponding viewer.

But if viewers are maintained opened and they're being updated after every code execution, the memory consumed by Spyder can skyrocket quite quickly, especially for large variables.

So, I think the best we can do is to add a refresh button to our viewers, so users can do update them on demand.

**Comment by ccordoba12** [comment]
I'm going to close this issue as a duplicate of #6325.

**Comment by kenhall999** [comment]
Is there an open issue to track adding a refresh button to your viewers?

**Comment by ccordoba12** [comment]
Yes, it's issue #6325, as I mentioned above.
