### ISSUE TITLE
Command-line input not being read properly

### ISSUE THREAD

**Issue by pscobey** [spyder-ide/spyder#20696]
### What steps will reproduce the problem?

Command-line input is read from the input box with F5 but not with select and F9 or with Ctrl+Enter if code is in a Spyder cell.

**Comment by ccordoba12** [comment]
Hey @pscobey, thanks for reporting. I think command line options make sense only for files, not for cells or selections. That's because running cells or selections make sense only inside Spyder and not out of it.

@spyder-ide/core-developers, what do you think about this?

**Comment by dalthviz** [comment]
I tried thinking on an example where a selection or code cell could use the value there but I could not came with an example. Taking that into account I guess command-line arguments only make sense when running a full file as @ccordoba12 said.

Maybe an example of how a code selection or cell could use the command line input option could help us understand better what @pscobey wants to achieve? Could it be that the feature is something like a way to setup a context/namespace where selected code or code cells run?

**Comment by pscobey** [comment]
Hello Daniel,

Thanks to you and Carlos for the follow-up.

I think you're right ... Spyder can handle
command-line parameters with no problem
as long as there is just one program that uses
them in the current file.

So let me explain how I encountered the "problem".
I am teaching Python using a zyBooks online text,
and I typically put several program examples from
a given chapter section in a single file, each one
within a Spyder cell. This is very convenient and
time-saving when I'm instructing online, and had
worked very well till I had two separate programs
in two Spyder cells, both of which used command-
line parameters.

If I ran the "file" then both programs in both cells
ran and both used the same command-line parameters.
But ... if I tried to run a cell by itself, no luck.

Anyway, now I know what's going on, so I can deal
with it accordingly.

Thanks again for your help!

Spyder is a great tool for teaching Python online.

Best regards,

Porter Scobey
Department of Mathematics and Computing Science
Saint Mary's University
923 Robie Street
Halifax, NS, Canada
B3H 3C3
Tel: 902-420-5790
Web: http://cs.smu.ca/~porter
________________________________

**Comment by CAM-Gerlach** [comment]
Putting multiple "scripts" that each expect to receive command input all within file  will of course not actually work normally with a regular Python interpreter, and isn't really how things are _intended_ to work in Spyder, but it's perfectly possible to make it work. You have a few options; here a couple (from most to least recommended).

The better design is to ensure your code for each "program" is inside a function, which can take an optional parameter with a list of CLI args to parse (instead of just reading `sys.argv` by default), which is useful for more than just this particular unusual situation. For example, if you're using `argparse` with code like this:

```python
import argparse

def program_1():
    parser = argparse.ArgumentParser()
    parser.add_argument("test_arg_1")
    parser.add_argument("--test-arg-2")
    print(parser.parse_args())
```

Then, you can modify it to accept a parameter with the ``argv`` you want it to parse, as a list:

```python
import argparse

def program_1(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("test_arg_1")
    parser.add_argument("--test-arg-2")
    print(parser.parse_args(argv))
```

If ``argv`` is not passed when `program_1` is called (either in the file, or from the Console), it will still read from `sys.argv` as normal, but if a list of args is passed, then it will parse that instead:

```pycon
>>> program_1(argv=["test_val_1", "--test-arg-2", "test val 2"])
Namespace(test_arg_1='test_val_1', test_arg_2='test val 2')
```

You could also have it convert `argv` to an argv list if it is passed as a string:

```python
import argparse
import shlex

def program_1(argv=None):
    if isinstance(argv, str):
        argv = shlex.split(argv)
    parser = argparse.ArgumentParser()
    parser.add_argument("test_arg_1")
    parser.add_argument("--test-arg-2")
    print(parser.parse_args(argv))
```

so you could also do

```pycon
>>> program_1(argv="test_val_1 --test-arg-2 'test val 2'")
Namespace(test_arg_1='test_val_1', test_arg_2='test val 2')
```

This would not only allow you to handle this situation, but also allow you and your students to easily import, run and test your programs from the Python interpreter and other modules without having to re-run a whole new Python process or do other hacks.

But speaking of "other hacks"—there is one other option, that wouldn't require modifying any code even if your program is written directly at the `__main__` level. You can just manually set `sys.argv` with the arguments you want prior to running your code (though I don't recommend it as its more hacky, less flexible, wipes out what the actual `sys.argv` was, is lower level and is prone to mistakes). I.e.

```
import shlex
import sys

# As a list
args = ["test_val_1", "--test-arg-2", "test val 2"]
sys.argv = [""] + args

# As a string
args = "test_val_1 --test-arg-2 'test val 2'"
sys.argv = [""] + shlex. split(args)
```

**Comment by pscobey** [comment]
Thanks very much for all the suggestions, but I'm
teaching first-year students, so I think I'd just better
go back to first principles and run each program
separately ... 🙂

Porter

Porter Scobey
Department of Mathematics and Computing Science
Saint Mary's University
923 Robie Street
Halifax, NS, Canada
B3H 3C3
Tel: 902-420-5790
Web: http://cs.smu.ca/~porter
________________________________

**Comment by ccordoba12** [comment]
@pscobey, I'm glad you understand better now what's happening here and that you decided to change the way you're teaching Python with Spyder to sort it out.

Given that I think there's nothing else to discuss about it, I'm going to close this issue.
