### ISSUE TITLE
Input problems 

### ISSUE THREAD

**Issue by AbokiMone** [spyder-ide/spyder#20705]
### What steps will reproduce the problem?

```python
# Height=float(input("Enter your height in centimeters: "))
Height=172
# Weight=float(input("Enter your Weight in Kg: "))
Weight=85
Height = Height/100
BMI=Weight/(Height*Height)
print("your Body Mass Index is: ",BMI)
if(BMI>0):
	if(BMI<=16):
		print("you are severely underweight")
	elif(BMI<=18.5):
		print("you are underweight")
	elif(BMI<=25):
		print("you are Healthy")
	elif(BMI<=30):
		print("you are overweight")
	else: print("you are severely overweight")
else:("enter valid details")
```

#the line with comment give an error. The same code don't produce an error with pycharm.

**Comment by ccordoba12** [comment]
Hey @AbokiMone, thanks for reporting. This problem is fixed in our latest version available in Anaconda (5.3.3). Please update by closing Spyder, opening the Anaconda Prompt and running there the commands mentioned in [our documentation](http://docs.spyder-ide.org/current/installation.html#updating-with-anaconda).
