### ISSUE TITLE
Ubuntu: default spyder command cannot find qdarkstlye

### ISSUE THREAD

**Issue by d-v-t** [spyder-ide/spyder#20815]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
After installing spyder from the apt store in Ubuntu 22.04, spyder returns that qdarkstyle isn't found. The first obvious check is to run the same import command in python3 (python isn't installed on my machine)
```
from qdarkstyle.colorsystem import Blue, Gray
```
which returns fine. Since this is curious, I launched spyder directly from ~/.local/lib/python3.10/site-packages/spyder/app using
```
python3 start.py
```
Works just fine (as in loads the GUI, haven't tested further operations). Overwrote the alias in ~/.bashrc and works fine from command line after sourcing .bashrc. I still can't start Spyder from its icon however (since this still runs the faulty spyder command).
If you're wondering about other packages that might be interfering, I installed Ubuntu on a brand new machine only a couple of hours ago and the largest other python-related thing was FreeCAD (0.19 from apt). That is to say I doubt conflicting packages are to blame.

### What steps reproduce the problem?

1. Install spyder on a (relatively) clean Ubuntu 22.04 machine via apt
2. Run spyder in the command line

### What is the expected output? What do you see instead?
Spyder should open, it doesn't, throws
```
ModuleNotFoundError: No module named 'qdarkstyle.colorsystem'
```
despite qdarkstyle being installed. Running start.py directly opens GUI successfully.

## Versions

* Spyder version: 5.4.3
* Python version: 3.10
* Qt version: 5.15.3
* PyQt version: 5.15.6
* Operating System name/version: Ubuntu 22.04

**Comment by ccordoba12** [comment]
Hey @d-v-t, thanks for reporting. You said

> After installing spyder from the apt store in Ubuntu 22.04

and 

> Since this is curious, I launched spyder directly from ~/.local/lib/python3.10/site-packages/spyder/app

This means that you're mixing Python packages from your Linux with others you installed with pip as a user. That's a really bad practice because both sets of packages are compiled differently.

So, the best advice we can give you is to remove the Spyder you installed with apt and also this directory:

    ~/.local/lib/python3.10

Afterwards, please install Spyder in a virtualenv, as described in [our docs](http://docs.spyder-ide.org/current/installation.html#using-pip).

If you want to keep working with your current setup, it's up to you to figure this problem out. That's because this is not a use case we support since it's not robust and can easily lead to similar problems than this one or worst (e.g. odd segfaults).
