### ISSUE TITLE
spyder missing dependencies !nbconvert >=4.0: None (NOK)

### ISSUE THREAD

**Issue by dongdongxk** [spyder-ide/spyder#20977]
TypeError: object list can't be used in 'await' expression
TypeError: object list can't be used in 'await' expression
TypeError: object list can't be used in 'await' expression

**Comment by dalthviz** [comment]
Hi @dongdongxk without further information there is not much we can suggest besides suggesting you to be sure to have Spyder latest release (Spyder 5.4.3) installed.

From the error message posted in the OP this could be related/be a duplicate of some of these issues: https://github.com/spyder-ide/spyder/issues?q=is%3Aissue+TypeError%3A+object+list+can%27t+be+used+in+%27await%27+expression+is%3Aclosed

Let us know if you can share more info with us about your setup (OS, Python version, Spyder version, dependencies version) and steps to reproduce the bug (what were you doing before the issue was triggered) and if something of the above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
