### ISSUE TITLE
Code Folding shortcuts : Sponsor features

### ISSUE THREAD

**Issue by pprokevin** [spyder-ide/spyder#21009]
is it possible to create a shortcut to folder all code up to some level ?

Stackoverflow:
https://stackoverflow.com/questions/59943300/keyboard-shortcut-for-code-folding-in-spyder

2018 open issue:
https://github.com/spyder-ide/spyder/issues/6810
https://github.com/spyder-ide/spyder/issues/2430

Honestly, am willing to sponsor and pay for this features.
thanks.

Sponsor Features would be good, 
since it incentivies new developpers to do PR 
and users willing to support the project....( = saving time)

**Comment by ccordoba12** [comment]
Hey @pprokevin, thanks for reporting. You said:

> is it possible to create a shortcut to folder all code up to some level ?

Yes, it should be possible. Unfortunately, we haven't had time to implement that improvement due to lack of resources.

> Honestly, am willing to sponsor and pay for this features.
thanks.

That's very generous, thanks! Please contact me via email (my email is in [my profile](https://github.com/ccordoba12)) to talk about it.

> Sponsor Features would be good,
since it incentivies new developpers to do PR
and users willing to support the project....( = saving time)

Yeah, right now we're discussing what would be the best way for users to sponsor certain features in the project. Hopefully, we'll have something in place before the end of the year.

**Comment by ccordoba12** [comment]
Let me know if that answers all your questions/comments or if you need something else.

**Comment by ccordoba12** [comment]
> For Paid Features Benefits are :
Incentive new developers (ie student,...) to learn / contribute Spyder codebase.
Also, helps fixing issues as side effects as active developper grows/maintained.

Right, that's a good point.

> On the github issues, add ["Sponsored Feature"]
and potential add the sponsors total amount or else in the ticket.

Thanks for the suggestion. We're thinking to do something similar, but we don't plan to use Github for this because we don't think it's the right place for it.

> When the amount budget is reached (or before), developper can do PR
and retributed back when the PR is merged (ie not sure how Spyder can retribute back...)

There are different platforms for this, like Open Collective and Github Sponsors.

> Am pretty sure for Code Folding Shortcut, more than 10 person can sponsor 10 USD each....

I'm sorry but you're underestimating what's needed for this. USD $100 don't cover even a month of salary for a student in a third-world country. But more than that, for our relationship with students to be really fruitful, we prefer to work with them for three or four months. That way we can train them in how Spyder works, assign them certain tasks and oversee their progress so that we can help them if they are blocked.

I'm not saying that implementing this shortcut would require four months. But we could improve several other shortcomings related to folding in that time. That way, the student involvement with Spyder would be really helpful and we could possibly count on them in the future too. In short, we'd need USD $2500 to hire a student in South America to work part time on improving folding for four months.

I think giving small bounties for features, as you suggest, would be detrimental for us maintainers because we'd probably receive many PRs for the same thing, which we'd need to evaluate and then maintain the contributed code afterwards.

> If you/your team are ok, we can start with this issue (ie Code Folding shortcut),
refining the behavior specs.

Sorry, I'm not ok with your suggestion, so we're not going to proceed with it.

**Comment by ccordoba12** [comment]
Since this issue was already reported (as you found out), I'm going to close it because I don't think there's much else to discuss about it.

**Comment by ccordoba12** [comment]
> For PR process, I suggest a more stricter process

I understand your point. But what we don't want to do (because it wouldn't work well for us) is to open up the possibility for any developer to contribute to Spyder and get rewarded for it. Instead, we want to hire and train junior developers that can stay with us for extended periods of time (three to six months, or even more). That would be a more productive way to invest their time for the core developer team.

> My view if the user base is big enough, a big amount of small paid contribution
on selected features can be positive impact

Yeah, that's our idea too. We're working with another organization to create a kind of Kickstarter website where people can sponsor the features they'd like to see in Spyder, instead of giving a general donation to it. Once the minimal amount we require for a specific feature is reached, we'd start to work on it.
