### ISSUE TITLE
Minor bug with empty files: `QTextCursor::setPosition: Position '-1' out of range`

### ISSUE THREAD

**Issue by mvillion** [spyder-ide/spyder#21028]
If an empty file is opened with Spyder when spyder is launched, a message is printed:

QTextCursor::setPosition: Position '-1' out of range

This message can be suppressed by changing one line in plugins/editor/widgets/codeeditor.py:
(around line 4973)
        # Text might be after a dot '.'
        if text == '':
            #was: cursor.setPosition(pos - 1, QTextCursor.MoveAnchor)
            cursor.setPosition(**max(0, pos - 1)**, QTextCursor.MoveAnchor)

Hope that helps.
Thank you

**Comment by dalthviz** [comment]
Hi @mvillion thank you for the feedback and giving a possible solution to the issue! I think I have been seeing that message around too but didn't know from where that was coming from :)

Would you like to submit a PR with your proposed fix? If that is the case I think this should go to the 5.x branch and you can check the contribution guide for more info about how to do the PR at: https://github.com/spyder-ide/spyder/blob/5.x/CONTRIBUTING.md (if you have any question feel free to ask here)

Otherwise we can try to do the PR with your proposed fix :+1:

Let us know!

**Comment by mvillion** [comment]
Hello,

I am not very familiar with writing PR on github. As this is a very small change, I am hoping that maybe you can fix it while solving another bug?

**Comment by dalthviz** [comment]
No problem! I will then submit a PR with your proposed fix and put you as a co-author there :+1:
