### ISSUE TITLE
Improve highlighting of current plot

### ISSUE THREAD

**Issue by meshgeneration** [spyder-ide/spyder#21046]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

Not so much a bug, but more of a request for improvement. When browsing through a large number of plots, it is barely possible to tell which plot we are currently viewing. Instead of a very thin light blue frame, I would recommend a thicker red line for emphasis. Thanks a lot!

**Comment by ccordoba12** [comment]
Hey @meshgeneration, thanks for the suggestion. We'll try to take address it in Spyder 6, to be released before the end of the year.

**Comment by jitseniesen** [comment]
I agree that it is not clear currently which plot is active, especially in dark mode:

![plots-orig-dark](https://github.com/spyder-ide/spyder/assets/7941918/d7a86e3f-855f-455a-8282-9c22956ea864)

It looks a lot better in light mode:

![plots-orig-light](https://github.com/spyder-ide/spyder/assets/7941918/93fec5e3-c225-4074-b2a4-ad13680bed21)

As suggested, I tried to change it to red, specifically `SpyderPalette.ICON_4`. Of course red normally is used to indicate an error, which is not the meaning here, so that is not ideal. However, it does make it clearer which plot is active:

![plots-red-dark](https://github.com/spyder-ide/spyder/assets/7941918/cdfbc9fe-9700-445c-ae62-5b1e58a43bab)

For comparison, here is the light mode with red:

![plots-red-light](https://github.com/spyder-ide/spyder/assets/7941918/7d593feb-4783-439e-8331-25e7937e4fbb)

I think the difficulty here is that if you use Spyder in dark mode and plots with a white background (the default in Matplotlib), then the border is between a dark colour and a light colour so it is hard to put something contrasting in with just two pixels. It naturally works better if Spyder is in light mode. Perhaps we need another mechanism to indicate the active plot, like a border on the outside around the plot instead of on the inside, or something completely different like putting an icon on top of the thumbnail of the active plot (but that would partially occlude the thumnail). I'm not sure how easy these are to implement.

@spyder-ide/core-developers @conradolandia Any preferences or ideas on how to proceed? See #10255 for some earlier discussion on the same topic. At the moment, I'm thinking to use red as a quick fix for Spyder 6 and (hopefully) discuss in more detail after Spyder 6.

**Comment by conradolandia** [comment]
I think we have two options: 

1. Use a darker orange-yellow color, with a 1px line. I could check what we have available on the pallete, or if needed, add another color. Using this color would be less aggresive than using red, and keeping the line thin would meake it less intrusive. 
3. Use a middle gray with a 3px line. This would contrast well enough in both colors, and a thicker line will make it more noticable. 

Any of these would probably solve the issue. Using a thin line with gray would not work because it will make it almost invisible, the same issue we have now. And using a thick line with a brighter color would be too much.

**Comment by ccordoba12** [comment]
> Use a middle gray with a 3px line. This would contrast well enough in both colors, and a thicker line will make it more noticable.

I really like this option and would match very well with the rest of our theme.

**Comment by jitseniesen** [comment]
Following the suggestions, here are some more options.

A thin orange line; specifically, `COLOR_WARN_2` at 1px:

![plots-warn-dark](https://github.com/spyder-ide/spyder/assets/7941918/58f9a213-5b17-4260-a80d-b6771b08e36b)

A thick gray line; specifically, `COLOR_BACKGROUND_4` at 3px:

![plots-gray-dark](https://github.com/spyder-ide/spyder/assets/7941918/b7e5a5d8-9669-49f9-8118-7de5732e4387)

The same thick gray line, but now on the outside:

![plots-gray-dark-outside](https://github.com/spyder-ide/spyder/assets/7941918/f03776d2-31ed-4373-9023-5f1f380e21ea)

An even thicker gray line (5px) on the outside:

![plots-gray-dark5-outside](https://github.com/spyder-ide/spyder/assets/7941918/658b3149-9a3b-4322-a28e-04236b1a5114)

For me, the last option is the only one which is clear but it takes up more space on the screen.

Here are the corresponding screenshots for the light theme:

![plots-warn-light](https://github.com/spyder-ide/spyder/assets/7941918/2a83b3e5-31ef-4cd2-9d81-93640ca7ddb0)

![plots-gray-light](https://github.com/spyder-ide/spyder/assets/7941918/1443586d-4722-4d31-b9b4-f32c980c5210)

![plots-gray-light-outside](https://github.com/spyder-ide/spyder/assets/7941918/7bbfefa8-7338-4b6c-a6a4-141355235d1f)

![plots-gray-light5-outside](https://github.com/spyder-ide/spyder/assets/7941918/ad1ac2ba-6193-47a9-915c-9946bcfd1c6b)

What do you think?

**Comment by conradolandia** [comment]
I suggest (using color names from QDarkStyleSheet): B90 for the dark theme, and B50 for the light theme. A 3px line should be more than enough.

![image](https://github.com/spyder-ide/spyder/assets/5027583/a8803520-e8ca-458f-9167-115eee658e8e)

**Comment by conradolandia** [comment]
Forgot to mention that these are from the Gray class from colorsystem.py
