### ISSUE TITLE
issue _pickle 

### ISSUE THREAD

**Issue by HalimaLotfe** [spyder-ide/spyder#21103]
`
this is the code :import cv2
import numpy as np
import pickle
import os
from skimage import transform
import matplotlib.pyplot as plt
import csv
from PIL import Image
import gr

class struc: #class= truc qui contient différents trucs et qui a des fonctions
  def __init__(self,img,frameID,ID,x1,y1,x2,y2):
      #self=variable de l'instance ????
    self.img = img
    self.frameID = frameID
    self.ID = ID
    self.bbxyxy = (x1,y1,x2,y2)

# Chemin vers le fichier pickle
pickle_path = 'C:\\Users\\ap000\\OneDrive\\Basler_acA2500-60um__40351785__20230621_121455564_tracks_classif.pkl'
# Charger les données à partir du fichier pickle
with open(pickle_path, "rb") as pickle_file:
    data = pickle.load(pickle_file)

cellIDs = list(data.keys())
cellIDs.sort()
and the error:
  File c:\users\ap000\.spyder-py3\untitled21.py:22
    data = pickle.load(pickle_file)

AttributeError: Can't get attribute 'GR' on <module 'gr' from 'C:\\Users\\ap000\\anaconda3\\envs\\stageinterface2\\lib\\site-packages\\gr\\__init__.py'>

**Comment by ccordoba12** [comment]
Hey @HalimaLotfe, thanks for reporting. It seems you saved your pickle file with a different version of the `gr` library than the one you're using to open it. That's probably why you're getting this error.

Since this is not a problem with Spyder, I recommend you to open an issue about in:

https://github.com/sciapp/python-gr

and ask for help there.
