### ISSUE TITLE
Spyder Outline doesn't open

### ISSUE THREAD

**Issue by mqystella** [spyder-ide/spyder#21195]
My spyder is 5.2.2 and my python is 3.9.13
All of a sudden, my outline is gone. I have tried restart spyder/computer,or upgrade it,but it didnt work.
I tried untick and then tick the outline button from panes, but there is still no sign of outline section, while project session works fine.

**Comment by mqystella** [comment]
I have encountered the problem of outline doesnt work, aka ouline only shows the file name but nothing like functions, classes. This time the entire outline pane is gone, disappeared. It doesnt either show on the left hand side as it used to be, nor on the right hand side with files, plots, tab.

**Comment by dalthviz** [comment]
Hi @mqystella thank you for the feedback! How did you install Spyder or tried to update it? Could it be possible for you to install a clean version of the latest release (5.4.4)? 

Also, in case you are using Spyder through the Anaconda distribution, maybe this is related with https://github.com/spyder-ide/spyder/issues/19233 ? Maybe creating a new conda environment using the conda-forge channel could help if you are using conda.

Any other info in order to understands what could be happening and do more suggestions is appreciated. Let us know!

**Comment by mqystella** [comment]
thank you for your reply. Does it mean 5.4.4 is a clean version and thus i should downgrade it to a lower version(which version would you recommend, including outline function)? My spyder says it is 5.2.2, so i suppose the original upgrade failed?

**Comment by dalthviz** [comment]
Checking again the error you are getting seems like it was fixed in Spyder 5.4.0. Depending on how did you install Spyder the update procedure could need different steps or limit the version you can have installed. Could it be possible for you to share more details about your setup (OS, if you are using pip or conda, etc)? Maybe a look to the installation guide from the Spyder docs could help too: https://docs.spyder-ide.org/current/installation.html#installation-guide

**Comment by mqystella** [comment]
I have tried uninstall anaconda, then install spyder, failed. Then I tried uninstall spyder, install the latest anaconda version, failed again. Finally, I reset spyder to default setting, and then it worked! No idea why but gladly problem solved.
