### ISSUE TITLE
Spyder doesn't render well on HighDpi screens

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2119]
_From [mjdep...@gmail.com](https://code.google.com/u/112397940646561315916/) on 2015-01-15T10:51:45Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1. Using a 4K screen with 3840 x 2160 2. 3. 

What is the expected output? What do you see instead?

 expect size of windows and consoles to look normal. The biggest issue is in the variable explorer the headers are cut off height-wise. The preference window comes up really small. What version of the product are you using? On what operating system? spyder 2.3.2 py3.4 windows 8.1 

Please provide any additional information below

. I am stuck in a class and super bored right now. In reality these issues are incredibly minor. But would be cool if they were fixed. Thanks!

**Attachment:** [spyder screen shot.PNG](http://code.google.com/p/spyderlib/issues/detail?id=2119)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2119_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-08T11:00:23Z_

I don't have access to such a high screen resolution, sorry :-(

**Summary:** 4K screen resolution issues  \<span class="oldvalue"> (was: 4K screen resolution issue) \</span>  
  **Labels:** Cat-SpyderGUI MS-v2.4

**Comment by patstew** [comment]
Fingers crossed this sort of thing will get better in Qt 5.6, but in the meantime with Qt 5.4+ it looks much better if you add the following to any qt.conf files in your python directory:

[Platforms]
WindowsArguments = dpiawareness=0

**Comment by ccordoba12** [comment]
What does that do?

**Comment by patstew** [comment]
It tells windows that the application is not DPI aware, which makes windows render it at 'normal' resolution then scale the output image. This makes it look less sharp, but everything is the right size.
By default Qt reports that it is DPI aware, and tries to scale the UI, but still renders anything sized in terms of pixels 1:1, which tends to mean that some ui components are miniscule and others are stretched out of shape.
This is supposedly fixed properly in 5.6 https://doc-snapshots.qt.io/qt5-5.6/highdpi.html

**Comment by SylvainCorlay** [comment]
@patstew if you run from master (and use the Spyder 3 icon theme), you will get the hight-dpi bitmaps for the icons.

**Comment by Nodd** [comment]
@patstew So is it better with Qt5.6 ?

**Comment by patstew** [comment]
No, and setting dpiawareness seems to have stopped working too.

**Comment by patstew** [comment]
Actually I spoke too soon, it's just disabled. You can enable it by setting the QT_AUTO_SCREEN_SCALE_FACTOR environment variable, or I've submitted a change to fix it properly in #3333. It seems pretty good with that change, overall it's 1000x better than before. The fonts are sharp on both screens, and everything is basically the right size. A few things seem to be slightly wrong, like half the e of 'Console' in help source is cut off, and the folder selector is slightly too short for its font, so the anything below the line, like the tail of y or p is cut off. The radio buttons in Preferences are slightly too big when I move it to my second, normal DPI screen. These are just slightly ugly though, I haven't noticed anything as bad as it was yet.

**Comment by goanpeca** [comment]
Could you paste some screenshots. We need them for UI related issues.

**Comment by patstew** [comment]
![spyder preferences highdpi](https://cloud.githubusercontent.com/assets/4478567/17252185/81d7b54c-55a3-11e6-8c83-edcd8c39330d.png)
![spyder preferences moved to normaldpi screen](https://cloud.githubusercontent.com/assets/4478567/17252183/81d30984-55a3-11e6-9bc4-625b9639d610.png)
![spyder](https://cloud.githubusercontent.com/assets/4478567/17252184/81d55f7c-55a3-11e6-8244-c941cd0d0741.png)
Here you go. I think most of the rendering issues are visible here. "spyder preferences moved to normaldpi screen.png" shows what happens when I move the preferences dialog to my other 1080p screen from my 4k laptop screen. In the image it looks like everything is too small, but actually the fonts in both pictures are the same size. The fact that there's loads of empty space is because Qt keeps windows with the same pixel size when moving to another screen, i.e. a Qt bug. Not really important though. The title bar is bigger than everything else due to a windows bug http://stackoverflow.com/questions/36864894/scaling-the-non-client-area-title-bar-menu-bar-for-per-monitor-high-dpi-suppo. The only thing that's spyder's problem I think is that the radio buttons are bigger than their containing widget.
