### ISSUE TITLE
issue with spider kernel

### ISSUE THREAD

**Issue by snehasavarapu** [spyder-ide/spyder#21208]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

there is a problem

**Comment by dalthviz** [comment]
Hi @snehasavarapu , could you provide more info about your setup (Python version, Spyder version, steps to replicate the issue, any tracaback you are seeing, etc)? Seems like you could be running an outdated version of Spyder since the error report doesn't come with any default info so I would sugget to try updating Spyder (the latest release is version 5.4.4).

Any order info in order to better understand what could be happening is greatly appreciated. Let is know!

Note: Also, seems like you created a couple of issues with empty info so I will close those and point them here

**Comment by dalthviz** [comment]
Closing due to lack of response
