### ISSUE TITLE
scope in console

### ISSUE THREAD

**Issue by olcaykursun** [spyder-ide/spyder#21344]
### What steps will reproduce the problem?

#Run the whole program once expecting and getting "2 2" as output
#Don't run it cell by cell, just run it once (hit F5)
#Then go to console and type n=3

#Now that we changed n to 3, calling foo should output "3 3", but we get "3 2"

#Approach 1: Stay in console and type foo(n)  
#Approach 2: Run the second code cell

n = 2

def foo(x):
    print(x, n)

#%%
foo(n)

**Comment by jitseniesen** [comment]
I don't completely understand how namespaces, scopes and closures work, but I think this is expected behaviour.

When you run a program with F5, it is not run in the console's namespace (I may well be wrong, but I believe "namespace" is a better term to use here than "scope"). Instead, the program is run in an empty namespace and at the end, the console's namespace is updated with the program's namespace. In your example, the program defines the function `foo` and the variable `n`, so after running the program the console's namespace will also have `foo` and `n`. However, the variable `n` in the program's namespace is not the same as the variable `n` in the console's namespace. The `n` in the function `foo` refers to the `n` in the program's namespace, not the `n` in the console's namespace. So changing the `n` in the console's namespace does not change the `n` in the function `foo`.

This behaviour is not specific to Spyder. If you run a program in IPython with `%run`, you will see the same, as described in the [IPython docs for %run](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-run). I expect the same happens in Jupyter, though I did not try it. The reason for this is that it can be confusing if variables defined in the console influence programs you run.

It is possible to run the program in the console's namespace, if you really want that. One way is to select the whole program and then click on `Run > Run selection or current line` (key `F9`). A more permanent way is to go to `Run > Configuration per file` and select the option `Run in console's namespace instead of empty one`. However, keep in mind that IPython and we chose the current behaviour (of using an empty namespace) because of the errors and confusion that we noticed with the old behaviour (of using the console's namespace).

Feel free to ask if you have more questions.

**Comment by olcaykursun** [comment]
I like your explanation that console and program's name spaces are different, but having a console is great for debugging and I'd like to change things and run code cells etc. I guess I need to change that habit then.

I tried it in Jupyter Lab, they dont have "run", they have "run all cells", maybe that's why? So, I couldn't reproduce the issue there. 

In Spyder, if I run every code cell one-by-one the problem does not occur. Only if I run the whole program once, then the issue comes up. For example, in my original post "Approach 2" states that after running the program we change n to 3 in the console, then we run the code cell that contains nothing but "foo(n)" to obtain "3 2" output. So, clearly, the code is able to see n's new value there. 

Either way, coming from Matlab background, I like Spyder, keep up the good work.

**Comment by jitseniesen** [comment]
> In Spyder, if I run every code cell one-by-one the problem does not occur. Only if I run the whole program once, then the issue comes up. 

You are right. There is a difference in Spyder between running the whole program on the one hand and running separate cells, lines or running selected code on the other hand. When you run the whole program, it is run in an empty name space, and you have the problem that you described. When you run by cell or by line, it is as if you type the code in the console and your problem does not occur. This is perhaps a bit inconsistent, but it is meant to reflect how the functionality is typically used. 

> Either way, coming from Matlab background, I like Spyder, keep up the good work.

Thanks, much appreciated. I also come from a Matlab background and the Matlab behaviour where programs can use variables from previous runs caused me enough problems that I got into the habit of starting every program with CLEAR ALL to make sure that it starts with a clear slate. So I was very happy that Spyder does something like this automatically. But I get that it does depend on what you are used to.

**Comment by quctex** [comment]
We can achieve desired `3 3` output in four ways. Instead of using `Run` function, we can:
1. Select all text in file (`Ctrl+A`) and `Run selection or current line` (`F9`), OR
2. Place cursor into the last line (`Ctrl+End`) and `Run to current line` (`Shift+F9`) OR
3. Place cursor into the first line (`Ctrl+Home`) and `Run from current line` (`Ctrl+F9`) OR
4. Leave cursor anywhere where it is, and activate consecutive `Run to current line` and `Run from current line`  (`Shift+F9`, `Ctrl+F9`).

So, if there are already workarounds exists, It might not be a bad idea to add a direct function for this — `Run all lines`. What are you thinking about it?

**Comment by olcaykursun** [comment]
Thanks quctex,

I don't think there are any needs for new functionalities, either. There is a more fundamental problem here. I just don't get how a "3 2" is possible under any explanation. 

But if I change a variable to 3 in console and that same 3 appears somewhere but not elsewhere and gives me a weird "3 2" behavior that shows me some inconsistency. I would be okay with "2 2" or "3 3", but "3 2" is not understandable. 

As Jitse also explained, if I don't make changes to variables in console then I have no trouble anyway.
