### ISSUE TITLE
codeium plugin

### ISSUE THREAD

**Issue by KnSun99** [spyder-ide/spyder#21356]
## Problem Description

Hello, will the new version of spyder support codeium plugin?

**Comment by ccordoba12** [comment]
Hey @KnSun99, thanks for reporting. Unfortunately, we don't have a plugin for that service and it doesn't seem easy to build because I couldn't find documentation on how to do it.

So, for now I'm going to close this issue in favor of #20632 because it has a longer discussion about possible AI code completion clients.

**Comment by KnSun99** [comment]
Thank you for your reply!

Spyder is an editor I use frequently, and I'm looking forward to new features.
