### ISSUE TITLE
Support for displaying dynamically generated functions in Outline Panel

### ISSUE THREAD

**Issue by OyiboRivers** [spyder-ide/spyder#21438]
### Issue Report Checklist

* [X ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports

## Feature Request: Support for displaying dynamically generated functions in Outline Panel

Description:

The Spyder IDE's outline panel currently lacks support for displaying dynamically generated functions within Python scripts. While functions generated through decorators are correctly shown, dynamically generated functions, are not displayed in the outline panel. This limitation hinders code navigation and readability, particularly in scenarios where such functions play a crucial role in the codebase.

Outline panel for example below:
my_module.py
└── sum_py

Example:

```
import numpy as np
import numba as nb
prange = nb.prange

def sum_py(arr):
    """Calculate the sum of all elements."""
    total_sum = 0
    for i in prange(arr.shape[0]):
        for j in prange(arr.shape[1]):
            total_sum += arr[i, j]
    return total_sum

sum_v1 = nb.njit(sum_py)
sum_v2 = nb.njit(parallel=True)(sum_py)
sum_v3 = nb.njit(parallel=True, boundscheck=False)(sum_py)
```

Request:

I would like to request an enhancement to the Spyder IDE's outline panel to include support for dynamically generated functions if it is technically possible. This feature would greatly benefit developers who use dynamically generated functions for various purposes, enabling them to navigate and understand the code more effectively.

Outline panel as requested:
my_module.py
├── sum_py
├── sum_v1
├── sum_v2
└── sum_v3

Thank you, Team Spyder

## Versions

* Spyder version: 5.4.3  (conda)
* Python version: 3.10.13 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Linux 5.15.0-87-generic

**Comment by ccordoba12** [comment]
Hey @OyiboRivers, thanks for reporting. Spyder can actually show those functions, but it doesn't do it by default because they are interpreted as variables.

To do it, you need to go to options menu of the Outline pane and enable the option called `Display variables and attributes`:

![image](https://github.com/spyder-ide/spyder/assets/365293/a0d551da-e79a-488d-9234-5c29f0876f17)

For this screenshot I used the code you posted above and you can see that the Outline is displaying `sum_v1`, `sum_v2` and `sum_v3`.

This is the best Spyder can do to support your use case because the Outline pane doesn't run files to get the symbols declared in them. That's not possible in general because there could be unexpected side effects when running files (e.g. it can take too much time or consume too much memory).

**Comment by OyiboRivers** [comment]
Amazing! 
Thank you very much @ccordoba12

**Comment by ccordoba12** [comment]
Glad you found this solution useful!
