### ISSUE TITLE
Variable Explorer fails to display Pandas DataFrame with Int64Index

### ISSUE THREAD

**Issue by cirnod** [spyder-ide/spyder#21475]
## Problem Description
When trying to open a DataFrame variable from the "Variable Explorer" that contains a `Int64Index` as index an error occurs and no data is displayed. The same works fine if the DataFrame contains a `RangeIndex` instead of a `Int64Index`. 

### What steps reproduce the problem?

1. Create DataFrame with `Int64Index` and store it in a variable
  For example:
  ```
import pandas as pd
df = pd.DataFrame()
df['a'] = [1, 2, 3]
df.index = pd.Int64Index(df.index)
  ```
2. Double click the `df` variable in "Variable Explorer"

### What is the expected output? What do you see instead?
Expected output: DataFrame is displayed as table in a new window. 
Actual output: "Spyder was unable to retrieve the value of this variable form the console. [...] An unknown error occurred. [...]"

I am aware that the pandas Int64Index is depricated (see [here](https://pandas.pydata.org/pandas-docs/version/1.5/reference/api/pandas.Int64Index.html)) and I am using pandas 1.5.3. However, since the Python packets are still available and the code runs without errors, it would be nice if Spyder would not fail to display the variable or would at least provide a meaningful error message instead of the generic message "unknown error". 

## Versions
* Spyder version: 5.4.5  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.19045-SP0

**Comment by ccordoba12** [comment]
Hey @cirnod, thanks for reporting. This problem happens because our Windows installer comes with Pandas 2 and you're using Pandas 1.5 in your external environment. The main thing here is that those versions are incompatible with respect to serialization, which is what allows us to display objects in the Variable Explorer.

Unfortunately, there's no workaround for this if you want to use our latest version. What you can do to keep using that old Pandas version is to uninstall Spyder and install an older version (i.e. 5.4.4, 5.4.3, etc) that comes with Pandas 1.5.

**Comment by ccordoba12** [comment]
> it would be nice if Spyder would not fail to display the variable or would at least provide a meaningful error message instead of the generic message "unknown error".

I understand. This was reported before on issue #21160, so I'm going to close this one in favor of that.
