### ISSUE TITLE
iuhohiuhiuhuioohuiihou

### ISSUE THREAD

**Issue by qwertyuiopasdfghjklzxcvbnmuiorhhui** [spyder-ide/spyder#21484]
### What steps will reproduce the problem?

hoiuhuiuhihiuoihuouihuihuhiouhihiouiuhouhiouhioiuhiu

### Traceback
```python-traceback
  File "/opt/anaconda3/envs/myenv/lib/python3.6/site-packages/spyder_pylint/widgets/pylintgui.py", line 446, in show_data
    self.treewidget.set_results(filename, results)
  File "/opt/anaconda3/envs/myenv/lib/python3.6/site-packages/spyder_pylint/widgets/pylintgui.py", line 83, in set_results
    self.refresh()
  File "/opt/anaconda3/envs/myenv/lib/python3.6/site-packages/spyder_pylint/widgets/pylintgui.py", line 107, in refresh
    for module, lineno, message, msg_id in messages:
ValueError: too many values to unpack (expected 4)
```

## Versions

* Spyder version: 3.3.3 
* Python version: 3.6.13
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 20.4.0

### Dependencies

```
pyflakes >=0.6.0  :  2.4.0 (OK)
pycodestyle >=2.3 :  2.8.0 (OK)
pygments >=2.0    :  2.11.2 (OK)
sphinx >=0.6.6    :  4.4.0 (OK)
rope >=0.9.4      :  0.22.0 (OK)
jedi >=0.9.0      :  0.17.0 (OK)
psutil >=0.3      :  5.8.0 (OK)
nbconvert >=4.0   :  6.0.7 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  1.16.6 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  5.2.2 (OK)
IPython >=4.0     :  7.16.1 (OK)
matplotlib >=2.0.0:  3.3.4 (OK)
pylint >=0.25     :  2.9.6 (OK)
```

**Comment by ccordoba12** [comment]
Hey @qwertyuiopasdfghjklzxcvbnmuiorhhui, thanks for reporting. This problem is fixed in our latest version available in Anaconda (5.4.3). Please update by closing Spyder, opening the Anaconda Prompt and running there the commands mentioned in [our documentation](http://docs.spyder-ide.org/current/installation.html#updating-with-anaconda).

If that doesn't work, I'm afraid you'll have to remove and install Anaconda again.
