### ISSUE TITLE
When closing a modified file, the text on the popup's buttons could be clarified

### ISSUE THREAD

**Issue by narFnarF** [spyder-ide/spyder#21482]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When closing a file that has been modified, Spyder opens a popup with this text:
"**filename** has been modified. Do you want to save changes?"
Buttons: [Cance] [No] [Yes]
![image](https://github.com/spyder-ide/spyder/assets/3538115/6f98e12a-224a-4f27-aab4-b883af53221c)

### What steps reproduce the problem?

1. Edit a file
2. Close the file without saving first

### What is the expected output? What do you see instead?
The wording of the popup could be improved as such:
Button "Cance" ➡️ "Cancel"
Button "No" ➡️ "Discard changes"
Button "Yes" ➡️ "Save changes"

## Versions

* Spyder version: 5.4.4
* Python version: 3.11
* Qt version: 5.15.2
* PyQt version: 5.15.7
* Operating System name/version: Linux 5.15.0-88-generic (x86_64) 

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                                                        :  1.4.1 (OK)
chardet >=2.0.0                                                             :  5.2.0 (OK)
cloudpickle >=0.5.0                                                         :  2.2.1 (OK)
cookiecutter >=1.6.0                                                        :  2.3.0 (OK)
diff_match_patch >=20181111                                                 :  20230430 (OK)
intervaltree >=3.0.2                                                        :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0,!=8.11.0,!=8.12.0,!=8.12.1 :  8.14.0 (OK)
jedi >=0.17.2,<0.19.0                                                       :  0.18.2 (OK)
jellyfish >=0.7                                                             :  1.0.0 (OK)
jsonschema >=3.2.0                                                          :  4.19.0 (OK)
keyring >=17.0.0                                                            :  24.2.0 (OK)
nbconvert >=4.0                                                             :  7.8.0 (OK)
numpydoc >=0.6.0                                                            :  1.5.0 (OK)
parso >=0.7.0,<0.9.0                                                        :  0.8.3 (OK)
pexpect >=4.4.0                                                             :  4.8.0 (OK)
pickleshare >=0.4                                                           :  0.7.5 (OK)
psutil >=5.3                                                                :  5.9.5 (OK)
pygments >=2.0                                                              :  2.16.1 (OK)
pylint >=2.5.0,<3.0                                                         :  2.17.5 (OK)
pylint_venv >=3.0.2                                                         :  3.0.2 (OK)
pyls_spyder >=0.4.0                                                         :  0.4.0 (OK)
pylsp >=1.7.4,<1.8.0                                                        :  1.7.4 (OK)
pylsp_black >=1.2.0,<3.0.0                                                  :  1.3.0 (OK)
qdarkstyle >=3.0.2,<3.2.0                                                   :  3.1 (OK)
qstylizer >=0.2.2                                                           :  0.2.2 (OK)
qtawesome >=1.2.1                                                           :  1.2.3 (OK)
qtconsole >=5.4.2,<5.5.0                                                    :  5.4.3 (OK)
qtpy >=2.1.0                                                                :  2.3.1 (OK)
rtree >=0.9.7                                                               :  1.0.1 (OK)
setuptools >=49.6.0                                                         :  68.1.2 (OK)
sphinx >=0.6.6                                                              :  7.2.4 (OK)
spyder_kernels >=2.4.4,<2.5.0                                               :  2.4.4 (OK)
textdistance >=4.2.0                                                        :  4.5.0 (OK)
three_merge >=0.1.1                                                         :  0.1.1 (OK)
watchdog >=0.10.3                                                           :  3.0.0 (OK)
xdg >=0.26                                                                  :  0.28 (OK)
zmq >=22.1.0                                                                :  25.1.1 (OK)

# Optional:
cython >=0.21                                                               :  None (NOK)
matplotlib >=3.0.0                                                          :  None (NOK)
numpy >=1.7                                                                 :  None (NOK)
pandas >=1.1.1                                                              :  None (NOK)
scipy >=0.17.0                                                              :  None (NOK)
sympy >=0.7.3                                                               :  None (NOK)
```

**Comment by narFnarF** [comment]
If someone could point me to where those strings are located, I might be able to fix them myself.

**Comment by dalthviz** [comment]
Hi @narFnarF thank you for the feedback and willingness to implement your suggestion! I think we are using there the standard Qt buttons and probably the `Cancel` button text is being cut due to the dialog size :thinking: Anyhow, regarding your text suggestions, what do you think @spyder-ide/core-developers ?

> If someone could point me to where those strings are located, I might be able to fix them myself.

I think that dialog is located at https://github.com/spyder-ide/spyder/blob/ec13a2547de6d158f4d366a693e190447cae2769/spyder/plugins/editor/widgets/editorstack/editorstack.py#L1668-L1676

To change the buttons text most probably you will need to manually add the button by calling [`QMessageBox.addButton`](https://doc.qt.io/qt-5/qmessagebox.html#addButton-1) from the message box widget that is being created instead of passing the buttons and accommodate the validations that check for what button was selected

**Comment by ccordoba12** [comment]
I think the dialog is clear enough if you read the text on it. But I agree that doing the changes suggested by @narFnarF you would have a better idea of what kind of action Spyder is requiring.

@CAM-Gerlach, what do you think?

**Comment by mrclary** [comment]
One issue I have with making custom button text is that the button text becomes cramped and difficult to read, or the buttons have to be made larger and become non-uniform in size in the message box. This is aesthetically distracting and does not look professional.

I would recommend keeping the standard buttons, but perhaps add vertical space above "Do you want to save the changes?", which might help give it more attention.

If we decide to change the button text, then I would recommend keeping the words short, e.g. "Cancel", "Discard", "Save", in order to maintain button size uniformity without crowding the text in the button.

**Comment by narFnarF** [comment]
I would be ok with the shorter text proposed by @mrclary

**Comment by ccordoba12** [comment]
@mrclary, could you take care of this one? Thanks!

**Comment by mrclary** [comment]
To be clear, we have agreed to modify the button text to "Cancel", "Discard", and "Save", correct?

**Comment by ccordoba12** [comment]
Yep, that's correct.

**Comment by CAM-Gerlach** [comment]
Overall, this would make the actions a lot clearer and avoid confusion, cognitive load and possible (desctructive) mistakes parsing it incorrectly, and would also follow the lead of what I'm seen from other applications. I do agree with the short forms, as otherwise you're likely to just have the text cut off as it is for the Cancel button in the OP's screenshot, due to their system's rather unusual and wonky theming I presume.

If possible, I'd suggest changing the order as well. Given the question is "Do you want to save changes?", the conventional and natural order to me in English would be "Save" "Discard" "Cancel" / "Yes" "No" "Cancel", which is also what I see testing a couple other editors.

**Comment by mrclary** [comment]
> If possible, I'd suggest changing the order as well. Given the question is "Do you want to save changes?", the conventional and natural order to me in English would be "Save" "Discard" "Cancel" / "Yes" "No" "Cancel", which is also what I see testing a couple other editors.

I believe this is actually platform dependent and should be respected as such.
On macOS:
<img width="401" alt="Screenshot 2023-12-18 at 1 40 22 PM" src="https://github.com/spyder-ide/spyder/assets/9618975/7984aefb-0e38-47a8-9e09-c632d1d09bcd">
On Windows:
<img width="279" alt="Screenshot 2023-12-18 at 1 45 03 PM" src="https://github.com/spyder-ide/spyder/assets/9618975/2b728f0e-6af2-4c6c-8b50-65c210db4140">
On Ubuntu:
<img width="297" alt="Screenshot 2023-12-18 at 2 00 10 PM" src="https://github.com/spyder-ide/spyder/assets/9618975/3df00cee-feab-4a14-adb6-15d0c942bec5">

**Comment by ccordoba12** [comment]
There is an additional change in PR #21631, which was opened by @mrclary to fix this issue. And I think we also need to agree on it first here: when multiple files are unsaved @mrclary proposes to add a checkbox named `Apply to all` to the dialog.

I don't have a strong opinion about it, but I'd prefer to keep the buttons because they seem simpler to use for me. Of course, following on what we agreed above, they should be renamed to `Save all` and `Discard for all`.

What do you think?

**Comment by conradolandia** [comment]
I think haveing the checkbox will make the choice binary for all files. Having different buttons (Cancel, Discard for All, Discard, Save All, Save)  provides a better UX because you can make the choice for each unsaved file.

**Comment by CAM-Gerlach** [comment]
I don't have a strong preference again the checkbox, but separate buttons seems to be the common convention in most other applications for this, and the checkbox looks a bit off as is in terms of layout and would need some UI tweaks to look better.

**Comment by mrclary** [comment]
> I think haveing the checkbox will make the choice binary for all files. Having different buttons (Cancel, Discard for All, Discard, Save All, Save) provides a better UX because you can make the choice for each unsaved file.

I think you may be confused by the current behavior. Discard All or Save All buttons are also binary for all unsaved files. In this case if the user wants to save some and discard other files, then the dialog box will go through each file one by one as the user selects to either save or discard. However, if at any time, the user selects Save/Discard All, then this action is applied to all remaining files.

The checkbox does not change this behavior. The checkbox is always initially unchecked. The user has the opportunity to Save/Discard changes to each file in turn. However, if at any time, the user selects the "Apply to all" checkbox, then the selected action is applied to all remaining files.

**Comment by mrclary** [comment]
> but separate buttons seems to be the common convention in most other applications for this

But an "Apply to all" checkbox seems to be the common convention in most other applications. I cannot recall any software that uses 5 buttons in a save dialog box.

> and the checkbox looks a bit off as is in terms of layout and would need some UI tweaks to look better.

The checkbox position is set in `spyder.widgets.helperwidgets.MessageCheckBox` and therefore is the same for any Spyder message box that uses this class. A "tweak" to this class would be outside the scope of the issue and associated PR.

This looks much clearer to me
<img width="401" alt="Screenshot 2023-12-18 at 10 15 39 PM" src="https://github.com/spyder-ide/spyder/assets/9618975/ec5b2e44-7df6-4016-a6d6-fa4cb5892c00">

than this
<img width="575" alt="Screenshot 2023-12-18 at 3 31 50 PM" src="https://github.com/spyder-ide/spyder/assets/9618975/336bf7a5-f314-4b46-b37e-1c898a07efd4">

**Comment by ccordoba12** [comment]
@CAM-Gerlach and @mrclary, could you post screenshots of those other apps to see how they approach this problem?

**Comment by CAM-Gerlach** [comment]
> I think you may be confused by the current behavior. Discard All or Save All buttons are also binary for all unsaved files.

Yes, I didn't really understand this comment, as the underlying behavior is effectively the same either way.

> @CAM-Gerlach and @mrclary, could you post screenshots of those other apps to see how they approach this problem?

The first two MDI applications I thought of that faced this issue, performing an operation that required confirmation and applied to multiple files, were MultiCommander and Notepad++, and they both used similar approaches:

![image](https://github.com/spyder-ide/spyder/assets/17051931/17a4a2dd-54a9-445a-a4fe-aa3559aa5a2c)

![image](https://github.com/spyder-ide/spyder/assets/17051931/6ac4834e-f046-4a1c-b7c7-bc08f5c4a66f)

By contrast, Windows File Explorer just shows the all file options and another option to decide per-file:

![image](https://github.com/spyder-ide/spyder/assets/17051931/f0ec61d6-222d-4451-a6f1-c3a1bee1fbd6)

Closing ConEmu with multiple consoles having incomplete operations takes a substantially different approach:

![image](https://github.com/spyder-ide/spyder/assets/17051931/96701b12-c260-4844-b608-f3d5c2c99c57)

I'm not sure what I can immediately think of that has a MDI on Windows and that I use frequently that has options to to make decisions both per-file or globally, the others I tested that did have otherwise similar behavior offered only per-file or global options, and not both.

**Comment by mrclary** [comment]
Well, I can't seem to find examples one way or the other 🤷🏼. All the apps I looked at on macOS either cycle through each unsaved document without the option to apply to all, or provide multiple message boxes, the first of which allows to discard all changes or to review changes and subsequent message boxes cycle through unsaved files.

So, I'm fine with whatever everybody else wants.

**Comment by ccordoba12** [comment]
> So, I'm fine with whatever everybody else wants.

Ok, in that case please restore the five buttons we were showing before but with the new text Discard/Save text.
