### ISSUE TITLE
Possibility to release constraint of qtconsole

### ISSUE THREAD

**Issue by frenzymadness** [spyder-ide/spyder#21495]
Qtconsole 5.5 is out and it seems it should still be compatible with spyder: https://github.com/jupyter/qtconsole/blob/master/docs/source/changelog.rst#550 AFAIU the drop of Python 3.7 is not a problem for spyder.

https://github.com/spyder-ide/spyder/blob/7ee864a19552a24ad565633a9621219eb7c4677e/setup.py#L241

**Comment by ccordoba12** [comment]
We're perfectly aware of this (I did the Qtconsole release because I'm its maintainer too). And I did it in preparation for a new Spyder version (5.5.0), to be released in a day or two.

So, we'd appreciate if you don't create this (basically) zero-day requests for next time because they are simply a waste of our time for us (to answer, classify, reference in PRs, etc). Thanks!

**Comment by frenzymadness** [comment]
I'm trying to deliver the latest software in Fedora Linux as fast as I can and I realized that the upper limit in Spyder is blocking the update of qtconsole to the latest version so I reported it. It's impossible for me to check who maintains what and assume that the situation is handled properly when one maintainer maintains both projects.

**Comment by ccordoba12** [comment]
>  It's impossible for me to check who maintains what

Sure, and that's why clearly said:

>> So, we'd appreciate if you don't create this (basically) zero-day requests for **next time**

because now you know we maintain both projects.

**Comment by ccordoba12** [comment]
And we also maintain Python-lsp-server, just so you know.
