### ISSUE TITLE
An Error occured While startting kenel

### ISSUE THREAD

**Issue by darshankumar2003** [spyder-ide/spyder#21497]
![Screenshot 2023-11-07 073839](https://github.com/spyder-ide/spyder/assets/148458023/d1f4ca46-572d-478a-b7db-f76ba7334f93)

**Comment by ccordoba12** [comment]
Hey @darshankumar2003, thanks for reporting. Since you didn't fill the information we require for an issue, I'm going to ask you to open a new one for this.

But instead of doing it directly here, please go to the Spyder menu

    Help > Report issue

and in the field to describe your error, please copy/paster the error you have in the screenshot above.

Then, the new issue will have all the information we need to properly help you.
