### ISSUE TITLE
doesn't have the spyder‑kernels module or the right version of it installed

### ISSUE THREAD

**Issue by xiaoweivivian** [spyder-ide/spyder#21592]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
The Python environment or installation whose interpreter is located at
    /Users/opt/anaconda3/envs/sele/bin/python
doesn't have the spyder‑kernels module or the right version of it installed (>= 2.5.0 and < 2.6.0). Without this module is not possible for Spyder to create a console for you.

You can install it by activating your environment first (if necessary) and then running in a system terminal:
    conda install spyder-kernels=2.5
or
    pip install spyder-kernels==2.5.*
```

**Comment by dalthviz** [comment]
Hi @xiaoweivivian , seems like you are trying to set a custom interpreter located inside a conda environment named `sele` as the one Spyder should use? Since you don't have the `spyder-kernels` package installed or with the right version installed or Spyder is being unable to detect it over your `sele` environment Spyder shows the message you are seeing.

Did you already tried to update/install `spyder-kernels` over your `sele` environment? If not and since seems like you are using conda, the actual command you need to run on the terminal (being sure of firts activate your `sele` environment) should be something like:

    conda install -c conda-forge spyder-kernels=2.5

Also, for more info about how to use specific interpreters/environments/packages checking the Spyder docs FAQ page could be worthy: https://docs.spyder-ide.org/current/faq.html#using-spyder

Let us know if the info above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
