### ISSUE TITLE
Spyder crashes on startup after update

### ISSUE THREAD

**Issue by orangepig1222** [spyder-ide/spyder#21642]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by orangepig1222** [comment]
### What steps will reproduce the problem?

1. Opened Spyder IDE from Anaconda Navigator.
2. Created a new Python file.
3. Typed some code and hit the 'Run' button.
4. The IDE froze and then displayed this error message.

**Comment by ccordoba12** [comment]
Hey @orangepig1222, thanks for reporting. It seems you're using a quite old Spyder version (perhaps Spyder 3).

If that's the case, I'm afraid you'll have to update to our latest version available in Anaconda (5.4.3) because older versions are not supported. Please do that by closing Spyder, opening the Anaconda Prompt and running there the commands mentioned in [our documentation](http://docs.spyder-ide.org/current/installation.html#updating-with-anaconda).

If that doesn't work, I'm afraid you'll have to remove and reinstall Anaconda.

Let us know if that work for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
