### ISSUE TITLE
Question regarding pyuca in Spyder 6.0.0a3

### ISSUE THREAD

**Issue by penguinpee** [spyder-ide/spyder#21677]
With version 6.0.0a3 Spyder introduced a new dependency on [`pyuca`](https://github.com/jtauber/pyuca) (https://github.com/spyder-ide/spyder/commit/77ff71b564812c4529cb67d551eef4f791d76b6e). I'm one of the package maintainers of Spyder in Fedora. Since we are required to package all dependencies seperately, I submitted `pyuca` as a new package for Fedora.

It turns out that in the current release, dating back to September 2017, the license situation wrt to the Unicode license(s) is unclear. I'm trying to get clarification internally as well as from the `pyuca` developer(s). However, the last commit to `pyuca` was made in October 2019.

So, we have a release from more than six years ago and a commit from more than four years ago. That raised my eyebrow, wondering why make Spyder dependent on a module that appears to be no longer under active development / maintenance?

If `pyuca` turns out to be not permissible in Fedora, that would make things very complicated keeping Spyder up to date downstream. I'd appreciate any thoughts on the matter.

**Comment by ccordoba12** [comment]
> That raised my eyebrow, wondering why make Spyder dependent on a module that appears to be no longer under active development / maintenance?

That module is quite simple: it allows to sort Unicode strings. That's why it probably doesn't require updates and additional maintenance. But I reviewed how it works and it doesn't its job as expected. And we need something like that in Spyder because we support languages such as Chinese, Japanese and Russian, so we want to provide a UI that makes sense for users in those languages.

> If pyuca turns out to be not permissible in Fedora, that would make things very complicated keeping Spyder up to date downstream. I'd appreciate any thoughts on the matter.

I understand, but that was the only pure Python package I could find for this. Others require heavy compiled dependencies.

**Comment by penguinpee** [comment]
Thanks for the explanation. I was mainly checking to be sure the effort I'm putting into getting pyuca into Fedora is not in vain. Since 6.0.0a3 is still a pre-release, it wouldn't have surprised me, if that was some kind of "let's try that".

I'll close the issue and focus on getting pyuca cleared.
