### ISSUE TITLE
Spyder don't launch

### ISSUE THREAD

**Issue by DjophDOVE** [spyder-ide/spyder#21735]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Hello, so thanks you first.
After anaconda installation, m'y Spyder worked good, and it opened ... 
But After installing qt-pyqt-pyside-custom-widgets.., pyqt5, Pyqt5-tools... My Spyder don't launch. Please me to resort this problem. I Must use these library for m'y project.

10x

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5
* Python version: 
* Qt version: 5
* PyQt version: 5
* Operating System name/version: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @DjophDOVE, thanks for reporting and sorry for the late reply. It seems you broke Spyder due to mixing pip and conda packages. The problem with doing that is that they are incompatible, so it leads to issues like the one you encountered.

Please take a look at [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to learn how to fix that problem. The basic ideas are:

* You need to uninstall and reinstall Anaconda to fix that problem.
* After doing that, you need to create a new conda environment to install the packages you need on it with pip (instead of doing it in the same environment in which Spyder is installed).
* Finally, you need to connect that environment to Spyder by following [these instructions](http://docs.spyder-ide.org/current/faq.html#using-existing-environment) in our documentation.
