### ISSUE TITLE
Can't open DataFrames in Variable Explorer

### ISSUE THREAD

**Issue by BierFlo** [spyder-ide/spyder#21835]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
When trying to open DataFrames in the Variable Explorer, I get this error message. Even if the DataFrame is really simple. The same code on a different device works, so its definetly a problem of what environment I got on this computer.

**Comment by ccordoba12** [comment]
Hey @BierFlo, thanks for reporting. This problem is fixed in our latest version available in Anaconda (5.4.3). Please update by closing Spyder, opening the Anaconda Prompt and running there the commands mentioned in [our documentation](http://docs.spyder-ide.org/current/installation.html#updating-with-anaconda).
