### ISSUE TITLE
I can't make matplotlib work on jupyter (chromebook)

### ISSUE THREAD

**Issue by lusidespyder** [spyder-ide/spyder#21901]
hi,
I've been having problems with the jupyter notebook on anaconda for a while now.
I can't seam to get my code work when I use matplotlib, it works for any other library.
It says that the kernel has died and that it will restart.
can you help me please

for info, i am on a chromebook and when i start anaconda i get this message (even though I reinstalled it multiple times) : 
2024-03-16 19:13:32,770 - WARNING linux_scaling.get_scaling_factor_using_dbus:32
An exception occurred during fetching list of system display settings.

libGL error: MESA-LOADER: failed to open virtio_gpu: /usr/lib/dri/virtio_gpu_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: virtio_gpu
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast

also i'm a noob at coding

**Comment by ccordoba12** [comment]
Hey @lusidespyder, thanks for reporting. You said:

> for info, i am on a chromebook and when i start anaconda i get this message (even though I reinstalled it multiple times) :
2024-03-16 19:13:32,770 - WARNING linux_scaling.get_scaling_factor_using_dbus:32
An exception occurred during fetching list of system display settings.
>
> libGL error: MESA-LOADER: failed to open virtio_gpu: /usr/lib/dri/virtio_gpu_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: virtio_gpu
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast

I don't think you'll be able to use Matplotlib on a Chromebook because it's not a regular Linux desktop.

> I've been having problems with the jupyter notebook on anaconda for a while now.

You should try to run in a cell

    %matplotlib notebook

and try again. That should work, but I can't  say for sure because I haven't heard of people using Anaconda on Chromebooks.

**Comment by ccordoba12** [comment]
Since this is a place to report issues about Spyder, not Jupyter, I'm going to close this issue. For additional help, I recommend you to post your problem here:

https://github.com/jupyterlab/jupyterlab/
