### ISSUE TITLE
How to detect python is running inside Spyder

### ISSUE THREAD

**Issue by eendebakpt** [spyder-ide/spyder#21929]
## Problem Description
 
Is the an "official" way to detect a python session is running as a console inside Spyder?

There are some methods listed in https://stackoverflow.com/questions/53829284/how-to-know-if-a-script-is-running-in-spyder-or-any-other-python-ide, but it is not directly clear whether there is a preferred one.

Also see https://github.com/tqdm/tqdm/pull/1559

**Comment by ccordoba12** [comment]
Hey @eendebakpt, thanks for reporting. Between the two methods mentioned in the SO question you referenced, I think it's safer to use the second one, i.e.

```
from IPython import get_ipython

shell_cls_name = get_ipython().__class__.__name__
if shell_cls_name == 'SpyderShell':
    # Do things only for Spyder
    ...
```

That's because we're considering to remove all env vars we use to start a kernel (the `SPY_*` ones mentioned there), but `SpyderShell` is not going to go away.

Let us know if that's enough for the Spyder support you're trying to add to `tqdm` (and thanks for taking care of that, by the way).

**Comment by ccordoba12** [comment]
Closing because I saw you followed my suggestion in your tqdm PR.
