### ISSUE TITLE
Attribute Qt::AA_UseSoftwareOpenGL must be set before QCoreApplication is created.

### ISSUE THREAD

**Issue by AlexisKaka** [spyder-ide/spyder#21949]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
Attribute Qt::AA_UseSoftwareOpenGL must be set before QCoreApplication is created.

**Comment by ccordoba12** [comment]
Hey @AlexisKaka, thanks for reporting. This problem should fixed in our latest version available in Anaconda (5.4.3). Please update by closing Spyder, opening the Anaconda Prompt and running there the commands mentioned in [our documentation](http://docs.spyder-ide.org/current/installation.html#updating-with-anaconda).

Let us know if that works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
