### ISSUE TITLE
pylsp >=1.4.1;<1.5.0 : 1.11.0 (NOK) ... on anaconda

### ISSUE THREAD

**Issue by paul18frr** [spyder-ide/spyder#21970]
Hi,
I've updated this morning my anaonda release and I'm getting an error (see screenshot); i do not understand what's going wrong => any suggestion?
Thanks
![Issue_Spyder](https://github.com/spyder-ide/spyder/assets/54111594/ccd4d98c-d01a-4629-b2d6-d6c4e5da7a9c)

```
conda install -c conda-forge python-lsp-server
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

# All requested packages already installed.
```

```
conda list python-lsp-server
# packages in environment at C:\Users\paul18fr\anaconda3:
#
# Name                    Version                   Build  Channel
python-lsp-server         1.4.1              pyhd8ed1ab_1    conda-forge
python-lsp-server-base    1.11.0             pyhd8ed1ab_0    conda-forge
```

**Comment by ccordoba12** [comment]
Hey @paul18frr, thanks for reporting. It seems you updated Spyder using Conda-forge in your base Anaconda environment. If that was case, I'm afraid you broke your Anaconda installation and you'll have to reinstall it.

That's because Conda-forge packages and those from the defaults channel (i.e. the ones that come from Anaconda) are binary incompatible. In other words, they can't be mixed in the same environment.

After you reinstall Anaconda, if you want to update to the latest Spyder (which is only available in Conda-forge), you need to create a new environment like this:

    conda create -n spyder-env -c conda-forge python=3.11 spyder
    conda activate spyder-env
    spyder

If you want to use other packages from Conda-forge, you also need to install them in that environment, like this

    conda activate spyder-env
    conda install -c conda-forge pandas matplotlib

in case you want to use Pandas and Matplotlib.

Let us know if that solves your problem.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
