### ISSUE TITLE
Use Python 3.11 in the Spyder 6 installers

### ISSUE THREAD

**Issue by Firestar-Reimu** [spyder-ide/spyder#22068]
The newest python is 3.12 and 3.10 will be deprecated in 2026-10

Is there any problem running spyder 6.0 on 3.12?

**Comment by PhilipYip1988** [comment]
I think the standalone installer only comes with Python 3.10. 

The conda install instructions on the [Spyder 6.0.0a5 Release Notes](https://github.com/spyder-ide/spyder/releases/tag/v6.0.0a5) also default to Python 3.10:

```
conda create -n spyder-env -c conda-forge python=3.10
conda activate spyder-env
conda install -c conda-forge/label/spyder_dev -c conda-forge/label/spyder_kernels_rc -c conda-forge spyder=6.0.0a5
```

However if search is used, instead of install in the third command:

```
conda install -c conda-forge/label/spyder_dev -c conda-forge/label/spyder_kernels_rc -c conda-forge spyder=6.0.0a5
```

There is a Python 3.11 version but no Python 3.12 version:

![spyder](https://github.com/spyder-ide/spyder/assets/56493395/d80f1915-4cd8-4c85-a6f1-d517b1d23393)

Spyder is an IDE that uses lots of Python libraries as dependencies and it is likely that one or more of these dependencies aren't updated to Python 3.12 yet.

I installed the Python 3.11 version, alongside some of the optional dependencies:

```
conda create -n spyder-env -c conda-forge python=3.11
conda activate spyder-env
conda install -c conda-forge/label/spyder_dev -c conda-forge/label/spyder_kernels_rc -c conda-forge spyder=6.0.0a5
conda install -c conda-forge cython seaborn scikit-learn pyarrow sympy openpyxl xlrd xlsxwriter lxml sqlalchemy tabulate pyqt
```

<img width="572" alt="image" src="https://github.com/spyder-ide/spyder/assets/56493395/9b85ef7f-a3e4-4b45-91f0-def446cbb5a3">

The [Status of Python Versions](https://devguide.python.org/versions/) shows that Python 3.12 is still in the **bugfix** stage and therefore it is still considered somewhat unstable. 

It is generally recommended to use an earlier version that is on the **security** stage, especially with a large Python environment with a large number of packages which is required for Spyder. This would be Python 3.11 or Python 3.10 as Python 3.9 and Python 3.8 are approaching end of life. The Anaconda 2024-02 installer which comes with Spyder 5.4.3, for example uses Python 3.11.

**Comment by ccordoba12** [comment]
@Firestar-Reimu thanks for reporting and @PhilipYip1988 for your thoughtful comment.

@Firestar-Reimu, you said:

> Is there any problem running spyder 6.0 on 3.12?

No, due to the reasons explained by @PhilipYip1988. We don't use the latest Python version in our installers to avoid potential issues while it's still being developed.

However, that doesn't make much a of a difference because Spyder installers come with the most basic Python libraries for scientific development. So, users have to connect Spyder to a separate Python installation that comes with a larger amount of packages (usually Anaconda). That's explained in our docs:

http://docs.spyder-ide.org/current/faq.html#using-packages-installer

@PhilipYip1988, you said:

> It is generally recommended to use an earlier version that is on the security stage, especially with a large Python environment with a large number of packages which is required for Spyder. This would be Python 3.11 or Python 3.10

That's a very good point and we're going to update our installers to use Python 3.11 before the final 6.0 release.

**Comment by ccordoba12** [comment]
@mrclary, could you take care of using Python 3.11 for our installers? Thanks!
