### ISSUE TITLE
Spyder on Binder is non-responsive

### ISSUE THREAD

**Issue by chrisjj** [spyder-ide/spyder#22124]
1 Follow https://www.spyder-ide.org/ :
     **You can also try out Spyder right in your web browser by [launching it on Binder](https://mybinder.org/v2/gh/spyder-ide/binder-environments/spyder-stable?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fspyder-ide%252FSpyder-Workshop%26urlpath%3Ddesktop%252F%26branch%3Dmaster).
2 See desktop:

![image](https://github.com/spyder-ide/spyder/assets/6157073/09f9f54e-5736-45aa-826d-1cd00ef90234)

3 Click **Run**

Expected: response
Observed: none

Likewise clicking other menu items and in the temp.py editor gets no response.

### Issue Report Checklist

* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)

Not possible, obviously.

**Comment by dalthviz** [comment]
Hi @chrisjj thank you for the feedback! I stumbled across this issue while releasing Spyder 5.5.5 and updating the binder image. Seems like having an open project causes Spyder to freeze over binder :thinking: Did a quick check launching Spyder in debug mode over binder and seems like maybe watchdog (package used to monitor project files) and the launching of a console due to a project being opened are causing some sort of deadlock? What do you think @ccordoba12 ?

Here the log I was able to capture: [binder-freeze.log](https://github.com/user-attachments/files/15829267/binder-freeze.log)

**Comment by ccordoba12** [comment]
> Did a quick check launching Spyder in debug mode over binder and seems like maybe watchdog (package used to monitor project files) and the launching of a console due to a project being opened are causing some sort of deadlock? What do you think @ccordoba12 ?

Yep, that was the problem in Spyder 5. But now there's another issue in Spyder 6 with the mechanism we use to kill kernels.

@chrisjj, sorry for the late reply but we were quite busy preparing the 6.0 release. However, we'll address this in 6.0.1, to be released this week.
