### ISSUE TITLE
Pushing local git repository to remote github repository

### ISSUE THREAD

**Issue by yam3moe** [spyder-ide/spyder#22125]
I am trying to push my local git repository, which is also a spyder project, into a github repository. This is a solo project, meaning I don't have to worry about collaborators. All I really want to achieve is to have any changes I make in my local git repository (rename a script, delete a script, etc.) pushed to remote github repository and have it as a backup. 

So, I did the following steps without success:

1. Create a spyder project, based on the Spyder documentation [here](https://docs.spyder-ide.org/current/panes/projects.html)

2. Open the project in Spyder, and in IPython console, type ```!git init```. This makes the Spyder project also the git repository (AFAIK).

3. On the github website, create a repository, say, named "gitpush" with readme file.

4. Coming back to Spyder, in Ipython console, type ```!git remote add origin https://github.com/myusername/gitpush.git```

5. Create a new script in the Spyder project, say, named "tobepushed" and insert some lines.

6. In Ipython console, add and commit changes made in step 5 with ```!git add .``` and ```!git commit -m "some message'``` 

7. Finally, push the changes to github "gitpush" repository with ```!git push -u origin main```

At stage 7, I get this message:
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/myusername/gitpush.git'

Can somebody please help me what is going on? I did a bit of searching+ChatGPT and first, my understanding of the problem is that the name of the branch in local git repository is 'central' rather than 'main'. So, I renamed the local branch with ```git branch -M main```, but I get even weirder/more complicated error message. All I want to do is push the changes in local git repository to remote github repository.

**Comment by roteiro** [comment]
The Issue is probably unrelated to Spyder.
If you did not configure differently, the name of the default branch should be master and not `central` or `main`. So repeat the procedure and in step 7 try: ̀`!git push -u origin master`
You should get the procedure working from the command line without the leading `!` before trying it from within the Spyder IDE.

**Comment by ccordoba12** [comment]
Hey @yam3moe, thanks for reporting. I think your problem is that you created a git repository locally and on Github and you can't sync them due to that.

To fix that, you need to remove your local `.git` directory and then clone your Github repo. To do that, go to the directory where you created your Spyder project, find `.git` and delete it. And then you need to run this command to do the second task:

    !git clone https://github.com/myusername/gitpush.git

You'll need to redo again your initial commit, but that shouldn't be a major issue.

Let us know if that works for you.

**Comment by ccordoba12** [comment]
> So, I first created a spyder project (say spyder1), then made a new github repo (gitpush) and ran this line in Ipython console !git clone https://github.com/myusername/gitpush.git.

I think this is your problem. Before creating a Spyder project, you need to clone your repository from Github (with `!git clone`, that's fine). Then, you need to create the Spyder project in the directory where your clone was created (i.e. in the `gitpush` directory). That should solve your problem.

> I guess it is because the cloned github repo is a subfolder in spyder1?

Yep, that's correct.
