### ISSUE TITLE
could not receive data from server: Software caused connection abort (0x00002745/10053)

### ISSUE THREAD

**Issue by Dexterity554** [spyder-ide/spyder#22463]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
1. dgen_model.py", line 59, in main
    con, cur = utilfunc.make_con(model_settings.pg_conn_string, model_settings.role)

2. utility_functions.py", line 144, in make_con
    con = pg.connect(connection_string, async_=async_)

3. site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not receive data from server: Software caused connection abort (0x00002745/10053)

**Comment by ccordoba12** [comment]
Hey @Dexterity554, thanks for reporting. Since you didn't provide any context about this problem, we can only guess that it's related to a program you're trying to run in Spyder, and not with Spyder itself.

If that's the case, we can't help you with it here and you need to ask about it in another website (e.g. StackOverflow). If not, please let us know how this is a bug in Spyder.
