### ISSUE TITLE
6.0.0 breaks pip editable mode

### ISSUE THREAD

**Issue by mluerig** [spyder-ide/spyder#22536]
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

6.0.0 breaks pip editable mode: packages are not automatically reloaded after code refactoring 

### What steps reproduce the problem?

1. I updated from 5.5.6 to 6.0.0
2. Installed a package using `pip install -e <package>`
3. Live code refactoring isn't recognized until the kernel is restarted

## Versions

* Spyder version: 6.0.0
* Python version:  py39, py310, py311 (tried all)
* Qt version: 5.15.8
* PyQt version: 5.15.9
* Operating System name/version: Windows 11

**Comment by dalthviz** [comment]
Hi @mluerig thank you for the report! Checking around, maybe this is related with https://github.com/spyder-ide/spyder/issues/22433? Seems like, on Windows, we disabled automatically enabling the `%autoreload` magic option. That could be something that enables doing live code refactoring 🤔 What happens if you try to enable again the autoreload preference? For that you can go to `Preferences > IPython Console > Advanced Settings > Autoreload` and check `Enable Autoreload`:

![image](https://github.com/user-attachments/assets/8e48a174-4c5e-4b63-8ac0-1140de414c4d)

Let us know if the info above helps!

**Comment by mluerig** [comment]
that seemed to have worked - thanks!
