### ISSUE TITLE
Start testing with pytest/pytest-qt and coverage for Spyder

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#2268]
I've never thought of creating a test suite because Spyder has a lot of moving parts, and it's hard to sit down and provide a test for each of them.

However, I've heard a lot lately that Spyder is considered unstable by several people. So I think we should start (at least) by testing that Spyder starts with the git-master versions of all its optional dependencies, to notice and fix startup crashes as quickly as we can.

I also just found this project

https://github.com/pytest-dev/pytest-qt

that seems to provide a good foundation to create a more comprehensive test suite.

Pinging @goanpeca and @blink1073 for discussion ;-)

**Comment by goanpeca** [comment]
Having a lot of moving parts is no excuse for not having a full test suite ;-)!

I will take a look at the package you mention. 

I can make a PR to include the yaml file to start at least basic tests of starting spyder and let it run for some time (a couple of minutes)

**Comment by ccordoba12** [comment]
> Having a lot of moving parts is no excuse for not having a full test suite ;-)!

Yes, I know, but given my limited time too, either I fixed bugs or wrote tests. But now that I have more time, I can consider this possibility ;-)

> I can make a PR to include the yaml file to start at least basic tests of starting spyder and let it run for some time (a couple of minutes)

Yes, please do it ASAP. I think pandas 0.16 broke us again :-(

**Comment by dhoegh** [comment]
:100:,  at least some parts have a decent test by `if __name__ == '__main__':` but they do not get executed often and hence do break without anybody noticing.

**Comment by Nodd** [comment]
A test suite should run every test everytime, otherwise it's not a testsuite but just help to develop faster.

That said it's hard to do for GUIs, slow and boring ;)

**Comment by SylvainCorlay** [comment]
Running the parts that have a `__main__` function in batch as part of the TravisCI script could still be a first step as in checking that things "build".

**Comment by Nodd** [comment]
:+1: Didn't think about that.

**Comment by goanpeca** [comment]
I already had started doing this that @SylvainCorlay  mentions (testing the mains inside the widgets). I can get that working for the weekend.

**Comment by Nodd** [comment]
Actually the main testing platform are nose and pytest (please don't use unittest!).
tox is used to run these tests under different environments and can run either pytest or nosetests.
I don't know about QTest but I guess it can be integrated into both (to be confirmed).

*nosetest* has the advantage of being used by numpy, which provides testing functions for arrays, but it's not really important for spyder itself.
*pytest* has the advantage of being easier to use, since tests are basically plain old ```assert```s. Also, it's needed for pytest-qt. My preference would be for pytest.

**Comment by ccordoba12** [comment]
I think QTest's can be created with pytest-qt, so I'd propose to use it (if that's the case :-)

@goanpeca, please move the tests out of widget and plugin files and into a `test` directory, placed in the `spyderlib` directory.

**Comment by goanpeca** [comment]
QTest has a gotcha, it only works with PyQt4/PyQt5, but not PySide... so in that case, pytest and pytest-qt would be the option to take

@ccordoba12 ok, I prefer `tests` ? but `test` is also fine....

**Comment by ccordoba12** [comment]
Oh, sorry. `tests` is fine!

**Comment by ccordoba12** [comment]
But should it be inside `spyderlib` so that people can run our test suite when Spyder is installed?

**Comment by goanpeca** [comment]
tests are not meant for users... are meant for us..., no?

Besides in travis the proces is to clone the repo.. and the do something like

```bash cd tests`

**Comment by Nodd** [comment]
tests are mostly meant for devs, but it would be good if someone reports an issue to ask him to run ```spyder --run-tests``` (or similar) to check if there are any problems here. It's easier than asking them to clone the repo first.

In my project I usually create a ```ŧests``` directory in each module I want to test, so that
* the tests are close to the code they test so it's easier to write
* the tests are easy to find
That's what numpy does for example.
Separating tests from the code has its advantages too. Seeing how most spyder modules are interdependent, maybe it's more appropriate.

**Comment by goanpeca** [comment]
Well I would rather have a single repo wide `tests` folder but that is just me...

**Comment by ccordoba12** [comment]
Ok, let's leave it under the root directory for now (i.e. next to `spyderlib` and not inside it)

**Comment by petebachant** [comment]
Chiming in here to note that, for example, both Numpy and Pandas include a `tests` package inside their main packages, like @Nodd is describing.

**Comment by blink1073** [comment]
I'm :+1: for `pytest` and `pytest-qt`.  I'd also argue that the tests should be under `spyderlib`.  This can provide invaluable feedback for users to be able to run the tests on their system and provide us with feedback.

**Comment by goanpeca** [comment]
Ok so we need to vote here, cause it seems opinions are divided! haha

**Comment by Nodd** [comment]
Well it seems that we all agree about pytest, that's a good start !

As for the position in the repo, here are the votes from the comments:
**/tests**
* @goanpeca 
* @ccordoba12 

**/spyderlib/tests**
* @blink1073 
* @Nodd 

Here are my opinions
**/test**
**+** Clearly separated from the code
**-** Not installed with spyder so users can not run tests

**/spyderlib/tests**
**+** Can be run without having to clone the repo
**+** Users can give valuable information
**-** "Clutters" the main code

For the travis script, this seems equally simple:
```
cd spyderlib/tests
python run_tests.py
```
Now FIGHT !

**Comment by goanpeca** [comment]
![image](https://cloud.githubusercontent.com/assets/3627835/6848593/6b061fc8-d3ce-11e4-8041-8972d3870bc8.png)

**Comment by blink1073** [comment]
In the end, Carlos has the trump card, so @Nodd  and I just need to work on him.  :smile:

**Comment by goanpeca** [comment]
Its ok, lets do it on `spyderlib/tests` I will have nightmares but otherwise I will survive, and no need to tub on @ccordoba12, he originally wanted that as well anyway!

**Comment by blink1073** [comment]
I would also argue that shipping with a test suite sends a strong message as an IDE.

**Comment by goanpeca** [comment]
sends a strong message that we should have done this a long time ago ;-)

**Comment by blink1073** [comment]
:tongue:

**Comment by blink1073** [comment]
@goanpeca, I can maintain the `.travis.yml` script.  I have a lot of battle scars from doing so for `scikit-image`

**Comment by goanpeca** [comment]
@blink1073 I have written a yml already using minconda only

You can see [here](https://github.com/goanpeca/QtPy/blob/master/.travis.yml) I know I could have made the file shorter, but assigning the matrix directly gave me the flexibility I needed

**Comment by goanpeca** [comment]
should we also use www.appveyor.com for windows testing?

**Comment by blink1073** [comment]
I'd say not at first.  Lets get the basics working.

**Comment by ccordoba12** [comment]
Just a little comment: I also think it's better to have our tests as part of the package rather than without it. That will make beta testers life easier too :-)

**Comment by goanpeca** [comment]
Ok I wil make the first PR if you are all ok with that?

For now I have these tests running https://travis-ci.org/goanpeca/spyder/builds/56129095

Not much for now, just starting spyder to see if it runs and shut downs with a timer after 30 seconds.

**Comment by goanpeca** [comment]
Ok, so back to testing. I have a basic thing that tests automatic indentation insertion and autocompletion in the code editor using the tests that were listed in the [documentation at google code](https://code.google.com/p/spyderlib/wiki/AutomaticColonAndQuotesInsertion). I am including all those tests but commenting out the ones that dont work ...while they get implemented :smiley:  

## BUT
Testing spyder widgets seem to be broken with `pytest-qt` because our shim (spyderlib.qt) seems to conflict with the one that comes with `pytest-qt`. I made a quick patch to make pytestqt import spyders shim instead its own and it seems to be working, so I guess we either need to look at ours or just use it with this patch.

I will open a PR soon to discuss more details but before that some comments.

**Comment by petebachant** [comment]
Another approach to testing PyQt apps: http://johnnado.com/pyqt-qtest-example/

**Comment by goanpeca** [comment]
I started a PR with tests using pytest-qt. So far its looking good, but before we continue we need to clean up the mess we have in CI with travis :-p (my fault...!).
