### ISSUE TITLE
Add a maximize button for each pane

### ISSUE THREAD

**Issue by thewhitetulip** [spyder-ide/spyder#2272]
Currently if we have to maximize a pane then we have to click on the button on the main toolbar
![screenshot from 2015-03-25 20 00 43](https://cloud.githubusercontent.com/assets/6261877/6826753/a322599e-d329-11e4-803f-b8fb8f464209.png)

A new button can be added right next to the two buttons in the screenshot above, and we can provide help text when a user hovers over the buttons

**Comment by ccordoba12** [comment]
@goanpeca, would you like to work on this one?

**Comment by goanpeca** [comment]
yep, its mine

**Comment by ccordoba12** [comment]
If you add the button as part of each pane, then sure, we can remove the one from the main toolbar.

**Comment by Nodd** [comment]
:+1:

**Comment by goanpeca** [comment]
Ok, so I took a look at this one. There should be a shorter way of doing this, but in Qt if you want a custom look/behaviour/widgets in the title bar of a QDockWidget you need to implement a new TitleBar widget. This is a pre test before I "mess up" the code in the dockwidgets of spyder. With the new icon there should be no awkwardness in the icons (as you can see now).

The good news on top of this, is that now we can get rid of the box around the title bar (which in my opinion looked ugly) plus, when setting the dockwidget margin globaly, we can also affect the titlebar so that it also looks better.

![image](https://cloud.githubusercontent.com/assets/3627835/6887970/30762148-d66f-11e4-9ddd-1712cc7f2ebb.png)

**Comment by thewhitetulip** [comment]
Looks great :+1: I didn't understand where is the box around the title bar.

**Comment by Nodd** [comment]
I think that the box depends on your OS/Theme.

**Comment by goanpeca** [comment]
@ccordoba12 I want to make a PR on this, but before I want to ask, should the new TitleBarWidget be created as a widget in `spyderlib/widgets` directory? or should it go directly in the `spyderlib/plugins/__init__.py`  (where the `SpyderDockWidget` class is located) ?

**Comment by goanpeca** [comment]
![image](https://cloud.githubusercontent.com/assets/3627835/6898621/7e25d49c-d6fb-11e4-9e54-8262b5533d12.png)

**Comment by Nodd** [comment]
I would put them with `SpyderDockWidget`. Also spyder-wise it's not a widget but more like a component of other widgets.

**Comment by goanpeca** [comment]
Good :) that is where I was putting them :p :+1:

**Comment by goanpeca** [comment]
Ok, now there is an issue... maximized widgets (for some reason) hide the title bar (custom or not) so basically the option to minimize it will be hidden, unless I change this behavior.

Any comments on this @ccordoba12

**Comment by fordanic** [comment]
Not sure if relevant to add this comment here (let me know if I should post it as a separate issue). Will adding the maximize button to the panes/widgets help with the issue to allow panes/widgets to be treated as standard windows when undocked from the main window? For example, in Windows you can use Windows key + arrow keys to move around windows and to allow a window to occupy half the monitor or the full monitor. This is currently not possible.

**Comment by goanpeca** [comment]
@fordanic this will not handle that... are normal floating dockwidgets supposed to do that on windows?

**Comment by fordanic** [comment]
Supposed to that, not sure but on the IDEs that I'm used to working in on windows (MATLAB, Visual Studio), as soon as you undock a widget/window you can treat as standard window in terms of using Windows key + Arrow keys for moving it around.

**Comment by goanpeca** [comment]
When you float something in matlab, you see this floating windows as separate instances when doing `Alt+Tab`?

**Comment by goanpeca** [comment]
I would say that it is not possible in a straightforward way...

**Comment by fordanic** [comment]
Yes, when undocked then Alt+Tab is possible.

**Comment by Nodd** [comment]
That also means that the separate instances can be "lost" behind the main window ? There are many users having problems with matplotlib windows appearing behind spyder, maybe adding this is not a great idea...

**Comment by goanpeca** [comment]
@fordanic actually I managed to get the floating dockwidgets as you indicated, so it is doable, now @spyder-ide/core-developers should decide if this is something you would like to see implemented.

**Comment by Nodd** [comment]
What *something* ? @fordanic's proposal or the maximize button one ?

**Comment by goanpeca** [comment]
@spyder-ide/core-developers , do you think this is useful to do?

>allow panes/widgets to be treated as standard windows when undocked from the main window? For example, in Windows you can use Windows key + arrow keys to move around windows and to allow a window to occupy half the monitor or the full monitor. This is currently not possible.

Example look (variable explorer) to get the idea. Floating panes (dockwidgets) would behave as independent windows, so that they can be fitted to the screen (in windows so far using `Wndows Meta + Arrows`)

![image](https://cloud.githubusercontent.com/assets/3627835/7453154/9482b792-f266-11e4-80d1-4d199b02a496.png)

**Comment by fordanic** [comment]
Nice!

**Comment by Nodd** [comment]
Are you sure that you can put the redock icon on the windows titlebar ?

**Comment by goanpeca** [comment]
Hmm no I think not possible, in that case I hide the title bar and use the DokWidget QTitleBar...

**Comment by ccordoba12** [comment]
+1 from me! I think treating undocked panes as proper windows would be really useful :-)

**Comment by thewhitetulip** [comment]
Can't we have both? meaning a maximise, minimize, fullscreen trio?
maximize : will maximize within spyder's main window
minimize: will minimize within sypder's main window
full screen: will create an independent window out of spyder's main window.

While programming or at least while python programming, I rarely ever just go on writing code, so the `alt +  tab` feature albeit it is good when we have multiple monitors, newbies or people like me will run their code and it is rather annoying to `alt+ tab` every time you need to run a program.

Eclipse does this really well, we have multiple docked windows which you can't detach, but you can do a `Ctrl+m` and it maximizes within the window, then you get fullscreen to code, then `ctrl+m` and it is restored, then run the program as you want it, whilst eclipse is vestigial Java, we need to think in python programming terms, python is scripting, something really different from java, so sypder has python interpreters inbuilt, ergo if we are to dock it as a window, then let's keep that option of maximize button alive

**Comment by ccordoba12** [comment]
Having a minimize button would be really nice too. But on Rstudio it works for all panes that are tabbed next to each other.

@goanpeca, what do you think? Is it doable?

**Comment by thewhitetulip** [comment]
Personally I don't like the `alt+tab` concept, because not every Spyder user will have multiple screens for that feature, and I don't feel that goes well with the way python programming is done normally.

**Comment by Nodd** [comment]
A user can still use docked widgets on a single monitor.

**Comment by thewhitetulip** [comment]
Actually if you want only the fullscreen behaviour as to get more screen for your code to rest, then I feel the maximize inside the spyder feature is the perfect solution.

Making the core docks as alt+tab `windows` or whatever is the proper name for them is an overkill actually, I started this issue only because there was no minimize button for each pane.

I don't ever use the variable explorer and a bunch of other views, so rather than have them waste my screen space, I would have used the maximize button (or the minimize button if sypder had one), also having `alt + tab` window means a user has to do an `alt + tab` to check the terminal output, this defeats the purpose of using an IDE, because when I was new to programming eclipse blew my mind, no longer did you have to alt tab to your console to see the output, It saves a lot of time they said.

That being said it is individual's choice if to use docked or undocked windows, but I feel an IDE like spyder should not force a particular paradigm on the user.

An easier solution to this original issue would be to add a `minimize`, `maximize` and `close`, because the `undock` or `fullscreen` button is already present, and if you don't want to see the variable explorer, fine, minimize it, else close it completely, the maximum would expand the current dock into the entire window of spyder, note that it won't pop out the widget, and a close would be a normal close. 

Keeping a undock is good for people like yourself @Nodd  because you use multi screen of a horizontal monitor and don't lack vertical space! That is the way an IDE should be designed, it should be one program to rule them all, as generic as possible.

**Comment by goanpeca** [comment]
@thewhitetulip I think you got lost or misunderstood something:

Things that will be implemented
1.) Dockwidget titlebars can be hidden optionally, when locked if the user selects this options in the preferences. If the Pane title is hidden then the options will most likely move to the context menu of the tabs and/or to the menu of the Pane (the icon to the right... in most of the actual panes)
2.) While a pane is fixed in spyder (not floating) the user can either choose to
  - Maximize inside spyder, which is the normal behavior that spyder has right now
  - Float the pane, which is the normal behavior of spyder except now floating panes are also independent windows
 - Close a pane, same what spyder is doing right now
3.) Floating panes as separate windows does offer advantages and people are free to Float them or not that is what @fordanic suggested and what I tried to implement in an image 10 messages above this one. When a pane is floating the pane title will be most likely hidden if everything works as expected in ubuntu and mac.

**Comment by thewhitetulip** [comment]
Okay, sounds great :+1: I got lost and confused :smile:

**Comment by goanpeca** [comment]
There is no minimize concept for a panes, so what do you suggest?

**Comment by ccordoba12** [comment]
See my https://github.com/spyder-ide/spyder/issues/2272#issuecomment-98854023 above :-)

**Comment by Nodd** [comment]
What does it do ? Only show the titlebar ? (which can be hidden in spyder...)

**Comment by ccordoba12** [comment]
The minimize button in RStudio collapses all panes tabbed together and only shows their titlles in a simple tabbar.

I don't know if that can be done in Qt :-)

**Comment by thewhitetulip** [comment]
As @ccordoba12 said that can be done, but if a minimize button is added we would need to show some indicator like eclipse or Rstudio do

**Comment by goanpeca** [comment]
@ccordoba12 @thewhitetulip the minimize button concept may work... but I think it is not really worth it. We have custom layouts so the users can organize the panels as they want and switch between this layouts.

I would say it is too much unnecessary work to make sure everything works as it should.

So I am :-1: on minimize functionality

**Comment by thewhitetulip** [comment]
Okay, I don't have any experience building GUI based applications so can't really comment on functionality, as far as designing webapps is concerned, it isn't a big deal to add one more button, if it is too much unnecessary work then your call.

**Comment by goanpeca** [comment]
@thewhitetulip the thing is that Spyder allows too much freedom for users on how to organize their windows by docking and undocking things and this flexibility provides for most user needs. The problem with having a minimize function is that...

1. What is the use, if you can define your layout, maximize and close panes already?

1. There is no concept for minimizing a pane that is alone, meaning with no other pane locked in the same position, because there is not even a TabBar at the bottom of this pane. This is how At works with panes (dockwidgets)

1. Now for the rest of panes that are grouped with more than one pane in it, the concept might work, except you need to check if there are panes above or bellow the current dockwidget. For instance if you have only editor pane to left and the rest of panes two the right (Two vertical panes) if you would try to minimize the panes to the right it cannot be done or work cause they share the same ROW in spyder, o minimizing one will affect how the other pane looks.... so the only possible situation where having a minimizing function would be when there are two or more rows of widgets and event then there would be too many check to see what should be done or not.

1. I tried to implement the code for the previous case and it was not really performant and would lead to a lo of problems trying to get it to work right.

Finally Spyder is not a webapp is a Qt app, and it has limitations, that are imposed but how Qt works. Work of implementing something is always way beyond adding or not a button or a widget.The thing is that there is a native behavior for dockwidgets (panes) that includes only floating and closing (That is all Qt gives.). Adding the maximize button is already adding something that Qt does not add by default and required an extensive amount of boiler plate code just because dockwidgets are not meant to be used like that. 

A minimize functionality would require for dockwidgets to play well with the concept itself which they do not at all. Dockwidgets are tied to their neighboring dockwidgtes, in the column level and in the row level.

**Comment by thewhitetulip** [comment]
>Adding the maximize button is already adding something that Qt does not add by default

In this case it would be besides the point to add a minimize button, the thing is the trio of minimize, maximize and close go hand in hand from the UX point of view, but as you said, spyder already provides the user with extensive options as to organizing the desktop, then it would be of little use to provide a minimize button considering that even maximize isn't provided by Qt, as you rightly said it would add too much of code and it would be pointless.
