### ISSUE TITLE
Plots still now showing up in spyder 6.0.2

### ISSUE THREAD

**Issue by Vladislav-Jovanov** [spyder-ide/spyder#22832]
So I switched to version 6.0.2 and the plots are still not displayed.

They show up as:
\<Figure size 864x576 with 1 Axes\>
OS is Linux Mint 21.3 Virginia 64-bit
Kernel Linux 5.15.0-124-generic x86_64
MATE 1.26.0
Python 3.10.12
matplotlib                    3.9.2
matplotlib-inline             0.1.7
PyQt5                         5.15.11
PyQt5-Qt5                     5.15.2
PyQt5_sip                     12.15.0
PyQtWebEngine                 5.15.6
PyQtWebEngine-Qt5             5.15.2

**Comment by Vladislav-Jovanov** [comment]
It seems that I do have spyder-kernels 3.0.1 but plots doesn't show

**Comment by ccordoba12** [comment]
Ok, please run these commands in the IPython console and post the output here:

```
In [1]: ip = get_ipython()
In [2]: ip.events.callbacks
```

Also, please post a simple code of the plot you're trying to generate.

**Comment by Vladislav-Jovanov** [comment]
I hope I did it right. Here is the output

{'pre_execute': [<bound method InteractiveShell._clear_warning_registry of <spyder_kernels.console.shell.SpyderShell object at 0x7f2c2350db10>>],
 'pre_run_cell': [<bound method AutoreloadMagics.pre_run_cell of <IPython.extensions.autoreload.AutoreloadMagics object at 0x7f2c235836a0>>],
 'post_execute': [<bound method SpyderShell.do_post_execute of <spyder_kernels.console.shell.SpyderShell object at 0x7f2c2350db10>>,
  <function matplotlib.pyplot._draw_all_if_interactive() -> 'None'>,
  <function matplotlib_inline.backend_inline.flush_figures()>,
  <bound method AutoreloadMagics.post_execute_hook of <IPython.extensions.autoreload.AutoreloadMagics object at 0x7f2c235836a0>>],
 'post_run_cell': [],
 'shell_initialized': []}

**Comment by Vladislav-Jovanov** [comment]
Sorry. I didn't see the part about the code example. Here it is.

import numpy as np
import matplotlib.pyplot as plt

w=2*np.pi*13.5e6;
cr=np.linspace(100e-12,500e-12,501);
cp=(1/500e-12+1/cr)**(-1)+100e-12;
xc=1/(w*cp);
xr=1//(w*cr);
plt.plot(cp,xc);
plt.plot(cr,xr);
plt.show();

I checked the settings in the spyder and it uses inline option. If I switch to automatic of Qt a plot pops up but it doesn't show anything and I have to force quit it. I installed spyder 6.0.2 via pip install spyder --user --upgrade

**Comment by ccordoba12** [comment]
Thanks for the script @Vladislav-Jovanov. I don't see anything strange in it.

However, you also said:

> I installed spyder 6.0.2 via pip install spyder --user --upgrade

That's actually not good because you ended up mixing your Linux distro Python packages with the ones installed by pip, and they are binary incompatible.

To fix this conflict, please remove the directory (or directories) where pip installed its packages by opening a terminal and running

    ~/.local/lib/python*

and then follow [our docs](http://docs.spyder-ide.org/current/installation.html#using-pip) to install Spyder in a virtualenv.

That should solve your problem.

**Comment by Vladislav-Jovanov** [comment]
It did. Thanks.

**Comment by Vladislav-Jovanov** [comment]
Thanks. I already installed all needed packaged in the virtual environment. I also made launcher for spyder from that virtual environment. Maybe launcher can be added to the installation from pip so users don't need to do it themselves.

**Comment by ccordoba12** [comment]
Thanks but we have our own installers for Windows, Linux and Mac which come with that functionality already.

Installing with pip is meant for power users because it's quite easy to break your env with pip

**Comment by JaccoHoogewoud** [comment]
same kind of issue here:
I installed spyder via windows, and used python from a different location
![afbeelding](https://github.com/user-attachments/assets/7fb38586-bbec-4801-ba06-2e0fd91a69d4)
spyder asked me to install a spyder kernell:
![afbeelding](https://github.com/user-attachments/assets/bc698128-f50f-41ad-8f5b-6b230c8e813a)
I did....
![afbeelding](https://github.com/user-attachments/assets/99426da4-b79f-4815-bcfb-2a13d3269e73)
And now plots are not displayed in spyder...

I get: `<Axes: ><Figure size 864x576 with 1 Axes>` instead of a plot

**Comment by ccordoba12** [comment]
As I suspected, you used pip to install Spyder-kernels in a Conda environment. Since pip and conda packages are binary incompatible, most probably you broke your environment and now you have to recreate it.

Given that Anaconda is always behind our latest releases, and that you need to have Spyder-kernels 3.0.1 due to the Matplotlib bug, I suggest you to use Conda-forge for that (because it's always up to date):

    conda create -n imodenv-1 -c conda-forge python=3.10 spyder-kernels matplotlib <add here all packages that you need for your work>

and then connect to this env from the standalone Spyder version, as you showed above.
