### ISSUE TITLE
An error occurred while starting the kernal

### ISSUE THREAD

**Issue by grantboxer** [spyder-ide/spyder#23080]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

### What steps reproduce the problem?

1. In Anaconda Navigator, select env
2. run Spyder
3. Cannot start kernel
4. 
5. 

### What is the expected output? What do you see instead?
Kernel should run

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @grantboxer, thanks for reporting. This problem is usually caused by installing Numpy, or a package that depends on it, with pip in a conda environment. Since pip and conda packages are binary incompatible, they can't be mixed in the same environment.

To solve this problem, I'm afraid you'll have to remove and reinstall Anaconda. To properly do that, please follow the instructions in the second part of [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) about that (the first part describes why you can't mix pip and conda packages).

**Comment by grantboxer** [comment]
Thanks Carlos,

 

Will try that. I wondered why things stopped working!

 

Cheers Grant
