### ISSUE TITLE
Plot tab haven't shown chart

### ISSUE THREAD

**Issue by harveynguyen09** [spyder-ide/spyder#23276]
I got issue for the Plot.
I run my code without any error but the "Plot" tab haven't shown any chart
<img width="959" alt="image" src="https://github.com/user-attachments/assets/26dee8c3-04e6-4a69-9b9d-0820249371e1" />

**Comment by ccordoba12** [comment]
Hey @harveynguyen09, thanks for reporting. As you can see from the output messages in the IPython console, `yfinance` was not able to download the data to plot. So, the plot is empty.

I don't know how to help you with that, but you can ask for help about it in

https://github.com/ranaroussi/yfinance

Since this is not an internal Spyder problem, I'm going to close it.
