### ISSUE TITLE
Enhancement: Add a 'dev' menu with common actions useful in development

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#2339]
I know this might not be useful to all contributors/developers out there, but in the specific case of people using Spyder to develop Spyder I suggest we include a new `Development` Menu that includes actions useful when developing Spyder.

Some things that could be included:
- An action to open a signal tracker panel, as discussed in #1421 
- Tools for using the translation scripts plus opening PoEditor when needed
- Actions to automate the packaging and release of Spyder (leveraging the scripts that are floating in the repo... by the way these scripts should be moved to the scripts folder)
- ...

**Comment by Nodd** [comment]
I'd prefer have a clean set of scripts for this rather than adding a new menu:
* It's better to separate production code and development when possible
* I regularly use the master version for daily use to be able to catch eventual bugs. There are already enough menus and submenus, thanks.

If it is implemented, it could be a new submenu in the help menu, it would be less intrusive this way.

**Comment by goanpeca** [comment]
Ok it can be hidden in the help menu if it makes you happier, but of course this is not intended for people that feel comfortable on the cmd prompt as @Nodd is.

**Comment by Nodd** [comment]
RIght, I find developing on windows so horrible that I forget other people do it anyway!

Counter-proposal: include this in a new external plugin. This way you're not limited to a menu and you can include any widget. The signal tracker could be either integrated in the plugin or set as another plugin.

Anyway, :+1: for the functionnality.

**Comment by goanpeca** [comment]
Until @ccordoba12 rolls ou the new plugin hook interface for spyder, I will not endeavor in making new plugins ;-)

**Comment by Nodd** [comment]
Yes, it would be a new-style plugin !

**Comment by ccordoba12** [comment]
@goanpeca, I do most of the actions you mention on the command line. So the only valuable action I see for this new menu would be the signals explorer.

Besides, since creating new releases or updating translations is not that frequent either, I don't think it's worthy to add them to a new menu.

What I could do is add more scripts to make these processes easier and simpler to do :-)

**Comment by techtonik** [comment]
Well, as an author of original Signal Tracer idea in #881and #1421, my vision was that it is hidden in a Help menu near "About Spyder.." to make it clear that it is some internal stuff. It should be named after the word "Internal Stuff", but not "Development", because Development is too abstract.

The menu items "Optional dependencies.." and "Report issue.." should also go there, as well as documentation links should be grouped.

Right now I can not think of anything better than Help -> "Spyder internals..." name for submenu. I don't think it should be an external plugin for now.
