### ISSUE TITLE
Release binaries as wheels

### ISSUE THREAD

**Issue by mikofski** [spyder-ide/spyder#2375]
The Windows installer binary distribution is deprecated. Please release Spyder as a [wheel](http://wheel.readthedocs.org/en/latest/). The only advantage of `bdist_wininst` is that it calls `spyder_win_post_install.py` and creates the variables used by it. The Windows post install file for Spyder creates the desktop and start menu items, but it also creates unnecessary registry entries whereas wheel files are installed by pip independent of Windows. The functions in `spyder_win_post_install.py` could be pulled into setup.py by applying issue #2188 .

**Comment by ccordoba12** [comment]
There are several things here:

1. Windows installers are easy to run and provide a GUI to install. Wheels are installed only through pip using a terminal (yikes on Windows :-)
2. `spyder_win_post_install.py` **doesn't** create unnecessary registry entries. Those entries are necessary to open Python files through the Windows file explorer.
3. We could release wheels along with our current installers, but we are not going to do the work for you. If you want this to happen, please open a PR (as I told you on issue #2188), and help us to make it happen. I'm perfectly fine with how things are right now, and I don't have time to dedicate to this, so it's up to you :-)
4. If you don't want to do it, or don't have time, please stop complaining about it :-)

**Comment by mikofski** [comment]
Sorry for complaining. In retrospect, I don't think it's necessary to release Spyder as a wheel, since it has no binaries. Spyder can be installed with pip just as it is, but it would be nice if I can get #2188 done. I've started working on it, but I have a question whether or not PyWin32 can be used. I'll close this issue as unnecessary.

FYI on windows, most users will have to use pip or conda to install most of the packages required for Spyder anyway.

**Comment by goanpeca** [comment]
We are trying to keep the user xp nice, so we have a GUI Conda Package manager that works as standalone and as a plugin inside Spyder itslef.

**Comment by guyverthree** [comment]
Hey Guys, I'm wrapping spyder up into a wheel for my own purposes (basically I'm looking to create wheels of many packages and use them for really fast installation in requirements.txt) so far this has just been a change in the setup.py to use setup tools since Wheel just packages this into a image for installation later as far as i am aware, once installed is there a set of unit tests that I can run. on it ? so that i can verify that the packaging is working as intended.
I know there are other packages that will require installers i'm just looking to streamline the process as much as possible, and have only a single installation method for many packages.

**Comment by mikofski** [comment]
@guyverthree you can use [wheel's `convert` command](https://wheel.readthedocs.org/en/latest/index.html#usage) to convert a bdist_wininst to a wheel:

    me@computer ~/Downloads $ wheel convert spyder-2.3.5.2.win-amd64-py3.4.exe

See [my post on NumPy wheels](http://poquitopicante.blogspot.com/2014/10/numpy-in-virtualenv-on-windows-x64-with.html).
