### ISSUE TITLE
Spyder is not displaying Matplotlib 3d plots in its Python consoles

### ISSUE THREAD

**Issue by s0r2637** [spyder-ide/spyder#2402]
I tried the following set of commands in the Spyder-2.3.4 console and it doesn't display a 3d plot.  It works fine when I run it outside Sypder-2.3.4.  Your help is highly appreciated.

```python
import numpy
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Set up grid and test data
nx, ny = 256, 1024
x = range(nx)
y = range(ny)

data = numpy.random.random((nx, ny))

hf = plt.figure()
ha = hf.add_subplot(111, projection='3d')

X, Y = numpy.meshgrid(y, x)  # `plot_surface` expects `x` and `y` data to be 2D
ha.plot_surface(X, Y, data)

plt.show()
```

**Comment by ccordoba12** [comment]
What console are you using? Python or IPython?

**Comment by s0r2637** [comment]
Python.

Srini

**Comment by ccordoba12** [comment]
For next time, please the *Report bug* menu entry, under the *Help* menu :-)

Are you using Python 2 or Python 3?

**Comment by s0r2637** [comment]
Sure. I will do that.  I am using Python 2.7

Srini

**Comment by ccordoba12** [comment]
I can confirm this problem. We'll see what we can do about it :-)

**Comment by ccordoba12** [comment]
This is not an error in Spyder. You just need to use

    plt.draw()

instead of

    plt.show()

as the last line of your example to make the plot appear.

Here is an explanation of the difference between the two:

http://stackoverflow.com/a/23141491/438386

Given that in interactive mode (i.e. introducing each command at a time), you generate an empty figure first (with `hf = plt.figure()`), I think you need to call `plt.draw()` to redraw it later.

**Comment by s0r2637** [comment]
Thanks!  I will look into this.

Srini
