### ISSUE TITLE
Easy way to collapse code

### ISSUE THREAD

**Issue by thewhitetulip** [spyder-ide/spyder#2430]
While browsing through a really long code it would be awesome to be able to collapse code with a button, and also a collapse all function feature if it doesn't exist, I am not aware if it does

**Comment by goanpeca** [comment]
You mean code folding? there is work on way and this is then a duplicate if so...

**Comment by thewhitetulip** [comment]
Yes, having a small plus icon on the place where we show line numbers

**Comment by zeluspudding** [comment]
Is ANY one working on code folding? I've been using spyder for 2 years and this NEEDS TO EXIST

**Comment by ccordoba12** [comment]
Yes, one of our juniors is working on it. It'll be present in Spyder 4 (to be released in August of next year :-) because we need to refactor and rewrite several parts of the Editor.

But it'll probably land be in master before the end of this year :-)

**Comment by maxborn** [comment]
A code editor without code folding is only good for small projects. This should be given a higher priority if you ask me.
Thanks for listening anyways.

**Comment by ccordoba12** [comment]
It's already implemented and it'll be released in Spyder 4.

**Comment by maxborn** [comment]
Hi Carlos, thanks for the quick reply. Is there a way to become a beta or alpha tester and have access to Spyder 4 without waiting for the official release? I could really use it. By the way, I didn't meant to be rude with my previous comment, it’s just that I'm in the process of switching from Matlab to Python, and after a relatively thorough search and analysis of most popular Python IDEs, Spyder was the best I could find for Scientific applications. I started using it, but soon notice how important code folding is, and how accustom I was to it (most programmer probably are). I really try to live without it, but couldn’t. Right now I’m using PyDev, but I haven’t use it much. If I could get my hand on Spyder 4 it will be great. Otherwise, I’m afraid by the time it is officially out, I’ll be already accustomed to PyDev and never take the time to switch to Spyder. Probably there are many people in similar cituations. Thank for your attention to this.
Regards.
Max.

**Comment by GershTri** [comment]
I use the outliner and the file switcher to navigate longish scripts and haven't really missed code folding that much, although I'm sure it will be useful once it's there. The outliner gives you a decent bird's eye view of the structure of the code and allows you to jump to cells, functions, loops, etc. The file switcher lets you switch between files and parts of files. They might help you bridge the time left until version 4 is released.

**Comment by maxborn** [comment]
I'll try that. Thanks.

**Comment by Tych0n** [comment]
As GershTri suggested to use outliner, some may find useful to use triple hash - ### to make links in outliner to just some particular point in code.
![screenshot from 2017-07-30 10-46-37](https://user-images.githubusercontent.com/3283584/28751608-fec58516-7514-11e7-9ba0-aaceed94cc19.png)

**Comment by nimishbansal** [comment]
someone had said above spyder 4 will release in aug 2017 with code folding. Is spyder 4 out?

**Comment by nimishbansal** [comment]
omg is there no other way that I could run before release?

**Comment by mprel** [comment]
Agreed with all above. No collapsible regions will only make due for small projects. So Spyder IV is set for a few months from now?

**Comment by ccordoba12** [comment]
One year, if things well.

**Comment by AdrienMau** [comment]
If :)

**Comment by lkallryd** [comment]
Does Spyder 4 work together with Python 2.7 or is the Python version irrelevant to the Spyder version? Code folding would be a great feature I agree.

**Comment by ccordoba12** [comment]
Yes, Spyder 4 will be compatible with Python 2.

**Comment by 1NilayPatel1** [comment]
I love spyder but deeply upsetting that 3.5+ years after this was first mentioned in this post, we still do not seem to have a solution for this.

I understand that it is a free software and so grateful of all the effort behind it, but it gets to a point where one wonders how such an integral feature can be missing.

**Comment by ccordoba12** [comment]
> we still do not seem to have a solution for this

There's a solution already, it was implemented a year and a half ago and it'll be part of Spyder 4, to be released next year.

However, you can install our first beta, which already has it:

https://github.com/spyder-ide/spyder/releases/tag/v4.0.0b1

**Comment by JohnRobson** [comment]
I hope to see Folding Code this year, is hard to work with big projects.

**Comment by skviknesh** [comment]
Spyder 4, is never released. Seriously! I tried installing spyder 4.0.0b version which is completely a failure each time. It dosen't even connect to kernel. and lots of other stuff......

**Comment by JohnRobson** [comment]
@skviknesh  I'm using version 4.0.0.dev0, which is working OK, but it can be improved.

**Comment by VikneshSK** [comment]
> Spyder 4, is never released. Seriously! I tried installing spyder 4.0.0b version which is completely a failure each time. It dosen't even connect to kernel. and lots of other stuff......
> 
> I don't get any installation guides too....
> I found all installation guides which is not a right way to install it completely.
> Can you write a blog/ suggest which way of installing, installs it better?

I have updated after the new release, now its really cool! right now, i have 4.0.1

**Comment by bclrk** [comment]
I am running 4.0.1, downloaded through conda, and it's working well. However, I still cannot collapse cells! only loops.

**Comment by matssnaps** [comment]
Same here, any news on when will a manual selection of lines of code be collapsable?

**Comment by Sue-Fwl** [comment]
Collapsing blocks of comments and regions/cells is something very essential, which I hope we seen soon in the next release!

**Comment by ccordoba12** [comment]
This was already implemented in Spyder 4 and it's been available since December 2019.

However, code folding markers are hidden by default due to performance reasons (this is the same in VSCode). To show them you need to hover the mouse to the left of your code, as is shown below.

### Default view

![Selección_100](https://user-images.githubusercontent.com/365293/93352673-b47cfd00-f800-11ea-9c8b-761c973fbe73.png)

### Hover to show folding regions

![Selección_101](https://user-images.githubusercontent.com/365293/93352722-c199ec00-f800-11ea-9bfa-c82afbf75d67.png)
