### ISSUE TITLE
Error evaluating cells with empty lines

### ISSUE THREAD

**Issue by j-chacon** [spyder-ide/spyder#2440]
Hey im having some issues while evaluating cells if there is an empty line just before the else statement. When this occurs, I get an unexpected indentation error.

``` python
#%%
a = False

if a:
    print('a is true')

else:
    print ('a is false')
```

Now if the blank line before the else is removed, then it works fine.

Can anyone fix this? :)

Greetings!
Juan

**Comment by ccordoba12** [comment]
This only happens in our Python Console, not in our IPython one. That's because our Python Console can't handle multiline statements but the IPython ones can.

So for now you can use our IPython consoles to keep working :-)

----

@SylvainCorlay, could you take a look at this one? It shouldn't be that hard to solve because this only requires removing blank lines present in a cell before sending it to the console.

**Comment by SylvainCorlay** [comment]
Ok I will fix this sometimes this week.
Cheers
S.

**Comment by j-chacon** [comment]
Awesome guys!

Thanks a lot

**Comment by ccordoba12** [comment]
To solve this correctly we need to create new `run` functions (or extend `runfile`) to run only portions of a file. They will only be necessary for the Python console.

IEP has something like this functionality already.

**Comment by ccordoba12** [comment]
I mean, these functions will avoid the need to evaluate a cell line by line, which is the current approach.

This is brittle and prone to fail, as this bug shows.

**Comment by goanpeca** [comment]
@ccordoba12 can you put some pointers here on what to do? file urls etc...?

**Comment by ccordoba12** [comment]
Closing because the Python console is going to be removed in Spyder **3.2**.

Please see issue #4524 for our reasons to do this.
