### ISSUE TITLE
Design for Projects in 3.0

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#2460]
I'm opening this issue to discuss how our Projects support should be improved in 3.0.

My main idea is to follow how RStudio handles projects, i.e.

1. Projects are **not** mandatory, as in other IDEs. Spyder must work without the need to create a project, i.e. as it works right now.
2. Projects save the state of open files in the Editor. In future versions we can add the ability to restore the state of Python/IPython consoles, but this is not necessary for a first implementation.
3. Projects are created through a toolbar like plugin, like our Working Directory one. There users find several menu entries:
    * Create a new project
    * Open a project
    * Configure the current project
    * A list of the last 10(?) opened projects
4. Users can only open one project at a time. This is a limitation over our current design, but I think it easies how RStudio handle projects.

Things to consider:

1. We need to decide what to do with our Project Explorer widget. Should we keep it or remove it? RStudio doesn't have one, I think because it's almost identical to the File Explorer one.
2. What options should be configurable for a project?
    * Conda/Virtualenv environments (for sure).
    * What else? Syntax highlighting? Space indentation?

**Comment by ccordoba12** [comment]
Pinging @goanpeca for discussion. I don't know if other @spyder-ide/core-developers want to join in ;-)

**Comment by ccordoba12** [comment]
For reference, this is the doc page where RStudio projects are described

https://support.rstudio.com/hc/en-us/articles/200526207-Using-Projects

**Comment by goanpeca** [comment]
Hi @ccordoba12, good, this way is better so I can start a PR with some milestones ;)

On your points:
1.) Agree
2.) Agree
3.) Hmm here I am not so sure a toolbar would be the best solution... We could also consider a statusbar widget that would work as a combo box for this?, some people disables toolbars (although some people disables the status bar as well)
4.) It is true that it would make our life easier, but at some point users will most likely wonder how to open 2 or more projects at the same time. I think is doable so I will leave an open door for this, even if in this first iteration it is not done

Things to consider
1.) Well this depends on the support we would like to have for future projects. Also we had talked at some point of merging the outline explorer and the project explorer into a single widget.
2.) I think we can have something like (pycharm)[https://www.jetbrains.com/pycharm/help/creating-projects-from-scratch-in-pycharm.html] If conda is installed, it should display the conda envs available and give support to create new ones, otherwise if virtualenv is installed it should give support for that as well.

**Comment by goanpeca** [comment]
I forgot to mention....

We can add support for http://editorconfig.org/, I would like to see the spyder logo in there! http://editorconfig.org/#download

Things to agree on...
1.) The format to store information. I guess we can keep using .ini file as the rest of the spyder infrastructure.
2.) I want to use a project folder (.spyproject) to store any projects related config. We could use a single file but having a project would give us way more flexibility for future enhancements, than keep adding things to a single file. Example https://www.jetbrains.com/pycharm/help/project.html . 

We can have a folder AND a project file so that it can be associated to spyder (double clicking on thin file would open spyder and the given project). Also for instance when implementing the session recovery the information on the session should be stored somewhere and this folder would be the best option to stop polluting the project folder. Anything related to projects that can or could be configured in spyder should go into this hidden folder,

```

\project_name\
    .spyproject\     -> Spyder project folder, anything related to the project conf and handling
        workspace.ini
        vcs.ini
        conda.ini
        venv.ini
        ....
   project_name.spy   -> Spyder project file, double click should open the project in spyder
   ...
```

**Comment by bilderbuchi** [comment]
Some points:
* Please consider moving the project/workspace files away from a binary format, towards a textual format - this would make sane handling in a version control system possible.
* When designating contents for your project folders, please separate (semi)permanent data files (e.g. run configuration) from files with ephemereal/often-changing content (e.g. window/tab positions, timestamps,...) - that way the often-changing files with content of probably secondary importance can be ignored in the version control system, significantly reducing the VCS noise from the project files - right now you have updated binary project files on every close/reopen of Spyder, but no idea what changes and why.
* Ideally, separate user-specific config (e.g. window position) from project-specific config (e.g. run parameters) into different files, which would significantly assist in sharing projects between several collaborators.

For all points, I think it would be instructive to look at how XCode (MacOS) handles projects. While I don't use it, personally, I have in the past had the pleasant task to come up with a [proper gitignore scheme](https://github.com/openframeworks/openFrameworks/blob/master/.gitignore#L47-L55) for a project, including XCode among other IDEs, and I have to say it really makes sense.

**Comment by goanpeca** [comment]
@bilderbuchi 

Thanks for the input,

To your points:
- We are moving to text based only *.ini which is what spyder uses internally
- That is the main reason I am in favor of having a folder with several files as opposed to a single file, so thumbs up!
- The idea is to include by default gitignore/hgignore files by default when creating projects (and using vcs) to only track files that make sense to track :)
- We are probably moving away from the "Workspace" word ;-)

**Comment by goanpeca** [comment]
![image](https://cloud.githubusercontent.com/assets/3627835/7932380/294a0660-0918-11e5-89fd-fcddfa49616a.png)

Not much, but getting things in motion

**Comment by Nodd** [comment]
@bilderbuchi :+1: That's exactly what I was going to write.

Also about opening only one project at the same time, I think it's OK *if* it is possible to open another project in another spyder window, and if it's easy to do (like right-click on a project's name > open in a new window).

**Comment by ccordoba12** [comment]
@goanpeca, great start! Keep the good work up! :-)

About my initial points:

3.) Let's go then for a main menu entry to start with, i.e. a *Projects* menu, next to *Consoles* and before *Tools*.
4.) Let's go simple on a first implementation, i.e. only show one project per session. But, as you said, we should try to design things to make it easier to add multiple projects later on. Also, if that's the case, we should maintain the Project Explorer because it'd make sense to show several projects at the same time there (as other IDEs do :-)

----

About using a dir instead of a file for project config:

* On  second thought I think it makes more sense, specially to version control it. I mean, things like the list of open files are transient and if we save them in a single file, they'd just add noise when vcs'ing the project file.
* It'd also let us follow @bilderbuchi suggestion about separating config in several files, which I like too :-)

----

A final suggestion: we could use the Project Explorer to present a type-based structure for the project, instead of a file-based one. By this I mean that that widget could show a view where all IPython notebooks are grouped under one *fictitious* dir, all Python files under another, all data files (csv, txt, etc) under yet another one, etc.

This is just a suggestion to explore what we could with the Project Explorer, but it's not important for a first implementation :-)

**Comment by goanpeca** [comment]
Ok, I will add the menu and create a new preferences dialogue for projects based on the existing general preferences dialog @ccordoba12.

I have to do some tweaking with the UserConfig to generalize it and make it usable also for this case.

**Comment by goanpeca** [comment]
About multiple projects, not sure how other IDEs handle it, but from a Spyder point of view, we could think of adding some color to the editos tabs to distinguish between project files and non project files.

I could open 2 projects at the same time and a random python script. Individual files will behave according to the project they belong to. This would require that projects cannot be nested.

**Comment by goanpeca** [comment]
Having a new Spyder Editor will not work, cause all files between editors are in sync so they have to display the same files. The "easier" solution would be, in case a project is open and one wants to open in a new one, then a new (and independent) spyder instance should launch.

**Comment by bilderbuchi** [comment]
> use the Project Explorer to present a type-based structure for the project, instead of a file-based one. By this I mean that that widget could show a view where all IPython notebooks are grouped under one fictitious dir, all Python files under another, all data files (csv, txt, etc) under yet another one, etc.

Personally, that would be too much "magic" for my taste. Hiding irrelevant stuff by default (e.g. `.git` directory, `~` backup files) is alright most of the time, but creating virtual file structures would be too much imo. if the user wants a directory structure, why not create it herself?

**Comment by ccordoba12** [comment]
@goanpeca said:

> I have to do some tweaking with the UserConfig to generalize it

Ok, but be very careful with that. We have a lot of logic in UserConfig to deal with several updates and changes to our config files and dir during the years.

> About multiple projects, not sure how other IDEs handle it, but from a Spyder point of view, we could think of adding some color to the editor tabs to distinguish between project files and non project files.

That's where things get complicated quite easily. So multi-projects should be left for a future PR.

----

@bilderbuchi said:

> Personally, that would be too much "magic" for my taste

Ok, it's just an idea, and it could be implemented in an optional way. It's quite useful in C/C++ projects to magically separate headers from source files. So it could be useful to do data analysis projects too :-)

**Comment by goanpeca** [comment]
@ccordoba12 sure, I am being extra careful. I added just an extra check so that a custom filename can be used instead of the default filename method, which assumes a lot of things and renamed the `__` methods to `_` so that I can inherit and have a `ProjectsConfig(UserConfig)`.

Multiprojects: yes that was just some random thought, I am assuming single-projects for now.

**Comment by goanpeca** [comment]
@ccordoba12 what do you think of adding a statusbar widget that displays the current project, or none if no project?

**Comment by ccordoba12** [comment]
I think the project name should be shown in the title bar. I find it more appropriate there :-)

**Comment by goanpeca** [comment]
You mean Spyder 3.0.0 (Python 2.7) - Project: Name

**Comment by ccordoba12** [comment]
Yep. Too crowded?

**Comment by goanpeca** [comment]
Hmmm, nope, I think is ok

**Comment by ccordoba12** [comment]
:+1:

**Comment by goanpeca** [comment]
I have a working version now of the project preferences that is linked to the individual files storing the info. I just used the values from R for the general options (so don't take them too seriously)

![image](https://cloud.githubusercontent.com/assets/3627835/8039909/11c50a54-0e0d-11e5-9402-46ab31659ef1.png)

I would like to hear some input of what should be the configurable options for the project preferences. The way the current project preferences dialog work is that each section in the left corresponds to a file (so in this case, `spyproject/workspace.ini -> General` and `spyproject/vcs.ini -> Version control`. This makes the handling of config files right now easy, but it can be changed so that the options in a section (General, Version control) can be split among several files if so needed to make vcs better.

Now some ideas on options.

## General
- (checkbox) Restore data on startup (eventually with [dill](https://pypi.python.org/pypi/dill))
- (checkbox) Save data on exit (idem)
- (checkbox) Save history (Save the history.py inside the .spyproject folder so general history and project history can be kept separate?)
- (checkbox) Save state of non project files opened? (I dont know if this useful or not. Project files are files under the root dir, so if you open another file while working on a project we can choose to save that state or not)

## Code Style
- (combobox) Indentation (2,3,4 spaces, tab)
- (combobox) Encoding (utf-8.....)
- (combobox) Line endings (lf, cr, lfcr?)
- (checkbox + spinbox) Vertical line (79, etc...)
- (checkbox) Automatically remove trailing spaces when saving files
- (checkbox) Automatically add an empty line at the end of file when saving files
- ???

## Version control
- (checkbox) Use version control
- (combobox) Version control system (git/hg, giving priority to git, and not necessarily in this first iteration)
- ???

## Environment (conda virtual env?)
- ???

**Comment by Nodd** [comment]
> Having a new Spyder Editor will not work, cause all files between editors are in sync so they have to display the same files. The "easier" solution would be, in case a project is open and one wants to open in a new one, then a new (and independent) spyder instance should launch.

This is what I meant by a new window, I think it's fine.

About settings, maybe the version control and environments settings can be left for later. Those are new things compared to the current version of spyder. The first step is to adapt the current features to projects. I guess it will be a gigantic PR already !

For options, you can add:
* Python executable
* Working directory

**Comment by dougthor42** [comment]
Will having items inside a project allow for project-wide refactoring a-la PyCharm?

For example: have a project open, press F2 on your method definition and hit Rename. All references to that method within the project are then changed to the new name.

Or is that kind of feature outside the scope of this PR?

**Comment by goanpeca** [comment]
Projects will allow for that. But refactoring feature will be another PR

**Comment by bilderbuchi** [comment]
regarding the line ending setting - this could be a bit complex, as this typically depends on the platform you use spyder on (so could change continually if several people share a project, or you share one betwen machines). also, line endings are ideally handled by your VCS in a sane way (e.g. only commit LF endings into a repo, but be transparent to the user, the way git offers with .gitattributes). I'm not sure this should be configurable, as it's easily mis-configurable - maybe in an "advanced" section?

regarding line length at 79, and indentation width - be careful that this does not clash/become unsynchronized with what pep8 does for you - ideally I guess some of these settings come from a pep8 config file. cf. also #2359.
