### ISSUE TITLE
Matplotlib Gtk backend is broken in Python consoles

### ISSUE THREAD

**Issue by anderwm** [spyder-ide/spyder#2471]
Starting with 10312, the standard console starts with warning :
(process:4958): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Pressing enter gets me the prompt, but none of my keystrokes appear.  Also, there is no option for Ipython console (which was available before 10312).  Am I the only one seeing these kinds of problems?  I am on Ubuntu 15.04

**Comment by ccordoba12** [comment]
There's no revision **10311**, I mean that don't correspond to any git hash. Please report the right revision.

Besides, master has moved to support only IPython version 3 or higher. That's probably the reason you're not seeing it.

**Comment by anderwm** [comment]
Sorry Carlos, I still use mercurial on my machine and pull with hg-git, I forgot the revision numbers are all changed.
You are right, it is the master branch that presents my issue.  I understand the IPython version restriction, but the internal console still seems like a bug.  Or at least some dependence that has changed from the 2.3 branch.  The console is not usable, as it seems the keystrokes are hijacked.  If your not ready for this kind of feedback yet on master branch I understand that and will continue using 2.3.

**Comment by anderwm** [comment]
The Locale not supported warning isn't related and begins on Merge pull request #2349 from goanpeca/language: Add support for language selection in preferences
commit 79242c45406bac02ffa0ae41066248903a0a691e

The console problem begins with
Python Console: Fix plotting with the Qt4 backend
Fixes #2231
commit 6bbd031d2b5714923a2322c7fe5aeaae41e3307c

**Comment by goanpeca** [comment]
Hmm, ok I will take a look

**Comment by ccordoba12** [comment]
@goanpeca, the problem is `en` is not recognized as a valid locale. I think you need to set as a default `en_US`. See this post for more info:

http://askubuntu.com/questions/359753/gtk-warning-locale-not-supported-by-c-library-when-starting-apps-from-th

**Comment by ccordoba12** [comment]
And according to @anderwm, the problem is in the **Python** console, with the `GtkAgg` mpl backend

**Comment by anderwm** [comment]
I now believe it is 2 unrelated issues.  The warning from goanpeca/language goes away before his merge, but the python console problem remains until before commit 6bbd031d2b5714923a2322c7fe5aeaae41e3307c

**Comment by ccordoba12** [comment]
Ok, thanks. I'll take care of the second problem then :-)

**Comment by goanpeca** [comment]
I was aware of the warning, but it seem harmeless so I ignored it :smile_cat:, but I can make a fix to get rid of it.

**Comment by ccordoba12** [comment]
@goanpeca, please do :-) This is too visible and so something please will keep complaining about.

**Comment by goanpeca** [comment]
@ccordoba12 for the language fix there are two ways... 

1.) Either rename the locale folders to valid names... (and from now on make sure translations are places in a correctly named directory) or 

2.) to make a mapping inside baseconfig so that when en is loaded it turns to en_US.

The first one would make it more future proof so I would prefer that one... but the gettext script would have to be changed as well. The second one is easier to implement but would become too hacky eventually...

Let me know

**Comment by ccordoba12** [comment]
I'm sorry but I'm going to remove support for the Gtk backend in our **Python** Consoles for Spyder 3. You can still use it without problems in our IPython ones :-)

I tried to make it work as expected for several hours this weekend and couldn't do it. It seems to be caused by a tricky interaction between Qt and Gtk event loops.

Since this backend doesn't provide any additional functionality over the Qt or Tkinter ones (which are working as expected), then I don't see the need to spend more time trying to support it.

**Comment by anderwm** [comment]
I may be missing something as I don't fully understand how all the backend systems hook in.  However, I am using Qt4Agg as the matplotlib backend as selected in console settings under preferences.  I am not sure how we got onto gtk, except that was the warning message for the locale problem.

**Comment by anderwm** [comment]
The problem I was having was resolved, according to bisect:

The first good revision is:
changeset:   fbd66cbc1a0734bfef51467e9fbe0c16f3cf167e
user:        Carlos Cordoba <ccordoba12@gmail.com>
date:        Sun Jul 12 10:19:33 2015 -0500
summary:     Python Console: Fix crash after first execution

**Comment by ccordoba12** [comment]
@anderwm, sorry, I thought you were using the `GtkAgg` backend because of the Gtk error message you also reported. But I'm glad to hear the error is fixed for you now ;-)

I already referenced this issue from a commit that I'm about to push, so let's leave it like this in case someone else looks for us dropping `GtkAgg` in the future :-)
