### ISSUE TITLE
debug - breakpoints inconvenience 

### ISSUE THREAD

**Issue by Temmplar** [spyder-ide/spyder#2518]
Spyder is in debug mode.
I have set several breakpoint in my script.
When I start the debugging, spyder automatically run to the first breakpoint not allowing me to do anything before. If I want to make some step before, I have to remove all the breakpoints, start the debugging, set the breakpoints back and then it makes steps properly. Is there any way to avoid this function?

**Comment by ccordoba12** [comment]
It was a very common complaint that Spyder didn't move to the first breakpoint automatically. and instead remained at the beginning of the file. That's why we added this functionality a couple of releases ago.

However, there's an easier way to make Spyder stop before your first breakpoint: just add another breakpoint before it, preferably on the first line of your file that's not empty or has a comment. That's how it worked before.

**Comment by Temmplar** [comment]
Well if the crowd is so divided regarding this function, may consider a debug config option.
