### ISSUE TITLE
Dock matplotlib figures

### ISSUE THREAD

**Issue by naught101** [spyder-ide/spyder#2550]
I don't use inline plotting, because you lose the zoom functions, which are really useful for me. But it'd be nice to have matplotlib windows docked into the spyder UI, so that I don't need to switch back and forth between the two windows.

**Comment by ccordoba12** [comment]
Sorry, but I think this is not so easy to do :-)

**Comment by vtraag** [comment]
This feature would be a great idea! Hopefully it is not as difficult as imagined...

**Comment by Nodd** [comment]
I depends a lot on how matplotlib is used, which backend... I think it's not even in the same process as the main interface ?

What we could provide is a module specific for spyder, so that `import spyderplotlib as spl; spl.figure()` creates a dockable widget instead of a standalone figure. That would mean that the scripts olny works from inside spyder. But it may create more problems that it solves.

**Comment by vtraag** [comment]
Personally, having the option of creating a dockable widget instead of a standalone (or inline) figure would be a benefit. Then whenever my script is ready (i.e. I'm done testing and playing around), I can always change it around to a standard `matplotlib`. But might it not be possible to enforce using <a href="http://matplotlib.org/1.4.3/examples/user_interfaces/embedding_in_qt4.html">`qt` backend for `matplotlib`</a>, which could then be used within Spyder?

**Comment by Nodd** [comment]
After a bit more thought, I don't know how any of this could be done: the script is completely independent from the main spyder interface so there is no way to get a reference of the QMainWindow.

It could work in the internal console, but we're not going to do that.

**Comment by vtraag** [comment]
That does sound rather insurmountable indeed. Too bad!

But here's another thought: could you perhaps display use the variable explorer to display an image/plot that is stored? Then one could simply store the plot in a variable, and have it displayed in that way. If in addition that window could be made dockable (and auto-refreshable), it would be a great solution (cf. issue #2863).

**Comment by Nodd** [comment]
The last news I had about this is that matplotlib figures don't work very well with pickle (which is what we use internally to exchange the variables), that's why there is no format to save matlab figures like .fig in matlab. Maybe it has changed, in that case it is possible that it can be a viable workaround.

**Comment by vtraag** [comment]
Perhaps the pickling of `matplotlib` figures will improve over time. We'll wait and see!

**Comment by gepcel** [comment]
Having a dockable plot window (or say panne) is a very good idea.
I don't know how, but the "Rodeo" ide managed to get this worked. 
It would be very wonderful that somebody can make it happen in spyder.

**Comment by goanpeca** [comment]
There are major technical differences when comparing to something like Rodeo...

## On Rodeo:
Rodeo is JS technology for the Desktop and they only have access to one console at a time, so they can connect that console directly to a "Plot Tab"
 
## On Spyder:
Spyder uses Qt, through PyQt, so there is one python console where the app lives (Internal Console) and Spyder allows you to open N number of python/ipython consoles as separate processes.

Like @Nodd says, it is not possible for us to hook to a Matplotlib Canvas (based on Qt) with the main python interpreter where Spyder runs.

### However, what we can do something along this lines...:
Add extra support for matplotlib figures inside the variable explorer so that everytime a specific type of matplotlib object is stored in a variable (an Axes object), we would pickle it, and then try to reload inside a Spyder Plugin that would now be running within the Spyder App. If we are running on the ipython console it would be something like:

```
import matplotlib.pyplot as plt
import numpy as np

ax = plt.subplot(111)
x = np.linspace(0, 10)
y = np.exp(x)
some_plot = plt.plot(x, y)
```
Now we can detect that some_plot was created (or updated if changed) and trigger a pickle/unpickle process where the unpickled result would be displayed in a separate dockwidget. So in theory is doable...

### Gotchas
- The user needs to save the plot inside a variable, which is ok, since is a minor style change, plus scripts will work inside and outside spyder
- We need to do some matplotlib patching on startup to make sure we can override some methods... like automatically displaying a plot, when doing `some_plot = plt.plot(x, y)`
- Depending on the complexity of the figure it might be slow?
- We now need to monitor these special variables to know if its content has been updates etc...

@Nodd, @ccordoba12 what do you think?

**Comment by gepcel** [comment]
Wow this sounds very complicated, though I'm happy this was tagged "wishlish" and "Enhancement". I missed rstudio(^_^).
And there's other things  like `boken`, `seaborn`, `cartopy`, `ggplot` ...

**Comment by goanpeca** [comment]
It is complicated!. So if it would add enough value to users to more happily move towards Spyder I am in for giving it a try. Right now we are trying to get 3.0 out so this is definitely on hold for now.

>If matplotlib plot can be implemented, means all other 'matplotlib' based plot will work automaticly, right?
In theory, but most likely we will need to implement some extra sanity checks depending on how the other libraries wrap the Axes object from MPL.

**Comment by goanpeca** [comment]
Some feedback from a lecture @jitseniesen gave recently (October 2016)

>Guy that is teaching Python programming to students using Spyder said that students like the fact that you can plot from the variable explorer (I didn't even know that that option exists!)

>But the integration of plots with console (and the use of backends) is rather confusing.
There was some bug report coming up recently about having a plot pane; I think that might be really helpful

>When the plot comes up inline, it is not easy to save it ... ideally, it would be a right click
This is all in the context of maths students that are absolute beginners in Python (and are more interested in maths than programming)

**Comment by ccordoba12** [comment]
We could grab plots that come inline and also show them in that dedicated pane :-)

**Comment by goanpeca** [comment]
Yep, the easiest approach/path would be to first handle the static inline plots case and then we can handle the more elaborate and general (dynamic) case. 3.2?, 3.3?

**Comment by ccordoba12** [comment]
3.2 for the simple case.

**Comment by goanpeca** [comment]
@ccordoba12  could you point me to the relevant place where I can get the inline plots

**Comment by ccordoba12** [comment]
They come in the messages sent by the kernel and are handled by qtconsole itself. The relevant method is called `_handle_execute_result` from `RichJupyterWidget`. For now this is placed here:

https://github.com/jupyter/qtconsole/blob/master/qtconsole/rich_jupyter_widget.py#L120
