### ISSUE TITLE
Scrolling fast breaks scrolling

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#2646]
## Description

**What steps will reproduce the problem?**
1. Scroll rapidly with the mouse wheel

**What is the expected output? What do you see instead?**
My code is flickering up and down, and the overall movement is going in the opposite direction !

**Please provide any additional information below**
I tried in another Qt5 app (retext) just in case and had no problem.
## Version and main components
- Spyder Version: 3.0.0dev d6f08e2
- Python Version: 3.4.3
- Qt Versions: 5.5.0, PyQt5 5.5 on Linux
## Optional dependencies

```
pyflakes >=0.6.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
IPython >=3.0   :  4.0.0 (OK)
zmq >=13.0.0    :  14.7.0 (OK)
qtconsole >=4.0 :  4.0.1 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
psutil >=0.3    :  3.1.1 (OK)
rope >=0.9.4    :  0.9.4-1 (NOK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  None (NOK)
pylint >=0.25   :  1.4.4 (OK)

```

**Comment by Nodd** [comment]
Also when dragging the scrollbar vertically the text moves quite slowly. I don't know if it's linked to the main problem, but it looks like the painting is a bit slow and that creates problems.

**Comment by ccordoba12** [comment]
Could you deactivate cell highlighting and try again? Maybe that's causing the problem.

**Comment by Nodd** [comment]
Nope, I see no difference. Also there is no cell in the file I currently use.
It could be due to the new additions to highlighting maybe, about the blank space. Note: I don't display them.
While doing this the CPU gets up to 90% (for spyder only), so something is really happening.

**Comment by goanpeca** [comment]
Ok I will dive into this and comment some line in the source code editor and check what can be causing this.

**Comment by Nodd** [comment]
I don't see it anymore, I have no clue about what fixed it.

**Comment by Nodd** [comment]
I see this issue again, the intensity seems to vary a bit but I'm not sure why.

**Comment by aje** [comment]
I also have this issue in the code editor.
 - If I scroll with my mouse wheel while not moving my mouse this is ok.
 - When I scroll and then move my mouse and then scroll again this issue appears: the scroll bar is moved wrongly (it seems that the scroll bar is moved at the middle of the file).

The author has probably this issue because when he scrolls fast, he also moves his mouse.

I also have the same issue in all the panels of spyder having a scrollbar:
 - panel at the top right (variable explorer/help/file explorer)
 - panel at the left (project explorer)
 - python console
 - ipython console
 - in the Tools/Preferences
 - ...

Using:
Spyder 3.0.2
Python 3.4.2 64bits, Qt 5.3.2, PyQt5 5.3.2 on Linux
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  None (NOK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5 (OK)
sympy >=0.7.3    :  None (NOK)
Gnome 3.14.1
Debian GNU/Linux 8.6 (jessie) 64-bit (Running Linux inside a virtual machine using Virtual Box on my Windows 10 system)

I don't have this issue with other applications such as Emacs, Gedit or Eclipse.

I hope you find a solution for this, this is really annoying.

**Comment by ccordoba12** [comment]
Closing because this is (most probably) a Qt issue.
