### ISSUE TITLE
Create self-contained Windows Installers

### ISSUE THREAD

**Issue by techtonik** [spyder-ide/spyder#2648]
After installing Spyder from `spyder-2.3.6.win32-py2.7.exe` it still fails to run without PySide or PyQt4 installed.

![image](https://cloud.githubusercontent.com/assets/515889/9519598/a93f08ea-4cc8-11e5-889d-e752ffb81e24.png)

It would be nice if instead of this window, Spyder could fetch and install PySide wheel locally.

**Comment by ccordoba12** [comment]
I think this doesn't belong on the Spyder side of things, it's a packaging issue.

**Comment by techtonik** [comment]
@ccordoba12 if Spyder aim is to provide a better UX that IDLE, then bootstrap process is also part of that experience. Take a look at how NLTK resolved that UX issue with `nltk.download()`.

**Comment by Nodd** [comment]
The minimum would be to add a link to PyQt or PySide next to the exe download. It's true that on windows it's very uncommon to install dependencies separately. (It only happened to me once with gtk.)
It could also be an option in the installer.

**Comment by techtonik** [comment]
I downloaded the standard installer for Python packages and I am not sure it can be patched to add such option.

**Comment by Nodd** [comment]
I meant spyder's installer.

**Comment by ccordoba12** [comment]
PySide is just the minimal thing to have Spyder working. But that doesn't give code completion, the IPython/Jupyter console, PyFlakes warnings, etc, etc. So it's not a real solution.

What we need is to create fully self-contained Windows installer. For that we could use this project:

https://github.com/takluyver/pynsist

@techtonik, if you want to contribute a `cfg` file for Spyder, that'd be great :-)

**Comment by techtonik** [comment]
@ccordoba12 I am interested to do this, but I am afraid that I will need some financial help to to get this done.

**Comment by techtonik** [comment]
https://github.com/pyinstaller/pyinstaller looks like a good option.

**Comment by techtonik** [comment]
One of the scenarios that needs to be supported is when the installer includes Python. Because Spyder is needed to teach people. And while installing Python 3.5, there is a problem with Windows updates that needs to be considered.

https://github.com/winpython/winpython/issues/341

**Comment by takluyver** [comment]
I'd be wary of trying to create a standalone installer for Spyder, because like IPython, it's a tool that you use as part of a larger Python system, and you might want to install all kinds of things into that. There are already tools like Anaconda or Winpython to set up that sort of Python ecosystem, and there are ways you can reuse their tooling to create an installer with your own selection of packages (see [conda constructor](https://github.com/conda/constructor), for instance).

Pynsist (along with Pyinstaller and other freeze tools) is intended to package applications where the user needn't know or care about Python code, and probably won't want to install extra packages. It doesn't make it impossible to install extra packages, but it also doesn't do anything to facilitate it.

That said, Pynsist should definitely be able to make an installer for Spyder, and if you want to do that despite my warnings, I'm happy to provide any necessary pointers.

**Comment by takluyver** [comment]
See here for an example using Pynsist with PyQt5:
https://github.com/takluyver/pynsist/blob/master/examples/pyqt5/installer.cfg

There isn't currently an example with PySide, but it should be easy if you're targetting a Python version for which there's a PySide wheel on PyPI. Unfortunately that doesn't include Python 3.5 yet.

**Comment by techtonik** [comment]
@takluyver is it possible to create installer that will install Spyder into system Python (whichever is available) instead of bundling its own, and if there is no Python installation, propose to download and install official Python package thus creating this "system Python" installation? Uninstall behavior should probably give an option to remove Python installed such way. That would be a perfect user experience, which won't limit users from using Python the standard way (pip etc.)

**Comment by takluyver** [comment]
It's certainly possible, but maybe not easy. Pynsist with `format=installer` will reuse an existing Python.org installation if it's in the location that Pynsist would install it anyway, but in a very stupid way (it always tries to install it, and lets msiexec deal with any existing installation). As far as I know, it won't find an Anaconda, Winpython, Python(x,y), etc. installation of Python, and I'm not sure if it will even find a python.org installation in another location. I'm moving towards `format=bundled`.

Doing something better than that would require some way to actually decide if Python is installed and what version it is, and some UI for the user to pick if multiple Pythons are found. If you want to have an installer that can target different versions of Python, you also need multiple copies of extension modules like PySide, so you can install the right one.

One of my design principles in Pynsist is to do as much as possible when building the installer, so that the installer code itself can be relatively simple. Writing anything non-trivial in NSIS script is not much fun, testing is slow and awkward, and installer bugs are hard to debug and leave users unable to use your software. What you want involves a fairly complex installer, which is probably a bad idea for a small development team. ;-)

Simpler alternative: have an install page with short sections for new-to-Python users and users who already have Python. We use [something like this](http://jupyter.readthedocs.io/en/latest/install.html) for Jupyter, though the wording is no longer quite like that.

**Comment by ccordoba12** [comment]
@techtonik, as the title says of this issue says, we want *self-contained* installers, meaning that they should come with Python, all our dependencies and the basic Scientific stack (i.e. Numpy, Pandas, and Matplotlib).

Otherwise, I don't see a point in having them. Windows users are not that good at tracking and installing several dependencies separately :-)

**Comment by ccordoba12** [comment]
Closing because we don't plan to work on this.

**Comment by techtonik** [comment]
Yes. Windows doesn't worth the hassle.

**Comment by ccordoba12** [comment]
No, because we have Anaconda now.

**Comment by techtonik** [comment]
Whatever. I don't know why I wasted so much time there.
