### ISSUE TITLE
spyder 2.3.6 broke guidata and guiqwt

### ISSUE THREAD

**Issue by picca** [spyder-ide/spyder#2651]
Hello, when I try to run guidata-test and guiqwt-test I got this error message.

com-sixs@sixs7:~/Fitnxs$ guidata-tests
Traceback (most recent call last):
  File "/usr/bin/guidata-tests", line 3, in <module>
    tests.run()
  File "/usr/lib/python2.7/dist-packages/guidata/tests/__init__.py", line 16, in run
    from guidata.guitest import run_testlauncher
  File "/usr/lib/python2.7/dist-packages/guidata/guitest.py", line 17, in <module>
    from spyderlib.widgets.sourcecode.codeeditor import CodeEditor
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/sourcecode/codeeditor.py", line 25, in <module>
    from spyderlib.qt import is_pyqt46
  File "/usr/lib/python2.7/dist-packages/spyderlib/qt/__init__.py", line 23, in <module>
    sip.setapi('QDate', 2)
ValueError: API 'QDate' has already been set to version 1

com-sixs@sixs7:~/Fitnxs$ guiqwt-tests
Traceback (most recent call last):
  File "/usr/bin/guiqwt-tests", line 3, in <module>
    tests.run()
  File "/usr/lib/python2.7/dist-packages/guiqwt/tests/__init__.py", line 16, in run
    from guidata.guitest import run_testlauncher
  File "/usr/lib/python2.7/dist-packages/guidata/guitest.py", line 17, in <module>
    from spyderlib.widgets.sourcecode.codeeditor import CodeEditor
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/sourcecode/codeeditor.py", line 25, in <module>
    from spyderlib.qt import is_pyqt46
  File "/usr/lib/python2.7/dist-packages/spyderlib/qt/__init__.py", line 23, in <module>
    sip.setapi('QDate', 2)
ValueError: API 'QDate' has already been set to version 1

It would be realy nice to provide a 2.3.7 with the fixed. and remove the support for API #1 only in spyder 3.0.0.

This seems to me a big issue.

Cheers

PS: guidata and guiqwt are broken now in Debian unstable and at in Ubuntu.

**Comment by ccordoba12** [comment]
@picca, I'm sorry, but we don't maintain guidata and guiqwt. Since @PierreRaybaut seems to be back in action, please ask him to update them to use API `#2`.

They live here now:

https://github.com/PierreRaybaut/guiqwt
https://github.com/PierreRaybaut/guidata

----

> It would be realy nice to provide a 2.3.7 with the fixed. and remove the support for API #1 only in spyder 3.0.0

I really understand that, but I had to do this change for two reasons:

1. Jupyter didn't leave us any other alternative. I don't know what happened but in the big split some things were not shimmed appropriately (i.e. `IPython.external.qt` I think). So we were forced to do this because there were already a lot of users complaining about the breakage.
2. Spyder 3.0 is still some months away to be finished, and I needed to take action immediately :-)

**Comment by picca** [comment]
ok, I already fill a bug against guiqwt. Now I will fille and RC bug in order to avoid spyder migration in Debian and Ubuntu.

Thanks

Fred

**Comment by ccordoba12** [comment]
> Now I will fille and RC bug in order to avoid spyder migration in Debian and Ubuntu.

What do you mean by that? Please don't do it. I can help you patch guiqwt and guidata if you want, but 2.3.6 has several important bugs to prevent freezes with DataFrames in the Variable Explorer.

So please don't block it in Ubuntu just because those packages don't work in Spyder. I mean, unfortunately Pierre almost left them abandoned until last week, so I don't see why Spyder will have to be impacted by that.

**Comment by picca** [comment]
I need to avoid this migration because other packages using spyder will be broken.
python-guiqwt
python-guidata
python-taurus
python-sardana

which are used by others. this API 1 et 2 is a big move...

the next Ubuntu version is for 15.10.

So for now and to avoid breaking things, I need to freeze the process until we find a solution which does not break already uploaded packages.

taurus use spyder for it's macro edition and I can not take the risk to brake it...
A bunch of instituts, I am working with rely on this piece of software.

Ps: jupyter is not yet part of Ubuntu and Debian so we are not concerned by this API 2 move already.
by concern I do not mean, we do not care, but for now we rely on the 2.4.0 ipython version available.

**Comment by ccordoba12** [comment]
> which are used by others. this API 1 et 2 is a big move...

I know, sorry for that :-) I was keeping it for 3.0 but those constant breakages introduced by IPython/Jupyer are really annoying!!

Since there are lots of users also having Spyder from Anaconda and pip, I needed to move really fast to fix our incompatibility with Jupyter 4.0.

> So for now and to avoid breaking things, I need to freeze the process until we find a solution which does not break already uploaded packages.

I understand your decision, too bad for Ubuntu/Debian users...

**Comment by picca** [comment]
The important point is not to break already available pacakges.
This is something pip/python is not really good at :). you can not compile all your software and garanties that it breaks nothing.

Maybe type hinting will help for this

**Comment by ccordoba12** [comment]
I wish there would be a simpler solution too. At the end that's why I think Anaconda is also useful in Linux too :-) I mean, it let us distribute the latest version of our packages as fast as possible :-)

**Comment by picca** [comment]
For pure python it is ok, but once it comes to extensions... you need to packages also third-party libraries.
So at the end I prefer e fully integrated distribution, instead of specialize distributions.

Cheers
