### ISSUE TITLE
Ubuntu doesn't recognize that there's a new version of Spyder

### ISSUE THREAD

**Issue by rbrackney** [spyder-ide/spyder#2668]
Hello,

I've been trying to upgrade Spyder to 2.3.6 in Ubuntu 15.04, however, when I run
    <pre><code>apt-get install --only-upgrade spyder</pre></code>

It tells me that spyder is already up to date, although the version is listed as "2.3.2+dfsg-1ubuntu1"

Can someone tell me how to get it to upgrade Spyder to 2.3.6?

Sorry if there's something basic I'm missing. I'm still fairly new to Linux.

**Comment by greenorca** [comment]
Hi there,
uninstall spyder with apt-get remove spyder, download from this page and extract the zip-file. The process is described in README.md file.

Cheers
:-)

**Comment by ccordoba12** [comment]
The problem is Linux packages (especially in Ubuntu and Debian) are (usually) not updated as new versions appear in already released distributions (even if they are bugfix versions, like all the ones in the 2.3 series).

So, you have two options:

1. Use `pip` (the Python package manager) to update Spyder (after removing the Ubuntu version, as described by @greenorca). For that you need to use this command:

        sudo pip install -U spyder

2. Use the [Anaconda Python distribution](http://continuum.io/downloads.html) to install Spyder. This is a third-party set of packages, made for scientists and data scientists.

    The good things is that Anaconda always maintain the latest versions of all scientific Python libraries (like Pandas and Matplotlib), and comes with its own package manager (called `conda`), with which you can update them at any time.

    To update Spyder in Anaconda, you need to run this command:

          conda update spyder
