### ISSUE TITLE
Spyder 2.3.6 says PySide 1.2.0+ is required, but I have PySide 1.2.2 installed

### ISSUE THREAD

**Issue by Stretch97** [spyder-ide/spyder#2699]
## Description

**What steps will reproduce the problem?**

1. Use pip to install Spyder 2.3.6
2. Start up Spyder from the command line

**What is the expected output? What do you see instead?**
I expect Spyder to launch, but instead I get the following error:
"Please check Spyder installation requirements: PyQt4 4.6+ (or PySide 1.2.0+) is required."

**Please provide any additional information below**
As you can see below, I have PySide 1.2.2 installed, so this error doesn't make a lot of sense.  Also, once I downgraded back to Spyder 2.3.5.2 using pip, Spyder launches without any problems.  In case it matters, I am using Enthought Canopy for my python installation.  Finally, the exact same issue occurs on my home computer (also a Mac), and it is also resolved by downgrading to Spyder 2.3.5.2.

## Version and main components

* Spyder Version: 2.3.6
* Python Version: 2.7.6
* Qt Versions:  4.8.6, PySide 1.2.2 on Darwin

## Optional dependencies
```
pyflakes >=0.5.0:  0.9.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.2.1 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
jedi >=0.8.1    :  None (NOK)
matplotlib >=1.0:  1.4.2 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  0.25.1 (OK)

```

**Comment by ccordoba12** [comment]
This was already reported in issue #2649 and fixed in pull request #2650 (to be part of Spyder 2.3.7).

**Comment by ArthurZ** [comment]
Anaconda Launcher reports I have ver 2.3.7 installed and when I start it I am seeing an error:
Please check Spyder installation requirements: PyQt4 4.6+ (or PySide 1.2.0+) is required.
I am on Windows 7.
Starting Spyder from the Start menu makes it run, but it is ver. 2.3.6
Note: I attempted to conda update -all and was getting linking errors I ignored.

**Comment by PerBr** [comment]
This issue is not fixed at least not on the Windows Spyder release in the Anaconda package.

I got this problem after updating conda (`conda update`) to the latest version today on a Win 7 machine.  Everything has worked OK up until the update this morning.

I already had PyQt 4.11.4 installed so it should have worked, right.
But it did not.

The solution was to also install pyside which is not by default in the Anaconda release

`conda install pyside`

After the pyside installation everything works again.

Have fun,
/Per
