### ISSUE TITLE
Release 3.0 with PyQt5 as default

### ISSUE THREAD

**Issue by flying-sheep** [spyder-ide/spyder#2763]
Last time we talked, you still considered PyQt5 support too immature to use.

So I filed this to track the status of this feature.

```py
os.environ.setdefault('QT_API', 'pyqt5')
```

**Comment by ccordoba12** [comment]
I've been thinking on this lately, and Spyder with PyQt5 seems right now very usable and stable. There are still some issues with code completion on the Editor. But I think they are going to be solved once @blink1073 moves that code from using threads to QProcess'es.

However, first we need to start testing this combo in Travis. That's why I opened PR #2762, but I found a major roadblock: there aren't usable PyQt5 conda packages. So I plan to spend this week creating them myself :-)

Then we can move with more confidence to accomplish this goal!

**Comment by flying-sheep** [comment]
yay, great to hear!

**Comment by goanpeca** [comment]
@flying-sheep pyqt5 will most likely be the default binding.
