### ISSUE TITLE
Add interactive checkmarks for "bool(...) = True | False" in the Editor's margin

### ISSUE THREAD

**Issue by goyou** [spyder-ide/spyder#2782]
Hello dear spyder contributors,

I would like to suggest a functionality for users that like to have some boolean to run their scripts using different options.
(For example, I like to have something like "Savefigs = True" at the beginning of a script, then if I want to run the script without saving (or without plotting for another example), I will just change the value to False and run the script.)
The idea is, if Spyder would recognize a line such as this :
    bool(Savefigs) = True
Spyder could add a checked box in the margin... then if the user will click on the box, Spyder will uncheck the box and change the corresponding value to "False".

Maybe it is not worth the work, but I think it would be a cool thing for comfort, usability or style.
Thank you for your attention.

**Comment by ccordoba12** [comment]
Thanks for the suggestion. Unfortunately we're very busy right now with other things, so someone will have to implement this feature :-)

**Comment by Nodd** [comment]
The problem I see is that it would promote a bad practice: it's cleaner to export your bloc of code in a function and just comment its call for example. I've had to update Matlab code full of `if 0` and `if 1`, it's very hard to read.
Also `bool(Savefigs) = True` is not valid python, am I missing something ?

**Comment by goyou** [comment]
Yes actually I've mistaken the syntax.
The usage will be that kind of way : 
<code>
Savefigs=bool(True)

[...blablabla...350 lines of code...]

if Savefigs : 
    call_some_function()

[...blablabla...]
<\code>
The user doesn't want to seek the call_some_function within so many lines, especially if he doesn't remember what is the name of the function.
Having such boolean definitions at the beginning is very clear, and it works very well. So This functionality is of the least of emergencies I understand.

**Comment by Nodd** [comment]
I think it could be done by a plugin listing all occurrences of values set to a boolean in a table. It would be even easier to find the values to change, and would keep the margin clean (ticks in the margin are already used for TODO items).
Plugin support will be greatly enhanced in spyder 3.0.

**Comment by goanpeca** [comment]
I do not think having `Savefigs = bool(True)` is a good idea. (It should be lowercased by the way.... PEP8)

If we are going to do thing like this, then they should be implemented in comments like

`savefigs = True    # Spyder: toggle`
or
`savefigs = True    # :spyder: toggle`

Like this the code would still make sense in other editors, and the magic would work in spyder when reading those tags.

**Comment by ahed87** [comment]
Hi,
:+1: I think this is a great idea and I would use it if it was there.
The whole point of something like this is visibility on the screen.

One suggestion could be:
do the flag with a comment as suggested by goanpeca.
```savefigs = True # :spyder: toggle```
have one additional panel popping up at the bottom of the editor (like the search panel when hitting Ctrl+F), with the identified check-boxes. I have no opinion of what keystrokes/menues should put this into action. This way it's out of the way for users that do not want it, and really easy access for users that want it.

I guess there is a syncronization between code and status of checkboxes hidden here somewhere as well :-)

Anyway I just stumbled over this issue and thought a +1 was in place since I recently had a small script where I put in some flags with true/false to control the flow of the program, most of them used as options in function calls.

**Comment by Nodd** [comment]
Another idea: have a shortcut to toggle between True/False when the cursor is on either one of them. It would be less visible, but not restricted to lines marked with a special comment.

The shortcut could be included in spyder by default, and the special comments listed in a table would be an external plugin (since I see it more as a niche).

**Comment by ahed87** [comment]
Would work as well - and maybe they would even complement eachother if they where both there.
I just wanted to voice that the feature as such is a good idea and I'm one that would appreciate such an enhancement.

I'll leave it up to you devs to make the call what/if to do, after all it's a nice to have not a must have.

**Comment by jondo** [comment]
My workaround is to write `Savefigs = bool(1)`. This makes switching much faster (though not single-click).

**Comment by ccordoba12** [comment]
Closing because we don't have plans to implement this.
