### ISSUE TITLE
Plots freeze in the Python console when using the Tk backend on Windows

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/spyder#2788]
on recent winpython with ipython4, spyder 2.3.6 , 2.3.7, 3.0dev (matplotlib 1.4.3 or 1.5rc3) , qtconsole 4.1, it seems an old issue is coming back.

test:
- launch spyder
- type this script and launch it in current Python (not Ipython) console:
````
import matplotlib.pyplot as plt
plt.scatter([0], [0])
plt.show()
plt.pause(5)
# plt.close  # will close the 'pending' tcl/tk window if you relaunch the script on same console !
````

effect:
- the tcl/tk windows open, show the graphic, thanks to the `pause`
- then enters in 'unresponsive` mode
- apparently, spyder seems to have taken back it's event loop, so is not directly affected.

I don't know if it's truly a spyder issue.

https://github.com/winpython/winpython/issues/191

**Comment by stonebig** [comment]
known workaround is to launch on an external terminal, or in the qtconsole

**Comment by ccordoba12** [comment]
I'll try to fix this for Spyder 2.3.8

**Comment by ccordoba12** [comment]
My findings (using Anaconda):

1. Plots with Tk block our Python consoles on Windows, i.e. they show up and you can interact with them as expected, but after that you can't evaluate further commands.
2. I also tried to create plots on a terminal, and the console blocks after running `plt.show()`. That means that the Tk event loop (which comes with Python itself) is not working on Windows.
3. We rely on the Tk event loop to be working because we don't have one. So if it fails, there's nothing we can do about it. This is (most probably) the problem you're seeing in WinPython too.

----

Given this situation, I decided to remove support for Tk on Windows for Python 3. Besides:

1. Things are working pretty well on the IPython console, so if people want to use Tk, they should use it instead.
2. The `Qt4Agg` backend works also very well on our Python consoles, so if people wants plots on those consoles, they are going to get them (at least in Spyder 2.3. There seems to be a bug in master :-)

**Comment by ccordoba12** [comment]
Sorry, support is not only removed for Python 3, but also for Python 2. And this is now part of Spyder 3.0.

**Comment by ccordoba12** [comment]
I just fixed the problem in master with plots using the Automatic (i.e. PyQt4 or 5) backend, everything is back to normal for our Python consoles.

**Comment by stonebig** [comment]
ok. will you do a new beta soon ?

**Comment by ccordoba12** [comment]
Yes, working ot it :-) I hope to have it for this weekend.

**Comment by stonebig** [comment]
super

**Comment by stonebig** [comment]
the complainer's remark is that there is no "Tk" in the given test he does. This was an error of interpretation from me.

On today master, the issue described [here](https://github.com/winpython/winpython/issues/191#issue-114266794) is still there, even if I specify 'Qt4':
````
import matplotlib as mpl
mpl.use('Qt4Agg')

import matplotlib.pyplot as plt
plt.scatter([0], [0])
````
