### ISSUE TITLE
Spyder editor cursor lags during typing

### ISSUE THREAD

**Issue by lonestar79** [spyder-ide/spyder#2817]
I have just installed the latest Anaconda package available on Anaconda website. I have now Spyder 2.3.7 running with Python 3.5. Operating system is OSX El Capitan 10.11 running on a newly purchased iMac.

When I start typing code on Spyder editor, the cursor is lagging. It's somewhat slow. This makes typing very difficult. Are there any solutions for this? Thank you.

**Comment by ccordoba12** [comment]
I think the only solution for all problems in El Capitan is waiting until Spyder 3.0 is released because it will come with PyQt5 instead of PyQt4.

I don't know how else to help you, sorry.

**Comment by cnolanAU** [comment]
I've had this issue since at least Yosemite. If I plug in an external monitor and start Spyder, the cursor is not laggy, and remains not-laggy if I then unplug the external monitor. Obviously that's not a workaround if you don't have an external monitor at hand (as I do not right now). I'll be looking forward to the 3.0 release, the software is completely unusable with the editor lag. Thanks for the info Carlos!

**Comment by durack1** [comment]
@ccordoba12 this seems to be similar to the experience I have with #2748 - @lonestar79 when the laggyness occurs, are there any variables in memory, or does it occur right away?

**Comment by lonestar79** [comment]
It occurs right away.

**Comment by goanpeca** [comment]
I think this specific problem no longe applies, however we do need to profile the codeeditor code to make sure we are doing the least amount of unnecessary processing on the main thread and move any heavy calculations to a separate thread.
