### ISSUE TITLE
Control+C should not copy if it has nothing selected on the editor

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#2835]
# Description

Select something on the editor and `Ctrl+C` it... then with nothing selected accidentally typing `Ctrl+C` will replace the content of the clipboard with an empty string... this is annoying.

If nothing is selected, the behavior should be to no put an empty string in the clipboard...

**Comment by goanpeca** [comment]
@julianrolon

**Comment by stephenshank** [comment]
Hello Spyder devs,
I have attempted to fix this issue here: https://github.com/spyder-ide/spyder/pull/3043

I would gladly welcome any criticism, as this is my first contribution to open source. If what I have submitted does not fully resolve the issue, I would also greatly appreciate advice on how to produce a satisfactory solution.

Thanks in advance!
