### ISSUE TITLE
Hide the titlebar from panes/dockwidgets if locked

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#2855]
# Description

This depends on #2854

**Comment by jnsebgosselin** [comment]
@goanpeca  and @ccordoba12 
Presently, the _Lock panes_ features (Ctrl+Shift+F5) that exists under the _View_ menu of the _MainWindow_ only serves to prevent the dock widgets to be dragged around. I propose that instead of adding an option, we use this same _Lock panes_ option to also : 

1. Hide the titlebar
2. Hide the Close and Detach button

Changes to the code would be minimal to implement this feature, there is no need to create a custom title bar. Everything can be done within the Qt framework. I will do it if it is accepted. Below, i present a POC of what I am proposing.

![dockwidget_titlebar](https://user-images.githubusercontent.com/10170372/30485468-791e207e-99fb-11e7-80d1-e49e635cc7d8.gif)

**Comment by jnsebgosselin** [comment]
I see this idea was already proposed/discussed in PR #2345, but as a new option on top of the _lock panes_ feature. 

I believe there is no need to add a new option.  _Lock panes_ would need to be _off_ by default however.

**Comment by ccordoba12** [comment]
Jean, we agree the title is unnecessary for most plugins, but we show the current file path in the Editor title bar, and people is very accustomed to that. So you would need to add a label to the Editor plugin for that.

Other than that, I'd like to see a PR for this. I think connecting this to the `Lock panes` action is a terrific move and something none of us had thought before!

**Comment by jnsebgosselin** [comment]
Alright thank you, I'll submit a PR soon.

**Comment by jnsebgosselin** [comment]
Note to self: I'm waiting for PR #3824 to be closed before working on this one.

**Comment by ccordoba12** [comment]
@jnsebgosselin, FYI, I just merged #3824 ;-)

**Comment by jnsebgosselin** [comment]
@ccordoba12 Thanks for the heads up! :+1:
