### ISSUE TITLE
Online help: show crom console

### ISSUE THREAD

**Issue by dacoex** [spyder-ide/spyder#2904]
Can Online help be used in such way that the following lookup in the console from *IPython* is shon in the Online help:

```
os.path.join?
```

**Comment by ccordoba12** [comment]
There is some work for it in side project called `docrepr` (that I developed a couple of months ago). We'll try to integrate it at a later Spyder release.

I'm closing this issue because:

1. We're aware of this problem
2. It's not a proper Spyder bug or problem, just a request for a improvement that we know how to fix.

**Comment by dacoex** [comment]
Thanks for the reply. And for all work with the great IDE!
