### ISSUE TITLE
PyLint plugin reports "Please install pylint" in MacPorts Spyder

### ISSUE THREAD

**Issue by nathan-artist** [spyder-ide/spyder#2933]
I am having the same problem today that was reported in issue #721 in 2011. Via MacPorts I installed Python 2.7.11 and Spyder 2.3.7 and all its dependencies. The "Static code analysis" pane in Spyder reports "Please install pylint". But pylint 1.5.3 is already installed (port py27-pylint), and pylint is listed in the "Online help" pane (pydoc). There are symlinks at /opt/local/bin/pylint and /opt/local/bin/pylint-2.7 and both are in my PATH. Everything else except pylint appears to be working in Spyder.

**Comment by ccordoba12** [comment]
As was mentioned in one of the last comments on issue #721, this is something for the MacPorts maintainers to solve given the way they handle different Python versions.

So please report this problem in MacPorts issue tracker. If there's something we can do in our side, please comment it on issue #721 instead of opening a new one (all issue can be reopened if there's need for that :-)

**Comment by nathan-artist** [comment]
Thanks for the response; I will report this in the MacPorts issue tracker.

**Comment by nathan-artist** [comment]
I reported this in the MacPorts issue tracker and promptly discovered that the problem was my own fault, due to the way I was launching Spyder. For details see this ticket on the MacPorts site:
https://trac.macports.org/ticket/50360

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
