### ISSUE TITLE
config: directory for new files

### ISSUE THREAD

**Issue by dacoex** [spyder-ide/spyder#2981]
With the mobile distributions WinPython & Anaconda it would be convenient to set the defaul saving place for 

* Spyder's temp.py file
* any new file (CTRL+N)

This prevents that files are burried in 
`"C:\WinPython-64bit-3.4.3.7Qt5\settings\.spyder-py3\temp.py"`

This would be independant of the default working directory which may always the directory where the opened file is stored.

**Comment by ccordoba12** [comment]
This is already fixed in Spyder 3.0 for new files because we made that the default current directory when you start Spyder for the first time be your home directory.

I think `temp.py` is fine where it is though. We couldn't create and save it in another place because we can't that decisions for our users.

**Comment by dacoex** [comment]
>I think temp.py is fine where it is though. We couldn't create and save it in another place because >we can't that decisions for our users.

Sure, at beginning.
But an option saying: save temp.py  in default current directory (starting second time and further) would be nice.

**Comment by ccordoba12** [comment]
`temp.py` is just a temporary file, and it's only shown the first time Spyder is started (or when you close all files, close and start Spyder again). So I don't see a need to put it somewhere else.
