### ISSUE TITLE
How to use debugger in Spyder 2.3.8

### ISSUE THREAD

**Issue by s0r2637** [spyder-ide/spyder#3057]
## Description
I am trying to use the F12 command to set break point at any specific line of the code.  However, when I run the code from inside Spyder, the debugger doesn't stop at that line.  Currently, for debugging I use import pdb, pdb.set_trace() command.  I am using Spyder 2.3.8 with Python 2.7 on Ubuntu 14.04 LTS.  Is there any options I need to check to enable the F12 command?
**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 2.3.8 
* Python Version: 2.7.6
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.10.4 on Linux

## Optional dependencies
```
pyflakes >=0.5.0   :  None (NOK)
pep8 >=0.6         :  None (NOK)
pygments >=1.6     :  2.0.2 (OK)
IPython >=1.0      :  4.1.2 (OK)
zmq >=2.1.11       :  15.2.0 (OK)
qtconsole >=4.0    :  4.2.0 (OK)
pandas >=0.13.1    :  0.17.1 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
psutil >=0.3       :  None (NOK)
rope >=0.9.2       :  None (NOK)
jedi >=0.8.1;<0.9.0:  None (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
sympy >=0.7.3      :  None (NOK)
pylint >=0.25      :  None (NOK)

```

**Comment by s0r2637** [comment]
Hi guys,
When do you think someone can start addressing my issue?

**Comment by ccordoba12** [comment]
You're using the debugger incorrectly. These are the instructions to use it in the right way:

1. Please stop using `pdb.set_trace()`. That's not the right way to set breakpoints in Spyder (it basically prevents our users to take advantage of most of the debugging facilities we have to offer :-)
2. You can add breakpoints by doing a mouse double-click in the line number area of our Editor, but only next to non-empty lines. You will see a red circle appear next to that line, which signals the presence of a breakpoint.
3. To start debugging, please press the blue Play-and-pause button on the top. That will start the debugging session. The other blue buttons help you to control it.

Note: I'm going to close this issue because it's not about an Spyder error or limitation. It's just a general question about how to use our debugger. If you have further questions, please post them in our mailing list:

https://groups.google.com/forum/#!forum/spyderlib
