### ISSUE TITLE
Problem using arrow keys in editor

### ISSUE THREAD

**Issue by bluephoton** [spyder-ide/spyder#3071]
## Description of your problem

**What steps will reproduce the problem?**

1. Use spyder editor for sometime and navigate through code using right/left arrows
2. I believe this happen when i have cells (#%%)

**What is the expected output? What do you see instead?**

When I click right arrow it takes me left and when i click left it take me right. Sometimes I can't even move at all within line only jump from line to line

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 2.3.8
* Python Version: 3.5.1
* Operating system: Window 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=1.0      :  4.0.3 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.17.1 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pyflakes >=0.6.0   :  1.0.0 (OK)
pygments >=1.6     :  2.1 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.1.1 (OK)
rope >=0.9.2       :  0.9.4-1 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
sympy >=0.7.3      :  0.7.6.1 (OK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for opening the issue again with the right information! :+1: 

Most probably this is a Qt problem (Qt is the graphical library used by Spyder). If you're using Qt4 through Anaconda (which seems you're doing :-), you'll have to wait until we release Spyder 3.0. This new version will support Qt5, which works correctly on Windows 10.

Unfortunately we're some months away of releasing 3.0. In the meantime you can use the WinPython distribution because it comes with Qt5 and Spyder 3.0 beta.

**Comment by bluephoton** [comment]
Thanks for explaining! yes I'm using Anaconda. I'll not use cells for now - It seems to work fine outside cell - as I don't want to bloat my PC with distros :)

**Comment by ccordoba12** [comment]
This should be fixed in Spyder 3.0 with Qt 5 :-)

**Comment by bluephoton** [comment]
Awesome!! Will update my bits :)
