### ISSUE TITLE
tabs are not lining up

### ISSUE THREAD

**Issue by mcrocco06** [spyder-ide/spyder#3090]
![spyder bug1](https://cloud.githubusercontent.com/assets/14320709/14236968/e1567796-f9e2-11e5-86e7-cbebdec95f95.png)

I'm new to using spyder, and only been coding for a few months. I just set up 2 monitors in addition to my laptop. Was wondering if this had to do with the multiple monitors or is it a bug?

**Comment by ccordoba12** [comment]
Thanks for reporting this bug. Unfortunately, it seems you dismissed the information asked by our issues template, i.e. the information we asked our users when they try to open an issue here on Github.

This information includes Spyder version, operating system, dependencies information and several other things. Without it we are not able to understand and solve Spyder bugs as efficiently as we would like to.

Because of that, I'm going to close your report, and ask you to open a new one with that information filled.
