### ISSUE TITLE
Spyder Kernel Dieing 

### ISSUE THREAD

**Issue by antonfisher108** [spyder-ide/spyder#3092]
Upon opening Spyder, the following appears in the console.

It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console.
It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console.
...

Restarting the console does not fix the issue.

Please help.
Thanks

**Comment by ccordoba12** [comment]
Thanks for reporting this bug. Unfortunately, it seems you dismissed the information asked by our issues template, i.e. the information we ask our users when they try to open an issue here on Github.

This information includes Spyder version, operating system, dependencies information and several other things. Without it we are not able to understand and solve Spyder bugs as efficiently as we would like to.

Because of that, I'm going to close your report, and ask you to open a new one with that information filled.

Thanks for understanding :-)
