### ISSUE TITLE
Load session makes Spyder crash

### ISSUE THREAD

**Issue by chulapo** [spyder-ide/spyder#3096]
I did 'Save session and quit' and then after opening Spyder again I did 'Load session'.
Selected the file to load, and then got a crash and restart of Spyder.
Sincerely,
Rafael

**Comment by ccordoba12** [comment]
Thanks for reporting this bug. Unfortunately, it seems you dismissed the information asked by our issues template, i.e. the information we ask our users when they try to open an issue here on Github.

This information includes Spyder version, operating system, dependencies information and several other things. Without it we are not able to understand and solve Spyder bugs as efficiently as we would like to.

Because of that, I'm going to close your report, and ask you to open a new one with that information filled.

Thanks for understanding :-)

**Comment by chulapo** [comment]
I apologize for inconvenience. Actually I have not dismissed the
information by the issues template.
Actually, I did click on Help>Report Issue and then a GIT screen showed up
directly.
I am pretty new to Spyder, so it may be that I do not know where to enter
the issue properly.
Would greatly appreciate any assistance.
Sincerely,
Rafael

**Comment by ccordoba12** [comment]
Ok, please open the green **New issue** button on the top, and after that you'll see template with information for you to fill.

It seems you're using an old Spyder version that doesn't have the template incorporated in

    Help > Report issue

Thanks for your patience :-)
