### ISSUE TITLE
spyder crashes on ubuntu 15.10

### ISSUE THREAD

**Issue by teymuri** [spyder-ide/spyder#3126]
I am new to using spyder. It happened now for some times that it crashes if i hit F5 to run the code. In the IPython console it prints: "It seems the Kernel died unexpectedly. Use restart kernel to continue use this console".  And it goes on printing this, so i should close spyder and start it again. What can i do and why is this happening? I have installed spyder using the ubuntu software center.

Can any one help?

**Comment by ccordoba12** [comment]
Thanks for reporting this bug. Unfortunately, it seems that either:

1. You're using a Spyder version older than 2.3.5.2 and you used the *Report bug* button present on Spyder's Help menu.
2. Or you dismissed the information asked by our issues template, i.e. the information we ask our users when they try to open an issue here on Github after they press the *New issue* green button.

This information is critical for us and it includes Spyder version, operating system, dependencies information and several other things. Without it we are not able to understand and solve Spyder bugs as well and efficiently as we would like to.

Because of that, I'm afraid I'm going to close your report, and kindly ask you to open a new one with that information filled.

Thanks for understanding :-)
