### ISSUE TITLE
Check : Profiler unable to find modules

### ISSUE THREAD

**Issue by cpashartis** [spyder-ide/spyder#3161]
I'm trying to use the profiler for the first time and have noticed that the following error comes up:

> import pymatgen as pm
> ImportError: No module named pymatgen

Is this still the same bug as #2378 ? If not how do I fix it? The code runs normally otherwise from within Spyder.
# Generic Reproduction
1. Download pymatgen
2. Write a script containing

<pre><code>import pymatgen as pm
pm.Element.from_Z(10)</code></pre>

1. You should (hopefully) get the profiler error as well.
## Versions and main components
- Spyder Version: 2.3.7
- Python Version: 2.7.10 64bit
- Operating system: 10.10.5
## Dependencies

pymatgen library [https://github.com/materialsproject/pymatgen]

**Comment by jitseniesen** [comment]
Do you get an `ImportError` if you run the script from within Spyder without using the profiler? What about if you run the script without using Spyder?

**Comment by cpashartis** [comment]
Runs fine without the profiler as well as simply running the script without spyder. I haven't the foggiest what is causing this.

**Comment by oscargus** [comment]
It seems like PYTHONPATH is not set when running the profiler. I have a related issue with profiling code I am developing, where the default library is loaded rather than the one in the PYTHONPATH.

I added the following piece of code to my code to be profiled:
``` python
import os
try:
    user_paths = os.environ['PYTHONPATH'].split(os.pathsep)
except KeyError:
    user_paths = []
print(user_paths)
```

This prints `[]` so it seems like the setting of paths does not work (I have two paths in my PYTHONPATH). At least on Windows 10.
