### ISSUE TITLE
DMGs for Spyder 2.3.9

### ISSUE THREAD

**Issue by durack1** [spyder-ide/spyder#3172]
Hi folks, just wondering whether `*.dmg` and `*.exe` files will be made available for the latest [Spyder 2.3.9 release](https://github.com/spyder-ide/spyder/releases/tag/v2.3.9)?

**Comment by ccordoba12** [comment]
Creating DMGs is a very lengthy process for me (usually 1 day), even though (almost) everything is automated :-) The problem is with updating all the packages that come with the DMG, that sometimes introduce incompatibilities and crashes.

Given that 2.3.9 is such an small release and that 3.0 is going to be ready soon (1 month or so), I prefer to invest my energies in the last one :-)

I hope you understand.

**Comment by durack1** [comment]
@ccordoba12 no problem, is there another way that I can test out and provide some feedback on `2.3.9` - is it available in anaconda for `OS X`?

**Comment by ccordoba12** [comment]
Yes, it is :-)
