### ISSUE TITLE
No spyder 3.0.0b3 in conda win-64 channel

### ISSUE THREAD

**Issue by s-weigand** [spyder-ide/spyder#3207]
## Description of your problem
The new spyder beta (3.0.0b3) wasn't found in the conda win-64 channel.

**What steps will reproduce the problem?**

`>conda install -c spyder-ide spyder==3.0.0b3`
`Using Anaconda Cloud api site https://api.anaconda.org`
`Fetching package metadata: ........`
`Solving package specifications: .`
`Error:  Package missing in current win-64 channels:`
`  - spyder ==3.0.0b3`

`You can search for this package on anaconda.org with`

`    anaconda search -t conda spyder ==3.0.0b3`

## Versions and main components

* Spyder Version: 3.0.0b2
* Python Version: 3.5.1 x64
* Operating system: Win7 x64

**Comment by ccordoba12** [comment]
I'm sorry but we're in a bit of a hurry right now. I'll upload packages for beta4, to be released in a couple of days :-)

**Comment by nevion** [comment]
@ccordoba12  updating the release page first and having the update checker report this was irresponsible.  I went on a wild goose chase and then had to repatch the broken out of the box b2 spyderlib/backend code.  Thanks for your efforts otherwise, though.

Please post b3 if it's not too much time to generate, or b4.  Keep in mind you said couple of days 11 days ago and this bug was opened 16 days ago.

**Comment by ccordoba12** [comment]
Sorry, I didn't see too much demand for our previous beta from Windows users, so I decided to prioritize my time on keep finishing what we need to do to release Spyder 3.0 ;-)

**Comment by oshribr** [comment]
Hi, can you give us an ETA for this issue please ?

**Comment by Nodd** [comment]
You can look at the beta4 status on this page: https://github.com/spyder-ide/spyder/milestones/v3.0beta4
So yeah, *soon*.
