### ISSUE TITLE
Shortcuts for external plugins can't be registered

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#3254]
Since #3235 and specifically https://github.com/spyder-ide/spyder/pull/3235/commits/2cee5fe389964b9dd89c5eb4bcc7cf94af8decf5, it's not possible for external plugins to define shortcuts.
For example I can't define in the vim plugin that `Esc` trigger the command mode.

I think we should allow defining default shorcuts for external plugins, but check if it's not already used, and in this case ask the user to change the shortcut.

**Comment by ccordoba12** [comment]
You should be able to use `CONF.set` to set shortcuts for external plugins. Is that not possible now? 

Besides, I'd say `Esc` is a fixed shortcut for Vim users (not a configurable one) so you should use the `fixed_shortcut` function to set it (instead of trying to save it in `spyder.ini`). That function is present in `config/gui`.

----

By the way, I had to remove setting default values because it was not letting us to change the context of our shortcuts in `config/main`.

**Comment by Nodd** [comment]
It works fine for vim with `fixed_shortcut`, thanks.

I managed to make it work for line profiler with a configurable shortcut.However `CONF.set` is very low-level, and I don't think that it can be the recommended way to set a shortcut in a plugin. Here is what it looks like:
```python
        lineprofiler_act = create_action(self, _("Profile line by line"),
                                         icon=self.get_plugin_icon(),
                                         triggered=self.run_lineprofiler)
        lineprofiler_act.setEnabled(is_lineprofiler_installed())
        CONF.set(section="shortcuts",
                 option="Line Profiler/Run line profiler",
                 value="Shift+F10")
        self.register_shortcut(lineprofiler_act, context="Line Profiler",
                               name="Run line profiler")
```

**Comment by ccordoba12** [comment]
We could add an additional option to `register_shortcut`, but i can't think of a good API right now. What do you propose?

However, I'd prefer for external plugins to set their shortcuts as fixed too. That way we are less prone to have shortcut conflicts in the future. What do you think?

**Comment by goanpeca** [comment]
>We could add an additional option to register_shortcut, but i can't think of a good API right now. What do you propose?

Sounds like a good idea, then we can check if the shortcut option exists in the configuration file and if the extra value for the actual shortcut is not provided then we should raise an error.

```python
# This fails for a newly registered shortcut (that did not exists in the configuration already
        self.register_shortcut(lineprofiler_act, context="Line Profiler",
                               name="Run line profiler", value=None)

# This fails for a newly registered shortcut (that did exists in the configuration already)
        self.register_shortcut(lineprofiler_act, context="Line Profiler",
                               name="Run line profiler", value='Shift+10')

# This works for a newly registered shortcut (that does not exists in the configuration already)
        self.register_shortcut(lineprofiler_act, context="Line Profiler",
                               name="Run line profiler", value='Shift+10')
```

Something like that?

**Comment by Nodd** [comment]
It wouldn't work very well: the plugin would have to check itself if the value exists, the use one form or another. I think it's better if `value` is actually `default`: if the shortcut is already defined, use what is defined, otherwise use the parameter.

There is another problem with shorcuts and plugins: they are stored in the main config file but can't change the config file version. If you install a plugin which defines a shortcut then remove it, the shortcut still appears in the preferences table because it's loaded from the config. I see two solution:
* Store each plugin config into its own file. I don't know how big the changes would be.
* Load shortcuts from the config file only if the associated action exists. The problem is that the config is loaded early so that widgets can access the config values.

**Comment by ccordoba12** [comment]
> I think it's better if value is actually default

We're not going to return to `default` values because:

1. Default values are used for transient config options, i.e. options that depend on user actions (e.g. recent files, or run options associated with a file) or options whose values we don't want to update in the future.
2. The use of default values doesn't let us update our config options by doing an update in CONF_VERSION because that depends on the values registered in `config/main.py`, and default values are not registered there.
3. Default values are untraceable by us and can lead to conflicts in the future.

> There is another problem with shorcuts and plugins: they are stored in the main config file but can't change the config file version

Because of this I think external plugins should define (for now) fixed shortcuts instead of configurable ones, at least until we can come up with a better solution.

What do you think @Nodd?

**Comment by Nodd** [comment]
For default value it was just to embed the code I posted before so that it's easier to use. Ideally it would be used for external plugins only (once the config storage is fixed).
To comment on your points:
1. Default values are not used anymore so I don't understand what you are referring to. It is how it was before ?
2. Yup
3. I don't think we'll be able to completely avoid conflicts. The thing is to detect them and ask the user what he wants to do (which one he wants to keep).

Note that the pylint plugin is currently cheating, because it defines a shortcut in `CONF`. So it's not really an external plugins shipped with spyder.

I agree that the *easiest* path is to use fixed shortcuts, but I predict that it will stay this way for a long time !

More generally about shortcuts, you seem to tend towards having most shortcuts fixed instead of configurable. Of course this is easier for us but users will want to customize their environment to their needs (see https://github.com/spyder-ide/spyder/issues/3276#issuecomment-230355796 for example). If the conflicts are managed properly I don't see any problem in letting the user configure spyder as he wants. Also I don't recall many issues where there was a shortcut conflict (except for the one I just linked, actually).

To conclude, yes I will use fixed shortcuts for now (since I develop the plugin I can set them how I want :smiling_imp: )

**Comment by ccordoba12** [comment]
We have decided to remove `fixed_shortcuts` for Spyder 4.0, so we need to find a way lo let external plugins to register configurable shortcuts.

It seems the easiest solution is just to leave the `fixed_shortcut` function for external plugins. @jitseniesen, what do you think?

**Comment by jitseniesen** [comment]
> It seems the easiest solution is just to leave the `fixed_shortcut` function for external plugins. 

It is the easiest, but I wouldn't call it a real solution. :) As Nodd said above, plugin shortcuts will clash, especially when others start to write plugins, and that is really what we want (otherwise, why have plugins?). And users will want to change shortcuts.

But I think a real solution requires us first to decide (and implement) how plugins store their user config.

**Comment by goanpeca** [comment]
Note to self: Move configuration management to the API so plugins can call this directly and the api will handle the different things needed.
