### ISSUE TITLE
The distinction between "working directory for newly opened consoles" and "working directory for current console" is hard to understand

### ISSUE THREAD

**Issue by ChristianKleineidam** [spyder-ide/spyder#3257]
Currently Spyder has at the top of the UI a line that specify the working directory for newly opened consoles.
As a new user I would have expected it also to switch the current working directory and got confused about how to set my working directory. Currently the menu also doesn't offer a menu point of "set working directory".

I think it would be easiest if the top of the UI always shows the current working directory.

Alternatively the UI could show _(current working directory)_ or _(not currert working directory)_ directly after the file path.

**Comment by nerdfever** [comment]
Agreed. Closely related issue: https://github.com/spyder-ide/spyder/issues/2030

Much of this could be fixed by simply rewording the prompts and dialog boxes (using clearer, more consistent terms).

**Comment by malliwi88** [comment]
Hi, @ChristianKleineidam @nerdfever 

Which Spyder version you have?

Actually (In Spyder v3.0.1),  Preference UI looks like as:

![preferences_001](https://cloud.githubusercontent.com/assets/5307894/19666494/6455daf6-9a10-11e6-83a6-c35f9050c599.png)

![preferences_002](https://cloud.githubusercontent.com/assets/5307894/19666497/684054c0-9a10-11e6-8eb0-6ee2da462413.png)

Could you say us: If the clarifications on the current user interface, meets your expectations or not? and because?. 

We appreciate your recommendations to improve spyder in this regard and further solve your issues. :)

**Comment by nerdfever** [comment]
@malliwi88 Thanks for looking into this issue.

If you read thru the other comments on related issues (linked above), I think it's pretty clear that most of the problem comes from use of unclear or inconsistent terms.

The Python os module defines os.getcwd(). "cwd" stands for "current working directory".

So to be consistent with the os module, I think the term "current working directory" should be used.

So re Preferences>Run: 

1 - I'm _still_ not sure what "Default working directory" does, but if in fact it controls the current working directory (cwd) when Spyder starts, then:

"Default working directory is:" >>> "Default working directory (the current working directory when Spyder starts) is:"

2 - It's still not clear to me where "the script directory" is. I have _many_ scripts in many directories - which directory is this referring to? 

3 - I don't think the checkbox "Enter debugging mode when..." belongs in this list, as if it's a 3rd choice for the default working directory.

Re Preferences>Global working directory:

1 - The description is pretty good, I think.

2 - In two places this menu uses the term "current file directory". Is that the same or different from the "current working directory"? If it's the same, call it that. If not, describe what it is.

3 - What is a "file base directory" (last box in the dialog box)? Is this the same as the "global working directory" or the "current working directory" or the "current file directory"? I find it completely unclear - the dialog box uses 4 different terms to describe somewhere between 2 and 4 concepts.

Whatever it is, if it's one of the previously defined directories, call it by the same term used above. If it's a different thing, describe what it is.

I hope this is helpful.

**Comment by nerdfever** [comment]
Perhaps it would be useful, as part of an overall review of Spyder's UI, to make a glossary of terms used in menus and dialog boxes.

Any time you find two or more terms referring to the same concept, clean it up (pick one term, use it consistently, and make sure it's clearly defined what it means).

**Comment by malliwi88** [comment]
I agree that the UI can be confusing in two cases:

* Due to unfamiliarity with Spyder.
* And little information about it on the website and documentation (Actualization coming soon).

I hope to resolve your doubts at the moment with this demonstrative example :wink: 

## some important details for my demonstrative example:

* I have two files locate in differents folders on my machine as well
![seleccion_003](https://cloud.githubusercontent.com/assets/5307894/19668458/9cb70bf6-9a1d-11e6-95bd-5e0afb5d8f55.png)

* And this configuration on (preferences -> Run):
![seleccion_004](https://cloud.githubusercontent.com/assets/5307894/19668524/0f38fd42-9a1e-11e6-8f04-4bd2b17b8c49.png)

* And this configuration on (preferences -> Run):
![seleccion_005](https://cloud.githubusercontent.com/assets/5307894/19668573/5959d00e-9a1e-11e6-9e45-66b3fa1b787d.png)

Ok!! Start with the example!!! For solve in order of your last post:

**you**: So to be consistent with the os module, I think the term "current working directory" should be used.
> ans-> The term **Global directory** at the moment refers to the folder that Spyder uses at moment to start. So this is used for this things:
> * Run a new Python/IPython console, the **Spyder Global directory**  is your **working directory** for this new console :+1:  As you can see here
![seleccion_006](https://cloud.githubusercontent.com/assets/5307894/19668614/96ff9812-9a1e-11e6-91b9-a588860a8177.png)

## So re `Preferences>Run`:

1. **"Default working directory is (I selected: Execute in current Python/IPython Console!!!):"** 
> * IIf you run code directly on this consoles, it's the same **Global Spyder directory** (My case /home/wallas/Documents) as you can see above. :point_up: 

2.  **script directory is** 
> * If you run a Script **current directory** automaticly changes to **path where the file is** (If you remember, It was my configuration in `preferences -> Run` ) :point_up: 

>> **Please, read All highlighted text in next picture for you can understand better my example** 
:+1: 
![seleccion_007](https://cloud.githubusercontent.com/assets/5307894/19669167/bceefeb0-9a22-11e6-936f-4d82250f6e7b.png)

3. **  "Enter debugging mode when..."**
> * I'm not sure at the moment. But I think it has to do with the idea of an external debugger for Spyder (It's an idea in development yet). @ccordoba12 @goanpeca - Maybe we should hide this checkbox at the moment? - What do you think?

## Re `Preferences>Global working directory`:
1. **The description is pretty good, I think.** Ok, Great!!! :+1: 
2. ** In two places this menu uses the term "current file directory". Is that the same or different from the "current working directory"? If it's the same, call it that. If not, describe what it is.**

> It's depends on your configurations!. I choose:
>> * The first One **In Open File** ->  the current directory (It's the path when you go to File -> open)

>>> This option is here because some people should prefer opens only files located on **Spyder Global Directory** (You remember, Just in my example, it is on: `/home/wallas/Documents`)

>> * The Second One **New File -> Spyder Global directory (in my example)**

>>>  It will be the path where new file will be created (Only created, not saved!!!), when you go to `File -> New File` 

3. **What is a "file base directory" (last box in the dialog box)? Is this the same as the "global working directory" or the "current working directory" or the "current file directory"? ** 

> Yes, In my opinion, these options in check box **file base directory** are quite redundant.
However, those are disabled by default on Spyder configuration. Those options only guaranty two things:
*  **(When you Open a file)** ->> Use the parent path of your Actual File If you have a file open in your editor
* **(When you Save a file)** ->> Use the parent path of your last one File opened (If you have a file open in your editor)

I will be reporting this redundant option in this moment @ccordoba12, @goanpeca, fot know your opinions about this.

Not being more, for now. I hope this lengthy example solve your confusion and many other users.

I think this anger for the project wiki;)

Best regards @nerdfever @ChristianKleineidam

**Comment by malliwi88** [comment]
@goanpeca the last example, Is it useful for the wiki page? or It's irrelevant.

**Comment by nerdfever** [comment]
@malliwi88 Thanks! This is very helpful re explaining how Spyder works. But still some things are not completely clear. (And of course this needs to be explained to other people who don't find this thread.)

1 - Re "Default working directory" (dwd) and "current working directory" (cwd):

If I understand correctly,

**cwd**  is the directory files will be opened in if no directory is explicitly specified. For example:

f = open("myFile.foo")

Python looks in the cwd for file "myFile.foo".

**dwd**  is the cwd that Python will use when Spyder executes a script (doesn't matter if normal execution or debug execution, correct?).  So if I'm editing "u:\data\projects\MyProgram.py" and then run it, if the first lines of that script reads:
 
  import os
  print( os.getcwd() )

If "the script directory" was selected in Preferences, this prints:

  "u:\data\projects"

If "the following directory" was selected in Preferences and set to "x:\somePlace\orOther", then the script prints:

  "x:\somePlace\orOther"

Do I understand correctly? (If you confirm, I'll propose wording for the Preferences box to try to make this clear - I'm a native English speaker.)

2 - "the script directory" means _the directory that stores the script being executed_ by Spyder.  (Again, doesn't matter if normal execution or debug execution, correct?). It has _nothing to do with the location of files being edited_ - only of the file being executed. 

Correct? (again, if you confirm I'll try to propose wording to make this more clear)

3 - My interpretation of "file base directory" in my earlier post of this thread was correct.  It refers to the directory where the **file being opened for editing**, or **saved from the editor**, is stored. 

Correct?

4 - I'm still not sure what "current file directory" means - I don't think you addressed that point in your post. I'm guessing it means cwd. 

Is that correct? If so, it should be called "current _working_ directory" (not current _file_ directory).

Thanks again for working on this problem.

**Comment by DanCodigaMWRA** [comment]
I have found these issues confusing as well. I think it would be very helpful to implement the suggestions from nerdfever.

**Comment by malliwi88** [comment]
**1-2** 
I could say that the behavior is similar to that of any office tool (MS Office or OpenOffice), by default always when opening or saving in My Documents (**dwd** for you), when you type the **cwd** is a temporary route that you never know, but Once you save the file somewhere on your computer, that path becomes **cwd** for what you type on the document and **dwd** to open a new document.

The only difference is that in spider gives you the possibility to choose a **dwd** of your preference different from my documents, for when you open new python files, precisely indicating your desired path `on preferences-> StartUP-> the following directory`
**3** - Yes
**4** - If you run a Script current directory automatically changes to path where the file is (If you remember, It was my configuration in preferences -> Run )

**Comment by DanCodigaMWRA** [comment]
The discussion here seems closely related: https://groups.google.com/forum/#!msg/spyderlib/HWCeeO8Tc7o/N_9cfh82AwAJ

**Comment by ccordoba12** [comment]
@rlaverde, please work on this one.

As we mentioned in the sprint, the idea is to synchronize the working directory toolbar, the file explorer and the `%cd` magic in the IPython console, so that at any moment a change on any of them appears reflected in the working directory toolbar.

Besides, after changing consoles, the toolbar needs to be updated too to show the cwd of the new console.
