### ISSUE TITLE
Spyder anaconda and system library conflict

### ISSUE THREAD

**Issue by ilkerhk** [spyder-ide/spyder#3307]
## Description of your problem
Looks like Spyder 3 is seeing the wrong _bootstrap.py in my system even the anaconda path is the first entry in my $PATH environment variable.  Anaconda documents says setting only PATH is sufficient for anaconda. Which paths and/or environment variables  is Spyder using besides $PATH ?   

**What steps will reproduce the problem?**
1.  I already have installed python3 from linux repos. 
2.  Install anaconda. Ugrade to Spyder 3.0b4
3. Run Spyder

**What is the expected output? What do you see instead?**
I am getting : /usr/lib64/python3.4/importlib/_bootstrap.py:321: RuntimeWarning: compiletime version 3.5 of module 'mtrand' does not match runtime version 3.4

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3 beta 4
* Python Version:  3.5.2
* Operating system: Opensuse Linux

**Comment by jitseniesen** [comment]
It should be possible to have different python versions from the OS and Anaconda, and on my system I do only need to change $PATH. 

What happens if you run python (Anaconda's python) and type `import numpy` and `import numpy.random` ?

If you look in the file that you execute when running spyder, does the first line refer to the same python as you tried above?

And just to check: the RuntimeWarning is the only message you get? And Python 3.4 is the version installed by Opensuse?

**Comment by ilkerhk** [comment]
Jitseniesen,
Thanks for the reply. Both Anaconda and system version seemed running fine from the a bash terminal. Yes 3.4 is the version on Opensuse. Imports are also fine from consoles over bash. 

When I deleted .spyder-py3 folder now it works fine. It might be possible that I messed up with my settings while trying to fix some other problem. 

Thanks again for the reply.
