### ISSUE TITLE
Installation on Windows10

### ISSUE THREAD

**Issue by stflustop** [spyder-ide/spyder#3445]
## Description of your problem

**What steps will reproduce the problem?**

1. Installation ArcGIS 10.4.1 with Python 2.7 in c:\python27
2. Installation Spyder

**What is the expected output? What do you see instead?**
The installation stops with tehe message: Python version 2.7 required, which was not found in the registry.
Whitch registry-key is needed?

**Please provide any additional information below**
-

## Versions and main components

* Spyder Version: 2.3.8
* Python Version: 2.7
* Operating system: Windows10

![error](https://cloud.githubusercontent.com/assets/16152377/18780572/81682716-817e-11e6-8867-bc88c97c3327.jpg)

**Comment by ccordoba12** [comment]
Two things are happening here:

1. I don't understand why the Python version that ArgGis installs is not detected by Spyder. Maybe it's not made available to other Python programs. That's why the installer complains about not finding Python in the system :-)
2. We won't support our Windows installers in the future. Please see our README on how to install Spyder on Windows now.

**Comment by stflustop** [comment]
thank you for the answer. 
we go to Anaconda
