### ISSUE TITLE
Break plugin creation into a spyder/api module for better decoupling and organization

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#3448]
Move the content from

https://github.com/spyder-ide/spyder/blob/master/spyder/plugins/__init__.py

To
https://github.com/spyder-ide/spyder/blob/master/spyder/api/plugins.py

This will more easily decouple what can be extended in spyder and what cannot.

For backwards compatibility plugins using the old way will still continue to work while we make the migration

----

And yes this is just a first step of other decoupling work in progress @Nodd  ;-)

**Comment by goanpeca** [comment]
@rlaverde

**Comment by Nodd** [comment]
This file is only a minor part of the problem. For example if you want to interact with the editor you have to crawl in spyder's internals to do anything. Spyder was not built with this decoupling in mind. There is no public or private api inside spyder, this is where the real problem is.

Moving the file will only change the import line when declaring a plugin. I don't think it's really useful considering the big picture: plugin devs will expect to have the whole spyder api in `spyder.api`. At least `spyder.plugins` is explicit.

I'm not against this change, but that would be for spyder 4.0 !

**Comment by ccordoba12** [comment]
@Nodd, I think this is just the first step.The idea is to move every public interface to `spyder.api`.

And (of course :-) this is for 4.0 (as it was marked in the milestone).

**Comment by Nodd** [comment]
Sorry, I didn't see the milestone on my phone. +1 then.

**Comment by goanpeca** [comment]
@Nodd, stop trolling :laughing:
