### ISSUE TITLE
Fix menus in macOS

### ISSUE THREAD

**Issue by tienhv** [spyder-ide/spyder#3484]
## Description of your problem

**What steps will reproduce the problem?**

1. Install Spyder 3 on Mac os 10.11, PyQt5

**What is the expected output? What do you see instead?**

There are icons on menu. However, they are disable by defaults, from issue  #2289 
<img width="209" alt="screenshot 2016-09-29 14 28 28" src="https://cloud.githubusercontent.com/assets/9072983/18963852/e080722e-8676-11e6-9239-d6e8574616f8.png">
The question is what I do to bring back the icons on menu?
**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3
* Python Version: 2.7.12
* Operating system: Mac 10.11

## Dependencies
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.4.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  0.6.1 (OK)
psutil >=0.3     :  4.3.0 (OK)
pyflakes >=0.5.0 :  0.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.4.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
@tienhv, it seems you're new to macOS. As all other Mac applications, Spyder tries to adhere to the [Human Interface Guidelines](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/OSXHIGuidelines/MenuAppearanceBehavior.html#//apple_ref/doc/uid/20000957-CH23-SW1) of Apple, which don't allow icons in menus. So please stop requesting that we do it because we want Spyder to look as well as all other Mac applications :-)

What we can do instead is fixing the odd placement of some menu entries. And that's what @goanpeca is going to do in a future release :-)

**Comment by danche354** [comment]
@ccordoba12 hello, I wonder why we can not use font "Monaco" in Spyder in OS X? There are only 5 fonts in anaconda distribution.....

**Comment by goanpeca** [comment]
@danche354 could you open a new issues, this issue has nothing to do with fonts ;-)
