### ISSUE TITLE
IPython console startup file / run lines not working

### ISSUE THREAD

**Issue by dstrozzi** [spyder-ide/spyder#3494]
## Description of your problem

Ipython console startup settings specified in spyder preferences, or my ipython startup file, don't work.

**What steps will reproduce the problem?**

First issue - startup code in ipython_config.py is processed when I start ipython from a prompt, but not in Spyder.

2nd issue - Preferences -> Ipython Console -> Startup -> Run a file isn't run.  I have a print statement, nothing is printed.  Also a magic line to set precision of printed numbers, doesn't work.

3rd issue - content of "run code" dialog box isn't run.

**What is the expected output? What do you see instead?**

ipython startup stuff to happen, it doesn't.

**Please provide any additional information below**

OK so the real issue is I want to control the precision of printed numbers in ipython console in spyder.  Without having to type %precision %.4g every time.

## Versions and main components

* Spyder Version: 3.0.0
* Python Version: 3.5.2
* Operating system: Windows 7, anaconda dist., all up to date as of 2 oct 2016.

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
* `ipython_config.py` is not run anymore because it's specific to Python. Please use the Jupyter configuration files instead.
* @jitseniesen, could you check what's happening here?

**Comment by jitseniesen** [comment]
Hmm, some commands work, but some don't.

If you put the statement `x=1` in either the startup file (set in Preferences -> IPython Console -> Startup -> Run a file) or the startup code (set in Preferences -> IPython Console -> Startup -> Run code), then this is executed as expected, and `x`  has the value 1 in the IPython console. So it's not all broken. :smile:

A print statement in either of these places has no effect. A `%precision` statement also has no effect.

However, if you run an IPython console outside Spyder and specify a startup file using the IPYTHONSTARTUP environment variable, the behaviour is the same: `x=1` has an effect, but `print()` and `%precision` do not. Reading ipython/ipython#7950, I think it may not be our fault.

I don't know how the IPython console in Spyder works, so I'm not going to investigate this further at the moment.

**Comment by jitseniesen** [comment]
http://shawnleezx.github.io/blog/2015/08/03/some-notes-on-ipython-startup-script/ suggests that you cannot use IPython magic (like `%precision`) in startup scripts.

**Comment by ccordoba12** [comment]
Thanks a lot @jitseniesen for checking this out!! About your remark, the IPython console in Spyder works in a very similar way to what you get when you run `jupyter qtconsole`, but with some internal additions to connect each console to the other Spyder plugins.

@dstrozzi, you need to use this file as startup file for `%precision` to work

```python
from IPython import get_ipython
ipython = get_ipython()

ipython.magic("precision %.4g")
```

`print` statements (as @jitseniesen noted) don't work, but that's not Spyder's fault, it's just the way IPython works :-)

**Comment by dstrozzi** [comment]
OK, I finally got around to this.  Making my own startup file with the
lines from Carlos does indeed work.  Thank you!

**Comment by mi44164** [comment]
I am executing my code on  Spyder IDE and it does not show me on the console as an OUTPUT.

whats should I do in this case?

**I am executing below code.**

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


import statsmodels.api as sm 
X = np.append(arr = X, values = np.ones((50,1)).astype(int), axis = 1)
X_opt = X[:, [0, 1, 2, 3, 4, 5]]
#Our X_opt array has a dtype of object and this may be causing an error. Try changing it to float.
X_opt = np.array(X_opt, dtype=float)
regressor_OLS = sm.OLS(endog = Y, exog = X_opt).fit()

and I am looking P- Values as an output but it shows me blow line instead of P-values.

runfile('C:/Users/lenovo/Desktop/ML/Python/Part 2 Regrassion/Section 7 - Multiple Linear Regression/Python/01 Multiple linear regression.py', wdir='C:/Users/lenovo/Desktop/ML/Python/Part 2 Regrassion/Section 7 - Multiple Linear Regression/Python')
