### ISSUE TITLE
Add multiple edgelines options in settings window

### ISSUE THREAD

**Issue by rlaverde** [spyder-ide/spyder#3592]
After #3512 edgeline widget support several lines with different colors. But this functionality isn't exposed through settings window.

How this should be done?
- Settings `'edge_line': True, 'edge_line_column': 79` changed by a list `'edge_line': [72,79]`?
- another option for colors `'edge_line_colors': []`? or this colors will be part of the syntax color scheme?
- How It'll look like in the settings page?

**Comment by goanpeca** [comment]
@ccordoba12 what do you suggest?

We could do 'edge_line': True, 'edge_line_columns': [79, 89]

So we change edge_line_column to edge_line_columns and avoid some problems moving forward?

**Comment by ccordoba12** [comment]
> Settings 'edge_line': True, 'edge_line_column': 79 changed by a list 'edge_line': [72,79]?

I agree with 'edge_line_columns: [79]` in `config/main.py`. Having `72` for docstrings is nice, but it shouldn't be the default because I think most people (especially newbies) don't know about that convention.

Besides, we should adjust the pep8 config to follow this setting too.

> another option for colors

Let's not add different colors, that can be confusing.

> How It'll look like in the settings page?

It could be a combo box with a list of columns separated by commas, like this option

    IPython Console > Startup > Run Code

**Comment by goanpeca** [comment]
@ccordoba12 
>It could be a combo box with a list of columns separated by commas, like this option

You meant textbox?

**Comment by ccordoba12** [comment]
Yep, sorry :-)

**Comment by goanpeca** [comment]
@rlaverde you can work on this then :-p
