### ISSUE TITLE
Console's message

### ISSUE THREAD

**Issue by RiMer** [spyder-ide/spyder#3603]
## Description

**What steps will reproduce the problem?**

1. Starting anaconda-navigator
2. 
3. 

**What is the expected output? What do you see instead?**
libpng warning: iCCP: known incorrect sRGB profile

**Please provide any additional information below**
What do this mean and if there is something to do

## Version and main components

* Spyder Version: 3.0.0 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment]
This is a harmless message, please don't worry about it :-)

**Comment by RiMer** [comment]
Ok, thank you

**Comment by PanderMusubi** [comment]
Nevertheless, there is a solution for it and it will prevent this unneeded cluttering of everybody's command line.

The cause of this are the PNG files which are embedded in SVG files:
- https://github.com/spyder-ide/spyder/blob/master/spyder/images/options.svg
- https://github.com/spyder-ide/spyder/blob/master/spyder/images/winpython.svg
- https://github.com/spyder-ide/spyder/blob/master/spyder/images/spyder.svg
- https://github.com/spyder-ide/spyder/blob/master/spyder/images/splash.svg

The PNG files need to be extracted from the SVG files, e.g. with [Inkscape](https://inkscape.org/). There may be more than one PNG per SVG file. Than fix these PNG files with [ImageMagick](https://www.imagemagick.org/script/index.php). Lastly, replace the existing PNG files in the SVG file with the fixed PNG files.

The extracted images are fixed with:

    convert in.png out.png

The resulting SVG files can be optimized with [svgo](https://www.npmjs.com/package/svgo). This will remove all Inkscape specific SVG (while it can still be editted by Inkscape) and speed up loading of the images by Spyder application.

**Comment by ccordoba12** [comment]
@PanderMusubi, a pull request is welcolme to get that fixed.

**Comment by PanderMusubi** [comment]
With what editor have these files been created or later on been updated?

**Comment by ccordoba12** [comment]
Inkscape, probably.
