### ISSUE TITLE
Tab in-between find and replace text boxes

### ISSUE THREAD

**Issue by DStauffman** [spyder-ide/spyder#3674]
## Description of your problem
The tab key doesn't move the cursor from the find to replace text boxes as expected.

**What steps will reproduce the problem?**

1. Hit control-F to open find text box.  Type in some text.
2. Hit control-R to open replace text box.  Type in some other text.
3. Press shift-tab to move from replace box back into text box.
4. Press tab to move from text box back forward into replace box. (This step doesn't do anything)

**What is the expected output? What do you see instead?**
The tab to move from the text to replace box doesn't work.  You stay within the text box.  Pressing shift-tab to move backwards works as expected.

## Versions and main components

* Spyder Version: 3.1.0
* Python Version: 3.5.2
* Operating system: Win 7

I remember this working fine a while ago, but I've since noticed this on some earlier versions of Spyder.  It's finally started to bother me enough to open the issue.  Thanks for any help!

## Dependencies

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.19.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.8 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll improve this behavior in a future version of Spyder.

**Comment by mvbentes** [comment]
Would be nice to have some `Alt+letter` shortcuts to the actions. Replace all, for example, with `Alt+a`.

**Comment by CAM-Gerlach** [comment]
Hey, is this still being looked at by any chance? I was going to file an issue report myself on this if this one wasn't already open, as it is a pretty major problem on a regular basis. 

I'm not @ccordoba12 or one of the contributors (at least not yet, anyway...hopefully someday) putting in all the amazing effort here so its probably not my place to say, but if it was, IMO, I'd consider this a type:bug to be dealt with accordingly, as it breaks core UI functionality and basic user expectations—Tab's otherwise consistent behavior across the interface—and the real smoking gun is that Shift-Tab works to go back a field, as other commenters mention, but not Tab to go forward, which doesn't seem like it could possibly be intended.

**Comment by ccordoba12** [comment]
@rlaverde, please work on this one.

**Comment by ccordoba12** [comment]
@CAM-Gerlach, would you like to take a look at this one? I think it's an easy fix ;-)

**Comment by CAM-Gerlach** [comment]
Sure thing; was just thinking of taking a look actually.

**Comment by CAM-Gerlach** [comment]
> I think it's an easy fix ;-)

Not for a CAM like me...X)
