### ISSUE TITLE
Debugger: Current Line not Highlighted and Variable Explorer Not Synced

### ISSUE THREAD

**Issue by Davo36** [spyder-ide/spyder#3714]
When I run a script in debugging mode, buy pressing Ctrl F5, there are a couple of problems as per the issue title.

The first is that I'm sure as I've stepped through code in the past, the current line is highlighted in the editor.  Now it is not.

The second is that the variable explorer is not showing any variables from the currrent stack, it shows global variables only.

To reproduce the problem all I have to do is enter debugging mode for any script.

* Spyder Version: 3.0.1
* Python Version: 3.5.2
* Operating system: Windows 10

Dependencies:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. This is a duplicate of issue #3711, so I'm closing it.

**Comment by Davo36** [comment]
Ok, thanks very much, love the IDE by the way.

**Comment by serg3y** [comment]
Regarding "Current Line not Highlighted" i think there is room to improve...

Currently focus moves to the break point but then if i click somewhere else the highlight moves with cursor, and after a while I forget where the code is upto. I executed some stuff in the console too so that's not showing where i am upto either.

Perhaps we need a little green arrow, (separate to highlighting of the line where the cursor is now) that shows where code execution is up to, right there in the editor, next to the line number.... like MatLab... :) sorry, or another highlighter that does not move with the cursor.

* Spyder version: 3.2.8 
* Python version: 3.6.4
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating system: Windows 7

**Comment by ccordoba12** [comment]
> Perhaps we need a little green arrow, (separate to highlighting of the line where the cursor is now) that shows where code execution is up to, right there in the editor, next to the line number.... like MatLab... :) sorry, or another highlighter that does not move with the cursor.

Sure, this will be part of Spyder 4, to be released in 2019.
