### ISSUE TITLE
issue on indentation and request for new features

### ISSUE THREAD

**Issue by kalbhairab** [spyder-ide/spyder#3718]
1.  if we write def func(            then please return 
                         def func( | ):
2.  Also auto indentation not working in function.
3.  please put ctrl+enter to go to next line as in pydev ecllipse.
4.  If possible can you make a gui to generate matplotlib code for label, axis color, while doing right click on 
     code so that the ploting can be super fast.

**Comment by ccordoba12** [comment]
Thanks for your suggestions. About them:

1. It's hard to automatically add code (even if short) and cover all corner cases, so we prefer not to do it.
2. Autoindentation only works if you add `:` after the function definition. The same works for `class`, `if`,  `else`, etc.
3. This is going to be possible in the next version of Spyder (3.1) because we're going to give users the ability to assign `Ctrl+Enter` for other actions.
4. I answered in Gitter about it.
