### ISSUE TITLE
Save figures of histogram

### ISSUE THREAD

**Issue by WebbYang** [spyder-ide/spyder#3775]
Hi, 
I have a problem to find the output figure blank when saving matplotlib.pylab.hist under Spyder 2.3.9.
The IPython console can show the histogram plot.
If I execute python from cmd, the figure can also be saved correctly.
I don't know if there's some interface issue.
Thank you. 

Best regards,
Webb

**Comment by ccordoba12** [comment]
Could you post some simple Python code of what you're trying to plot and describe step by step what you're trying to do and what's not working for you?

Thanks!

**Comment by WebbYang** [comment]
Hi ccordoba12,
Thank you.
I just add ion() and savefig() from an example code.

`import numpy as np`
`import matplotlib.pyplot as plt`

`mu, sigma = 100, 15`
`x = mu + sigma*np.random.randn(10000)`
`n, bins, patches = plt.hist(x, 50, normed=1, facecolor='green', alpha=0.75)`
`plt.ion()`
`plt.show()`
`plt.savefig('testHistogram')`

If I run from Spyder, the testHistogram.png shows blank figure.
However, I can see the histogram plot from IPython console of the Spyder environment.
Also, if I execute from cmd, the testHistogram.png is good.

I found that if I comment ion() and show(), the figure saved successfully from both environment.
Maybe the ion() is the problem that makes the result different form Spyder and cmd.
Thank you.

Best regards,
Webb

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one.

**Comment by dalthviz** [comment]
Hi @WebbYang , reading the docs from mathplotlib, and playing around with the example code that you provide us, I can say that the problem was in the call of the `show()` function. As the docs say ["... you should call savefig() before calling show if you wish to save the figure as well as view it."](http://matplotlib.org/faq/howto_faq.html) in the `Use show()` section.

Also  I tried, as the docs say, to call first the `savefig()` function, and then the `ion()` and `show()` functions, it worked for me. Can you test if this order of calls solves the problem for you?. It's strange that with the cmd works without taking into account the order of calls, however probably will be enought changing in your code the order of the calls to be able to work with Spyder.

**Comment by WebbYang** [comment]
Hi @dalthviz , 
It works! Thank you.
I'll remember this order from now on.

Best regards,
Webb
