### ISSUE TITLE
File Switcher should search all project files and not only the open ones

### ISSUE THREAD

**Issue by talkaminker** [spyder-ide/spyder#3860]
Currently Ctrl+P fuzzy searches only the open files. in other editors (sublime, pycharm) it fuzzy searches the whole project so that you can easily find files regardless of whether they are open or not.

Since good implementation might be tricky, maybe you should somehow use [fzf project](https://github.com/junegunn/fzf)?

**Comment by ccordoba12** [comment]
@mariacamilaremolinagutierrez, I'm assigning this one to you but for 3.2, not 3.1 ;-)

@talkaminker, unfortunately `fzf` is made in Go, but we already have our own fuzzy search library.

**Comment by goanpeca** [comment]
@ccordoba12 is this going to v4.2 or v5 ?

**Comment by ccordoba12** [comment]
This is for Spyder 5.

**Comment by maurerle** [comment]
Just a finding:
Ctrl+Shift+P is used as the Print-Key on non OSX. Yet the Project Pane already has this Shortcut, so there already are shortcuts for:

* File Switcher -> Ctrl+P
* Project Pane -> Ctrl+Shift+P
* Printing -> Nothing

**Comment by ccordoba12** [comment]
Note: This problem is really complex and difficult to solve in pure Python. So now I agree that we should use `fzf` to solve it.

**Comment by degel123** [comment]
Guys any progress on that? It would save a lot of time

**Comment by ccordoba12** [comment]
Perhaps we'll have time to work on this before the end of the year.

**Comment by ccordoba12** [comment]
A few more details about how this could be implemented:

1. I think we need to create first a `SpyderPluginV2` for the switcher, so that it provides a public API that other plugins (in this case Projects) can rely on to populate it with the content they want to display there.
2. Then, we'd to implement a way to call [`fzf`](https://github.com/junegunn/fzf) with the query passed by the user in the switcher and gather the results it returns.
3. Finally we'd need to display those results in the Switcher.

Some important points to take into account are the following:

* This will only work for projects. In other words, if no project is active, then this functionality won't be available.
* We need to filter the results coming from `fzf` to only display plain text files because those are the only ones that can be handled by the editor.
