### ISSUE TITLE
Unavailable Multibyte language  (Mozc )

### ISSUE THREAD

**Issue by hk216** [spyder-ide/spyder#3905]
## Description

**What steps will reproduce the problem?**

1. from ANACONDA-NAVIGATOR  beta
2. Spyder launch 
3.in  iPython console , Unavailable Multibyte language  (Mozc )

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.0.2 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment]
I don't understand your bug report :-/

Please try to add more information on what you're trying to do and why Spyder is failing to accomplish that.

**Comment by hk216** [comment]
I'm sorry for  my few information. I use spyder by starting it from Anaconda-Navigator, and starting it independently. I can't iuse Multibyte language(Mozc) in IPython console in the former case. I can use it in the latter case. Why I can use it? I sent the mail to know the reasons. I would like to have an idea on how someone do that. Is the reason in Anaconda?

**Comment by ccordoba12** [comment]
This probably happens because you have some environment variables defined in your terminal that are only read when Spyder is started from it and not when it's started with the Anaconda Navigator.

If that's the case, there's nothing you can do about it for now but to always start Spyder from the terminal. We plan to fix this problem in Spyder 3.2.

**Comment by hk216** [comment]
Thank you very much for your advice. Anaconda-Navigator use Spyder 3.0.2. I will follow your advice. Now I use from my terminal Spyder 2.3.8 . and Python 3.5.2 32bits, Qt 4.8.7, PyQt4 (API v2) 4.11.4 on Linux. I will update Spyder 3.2. I don't know how Anaconda entertain my environment variables defined in my terminal.

**Comment by ccordoba12** [comment]
Spyder 3.2 will be released in three months, so it's not available yet. 

It also seems you have Spyder installed with Anaconda and your Linux package manager. That's why you have two different versions of it.

**Comment by hk216** [comment]
Thank you very much for your informative and helpful advice. The reason simply comes from the fact that I believe a revised version has functional capability, but previous version may be stabler than it, though  I don't give a specific example.

**Comment by sohnishi** [comment]
Dear @ccordoba12 , @hk216 
I guess that is the problem of Qt5 and input method framework.
hk216 could input in _Python 3.5.2 32bits, Qt 4.8.7, PyQt4_, but could not in _PyQt5 5.6_.
Because Qt5's input method model was changed drastically, some input method framework, for example uim, does not work correctly in Qt5. (So I'm using fcitx-mozc instead of uim-mozc these days.)
Installing [input-method-framework-name]-qt5 (ex. fcitx-qt5) might help if supplied by the distribution.

**Comment by ccordoba12** [comment]
@sohnishi, I don't quite understand what are those packages used for, and what you guys are trying to do with Spyder.

**Comment by sohnishi** [comment]
Hi @ccordoba12 , if my guess is correct, this problem has nothing to do with Spyder.

To input multibyte-characters, input method framework(uim, ibus, fcitx or so on) and input method editor(mozc, anthy...) are needed. Qt5 requires Qt5-compliant-version of input method framework(fcitx-qt5, not fcitx-qt4).
If @hk216  install fcitx-qt5 or uim-qt5(experimental) in his computer this probrem might be solved.
see http://stackoverflow.com/questions/25621349/how-to-use-imeinput-method-editor-with-pyqt5

However, this problem is difficult to be solved if the Qt5 is user provided newer version...

**Comment by ccordoba12** [comment]
I see. I hope the situation is improved for you guys in the next Ubuntu releases.

**Comment by hk216** [comment]
Der @ccordoba12, @sohnishi
Thunk you for your informations.
 I have already used Mozc(Fcitx) sorry to say.
The fcitx-mozc (2.17.2116.102+),  libfcitx-qt5-1 (1.0.5-1) has been installed by aptitude.
But I could'nt use Mozc(Fcitx) from spyder which called by Anaconda-Navigator, though could it from a terminal.
I can't understand the reason at this time.

**Comment by ccordoba12** [comment]
Thanks for your answers. I'm closing this bug because it's not related to Spyder.
