### ISSUE TITLE
Variable Explorer past (2.3.9) and present ( 4.0.0.dev0)

### ISSUE THREAD

**Issue by markuman** [spyder-ide/spyder#3947]
## Description of your problem

In 2.3.9 the variable explorer work with both, python and ipython console.  
In 4.0.0.dev0 is only with ipython console.

**What steps will reproduce the problem?**

1. Install 2.3.9 and 4.0.0.dev0 with Python 3.6.0
2. open new python console
3. enter `a = 1` and take a look at the variable explorer

## Versions and main components

* Spyder Version: 2.3.9, 4.0.0.dev0
* Python Version: 3.6.0
* Operating system: Arch Linux

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

### 4.0.0.dev0

    jedi >=0.8.1     :  0.9.0 (OK)
    matplotlib >=1.0 :  1.5.3 (OK)
    nbconvert >=4.0  :  5.0.0 (OK)
    numpy >=1.7      :  1.11.3 (OK)
    pandas >=0.13.1  :  0.19.2 (OK)
    pep8 >=0.6       :  1.7.0 (OK)
    psutil >=0.3     :  5.0.1 (OK)
    pyflakes >=0.6.0 :  1.4.0 (OK)
    pygments >=2.0   :  2.1.3 (OK)
    pylint >=0.25    :  1.6.4 (OK)
    qtconsole >=4.2.0:  4.2.1 (OK)
    rope >=0.9.4     :  0.9.4-1 (OK)
    sphinx >=0.6.6   :  1.5.1 (OK)
    sympy >=0.7.3    :  1.0 (OK)

### 2.3.9

    IPython >=1.0      :  5.1.0 (OK)
    jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
    matplotlib >=1.0   :  1.5.3 (OK)
    pandas >=0.13.1    :  0.19.2 (OK)
    pep8 >=0.6         :  1.7.0 (OK)
    psutil >=0.3       :  5.0.1 (OK)
    pyflakes >=0.6.0   :  1.4.0 (OK)
    pygments >=1.6     :  2.1.3 (OK)
    pylint >=0.25      :  1.6.4 (OK)
    qtconsole >=4.0    :  4.2.1 (OK)
    rope >=0.9.2       :  0.9.4-1 (OK)
    sphinx >=0.6.6     :  1.5.1 (OK)
    sympy >=0.7.3      :  1.0 (OK)
    zmq >=2.1.11       :  16.0.2 (OK)

### Screenshot 2.3.9

![spyder_2 3 9](https://cloud.githubusercontent.com/assets/3920157/21855206/df535fee-d81d-11e6-9a98-521d56852db9.jpg)

### Screenshot 4.0.0.dev0

![spyder_4 0 0 dev0](https://cloud.githubusercontent.com/assets/3920157/21855205/df523e52-d81d-11e6-9787-4c07f0597351.jpg)

**Comment by ccordoba12** [comment]
The reason for this change is that we are going to remove the Python console in Spyder 4, and disconnecting it from he Variable Explorer was the first step.

And we want to remove the Python console because:

1. Supporting two consoles is too much work for us (e.g. we need to maintain two quite different implementations to connect the Python and IPython consoles to the Variable Explorer).
2. It's broken on Windows with PyQt5 and we don't know how to fix it.
3. It has several shortcomings that don't allow us to improve several plugins (e.g. the history log, which is semi-broken right now).
