### ISSUE TITLE
Spyder is not starting

### ISSUE THREAD

**Issue by varunkhanna93** [spyder-ide/spyder#4266]
I am running python 3.5 on windows and had previously installed spyder through the anaconda package
I run this command "spyder --show-console" in the cmd and there is an error which pops up which says 

"Entry Point not Found
The procedure entry point mkl_lapack_cgesvd_sf could not be located in the dynamic link library 
C:\ProgramData\Anaconda3\Library\bin\mkl_intel_thread.dll.
"

Please help!

**Comment by ccordoba12** [comment]
Please uninstall Anaconda, reinstall it for your user only (instead of all users) and try again.

**Comment by ccordoba12** [comment]
Closing because of lack of response.

**Comment by rausm** [comment]
Have this problem also, and I don't conside "reinstall under user" a solution AT ALL.

1) Default system-wide install is something that should always be supported.
2) I always have a shitload of packages manually installed in my default env, and I don't wanna to _yet again_ go through the dance of "discover a missing/outdated package while net is not easily reachable".

What exactly was a "user install" supposed to fix, before I even consider it ?

**Comment by rausm** [comment]
Just for your info, the MKL contained in conda, and in the MKL package, contains this function. The problem is just that the .dlls bundled with Numpy don't contain them.

What sufficed was moving out the mkl_*.dll in numpy package dir somewhere else (or delete them / or change the suffix / whatever).

Works like a charm.

PS: Reinstalling under user, and installing the same numpy package would have led to the same problem. That's why I don't do bogus "try this" without an idea of what is should fix & how.

**Comment by ccordoba12** [comment]
> I always have a shitload of packages manually installed in my default env, and I don't wanna to yet again go through the dance of "discover a missing/outdated package while net is not easily reachable".

I think this is the problem here. You **must** use a different env to try packages not provided by Continuum, with the exception of pure Python packages.

> That's why I don't do bogus "try this" without an idea of what is should fix & how.

Very few people have reported this problem, so I'm almost sure it doesn't appear on clean installations. Besides, this is not a Spyder issue per se, it's a Numpy issue.
