### ISSUE TITLE
Spyder looks terrible on a very high resolution screen

### ISSUE THREAD

**Issue by wyntervivaldi** [spyder-ide/spyder#4316]
## Description of your problem
![image](https://cloud.githubusercontent.com/assets/26839804/24579792/7ac37cf8-172e-11e7-8643-f46af1dac2d5.png)
Display scaling is on, but my text on the tabs and the like are really tiny? I also cannot drop the reso as it causes issues on this laptop, my laptop is  new but is super buggy and I really don't have time to exchange it and what not.
**What steps will reproduce the problem?**

1. Leaving the com at original reso
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 2.7
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

I really don't know my way around spyder and I'm a student, so a super idiot proof guide would really help, thanks! I also don't know how to mess around with it much; nor can I ><

**Comment by ccordoba12** [comment]
I have no idea why that's happening, sorry. What's your screen resolution?

**Comment by juejung** [comment]
Same problem on a Dell XPS 13, high dpi laptop under Ubuntu 16.10 with high-dpi scaling on. Ubuntu Unity has a central scaling option for high dpi screens.
The button size in spyder is okay, editor and command window fonts are okay, but the fonts in the window frames and the menu entries are tiny - just like in the screenshot above.
I run Python 3.6.1 - Anaconda custom (64-bit) distribution with qt 5.6.2 and Spyder Version: 3.1.3

**Comment by ccordoba12** [comment]
@juejung, what if you run Spyder like this?

    QT_SCALE_FACTOR=1.5 spyder

You can adjust your scale factor according to Ubuntu settings (in this case it's 150%).

**Comment by ccordoba12** [comment]
If this works for you, we can add an entry in our Preferences so that people can adjust this factor by hand.

**Comment by ccordoba12** [comment]
Some references about this:

* https://wiki.archlinux.org/index.php/HiDPI#Qt_5
* https://blog.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6/

**Comment by juejung** [comment]
I get the following results:

Turn OFF high dpi scaling in spyder preferences menu (so UNtick the tickmark item) and start with
QT_SCALE_FACTOR=2.5 spyder
This is the best solution and solves my problems as it scales up everything nicely (buttons plus fonts)
![image](https://cloud.githubusercontent.com/assets/1740639/24705755/499a8dec-19db-11e7-8e7f-3857c88ef2a5.png)

Turn ON high dpi scaling in spyder preferences menu (so tick the tickmark item) and start with
QT_SCALE_FACTOR=2.5 spyder
This increases the size of the button bar only but doesn't scale the font in the menu or window borders
![image](https://cloud.githubusercontent.com/assets/1740639/24705799/76a7372c-19db-11e7-9147-8232b4eef5a3.png)

Turn OFF high dpi scaling in spyder preferences menu (so Untick the tickmark item) and start with
QT_SCALE_FACTOR=1 spyder
Now everything is tiny - spyder is not using any of the up-scaling from the Unity environment. This is the default setting if a new user starts Spyder for the first time with a hi dpi screen.
![image](https://cloud.githubusercontent.com/assets/1740639/24705853/a2c4946c-19db-11e7-9663-7ceb7d12e03a.png)

Turn ON high dpi scaling in spyder preferences menu (so tick the tickmark item) and start with
QT_SCALE_FACTOR=1 spyder
This increases the size of the button bar only (as before) but doesn't scale the font in the menu or window borders
![image](https://cloud.githubusercontent.com/assets/1740639/24705905/c63e8b82-19db-11e7-974f-eac929cb5fc7.png)

So I think if you add QT_SCALE_FACTOR=2.5 to the preference menu users could scale everything according to what they need. The current hidpi adjustment only scales the buttons, and is therefore less helpful in my case.

**Comment by goanpeca** [comment]
@juejung this information is very useful!, thanks a lot :-),

@ccordoba12 this would be a new option that would require restarting spyder, right?

**Comment by ccordoba12** [comment]
Yes, this needs a new option, and we also need to allow setting the resolution for multiple screens, i.e. not only a single number but multiple ones separated by `;` (this is described in the Qt5 blog post I mentioned above).

So my idea is to create a new section in `Preferences > General > Appearance` like this

```
           Fonts
....

           Screen resolution

( ) Autoscale resolution for High DPI screens
( ) Define a custom scale factor [______]

           Interface
....
```

`Autoscale ...` and `Define ...` must be radio buttons so that users can select or the other but not both at the same time.

Then we can define the corresponding environment variable in `spyder/app/start.py`.

*Note*: We need to add to the `Define ...` option some help to tell users how to set it for multiple screens.

**Comment by goanpeca** [comment]
Ok, I will take this one :-)

**Comment by ccordoba12** [comment]
Great!

**Comment by groundhogxc** [comment]
One more remark on this: Two more things which I found which are affected (in addition to the panel move/close buttons, see screenshots):

- the font of the Help tab which somehow seems to be separate from the other fonts. It is also much too small in my system

- the inline plot output in the IPython console is also rendered too small. In addition, if you set the QT scale factor (which simply scales the matplotlib output), then this problem is not really adequately solved: The system should render the plot bitmap with twice the pixel size instead of rendering the same bitmap and scaling the pixels.

See screenshots for example (from the console window you can see what the correct size would be):

![screenshot_qtfactor1](https://cloud.githubusercontent.com/assets/8235582/24791732/96fc20e0-1b7b-11e7-9a20-e4ddd5a577f4.png)
![screenshot_qtfactor2](https://cloud.githubusercontent.com/assets/8235582/24791737/9f79b50c-1b7b-11e7-8bd3-554fc8700bca.png)

**Comment by groundhogxc** [comment]
...and one more comment:

In Windows, strangely enough, the Help Window font seems to be OK, whereas all the other behaviour seems identical to Linux.  (the same buttons are too small)

Possibly the "Spyder" Icon in the top left corner Window button is also too small, but maybe that is by design. It is much smaller than the Linux one though.

**Comment by Elliptica1** [comment]
@juejung How do you set the QT_SCALE_FACTOR like you did? When I try to run the same command as you, it says that QT_SCALE_FACTOR is not an internal or external command. I figure I need to add it to my computer's environment variables somehow, but I'm not sure where to point it?

**Comment by ccordoba12** [comment]
@rlaverde, please work on this one. My proposed solution is here

https://github.com/spyder-ide/spyder/issues/4316#issuecomment-291879519

and you solve have to take into account

https://github.com/spyder-ide/spyder/issues/4316#issuecomment-292474386

For the help plugin.

**Comment by juejung** [comment]
@Elliptica1 I simply ran it from command line:
QT_SCALE_FACTOR=2.5 spyder
This then starts spyder with the high dpi scaling.

**Comment by Elliptica1** [comment]
@juejung But what is your QT path in environmental variables? When I run the same code, I get `'QT_SCALE_FACTOR' is not recognized as an internal or external command,`
I know that means it's not part of my path, but I'm not sure where QT is stored, I can't seem to find it. I have Anaconda and Spyder both working, but that command does not.

**Comment by juejung** [comment]
@Elliptica1 I don't recall having to set anything. On my system QT is already in the path. Maybe try something like this? 
https://askubuntu.com/questions/435564/qt5-installation-and-path-configuration

**Comment by bclinthall** [comment]
I'm running spyder 3.1.4 on Ubuntu 17.04, ThinkPad P50s, 2880 x 1620 resolution.  The suggestion from @ccordoba12  to run python using `QT_SCALE_FACTOR=<preferred_scale_factor> spyder` works great for me.  I get the same results as @juejung.  Thanks for posting this stuff.  

@groundhogxc, you can rescale the help menu text in spyder 3.1.4 settings.  *Tools > Preferences > General > Rich Text Font*
Here's an image that shows the setting and the help panel with the Rich Text Font set really high:
![helpscaling](https://cloud.githubusercontent.com/assets/25251768/26154704/8b4433d2-3ade-11e7-82b3-858e554fa720.png)

**Comment by rlaverde** [comment]
Thanks @bclinthall your comment gave me a clue of where to trace the error 😄

**Comment by ccordoba12** [comment]
We just added a new option to set a custom scale factor to our `3.x` and `master` branches. Those of you who have this problem, please test it and let us know if it solves it.

**Comment by juejung** [comment]
Hi Guys,
I'm running on XPS 13 high DPI, Ubuntu 17.10, Anaconda custom (64-bit) distribution with Python 3.6.2 64bits, Qt 5.6.2, PyQt5 5.6  and Spyder Version: 3.2

Thanks for adding the: Set a custom high DPI scaling - option to Spyder 3.2

There are now 3 options available in the settings menu:
[1] Normal
[2] Enable auto high scaling
[3] Set custom high DPI scaling

alternatively we can run it from command line using:
[4] QT_SCALE_FACTOR=2.5 spyder



Running Spyder with [1] Normal, I get this:
![image](https://user-images.githubusercontent.com/1740639/28717316-43b33d46-736f-11e7-8a8c-1ee1ca959e31.png)
Everything is very small.

Running Spyder with [2] Enable auto high scaling, I get this:
![image](https://user-images.githubusercontent.com/1740639/28717413-ab81b042-736f-11e7-8e7c-9383b63ce24e.png)
Everything is still small except for the toolbar which is now scaled up.

Running Spyder with [3] Set custom high DPI scaling set to 2.5 I get this
![image](https://user-images.githubusercontent.com/1740639/28717452-dd8b76e0-736f-11e7-9d26-ed51c10c5d6a.png)
Still everything is small, except for the toolbar - this is puzzling since I expected that everything would be scaled.

Running Spyder from command line with: QT_SCALE_FACTOR=2.5 spyder
I get this:
![image](https://user-images.githubusercontent.com/1740639/28717542-3db91d9c-7370-11e7-852a-1a9088738608.png)

Perfect outcome, everything is scaled up. I assumed that option [3] would produce this, but on my system it does not?

**Comment by rlaverde** [comment]
That is a bug, setting a custom high DPI scaling to 2.5 in the configurations, and running Spyder from command line with: QT_SCALE_FACTOR=2.5 should have the same effect.

@ccordoba12 I guess we need to add the environment setting, event before the qtpy imports 😕 what do you think?

**Comment by ccordoba12** [comment]
I don't think so, we're already setting the env var before qtpy is imported.

Instead, it seems QT_SCALE_FACTOR and QT_SCREEN_SCALE_FACTORS (which is 
the one we're using) give different effects. Please open a new issue 
about this for 3.2.1, so we don't forget to address it.

**Comment by rlaverde** [comment]
@juejung Could you test if the fix proposed in #4846 works for you?

**Comment by juejung** [comment]
@rlaverde Yes, it works. Thank you.

**Comment by rlaverde** [comment]
@juejung Thank you for testing it 😄

**Comment by simonsayshi** [comment]
@juejung hi, I'm new to spyder and I met the  same issue. where am I supposed to add this command? type it in cmd ? 
Ill be appreciated if you can give me full description how to do it :)

**Comment by juejung** [comment]
@simonsayshi This has been fixed in the newest version of Spyder. I would just upate with: conda update spyder

**Comment by simonsayshi** [comment]
@juejung sorry....where should I type this command? run it in cmd?

**Comment by simonsayshi** [comment]
oh I see, I typed it in the terminal but it showed 

CondaIOError: Missing write permissions in: C:\ProgramData\Anaconda3
#
# You don't appear to have the necessary permissions to update packages
# into the install area 'C:\ProgramData\Anaconda3'.
# However you can clone this environment into your home directory and
# then make changes to it.
# This may be done using the command:
#
# $ conda create -n my_root --clone="C:\ProgramData\Anaconda3"



how do I deal with it?

**Comment by hsauro** [comment]
The new options in 3.2.3 for dealing with high res displays don't work for me. I had to reduce the resolution of my laptop to get the my plots look bigger (I can't resize the plots at this point in time). I'm running on Windows 10. I went to the link that is indicated on the preferences page, but its seems to be more for developers than users. Are there simple instructions to work with high res screens that say a casual user which doesn't know about command lines or jargon can follow?

**Comment by ccordoba12** [comment]
The resolution of plots is handled in the IPython console options. 
Please take a look at them.

**Comment by hsauro** [comment]
I saw those and tried changing the width and height but it didn't make any difference. Perhaps they only apply to non-inline plots?

**Comment by ccordoba12** [comment]
You have to change the resolution, but please open a new issue about it. 
I think there's an option to set HiDPI for inline plots.

**Comment by hsauro** [comment]
I set resolution to 300dpi (and to 48dpi) and increased width and height but no change. I also switched between normal, auto and set custom high DPI in the General->Appearance tab and no difference. If there is nothing else to try I'll open an issue.

**Comment by ccordoba12** [comment]
Yep, there's nothing else to try. Please open the issue.

**Comment by hsauro** [comment]
One other thing, at high resolution I tend to increase the font size but this makes the code completion window in the editor not wide enough to fit the options (see attached image). From the IPython console the code completion window is wide enough. I didn't see an option to widen the completion window or drag it wider with the mouse. 

![codecompletion](https://user-images.githubusercontent.com/1054990/34747947-35ce0596-f54f-11e7-9ea2-a639d9a830ee.png)

**Comment by ccordoba12** [comment]
There's no option to increase that size. Please open a different issue 
for that.

**Comment by hsauro** [comment]
With reference to the small matplotlib image on high res screens, in the process of creating a small example to include with the issue, it turns out it was the application I was using that must have the problem because a small example such as 

   import pylab
   pylab.plot ([1,2,3,4],[6,7,4,5])

does change the size of the inline plot to changing the width and height under IPython preferences. The only thing I found is that you must restart spyder to have the settings apply.  I will report this to the application developers of the tool I was using.   This does not appear to be a problem with spyder.

**Comment by ccordoba12** [comment]
Oh, that's a Spyder problem. We should inform users when a change in an 
option in the IPython console requires a restart, not of Spyder but of 
the console kernel.

**Comment by hsauro** [comment]
You're right a kernel restart is sufficient for the setting to be recognized.

**Comment by Khalilsqu** [comment]
my new xps 9570 4k was delivered today. `enable auto high DPI scaling` was the solution

**Comment by Elliptica1** [comment]
I used to use this thread to make Spyder look bigger/readable (right now it's minuscule) on a high resolution screen. I would do

set QT_SCALE_FACTOR=2.5
spyder

It used to work fine. Now, however, it does nothing. I've tried putting it on one line, but if I do that, nothing happens. How can I increase the scale factor now? I'm using Spyder 3.3.1

**Comment by RViking** [comment]
I'm having the same issue with the newest version of Spyder. Adjusting the QT_SCALE_FACTOR does nothing. The text is grotesquely large. Any help? I'm running this on Windows 10.

![SpyderTexttooLarge](https://user-images.githubusercontent.com/35347325/68214554-aa1c9080-ffab-11e9-91bc-ecae2bbf2d49.PNG)

**Comment by csbrace** [comment]
I also ran into this issue, but was able to fix it by following the advice of this person on Stack Overflow: https://stackoverflow.com/a/48141311/11627783
Would love it if this could be somehow integrated into Spyder! Very annoying.

**Comment by christian-ruf** [comment]
I am using Spyder 4.1.5. and have the same issue. Everything is terribly small. If there is a global scaling setting, I do not find it.

**Comment by apachaves** [comment]
Thank you for the rescaling option. I had the same problem in my high resolution display and thanks to the option to auto scale HDPi I can now use Spyder well. 👍🏻
