### ISSUE TITLE
Define a road-map to drop python2 support

### ISSUE THREAD

**Issue by rlaverde** [spyder-ide/spyder#4391]
I'm not saying that python2 support should be dropped soon, but I think that we should define a road-map, and make an official announcement  to aware spyder users of when and how python2 support will be end.

Reasons:
- python2.7 support will end in 2020 https://pythonclock.org/
- Some libraries are dropping python2 support ([ipython](https://blog.jupyter.org/2017/04/19/release-of-ipython-6-0/))  http://www.python3statement.org/
- the majority of libraries already support python3 http://py3readiness.org/
- there is a big technical debt in spyder related of python2 support (the utility py3compat is used in +50 files)
- the CI time will drop to ~almost~ the half

I think we could follow what ipython did:

- Drop python2 support in a major release (5.0)
- Continue buxfixes in 4.0 with python2 support until 2020 (EOL of python2.7)
- Maybe we could join http://www.python3statement.org/

---------

Also I think that dropping python2 support shouldn't be too much harm to the end user, although they won't be able to install spyder in a 2.7 environment, they could change the python executable in the preferences and continue running 2.7 code.

**Comment by ccordoba12** [comment]
Let's see how things evolve after IPython 6 (which is Python 3 only). I think we can revisit this at the end of the year.

**Comment by bcolsen** [comment]
@ccordoba12 This is just my opinion. I have no idea if this makes things more difficult or easier for you, but....

I think dropping python 2 in Spyder 4 would be great for development and users wouldn't be confused with dropping support because it's a major version.  I not suggesting that we change a bunch of code to make python 2 not work in Python 4, but just not support it.

I got bit by py2 here:
https://github.com/spyder-ide/spyder-kernels/issues/14

If Spyder 4 is not going to be released until 2019, python 2 will have less then a year of support anyway. 

Supporting Spyder 3 with security for less than a year after Spyder 4 is out might be less work then supporting unsupported python 2 in Spyder 4 after Jan 2020 or needing to release a quick Spyder 5 with dropping python 2 as it's major feature.

**Comment by ccordoba12** [comment]
> I think dropping python 2 in Spyder 4 would be great

The problem is the big refactoring we're planning for Spyder 4 (and that now lives in the split-plugins branch) will make really, really hard to keep maintaining our 3 series with bugfixes until 2020.

So we decided to leave Python 2 support in Spyder 4 and to release Spyder 5 at the end of 2019 with the single change of being Python 3 only.

**Comment by ccordoba12** [comment]
Yeah, that's our main reason right, that Spyder 4 is working just fine in Python 2.
