### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by ypokkinen** [spyder-ide/spyder#4620]
## Description of your problem

**What steps will reproduce the problem?**

1. When trying to start Spyder from Anaconda Navigator, nothing happenns.
2. opened cmd.exe. Did pip install --upgrade spyder
3. Opened red error: 'utf-8' can't decode byte 0xf6 in position 12: invalid start byte.

**What is the expected output? What do you see instead?**
I expected installation success. 

**Please provide any additional information below**
 My name is by the way Yrjö.

## Versions and main components

* Spyder Version:3.1.4
* Python Version:3.6.1
* Qt Version:5.8.0
* PyQt Version:5.8.2
* Operating system: Windows 7 professional 64-bit.

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
You mixed pip and conda packages, and that most probably broke your Anaconda installation. They can't be mixed because they have different build specs.

So I'm afraid you'll have to uninstall and reinstall Anaconda, and don't forget to remove your Anaconda installation directory before reinstalling.

Then please start Spyder again (without using pyqt pip packages) and let us know if it works for you or not.

**Comment by ccordoba12** [comment]
Closing because this is not really a Spyder problem, just an incorrect installation issue.
