### ISSUE TITLE
Can't launch Spyder IDE

### ISSUE THREAD

**Issue by allg18** [spyder-ide/spyder#4659]
I can't find any way to launch the Spyder IDE, when installed via pip...

So I ran CMD as Admin, and then:
`pip install spyder`

Whoever I can find anything related on the start menu.
Also went to the Python installation folder, Scripts folder, and there is only a spyder3.py file, which I tried to run, but then again nothing happened. I also saw on the internet that I should look for a spyder .bat file, but there isn't one.

Also, when I run the spyder3.py file from the terminal using python nothing happens...

This is the 2nd time I try to use Spyder, but with no success.

(Python version: 3.6 64bit;
Operating system: Windows 10)

**Comment by ccordoba12** [comment]
> Whoever I can find anything related on the start menu.

We don't install menu entries with our pip packages.

> but then again nothing happened.

I think you still need to run

    pip install pyqt5

> This is the 2nd time I try to use Spyder, but with no success.

Pip installations are for experts only. If you don't know the Python scientific system ecosystem very well, please download and install Anaconda. It's much easier to use than plain Python.

I'm closing this one because we can't give you more support for pip. It's really up to you (if you want to keep using it) to figure out for yourself how to make Spyder work with it.

**Comment by allg18** [comment]
Thanks, pip installing pyqt5 worked.
I will just leave the suggestion to add this step to the README.md, this may save the trouble to other people who don't want to install python bundles.

**Comment by ccordoba12** [comment]
You're probably right, but again, that's why pip installations are for 
experts.
