### ISSUE TITLE
No spyder on Conda distribution

### ISSUE THREAD

**Issue by MrWanter** [spyder-ide/spyder#4757]
A simple but strange problem, I installed Conda, but there is no spyder in it, what's the problem?

**Comment by MrWanter** [comment]
now I'm using `conda install spyder`, but it's very much slow, only around 20 kB/s, and seems there is a lot of dependencies to be installed, is there other more efficient way to install spyder on my conda distribution?

**Comment by MrWanter** [comment]
the `conda install spyder` just got stucked,  then I use `pip install spyder`, after installation, how can I run it? I typed `spyder `on the anaconda prompt, the system cannot recognize it, but with `pip list`, there is a `spyder 3.1.4` in the list, so how can I fix the problem and got spyder working? thanks in advance!

**Comment by ccordoba12** [comment]
I you install Anaconda, then you will get Spyder with it. Miniconda (which I presumed you installed) comes only with conda but not Spyder. You have to be patient and wait until Spyder is installed in this case.

Besides, if you use Anaconda or Miniconda, please don't use pip because mixing the two systems will break your installation.
