### ISSUE TITLE
Cannot install Spyder 3 on Ubuntu

### ISSUE THREAD

**Issue by Mathemilda** [spyder-ide/spyder#4967]
## Description of your problem

**What steps will reproduce the problem?**

1. I've tried to install spyder and got spyder 2 with python 3
2. I wanted spyder 3 and tried to update it using pip. At some point I would get Spyder 3 with Python 2.7 and need Python 3.5 to work on my course with my students. They use Spyder as well, and it is Spyder 3.2.0. I should use the same to be able to advice them. 
3. As result I cannot use spyder at all. I got a message:
`Segmentation fault (core dumped)`

**What is the expected output? What do you see instead?**
I wanted Spyder 3 with Python 3.5, installed on my system.

**Please provide any additional information below**
I had  Anaconda installed before, but it could not get with Python library's updates I needed on time. So I removed Anaconda and tried to install it with out it, and did not get what I wanted.

## Versions and main components

* Spyder Version: right now none
* Python Version: 3.5 
* Qt Version: 
* PyQt Version: 5
* Operating system: Ubuntu 16.04

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

Sorry, cannot open spyder.

**Comment by ccordoba12** [comment]
> I've tried to install spyder and got spyder 2 with python 3

I guess you used `apt-get` to do this. That's the problem with Ubuntu, its packages are (almost always) outdated.

> I wanted spyder 3 and tried to update it using pip

Pip installations are for experts, really. Pip seems as easy as conda, but unless you have a good knowledge of the scientific Python ecosystem, you can easily end up in a broken state (like in you case).

> I had Anaconda installed before, but it could not get with Python library's updates I needed on time

Could you explain this? I don't understand exactly what you mean.

----

Anaconda is our number one recommendation because it's a well curated and mostly stable set of packages, which is independent of your system Python.

So my advice is for you to reinstall Anaconda.

**Comment by Mathemilda** [comment]
Thanks for your reply,
I appreciate your attempt to help. Hower, I not only work with a Spyder myself but help students to do this as well, and they work with Anaconda. So I daily comfort them because Anaconda is not a good choice for working with Spyder. They suffer through version conflicts, and one of the reason is that Anaconda forces them to use particular versions, and tuning with it to something which works is a real pain. 
Thanks anyway.

**Comment by goanpeca** [comment]
>So I daily comfort them because Anaconda is not a good choice for working with Spyder

??

Anaconda IS the best choice for working with spyder

**Comment by Mathemilda** [comment]
Do you daily work with students who are to use Python with Spyder?

**Comment by goanpeca** [comment]
Daily? nope. But I have given many week long courses, lectures, workshops (for years now) and I have always used Anaconda reliably.

**Comment by ccordoba12** [comment]
> They suffer through version conflicts

Unfortunately, that happens also with pip.

> and one of the reason is that Anaconda forces them to use particular versions, and tuning with it to something which works is a real pain

The same will happen with pip.

> It would be so much easier to download a preferable version and to install it.

It seems your students are constantly updating Anaconda, and that's where the pain comes from. You should instruct them to not do that, and instead simply run

    conda update anaconda

when a new version of Anaconda comes up.

> Do you daily work with students who are to use Python with Spyder?

I also have given Python courses before, and I've found Anaconda is the best and simplest way to install Spyder, all its dependencies and the scientific libraries needed to give a course (Numpy, Pandas, Matplotlib, Scikit-learn, etc).

----

I still don't understand what's the exact problem you have with Anaconda, sorry.

**Comment by Mathemilda** [comment]
I see. So nobody is responsible. 
Anaconda takes place and computer resourses. Why should I put on my computer more than I need?
There are some packages versions which I and my student use and which work for Python 3.5. In the same time we use other packages as well. Anaconda updates stuff as it wishes, creating version conflicts. 
So, no knowledgable people here who know something beside Anaconda?

**Comment by jitseniesen** [comment]
I use Debian which is quite similar to Ubuntu. In my experience, the Debian packages are working quite well recently, though they usually lag a bit behind. However, mixing Debian packages with pip packages caused a lot of problems for me, and that is why I switched to Anaconda.

**Comment by goanpeca** [comment]
@Mathemilda 

>I see. So nobody is responsible.

All the people in this thread are Spyder core developers and users for a long time, and we have used Spyder on several operating systems and on different educational settings. We are trying to do our best to help.

>Anaconda takes place and computer resourses. Why should I put on my computer more than I need?

You don't, Anaconda is convenient, but if HD space is a scarce resource you can install miniconda which is a minimal version of anaconda with just python conda and its dependencies. From there you can choose to install whatever package you need. See [Miniconda](https://conda.io/miniconda.html).

>There are some packages versions which I and my student use and which work for Python 3.5. In the same time we use other packages as well.

You can create a py35 environment and install anything you need there. Or change the root python version to python=3.5

>Anaconda updates stuff as it wishes, creating version conflicts.

This is inaccurate, anaconda won't change anything until you ask conda to install, update or remove something. Conda has an efficient and battle tested solver, so if it tries to change (upgrade/downgrade) packages it is because the dependencies of one or more of the requested packages required so.

**Comment by ccordoba12** [comment]
> Why should I put on my computer more than I need?

Because it's easier to install and maintain. If you use `pip`, that will the same extra resources with the disadvantage that it's very hard to debug.

> There are some packages versions which I and my student use and which work for Python 3.5

Which packages? Please be clear, so we can help you better.

> Anaconda updates stuff as it wishes, creating version conflicts.

Anaconda doesn't update anything by itself, unless you run `conda update foo`.

Also, please be clear and tell us what these version conflicts are.

> So, no knowledgable people here who know something beside Anaconda?

Your reported error message

     As result I cannot use spyder at all. I got a message:
     Segmentation fault (core dumped)

is totally unhelpful. If you installed Spyder with `sudo pip install spyder`, you're probably getting conflicts with your Ubuntu system packages. So please uninstall it and all other packages you installed in `/usr/local/lib/python3.5/` (you can safely remove that directory, if you prefer).

Then create a clean virtualenv in your home directory (using `mkvirtualenv` or `pyvenv`) and install Spyder there with

    pip install spyder
    pip install pyqt5

Even after that Spyder could crash because of OpenGL problems (if you use an Nvidia card as your default graphical card). This is a bug in Ubuntu and (currently) there's no solution to that.

If everything went well, you can install the rest of the packages you said you need in your virtualenv too.

**Comment by ccordoba12** [comment]
@Mathemilda, did my last instructions work for you?

**Comment by ccordoba12** [comment]
Closing because of lack of response. Hopefully, things are well for you now.

**Comment by hmaarrfk** [comment]
Hey, just chiming in. Thanks for being patient with @Mathemilda. This thread solved my problem.

Need to both install 
```sh
pip install spyder
pip install pyqt5
```

**Comment by Mathemilda** [comment]
Hello Carlos,
no, i used something else, found a solution on Internet. I felt at the
point that it is too much fuss to work with environments, and why should I
do it if I can avoid it? An additional problem here is that some packages
do not work with Python 3.6 yet, like nltk for Natural Language Processing,
and keras developers for Deep Learning only recently claimed that their
library now cooperates with Python 3.6, although in practice is it not a
smooth ride. I have students who are learning and the environments for them
is additional burden. I wish you would have a choice for people what
Anaconda version to load with what Python. By the way people with Windows
10 complain that 5th Anaconda crushes. I directed them to your site but do
not know if they made it or switched to earlier version.
Best,
Mya
