### ISSUE TITLE
Error when startup spyder

### ISSUE THREAD

**Issue by dickhfchan** [spyder-ide/spyder#5072]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/Users/dickhfchan/anaconda/lib/python2.7/site-packages/spyder/otherplugins.py", line 79, in _import_plugin
    module = _import_module_from_path(module_name, plugin_path)
  File "/Users/dickhfchan/anaconda/lib/python2.7/site-packages/spyder/otherplugins.py", line 103, in _import_module_from_path
    module = imp.load_module(module_name, *info)
  File "/Users/dickhfchan/anaconda/lib/python2.7/site-packages/spyder_pylint/__init__.py", line 6, in <module>
    from .pylint import Pylint as PLUGIN_CLASS
  File "/Users/dickhfchan/anaconda/lib/python2.7/site-packages/spyder_pylint/pylint.py", line 28, in <module>
    from .widgets.pylintgui import PylintWidget
  File "/Users/dickhfchan/anaconda/lib/python2.7/site-packages/spyder_pylint/widgets/pylintgui.py", line 22, in <module>
    import pylint
  File "/Users/dickhfchan/anaconda/lib/python2.7/site-packages/pylint/__init__.py", line 8, in <module>
    from .__pkginfo__ import version as __version__
  File "/Users/dickhfchan/anaconda/lib/python2.7/site-packages/pylint/__pkginfo__.py", line 16, in <module>
    from pkg_resources import parse_version
ImportError: No module named pkg_resources

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 2.7.12
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.5.0  :  1.3.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.19.2 (OK)
numpy >=1.7       :  1.11.1 (OK)
sphinx >=0.6.6    :  1.4.6 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.9.0 (OK)
psutil >=0.3      :  5.2.2 (OK)
nbconvert >=4.0   :  4.2.0 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.24.1 (OK)
qtconsole >=4.2.0 :  4.2.1 (OK)
IPython >=4.0;<6.0:  5.1.0 (OK)

```

**Comment by ccordoba12** [comment]
Please post the output of

    conda list

**Comment by yehoshuadimarsky** [comment]
Not sure if I'm supposed to open a new issue for this, but I'm also having the same problem. When I start it, it shows this:

![image](https://user-images.githubusercontent.com/24758845/29796776-101b7e88-8c21-11e7-8a31-f34c0ac5b71f.png)

I  think this might be because I messed up some packages by using both pip and conda, but not sure.

Specs:
Windows 10
Python 3.6.1

I ran `conda list --export > conda-packages.txt` and attached the file here:

[conda-packages.txt](https://github.com/spyder-ide/spyder/files/1258608/conda-packages.txt)

Also tried removing and reinstalling spyder using conda, no dice.
Thanks.

**Comment by ccordoba12** [comment]
According to this StackOverflow post

https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources

this is a problem with `setuptools`, though your `conda list` shows no problem.

Since I really don't know what's happening in your case, my only advice is for you to uninstall and reinstall Anaconda all over again, sorry.

I guess at some point you installed a package with `pip` and that messed up your installation.
