### ISSUE TITLE
There are two scroll bars in the Editor

### ISSUE THREAD

**Issue by ma-sadeghi** [spyder-ide/spyder#5085]
## Description of your problem
There are two scroll bars instead of one in the text editor. Here's how my text editor looks like:
![image](https://user-images.githubusercontent.com/14086031/29847266-bd031684-8ce8-11e7-851d-3d23dbba8973.png)

**What is the expected output? What do you see instead?**
I expect to only see one scroll bar!

## Versions and main components

* Spyder Version: 3.2.1
* Python Version: 3.6
* Qt Version: 5.9.1
* PyQt Version: 5.9
* Operating system: Windows

## Dependencies
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by jnsebgosselin** [comment]
The "scrollbar" on the left is not actually a scrollbar. This is an indicator that shows the portion of the file that is visible in the Editor, with the actual position of code errors (red lines), code analysis (yellow lines), positions of break points (red lines), etc... This is quite handy to navigate quickly to a given flag in a file.

**Comment by ma-sadeghi** [comment]
@jnsebgosselin Maybe, but it's annoying to me. I'd like the editor to be minimal like in Sublime or Atom. Right now Spyder GUI is cluttered IMO. Is there any way to get rid of this so-called "scroll bar". Thanks for your quick reply btw 👍

**Comment by ma-sadeghi** [comment]
@jnsebgosselin Also, I understand that the errors/warnings show up in this area, but I'm talking about the grayish box that looks like a scroll bar, not the whole area itself.

**Comment by jnsebgosselin** [comment]
Unless I'm mistaken, I do not think there is such an option to do that in the options. @ccordoba12 what do you think?

If you really really want to get rid of the grayish box and quick, you can patch your local copy of Spyder by commenting lines [1487 ](https://github.com/spyder-ide/spyder/blob/3.x/spyder/widgets/sourcecode/codeeditor.py#L1487) to [1493 ](https://github.com/spyder-ide/spyder/blob/3.x/spyder/widgets/sourcecode/codeeditor.py#L1493) in the [code editor](https://github.com/spyder-ide/spyder/blob/3.x/spyder/widgets/sourcecode/codeeditor.py) and it should be gone once you restart Spyder.

![image](https://user-images.githubusercontent.com/10170372/29852711-918d741a-8d09-11e7-8892-35eee29b95fb.png)

**Comment by ccordoba12** [comment]
> @ccordoba12 what do you think?

i think we should remove that spurious scrollbar for Spyder 4. @goanpeca?

**Comment by Prikers** [comment]
An idea could be to hide the actual scrollar (set its width to 0) and make it possible to use the scrollflag to actually scroll (by grabbing it). It would save some space as it would combine the (very usefull) flag area with the grabbable item.

**Comment by jnsebgosselin** [comment]
I personally got used to love this slider range indicator, so :-1: to completely remove it. I'll go for an option instead.

Pikers idea is interesting, though this may cause problem for very long files for which the slider range indicator becomes very small.

**Comment by jnsebgosselin** [comment]
I'll go with something like this in the Editor preferences, with two checkboxes:

`[x] Show scroll flag area    [ ] Show slider range indicator`

The "show slider range indicator" would be active only when "show scroll flag area" is checked.

**Comment by Prikers** [comment]
@jnsebgosselin you're idea seems to be the most reasonable! :+1: 
My initial idea was to combine these two "scrollbars" into one. So either:

- Hidding the standard scrollbar (without messing it further than just hidding) and making the scroll flag area act as a scrollbar (draggable and also clickable for long files)
- Or painting all the flags on the standard scrollbar (not sure that's even possible)

I will give it a try to test the first bullet and see what's possible and how it feels.

**Comment by jnsebgosselin** [comment]
@Prikers What I meant is, from a user perspective, I'm not sure it is a good idea to change the behaviour of the scrollbar. I know it is not exactly the same issue, but I remember when they changed the scrollbars in Unity for Ubuntu, there was a lot of rage. They finally added an option to revert back to the standard scrollbar. I think we would have to to the same also if we go this route. Just my two cents :)

That being said, I think it may be a good idea to make the slider range indicator draggable. though, I still see the problem with long files. Since we compared Spyder to it, here is how a similar feature is working in Sublime. As we can see, they kept the standard scrollbar along with their "file preview scrollbar".

![sublime](https://user-images.githubusercontent.com/10170372/29874732-ad0befe4-8d65-11e7-9d05-9d0011c10d0a.gif)

**Comment by goanpeca** [comment]
We should probably just show the grayish area on hover and not all the time?

**Comment by ccordoba12** [comment]
> We should probably just show the grayish area on hover and not all the time?

I agree with @goanpeca on this one. I wouldn't like to add yet another option to our (already overcrowded) Preferences.

**Comment by rlaverde** [comment]
> i think we should remove that spurious scrollbar for Spyder 4

Deactivating/activating it in master is kind of easy, because It's a panel, Maybe we could  add an option for deactivating

I find this scrollbar a little annoying, but at the same time It's kind of useful, maybe we could improve it to be a mini-map (like the one in sublime), that will also show the errors/warnings.

> We should probably just show the grayish area on hover and not all the time?

I also agree with this, removing the grayish area It'll not look as an scrollbar, but the current part of the file should be in the center as sublime does.

**Comment by jnsebgosselin** [comment]
> We should probably just show the grayish area on hover and not all the time?
I agree with @goanpeca, but I would like to see this visible also when scrolling (with a timer maybe before hiding it). Really, this area is very useful to me, I can't be the only one lol? Moreover, it is going to be even more useful once I add the bookmarks feature.

> I also agree with this, It'll not look as an scrollbar if we remove the grayish area , but the current part of the file should be in the center as sublime does.

As for making it like in Sublime, I'm not sure. Presently, the scroll flag area can show with a glance all the flags there is in the entire file. If we make it like Sublime, it is going to be a lot less useful since only a part of the file is going to get covered at the time

> I wouldn't like to add yet another option to our (already overcrowded) Preferences.

I still believe this would be a good idea to add an option in the editor preferences to hide the scroll flag area :) (not the slider range indicator now with @goanpeca solution). @ccordoba12  It is not that overcrowded, it is almost half empty :) It goes well with other options like "Show line numbers" and "Show Class/Function dropdown".

![image](https://user-images.githubusercontent.com/10170372/29877627-24e5d1ee-8d6e-11e7-9d3d-3500c1edb1f4.png)

**Comment by rlaverde** [comment]
Another option is as KWrite does, show all the file and always show the selected area: (It still looks good with a file with + 3000 lines), although kwrite replace the normal scrollbar with the minimap-scrollbar

![spectacle hz8669](https://user-images.githubusercontent.com/2024217/29878003-ee598ec4-8d66-11e7-9fbe-8444863cdfad.png)

**Comment by ccordoba12** [comment]
@rlaverde, I'm a big fan of Kwrite/Kate but I really prefer Spyder's simplicity. I'm not opposed to add a minimap to Spyder, but as a third-party plugin, not by default.

**Comment by ccordoba12** [comment]
> I still believe this would be a good idea to add an option in the editor preferences to hide the scroll flag area :)

@goanpeca, @rlaverde, what do you say?

**Comment by goanpeca** [comment]
@rlaverde I think eventually every panel should have an option for enabling disabling, so the question is, this should be probably an option on the panel? so that the config is automatically generated instead of manually adding theses options per panel?

**Comment by jnsebgosselin** [comment]
Also, maybe toning down a little the _slider range indicator_ would help a long way to make it less annoying?

 In the screenshot below, I changed the color from `white` to `grey`, toned down the alpha from 50% to 35% and removed the edge.

![image](https://user-images.githubusercontent.com/10170372/29882633-a03ea4c6-8d7b-11e7-9dda-268622077aef.png)

**Comment by goanpeca** [comment]
Well @ccordoba12, @rlaverde @jnsebgosselin , if we did not have the normal OS scrollbar, we could simply use the flag area? What we can then enable or disable, is if warning are shown or not.

**Comment by jnsebgosselin** [comment]
@goanpeca hehe this is what @Prikers suggested in the first place. It won't work for large files, because the slider height will be too small. but we can simply fix a minimum height for this scenario. I'm still not sure I like this approach though...  I've never been a big fan of software with custom scrollbar. I will continue to think about it though.

Personally, I would prefer the option to keep the layout as it is, but tone down the slider range indicator and make it visible only when hovering and scrolling.

**Comment by rlaverde** [comment]
> so the question is, this should be probably an option on the panel? so that the config is automatically generated instead of manually adding theses options per panel?

Yes, It also could be added to editor extensions, although that could be generated based in the name of the panel, or maybe add an attribute with a custom text to be displayed.

**Comment by goanpeca** [comment]
@rlaverde plus some option to add it or not to the panel

**Comment by jnsebgosselin** [comment]
@goanpeca and @prikers here is how your idea could look like. I'll work for a while like that and I will comment back later. I must admit I kind of like that after all. The implementation is a little bit hacky, it was only to test how it felt user-wise. You can test it here: https://github.com/jnsebgosselin/spyder/tree/flagarea_as_scrollbar

Some downsides are that we kind of have to lose the up/down arrows, we also have to fix a minimum height for the handler or it becomes too small for long files, and it kind of break the uniformity with the rest of the Spyder UI.

![scrollbar](https://user-images.githubusercontent.com/10170372/29925980-07b25e9a-8e30-11e7-881c-5e084905b094.gif)

**Comment by ccordoba12** [comment]
@jnsebgosselin, although these experiments are interesting, I don't think we should remove the OS scrollbar in the Editor.

**Comment by goanpeca** [comment]
@ccordoba12 there is duplication and I do feel the concern of the user. Avoiding duplication has 2 roads.
- We implement a custom scroll bar (QScrollBar widget) and add warnings on top of it
- We use the custom widget for the scroll flag area

**Comment by jnsebgosselin** [comment]
> @ccordoba12 there is duplication and I do feel the concern of the user. Avoiding duplication has 2 roads.
> - We implement a custom scroll bar (QScrollBar widget) and add warnings on top of it
> - We use the custom widget for the scroll flag area

@goanpeca In the proof-of-concept I made above, I did the former, i.e. I implemented a custom QScollBar and added warnings on top of it.

**Comment by ccordoba12** [comment]
Yeah, but Chrome only has one panel/view active all the time, and we have several instead. Having one panel with a custom scrollbar and the others with the OS scrollbar is more confusing, I'd say.

Besides, this is the first complain I've heard about this, so we shouldn't rush to *fix* it.

**Comment by goanpeca** [comment]
>Having one panel with a custom scrollbar and the others with the OS scrollbar is more confusing, I'd say.

It is just the same scrollbar, only that it has warnings painted on top of it (like chrome does). I am not sure why @jnsebgosselin POC looks so different if he used the OS Scroll bar.

>Besides, this is the first complain I've heard about this, so we shouldn't rush to fix it

Not really, some other issues regarding waste of horizontal and vertical space addressed this issue as well. This is definitely not the first time it comes up.

**Comment by jnsebgosselin** [comment]
> I am not sure why @jnsebgosselin POC looks so different if he used the OS Scroll bar.

I changed it with setStyleSheet. If I use the default style of the OS, it works, but it doesn't look very good when the OS theme is not a flat one like in Windows 7 for example.

![image](https://user-images.githubusercontent.com/10170372/29934497-705d5f8a-8e49-11e7-9c73-06bbce56dd7b.png)

**Comment by jnsebgosselin** [comment]
Ok, Here's my feedback after working for a day or two with the POV I've presented above. I agree with @ccordoba12 we should not rush to fix this and at the same time, I agree with @goanpeca there is a duplication that is undesirable here. So let's continue to brainstorm a little bit on this topic while it is still hot :)

So, working with the custom toolbar with the flags painted over it is working great. Better than the original design I must admit. That being said, if we use the OS default scrollbar, I bet this won't look good for a lot of OS themes. So to be sure to offer a consistent experience across all platforms and themes, I think we would have to impose a flat style for the editor scrollbar. I'm with @ccordoba12 on this, I don't like that very much...

So I've thought about this a little bit more and I've come up with another idea that is presented in the animation below. 
- Firstly, I've removed the vertical offset that existed between the _slider range indicator_ and the _scrollbar handle_. This offset was caused by the vertical space taken up by the up/down scrollbar arrow buttons. This way, the scrollbar handle position can now be used directly as a slider range indicator to see what part of the file is shown on-screen from the scrollbar area.
- Secondly, I've toned down the color of the slider range indicator from white to grey.
- Thirdly, the slider range indicator is shown only on mouse hover and also follow the mouse cursor position. This way, it helps to better position what part the file we want to show on-screen when clicking on the flag scrollbar area.

Of course, with this we do not save any horizontal space, but we are assured of a consistent experience across different platforms and OS, we address the duplication issue raised by @goanpeca and finally the issue that was raised in the OP about the annoying double scrollbar handle.

![scrollbar4](https://user-images.githubusercontent.com/10170372/29979469-90799106-8f13-11e7-9981-7e9a05fdbf48.gif)

**Comment by goanpeca** [comment]
@jnsebgosselin thanks a lot for working on this POCs :-), I would personally prefer to have a single OS scroll bar with stuff on top of it but the middle ground is probably what you propose so :+1:

**Comment by jnsebgosselin** [comment]
@goanpeca hehe well, there is still room for other ideas :). I'm testing stuff while working, so maybe I'll think of something else.

The thing with drawing flags on the scrollbar is, we won't have control over how it looks like on different OS. I don't know if you agree with me, but for example in Windows 7, it doesn't look very good... Chrome force a flat toolbar, so it looks good even in Windows. Do you have any idea how we could solve this problem?

**Comment by ccordoba12** [comment]
From all @jnsebgosselin POCs, I prefer the last one the most.

> Do you have any idea how we could solve this problem?

@goanpeca is working to style the entire application, so (as part of that work) we would be able to define a custom style for scrollbars too.

**Comment by jnsebgosselin** [comment]
@ccordoba12 yeah me too.

I think I may have found an interesting idea that could make my last approach more interesting. What if  when in the editor, we bind the navigating capability of the `flagscrollarea` with a keyboard modifier key? This would make the `flagscrollarea` even more useful and this would minimise the mouse travel length for navigating within the file. What do you think?

![scrollbar6](https://user-images.githubusercontent.com/10170372/29990489-1b1cb628-8f49-11e7-905a-f5b07b2fa525.gif)

**Comment by jitseniesen** [comment]
I also like what @jnsebgosselin showed  [five posts above](https://github.com/spyder-ide/spyder/issues/5085#issuecomment-326630958). I hope it will look as good in the default light background. I'm a bit less sure about the keyboard modifier idea, but it will not really bother people who won't use it so I'm not against it.
