### ISSUE TITLE
DMG Installers for New Versions

### ISSUE THREAD

**Issue by FuriouslyCurious** [spyder-ide/spyder#5091]
## Description of your problem
The latest DMG I could find is from Nov 2016.  I don't like to pollute my native OS with packages, so all my Python environment and Anaconda are Dockerized.  

Are there any plans to update the DMG?

**What is the expected output? What do you see instead?**

An updated DMG image with each major release would be helpful to many.

**Comment by ccordoba12** [comment]
> Are there any plans to update the DMG?

No, there aren't, sorry.

**Comment by goanpeca** [comment]
@ccordoba12 since I have a mac, I could potentially do this if needed, but then again, I think having a dmg of spyder defeats the purpose of updating installing new packages etc. Thoughts?

**Comment by ccordoba12** [comment]
I think we should really invest time in `menuinst`. The DMG is convenient for macOS users because it has good integration with the Dock and Finder. But we could add that to `menuinst` and avoid maintaining more stuff that we can process.

My idea is to push for Anaconda as our only supported source of installation, and leave pip and any other method as alternative and for experts only.

**Comment by ccordoba12** [comment]
I mean, that's why RStudio and Matlab are so stable: because they are a unified platform at the bottom. We're never going to achieve that if we try to support every installation method under the sun :-)

**Comment by goanpeca** [comment]
Agree, I am working on `menuinst` then ;-)

**Comment by ccordoba12** [comment]
Great! Thanks a lot!!
