### ISSUE TITLE
Static Code Analysis Not Reading .pylintrc file

### ISSUE THREAD

**Issue by yahiakala** [spyder-ide/spyder#5345]
I have a .pylintrc file in the Spyder project directory and in the file directory (it is located in a subdirectory). It has the following line in the [MASTER] block:

extension-pkg-whitelist=numpy

It also has the following lines in the [TYPECHECK] block:
ignored-modules=numpy
ignored-classes=optparse.Values,thread._local,_thread._local,numpy

However, the code analysis still gives me an error on the second line of these two:
time1 = df.index.to_datetime()
time2 = np.array([time1.year, time1.month, time1.day,
                          time1.hour, time1.minute,
                          time1.second, time1.microsecond/1000]).transpose()

The error is [E1101] Instance of 'list' has no 'transpose' member

Is there another directory that Spyder's call of Pylint must be reading from? How do I check this? Also, my project is on a shared network drive (temporarily). 

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: Anaconda 3.6
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: Windows 7

**Comment by ccordoba12** [comment]
Sorry, at the moment we don't read the contents `.pylintrc` when running Pylint inside Spyder.

You're welcome to send us a pull request to provide this functionality.

**Comment by CAMGerlach-Baron** [comment]
I've been able to do this just fine on a per-user basis on Windows by just editing the .pylintrc file in my user folder (`/Users/username/,pylintrc`). I would guess what is missing is per-project reading/overriding of this?

**Comment by ccordoba12** [comment]
I think so, yeah.

**Comment by MrFuppes** [comment]
sorry to necro-bump this; but is this issue (really) still open?
just ran into the same issue with the wxpython package. In VS Code, I can circumvent this by adding extension-pkg-whitelist=wx to the settings.json. But most of the time I prefer to use Spyder and [CAMGerlach-Baron](https://github.com/CAMGerlach-Baron)'s solution unfortunately does not work for me; pylint seems to ignore the pylintrc file I tell it to use...

**Comment by tovogt** [comment]
I suggest using `self.process.setWorkingDirectory(getcwd_or_home())` in https://github.com/spyder-ide/spyder/blob/master/spyder/plugins/pylint/widgets/pylintgui.py#L320 and specifying the full path to the file in https://github.com/spyder-ide/spyder/blob/master/spyder/plugins/pylint/widgets/pylintgui.py#L341 and https://github.com/spyder-ide/spyder/blob/master/spyder/plugins/pylint/widgets/pylintgui.py#L343

Alternatively, we could check for a `.pylintrc` file in the project directory and - if found - make note of it in the GUI widget. In the widget we can give the user an option to use this `.pylintrc` (checkbutton) and - if so - explicitly pass the path to the `.pylintrc` file by adding the `--rcfile` option to the `p_args` in https://github.com/spyder-ide/spyder/blob/master/spyder/plugins/pylint/widgets/pylintgui.py#L348

What do you think, which one do you prefer?

**Comment by ccordoba12** [comment]
@tovogt, thanks for your suggestions. We were thinking to implement something similar with @goanpeca.

@goanpeca, what do you think?

**Comment by goanpeca** [comment]
Yes, indeed this is in out to do list. I prefer the option that does not add any extra options for the user and does "the right thing"

Is there an actual use case where a user might be with a project open and wants to use a different pylint? like the global one? if this is the case then indeed we might have to add an option to select between global pylint config and current project config (if a project is open of course)

**Comment by tovogt** [comment]
You could have a `.pylintrc` in the project's root and additional `.pylintrc` files in subdirectories that are supposed to apply only to the files in the subdirectories. This as open issue with pylint, see https://github.com/PyCQA/pylint/issues/618.

**Comment by TungCQS** [comment]
Hi, can I ask if this is still true? 
"Sorry, at the moment we don't read the contents .pylintrc when running Pylint inside Spyder."
I have tried putting .pylintrc in various places, even in the environmental variable PYLINTRC , but it seems like running Code Analysis within Spyder does not read any .pylintrc file at the moment. It would be good if you could confirm, thanks.

**Comment by ccordoba12** [comment]
> Hi, can I ask if this is still true?
> "Sorry, at the moment we don't read the contents .pylintrc when running Pylint inside Spyder."

Yes, it is. We'll try to fix it in a couple of months.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Modifying pylint settings via a `.pylintrc` in my home directory used to work as of my message above), but I can confirm it doesn't as of Spyder 4.x (not sure about before; of course, per project settings with the `.pylintrc` in the working directory doesn't work either), while running the standalone `pylint` command from the same `conda` env on the same file does pick up the custom settings. I understand why per-project settings doesn't work but I'm not sure why Pylint isn't still falling back to the `.pylintrc` in the user home directory, as I don't see anywhere obvious that Spyder is overriding this.

For reference, the one approach that _does_ work currently with Spyder is including the `.pylintrc` in a parent directory of the file in question, _inside_ the package directory (e.g. `project_dir/src/package_name/.pylintrc` for a file `project_dir/src/package_name/subpackage_name/module_name.py`) so that pylint finds it; however this won't work for code that isn't in a package (analysis scripts, tests, etc), and separate `.pylintrc` files will be needed for every package (due to global configuration in the home dir apparently not being picked up).

While the change in #10751 will make this approach stop working (since the working directory will no longer be inside the module, unless the user manually puts it there), a duplicate `.pylintrc` file in the project directory is needed anyway if one wants to run `pylint` from the command line or use an automated linter (e.g. on a CI) on the project, as I will be. This actually does have one small advantage, however, as the user can enable different checks to be run in Spyder and in an external/automated/CI linter run in the normal fashion; one use case of this is ignoring failed imports in Spyder but not on a CI—since Spyder runs Pylint in _Spyder's_ environment, not that of the project. However, with some extra work, one can simply specify a different config file or Pylint options on the command line when calling Pylint outside of Spyder so this certainly isn't worth keeping just for this behvior.
