### ISSUE TITLE
Auto suggestion for variables (Enhancement)

### ISSUE THREAD

**Issue by geekonloose** [spyder-ide/spyder#5398]
Right now IDE can suggest when type for example,
If I type "plt." it will suggest suitable options like close, legend, etc.

But when I type variable name it don't show suggestion to complete. 

I have many variables in my program and auto-suggesting for completing variable would ease my task.

**Comment by bcolsen** [comment]
Right now the code completion actually can complete variable names, strings and methods/properties of objects.

It can't complete everything because somethings are difficult to figure out.

If there is a particular code example that doesn't work for you I could help more.   

The code completion is  particularly poor with matplotlib, but hopefully things will be better in the 2.1 release (should be soon)

**Comment by geekonloose** [comment]
I am not saying auto complete is not working. But, I think every time pressing "ctrl + space" to complete variable is tedious task. Instead, Automatically suggestion should pop as soon I type.

Example, I have many variable like number_density_in_pipe, number_density_in_vessel, number_density_xxx
so As soon I start typing number it should suggest all variable starting from number.
I hope this can be implemented.

**Comment by ccordoba12** [comment]
@geekonloose, we aware of this and we're thinking to make code-completion work without pressing `Tab` or `Ctrl+Space` by default.

**Comment by geekonloose** [comment]
Oh. It would be great. Thank you. Apologies for redundant issue
