### ISSUE TITLE
Enhancements proposal related to the undocking and docking of plugins in the Main Window

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#5515]
Some observations that I've noted regarding the undocking/docking of plugins in the mainwindow. This is a follow up of PR #5487 and #3824.

1. I think that new windows should  be created when undocking plugin from their cog menu when `Lock panes` is checked. Currently, undocking a plugin from its cog menu never create a new window, whether `Lock panes` is checked or not.

![undocking_cog](https://user-images.githubusercontent.com/10170372/31684291-3521eca0-b34d-11e7-8a24-1168b059b275.gif)

2. The `Undock` action in the plugins cog menu is not disabled when undocking plugins through their undock button. This does not generate any error, so it's not a big deal, but it is confusing a little bit.

![undock_not_deactivated](https://user-images.githubusercontent.com/10170372/31683816-eed4fc7a-b34b-11e7-9576-004c6013ce65.gif)

3. Instead of disabling the `Undock` action in the plugin cog menu when it is undocked, I would replaced it by a `Dock` action.

![image](https://user-images.githubusercontent.com/10170372/31684553-27703246-b34e-11e7-96ac-e8f8bb9adaf2.png)

**Comment by ccordoba12** [comment]
@dalthviz, what do you think about @jnsebgosselin's suggestions?

**Comment by dalthviz** [comment]
@ccordoba12 and @jnsebgosselin 

## About 1:
I think the idea of having the undock action was to replace the native action that you can do to only undock one plugin (without having the others unlocked). However if you guys think that simplifying this behavior to two states (everything can be undocked or anything can't be undocked) based on the `lock panes` check is better or more simple to understand I think is ok :+1:
## About 2:
I think we should change this since as @jnsebgosselin say could be confusing.
## About 3:
I think this could be done to have more points of interaction with the docking behavior since currently the way to dock again the plugin is closing the window (which maybe people initialilly wouldn't do beacuse could think that they will close the plugin completly).

**Comment by jnsebgosselin** [comment]
Thank @dalthviz for the answer.

About 1
----

Point 1 is important if we still go with what I've proposed in [here](https://github.com/spyder-ide/spyder/issues/2855#issuecomment-329789598) to hide the plugin taskbar when `Lock panes` is checked. If we do that without changing the "create-a-new-window-from-cog-menu" behaviour, what you've done in PR #3824 will almost never be used.

So we need to clarify that before I can start working on spyder #2855.

**Comment by ccordoba12** [comment]
About 1.
----

You're right @jnsebgosselin, but I think that when *Lock panes* is active we should change the name of the action from *Undock* to *Move to new window* (or something like that), to not associate two different behaviors to the same action when *Lock panes* is on or off.

About 2 and 3.
----

@dalthviz, please implement Jean's suggestions in a new PR.

**Comment by jnsebgosselin** [comment]
@ccordoba12  alright. Do you want me to take care of point 1 while working on a PR for #2855?

**Comment by ccordoba12** [comment]
Sure, please go ahead!
