### ISSUE TITLE
Online help index contains invalid links

### ISSUE THREAD

**Issue by homofortis** [spyder-ide/spyder#5533]
## Description

**What steps will reproduce the problem?**

1. Select Online Help
2. From the "pinky" index page select any topic or link
3. "Unable to load page" is displayed and "lank" is inserted in Module or Package text box

**What is the expected output? What do you see instead?**
Load and display the selected topic's html page

**Please provide any additional information below**

----------------------------------------

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.9.1, PyQt5 5.9 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.4 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
psutil >=0.3     :  5.4.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
Sorry, this is not a Spyder issue. The only thing we do is to render what the `pydoc` module provides.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 I'm seeing this as well; the issue isn't necessarily "invalid internal links" but that clicking any link, on any page, doesn't work and produces the text ``lank`` in the search bar while entering the name directly in the search box does. I tested in Spyder 3.2.6-3.3.2 and Python 3.6.5-3.7.1 in several different environments and all of them produced the error. However, realistically this seems unlikely to be fixed since the ``Online Help`` pane was removed in Spyder 4, apparently in favor of the standard "Help" pane since it displays essentially the same information (except without links and forward-back navigation, although the latter wouldn't be too difficult to implement since it already remembers search history).
