### ISSUE TITLE
sorting dict keys

### ISSUE THREAD

**Issue by usmanov** [spyder-ide/spyder#5592]
## Description
spider sorting my dictionary in alphabetical order
**What steps will reproduce the problem?**

1. c = {'y': 1, 'o': 2, 'c': 2, 't': 2, 'z': 1, 'h': 1, 'a': 1, 'u': 2}

2. c
Out[61]: {'a': 1, 'c': 2, 'h': 1, 'o': 2, 't': 2, 'u': 2, 'y': 1, 'z': 1}
3. 

**What is the expected output? What do you see instead?**
why is spider mutating my dictionary?

**Please provide any additional information below**
When I'm creating dictionary with unsorted elements, spider returning it sorted 

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by Prikers** [comment]
This is a python behavior rather caused by spyder (below is a regular ipython console outside of spyder). 

`dict` have no particular order in python and you should never rely on or expect any kind of order from a `dict`. If you need an ordered dict-like object you can refer to [`OrderedDict`](https://docs.python.org/3/library/collections.html#collections.OrderedDict)

![image](https://user-images.githubusercontent.com/20270441/32119646-319472f4-bb56-11e7-8345-bc5aa2e74b0b.png)
