### ISSUE TITLE
Cannot run static code analysis on Spyder 3.2.4

### ISSUE THREAD

**Issue by Giangblackk** [spyder-ide/spyder#5640]
## Description

**What steps will reproduce the problem?**

1. Open Static code analysis
2. Open A python file
3. Press Analyze button

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

KeyError: None

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 2.7.14
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.11.3 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.4.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one.

**Comment by rlaverde** [comment]
This is related to #4992, although the validation is working well, It isn't called at startup (the issue only happens when opening the plugin, and not when editing the filename)

I think is enough to move the rdata loading to the end of the init, and disable the button if not rdata is found:
https://github.com/spyder-ide/spyder/blob/master/spyder_pylint/widgets/pylintgui.py#L172
```
if self.rdata:
    self.remove_obsolete_items()
    self.filecombo.addItems(self.get_filenames())
else:
    self.start_button.setEnabled(False)
```
