### ISSUE TITLE
error on saving data from variable explorer

### ISSUE THREAD

**Issue by hiteshnitetc** [spyder-ide/spyder#5647]
I am unable to save data from variable explorer. When i click Save data it gives error `unsupported file type`  How to solve it
![screenshot from 2017-11-03 13-10-28](https://user-images.githubusercontent.com/30615882/32364177-5465c89a-c06b-11e7-80f9-e634efc80ca7.png)
## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.11.0 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.24.1 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  4.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. Unfortunately, we can't save all data types present in the Variable Explorer, and when that happens we show the message you're currently seeing.

We're aware this is a limitation and we're working to fix it for Spyder 4, to be released next year.

**Comment by hiteshnitetc** [comment]
thnx

**Comment by hiteshnitetc** [comment]
with reference to #7249 i have various various type like int,float,list,bool,str. @CAM-Gerlach please see the issue

**Comment by CAM-Gerlach** [comment]
Okay, what is the *exact* error message you are getting @hiteshnitetc ?

> various various type like int,float,list,bool,str

None of those types are going to cause a problem; I also tested various numpy arrays and scalars and lists of the same, with no issues. It's very likely one of the special object types you have loaded, quite possibly list ``cb1`` with ``TimingCallback``, which [some Googleing](https://stackoverflow.com/questions/4831178/how-to-pickle-a-callback-chain) suggests might have problems being pickled.

Therefore, to isolate the issue, please run ``del <variable_name>``, e.g. ``del cb1``, on any types (or collections of the same) that are are objects and aren't numpy scalars/arrays or pandas series/dataframe, starting with the most esoteric ones first, and after each one try saving. Once saving spydata starts working, you know the last type you deleted was certainly at fault, and possibly one or more of the others (carefully record which you delete). Then, to rule out any of the other types, add them back one by one (e.g. with your code) and check after each if it still works. If it doesn't, you know that one is also a problem, and you can ``del`` it again, and try the next. Then, inform us which one(s) were the problem.

You can also try pickling each potentially suspect variable (``import pickle`` then ``pickle.dump(<variable_name>, <filename>.pkl, 2)``, e.g. ``pickle.dump(cb1, cb1.pkl, 2)`` and if that doesn't work, then that variable is almost certainly one of the culprits; additionally, try replacing the ``2`` with ``-1`` and seeing it if works then, again noting this carefully to inform us which work with this setting. Then, ``del`` those variables and see if it works. If it does, and using ``-1`` also worked for pickling all of them, its a simple fix, although it would prevent Spyder on Py2 from reading sessions saved under Py3.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Some related thoughts, which I can turn into issues (for Spyder 4) if you think warranted...

* We should consider changing our pickle protocol argument to ``-1`` instead of ``2`` for Spyder 4, since on Python 3 that would correspond to protocol 4 which per [PEP 3154](https://www.python.org/dev/peps/pep-3154/) supports more and larger objects and is supported on Python >3.4, and thus all Python 3 versions, while on Python 2.7 the behavior is the same as the current. Therefore, loading data in Spyder running on Py3 from Py2 Spyder would still work which seems much more likely than the converse, which I would think is a rather uncommon usecase outside of a development environment, and by the Spyder 4 release Python 2 would be less than a year away from EoL, so going *back* to Python 2 Spyder after doing substantial work in Python 3 Spyder seems very unlikely (while upgrading would work just fine).

* We could have an option, perhaps off by default, to skip and warn on objects that can't be saved rather than fail to save anything. We could also modify the current error dialog to read something like ``Failed to save session due to unsupported objects. Error: <...> Would you like save your session without the unsupported objects? [Continue] [Abort]``

* Even more generally, it might be very handy to have a way for the user to be able to set a custom blacklist of names and/or types to not save in the preferences (and would be particularly useful on a project-specific level once project settings are implemented in Spyder 4). Besides types that can't be pickled, the user might not want to save objects that take up a lot of space, those saved elsewhere, those that are more expensive to save+load then to re-create, etc.

Thoughts?

**Comment by ccordoba12** [comment]
The dill package has the ability to save and restore the entire namespace of IPython consoles, so that's what we should for this.

However, it's not planned for Spyder 4.

**Comment by ccordoba12** [comment]
Maybe 4.1

**Comment by CAM-Gerlach** [comment]
Ah, I see. If we won't have that for 4.0, might it be worth implementing either or both of the first two options now, since the first is extremely quick to do and only has a very unlikely to be encountered downside (quite possibly less likely than an environment containing at least one object that couldn't be picked by version 2 but could by version 4), while the second should still be fairly quick and has no downsides?

The third one, meanwhile, has a lot of potential usefulness well beyond just being an easy workaround for this problem, so do you mind if I make an issue of it (with the intention of implementing it sometime before the Spyder 4 release)?

**Comment by ccordoba12** [comment]
Ok, no problem.

**Comment by hiteshnitetc** [comment]
@CAM-Gerlach Initial trial: yes cb1 was creating problem.

**Comment by CAM-Gerlach** [comment]
@hiteshnitetc Thanks. Did ``pickle``ing it work with ``pickle.dump(cb1, cb1.pkl, 2)``? What about with ``pickle.dump(cb1, cb1.pkl, 4)``?

**Comment by hiteshnitetc** [comment]
@CAM-Gerlach first i want to tell what is cb1. Actually i am working on Keras libraby. And i wanted to know execution time of my code. So from [here](https://keras.io/callbacks/) i make a callback to know the time as log stored in cb1 (for every fold from 10 fold), but it's wrong way. So i modified my code, and know that not required cb1. I removed cb1. for your above mention your two comments i got `AttributeError: 'list' object has no attribute 'pkl'`  and `pickle.dump( cb1, open( "/home/nd/Desktop/cb1.p", "wb" ) )` this works for me. But i suggest not to focus on cb1 for making changes in spyder. Because it's not general variable that every buddy will encounter. I use keras and it's from there only. And i use that may be not correctly.

**Comment by hiteshnitetc** [comment]
Some pics of cb1 (may be not useful)
![screenshot from 2018-06-08 10-13-42](https://user-images.githubusercontent.com/30615882/41141133-69df74fc-6b0e-11e8-878e-29a77298fdf7.png)

**Comment by CAM-Gerlach** [comment]
Sorry, I made a mistake in my comment. ``cb1.pkl`` should be in quotes, since its a file path. So you should run:

```python
pickle.dump(cb1, cb1.pkl, 2)
pickle.dump(cb1, cb1.pkl, 4)
```

just to check.

> But i suggest not to focus on cb1 for making changes in spyder.

Yeah, the idea is to make Spyder able to save an entire ``IPython`` namespace without errors, and some things just can't be pickled for different reasons. However, I'm curious if that small tweak will fix this problem, and likely others.

**Comment by hiteshnitetc** [comment]
ok wait for a minute. I have to re run the code.....

**Comment by hiteshnitetc** [comment]
Some code line are (using keras): `cb1=[]`; `history=model.fit(X_train, y_train,
          batch_size=10,validation_split=0.0,
          epochs=2,
          verbose=2,callbacks=[cb])` ; `    cb1.append(cb)
`

**Comment by hiteshnitetc** [comment]
@CAM-Gerlach  i got error for your mention two line are `TypeError: file must have a 'write' attribute`

**Comment by CAM-Gerlach** [comment]
Oh, my bad—I almost always use ``joblib`` (or ``pandas``) for reading and writing instead of plain ``pickle``, which take paths instead of file objects. Therefore, you should run

```python
with open(cb1.pkl", "wb") as test_file:
    pickle.dump(cb1, test_file, 2)
    pickle.dump(cb1, test_file, 4)
```

**Comment by CAM-Gerlach** [comment]
Yes, I fixed it a few seconds after I posted. What was the result?

**Comment by hiteshnitetc** [comment]
TypeError: can't pickle _thread.lock objects

**Comment by CAM-Gerlach** [comment]
Okay, thanks! I assume for both?
