### ISSUE TITLE
Improved dependency dialog

### ISSUE THREAD

**Issue by timhoffm** [spyder-ide/spyder#5652]
## Description of your problem

The current dialog is not quite clear:

![grafik](https://user-images.githubusercontent.com/2836374/32403618-f36b201a-c13e-11e7-9a23-8c5762735896.png)

- it has a lengthy textual disclaimer.
- at first I got confused, because "required" does refer to the version number, whereas I thought it was used in the sense of mandatory.
- no obvious distinction bewteen mandatory and optional dependencies: I cannot see if I'm missing some optional packages that might add additional features.

**Proposal:**

I propose to exchange the table for a tree view:

~~~
+ Mandatory Packages
  - IPython
  - ...
+ Optional Packages
  - numpy
  - ...
~~~

The columns Required, Installed and Provided features will remain.

The "(OK)" text from Installed is removed. Instead, there will be an icon at the front indicating if there is an issue.

If there is interest, I can work on a pull request. Is this something for 3.x or for 4.x?

**Comment by ccordoba12** [comment]
Hey Tim, sounds good to me! We were not aware the dialog is not clear as it is, so I'm happy to see improvements to it, specially because Spyder 4 is going to bring at least 3 more new dependencies (docrepr, spykernel and pyls).

> If there is interest, I can work on a pull request. Is this something for 3.x or for 4.x?

Sure, please go ahead! Spyder 3 is now our maintenance branch, so it only receives bug fixes and very minor features. So please make this work against master.
