### ISSUE TITLE
PYTHONSTARTUP not launched at Spyder start

### ISSUE THREAD

**Issue by GeodeZYX** [spyder-ide/spyder#5708]
## Description of your problem

I set a regular _scientific_startup.py_ script as a Startup script for Ipython 

```
Preferences > IPython console > Startup > Run a file
/usr/lib/python2.7/dist-packages/spyder/scientific_startup.py
```

But this script is not loaded directly when I start Spyder

I need  to reboot the Ipython console using the "Restart kernel"  button (right click on the console tab)

Only then `Imported NumPy 1.12.1, SciPy 0.18.1, Matplotlib 2.0.0` is printed in the console

Thanks for your help !

## Versions and main components
* Spyder Version: 3.2.4
* Python Version: Python 2.7.14
* Qt Version: Qt 5.9.1
* PyQt Version: PyQt5 5.7 
* Operating system: Ubuntu MATE flavor 17.10 

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this in a future release.

**Comment by glefebvr** [comment]
I meet exactly the same problem with Spyder 4.1.2 with Python 3.7.3 on Windows 10.

Note that the problem also happens when I switch from a project to another.

**Comment by ccordoba12** [comment]
This problem no longer applies because it was related to the Python console, removed a long time ago.

**Comment by glefebvr** [comment]
Python console or IPython console ?

As the initial post, I speak about IPython console. IPython 7.13.0 precisely for my case.

**Comment by ccordoba12** [comment]
The initial post talks about a script that we no longer distribute because it made part of the Python console.

That's why this issue is not valid anymore.

**Comment by glefebvr** [comment]
Ok, just let me reformulate.
Because, even if spyder does no longer distribute this kind of script, it is now possible to define its own script. And this functionality contains a bug.

Detailed step to reproduce the bug : 
I create a file (E:/pythonstartup.py), that contains, for instance just this line :
`print('PythonStartup file was executed')`
Now, I go in Preferences > IPython console > Startup > Run a file, and I specify E:/pythonstartup.py.
Then I click on "Apply".

Now if I restart my kernel in IPython, the message is printed. If I switch to an other project the message does not appear. If I close spyder and restart it, the message does not appears also. But if I restart again the kernel, this time, the message appears.
So, in my point of view there are 2 (linked) bugs : 
- the user defined pythonstartup script is not run at the start of spyder
- the user defined pythonstartup script is not run after switching project

**Comment by ccordoba12** [comment]
@glefebvr, thanks for the detailed explanation. Could you open a new issue about it? Thanks!

**Comment by glefebvr** [comment]
@ccordoba12: Yes. Thanks to you, for the spent time to understand the problematic.
