### ISSUE TITLE
from keras.models import Sequential Kernel die, restarting

### ISSUE THREAD

**Issue by ecocarlisle** [spyder-ide/spyder#5741]
## Description

**What steps will reproduce the problem?**

1. open spyder and enter the following import: from keras.models import Sequential
2. hit f9

**What is the expected output? What do you see instead?**
Sequential is imported

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.2 
* Python Version: 3.6.0
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Does this work outside Spyder? I mean, for example in the Jupyter notebook?

**Comment by ecocarlisle** [comment]
No.

But it does work in Python 3.5.

**Comment by ccordoba12** [comment]
> No.
>
> But it does work in Python 3.5.

Then it's not a Spyder problem, it's a Python or Keras problem.

Please try to update to the latest Python 3.6 version because 3.6.0 has some problems with compiled modules. If that doesn't work, please stick with Python 3.5. I don't have any better advice to give you.

I'm closing this issue because it's not related to Spyder.
