### ISSUE TITLE
IPython console missing features with respect to the old Python console

### ISSUE THREAD

**Issue by jpoeppel** [spyder-ide/spyder#5759]
As discussed over in gitter, this issue is intended as a collection of the issues I encountered with the ipython console compared to the old python console. Those below are just those, that came to my mind right away. I might extend upon this, when I run into more things, or open separate issues then.

Some things may work in a different way than before, so feel free to take those out:

* Slow re-starts of the ipyhon console (Which can even freeze other parts of spyder). While one usually does not need to do this often, in some projects it might be desired/required to occasionally restart.
* Elapsed time of scripts: One of my favourite features of the old python console was the display of the elapsed time. Really nice for long running scripts.
* Variable Explorer cannot lookup variables before execution of scripts ended: In 3.1. you could hit "refresh" in the Variable Explorer, even while a script was running and one saw the current namespace and it's variables, allowing one glimpses into the running code. AFAIK this is not possible in 3.2.4 (at least I cannot find a refresh button anymore)

Very minor:
* Cannot restart a script with a single click on the console pause/rerun. (I could click on run, but that requires switching to that script in the editor first, when I am working on a different file, as I said, very minor and something I can get used to, especially since I could execute the "runfile(XY)" command in the console manually with the keyboard)

I should probably open a separate issue for this, but as I am already talking about it:

When I run a script in an ipython console, the button "Stop current command" is not enabled. If however, I use the "runfile" command, the button is enabled. I guess this is not intented?

**Comment by ccordoba12** [comment]
Thanks for taking the time to opening this issue!

We can solve the first, second and fourth of your issues for 3.2.5, and take a look at your last problem. The third one (updating the Variable Explorer while code is running) is not possible because of limitations of the IPython/Jupyter architecture, sorry.

**Comment by jpoeppel** [comment]
@ccordoba12 That sounds great already! I miss the python console since I am more used to it in my workflow, but that didn't make me reconsider using spyder yet, especially not with all the cool things in the pipeline for spyder 4 :-)

**Comment by ccordoba12** [comment]
@jpoeppel, in PR #5878:

1. I improved kernel startup time, but it's still slow compared to the old Python console. That's because we need to always load IPython, and that's a big package.
2. We added a button to reset kernels instead of restarting them. That's way faster and it's equivalent to restarts.
3. I added the Elapsed time feature to the IPython console.
4. I decided to not add a button to rerun files, sorry. That's something we can't easily implement in the IPython console.

Please open a new issue about your last problem, so we can take a look at it in the future.
