### ISSUE TITLE
'runfile' is not defined

### ISSUE THREAD

**Issue by simeb** [spyder-ide/spyder#5809]
## Description of your problem

When I try to run a script in Spyder, I get the following error "NameError: name 'runfile' is not defined"

**What steps will reproduce the problem?**

1. Run any script in Spyder

**What is the expected output? What do you see instead?**

The output of my script. Instead I get "NameError: name 'runfile' is not defined"

**Please provide any additional information below**

It worked until recently, but some reason it stopped. I tried the usual steps for fixing this problem like resetting Spyder to factory setting, but nothing worked.

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 3.6.2
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Windows 10

## Dependencies

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by CAM-Gerlach** [comment]
If you search for it, this error has been reported many times before from different causes (perhaps the most prolific being #3428 ); apparently some cases are bugs in Spyder and others are due to something going wrong during installation or something else gone wrong on the user side of things. If you have not already, you could read through those threads carefully and make sure none of those user-side fixes resolve your issue.

Other than that, you could try reinstalling a clean copy of anaconda, or at least installing Spyder in a clean conda-env, and seeing if the error persists. If so, and a more specific fix is not readily offered and a non-user cause is not ruled out, it would be important to know exactly what changed in your environment between when Spyder worked and when it didn't (OS, Python, Spyder, package updates, configuration, etc.), as that would be the main way to narrow down the problem.

**Comment by simeb** [comment]
Re-installing anaconda fixed the problem. Thanks for your help
