### ISSUE TITLE
variable explorer does not show pandas DataFrame, gives dir() instead

### ISSUE THREAD

**Issue by weichm** [spyder-ide/spyder#5819]
## Description of your problem

**What steps will reproduce the problem?**
```python

import pandas as pd
x = pd.DataFrame({"a": np.arange(1,10)})
```
double-click on x in variable explorer

**What is the expected output? What do you see instead?**
I expect to see a table showing the values of pandas DataFrame.
Instead, I see all the attributes of DataFrame x, like some enhanced version of dir(x) would give:
![image](https://user-images.githubusercontent.com/6342556/33153885-e84f2a00-cfe4-11e7-9fb0-0773e5e148d4.png)

**Please provide any additional information below**

I think in an earlier verision (maybe 3.2.2), variable explorer worked as expected

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.5
* Qt Version:
* PyQt Version:
* Operating system: Debian testing

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
psutil >=0.3     :  5.4.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. I'm running 3.2.4 as well on Windows 8.1 Pro, and could not reproduce the issue given your example code (nor have I seen it otherwise) with Python 3.6.3, along with a few minor differences in package versions (you have newer builds of rope, jedi, iPython and sphinx and lack cython, none of which I would think would make a difference...but you never know).

Do you get this with all data frames, or any certain (single column?) ones? Anything else peculiar about your setup?

**Comment by weichm** [comment]
I tried again my example, EXACTLY in the same way, now it works as expected.

Only reason I can imagine is a reboot in between: I had installed spyder 3.2.2 from debian repo, then `apt-get remove spyder3` (without `--purge`), then as root: `pip3 install spyder`. Then I got the problems and opened this issue. I'm sure, type of x was `DataFrame` before clicking on it.

Now I tried again, it worked, only thing in between was a reboot.

I think, perhaps we'll never know, but I'm closing this now.

Thanks for your help! Great piece of software!

**Comment by ccordoba12** [comment]
Thanks for letting us know about it!

**Comment by rockoff** [comment]
Had the same issue with spyder 3.3.2. I had to install 3.3.0 instead and it worked

**Comment by CAM-Gerlach** [comment]
I have no problem viewing dataframes in Spyder 3.3.2 on Windows 8.1 and Python 3.6.7, Pandas 0.23.4 and Spyder-Kernels 0.3.0. Since this problem occurs relatively rarely and at random to a few users, did you test with a number of different data frames and in a fresh Spyder session before taking the relatively major step of downgrading? If not, I urge you to do so and post your environment information (at least what I've posted) to give us some hope of tracking down the problem, if there is one. Furthermore, you should at least use 3.3.1 (unless it exhibits the same problem consistently) since 3.3.0. as the first release of a new minor version (3.3.x) contained several non-trivial bugs that were fixed in 3.3.1. Thanks.

**Comment by rockoff** [comment]
My bad, I tried with 3.3.2 now and it works. Maybe the fact that I restarted my computer played a role.
config spyder: 
pandas 0.23.4
Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]
IPython 7.2.0 -
Thanks for your advices

**Comment by sean-ijack** [comment]
I had the same problem with Spyder 3.3.4 and Pandas 0.24.2. DataFrames were there and I could manipulate them with code in the terminal, but they weren't visible in the variable explorer.

**Comment by JuluruAkhil** [comment]
I had the same problem when I ran Spyder as an administrator.

**Comment by CAM-Gerlach** [comment]
Are you running Spyder 4.0.1, the current version?

**Comment by JuluruAkhil** [comment]
I am running Spyder 3.3.6. The problem got resolved when I opened the application normally

**Comment by shankyemcee** [comment]
I just recently installed spyder 4.0.1 and when i try to view a dataframe in my variable explorer it only shows the dataframe attributes. How can i see my data?
![image](https://user-images.githubusercontent.com/30503832/93691822-d86a6800-fab8-11ea-9409-e54278ce1b5d.png)

**Comment by ehadavi** [comment]
See the Maintainer's response [here](https://stackoverflow.com/questions/60206250/pandas-dataframes-are-displaying-with-new-object-explorer-in-spyder-4), Only needed to install pandas and then restart Spyder
