### ISSUE TITLE
spyder run error

### ISSUE THREAD

**Issue by hedeqing** [spyder-ide/spyder#5823]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\anaconda\anconda3\lib\site-packages\spyder\plugins\editor.py", line 1711, in new
    text, enc = encoding.read(self.TEMPLATE_PATH)
  File "D:\anaconda\anconda3\lib\site-packages\spyder\utils\encoding.py", line 243, in read
    text, encoding = decode( open(filename, 'rb').read() )
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\.spyder-py3\\template.py'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.24.1 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by dalthviz** [comment]
Thanks for reporting, I think this is a duplicated of #5717

**Comment by CAM-Gerlach** [comment]
Indeed. There is also a small chance it is slightly different, in that it may be looking in the wrong user profile directory—on Windows, `Administrator` is the name of the build-in administrator account, not a normal user. Or, it could be due to not being able to create the file in that folder due to permissions issues. @hedeqing  What's your user name/user folder path? Does the file (or the .spyder-py3 directory) exist there? Did you try running `spyder --reset` from the Anaconda prompt? If that doesn't fix it, did you try uninstalling/reinstalling, for just you as a normal user?

**Comment by ccordoba12** [comment]
I think we should merge this one with #5717. I think the problem here is installing Anaconda as admin in one drive and trying to use it with a user in another.
