### ISSUE TITLE
I cant use the spyder in a right way.I hope someone help me!please!

### ISSUE THREAD

**Issue by ZhouHuiZi** [spyder-ide/spyder#5857]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/260153/anaconda2/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 1009, in create_new_client
    self.connect_client_to_kernel(client)
  File "/home/260153/anaconda2/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 1035, in connect_client_to_kernel
    stderr_file)
  File "/home/260153/anaconda2/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 1437, in create_kernel_manager_and_kernel_client
    stderr = codecs.open(stderr_file, 'w', encoding='utf-8')
  File "/home/260153/anaconda2/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 13] Permission denied: u'/tmp/spyder-260153/kernel-69d70d4a69c9.stderr'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.1.3 (OK)
pandas >=0.13.1   :  0.19.2 (OK)
numpy >=1.7       :  1.11.3 (OK)
sphinx >=0.6.6    :  1.5.1 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.9.0 (OK)
psutil >=0.3      :  5.0.1 (OK)
nbconvert >=4.0   :  4.2.0 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.25.2 (OK)
qtconsole >=4.2.0 :  4.2.1 (OK)
IPython >=4.0;<6.0:  5.1.0 (OK)
pylint >=0.25     :  1.6.4 (OK)

```

**Comment by CAM-Gerlach** [comment]
First thing to check would be whether there are any Unicode (non-ASCII) characters in the file path, specifically your username/user directory name—particularly in Python 2, that's liable to cause problems, though its not clear that's what's happening here. If so, the solution for the near term is to either remove/replace those characters from the path name, or upgrade to Python 3.

Other than that, you could try running `spyder --reset` at the terminal/bash prompt, and then try reinstalling Anaconda. Also, if you install anything with `pip` rather than `conda`, that's liable to cause weird problems, so you can uinstall any of that. You can try updating your dependencies; while none stands out as an obvious problem a lot of them look rather outdated. Finally, there is always a slight chance it might actually be a permissions issue with the `/tmp/` directory or the `spyder` subdir, so you could at least check to see if that looks (w)right(able) assuming you know what you're doing there. Best of luck!

**Comment by ccordoba12** [comment]
Yeah, this seems a permissions problem in your `/tmp` directory. You need to fix that for Spyder to work.

**Comment by ZhouHuiZi** [comment]
@CAM-Gerlach @ccordoba12  thank you so much!!!  I had fix this problem by using `spyder --reset` .it's worked for me.
![2017-12-01 08-20-34](https://user-images.githubusercontent.com/33747050/33462890-52ab7d68-d675-11e7-9891-7eb3df3123aa.png)

**Comment by ccordoba12** [comment]
Really glad to hear that!

**Comment by CAM-Gerlach** [comment]
Fantastic!
