### ISSUE TITLE
h

### ISSUE THREAD

**Issue by somayekarimi** [spyder-ide/spyder#5870]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 2.3.8 
* Python Version: 3.5.2
* Qt Versions:  4.8.7, PyQt4 (API v2) 4.11.4 on Linux

## Optional dependencies
```
pyflakes >=0.6.0   :  1.1.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pygments >=1.6     :  2.2.0 (OK)
IPython >=1.0      :  6.0.0 (OK)
zmq >=2.1.11       :  16.0.2 (OK)
qtconsole >=4.0    :  None (NOK)
pandas >=0.13.1    :  0.17.1 (OK)
sphinx >=0.6.6     :  1.3.6 (OK)
psutil >=0.3       :  3.4.2 (OK)
rope >=0.9.2       :  None (NOK)
jedi >=0.8.1;<0.9.0:  0.10.2 (NOK)
matplotlib >=1.0   :  2.0.2 (OK)
pylint >=0.25      :  1.7.4 (OK)

```

**Comment by CAM-Gerlach** [comment]
Sorry, if you don't add any information about what your actual issue is (not to mention, there's a good chance it is has something to do with a positively ancient Spyder version and/or missing/incompatible dependencies) this issue will be swiftly closed/deleted. All I can suggest is you update to the latest Anaconda.
