### ISSUE TITLE
Is there any way to change the font for the entire application?

### ISSUE THREAD

**Issue by liuxsdev** [spyder-ide/spyder#5942]
## Is there any way to change this font
![22](https://user-images.githubusercontent.com/11004456/33801249-1121ecde-dd90-11e7-8859-c8e3a0e76ad9.png)

the font in right is "Simsun" ,so uglily

宋体在这儿(和其他地方)太违和了，好丑，有办法改掉吗？

## Versions and main components
* Spyder Version:3.2.4
* Python Version:
* Qt Version:
* PyQt Version:
* Operating system:Windows 10

**Comment by ccordoba12** [comment]
That font is controlled by Windows, not by Spyder. Does other applications in your system look the same?

**Comment by smilevent** [comment]
Thank you! Finally I found a way to change the windows default font. It looks much better now.
In my computer the Mendeley has the same question and for 7 years ,it has't improved it.
I hope Spyder can make font looks better in Windows(Chinese edition), for the fact that the "Simsun" font has Highest priority 。

谢谢你！最终改了windows的默认字体，基本解决了这个问题。
我电脑上mendeley也是这样的问题，原因可能是软件没有对字体进行设置（我也学过 一点点QT，控件自定义字体不是很难吧)，宋体在系统中优先级很高，但其英文字体效果太差。
还是希望Spyder进行一些改进。

**Comment by CAM-Gerlach** [comment]
Glad you got it fixed!

@ccordoba12 Is there anything more than can be practically done on the Spyder side regarding this, or can this be closed?

**Comment by loveritsu929** [comment]
Hi, sorry to bring this up.  But I probably run into the same issue, and this seems to be the only one talking about this.

My spyder now show this serif font in the working directory, file title, pane title, pop-up window, and even code completion, see the screenshots:
![image](https://user-images.githubusercontent.com/20154344/98863273-21de9000-2436-11eb-95e1-bf6c8df386a4.png)
![image](https://user-images.githubusercontent.com/20154344/98863316-2efb7f00-2436-11eb-828e-fab0af4e820a.png)
![image](https://user-images.githubusercontent.com/20154344/98863338-3589f680-2436-11eb-885f-2f1bbe2058c3.png)
![image](https://user-images.githubusercontent.com/20154344/98863385-420e4f00-2436-11eb-94b7-c5bdbbcfc373.png)

I have tried to change the windows default font using noMeiryoUI  [https://github.com/Tatsu-syo/noMeiryoUI](url). However, these do not change, though they are supposed to follow the system setting.

I believe this issue appears after several updates I have done, includes updating win10 to version 2004 (English system with some Chinese fonts installed), updating conda, and updating spyder from 4.1.2 to 4.1.5.  Rolling back spyder doesn't help. I just reinstall the lastest anaconda and spyder, the issue is still there.

What method do you use to change the default fault? @smilevent

This issue doesn't affect the function of spyder but it's pretty annoying.  Could you take a look at this? @ccordoba12 

Thank you

**Comment by loveritsu929** [comment]
Sorry for bothering you guys, but I may find an explanation && solution for this.

1. The windows fallback font for Chinese in win10 is set back to SimSun. Even worse, in win10 with Chinese installed as a second language, the default font for English in QT programs will be this SimSun.
2. Qt will call two Windows APIs `SystemParametersInfo` and `GetStockObject` (older win32 API) to get system default font. So even though they are all supposed to use the default one, the widgets may have different fonts.
3. For Chinese & Japanese communities, the default Chinese/Japanese serif font looks awful on high DPI monitors.
4. Then I simply change the value of `SimSun （宋体&新宋体）` in regedit to any other desired fonts, e.g., consolas.ttf

Source:
1. [https://stackoverflow.com/questions/11011238/how-do-you-get-system-default-font-settings-in-qt](url)
2. [https://shuhari.dev/blog/2018/10/qt-new-font](url) (Chinese)
3. [https://zhuanlan.zhihu.com/p/120299074](url) (Chinese)

**Comment by dalthviz** [comment]
Thank you for the info @loveritsu929 , glad is working for you now :+1:

**Comment by ccordoba12** [comment]
Thanks @loveritsu929 for bringing this one up to our attention again. We'll address it in our 4.2.2 version, to be released nex February.

**Comment by Firestar-Reimu** [comment]
![image](https://github.com/user-attachments/assets/4f02749b-69a0-46ac-97da-8de468060700)

@loveritsu929 can you have a look at https://github.com/spyder-ide/spyder/issues/22445 , thanks!
