### ISSUE TITLE
UserWarning: Config option use_jedi not recognized by IPCompleter

### ISSUE THREAD

**Issue by TheTinka** [spyder-ide/spyder#5944]
I really don't know why this happen suddenly all the time. A module of mine isn't  running anymore. I get this warning: 
UserWarning: Config option `use_jedi` not recognized by `IPCompleter`.   self.config = config
And than "Kernel died, restarting".

I'm not able to fix it on my own. Even when I take back my changes I get that message.
Thank you for every helpfull hint.

Additional:
![image](https://user-images.githubusercontent.com/22595315/33804086-d48a5258-dd9d-11e7-9b37-acb5857dcc9a.png)

## Versions and main components

* Spyder Version:  3.2.4
* Python Version:  3.6.1
* Qt Version:  5.6.2
* PyQt Version:  5.6.0
* Operating system: Windows 10, 64-bit

## Dependencies

IPython >=4.0    :  5.3.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. So it only happens in your module? Have you tried to run it in `qtconsole`, `iPython`, and normal python in that order? If it doesn't work in any of them, then the problem, if it isn't something with your module, probably lies closest to with whatever it didn't work in last, and so the bug (if it is one) should be reported at their respective repos instead. 

Given it involves `jedi`, there is a slight chance it could be related to the recent bugs people have been having, so you can try updating `jedi` to the latest version and/or making sure you don't have `parso` 0.1.1 installed (rather than 0.1.0). You could also try a `spyder --reset` just in case it is a spyder issue (though that is very unlikely to fix it I'd think), and doing a clean (re-)install of Anaconda, uninstalling it if you have it. 

Other than that, if you can't isolate it to a bug in Spyder or one of the packages you are using, then something like Stack Overflow would probably be a more appropriate place to post the relevant section of your code and get help.

**Comment by ccordoba12** [comment]
Thanks for reporting. The Jedi part of this problem will be fixed in PR #5878.

**Comment by ccordoba12** [comment]
Let's hope that fixes your other problem.

**Comment by TheTinka** [comment]
Thanks for your tips. The UserWarning has disappeard, but my Kernel is still dying. I did reset spyder, but it doesn't help. I have installed parso 0.1.1. What would be the recommended version? The execution in  qtConsole doesn't make it better, the Kernel still dies. I will test to reinstall anaconda and report afterwards.

**Comment by ccordoba12** [comment]
Sorry but Spyder can't be responsible for your kernel dying because the 
kernel runs in a separate process from Spyder. Most probably it has to 
do with one of the packages you installed.

**Comment by CAM-Gerlach** [comment]
The latest version of `jedi`, I believe, should work with `parso` 0.1.1 as well as 0.1.0 that was compatible with previous. In any case, since as you say it still breaks in `qtconsole`, it indeed isn't a Spyder issue.

**Comment by TheTinka** [comment]
Okay... I have found the problem (the way I'm able to). 
I'm doing a simulation and uses Scipys odeint there. If the time period is by mistake zero, the Kernel dies. Isn't that a very odd reaction?

**Comment by CAM-Gerlach** [comment]
Regardless, it seems quite clear (as this occurs in qtconsole, and presumably iPython) this issue doesn't seem to have anything to do with the Spyder IDE proper. Therefore, again, assuming it isn't something with the script being run (in which case debugging, SO, etc. would be the proper response), you are much better off closing this and asking on the `iPython` repo (or whatever you can isolate it to), as there you have a chance of a useful response or a bug fix. Best of luck!
