### ISSUE TITLE
pygal.maps.world not working with spyder v3.2.4

### ISSUE THREAD

**Issue by casnow** [spyder-ide/spyder#6068]
## Description
In Spyder v3.2.4 when attempting to use the pygal.maps.world library, trying to render the svg to a file results in the following traceback error (copied and pasted to bottom of this).  Please note, the following code was tested in Jupyter on same PC.  If it matters, I'm using the Anaconda Navigator.

**What steps will reproduce the problem?**

1. To reproduce the problem try the following code:
```
from pygal.maps.world import World
wm = World()
wm.title = 'North Central and South America'
wm.add('North America', ['ca', 'mx', 'us'])
wm.add('Central America',['bz', 'cr', 'gt', 'hn', 'ni', 'pa', 'sv'])
wm.add('South America',['ar', 'bo', 'br', 'cl', 'co', 'ec', 'gf', 'gy', 'pe', 'py', 'sr', 'uy', 've'])
wm.add('North America', {'ca':34126000, 'us':309349000, 'mx': 113423000})

wm.render_to_file('americas.svg')
```

**What is the expected output? What do you see instead?**
The expected output is a svg file that looks like the attached file (I couldn't attach an svg, so this is an equivalent png).
![crash_course16-07](https://user-images.githubusercontent.com/3525243/34386106-eff75b7e-eb1e-11e7-838f-45450a986d9a.png)

**Please provide any additional information below**
Traceback (most recent call last):

  File "<ipython-input-21-ee4ded5f8da2>", line 1, in <module>
    wm.render_to_file('americas.svg')

  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\pygal\graph\public.py", line 114, in render_to_file
    f.write(self.render(is_unicode=True, **kwargs))

  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\pygal\graph\public.py", line 52, in render
    self.setup(**kwargs)

  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\pygal\graph\base.py", line 185, in setup
    self.state = State(self, **kwargs)

  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\pygal\state.py", line 35, in __init__
    merge(self.__dict__, graph.config.__class__.__dict__)

  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\pygal\util.py", line 384, in merge
    dict1[key] = mergextend(val, dict1.get(key, ()))

  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\pygal\util.py", line 370, in mergextend
    if list1 is None or _ellipsis not in list1:

TypeError: argument of type 'Key' is not iterable

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. Looking at the error trace, it appears to be entirely an issue in `pygal`, and as the latter is not on `conda` that I can tell, it can't be easily reproduced. Does the same code run in `qtconsole`, `IPython` and/or the regular python interpreter? If not, it is not an issue with Spyder and thus you should report to whichever package on that list is the last it _didn't_ work in, or `pygal` itself if it didn't work in any and you can confirm it isn't a user side issue, and close this one. Further, if you installed it with `pip`, that can also be a major source of problems and we don't really recommend it for non-experts and thus only officially support `conda`/Anaconda, though you're welcome to get it to work on your own.

If this does end up being isolated only to spyder, please let us know how you installed spyder/its stack and `pygal`, as well as any other details about the problem and we can try to help, but otherwise we'll have to close this issue after a week (7 days) as from what we have so far, it doesn't appear to be an issue with Spyder's code specifically. Best of luck!

**Comment by casnow** [comment]
Okay, so I updated to spyder 3.2.5 and it seems to work fine the first time I run it.  Second time I press F5 it doesn't work.  It was a pip install, as the conda is only available on linux.

Regardless, thanks for the heads up on pip installs.
