### ISSUE TITLE
Spyder 2 tabs looks huge on screen

### ISSUE THREAD

**Issue by shacharBD** [spyder-ide/spyder#6069]
## Description of your problem

I use spyder 2 (python 2.7) on ubuntu 16.04.
My screen resolution is 1920X1080 but spyder looks really bad, the tabs are really huge.
I changed the editor and the console fonts but I can't fix the size of the tabs.  I used the command QT_SCALE_FACTOR=1 spyder as advised in issue 4316 but that does not change anything.

I can't install spyder 3, can only use spyder 2.
![image](https://user-images.githubusercontent.com/32335220/34388457-5a54780e-eb3c-11e7-9001-eae81c46bb0a.png)

**What steps will reproduce the problem?**

1. start spyder with QT_SCALE_FACTOR=1 spyder
2. 
3. 

**What is the expected output? What do you see instead?**
smaller fonts on the tabs.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 2.3.8
* Python Version: 2.7.12
* Qt Version: 4.8.7
* PyQt Version: 4
* Operating system: ubuntu 16.04

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=1.0      :  5.5.0 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  2.1.0 (OK)
pandas >=0.13.1    :  0.17.1 (OK)
pep8 >=0.6         :  None (NOK)
psutil >=0.3       :  5.4.0 (OK)
pyflakes >=0.5.0   :  1.1.0 (OK)
pygments >=1.6     :  2.2.0 (OK)
pylint >=0.25      :  1.5.2 (OK)
qtconsole >=4.0    :  4.3.1 (OK)
rope >=0.9.2       :  0.10.2 (OK)
sphinx >=0.6.6     :  1.3.6 (OK)
sympy >=0.7.3      :  None (NOK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. I see you are using a very old Spyder version, which we don't support anymore. If you could upgrade to the latest version (preferably just upgrade everything in one go with the Anaconda distribution), there is a good chance your problem is fixed or at least addressed. Also, it has several new options for font size and HiDPI you can play around with to see if it helps; and note that while Spyder has some control over the font, it is ultimately the responsibility of the OS, so I'm not sure how much can be done. Finally, that Spyder version has been around way longer than I've been with the project, but to be honest, I don't see anything that out of the ordinary in the screenshot you posted; you'll need to be more specific. 

In any case, due to those reasons, this issue will have to be closed for now. If you update Spyder, Qt, and all dependencies with `conda` to the latest version, 3.2.5 just out now, reset your preferences with `spyder --reset`, play around with the settings, and still can't solve the problem, then please reopen with a detailed description of what specifically isn't displaying well (e.g. an annotated screenshot would be perfect) as well as what you tried in the preferences and the command line to set it right. Thanks, and best of luck!

**Comment by shacharBD** [comment]
Hi, just wanted to say thanks for your answer. Unfortunately, I can't install anaconda on the machine because I share it and it is not mine to use. When installing spyder on Linux it automatically installs spyder 2 (Unless you enable the universe repository which I'm afraid to do). But I'll try to work with it anyway. Thank you very much!

**Comment by ccordoba12** [comment]
You can use `pip` to install a more recent version. As @CAM-Gerlach pointed out, we don't support Spyder 2 anymore, sorry.

**Comment by CAM-Gerlach** [comment]
> Unfortunately, I can't install anaconda on the machine because I share it and it is not mine to use. 

You can't install it just for your user account? Or ask your sysadmin to update from such a criminally old and mismatched version of everything? That sounds like a pretty awful situation, sorry to hear it...

**Comment by shacharBD** [comment]
Hi, I managed to resize the font by changing the QT to GTK+ and then back to windows.
I didn't know that spyder3 can be installed on my user account only, since I read that you have to enable the universe repository. But I will try to do so. Thanks!
