### ISSUE TITLE
jupyter_client is missing from the requirements list

### ISSUE THREAD

**Issue by yurivict** [spyder-ide/spyder#6073]
```
Traceback (most recent call last):
  File "/usr/ports/science/py-spyder/work-py27/spyder-3.2.5/spyder/app/mainwindow.py", line 3110, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/ports/science/py-spyder/work-py27/spyder-3.2.5/spyder/app/mainwindow.py", line 3007, in run_spyder
    main.setup()
  File "/usr/ports/science/py-spyder/work-py27/spyder-3.2.5/spyder/app/mainwindow.py", line 932, in setup
    from spyder.plugins.ipythonconsole import IPythonConsole
  File "/usr/ports/science/py-spyder/work-py27/spyder-3.2.5/spyder/plugins/ipythonconsole.py", line 25, in <module>
    from jupyter_client.connect import find_connection_file
ImportError: No module named jupyter_client.connect
```

Also, if possible, please make jupiter optional, because this is a heavy dependency, it assumes that Jupiter is installed, and Jupiter assumes that NodeJS is installed, etc.

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. `qtconsole` is listed as a dependency, and `jupyter-client` is listed as a dependency of that, so it should get installed just fine normally at least using `conda` as I've successfully tested several times, in several different fashions. If you are installing using `pip` or another method, you are welcome to get it working on your own but due to the number of resulting problems with external dependencies, we recommend and can only officially support the Anaconda distribution and `conda` package manager at this time, sorry. Therefore, this issue will have to be closed for now, unless you can isolate a specific problem with Spyder. Best of luck!

**Comment by ccordoba12** [comment]
> Jupiter assumes that NodeJS is installed

That's true only if you want to develop things for Jupyter, but not for users.

**Comment by yurivict** [comment]
But it breaks with the missing ```jupyter_client.connect``` when I just run ```bootstrap.py```.
What is the recommended way to run to not use ```jupyter_client.connect```?

**Comment by ccordoba12** [comment]
There's no way to not use jupyter_client, sorry.
