### ISSUE TITLE
Consoles get renamed when moved in the IPython console

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#6098]
If I rename a console `foo` and move it next to another one, their names get swapped.

**Comment by csabella** [comment]
They don't need to be renamed for this to happen.  Just swapping two tabs causes them to switch names.

**Comment by csabella** [comment]
@ccordoba12   It appears this is a result of PR #5902.    In `tabs.py`, PR 5902 commented out the code in `mouseMoveEvent` that created the QDrag object.  Without the QDrag object, `dragEnterEvent` and `dropEvent` aren't called, which means the signals aren't emitted to `move_tabs` which does the renaming.  `editor.py` uses the `tabMoved()` signal (which was added in Qt 4.5).

As you said in #5902, I think `tabs.py` should be updated to match `editor.py`, which would mean using `tabMoved()`.  However there is also code in there to move tabs from one widget to another, so that would be lost without the custom drag and drop.  Although, it's not working anyway, so maybe it wouldn't be an issue to lose that functionality?

**Comment by ccordoba12** [comment]
Thanks Cheryl! I used your idea of switching to `tabMoved` to handle this.

> However there is also code in there to move tabs from one widget to another, so that would be lost without the custom drag and drop

You're right. I think we should remove all that code for Spyder 4.
