### ISSUE TITLE
GIT integration

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [spyder-ide/spyder#6105]
## GIT integration

**Is there any way to add GIT integration to Spyder?**

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. Currently, Spyder has basic integration with `git` via its projects support, see [here ](https://pythonhosted.org/spyder/projects.html#version-control-integration)for more details. However, much more extensive support is planned for the future and currently in work for Spyder 4.0, which was previously planned for next (northern hemisphere) summer, though is currently on hold due to Spyder losing its funding. This is addressed in issue #816 and so this, as a duplicate, will be closed.

**Comment by Abdur-rahmaanJ** [comment]
ok saw it but was 2015 so now 2018. ok thank you ! hope to add it soon. else i am using git with it manual, like any other text editor !

**Comment by CAM-Gerlach** [comment]
I understand that you're frustrated, and to be honest we'd all like to see the features we want come sooner. However, this is the same issue, and therefore discussion about it belongs there to keep everything in one place, or else it takes up more of our time toward responding to the same issue over and over and away from coding those features you'd like. 

At the moment, you can choose files to stage and commit, and run the full ``gitk`` GUI. Personally, I've used other IDEs with built in git support, but honestly prefer the command line anyway—to each their own.

As mentioned, it is one of the major features planned for 4.0, which unfortunately has been delayed since we lost our funding; as of now, so we are all just volunteers doing this in our spare time. If you'd like to make it happen faster, we'd be glad to have your help coding, documenting, and testing it, or you can help support the project at [OpenCollective](https://opencollective.com/spyder). Thanks!

**Comment by Abdur-rahmaanJ** [comment]
how to help with coding?

**Comment by CAM-Gerlach** [comment]
[CONTRIBUTING.md](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md)

**Comment by xjdeng** [comment]
Fyi, I only recently discovered this workaround:

First right click the tab corresponding to any file in your repository and click "set console working directory."

Then go to the Ipython window in Spyder and simply type your git commands (assuming Git is installed and its paths are configured properly) but append a "!" to the beginning of your command:

```
!git add "file.py"
!git commit -m "My commit"
!git push origin master
```

**Comment by loneharoon** [comment]
It seems most of the terminal commands work in Spyder console by appending `!`.

**Comment by CAM-Gerlach** [comment]
Right, using IPython escape magics...nice.

**Comment by CatalunaLilith** [comment]
> Fyi, I only recently discovered this workaround:
> 
> First right click the tab corresponding to any file in your repository and click "set console working directory."
> 
> Then go to the Ipython window in Spyder and simply type your git commands (assuming Git is installed and its paths are configured properly) but append a "!" to the beginning of your command:
> 
> ```
> !git add "file.py"
> !git commit -m "My commit"
> !git push origin master
> ```

thank you for this! 

p.s. "appending" is usually used to mean adding to the end. adding to the start is often called "prepending"

**Comment by rvelseg** [comment]
Please add to the documentation the dependence of the `git` integration on `git-cola`. Possibly [here](https://docs.spyder-ide.org/current/panes/projects.html).

In Debian 11 and Ubuntu 18.04, if `git-cola` is not installed, the `commit` button in the files sidebar does nothing, and throws no error message, even when spyder was started with the flag `--debug-info verbose`.

**Comment by dalthviz** [comment]
Hi @rvelseg thank you for the feedback. Maybe you can create an issue in https://github.com/spyder-ide/spyder-docs

Probably the info you want added could be put in the `Working with version control` section here: https://docs.spyder-ide.org/current/panes/projects.html#working-with-version-control
