### ISSUE TITLE
Sypder3 crashed on windows 7

### ISSUE THREAD

**Issue by phanqth95** [spyder-ide/spyder#6182]
## Description of your problem

**What steps will reproduce the problem?**
Spyder crashed during last session.

1.  Freshly Install python 3, spyder 3 and dependencies (matplotlib, numpy,etc)
2.  Run in CMD admin "spyder3"
3.  Crashed during session

**What is the expected output? What do you see instead?**
Spyder 3 should run fine as it is on my laptop

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.2.6
* Python Version: 3.6.4
* Qt Version: 1.3.1
* PyQt Version: 5.9.2
* Operating system: windows 7 professional SP1

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.

**Comment by phanqth95** [comment]
Thank you for your prompt reply,

I'll try Anaconda.

Best regards,

2018-01-11 1:25 GMT+09:00 Carlos Cordoba <notifications@github.com>:
