### ISSUE TITLE
Spyder will not run Anaconda 5.0.1 Windows 10 python 2.7

### ISSUE THREAD

**Issue by caca7566** [spyder-ide/spyder#6210]
## Description of your problem
1-2 succesfull starts after installation, Spyder stops working. 

**What steps will reproduce the problem?**

1. install anaconda 5.0.1 python 2.7 64 bit on my windows 10 system
2. succefully launch spyder a couple of times
3. spyder will not start anymore even after several reboots of the computer

**What is the expected output? What do you see instead?**
See above

**Please provide any additional information below**

## Versions and main components

* Spyder Version: latest supplied with anaconda 5.0.1
* Python Version: 2.7
* Qt Version: Dont know
* PyQt Version: Dont know
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
Cannot access operational menu

Help appreciated

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. Please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

If it still isn't working, please post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Calling for Help section as a comment to this issue, providing as much specific detail as possible, and we'll try to help if we can. You can get the relevant version information with ``conda list`` from the Anaconda Prompt. Otherwise, your issue will have to be closed after one week (7 days). Thanks, and best of luck!

**Comment by caca7566** [comment]
Thank you for your support.
I have read through the Basic First Aid and Emergency CPR sections that you listed. However, the thing is that there is now shortcuts to apps related to my Anaconda installtion anymore. So I cannot access anaconda prompt or any other anaconda/python related software (at least I dont know how). This happend after the first installation aswell. After the first installation I immediatly created a spyder shortcut onto the desktop if this would happen again. When I click it now, the pointer goes to "thinking mode" for a second, then back to pointer mode and nothing happens.

Because of this I cannot perform the steps in the help sections above which eg involves launching a prompt to reset spyder etc.

When I search for apps regarding anaconda, spyder or python noting is found.

Please advice how to proceed. Is the anaconda 5.0.1 not stable? Can I launch the anaconda prompt any other way?

**Comment by CAM-Gerlach** [comment]
Thanks for following up. Based on the information you've provided, it clearly looks to be a persistent issue with your Anaconda install, and well outside of Spyder's control; it has no ability to install or remove shortcuts from itself, much less other Anaconda software, and the fact that it is happening to all shortcuts, not just Spyder is a clear indicator on an Anaconda or system-level issue. However, I've occasionally been in similar situations before installing and maintaining the distribution on various machines, so I'll try to help where I can.

I'm not sure exactly what's going on; sometimes this happens for various reasons but the fact that it is persistent, and happens shortly after you successfully install it suggests it may be something going on at your system-level that's interfering—I'd immediately suspect any security/antimalware software you might have is blocking, quarantining or deleting it. Are you doing anything at all with ``conda``, updating Anaconda or individual packages, or Anaconda Navigator? If not, then I'm not sure how it would be happening except by something outside Anaconda entirely. 

Other than that, are you performing any regular maintenance or utility tasks on the machine around when it occurs? Can you check your ``Start Menu Items`` directory to see if they are actually being removed from there, or just not shown on the start menu due to e.g. borked search indexing (that I've sometimes had happen on my Win 10 machine when I'm not using ClassicShell)?

There are ways to recover from that situation on Windows; I've done it a few times (once when something went wrong with a new Anaconda install and didn't install all the shortcuts, once when I logged in to a different user account that had Anaconda installed systemwide but none of the shortcuts, and once on a borked ``conda``/``Anaconda`` update), but it is usually easier and more foolproof to just do a full reinstall. Basically, in ``cmd``, you need to ``cd`` to your ``conda`` directory or just temporarily add it to your path, and then force conda to reinstall the packages with shortcuts, most importantly ``Anaconda prompt``. There's probably a few more tricks in there but that's the general gist of it.

Another possible permanent work around to this problem is installing in the opposite way (current user vs. all users) as you've done previously; one or the other sometimes has problems on various setups. Also make sure there's nothing weird going on (spaces, special chars, permissions, non-C:/ drive etc) with the paths you're installing it to.

**Comment by caca7566** [comment]
Thank you very  much for your reply. It is much appreciated. Let me adress your inputs below:
I'd immediately suspect any security/antimalware software you might have is blocking, quarantining or deleting it. 
I have actively made an exception for windows defender to allow pythonw.exe. I also have avast, have not been asked about pythonw.exe by that as I can recall

Are you doing anything at all with conda, updating Anaconda or individual packages, or Anaconda Navigator? 
No

Can you check your Start Menu Items directory to see if they are actually being removed from there,
I have checked, they are gone.

What I have done is tried you final suggestion, I installed for all users instead of just me as I did the last two times. Now I was asked by avast and windows defender and I granted exception for those. Right now it worked, lets see what happens.

**Comment by CAM-Gerlach** [comment]
BTW, you can use ``> `` to quote text, or the quote button, as I do below.

> I have actively made an exception for windows defender to allow pythonw.exe. I also have avast, have not been asked about pythonw.exe by that as I can recall

Its possible it could be doing it in the background, or could be due to another, less specific protection. Look through the interface for any logs or qaurentine information, and try launching Spyder again after disabling both programs just to check. Also, since they can interfere with one another as well as sap performance, its generally not a good idea to keep more than one active A/V product running simultaneously.

> No

I assumed so, but just wanted to rule that out.

> I have checked, they are gone.

Then something is actively removing them, and its certainly not Spyder (it doesn't even have the ability to, as as far I'm aware) and apparently not Anaconda either. That's what makes me suspect something else on your system, like an A/V.

> lets see what happens

Let us know, thanks. I strongly suspect it has to do with your A/V or something similar, since files don't just disappear of their own accord.

**Comment by CAM-Gerlach** [comment]
Any updates? If we don't hear from you, we won't be able to do anything on the Spyder side to fix this (in the unlikely event that is possible), so this will be closed in a few days if we don't. Hope you got it fixed! Thanks.

**Comment by caca7566** [comment]
Thanks for getting in touch. I reinstalled as admin instead of just me as user after that it worked fine, thanks for your support :)

**Comment by CAM-Gerlach** [comment]
Glad that got it working!
