### ISSUE TITLE
Scikit-Learn Decision Tree Error

### ISSUE THREAD

**Issue by AlbertAmI** [spyder-ide/spyder#6213]
## Description

**What steps will reproduce the problem?**

1. I am running the `DecisionTreeClassifier` of Scikit-Learn. When I look into the value of `children_left`, it reports the error.

**Please provide any additional information below**

  File "/Users/albert/anaconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 449, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "/Users/albert/anaconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/arrayeditor.py", line 619, in setup_and_check
    self.data.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array

## Version and main components

* Spyder Version: 3.2.6
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.4.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. Its possible that the recent changes to introspecting objects have fixed or ameliorated this error, so please update to Spyder 3.2.6 (with ``conda update spyder``) and see if it is resolved. If not, please provide a minimal reproducible example so we can investigate it on our end, and and additional details you may have that will help replicate and isolate the problem.

**Comment by AlbertAmI** [comment]
I have updated Spyder to 3.2.6. the bug still exists. I have sent the sample code and data to you. please kindly review. thanks.

**Comment by CAM-Gerlach** [comment]
> I have sent the sample code and data to you.

I haven't received anything by any means I'm aware of. Please post a minimal reproducible version here on this thread so we can all verify and isolate what you're referring to; thanks.

**Comment by AlbertAmI** [comment]
[
[horseColicTraining.txt](https://github.com/spyder-ide/spyder/files/1634683/horseColicTraining.txt)
[horseColicTest.txt](https://github.com/spyder-ide/spyder/files/1634687/horseColicTest.txt)
[loaddata.docx](https://github.com/spyder-ide/spyder/files/1634700/loaddata.docx)



](url)

**Comment by AlbertAmI** [comment]
[
import test2

from sklearn.externals.six.moves import zip
 
import matplotlib.pyplot as plt

from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

X_train,y_train = test2.loadDataSet('horseColicTraining.txt')
X_test,y_test = test2.loadDataSet('horseColicTest.txt')

bdt_real = AdaBoostClassifier(
    DecisionTreeClassifier(max_depth=2),
    n_estimators=40,
    learning_rate=1)
bdt_discrete = AdaBoostClassifier(
    DecisionTreeClassifier(max_depth=2),
    n_estimators=40,
    learning_rate=1.5,
    algorithm="SAMME")

bdt_real.fit(X_train, y_train)
bdt_discrete.fit(X_train, y_train)
real_test_errors = []
discrete_test_errors = []

for real_test_predict, discrete_train_predict in zip( bdt_real.staged_predict(X_test), bdt_discrete.staged_predict(X_test)):
    real_test_errors.append(
        1. - accuracy_score(real_test_predict, y_test))
    discrete_test_errors.append(
        1. - accuracy_score(discrete_train_predict, y_test))
n_trees_discrete = len(bdt_discrete)
n_trees_real = len(bdt_real)
# Boosting might terminate early, but the following arrays are always
# n_estimators long. We crop them to the actual number of trees here: 
real_estimators = bdt_real.estimators_
real_ns = bdt_real.n_classes_
discrete_estimator_errors = bdt_discrete.estimator_errors_[:n_trees_discrete] 
real_estimator_errors = bdt_real.estimator_errors_[:n_trees_real] 
discrete_estimator_weights = bdt_discrete.estimator_weights_[:n_trees_discrete]

plt.figure(figsize=(15, 5))
plt.subplot(131)
plt.plot(range(1, n_trees_discrete + 1),
         discrete_test_errors, c='black', label='SAMME')

plt.plot(range(1, n_trees_real + 1),
         real_test_errors, c='black',
         linestyle='dashed', label='SAMME.R')
plt.legend()
plt.ylim(0.18, 0.62)
plt.ylabel('Test Error')
plt.xlabel('Number of Trees')
plt.subplot(132)
plt.plot(range(1, n_trees_discrete + 1), discrete_estimator_errors,
         "b", label='SAMME', alpha=.5)
plt.plot(range(1, n_trees_real + 1), real_estimator_errors,
         "r", label='SAMME.R', alpha=.5)
plt.legend()
plt.ylabel('Error')
plt.xlabel('Number of Trees')
plt.ylim((.2,
         max(real_estimator_errors.max(),
             discrete_estimator_errors.max()) * 1.2))
plt.xlim((-20, len(bdt_discrete) + 20))
plt.subplot(133)
plt.plot(range(1, n_trees_discrete + 1), discrete_estimator_weights,
         "b", label='SAMME')
plt.legend()
plt.ylabel('Weight')
plt.xlabel('Number of Trees')
plt.ylim((0, discrete_estimator_weights.max() * 1.2))
plt.xlim((-20, n_trees_discrete + 20))
# prevent overlapping y-axis labels
plt.subplots_adjust(wspace=0.25)
plt.show()


](url)

**Comment by AlbertAmI** [comment]
sorry the code looks ugly. what I wanna do is to clarify the detail of the base-classifiers (especially how a sample is defined 1 or -1 under Decision Tree) in AdaBoost method. but when I look into the "bdt_real.estimators_" it isn't quite clear what is the base-classifier like and there is the reported bug. Could you please Kindly help me understand the decision tree result as a base-classifier and solve the bug? thank you so much.

**Comment by CAM-Gerlach** [comment]
> sorry the code looks ugly

That's because you wrapped it (and your three urls together) as a url, not as code (the button next to it, or triple backtick above and below). I've edited your post to fix it. Also, there is never any reason to save your code into a `docx` format MS Word document; if you can't save it as `.py` for some reason, at least just save it as `.txt`. Also, by the way, don't ever do ``import numpy as *`` (or any module) unless you have a very good reason and know what you are doing; the standard convention is ``import numpy as np`` or just ``import numpy``, and access it like that to keep your namespaces in order. 

Also, when people ask for a minimal example, that means to remove any code that isn't strictly necessary to reproduce the specific problem being discussed, which allows us to isolate exactly what is going on and run your code without jumping through several hoops, as I had to. This makes our job much easier, and makes it much more likely you'll get effective help and your problem solved.

> When I look into the value of `children_left`, it reports the error.

In any case, after spending 15 minutes scouring through every introspectable object your code produced, I wasn't able to find any ``children_left`` object anywhere, and didn't encounter this error anywhere else, and was therefore unable to reproduce the problem. At the very minimum, you'll need to tell me exactly where to find it.

> Kindly help me understand the decision tree result as a base-classifier

I'm sorry, but this is the bug tracker for the Spyder IDE, not Stack Overflow or the help forum for ``scikit-learn``; the latter might be more appropriate places to ask such a question. Particularly with being currently unfunded, we have very limited resources to help people even with their spyder-related problems as it is. 

> when I look into the "bdt_real.estimators_" it isn't quite clear what is the base-classifier like and there is the reported bug.

This is a quite different error entirely, and appears to be the result of an exception deliberately thrown by sklearn to prevent the user from mistakenly accessing an untrained estimator. I'm not sure how really to best handle it other than wrapping the appropriate block in a try catch, and passing/doing nothing if the error is found, but that seems a bit overkill for something so specific to a certain class in a certain package that is deliberately raised; the most we could probably do is catch the error and do nothing, since ``sklearn`` apparently won't let us introspect the object. @ccordoba12 , opinion?

**Comment by CAM-Gerlach** [comment]
For the record, here's the full traceback for the other ``bdt_real.estimates``; the identical error occurs for the private version (``_bdt...``) and the two in ``bdt_discrete.estimators``.

```
  File "C:\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 516, in createEditor
    readonly=readonly)
  File "C:\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 1327, in setup
    remote=remote)
  File "C:\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 1275, in __init__
    title)
  File "C:\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 1152, in __init__
    minmax=minmax)
  File "C:\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 110, in __init__
    self.set_data(data)
  File "C:\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 158, in set_data
    self.set_size_and_type()
  File "C:\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 178, in set_size_and_type
    for index in range(start, stop) ]
  File "C:\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 178, in <listcomp>
    for index in range(start, stop) ]
  File "C:\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 78, in __getitem__
    return getattr(self.__obj__, key)
  File "C:\Anaconda3\lib\site-packages\sklearn\tree\tree.py", line 506, in feature_importances_
    check_is_fitted(self, 'tree_')
  File "C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 768, in check_is_fitted
    raise NotFittedError(msg % {'name': type(estimator).__name__})
sklearn.exceptions.NotFittedError: This DecisionTreeClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.
```

**Comment by CAM-Gerlach** [comment]
Funny enough, I actually managed to reproduce this. The culprit appears to be masked arrays; when I attempt to view them in the Variable Explorer, I get the above error, in the latest Spyder 3.3.2. I can investigate further in a few days when I'm not under a tight deadline.

```
  File "C:\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 482, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "C:\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\arrayeditor.py", line 620, in setup_and_check
    self.data.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array
```

**Comment by ccordoba12** [comment]
It should be an easy fix, right @CAM-Gerlach? I mean, we just need to catch the exception and pass, right?

**Comment by CAM-Gerlach** [comment]
It would seem so, perhaps with a popup warning dialog ("Masked arrays not supported yet") unless and until we want to add support for masked arrays. 

As a more general idea though, we could consider falling back to the standard arbitrary object ``dict`` view if we can in these sorts of cases. It might not be ideal, but its better than nothing...

**Comment by ccordoba12** [comment]
Masked arrays are supported. We simply need to skip trying to change the wrriteable flag array.

**Comment by CAM-Gerlach** [comment]
> Masked arrays are supported.

D'oh, I should know since I've tested them in the past. I guess that's what I get for not sleeping for way too long to go all out on my final project. For the record, I specifically reproduced this on a 1-element masked array, an element in a Pandas DataFrame, output from ``np.nanmean()`` when running on an array of all masked values.

> We simply need to skip trying to change the wrriteable flag array.

Or just take the Pythonic BTAFTP and catch and pass the specific error?

**Comment by ccordoba12** [comment]
Let's close this one in favor of #8582, which I've been referencing more lately.
