### ISSUE TITLE
 NameError: name 'runfile' is not defined

### ISSUE THREAD

**Issue by fahmanali** [spyder-ide/spyder#6214]
## Description

 NameError: name 'runfile' is not defined

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.5.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.0 (OK)
pandas >=0.13.1  :  0.21.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  None (NOK)

```

**Comment by CAM-Gerlach** [comment]
This is almost certainly a user-install issue. To fix, uninstall whatever you have currently and do a clean install of the latest version of Anaconda; due to limited resources we can't provide individual support for installing other distributions or with ``pip``. If that doesn't do the trick, following the advice in our [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which almost certainly will. Due to that and the total lack of any actionable information included with the report, this issue will be summarily closed. However, here is some more specific information from a previous duplicate issue:

If you search for it, this error has been reported many times before from different causes (perhaps the most prolific being #3428 ); apparently some cases are bugs in Spyder and others are due to something going wrong during installation or something else gone wrong on the user side of things. If you have not already, you could read through those threads carefully and make sure none of those user-side fixes resolve your issue.

Other than that, you could try reinstalling a clean copy of anaconda, or at least installing Spyder in a clean conda-env, and seeing if the error persists. If so, and a more specific fix is not readily offered and a non-user cause is not ruled out, it would be important to know exactly what changed in your environment between when Spyder worked and when it didn't (OS, Python, Spyder, package updates, configuration, etc.), as that would be the main way to narrow down the problem.
