### ISSUE TITLE
Crash when I copy output from console while waiting for user input

### ISSUE THREAD

**Issue by joneML** [spyder-ide/spyder#6216]
## Description of your problem
I run a for-loop to check each case in a list, say.
In each iteration, i insert an input statement, mainly to give me a pause control.
Then when i copy output from the console, the for-loop / input statement will not work.

**What steps will reproduce the problem?**
*Python code below:   Sorry about the indent.. github takes it away..

```python
l=['aaaaa', 'bbbbb', 'cccccc']
for val in l:
    print(val)
    ans = input('enter z to terminate..')
    if ans == 'z':
        break
```

**What is the expected output? What do you see instead?**
*if i run it, it prints the following in the first iteration:
aaaaa

enter z to terminate..
*at this moment, I copy the output "aaaaa" from the console to somewhere
*then i cannot continue to press ENTER or enter z & ENTER to exit the for-loop. It just froze there.
*i have to restart kernel ...

**Please provide any additional information below**
The Red Stop button doesn't help either.

## Versions and main components
* Spyder Version: 3.1.4
* Python Version:  3.6.1.final.0
* Qt Version: 5.6.2
* PyQt Version: 329216
* Operating system: win10-64

## Dependencies
I don't think it matters.  i didn't install much either. mainly use anaconda "built-in" packages

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this in a future release.

**Comment by CAM-Gerlach** [comment]
If you press <kbd>Ctrl</kbd> + <kbd>c</kbd> in the Console, it terminates the process, which causes the problem. However, it shouldn't hang and force a full kernal restart. Also, normally kbd>Ctrl</kbd> + kbd>Shift</kbd> + <kbd>c</kbd> copies just fine, but it appears to cauase the problem too here. However, either copy option from the context menu works without a problem. 

In any case, this is a known issue I've seen previously in situations like this. However, I've replicated all of the above behaviors in ``qtconsole``, as expected. Therefore, the bug should presumably be reported to that repo, not here, as it would lie in that codebase. Accordingly, I'm closing this unless @ccordoba12  things otherwise or can move it over there.

**Comment by CAM-Gerlach** [comment]
Also, Spyder 3.1.4 is very old, so you really should update with ``conda update spyder`` (or ``pip``, if you use that, though ``Anaconda`` is recommended to avoid problems we aren't able to help you with).
