### ISSUE TITLE
Spyder crashing

### ISSUE THREAD

**Issue by tomL89** [spyder-ide/spyder#6236]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1290, in close_client
    self.create_new_client()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1009, in create_new_client
    self.connect_client_to_kernel(client)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1035, in connect_client_to_kernel
    stderr_file)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1440, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 238, in start_kernel
    self.write_connection_file()
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 431, in write_connection_file
    kernel_name=self.kernel_name
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 100, in write_connection_file
    sock.bind((ip, 0))
OSError: [WinError 10055] An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full
WARNING:traitlets:kernel died: 18.00380039215088

## Version and main

**Comment by CAM-Gerlach** [comment]
I'm assuming this was some sort of user or platform-specific issue unrelated to Spyder's code?

**Comment by tomL89** [comment]
Hi,

Spyder did crash for unknown reason, and suggested to share the error on
GitHub. However, I was expecting this to be some kind of automatic
reporting, but it looked like an actual thread, as if I was facing an issue
and asking for help, which I was not: that is why I deleted the thread.

Thanks,
Thomas

**Comment by CAM-Gerlach** [comment]
> However, I was expecting this to be some kind of automatic reporting, but it looked like an actual thread, as if I was facing an issue and asking for help

Sorry for the confusion. We're actually working on making that clearer right now in e.g. #5346 , #6207 and #6154 , which should be part of the next release (3.2.7) due out by around the end of this month.

 In short, it has some attributes of both, and the great majority of new reporters assume its one or the other (either submitting a "drive-by" report with just a traceback and never following up with more information about how the error occurred, or using it as a help forum for their user-side individual installation issues), but it is actually neither. Rather, it is a place for users to file bugs they find in Spyder's code in a semi-automated manner, with a (often automatically provided) traceback along with a detailed (as practicable) manual description of how the error occurred, so we can reproduce it ourselves, follow up as necessary, and fix it for everyone in the future.

Therefore, assuming this bug didn't appear to be due to your own code, a third party package you were using, or something specific to your machine/install, if you can provide more information about what you were doing when it occurred (specific helpful items to include are listed in the [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Spyder Troubleshooting Guide, along with more detail about the process) then please reply with a comment to that effect re-opening the issue, and we'll do our best to fix it in a future release if we can. Thanks!
