### ISSUE TITLE
Spyder won't start on OS X with error line 3126 in main

### ISSUE THREAD

**Issue by asabbah** [spyder-ide/spyder#6242]
Spyder doesn't start, giving the following error:
2018-01-18 14:33:29.603 python[14568:511622] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
Traceback (most recent call last):
  File "/Users/asabbah/anaconda/envs/carnd-term1/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 3126, in main
    mainwindow = run_spyder(app, options, args)

This is the yml file used for creating the environment:
```
name: carnd-term1
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.2
    - numpy
    - matplotlib
    - jupyter
    - opencv3
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn
    - pandas
    - ffmpeg
    - imageio=2.1.2
    - pyqt=4.11.4
    - pip:
        - moviepy
        - tensorflow==0.12.1
        - keras==1.2.1
```

## Versions

* Spyder Version: 3.2.6
* Python Version: 3.5.2
* Qt Version: 4.8.7
* PyQt Version: 4.11.4
* Operating system: OSX Sierra 10.12.6

**Comment by CAM-Gerlach** [comment]
Thanks for reporting; this looks like an installation or package conflict issue of some sort, and so its rather limited what we can do from here, particularly without more information from you. 

Therefore, can you try updating to more recent versions of packages where supported (particularly PyQt4, which hasn't been updated in several years, and Python 3.5.4 at least if not 3.6.4), and see if that fixes it? Also, please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

If none of that helps, to narrow down the problem, could you try opening and running some code in ``qtconsole``, ``python`` and ``IPython`` from that same environment, and see if they work fine? If they do, start spyder from a clean environment with just it and its deps installed to make sure that works, then you can try to narrow it down to the specific package causing the problem by ``remove``ing them one by one along with unneeded deps, and seeing when it starts working. Also, you can run Spyder with the debug flag, i.e. ``spyder --debug`` or running ``SPYDER_DEBUG=3`` then ``spyder`` from a Terminal prompt, in order to see more detailed information that might help isolate what's going on.

**Comment by asabbah** [comment]
Thank you for that. 

Upgrading PyQt didn't help, but upgrading Python did, and now Spyder works. 

Just two comments re the environment without these upgrades. before closing this matter. Idle3 was able to launch under this same environment, and Spyder worked under Ubuntu. It seems related to OSX in the case of Spyder.

**Comment by CAM-Gerlach** [comment]
Interesting, thanks, and glad you got it fixed. As it was solved by upgrading from a Python version that is over a year and a half out of date, it very unlikely to be something Spyder has any control over.
