### ISSUE TITLE
Spyder 3.2.6 [crashes/won't launch] after conda install into a fresh Python 2.7 environment

### ISSUE THREAD

**Issue by Gabrielvon** [spyder-ide/spyder#6246]
Hi everyone,

## Description of your problem
Thanks for looking into it.
The following error notification pop up when I launch spyder 3.2.6.

![image](https://user-images.githubusercontent.com/8952869/35135806-7f6cd89e-fd1a-11e7-8957-d61711afe784.png)

I did some search on Internet and tried the following stuffs and still cannot solve the problem.
'spyder --reset' and then do `spyder`, this seems loading stuffs without showing anything. However, a new pythonw.exe runs at the background though I don't where it is. 

 `spyder --show-console` shows same situation above.

delete the .spyder/spyder.lock folder 
delete the .spyder2 folder 
both shows same error notification.

**What steps will reproduce the problem?**
Initially, I got the error notification above. 
install spyder in a brand-new virtual environment of python2.7 created via conda 

## Versions and main components

* Spyder Version: 3.2.6
* Python Version: python 2.7.114
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: windows 7, 64bits

**Comment by CAM-Gerlach** [comment]
Thanks for following up (apparently?), but this needs to be posted as a reply comment to whichever of your report(s) it applies to; little to nothing is stated about the circumstances of the problem such that I can't tell which one, which is along with other reasons is exactly why everything needs to be kept under one issue as it should be—perhaps #6245 ?

**Comment by Gabrielvon** [comment]
@CAM-Gerlach I think they are not the same issues from my perspective. One leads to the problem of keyboard shortcut modification, the other stop me opening the spyder from the beginning. However, I don't know if they can be solved by doing same thing from developer's end.

**Comment by CAM-Gerlach** [comment]
Thanks for following up, and for trying several techniques and search your issue before posting here. I'm sorry, I guess I must have misinterpreted your post. Since you never actually directed stated in the body of it _what_ your actual problem was, particularly not near the top where one generally does so, and the title started with

> Still cannot solve

and your first line was

> Thanks for looking into it.

coupled with the fact that you had just posted at least one other issue, hopefully you can see how this looked like a followup post to some other topic, not a self-contained bug report. Unfortunately, a number of users lately have been clogging up the system by doing the former and this one appeared to fit the pattern, but I'm sorry I jumped to conclusions so quickly before asking you to clarify. We just have very limited time and resources right now, being unfunded, and the constant barrage of duplicate issues we have to deal with saps a significant portion of what we do have.

To help avoid this in the future and ensure you get the best help possible, *please* make sure your title and the first few lines/paragraph(s) contains a detailed description of what the actual issue is, rather than a line or two referring to such buried at the very end. Furthermore, a title like 

> Still cannot solve spyder crash on python2.7 after a few attempts.

would make sense I suppose for a help forum, but isn't very helpful for a bug tracker; instead, something like

> Spyder 3.2.6 [crashes/won't launch] after conda install  into a fresh Python 2.7 environment

is much more appropriate and descriptive.

Anyway, that aside, my main recommendation to you is to diligently follow all the steps/procedures described in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

If it still isn't working, please post any additional information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) as a comment on this thread, and we'll see what we can do.

> spyder --show-console shows same situation above.

This doesn't do anything; it is already enabled by default and is thus deprecated. ``spyder --debug`` is what you want.

> delete the .spyder/spyder.lock folder
delete the .spyder2 folder

``spyder --reset`` should already take care of the needed portion of this for you; hopefully this didn't mess anything up.

> Initially, I got the error notification above.

As the (I'd assume localized) text states, this just means Spyder crashed last time you were using it, not that anything's necessarily wrong this session. The next version of Spyder will include an enhanced version of that dialog, with clearer and more detailed descriptive text, and links to more help resources including the troubleshooting guide. Hopefully that should solve any confusion there.

Anyway, if you've made it to the end of this mega-post, congrats. Your kitty (profile photo) is very cute, by the way...looks a lot like my precious cat.

**Comment by Gabrielvon** [comment]
@CAM-Gerlach Hey, I did read all of the mega-post ;) . Sorry about the confused description. I found a lot of similar questions during my search so I thought your team may be familiar with this issue but now I knew I was wrong. My apologies. 

Since I am not familiar with development, my way try every possible solutions online even though I don't 100% understand the codes. I posted what I did for further explaining my situation in case you put forward similar solution. 

I double checked my issues following your guidance as below and the error still occurs.
> Anyway, that aside, my main recommendation to you is to diligently follow all the steps/procedures described in the Spyder Troubleshooting Guide, specifically the Basic First Aid and Emergency CPR sections, which resolve the great majority of Spyder installation issues.

> `spyder --show-console` shows same situation above.
> This doesn't do anything; it is already enabled by default and is thus deprecated. spyder --debug is what you want.

spyder --debug make no response to me, which prints nothing on python2.7. Further, I also tried in python3.6 environment, it shows 'spyder: error: no such option: -d'.

Last, thanks for noticing the kitty on my profile photo. Actually it is a picture from instagram, which is super cute. I believe so your cat is.

**Comment by CAM-Gerlach** [comment]
> Hey, I did read all of the mega-post ;)

I'm not sure if a non-native English speaker will get this joke, but here you go: 🍪  :D

But in all seriousness, thanks for doing so and getting back to us so quickly.

> I found a lot of similar questions during my search so I thought your team may be familiar with this issue but now I knew I was wrong. My apologies.

Well, this is just a generic non-startup/crash as far as we are able to tell with the limited level of detail provided, though even that wasn't obvious from the original post since it wasn't ever really directly stated what exactly the issue was nor anything particularly descriptive about it that would identify it in particular. Probably close to 50% of the up to several dozen issue reports per day we get are of this nature, and at least ~90% of those are user-side/install issues we have no control over.

Never forget the Zen of Python: ``Explicit is better than implicit.``

> I double checked my issues following your guidance as below and the error still occurs.

So you tried all ~15 troubleshooting procedures specified under ``Recommended troubleshooting steps`` and ``Common solutions``? Did you then try the ``Standard approach to isolating problems`` to see if all of the other stated applications (``qtconsole``, ``IPython``, ``python``) work? Did you then proceed to the ``Advanced tricks`` section to try starting Spyder via alternative means and debug mode enabled and reporting the results? Do you have any Spyder plugins installed, like ``Spyder-terminal``, or any ``pip``-installed or otherwise nonstandard packages in the environment?

Once/if you've done all that in full and still not gotten results (as again, user install issues like this are usually 90%+ out of our control), then please provide the rest of the information listed under the [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include), including a detailed description of exactly what you are observing when it starts and under exactly what conditions (Python 2, Python 3, different Anaconda versions, different means of starting, etc) it works and it doesn't and what exactly does happen in each scenario, any relevant results from troubleshooting procedures other than those that produced no effect, output from ``conda list`` in the relevant environment, how you installed Spyder (distribution/source and version thereof), whether you've got Spyder working before and if so, what precisely changed, and anything else you can think of that might relate to the problem or unusual about your environment.

> spyder --debug make no response to me, which prints nothing on python2.7. Further, I also tried in python3.6 environment, it shows 'spyder: error: no such option: -d'.

For reasons I'm not fully aware of, this sometimes doesn't work. Instead, ``set`` the ``SPYDER_DEBUG`` enviroment variable to ``3`` in the same Anaconda prompt you use to launch Sypder (e.g. ``set SPYDER_DEBUG=3``) and then launch Spyder after with ``spyder``.

> Last, thanks for noticing the kitty on my profile photo. Actually it is a picture from instagram, which is super cute. I believe so your cat is.

Here he is, to lighten the mood since I'm sure you must be frustrated:

![2017-07-17_yang-cat-porch-traits_01](https://user-images.githubusercontent.com/17051931/35181881-1fc3b874-fd90-11e7-8009-b3338a4d9539.jpg)

> Gabrielvon changed the title from Still cannot solve spyder crash on python2.7 after a few attempts. to Spyder 3.2.6 [crashes/won't launch] after conda install into a fresh Python 2.7 environment

By the brackets around ``[crashes/won't launch]`` I meant to imply you should use the most accurate term that describes your situation; I'm still not exactly clear on what does and doesn't happen since I think you assume my powers of telepathy and prescience are even more powerful than they really are :D since I still haven't seen a 100% explicit description of what exactly occurs nor any error messages or tracebacks, etc.

**Comment by Gabrielvon** [comment]
Hey, thanks in advanced. 

I tried all things you mentioned here. All relative applications stated (qtconsole, IPython, python)  work just fine. For this fresh python 2.7 environment, I haven't install any plugins or packages yet.
> So you tried all ~15 troubleshooting procedures specified under Recommended troubleshooting steps and Common solutions? Did you then try the Standard approach to isolating problems to see if all of the other stated applications (qtconsole, IPython, python) work? Did you then proceed to the Advanced tricks section to try starting Spyder via alternative means and debug mode enabled and reporting the results? Do you have any Spyder plugins installed, like Spyder-terminal, or any pip-installed or otherwise nonstandard packages in the environment?

Honestly, I don't what else should I provide with except for those mentioned in the format of new issue post, since I can even open the spyder. Recalling the procedure, I ran `spyder` on windows command line and the error notification as the screenshot occurs. 
**Versions and main components**
Spyder Version: 3.2.6
Python Version: python 2.7.114
Qt Version: 5.6.2
PyQt Version: 5.6.0
Operating system: windows 7, 64bits

In fact, your term is precise and accurate for now because I don't what else information should be added, so advice accepted. Thanks.

What a cool cat he is! Looks like he think this issue is easy for him ;D . Let me know what other information should I provide with.

**Comment by CAM-Gerlach** [comment]
Thanks again for your response. BTW, as a general note I've been a little confused about what you're referring to when you're quoting stuff—are you quoting the thing you're talking about *underneath* where you talk about it? If so, that would explain a lot of the confusion...FYI, at least in English the general convention is to quote whatever it is *above* where you talk about it, so then its clear what you are referring to.

> I tried all things you mentioned here.

Do you mean all the things *here* as in in this thread, or *here* as in the guide you quote below? I'm still not clear on whether you've read the latter. Again...explicit is better than implicit and all that. Also, if/once you have done that, please proceed to 

> the [Advanced tricks](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#advanced-tricks) section to try starting Spyder via alternative means and debug mode enabled and report the results

Again, debug mode can be enabled as stated previously by executing ``set SPYDER_DEBUG=3`` before running Spyder from the Anaconda Prompt. Please do so and report your results as I've requested.

> All relative applications stated (qtconsole, IPython, python) work just fine. For this fresh python 2.7 environment, I haven't install any plugins or packages yet.

Good to know; this isolates it considerably.

> Honestly, I don't what else should I provide with except for those mentioned in the format of new issue post, since I can even open the spyder.

As I state in the post above, here is what you should provide, all of which can obtained without being able to successfully launch Spyder;

> Once/if you've done all that in full and still not gotten results (as again, user install issues like this are usually 90%+ out of our control), then please provide the rest of the information listed under the [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include), including a detailed description of exactly what you are observing when it starts and under exactly what conditions (Python 2, Python 3, different Anaconda versions, different means of starting, etc) it works and it doesn't and what exactly does happen in each scenario, any relevant results from troubleshooting procedures other than those that produced no effect, output from ``conda list`` in the relevant environment, how you installed Spyder (distribution/source and version thereof), whether you've got Spyder working before and if so, what precisely changed, and anything else you can think of that might relate to the problem or unusual about your environment.

Please do so; thanks.

> Recalling the procedure, I ran spyder on windows command line and the error notification as the screenshot occurs.

Again, run ``set SPYDER_DEBUG=3`` first to hopefully get some useful output. Also, if you read it carefully the message in the screenshot is *not* an error dialog and provides no meaningful information about any error; it is only there to inform you that Spyder detected a crash last time it was started, and advise you of some basic troubleshooting steps should it happen again; therefore, you haven't actually provided anything indicating what error occurred if any, and was also part of why I thought your post was a duplicate since it didn't contain an actual error message. Again, I have revised it for clarity in the next release.

> In fact, your term is precise and accurate for now because I don't what else information should be added, so advice accepted.

I'm not sure what you're referring to, nor exactly what you're trying to say about it—do you mean the title? If Spyder **won't start** (which I **think** is the case here from what you've told me) then you want to put that there; otherwise, if it starts and load up, you can use it, and then it crashes, then the latter is a more appropriate term.

> Let me know what other information should I provide with.

I have; please refer to this post, the previous post it references, and the linked guide.

Again, please carefully read this post, follow the steps it states or refers to, and then explicitly state exactly which you have followed and what the exact results were for each. Otherwise, I'm not sure how much more I will be able to help you other than repeating the same instructions I have for the last few posts now. Thanks.

**Comment by Gabrielvon** [comment]
Yes, normally I refer those quoted above my word but last post was an exception. Sorry about the confusion. I edited my last post already. 

I've tried all the things in the thread except for the[ Advanced tricks ](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#advanced-tricks). And got no any other special warning, error or notifications happen. However, with trying **Advanced tricks**, I did get something. Please see screenshots below.
![7ji t_pm_k55tfsrat80yde](https://user-images.githubusercontent.com/8952869/35201904-ecec58ae-ff59-11e7-9ad5-37a1149fca90.png)
![9 00 a_ g 6ok3 iwcw2rj6](https://user-images.githubusercontent.com/8952869/35201905-ed16aea6-ff59-11e7-9af1-c29bb0aed0c8.png)
![z6zzfx6enc 4fuxo8_ af0](https://user-images.githubusercontent.com/8952869/35201907-efbd9214-ff59-11e7-95e6-88600299bf98.png)
![y997p2bwl gr_5 l8a n43s](https://user-images.githubusercontent.com/8952869/35201910-f1ecae30-ff59-11e7-9104-71e9422db4bd.png)
Both of running start.py and mainwindow.py gave me same traceback. The traceback occurs after I press the OK button in the 'Spyder crashed during last session' pop-up window.

As for `spyder --debug`, it shows nothing. Please see the screenshot below.
![qpo roeemznjem0 0 8vg](https://user-images.githubusercontent.com/8952869/35202023-d4732e46-ff5a-11e7-9340-d946ff8645f3.png)

**Comment by ccordoba12** [comment]
So you have `spyder-autopep8` installed, right? Why didn't you say that from the beginning? You'd have saved @CAM-Gerlach a lot of time.

**Comment by Gabrielvon** [comment]
My apologies. You are right. I simply copy-pasted the spyder_autopep8 folder under the plugin folder and didn't consider that as an installation so I did not keep it in mind. Also, at the first time I  thought `spyder --reset`  reset everything including the plugins. I am sorry about my negligence. Anyway, I did solve it by removing the spyder-autopep8 and reinstalling it again. Thanks and sorry for your times.

**Comment by CAM-Gerlach** [comment]
Solution: Uninstall ``spyder-autopep8``. As @ccordoba12  states in #5967 it is not possible (to our knowledge) to receive that error without a plugin installed, as no object called ``DummyDock`` exists anywhere in our codebase.

I don't want to prolong this any further, but to explain why we're a little frustrated, in my second post I specifically asked 

> Do you have any Spyder plugins installed, like ``Spyder-terminal``, or any ``pip``-installed or otherwise nonstandard packages in the environment?

and you replied with

> For this fresh python 2.7 environment, I haven't install any plugins or packages yet.

Furthermore, I asked three times for the information requested under the "Things to include" section in that guide (which included ``conda list`` output), and explicitly asked for ``conda list`` output twice, to still no avail, both before and after you asked 

> Honestly, I don't what else should I provide with except for those mentioned in the format of new issue post like above

which would have revealed this, particularly since we'd already isolated the issue to an otherwise "clean" environment.

Finally, ``spyder-autopep8`` was directly mentioned as a potential source of issues, with uninstalling it being the solution, under "Plugin Problems" in the troubleshooting guide I repeatedly requested you read for the past three consecutive posts.
