### ISSUE TITLE
I can't launch spyder  from anaconda-navigator environment

### ISSUE THREAD

**Issue by flwheeler2** [spyder-ide/spyder#6272]
## Description of your problem

I upgraded many python packages using the Anaconda-Navigator Environment , 
which broke  spyder ( and also jupyterlab, which I don't use ) 
the GitHub python people suggested I roll back to a good version, but the command  apparently removed a lot of files it wasn't supposed too.  :-(.  finally, I have used "conda install" to get about 50 removed files back and Anaconda-Navigator will launch , but spyder will not!! I've done the spyder -- reset  several times.  

**What steps will reproduce the problem?**

1. more history on Anaconda GitHub, issue # 7855 .  
2. 
3. 

**What is the expected output? What do you see instead?**
I only get the crash reports traceback ( from the Terminal window ) and the jpg above.  

![spyder launch error screen 21jan2018](https://user-images.githubusercontent.com/34629423/35253150-e3b72fe0-ffb1-11e7-99ef-2b3527fa8f5b.jpg)

CAM-Gerlach Edit: Pasted your traceback inline

fredericks-MBP:~ bravo$ spyder
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3126, in main
    mainwindow = run_spyder(app, options, args)
  File "/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3023, in run_spyder
    main.setup()
  File "/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 825, in setup
    from spyder.plugins.console import Console
  File "/anaconda3/lib/python3.6/site-packages/spyder/plugins/console.py", line 35, in <module>
    from spyder.widgets.internalshell import InternalShell
  File "/anaconda3/lib/python3.6/site-packages/spyder/widgets/internalshell.py", line 27, in <module>
    from spyder.interpreter import Interpreter
  File "/anaconda3/lib/python3.6/site-packages/spyder/interpreter.py", line 14, in <module>
    import ctypes
  File "/anaconda3/lib/python3.6/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so, 2): Symbol not found: __PyUnicode_AsWideCharString
  Referenced from: /anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so
  Expected in: flat namespace
 in /anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so

**Please provide any additional information below**
[conda info.txt](https://github.com/spyder-ide/spyder/files/1654147/conda.info.txt)

[conda list.txt](https://github.com/spyder-ide/spyder/files/1654149/conda.list.txt)

## Versions and main components

* Spyder Version: 3.2.6
* Python Version:  3.6.4 
* Qt Version:
* PyQt Version:
Anaconda-Navigator :   1.6.12
* Operating system: Mac OS 10.13.2.  

==========

I'm trying to begin a new online Udemy course on Neural Networks, and I have to have Python to begin. 
I'm pretty new to all this.  But my system has been broken since Dec 19, so I'm not feeling optimistic about  this .  

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by CAM-Gerlach** [comment]
Thanks for reporting, and sorry you've been having this issues for so long—it must be very frustrating I'm sure. Unfortunately, as you state, ``jupyterlab`` is not working, and the issue stemmed from a botched Anaconda/conda install, then Spyder has little or no control over that. 

We can only recommend you do a complete uninstall of any Anaconda installed on your machine, and clean reinstall using the latest Anaconda3 5.0.1 package downloaded from the web, then update Spyder (and only Spyder) with ``conda update spyder`` from the Anaconda prompt, and launch it via an alias (if possible on macOS) or the Terminal as opposed to Anaconda Navigator, if that is where you are running into trouble. Furthermore, we aren't able to support install problems caused by using ``pip`` instead of the ``conda`` installer, if that has anything to do with your problem. Finally, while this doesn't appear to be it, there are known issues with Qt/PyQt not fully supporting macOS 10.13 High Sierra which are also out of our control.

Also, if that still doesn't do it, you can try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues. Best of luck!

**Comment by flwheeler2** [comment]
thank you for all your good advice.  I'll probably do a clean install.  I'm trying to decide whether to replace my SSD drive first, as it's almost full.

**Comment by flwheeler2** [comment]
oh.  if I can launch spyder from a terminal window, why do I even need Anaconda?  I guess to get spyder and python in the first place ?

**Comment by ccordoba12** [comment]
> import ctypes
File "/anaconda3/lib/python3.6/ctypes/init.py", line 7, in
from _ctypes import Union, Structure, Array
ImportError: dlopen(/anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so, 2): Symbol not found: __PyUnicode_AsWideCharString
Referenced from: /anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so
Expected in: flat namespace
in /anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so

@mingwandroid, have you seen this error before?

**Comment by CAM-Gerlach** [comment]
> oh. if I can launch spyder from a terminal window, why do I even need Anaconda? I guess to get spyder and python in the first place ?

Technically, you don't _need_ it to install and run Spyder, but you really do _want_ it unless you're an expert (or a masochist). You can install everything with ``pip`` and a standard Python distribution, but there are numerous caveats, pitfalls and other things that can go wrong that can be frustratingly difficult for even experienced users to figure out, and once set up its easy to break your installation with one wrong ``pip`` install or command, and have to start over. We usually get multiple issue reports per day that ultimately stem from messed up ``pip`` installs, which is why we officially recommend Anaconda as we don't have the resources to provide individual support for the many intricacies of users' specific ``pip`` installs. 

Anaconda automatically installs an integrated environment with numerous dependencies that Spyder needs to function, many of which rely on binaries or code compiled in other languages (C, C++, Fortran, Qt) that can play havoc with ``pip`` installs, and gets your system all set up to be used either from the command line, a GUI, or the Navigator (if it weren't for Anaconda, you'd likely have to muck around with executables and your path manually to get it to launch from the Terminal that easily). Furthermore, for data analysis and scientific work, conda makes things much easier when it comes to updating your installation, working with environments, and installing additional packages, and even allows ``pip`` to work seamlessly with ``conda`` packages and environments, while the converse with ``virtualenv`` and a native ``pip`` install is not possible. Simply put, without Anaconda, Spyder wouldn't function, at least not without a huge amount of work.

That said, if you're looking for something lighter on your SSD, you could consider Miniconda instead, a version of Anaconda that comes with just ``python``, ``conda`` and the bare-bones environment you need to install ``spyder`` and any other packages you need, potentially saving a lot of disk space over the "full-fat" version.

**Comment by flwheeler2** [comment]
great info. I'm a beginner so  I'm definitely using Anaconda.   :-). thank you for your time

**Comment by CAM-Gerlach** [comment]
@flwheeler2 Was this solved by the reinstall? If so or we don't hear from you after a few more days, this issue will be closed. Thanks!

**Comment by flwheeler2** [comment]
I am doing a complete remove and install of anaconda.  Hopefully  the second time around to install the  data programs like XGBoost, TensorFlow,  Brew, and others will be easier if I have kept good notes.  my key learning is that I'm NOT using the Anaconda --> Environment page to update individual packages.  
I really appreciate your time and information.   I have  saved your anaconda info from above.

**Comment by debasistripathy1** [comment]
Traceback (most recent call last):
File "/Users/dev/opt/anaconda3/bin/spyder", line 7, in 
from spyder.app.start import main
File "/Users/dev/opt/anaconda3/lib/python3.7/site-packages/spyder/app/start.py", line 33, in 
from spyder.config.base import (get_conf_path, running_in_mac_app,
File "/Users/dev/opt/anaconda3/lib/python3.7/site-packages/spyder/config/base.py", line 30, in 
from spyder.utils import encoding
File "/Users/dev/opt/anaconda3/lib/python3.7/site-packages/spyder/utils/encoding.py", line 24, in 
from atomicwrites import atomic_write
ModuleNotFoundError: No module named 'atomicwrites'

I am. having this

**Comment by CAM-Gerlach** [comment]
@debasistripathy1 That traceback is completely different from that originally reported here, sorry. In any case, the error is fairly clear if you are familiar with Python—Spyder can't find the `atomicwrites` module it requires installed. You can try installing it by running `conda install atomicwrites` in your `base` environment on the command line (you may need to type `conda activate base` first). However, this may be a symptom of a broken Anaconda installation since `atomicwrites` should be installed by default with Anaconda. If you still get problems, try creating a fresh Spyder environment with `conda create -n spyder-env spyder=4 python=3.7` then activating it with `conda activate spyder-env` and finally running Spyder from it with `spyder` (or doing the last two steps with Anaconda navigator, if you prefer).

**Comment by debasistripathy1** [comment]
**conda activate base gives this result**
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.



Note: you may need to restart the kernel to use updated packages.
-------------------------------------------------------------------------
**conda install atomicwirtes gives this result**

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - atomicwirtes

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.



Note: you may need to restart the kernel to use updated packages.
-------------------------------------------------------------------------------------
and when I installed  **conda create -n spyder-env spyder=4 python=3.7**
it failed.

**Comment by jitseniesen** [comment]
> conda install atomicwirtes gives this result [...]

@debasistripathy1 Take care of the spelling: it is atomicwrites, not atomicwirtes.
