### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by RuikunLi** [spyder-ide/spyder#6277]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Application\lib\site-packages\spyder\plugins\ipythonconsole.py", line 912, in set_working_directory
    refresh_console=False)
  File "C:\Application\lib\site-packages\spyder\plugins\workingdirectory.py", line 286, in chdir
    os.chdir(directory)
WindowsError: [Error 123] : u'C:\\Users\\lgd\\OneDrive - Universit?t Duisburg-Essen\\Master_\u8bfe\u4ef6\\FoDS\\Exercise'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.1 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.26.1 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.2 (OK)

```

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. A fairly safe guess is that it has to do with non-ASCII characters in the file path (as you can see by the question marks) and Python 2's lack of proper Unicode support for them. We will likely need to know more about the circumstances of this error in order to fix it, but ultimately, the safest solution is simply to avoid non-ASCII paths with Python 2, or upgrade to Python 3 which has native Unicode support.

There is a chance we might be able to work around this on Spyder's side, but you'll need to describe in detail what you were doing when the error occurred, and post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Calling for Help section as a comment to this issue, and we'll try to help if we can. Otherwise, your issue will have to be closed after one week (7 days), since we likely won't be able to fix it without that information, and to some extent it is an intrinsic limitation of Python 2. Thanks, and best of luck!

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response.
