### ISSUE TITLE
Add ability to refresh/update existing Variable Explorer windows to reflect current variable state

### ISSUE THREAD

**Issue by Murmele** [spyder-ide/spyder#6325]
Hello,
when you click on a variable in the variable explorer you get a new window from the variable and it's content (see pic1.png). At the moment these small windows will not be updated when the variable changes. In some cases it is really usefull to compare values, but sometimes it would be nice when the windows will be updated. For this i propose if there is a checkbox which is by default unchecked, but when you check the checkbox, the content of the window will be updated.
Is something like that possible to make?

![pic1](https://user-images.githubusercontent.com/10099533/35510602-08eb5790-04f9-11e8-9c22-036374519d6b.png)

![pic2](https://user-images.githubusercontent.com/10099533/35510848-10044e28-04fa-11e8-8cd9-8dc77068f4a8.png)

**Comment by ccordoba12** [comment]
Thanks for the suggestion. We'll try to implement this in a future release.

**Comment by Murmele** [comment]
Thank you!

**Comment by CAM-Gerlach** [comment]
Agreed, this would definitely be a very useful feature and something I've thought about as well, though would take at least some backend work to implement. Also, from a UI perspective, It would probably be easiest and most straightforward to stick the button bottom left.

**Comment by Heuristicmystic** [comment]
Absolutely loved this in the old Linux build I used

**Comment by rpinto73** [comment]
Hi, I noticed that this issue was removed from the "future" milestone label - @goanpeca or @ccordoba12 are there still plans to implement this in future releases? This would be a great feature to have.  Thanks

Aside: Btw a huge thanks to the entire team that updates and maintains Spyder!

**Comment by ccordoba12** [comment]
Thanks for your kind words @rpinto73!

**Comment by a4bears** [comment]
Yes!! This would be super useful

**Comment by wwhoward** [comment]
Would love to see this.

**Comment by ajauskas** [comment]
Still doesn't exist, right? That would be quite useful for me.

**Comment by BerezhnoyD** [comment]
Will add my upvote. Adding this functionality would be great. Thank you for maintaining Spyder.

**Comment by EdSaiedi** [comment]
Will add my upvote too for such a feature. Coming from a Stata background, autorefreshing is key for understanding the data. Given the comment of a user [here](https://stackoverflow.com/questions/53571920/how-to-see-updated-dataframe-after-i-run-the-code-again-in-spyder-without-doubl), users switch to other programs like Sublime due to such an issue. Perhaps implementation could start with smaller dataframes, if a concern is the processing power an autorefresh function would use up?

**Comment by anton2qr4q** [comment]
This would be incredibly helpful

**Comment by anton2qr4q** [comment]
> 

I don't think Sublime can do it, think he is just saying he will stick with Sublime and print to console.

Have you had any luck finding an alternative? Thanks

**Comment by anton2qr4q** [comment]
> Will add my upvote too for such a feature. Coming from a Stata background, autorefreshing is key for understanding the data. Given the comment of a user [here](https://stackoverflow.com/questions/53571920/how-to-see-updated-dataframe-after-i-run-the-code-again-in-spyder-without-doubl), users switch to other programs like Sublime due to such an issue. Perhaps implementation could start with smaller dataframes, if a concern is the processing power an autorefresh function would use up?

I don't think Sublime can do it, think he is just saying he will stick with Sublime and print to console.

Have you had any luck finding an alternative? Thanks

**Comment by Artyom-K** [comment]
I would also like the global setting for all these windows. Most of the time I would like them to be autorefreshed but sometimes I need to compare values for different runs.

**Comment by ccordoba12** [comment]
Unfortunately, we can't make this work automatically because it'd consume a lot of memory. Every operation that shows a variable in one of our specialized viewers involves making a copy of it. That copy is cleared once users close the viewer.

But if viewers are maintained opened and they're being updated after every code execution, the memory consumed by Spyder can skyrocket quite quickly, especially for large variables.

So, I think the best we can do is to add a refresh button to our viewers, so users can do update them on demand. We'll try to do that in the future.

**Comment by anton2qr4q** [comment]
Understood Carlos, the refresh button would be a fantastic addition, thank you

**Comment by bajhuman** [comment]
This would be a very useful feature, i.e. allowing only one open view per variable and updating that variable as code gets executed rather than pressing refresh.

**Comment by ccordoba12** [comment]
@bajhuman, please read my [previous comment](https://github.com/spyder-ide/spyder/issues/6325#issuecomment-1472388650): that can't be done because it'll increase the memory consumed by Spyder without limit.
