### ISSUE TITLE
Received signal 11 SEGV_MAPERR

### ISSUE THREAD

**Issue by sphh** [spyder-ide/spyder#6347]
## Description of your problem

Spyder crashes immediately after starting.

**What steps will reproduce the problem?**

1. Start spyder from a terminal: `$ spyder3`
2. Introscreen is shown until `Setting up main window` (at least I believe that's the last message shown)
3. Crash

**What is the expected output? What do you see instead?**
Well, spyder should start.

**Please provide any additional information below**

- Spyder was installed via pip: `sudo pip3 install`.
- Spyder was upgraded via pip: `sudo pip3 install --upgrade spyder` (see output below).
- I reset spyder with `spyder3 --reset`.

If you need any more info than given below, I am happy to provide it.

## Versions and main components

* Spyder Version: 3.2.6
* Python Version: 3.5.2
* Qt Version: 5.10
* PyQt Version: 1.3.1
* Operating system: Linux Mint 18.3

## Error message

```
QApplication: invalid style override passed, ignoring it.
Received signal 11 SEGV_MAPERR 000008b1d8fc
#0 0x7fb3c257c9a5 <unknown>
#1 0x7fb3c12bc501 <unknown>
#2 0x7fb3c257cd3d <unknown>
#3 0x7fb3fe0ae390 <unknown>
#4 0x7fb3fde21168 <unknown>
#5 0x7fb3b06c0f75 <unknown>
#6 0x7fb3b04ebaad <unknown>
#7 0x7fb3b04ecd25 <unknown>
#8 0x7fb3b04ee031 <unknown>
#9 0x7fb3b03fe27a <unknown>
#10 0x7fb3d2ae48a0 <unknown>
#11 0x7fb3d2ae5501 <unknown>
#12 0x7fb3d2ab328f <unknown>
#13 0x7fb3d2ab3aca QOpenGLShaderProgram::link()
#14 0x7fb3d2ad3a05 QOpenGLTextureBlitter::create()
#15 0x7fb3d2a5a272 QPlatformBackingStore::composeAndFlush()
#16 0x7fb3bb523a95 <unknown>
#17 0x7fb3cd95292a <unknown>
#18 0x7fb3cd953d41 <unknown>
#19 0x7fb3cd955a50 <unknown>
#20 0x7fb3cd956192 <unknown>
#21 0x7fb3cd99e624 <unknown>
#22 0x7fb3cd99f123 <unknown>
#23 0x7fb3cd94654c QApplicationPrivate::notify_helper()
#24 0x7fb3cd94d897 QApplication::notify()
#25 0x7fb3ce391c9e sipQApplication::notify()
#26 0x7fb3d71009f8 QCoreApplication::notifyInternal2()
#27 0x7fb3d27bb837 QGuiApplicationPrivate::processExposeEvent()
#28 0x7fb3d27bc38d QGuiApplicationPrivate::processWindowSystemEvent()
#29 0x7fb3d279815b QWindowSystemInterface::sendWindowSystemEvents()
#30 0x7fb3bb5969ab <unknown>
#31 0x7fb3d7710a04 meth_QCoreApplication_processEvents
#32 0x0000004e9ba7 PyCFunction_Call
#33 0x0000005372f4 PyEval_EvalFrameEx
#34 0x000000540f9b PyEval_EvalCodeEx
#35 0x0000004ebd23 <unknown>
#36 0x0000005c1797 PyObject_Call
#37 0x0000004fb9ce <unknown>
#38 0x0000005c1797 PyObject_Call
#39 0x000000534d90 PyEval_CallObjectWithKeywords
#40 0x7fb3d77abe25 PyQtSlot::call()
#41 0x7fb3d77ac330 PyQtSlot::invoke()
#42 0x7fb3d77ac5ab PyQtSlotProxy::unislot()
#43 0x7fb3d77ad387 PyQtSlotProxy::qt_metacall()
#44 0x7fb3d712bd34 QMetaObject::activate()
#45 0x7fb3d77a8bf9 pyqtBoundSignal_emit
#46 0x0000004e9b7f PyCFunction_Call
#47 0x0000005372f4 PyEval_EvalFrameEx
#48 0x000000540199 <unknown>
#49 0x00000053bd92 PyEval_EvalFrameEx
#50 0x0000005406df <unknown>
#51 0x00000053bd92 PyEval_EvalFrameEx
#52 0x00000053b7e4 PyEval_EvalFrameEx
#53 0x00000053b7e4 PyEval_EvalFrameEx
#54 0x00000053b7e4 PyEval_EvalFrameEx
#55 0x00000053b7e4 PyEval_EvalFrameEx
#56 0x00000053b7e4 PyEval_EvalFrameEx
#57 0x00000053b7e4 PyEval_EvalFrameEx
#58 0x000000540199 <unknown>
#59 0x000000540e4f PyEval_EvalCode
#60 0x00000060c272 <unknown>
#61 0x00000060e71a PyRun_FileExFlags
  r8: ffffffffffffffff  r9: 0000000000000000 r10: 0000000000000022 r11: 0000000000000246
 r12: 0000000004b9b170 r13: 0000000004bd5c30 r14: 0000000004b74b70 r15: 0000000004b3cee0
  di: 00007fb2f807d010  si: 0000000004b9b170  bp: 00007ffcb55d3430  bx: 0000000003f8280c
  dx: 0000000003f8280c  ax: 00007fb2f807d010  cx: 0000000008b1d97c  sp: 00007ffcb55d3418
  ip: 00007fb3fde21168 efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000008b1d8fc
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

## Dependencies

Output of `sudo pip3 install --upgrade spyder`:
```
Requirement already up-to-date: spyder in /usr/local/lib/python3.5/dist-packages
Requirement already up-to-date: rope>=0.10.5 in /usr/local/lib/python3.5/dist-packages (from spyder)
Requirement already up-to-date: psutil in /usr/local/lib/python3.5/dist-packages (from spyder)
Requirement already up-to-date: numpydoc in /usr/local/lib/python3.5/dist-packages (from spyder)
Requirement already up-to-date: qtconsole>=4.2.0 in /usr/local/lib/python3.5/dist-packages (from spyder)
Requirement already up-to-date: pyqt5; python_version >= "3" in /usr/local/lib/python3.5/dist-packages (from spyder)
Requirement already up-to-date: chardet>=2.0.0 in /usr/local/lib/python3.5/dist-packages (from spyder)
Requirement already up-to-date: qtpy>=1.2.0 in /usr/local/lib/python3.5/dist-packages (from spyder)
Requirement already up-to-date: pickleshare in /usr/local/lib/python3.5/dist-packages (from spyder)
Requirement already up-to-date: jedi>=0.9.0 in /usr/local/lib/python3.5/dist-packages (from spyder)
Requirement already up-to-date: cloudpickle in /usr/local/lib/python3.5/dist-packages (from spyder)
Requirement already up-to-date: pyflakes in /usr/local/lib/python3.5/dist-packages (from spyder)
Requirement already up-to-date: pycodestyle in /usr/local/lib/python3.5/dist-packages (from spyder)
Requirement already up-to-date: nbconvert in /usr/local/lib/python3.5/dist-packages (from spyder)
Requirement already up-to-date: qtawesome>=0.4.1 in /usr/local/lib/python3.5/dist-packages (from spyder)
Requirement already up-to-date: pyopengl; platform_system == "Linux" in /usr/local/lib/python3.5/dist-packages (from spyder)
Requirement already up-to-date: pyzmq in /usr/local/lib/python3.5/dist-packages (from spyder)
Requirement already up-to-date: pygments>=2.0 in /usr/local/lib/python3.5/dist-packages (from spyder)
Requirement already up-to-date: sphinx in /usr/local/lib/python3.5/dist-packages (from spyder)
Requirement already up-to-date: pylint in /usr/local/lib/python3.5/dist-packages (from spyder)
Requirement already up-to-date: Jinja2>=2.3 in /usr/local/lib/python3.5/dist-packages (from numpydoc->spyder)
Requirement already up-to-date: ipykernel>=4.1 in /usr/local/lib/python3.5/dist-packages (from qtconsole>=4.2.0->spyder)
Requirement already up-to-date: jupyter-client>=4.1 in /usr/local/lib/python3.5/dist-packages (from qtconsole>=4.2.0->spyder)
Requirement already up-to-date: ipython-genutils in /usr/local/lib/python3.5/dist-packages (from qtconsole>=4.2.0->spyder)
Requirement already up-to-date: jupyter-core in /usr/local/lib/python3.5/dist-packages (from qtconsole>=4.2.0->spyder)
Requirement already up-to-date: traitlets in /usr/local/lib/python3.5/dist-packages (from qtconsole>=4.2.0->spyder)
Requirement already up-to-date: sip<4.20,>=4.19.4 in /usr/local/lib/python3.5/dist-packages (from pyqt5; python_version >= "3"->spyder)
Requirement already up-to-date: parso==0.1.1 in /usr/local/lib/python3.5/dist-packages (from jedi>=0.9.0->spyder)
Requirement already up-to-date: entrypoints>=0.2.2 in /usr/local/lib/python3.5/dist-packages (from nbconvert->spyder)
Requirement already up-to-date: nbformat>=4.4 in /usr/local/lib/python3.5/dist-packages (from nbconvert->spyder)
Requirement already up-to-date: pandocfilters>=1.4.1 in /usr/local/lib/python3.5/dist-packages (from nbconvert->spyder)
Requirement already up-to-date: bleach in /usr/local/lib/python3.5/dist-packages (from nbconvert->spyder)
Requirement already up-to-date: mistune>=0.7.4 in /usr/local/lib/python3.5/dist-packages (from nbconvert->spyder)
Requirement already up-to-date: testpath in /usr/local/lib/python3.5/dist-packages (from nbconvert->spyder)
Requirement already up-to-date: six in /usr/local/lib/python3.5/dist-packages (from qtawesome>=0.4.1->spyder)
Requirement already up-to-date: requests>=2.0.0 in /usr/local/lib/python3.5/dist-packages (from sphinx->spyder)
Requirement already up-to-date: snowballstemmer>=1.1 in /usr/local/lib/python3.5/dist-packages (from sphinx->spyder)
Requirement already up-to-date: sphinxcontrib-websupport in /usr/local/lib/python3.5/dist-packages (from sphinx->spyder)
Requirement already up-to-date: docutils>=0.11 in /usr/local/lib/python3.5/dist-packages (from sphinx->spyder)
Requirement already up-to-date: babel!=2.0,>=1.3 in /usr/local/lib/python3.5/dist-packages (from sphinx->spyder)
Requirement already up-to-date: setuptools in /usr/local/lib/python3.5/dist-packages (from sphinx->spyder)
Requirement already up-to-date: imagesize in /usr/local/lib/python3.5/dist-packages (from sphinx->spyder)
Requirement already up-to-date: alabaster<0.8,>=0.7 in /usr/local/lib/python3.5/dist-packages (from sphinx->spyder)
Requirement already up-to-date: astroid<2.0,>=1.6 in /usr/local/lib/python3.5/dist-packages (from pylint->spyder)
Requirement already up-to-date: isort>=4.2.5 in /usr/local/lib/python3.5/dist-packages (from pylint->spyder)
Requirement already up-to-date: mccabe in /usr/local/lib/python3.5/dist-packages (from pylint->spyder)
Requirement already up-to-date: MarkupSafe>=0.23 in /usr/local/lib/python3.5/dist-packages (from Jinja2>=2.3->numpydoc->spyder)
Requirement already up-to-date: ipython>=4.0.0 in /usr/local/lib/python3.5/dist-packages (from ipykernel>=4.1->qtconsole>=4.2.0->spyder)
Requirement already up-to-date: tornado>=4.0 in /usr/local/lib/python3.5/dist-packages (from ipykernel>=4.1->qtconsole>=4.2.0->spyder)
Requirement already up-to-date: python-dateutil>=2.1 in /usr/local/lib/python3.5/dist-packages (from jupyter-client>=4.1->qtconsole>=4.2.0->spyder)
Requirement already up-to-date: decorator in /usr/local/lib/python3.5/dist-packages (from traitlets->qtconsole>=4.2.0->spyder)
Requirement already up-to-date: jsonschema!=2.5.0,>=2.4 in /usr/local/lib/python3.5/dist-packages (from nbformat>=4.4->nbconvert->spyder)
Requirement already up-to-date: html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre in /usr/local/lib/python3.5/dist-packages (from bleach->nbconvert->spyder)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python3.5/dist-packages (from requests>=2.0.0->sphinx->spyder)
Requirement already up-to-date: idna<2.7,>=2.5 in /usr/local/lib/python3.5/dist-packages (from requests>=2.0.0->sphinx->spyder)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.5/dist-packages (from requests>=2.0.0->sphinx->spyder)
Requirement already up-to-date: pytz>=0a in /usr/local/lib/python3.5/dist-packages (from babel!=2.0,>=1.3->sphinx->spyder)
Requirement already up-to-date: lazy-object-proxy in /usr/local/lib/python3.5/dist-packages (from astroid<2.0,>=1.6->pylint->spyder)
Requirement already up-to-date: wrapt in /usr/local/lib/python3.5/dist-packages (from astroid<2.0,>=1.6->pylint->spyder)
Requirement already up-to-date: pexpect; sys_platform != "win32" in /usr/local/lib/python3.5/dist-packages (from ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
Requirement already up-to-date: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python3.5/dist-packages (from ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
Requirement already up-to-date: simplegeneric>0.8 in /usr/lib/python3/dist-packages (from ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
Requirement already up-to-date: webencodings in /usr/local/lib/python3.5/dist-packages (from html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre->bleach->nbconvert->spyder)
Requirement already up-to-date: ptyprocess>=0.5 in /usr/local/lib/python3.5/dist-packages (from pexpect; sys_platform != "win32"->ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
Requirement already up-to-date: wcwidth in /usr/local/lib/python3.5/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
```

**Comment by ccordoba12** [comment]
Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.

**Comment by sphh** [comment]
But I followed the Troubleshooting-Guide-and-FAQ as you certainly has noticed (e.g. calling `spyder3 --reset` and upgrading all packages, etc.).

In the [Installation Guide](https://pythonhosted.org/spyder/installation.html#installing-on-linux) the installation via `pip` is a supported installation method.

I am really surprised that you are not interested to track this issue down. I installed spyder on three different computers with the very same procedure, but only have this problem on one computer after it was working perfectly for a long time.

What you are basically saying is, that this is a user's error. This reminds me very much of the standard answer of a big software company.

Honestly, I am highly disappointed with this reply.

**Comment by ccordoba12** [comment]
> In the Installation Guide the installation via pip is a supported installation method.

It is, of course, that's why you can run `pip install spyder`. But we don't give support for it, as I said.

> I am really surprised that you are not interested to track this issue down

It's probably a PyQt issue, so please downgrade to PyQt 5.9.2 and try again. Spyder is a pure Python package, so it can't generate segfaults like the one you reported.

> What you are basically saying is, that this is a user's error

No, we're saying that if you want to use a custom installation procedure, it's up to you to find and solve all the problems you encounter. Else, you're welcome to receive our (limited) help if you use Anaconda.

**Comment by CAM-Gerlach** [comment]
> In the Installation Guide the installation via ``pip`` is a supported installation method.

We've made this distinction (hopefully) much clearer in all the docs for 3.2.7, due out soon. Basically, we provide the packages for various install mechanisms on a "best-effort" basis, but due to the many tricky issues that can occur with non-Anaconda installers, particularly ``pip``, we strongly discourage using them for users who aren't experts able to solve any resulting problems on their own, and particularly as we are currently unfunded and entirely community supported, we simply lack the resources to provide individual post-install help to everyone who chooses this method.

> I installed spyder on three different computers with the very same procedure, but only have this problem on one computer after it was working perfectly for a long time.

Indeed, then this is a clear sign the issue is likely with something in your specific install/machine/environment, rather than intrinsic to the Spyder package, and thus only you are likely to be able to fix it.

> What you are basically saying is, that this is a user's error. This reminds me very much of the standard answer of a big software company.

We are saying that, given all the data that has been provided to us, the error appears very likely to be something other than a bug in the native Spyder codebase, and therefore outside our native ability to fix or likely even easily diagnose, and in any case is a result of a non-recommended install method, I'm not quite sure what else we're supposed to say—this is a bug tracker, not a help forum after all, though we generally do our best to help where we can.

Furthermore, unlike a "big software company", we are all volunteers and members of the community like you, and being currently unfunded we have no real money coming in aside from a relatively small amount of donations. Therefore, while we try to help where we can, we must spend our very limited time wisely so we can still have the resources to make Spyder even better you and everyone else, beyond just keeping our heads above the flood of user-specific issues.

I'm really sorry we can't immediately fix your problem, and I wish we could do more. Best of luck!

**Comment by sphh** [comment]
Thanks @CAM-Gerlach and @ccordoba12 for taking the time and explaining everything. Highly appreciated!

May I suggest a way forward for similar issues: Instead of only telling the user that s/he should look into the troubleshooting guide (let's assume in his/her favour that s/he did that already!), simply write a quick reply where you think the problem lies. Since you already invested the time to figure out that it's not spyder's problem, that should be easy to do. The user does not necessarily know that this is not spyder's problem. It might also help others stumbling over the same issue. (At least I am always searching the open and closed bugs for similar problems before reporting it.)

Thanks.

**Comment by sphh** [comment]
BTW I now believe that this is a problem with the mesa libraries. After downgrading it by one version (18.1→17.4), spyder works again.

Thank you @ccordoba12 to point me in the right direction!!

For everybody who comes to this thread, these are the commands I used (assuming that the .deb packages are still cached):
```
$ VERSION=17.4~git1801240952.4064fe~oibaf~x
$ sudo dpkg -i \
libgl1-mesa-dri_${VERSION}_amd64.deb \
libgl1-mesa-dri_${VERSION}_i386.deb \
libgl1-mesa-glx_${VERSION}_amd64.deb \
libgl1-mesa-glx_${VERSION}_i386.deb \
libglapi-mesa_${VERSION}_i386.deb \
libglapi-mesa_${VERSION}_amd64.deb \
libgles1-mesa_${VERSION}_amd64.deb \
libgles2-mesa_${VERSION}_amd64.deb \
libegl1-mesa_${VERSION}_amd64.deb \
libegl1-mesa-drivers_${VERSION}_amd64.deb \
libgbm1_${VERSION}_amd64.deb \
libwayland-egl1-mesa_${VERSION}_amd64.deb \
libxatracker2_${VERSION}_amd64.deb
```

**Comment by CAM-Gerlach** [comment]
> May I suggest a way forward for similar issues: Instead of only telling the user that s/he should look into the troubleshooting guide (let's assume in his/her favour that s/he did that already!), simply write a quick reply where you think the problem lies.

I can't speak for anyone else, but generally I do so when the information provided is sufficient to make such a guess, and try to follow up with more detail to flesh out others' responses when appropriate. However, with potentially dozens of issues per day, it can take a non-trivial amount of time to do and particularly for other team members who presumably have personal lives unlike myself, along with full time jobs and other projects they are working on, this can potentially take up a significant amount of their limited time to develop Spyder.

> At least I am always searching the open and closed bugs for similar problems before reporting it.

Suffice to say, with this, checking the troubleshooting guide, and providing plenty of information about the problem, you're ahead of >95% of posters here, and the majority have none of them. To be honest, my typical responses are probably too detailed already, since I spend an average of several hours per day just responding to issues, close to the equivalent of a 20 hr/week part time job, aside from my time developing Spyder itself.

> his/her

Pro tip (from a former copyeditor): I used to be a big stickler on this, but I now would suggest "they" in this context as its much cleaner and less awkward, and is effectively unambiguous in this context...if it was good enough for Shakespeare, its good enough for me.
