### ISSUE TITLE
Closing Project: Error

### ISSUE THREAD

**Issue by virati** [spyder-ide/spyder#6353]
## Description

**What steps will reproduce the problem?**

1. Open a project with multiple documents
2. Close the project through "Projects -> Close Project"
3. 

**What is the expected output? What do you see instead?**
I expected for the project to close without an error and the appearance of a temporary document

**Please provide any additional information below**

  File "/usr/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1967, in plugin_focus_changed
    self.update_edit_menu()
  File "/usr/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 2009, in update_edit_menu
    widget, textedit_properties = self.get_focus_widget_properties()
  File "/usr/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 2002, in get_focus_widget_properties
    not_readonly = not widget.isReadOnly()
RuntimeError: wrapped C/C++ object of type CodeEditor has been deleted

## Version and main components

* Spyder Version: 4.0.0.dev0 
* Python Version: 3.6.4
* Qt Versions: 5.10.0, PyQt5 5.10 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.21.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.6 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. To note, this error appears identical to #5898, which was closed as a ``NoResponce``. 
In any case, please describe in detail the circumstances in which the error occurred, and post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Spyder Troubleshooting Guide as a comment to this issue, and we'll try to help if we can. Otherwise, your issue will likely have to be closed after one week (7 days). 

Also, if it occurs again, please reference [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) section for some basic steps to try to fix it or at least narrow it down for us. Thanks, and best of luck!

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response. Please comment and reopen if you can provide more details about the situation. Thanks!
