### ISSUE TITLE
segfault when trying to run spyder on Manjaro Linux

### ISSUE THREAD

**Issue by tomkc** [spyder-ide/spyder#6377]
## Description of your problem

after using spyder perfectly fine for few months without any issues i was trying to run it yesterday (first time since few weeks) and stuck on a segfault, here's a dump from console:

```
[tqc@tqc-pc ~]$ spyder
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
Received signal 11 SEGV_MAPERR 000004e00028
#0 0x7f04bc2d02f6 <unknown>
#1 0x7f04baefc24c <unknown>
#2 0x7f04bc2d066c <unknown>
#3 0x7f04e46cadd0 <unknown>
#4 0x7f04e43396f2 __GI___cxa_atexit
#5 0x7f0434002e40 <unknown>
  r8: 0000000000000000  r9: 0000000000000000 r10: 0000000000000000 r11: 00007f04a82c5600
 r12: 3e9e240f56dca900 r13: 00007f043fffe4e0 r14: 00007f04ab460da0 r15: 00007f04ab665000
  di: 00007f0434000020  si: 0000000000000000  bp: 0000000000000407  bx: 00007f0434000020
  dx: 00005562c51e4780  ax: 0000000004e00018  cx: 0000000000000000  sp: 00007f043fffe330
  ip: 00007f04e43396f2 efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000006
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000004e00028
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```
fresh reinstall didn't fix the problem.

My software configuration:

Spyder 3.2.4-1
Python 3.6.4
Qt 5.10.0-3
PyQt 5.10-1
Manjaro 17.1.3

**Comment by ccordoba12** [comment]
Please downgrade pyqt5 to its 5.9.2 and try again.

If that fails, please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.
