### ISSUE TITLE
Empty lines are hidden in source editor

### ISSUE THREAD

**Issue by bruns01** [spyder-ide/spyder#6402]
## Description of your problem
I freshly installed a python 3.5.4 from python.org (msi-install) under windows 10 and pip-installed spyder, which resulted in spyder 3.2.6 .
When I type my source code and insert empty lines for improved readability, the empty lines do not show in the editor window. If I enter 3 new lines I need 3 back-spaces to get back to the original position with the cursor. Hence, the empty lines seem to exist, but are not shown.
I checked all preferences for an option to hide/un-hide empty lines, but didn't find anything.

Whats wrong???

An additional issue is that line numbers are not shown at the left border, although the option is marked in the preferences. But I can live with that.

**What steps will reproduce the problem?**

1. start spyder 
2. type some code
3. enter newline several times 
4. enter additional code

**What is the expected output? What do you see instead?**
The expected output is "code -- space (empty lines) -- code"
What I see is "code code"

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.2.6
* Python Version: 3.5.4
* Qt Version: 5.10.0
* PyQt Version: 5.10
* Operating system: windows 10 64-Bit

## Dependencies
all dependencies listed are "ok" except for
cython
sympy

**Comment by ccordoba12** [comment]
> I freshly installed a python 3.5.4 from python.org (msi-install) under windows 10 and pip-installed spyder, which resulted in spyder 3.2.6

Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.

> Whats wrong???

Probably the use of PyQt 5.10. My only advice: try to downgrade to 5.9.2 and try again. Else use Anaconda, as I said above.

**Comment by erik-mansson** [comment]
Although the issue is long closed, I want to document what happened to me today for people finding this issue by web searches in the future:

I used Spyder while on a wireless network (somestimes also with VPN client's virtual network adapter) yesterday on a Windows 10 64-bit laptop, then quit Spyder and hibernated the computer, then started it today with a network cable connected. When starting Python, on the same Python source code files as yesterday several issues were noticed:

- The gray area for line numbers was visible but no numbers were printed (not even line 1)
- Blank lines were missing or hidden! It was really confusing with the cursor that if I moved it down from a line with code, or right past the end of the line, the text cursor became invisible. Moving it further could make it show up on the next line (which had code). If I typed while invisible, a new line would appear, but with Enter-presses I could never achieve the pair of line breaks that would normally produce a blank line.
- This was the case both for some small files and for the big file (with 2300 lines) where I noticed it first.

After not finding any similar issues online, I thought maybe it was time to upgrade Anaconda & Spyder, but after doing this the issue remained. Tried disabling and re-enabling line numbers and other Spyder-editor settings, with no success.

Finally, I rebooted the computer. And now the editor works normally again. My guess is that it was something related to a service running in the background (e.g. something else for code analysis although I have disabled Kite) and getting confused by the way I was on another network (wired instead of wireless) after exiting hibernation. (Spyder 4.1.2, 32-bit Python 3.7.7, IPython 7.13.0, Qt 5.9.7).
