### ISSUE TITLE
Failed to Start Spyder for no OpenGL found in my PC

### ISSUE THREAD

**Issue by gfkdcadet** [spyder-ide/spyder#6411]
## Failed to start spyder3

**What is the expected output? What do you see instead?**
I installed python3.5, then downloaded spyder by pip command. When I wanted to start spyder, it showed a warning that my PC hadn't installed a graphic driver with OpenGL.

**Please provide any additional information below**
![failed_to_start_spyder](https://user-images.githubusercontent.com/9277924/35949670-a3d319e4-0cad-11e8-8a92-76d32fbccbd8.png)
![python_version](https://user-images.githubusercontent.com/9277924/35949671-a40fe86a-0cad-11e8-86bc-c219c12bd8c2.png)

## Versions and main components

* Spyder Version: 3.2.6
* Python Version: 3.5.3
* Qt Version: QtPy, 1.3.1
* PyQt Version: PyQt5, 5.10
* Operating system: win 7 x64-based PC

**Comment by ccordoba12** [comment]
> I installed python3.5, then downloaded spyder by pip command

Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.

----

I'm closing this one because this is not a Spyder problem but a PyQt5 one.
