### ISSUE TITLE
Error on Launch from Anaconda Navigator 1.6.12

### ISSUE THREAD

**Issue by spradlig** [spyder-ide/spyder#6441]
## Description
This is an automatically generated error report from Spyder that occurs every time I launch Spyder from Anaconda Navigator under one of my environments. I have not tried with the base environment as this error has not caused me any real issues only the annoyance of seeing it every time I launch Spyder.

**What steps will reproduce the problem?**

1. Launch Spyder via Anaconda Navigator 1.6.12 on Ubuntu 16.04 Desktop.
2. 
3. 

**What is the expected output? What do you see instead?**
N/A

**Please provide any additional information below**

    module = _import_module_from_path(module_name, plugin_path)
    module = spec.loader.load_module(module_name)
AttributeError: 'NoneType' object has no attribute 'load_module'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.1 (OK)

```

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. A seemingly identical issue was reported previously as  #5593 , but the poster never followed up. Have you installed any third-party plugins, like ``spyder-terminal``, ``spyder-notebook``, etc? These might be associated with this error.

If you are sure you haven't installed any of these, please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

If it still isn't working, please describe in detail the circumstances in which the error occurred, and post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Calling for Help section as a comment to this issue, and we'll try to help if we can. Otherwise, your issue will likely have to be closed after one week (7 days). Thanks, and best of luck!

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response.
