### ISSUE TITLE
Spyder freezes at starting window

### ISSUE THREAD

**Issue by Daniel439** [spyder-ide/spyder#6449]
## Description of your problem
The Spyder freezes at "Loading outline explorer" when starting.

**What steps will reproduce the problem?**

1. Start Spyder 

**What is the expected output? What do you see instead?**
The Spyder freezes at "Loading outline explorer" when starting.

**Please provide any additional information below**
No error shown.

>conda update spyder

and

>spyder --reset

have been tried. It's not working. The issue used to be resolved by reinstall the spyder through Anaconda.

Update: Issue can also be solved by restarting PC. Still my PC always remains open and if there is a method to fix this without restarting it would be great.

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.6
* Qt Version:
* PyQt Version:
* Operating system: Win10 Newest Update

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by CAM-Gerlach** [comment]
This is rather odd, but given the information you've provided, it seems unlikely to be within Spyder's control possibly unless it has to do with some of zombie process sticking around after Spyder is first closed, and in any case we have no way to reproduce it.

In any case, please try the remaining steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

If it still isn't working, please describe in detail the circumstances in which the error occurred, and post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Calling for Help section as a comment to this issue, and we'll try to help if we can, but I'm not sure how much we can do for you. Otherwise, your issue will likely have to be closed after one week (7 days). Thanks, and best of luck!

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response.
