### ISSUE TITLE
Use an authentication dialog to send reports to Github

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#6617]
I recently learned about the QCrash package (thanks @gmarull!):

https://github.com/ColinDuquesnoy/QCrash

which has a very nice dialog to authenticate users and open an issue on Github on behalf of them:

https://github.com/ColinDuquesnoy/QCrash/blob/master/docs/_static/qcrash_github_login.png

Since QCrash is licensed MIT, I think we should use this dialog after users press our *Submit to Github* button. Our current approach is not working as expected because I've seen several issues without a traceback and other empty ones.

@dalthviz, please work on this by:

1. Copying that dialog to our source code.
2. Adding the `githubpy` dependency to our `utils/external` module.
3. Remove the `keyring` dependency used to save passwords through the `Remember me` checkbox of that dialog.

**Comment by ccordoba12** [comment]
By the way, the problem with `keyring` is that it's a new dependency and it's not packaged correctly in conda for Linux. But could use it for Spyder 4 :-)

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Sounds like a good plan; yeah, I've seen quite a few of those too. Some less observant users are clearly still missing the "Paste here to complete reporting" message or otherwise mishandling that, even though added more emphasis to the latter to try to make it harder to miss. This definitely looks a lot slicker, and potentially could open up additional enhancement opportunities down the road. I assume this all uses the Github API with the user's credentials, and everything else is handled automatically?

**Comment by ccordoba12** [comment]
> I assume this all uses the Github API with the user's credentials, and everything else is handled automatically?

Yes, that's right.

**Comment by gmarull** [comment]
If you need any help let me know :-) I have also used QCrash with sentry.io or rollbar (i.e. custom backend), they are great to discover bugs.
