### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by ARoseB** [spyder-ide/spyder#6636]
I had tried to install mapsplotlib. I got an error related to the Pillow package version. Since then, my kernal isn't restarting.
I have tried to reset settings, that doesn't work

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. Unfortunately, you've given us very little information on which to go on, including that which is supposed to be included automatically with these reports (error traceback, versions of key components and dependencies, etc.) and must have been either deleted or not copied properly. Please provide this information so we can properly respond; otherwise, this issue will be closed after one week (7 days). Furthermore, the error popup you received should have clearly stated your first recourse should be the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

In any case, if the error started after doing an install (most likely with ``pip``, but possible with ``conda`` as well), it is almost certainly outside of our control. Try ``conda install tornado=4.5.3`` in case you accidentally updated to 5.0, which is having issues right now. Other than that, you'll need to (re)-install Anaconda or fix your installation yourself, following the steps in the above guide.

If it still isn't working, please describe in detail the circumstances in which the error occurred, and post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Calling for Help section as a comment to this issue, and we'll try to help if we can.
