### ISSUE TITLE
Automatic error report [fresh install not working]

### ISSUE THREAD

**Issue by MAFiA303** [spyder-ide/spyder#6638]
steps:
1. install fresh anaconda (latest 64 on windows 10)
2. using terminal 
`conda update --all`
it fails 
3. try:
`conda update ipykernel`
it results in updating anaconda to a new custom version
4. `conda update --all`

result:
spyder kernal is not working and I'm here submitting the popup error

**Comment by MAFiA303** [comment]
it seems latest Tornado is causing this error
downgrade from 5.0 to 4.5.3

**Comment by CAM-Gerlach** [comment]
> spyder kernal is not working and I'm here submitting the popup error

Thanks for figuring this out. Please be aware that you didn't actually include any error message or report with your post as this seems to imply, probably because you didn't actually paste it into the dialog as the instruction states, or you deleted the default template. In any case, we will likely be including a new system to send error reports in the next version of Spyder, 3.2.8, to make it even more difficult for users to make these sorts of mistakes.

**Comment by CAM-Gerlach** [comment]
For reference, yet another duplicate of #6627
