### ISSUE TITLE
Problem in dictionary

### ISSUE THREAD

**Issue by Javilu11** [spyder-ide/spyder#6666]
## Description

**What steps will reproduce the problem?**

1. Make a dictionary
2. Fill it with lists of tuples

**What is the expected output? What do you see instead?**

The problem is, when spyder shows the dictionary, the size of each list has errors. Maybe, it is a list of 4 tuples and this shows 15 but if you use len(...) this shows 4.

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 2.7.14
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
numpy >=1.7       :  1.13.3 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.4.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.26.1 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.4 (OK)

```

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. I was unable to reproduce this in Spyder 3.2.7, the current version (3.2.4 is many months out of date). I ran the following

```
test_dict = {"test1": [(43, 32, "won"), (34., "dsfds"), (7.2, 5.3, 2, 3)],
             "test2": [("43", "dds", "won"), (34., "dsfds")],
             "test3": [(43, 32), (34., "sfdds"), (7.2, 5.33, 23), ("foo")]}
```

and observed all the correct values in the Variable Explorer. Please update Spyder, try it and see if you get the same results, and if not, provide sample code for a dictionary that does trigger the problem for you. My naive speculation is that it might be something transient and difficult to reproduce, along the lines of e.g. #6258 and its brethren. Otherwise, if we don't hear from you, this issue will be closed after a week (7 days).

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.
