### ISSUE TITLE
Problem spyder crashed in windows10

### ISSUE THREAD

**Issue by 2jl** [spyder-ide/spyder#6668]
Hello, I just installed Anaconda 3 in windows10 and I have problems running spyder

### What steps will reproduce the problem?

When I run the Spyder shortcut I get the error of the image

![image](https://user-images.githubusercontent.com/28129001/37126270-40f27594-223e-11e8-8247-97c444fab23e.png)
When I use the command `spyder --show-console` it gives me the following error in the console.

(base) C:\Users\Jorge Julca>spyder --show-console
(Deprecated) --show console does nothing, now the default  behavior is to show the console, use --hide-console if you want to hide it
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3126, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3023, in run_spyder
    main.setup()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 847, in setup
    from spyder.plugins.help import Help
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\help.py", line 32, in <module>
    from spyder.utils.help.sphinxify import (CSS_PATH, generate_context,
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\help\sphinxify.py", line 30, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "C:\ProgramData\Anaconda3\lib\site-packages\jinja2\__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "C:\ProgramData\Anaconda3\lib\site-packages\jinja2\environment.py", line 15, in <module>
    from jinja2 import nodes
  File "C:\ProgramData\Anaconda3\lib\site-packages\jinja2\nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "C:\ProgramData\Anaconda3\lib\site-packages\jinja2\utils.py", line 647, in <module>
    from markupsafe import Markup, escape, soft_unicode
  File "C:\Users\Jorge Julca\AppData\Roaming\Python\Python36\site-packages\markupsafe\__init__.py", line 14, in <module>
    from markupsafe._compat import text_type, string_types, int_types, \
ModuleNotFoundError: No module named 'markupsafe._compat'

What I was testing was the following
1. Reinstall Anaconda
2. Install and update spyder `pip install -U spyder`
3. Remove and install spyder `conda install -c anaconda spyder`
4. Remove and install spyder (Anaconda Navigator)

## Package Versions

* Spyder: 3.2.7
* Python: 3.6.4

**Comment by CAM-Gerlach** [comment]
Thanks for reporting and including the steps you tried.

> Install and update spyder ``pip install -U spyder``

Will likely mess up your install since you already have Spyder installed with Anaconda, presumably. Avoid installing packages with ``pip`` if at all possible, particularly anything Spyder or Spyder related. Please reinstall Anaconda and only install/update Spyder, etc. with ``conda`` and see if the error persists. Also, if you look at the specific error, the problem occurs with the ``markupsafe`` package, which appears to be installed in a custom per user non-Anaconda Python install for some reason, which is likely to cause problems. Please remove it as well and reinstall if using ``conda`` if necessary. Again, to fully repair the damage, you might need to do a complete clean uninstall and reinstall of Anaconda, so I recommend doing these two things first.

Other than that, please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

If it still isn't working, please describe in detail the circumstances in which the error occurred, and post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Calling for Help section as a comment to this issue, and we'll try to help if we can. Otherwise, your issue will likely have to be closed after one week (7 days). Thanks, and best of luck!

**Comment by 2jl** [comment]
Hi, thanks for the help.
Do all the steps you tell me, but I keep getting error.
1. Make a clean installation of anaconda (for a single user) and update spyder (without using pip) but I kept giving error. That's why I removed markupsafe and reinstalled it, but error kept coming up.
2. I reinstalled the clean anaconda and followed the steps Emergency CPR: Spyder will not launch. But he kept giving me error.
But I keep giving the same error.

As I can perform the next step, it was the only one I could not perform.
"Try installing Spyder into a new conda environment (recommended) or virtualenv, and only installing its dependencies there, and seeing if the issue reoccurs. If it does not, it is likely due to another package installed on your system, particularly if done with pip, which can cause many problems and should be avoided if at all possible."

Thanks for the help

**Comment by CAM-Gerlach** [comment]
Thank you for responding and trying those things.

> As I can perform the next step, it was the only one I could not perform.

What do you mean, could you preform it or not? If so, what happened? If not, why not?

Please post the output of ``conda list`` in the ``base``/``root`` environment and/or the the one you're trying to launch Spyder in. Also, what operating system and version are you using?

Try the procedure listed under "Standard approach to isolating problems" in the guide and report the results (whether/which applications worked). Also, try the technique listed under "Advanced Tricks" and report what you get. Finally, try ``spyder --debug`` from an Anaconda prompt and let us know what you see.

Is there anything otherwise special or unusual about your install, system, or environment? Had any problems before, or is this your first install? If the former, what changed since it worked? Thanks.

**Comment by 2jl** [comment]
Thanks for the help, but in the end I preferred to perform a clean installation on windows. I reinstalled anaconda and when I run spyder I do not get an error, now it's all good
Thank you

**Comment by CAM-Gerlach** [comment]
Thanks excellent news. Thanks for the update, and best of luck with Spyder in the future!
