### ISSUE TITLE
After crashing and rebooting file became all blank (saved file)

### ISSUE THREAD

**Issue by jimmycy93** [spyder-ide/spyder#6686]
## Description

**What steps will reproduce the problem?**

1.  I tried to run a python script which I have saved it previously, then I interrupted it. Then the screen started to freeze and I have to close the file and saving it. My computer crashed and after rebooting it, I see my .py file became all blank while opening it in Spyder or notepad. I have no clue of the reason. 

**What is the expected output? What do you see instead?**
The file is all blank like a new file, but from my folder I can see that it is taking up 12kb of storing space, which doesn't seems like an empty file. 

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
Sorry, we don't know why this problem happens, although it has bee reported several times. However, we're working to implement file backups in Spyder 4.

**Comment by CAM-Gerlach** [comment]
Possible duplicate of #6571 , and mitigated by the implementation of #2111

Sorry for the issue. We recommend you always back up your code, and/or track in in a version control system like ``git``, to prevent this from happening. Even if you didn't have any backups that would allow you to recover it, you may be able to get it back from the automatic Windows File History feature if its turned on. Go to the file, under properties, and look for "Previous Versions" and hopefully windows saved one.

Also, while version control systems like ``git`` are not intended to primarily be backup systems, they certainly can be used as one and would prevent any such situation like this in the future (at most, you might loose any work since your last commit, which shouldn't be too big of an issue if you commit early and often as is recommended). There are also a lot of other benefits as well; I used to think git wasn't worth it just for scripts and data analysis stuff but once I started using it, I can't tell you how many dozens of times its saved my bacon and helped out in so many ways, so I strongly recommend one.

Again, sorry, and best of luck!

**Comment by AlbertSugi** [comment]
IT HAPPENS TO ME TOO!! crazy
