### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by GregRidl** [spyder-ide/spyder#6696]
I am trying to use Jupyter notebook in spyder, I have gone through the install and updates, I have just upgraded my memory to 4gb as the previous solutuion was not enough resorces. I am only using 50% of the new memory when spyder loads, is there a minimum processor speed or hard drive space for this to function correctly?

Spyder work on my system no issues - error comes when trying to load Jupyter Notebook while loading the IDE
Jupyter Notebook runs on my system with no issues (from command prompt)

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. This is a bug tracker for Spyder, not ``spyder-notebook`` which is a separate plugin. Development is currently stopped due to lack of funding at the moment, so unfortunately there may be some issues which will not get fixed for the time being. However, please check over on that repo to see if your issue has been reported, and if not, then consider reporting there. Thanks.
