### ISSUE TITLE
Nothing happens when clicking play

### ISSUE THREAD

**Issue by soulslicer** [spyder-ide/spyder#6726]
## Problem Description

Just installed via Apt-get. When I open a script and click play. Nothing happens. Absolutely no output. What is going on

### What steps will reproduce the problem?

As above.

### What is the expected output? What do you see instead?

Nothing is seen

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Package Versions

* Spyder: 2.2.5
* Python: 2.7
* Qt:
* PyQt: 4
* Operating System: 14.04

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by CAM-Gerlach** [comment]
> Just installed via Apt-get. When I open a script and click play. Nothing happens. Absolutely no output. What is going on

Like you said yourself, nothing.

That's also about as far as we can individually help you, since we have zero information to go on here. However, taking a wild guess, it is virtually certain to be an install problem of some sort. Furthermore, the above version of Spyder is many months out of date (3.2.7 is the current, and 3.2.8 is about to come out), and PyQt4 has been end of lifed for years. Above all, as we state in the Readme, install instructions and documentation, we recommend you use the all-in-one Anaconda distribution unless you're an expert able to solve these problems on your own, we do not have the resources to provide individual post-install support to those using other methods. 

In any case, everything I've told you and much more in the way of fixing these sorts of problems is laid out step by step in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), (which among many other places was highlighted in all caps at the top of the issue you just submitted), the first resource of several you should look to to solve your problem faster _before_ submitting an issue. Specifically, consult the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

**Comment by ccordoba12** [comment]
> Spyder: 2.2.5

This release is like 5 years old! Please download Anaconda and use a more up to date version.

**Comment by soulslicer** [comment]
What about the pip version..is that more up to date?

**Comment by ccordoba12** [comment]
Yes, but we don't give support for pip installations because they are for experts. If you want a smooth and pain free experience, please use Anaconda.

**Comment by soulslicer** [comment]
That's unfortunate as I am not allowed to install that here sadly. I did try the pip version, but it throws me an error saying QtSvg is missing, despite it being installed

**Comment by ccordoba12** [comment]
Anaconda can be installed in your home directory. If it's too big for you, you can also try with Miniconda.

**Comment by CAM-Gerlach** [comment]
> > Spyder: 2.2.5

> This release is like 5 years old! Please download Anaconda and use a more up to date version

I read that as 3.2.5, haha...

> Anaconda can be installed in your home directory

Indeed; no admin rights required. That's exactly how I use it and Spyder every day on my work machine so I can manage all aspects of my installation, though I also got my IT people to make it available to everyone via their software distribution system as an all-users install.
