### ISSUE TITLE
Have pptx installed with Anaconda3 but could not locate module pptx

### ISSUE THREAD

**Issue by minh-nguyen-va** [spyder-ide/spyder#6751]
sample code:
```
from pptx import Presentation
prs = Presentation()
title_slide_layout = prs.slide_layouts[0]
slide = prs.slides.add_slide(title_slide_layout)
title = slide.shapes.title
subtitle = slide.placeholders[1]
title.text = "Hello, World!"
subtitle.text = "python-pptx was here!"
prs.save('test.pptx')
```
------------- 
error message:
from pptx import Presentation
ModuleNotFoundError: No module named 'pptx'

**Comment by CAM-Gerlach** [comment]
This error appears to have nothing to do with Spyder, but rather your own code. Therefore, this will be closed. You probably don't have ``pptx`` installed or something is messed up with your installation. Try ``conda install pptx`` or, if that doesn't work, ``pip install pptx`` and try again. Thanks.

**Comment by minh-nguyen-va** [comment]
you are wrong... it has nothing to with my code...but with the version of
spyder...
it works for me now

**Comment by CAM-Gerlach** [comment]
> you are wrong... 

Just a gentle tip: If you want a volunteer like myself to take the time and effort out of the few free hours of their day to help you fix your problem, that probably isn't the best thing to say to them...

> it works for me now

Okay; good to hear. Is there an apparent reason it started working? Perhaps one that might help provide some evidence for the otherwise unsupported assertion that this has something to do with Spyder? Perhaps it is related to #5299 in some fashion? Other than that, every issue we've had that I'm aware of involving modules not being imported properly had to do with either user error or something wrong with the installation, neither of which we have any control over. Does this happen in ``qtconsole`` as well?

**Comment by minh-nguyen-va** [comment]
ok

**Comment by minh-nguyen-va** [comment]
i will explain what works and does not... it has nothing to do with the
coding but the versions installed.. i found that out because i have 3
systems with spyder installed in thespan of 2 years

thanks

**Comment by CAM-Gerlach** [comment]
> i will explain what works and does not...

Okay...? I don't see your explanation, sorry.

In lieu of that, you can just try the same command in ``qtconsole`` (type ``jupyter qtconsole`` from the Anaconda prompt/command line to launch it, then run the ``import pptx`` and report whether you see the same error.

>  the versions installed.. 

The versions of what, exactly? Please be clear, detailed, and explicit, or we won't be able to do much to help your problem if we can't understand it.

**Comment by CAM-Gerlach** [comment]
> Thanks for responding to my question and sorry for being 'uncool' to you.

Don't worry, we all make mistakes, especially in languages other than our native tongue.

**Comment by minh-nguyen-va** [comment]
You are very gracious.

Thanks

Minh
