### ISSUE TITLE
Potential documentation clarifications regarding IPython/Jupyter notebook support?

### ISSUE THREAD

**Issue by westurner** [spyder-ide/spyder#6774]
What support does Spyder have for Jupyter Notebook .ipynb files?
- I see that nbconvert is a dependency?

What support does Spyder have for .py files with ``# In[0]`` prompts? (What are these called?)
- Ctrl-Return -- Run cell
- Shift-Return -- Run cell and advance

A page in the docs to link to would be helpful in regards to pandas-dev/pandas#20345: https://github.com/westurner/pandas/blob/master/doc/source/ecosystem.rst#spyder

**Comment by CAM-Gerlach** [comment]
I'm not convinced that major substantive changes are really necessary at this point, but certainly something to consider, and we'd certainly be willing to at least look at a PR with proposed changes. FYI, the documentation is currently being moved to a separate repo, so if you are going to do that, best to wait until that's done (perhaps a few days to a week, depending on my schedule?)

> What support does Spyder have for Jupyter Notebook .ipynb files?

Not directly supported inside core Spyder, but we do have a plugin that does so, Spyder-Notebook, on which further development is on hold right now due to our funding.

> What support does Spyder have for .py files with ``# In[0]`` prompts? (What are these called?)

Are you confusing the interactive IPython console/Jupyter notebooks with code cells? The former are present in interactive IPython sessions and in rendered Jupyter notebooks, while the latter are ``# %%`` markers in the source code that delineate different chunks of code to be navigated and run as a unit if desired, by e.g. the commands you mentioned.

> A page in the docs to link to would be helpful in regards to pandas-dev/pandas#20345: https://github.com/westurner/pandas/blob/master/doc/source/ecosystem.rst#spyder

We already discuss the Variable Explorer in some detail on several pages, including [its dedicated one](https://pythonhosted.org/spyder/variableexplorer.html), though like much of our docs it could certainly used being fleshed out more.

@ccordoba12 , opinion?

**Comment by westurner** [comment]
> Not directly supported inside core Spyder, but we do have a plugin that does so, Spyder-Notebook, on which further development is on hold right now due to our funding.

https://github.com/spyder-ide/spyder-notebook

**https://opencollective.com/spyder#support**

> The former are present in interactive IPython sessions and in rendered Jupyter notebooks, while the latter are ``# %%`` markers in the source code that delineate different chunks of code to be navigated and run as a unit if desired, by e.g. the commands you mentioned.

What is the format for these ``# %%`` markers and where in the docs should this be explained? It's super useful.

**Comment by CAM-Gerlach** [comment]
> https://github.com/spyder-ide/spyder-notebook

> https://opencollective.com/spyder#support (<-- Donations)

Um, okay...? I am quite aware of those URLs, thank you; I occasionally ~~shill~~ post the latter when appropriate.

Also, you are aware you can just do [Donations ](https://opencollective.com/spyder#support)?

> What is the format for these ``# %%`` markers 

Exactly what you just typed, on a new line, to define the border of a cell. Or, more conventionally; ``#%%``; I'm just used to the former for some reason.

> and where in the docs should this be explained? It's super useful.

It already _is_ explained in the docs, and in fact even has its [own section](https://pythonhosted.org/spyder/editor.html#how-to-define-a-code-cell).

Therefore, I'm not sure what further remains of substance in this issue report that wasn't already addressed in the docs, but I await @ccordoba12 's more authoritative opinion as to whether anything need be done.

**Comment by westurner** [comment]
On Friday, March 16, 2018, C.A.M. Gerlach <notifications@github.com> wrote:

> https://github.com/spyder-ide/spyder-notebook
>
> https://opencollective.com/spyder#support (<-- Donations)
>
> Um, okay...? I am quite aware of those URLs, thank you; I occasionally
> shill post the latter when appropriate.
>
> Also, you are aware you can just do Donations
> <https://opencollective.com/spyder#support>?
>
Yes, but then I would need to hover over the donations link to determine
how you're accepting donations.


> What is the format for these # %% markers
>
> Exactly what you just typed, on a new line, to define the border of a
> cell. Or, more conventionally; #%%; I'm just used to the former for some
> reason.
>
> and where in the docs should this be explained? It's super useful.
>
> It already *is* explained in the docs, and in fact even has its own
> section
> <https://pythonhosted.org/spyder/editor.html#how-to-define-a-code-cell>.
>
Thanks for the link. So, ``# %%`` matches ``# In[0]:`` but not ``# this is
a comment``?

> Therefore, I'm not sure what further remains of substance in this issue
> report that wasn't already addressed in the docs, but I await @ccordoba12
> <https://github.com/ccordoba12> 's more authoritative opinion as to
> whether anything need be done.
>
I'm trying to help rep Spyder with the linked pandas ecosystem.rst doc; so
a page describing spyder-notebook, code cell support, and ``jupyter convert
--to python nb.ipynb`` for code cells that that paragraph could link to
would be helpful.

Is spyder-notebook a separate project for a reason?

**Comment by CAM-Gerlach** [comment]
> Yes, but then I would need to hover over the donations link to determine how you're accepting donations.

Hmm. I suppose one could infer _something_  from the URL, but if they are so inclined, hovering is essentially instantaneous, and in order to see anything substantive they'd need to visit there anyway. On the other hand, a bare link takes up excessive space and attention, prevents the layout from looking clean, polished, streamlined and professional, is obtrusive, and just plain ugly. A minuscule delay for the fraction of users interested in gleaning a modest amount of information from the link target without visiting simply doesn't seem worth these drawbacks, and it seems professional designers across the web overwhelmingly agree, considering that inline links become overwhelmingly dominant as one considers better funded and higher-profile sites.

> Thanks for the link. So, ``# %%`` matches ``# In[0]:`` but not ``# this is a comment``?

Sure; its a really useful feature that I couldn't see myself living without, so glad I could help you discover it. However, I'm sorry; I'm not clear what your referring to. ``# %%`` is just the literal ``# %%`, its as simple as that. As our linked doc states, we also support the IPython notebook separator ``# <codecell>`` among others. Maybe you're just overthinking it? :) 

By way of example.

```
#%% This is a cell

some()
code()
here()

#%% This is another cell

more()
code()
```

> I'm trying to help rep Spyder with the linked pandas ecosystem.rst doc

We appreciate your support; especially now that we currently are trying to find a new source of funding, and have to up our game to compete with the marketing might of more corporate alternatives (e.g. VSCode, PyCharm, etc), we need visibility more than ever.

On the linked doc, the link for Spyder is many years out of date; it should be to the Github here, or our new proper website that we're just getting off the ground. If you could fix that as part of your PR, that would be great.

> so a page describing spyder-notebook

Hmm, while we certainly could at least mention a list of plugins somewhere, I'm not sure its appropriate to do now that we can't provide official support for them for the time being, and development is stopped in early alpha. That's a separate plugin with its own docs, still in early alpha (and is not fully stable), and currently has major work suspended due to the funding shortage, so not sure its worth covering especially in the main Spyder IDE docs right now, especially considering we are already getting maybe a dozen issues a month here just having to do with plugin, esp. notebook related problems that we simply don't have the resources to fix at the moment. I.e. not sure it make sense to air our dirty laundry, even if the clothing article in question is a sought-after fashion.

> code cell support,

Again, this already exists as its own linked section/subpage, and is a quite simple/straightforward feature so there isn't too much more to say relative to what exists, especially compared with the much greater room for improvement in our docs in numerous other areas.

 and ``jupyter convert --to python nb.ipynb``

I don't see how this command has anything to do with Spyder; I'm not sure why we'd document functionality that isn't anywhere in our codebase or any project directly connected to it. Is there something I'm missing here?

>   Is spyder-notebook a separate project for a reason?

Yes.

Specifically, because just like ``spyder-terminal``, ``spyder-reports``, ``spyder-unittest``, ``spyder-vim``, etc., it is a separate plugin for the Spyder IDE, not included with core Spyder, and in an alpha stage of development currently.
