### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by 4sf12ec079** [spyder-ide/spyder#6777]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Rakhesh\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 849, in keyPressEvent
    self.remove_item()
  File "C:\Users\Rakhesh\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 936, in remove_item
    keys = [ self.model.keys[idx_row] for idx_row in idx_rows ]
  File "C:\Users\Rakhesh\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 936, in <listcomp>
    keys = [ self.model.keys[idx_row] for idx_row in idx_rows ]
IndexError: list index out of range

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. Please describe in detail the circumstances in which the error occurred, and post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Spyder Troubleshooting Guide as a comment to this issue, and we'll try to help if we can. Otherwise, your issue will likely have to be closed after one week (7 days). 

Also, if it occurs again, please reference [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) section for some basic steps to try to fix it or at least narrow it down for us. Thanks, and best of luck!

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.
