### ISSUE TITLE
I got this error while launching `spyder3`. Can you please elaborate on this error?

### ISSUE THREAD

**Issue by HridayThakkar** [spyder-ide/spyder#6807]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

    module = _import_module_from_path(module_name, plugin_path)
    module = spec.loader.load_module(module_name)
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 262, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    from .pylint import Pylint as PLUGIN_CLASS
    from .widgets.pylintgui import PylintWidget
    import pylint
    from .__pkginfo__ import version as __version__
    from setuptools import __version__ as setuptools_version
ModuleNotFoundError: No module named 'setuptools'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)

```

**Comment by ccordoba12** [comment]
You need to install or update setuptools with

    pip install -U setuptools

**Comment by HridayThakkar** [comment]
@ccordoba12 Thanks for your prompt advice and response. 

It looks like I've already performed this action for both pip and pip3 but the error still remains. Any thoughts? 
➜  ~ pip install -U setuptools
Requirement already up-to-date: setuptools in /Library/Python/2.7/site-packages
~
➜  ~ pip3 install -U setuptools
Requirement already up-to-date: setuptools in ./Library/Python/3.6/lib/python/site-packages

**Comment by ccordoba12** [comment]
@HridayThakkar, the main problem you have is that you're trying to install Spyder in your system Python. This is a really bad decision because your system Python is used by macOS to perform critical operations, so you should never touch it.

Now that you did it, you should try to restore it to its original state or don't ever touch it again.

Besides that, this is as far as I can get with my help. Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations with pip, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.

**Comment by HridayThakkar** [comment]
@ccordoba12 Noted. Thanks so much for your advice!

**Comment by ccordoba12** [comment]
Thanks for understanding and I hope you have no problems with Anaconda, but if you do, please open a new issue.

**Comment by HridayThakkar** [comment]
@ccordoba12  In fact, so far, I was accessing Spyder via Anaconda. I will open a new issue.
