### ISSUE TITLE
Window layouts option unclickable

### ISSUE THREAD

**Issue by cocoaaa** [spyder-ide/spyder#6818]
## Problem Description
Under the menu `View`, `Window Layouts` is always grayed out, and I cannot click it to select other stored layout options. It worked the first time I installed spyder with `conda`, but after a certain point that I cannot pinpoint to, it is always unclickable. I updated spyder several times with conda. At this point, I cannot figure out how to make this menu active or what may have caused this issue..

![image](https://user-images.githubusercontent.com/8037983/37749193-178dfc76-2d44-11e8-864b-1812d3346a12.png)

### What steps will reproduce the problem?

1. 
2. 
3. 

### What is the expected output? What do you see instead?
I would like to be able to select the window layout menu.

## Package Versions

* Spyder: 3.2.8
* Python: 3.6.4
* Qt: 5.6.2
* PyQt: 5.6.0
* Operating System: MacOS High Sierra 10.13.3

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at it in our next version.

**Comment by csabella** [comment]
On the screenprint above, I noticed that 'Panes' and 'Toolbars' is also grayed out, i.e. all the menu options that have submenus.  Do other menus have the same issue, such as 'Interactive Tours' under 'Help' or 'Show todo list' under 'Source'?

**Comment by CAM-Gerlach** [comment]
@cocoaaa Try unchecking "Lock Panes" in the menu you showed. It apparently doesn't do anything on either of my (Windows) machines, but perhaps it is working on macOS, as intended.

If not, there is always a chance it could have something to do with weirdness between High Sierra and Qt 5.6.2, since the latter version is rather old and doesn't fully support the former.

Finally, you could try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

Best of luck!

**Comment by cocoaaa** [comment]
@csabella  The problem goes away if I restart spyder.  However after some time using the program, it stops working.  And, other menus with submenus have the same problem:

![image](https://user-images.githubusercontent.com/8037983/38147088-a4e2a348-3405-11e8-85c0-cbc8a51eed9d.png)
![image](https://user-images.githubusercontent.com/8037983/38147112-b61d838a-3405-11e8-9bd1-1d6485535888.png)
![image](https://user-images.githubusercontent.com/8037983/38147126-c344c762-3405-11e8-8e3c-4a6134f37ac5.png)
![image](https://user-images.githubusercontent.com/8037983/38147133-cd355e8a-3405-11e8-9ee3-63fe7f82a3a6.png)
![image](https://user-images.githubusercontent.com/8037983/38147147-d7cd18a6-3405-11e8-85b8-7757c9c2d76d.png)

**Comment by cocoaaa** [comment]
@CAM-Gerlach Thank you for the pointers!  I tried unchecking "Lock Panes" but it didn't help with the problem.

**Comment by ccordoba12** [comment]
@cocoaaa, this could be a problem with Qt, the graphical library used by Spyder, and macOS. Anaconda is the process of updating Qt, so let's wait until that happens to see if your problem is solved by that.

**Comment by cocoaaa** [comment]
@ccordoba12 Sure, thank you.

**Comment by goanpeca** [comment]
@cocoaaa Qt has been updated for some time now. Do you still have the issue?

Thanks!
