### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by larrybtagao** [spyder-ide/spyder#6828]
Spyder3 on Windows 10 Enterprise. On accessing any object method/parameter using dot notation, it crashes 

Example:
import requests
requests. --> Crashes at this exact moment

**Comment by ccordoba12** [comment]
> On accessing any object method/parameter

Accessing how? What do you mean by this?

> it crashes

How? What's the error?

Finally, how did you install Spyder?

**Comment by CAM-Gerlach** [comment]
Most likely an install issue, as I use the latest version of Spyder (3.2.8) on Windows 10 Enterprise every day, and have never had anything like this happen. Please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

If it still isn't working, please describe in detail the circumstances in which the error occurred, and post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Calling for Help section as a comment to this issue, and we'll try to help if we can. Otherwise, your issue will likely have to be closed after one week (7 days). Thanks, and best of luck!

**Comment by larrybtagao** [comment]
I did those troubleshooting steps in Spyder Troubleshooting Guide and it's still the same. I've also reinstalled a few times already. Technically, it doesn't really crash, but it throws the below error when trying to use intellisense. As an example:

import requests
r = requests. --> As soon as I hit the dot ( . )  after requests, it throw an error

![spyder](https://user-images.githubusercontent.com/19632636/37908317-77ee107a-313a-11e8-8d42-957a44c749b9.JPG)

**Comment by ccordoba12** [comment]
> Well, we don't have any such named feature. This is Spyder, not VSCode...

Intellisense is another name for code completion.

**Comment by CAM-Gerlach** [comment]
> Intellisense is another name for code completion.

I figured that's what they were referring to. However, Intellisense is a Microsoft trademark, referring specifically to suite of features in VisualStudio and VSCode, and I've not really seen it used outside that context. It would be akin to calling completion, introspection etc. ``jedi`` in VSCode, from what I understand.

**Comment by CAM-Gerlach** [comment]
@larrybtagao If you could please provide the requested information within the next couple days, we'll see what we can do about your problem. Otherwise, this issue will have to be closed, as we don't have enough information to identify and resolve your issue. Thanks.

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.
