### ISSUE TITLE
Can't launch Spyder on OS

### ISSUE THREAD

**Issue by mike820808** [spyder-ide/spyder#6867]
## Problem Description

When I click the launch button, a window will jump out with:

```
Traceback (most recent call last):
File "/Users/richard/anaconda3/bin/spyder", line 7, in 
from spyder.app.start import main
File "/Users/richard/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 27, in 
from spyder.config.main import CONF
File "/Users/richard/anaconda3/lib/python3.6/site-packages/spyder/config/main.py", line 22, in 
from spyder.config.user import UserConfig
File "/Users/richard/anaconda3/lib/python3.6/site-packages/spyder/config/user.py", line 26, in 
from spyder.utils.programs import check_version
File "/Users/richard/anaconda3/lib/python3.6/site-packages/spyder/utils/programs.py", line 18, in 
import subprocess
File "/Users/richard/anaconda3/lib/python3.6/subprocess.py", line 136, in 
import _posixsubprocess
ImportError: dlopen(/Users/richard/anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so, 2): Symbol not found: __Py_set_inheritable_async_safe
Referenced from: /Users/richard/anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so
Expected in: flat namespace
in /Users/richard/anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so

```

## Package Versions

* Spyder:3.2.8
* Python: 3.6.5 
* Qt:5.6.2
* PyQt:5.6.0
* Operating System:Mac OS High Sierra 10.13.3

dependencies:
    chardet >=2.0
    cloudpickle
    jedi >=0.9
    nbconvert
    numpydoc
    pickleshare
    psutil
    pycodestyle
    pyflakes
    pygments >=2.0
    pylint
    pyqt
    python >=3.6,<3.7.0a0
    python.app
    pyzmq
    qtawesome >=0.4.1
    qtconsole >=4.2
    qtpy >=1.2.0
    rope >=0.9.4
    sphinx

**Comment by mike820808** [comment]
Sorry, when I downgrade the python to 3.6.4, it solves the issue.

**Comment by CAM-Gerlach** [comment]
Duplicate of #6876 as well. Glad you resolved it.

**Comment by shangyan0517** [comment]
try 'conda update --all'

**Comment by CAM-Gerlach** [comment]
@shangyan0517 I appreciate you trying to help. However, this issue is closed, is a duplicate, a year old, the OP has stated it is resolved, and the correct solution is ``conda update python python.app`` as is stated on the main thread linked above.

Furthermore, the command you posted, which indiscriminately updates every single package in the current environment (more than likely ``base``) to the latest versions, has a high chance of breaking things due to mutual incompatibilities that have not yet been tested and validated and is not recommended by Anaconda (to the point where removing that option entirely has been considered), and should never be used without a high level of expertise or being explicitly told to do so by someone with it. Therefore, I have modified your comment to ensure other users are not led astray by it.

Therefore, in the future, please post such solutions (preferably with a proper explanation rather than simply a bare command, and prefixing it by stating you're suggesting it simply because it worked in your case as a Spyder user) on the main issue, and only if it is not already closed and resolved with an authoritative solution, and if you're very sure the command in question is not likely to be harmful (as this one is). Thanks.
