### ISSUE TITLE
Include Matplotlib in Help > Dependencies

### ISSUE THREAD

**Issue by hiccup7** [spyder-ide/spyder#6887]
This will give users more helpful info about their installation and improve Spyder problem reports when users paste their installed dependencies list.

## Package Versions
* Spyder: 3.2.8

**Comment by CAM-Gerlach** [comment]
@ccordoba12 If you get to it first, I've been meaning to do this for a long time but can we sort our dependency list alphabetically, and make the order consistent between the dialog/manually copyed dep list and the Report Error Help Menu item/automatic error report? This has been bugging me for a while and makes tracking down issues due to specific package versions (or ruling them out) that much harder.

**Comment by ccordoba12** [comment]
> can we sort our dependency list alphabetically, and make the order consistent between the dialog/manually copyed dep list and the Report Error Help Menu item/automatic error report?

This is for another issue, and I don't have plans to solve it for now.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Okay, I'll try to get to it at some point—its been high in my queue due to how annoying it has been, but keeps getting bumped by more pressing matters.

**Comment by ccordoba12** [comment]
@dalthviz, an easy one for you. Please add the dependency in `plugins/ipythonconsole.py`
