### ISSUE TITLE
OSError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by Pandolph** [spyder-ide/spyder#6901]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 944, in set_working_directory
    refresh_console=False)
  File "/anaconda3/lib/python3.6/site-packages/spyder/plugins/workingdirectory.py", line 296, in chdir
    self.refresh_plugin()
  File "/anaconda3/lib/python3.6/site-packages/spyder/plugins/workingdirectory.py", line 204, in refresh_plugin
    self.save_wdhistory()
  File "/anaconda3/lib/python3.6/site-packages/spyder/plugins/workingdirectory.py", line 234, in save_wdhistory
    encoding.writelines(text, self.LOG_PATH)
  File "/anaconda3/lib/python3.6/site-packages/spyder/utils/encoding.py", line 236, in writelines
    return write(os.linesep.join(lines), filename, encoding, mode)
  File "/anaconda3/lib/python3.6/site-packages/spyder/utils/encoding.py", line 228, in write
    textfile.write(text)
OSError: [Errno 28] No space left on device

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
We'll catch the error and show a warning in our next release, but you need to delete some stuff for Spyder to be able to save your files.

**Comment by CAM-Gerlach** [comment]
@ccordoba12  To note, this is also a duplicate of #6495 which you previously decided to close due it being user error and not a Spyder one.

**Comment by ccordoba12** [comment]
Let's address this in 3.3. I think it's valid in Linux clusters, where people has a very limited quota, most of it probably filled with Anaconda itself.

**Comment by CAM-Gerlach** [comment]
Gotcha, thanks.

**Comment by andersonwinkler** [comment]
I am experiencing the exact problem trying to install Spyder on a RHEL 7.4 machine. There is plenty of disk space in all mounted filesystems and there are no quotas in place. The splash screen appears, then it crashes:

```
[REDACTED]@[REDACTED]:~ $ spyder3 
[35407:35407:0603/163727.596738:FATAL:credentials.cc(137)] Check failed: error == EPERM || error == EUSERS || error == EINVAL || error == ENOSYS. : No space left on device
#0 0x7fd5347c5d1e <unknown>
#1 0x7fd5347d7a5e <unknown>
#2 0x7fd5347d7ce9 <unknown>
#3 0x7fd53548ffdf <unknown>
#4 0x7fd535490954 <unknown>
#5 0x7fd5344326c5 <unknown>
#6 0x7fd5340eab40 <unknown>
#7 0x7fd5340ee1b2 <unknown>
#8 0x7fd533ee812a <unknown>
#9 0x7fd533ee9775 <unknown>
#10 0x7fd533ed9749 <unknown>
#11 0x7fd533ed9a6e QtWebEngineCore::WebContentsAdapter::WebContentsAdapter()
#12 0x7fd53a1f8e11 <unknown>
#13 0x7fd53a1f9964 QWebEnginePage::QWebEnginePage()
#14 0x7fd53a4389d9 sipQWebEnginePage::sipQWebEnginePage()
#15 0x7fd53a438b92 init_type_QWebEnginePage
#16 0x7fd53ca0ca74 sipSimpleWrapper_init
#17 0x7fd551723982 <unknown>
#18 0x7fd5516d3e10 _PyObject_FastCallDict
#19 0x7fd55177dfac <unknown>
#20 0x7fd5517722a7 _PyEval_EvalFrameDefault
#21 0x7fd55177f09a _PyFunction_FastCallDict
#22 0x7fd5516d3e8e _PyObject_FastCallDict
#23 0x7fd5516d3fa1 _PyObject_Call_Prepend
#24 0x7fd5516d3c13 PyObject_Call
#25 0x7fd551726555 <unknown>
#26 0x7fd551723982 <unknown>
#27 0x7fd5516d3e10 _PyObject_FastCallDict
#28 0x7fd55177dfac <unknown>
#29 0x7fd5517722a7 _PyEval_EvalFrameDefault
#30 0x7fd55177f09a _PyFunction_FastCallDict
#31 0x7fd5516d3e8e _PyObject_FastCallDict
#32 0x7fd5516d3fa1 _PyObject_Call_Prepend
#33 0x7fd5516d3c13 PyObject_Call
#34 0x7fd551726555 <unknown>
#35 0x7fd551723982 <unknown>
#36 0x7fd5516d3e10 _PyObject_FastCallDict
#37 0x7fd55177dfac <unknown>
#38 0x7fd5517722a7 _PyEval_EvalFrameDefault
#39 0x7fd55177f09a _PyFunction_FastCallDict
#40 0x7fd5516d3e8e _PyObject_FastCallDict
#41 0x7fd5516d3fa1 _PyObject_Call_Prepend
#42 0x7fd5516d3c13 PyObject_Call
#43 0x7fd551726555 <unknown>
#44 0x7fd551723982 <unknown>
#45 0x7fd5516d3e10 _PyObject_FastCallDict
#46 0x7fd55177dfac <unknown>
#47 0x7fd5517722a7 _PyEval_EvalFrameDefault
#48 0x7fd55177d2b2 <unknown>
#49 0x7fd55177f18c _PyFunction_FastCallDict
#50 0x7fd5516d3e8e _PyObject_FastCallDict
#51 0x7fd5516d3fa1 _PyObject_Call_Prepend
#52 0x7fd5516d3c13 PyObject_Call
#53 0x7fd551726555 <unknown>
#54 0x7fd551723982 <unknown>
#55 0x7fd5516d3e10 _PyObject_FastCallDict
#56 0x7fd55177dfac <unknown>
#57 0x7fd5517722a7 _PyEval_EvalFrameDefault
#58 0x7fd55177d2b2 <unknown>
#59 0x7fd55177dc9a <unknown>
#60 0x7fd55177df23 <unknown>
#61 0x7fd5517722a7 _PyEval_EvalFrameDefault

Aborted (core dumped)
[REDACTED]@[REDACTED]:~ $ df
Filesystem                              1K-blocks        Used  Available Use% Mounted on
/dev/mapper/rhel-root                   123723328    23224796   94190692  20% /
devtmpfs                                264011744           0  264011744   0% /dev
tmpfs                                   264027940       61896  263966044   1% /dev/shm
tmpfs                                   264027940      167784  263860156   1% /run
tmpfs                                   264027940           0  264027940   0% /sys/fs/cgroup
/dev/sda2                                  920952      221864     635088  26% /boot
/dev/sda1                                  535512        9976     525536   2% /boot/efi
/dev/mapper/rhel-opt                    123719232    47199600   70212000  41% /opt
tmpfs                                    52805588          20   52805568   1% /run/user/1000
/dev/mapper/[REDACTED]     10652622752  3531471444 7013760744  34% /home
/dev/mapper/[REDACTED]  4474029952  1538685272 2890231132  35% /[REDACTED]/[REDACTED]
tmpfs                                    52805588           4   52805584   1% /run/user/986
tmpfs                                    52805588          16   52805572   1% /run/user/200210968
tmpfs                                    52805588          28   52805560   1% /run/user/4001
tmpfs                                    52805588          16   52805572   1% /run/user/200227514
tmpfs                                    52805588          16   52805572   1% /run/user/200212853
[REDACTED]:/[REDACTED]/[REDACTED]                 14346364928 13184329728 1016313856  93% /[REDACTED]/[REDACTED]
tmpfs                                    52805588          16   52805572   1% /run/user/200053226
tmpfs                                    52805588          16   52805572   1% /run/user/200200151
mapbackup1:/mnt/workingdata4           5379586560  2644754944 2625524224  51% /[REDACTED]/[REDACTED]/[REDACTED]/workingdata4
tmpfs                                    52805588          20   52805568   1% /run/user/200200206
tmpfs                                    52805588          16   52805572   1% /run/user/200195119
[REDACTED]:/[REDACTED]/[REDACTED]                     9650211840  9119920128  432293888  96% /[REDACTED]/[REDACTED]
[REDACTED]:/[REDACTED]/[REDACTED]/rawdata              206294016    12087296  192109568   6% /[REDACTED]/[REDACTED]/rawdata
[REDACTED]:/[REDACTED]/[REDACTED]/structural          2786599936  2466276352  292031488  90% /[REDACTED]/[REDACTED]/structural
```

**Comment by CAM-Gerlach** [comment]
@andersonwinkler 

> I am experiencing the exact problem trying to install Spyder on a RHEL 7.4 machine.

This seems very unlikely to be the "exact problem", since the error message is different, the circumstances are different, the traceback is different, the error location is very different, the error appears to be in Qt C code rather than Spyder's pure Python codebase, etc. In any case, as you can see the fix for this problem was already committed to our codebase, so if it is indeed the "exact problem" you can just run Spyder from the latest github source and the problem will be resolved.

Most likely, however, this is a non-Spyder-related  install issue specific to your machine, quite possibly the result of using an install method other than that we recommend—we aren't generally able to provide individual support for install issues for non-Anaconda installs, due to the number of tricky issues that can result. Considering you are using RHEL, it is also quite likely the version it installed is very out of date, without the benefit of months or quite possibly *years* worth of fixes and improvements. Therefore, you should install the current release via the latest version of Anaconda or Miniconda instead (``conda install spyder``), running under Python 3.6/x64/Qt5 if at all possible (although we still support legacy Python 2.7 and 3.5 for now, there's no reason to use them unless you need a specific package that doesn't run under Python 3.6).

You can also try the other steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues, to see if you can fix your problem on your own. Thanks, and best of luck!

**Comment by andersonwinkler** [comment]
Thanks for the quick feedback. Right after I wrote "exact same problem" I realised the issue end edited the post.

The install method is "pip3.6 install spyder". The system is up to date.

It's unfortunate in my opinion that conda is now favoured over pip, but whatever, will give it a try.

Enjoy the weather!

**Comment by CAM-Gerlach** [comment]
> Thanks for the quick feedback. Right after I wrote "exact same problem" I realised the issue end edited the post.

Ah, sorry—it must not have updated for me before I submitted my post.

> The install method is "pip3.6 install spyder". The system is up to date.

Okay, that should indeed get you the latest version—many users install the versions available through their downstream package managers, which often lag far behind the current Spyder release, sometimes by years or more. Are you using a virtualenv/venv to install it in an isolated environment, to avoid conflicts with your system python and other packages? That can help avoid many issues, if you want to stick with ``pip`` and try to work through these problems with our troubleshooting guide and your own experience.

> It's unfortunate in my opinion that conda is now favoured over pip

We do our best to support both, and we provide official wheels, fix any bugs we can from our side in them, and run our CIs using both ``pip`` and ``conda``; also, several of the developers install and run Spyder and their other packages via ``pip``. However, since we're a small team of unfunded volunteers stretched between maintaining Spyder 3, developing Spyder 4, developing and maintaining over a half-dozen plugins, other related projects, and responding to sometimes dozens of user issue reports per day just on Github, plus our Google Group/mailing list, Stack Overflow, Gitter public chat, social media and more, we have to prioritize our limited resources, and since most ``conda`` tends to be a much more reliable install method overall and avoids the many user/environment/machine specific issues with ``pip`` and compiled packages that we can't really control from the Spyder side of things, we only recommend it for users able to resolve such issues, as most likely there isn't anything we can really do about them anyway. Thanks for being willing to try ``conda``, and best of luck!

> Enjoy the weather!

Thanks...being an atmospheric scientist, I do love watching storms which we get here quite regularly in the summer now.

**Comment by andersonwinkler** [comment]
Perfect, thanks. Understood the reasons for conda. I'll try a few more things to see if it works with pip, and if not, will switch over (perhaps also drop various other Pythons installed... though they aren't supposed to be conflicting).

> being an atmospheric scientist, I do love watching storms

I guessed that. Have fun :)

Thanks again!

**Comment by andersonwinkler** [comment]
Ok, I've removed completely pythons 3.4 and 3.6 that were in the system (from RHEL and EPEL repositories) and installed Anaconda. Still it crashes. Interestingly, in two other machines, both with same software, and one of them with same hardware, Spyder works just fine.

The only "special" thing about storage in this machine is that it has the logical volumes attached directly to it. This includes the /home directory, which is mounted as a local filesystem. The other two see the same filesystem via NFS (i.e., served from this one that is giving the error).

Should I open a separate thread, or this should be unrelated to Spyder? Thanks.

```
[REDACTED]@[REDACTED]:~ $ /opt/anaconda3/5.2.0/bin/spyder 
[59046:59046:0603/194125.689576:FATAL:credentials.cc(137)] Check failed: error == EPERM || error == EUSERS || error == EINVAL || error == ENOSYS. : No space left on device
#0 0x7fcec909718e <unknown>
#1 0x7fcec90a9832 <unknown>
#2 0x7fcec90aabac <unknown>
#3 0x7fcec9a6f21b <unknown>
#4 0x7fcec9a6f5bc <unknown>
#5 0x7fcec8e13897 <unknown>
#6 0x7fcec8bbd6ce <unknown>
#7 0x7fcec8bc1461 <unknown>
#8 0x7fcec8a530d0 <unknown>
#9 0x7fcec8a532a6 <unknown>
#10 0x7fcec8a4a255 <unknown>
#11 0x7fcec8a4a306 QtWebEngineCore::WebContentsAdapter::WebContentsAdapter()
#12 0x7fcecd316866 <unknown>
#13 0x7fcecd3145b4 <unknown>
#14 0x7fcecd314742 QWebEnginePage::QWebEnginePage()
#15 0x7fcecd346369 sipQWebEnginePage::sipQWebEnginePage()
#16 0x7fcecd3464f2 init_type_QWebEnginePage
#17 0x7fced1d11f04 <unknown>
#18 0x5602c7f4f9b7 <unknown>
#19 0x5602c7ebfd7b <unknown>
#20 0x5602c7f4f7ce <unknown>
#21 0x5602c7f71cba <unknown>
#22 0x5602c7f49d7b <unknown>
#23 0x5602c7ebff5f <unknown>
#24 0x5602c7ec4a03 <unknown>
#25 0x5602c7ebf99e <unknown>
#26 0x5602c7f1c02b <unknown>
#27 0x5602c7f4f9b7 <unknown>
#28 0x5602c7ebfd7b <unknown>
#29 0x5602c7f4f7ce <unknown>
#30 0x5602c7f71cba <unknown>
#31 0x5602c7f49d7b <unknown>
#32 0x5602c7ebff5f <unknown>
#33 0x5602c7ec4a03 <unknown>
#34 0x5602c7ebf99e <unknown>
#35 0x5602c7f1c02b <unknown>
#36 0x5602c7f4f9b7 <unknown>
#37 0x5602c7ebfd7b <unknown>
#38 0x5602c7f4f7ce <unknown>
#39 0x5602c7f71cba <unknown>
#40 0x5602c7f49d7b <unknown>
#41 0x5602c7ebff5f <unknown>
#42 0x5602c7ec4a03 <unknown>
#43 0x5602c7ebf99e <unknown>
#44 0x5602c7f1c02b <unknown>
#45 0x5602c7f4f9b7 <unknown>
#46 0x5602c7ebfd7b <unknown>
#47 0x5602c7f4f7ce <unknown>
#48 0x5602c7f71cba <unknown>
#49 0x5602c7f48dae <unknown>
#50 0x5602c7f49e1b <unknown>
#51 0x5602c7ebff5f <unknown>
#52 0x5602c7ec4a03 <unknown>
#53 0x5602c7ebf99e <unknown>
#54 0x5602c7f1c02b <unknown>
#55 0x5602c7f4f9b7 <unknown>
#56 0x5602c7ebfd7b <unknown>
#57 0x5602c7f4f7ce <unknown>
#58 0x5602c7f71cba <unknown>
#59 0x5602c7f48dae <unknown>
#60 0x5602c7f49941 <unknown>
#61 0x5602c7f4f755 <unknown>

Aborted (core dumped)
```

**Comment by CAM-Gerlach** [comment]
> Ok, I've removed completely pythons 3.4 and 3.6 that were in the system (from RHEL and EPEL repositories) and installed Anaconda.

FYI, Anaconda doesn't touch any other Python installs on your machine, including your system Python, so you don't need to remove any others in the future. Its completely self-contained.

> The only "special" thing about storage in this machine is that it has the logical volumes attached directly to it. This includes the /home directory, which is mounted as a local filesystem. 

Seems likely to be related, as strange as it sounds, given the nature of the error. It *shouldn't* happen, but clearly, for some reason, it does. Something to do with your storage interacting with a possible bug in QtWebEngine it seems.

> Should I open a separate thread, or this should be unrelated to Spyder?

Unrelated to Spyder, I'm virtually certain, as the problem isn't anywhere in Spyder's codebase or even in Python it all. Skimming over [the top three Google results](https://www.google.com/search?ei=ZX8UW93YLavV0gK_yYOACQ&q=FATAL%3Acredentials.cc%28137%29%5D+Check+failed%3A+error+%3D%3D+EPERM+%7C%7C+error+%3D%3D+EUSERS+%7C%7C+error+%3D%3D+EINVAL+%7C%7C+error+%3D%3D+ENOSYS.+%3A+No+space+left+on+device&oq=FATAL%3Acredentials.cc%28137%29%5D+Check+failed%3A+error+%3D%3D+EPERM+%7C%7C+error+%3D%3D+EUSERS+%7C%7C+error+%3D%3D+EINVAL+%7C%7C+error+%3D%3D+ENOSYS.+%3A+No+space+left+on+device&gs_l=psy-ab.3...13315.23691.0.24158.5.5.0.0.0.0.0.0..2.0....0...1.1.64.psy-ab..3.0.0.0...271.09yE3EzxS0Q), It appears it might be some sort of bug in QtWebEngine on Linux, which also cropped up in Chromium and various KDE applications. You could try asking on our Google Group or on one of the Stack Exchange sites to see if anyone else has seen it, or try your local sysadmin. Unfortunately, as it appears to be in KDE itself and specific to your machine configuration, we have no control over it :(

Hope you get it figured out!

**Comment by andersonwinkler** [comment]
Righto. Will do, thanks!
