### ISSUE TITLE
ImportError: cannot import name 'nonlinsolve'

### ISSUE THREAD

**Issue by JPICARD02** [spyder-ide/spyder#6974]
## Description
I'm trying to find the fixed points of a set of non linear equations unsing the command nonlinsolve from sympy. The code is as follow :

from sympy.core.symbol import symbols
from sympy.solvers.solveset import nonlinsolve

A, B, Pa, Pb = symbols('A, B, Pa,Pb', real=True)
X=nonlinsolve([Q_A(0,10,0,10,A,B,Pa),Q_B(0,10,0,10,A,B,Pb),Pdec(Q_A(0,10,0,10,A,B,Pa),Q_B(0,10,0,10,A,B,Pb),100)-Pa,Pdec(Q_B(0,10,0,10,A,B,Pb),Q_A(0,10,0,10,A,B,Pa),100)-Pb], [A,B,Pa,Pb])      
 
The error message I get is the following :

ImportError: cannot import name 'nonlinsolve'

**Please provide any additional information below**
You'll find my .py file in attachement
The version of python I use is the Python Version: 3.5.2
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

Thanks in advance :)
[voting.zip](https://github.com/spyder-ide/spyder/files/1919711/voting.zip)

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. I was able to run the import statements (which presumably produce the error) just fine, both with ``runfile`` and sending the commands to the console individually, but got an error on line 45 of your file ``TypeError: cannot determine truth value of Relational`` with Spyder 3.2.8 and Sympy 1.1.1 on Win 8.1 and Python 3.6.4

In any case, your error could simply be due to not having ``sympy`` installed properly, an older version, or something along those lines. Please update Spyder to the latest version (3,2.8) with ``conda update spyder`` (if you're using Anaconda, or ``pip update spyder`` otherwise), update ``sympy``, and I'd recommend you update Python as well if you can. Also, try the same commands from a standalone ``qtconsole`` prompt (you can launch it from Anaconda Prompt/Terminal/Command line with ``jupyter qtconsole``) in the same environment to see if you get the same error. Also, please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.
