### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by ashourm** [spyder-ide/spyder#6984]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
Sometimes when Spider it is unable to connect to kernel & you have to restart it to connect.

[spydernotconnectingtokernel](https://user-images.githubusercontent.com/35844281/38942996-d31901a2-431f-11e8-8767-b3b85800bf37.png)

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. Your image didn't load

> you have to restart it to connect. 

The kernel or Spyder? Assuming the former, I used to occasionally see this a while ago with older Spyder, IPython etc. version but haven't noticed it since.

Please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

If it still isn't working, please describe in detail the circumstances in which the error occurred, and post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Calling for Help section as a comment to this issue, and we'll try to help if we can. Otherwise, your issue will likely have to be closed after one week (7 days). Thanks, and best of luck!

**Comment by ashourm** [comment]
Thank you for your quick response and directions.

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.
