### ISSUE TITLE
Cannot open file in Spyder editor; only getting linux error: setNativeLocks failed: “No locks available”

### ISSUE THREAD

**Issue by ariannajojo** [spyder-ide/spyder#6987]
#**# Problem Description**

Hello,

I'm trying to access my files on the Spyder 3.2.8 editor, but any time I double-click on the file the editor freezes and I can't navigate it. Meanwhile, the error: setNativeLocks failed: "No locks available" continuously pops up in the Linux terminal I open Spyder with.

For some context, I did recently update from version 3.1.4 to 3.2.8. I also mainly use my own environment I created in anaconda, but the result is the same inside or outside the environment. I've reinstalled/reset spyder, and restarted my computer.

![spyder_issue_2](https://user-images.githubusercontent.com/20048008/38960097-0a913a9e-4318-11e8-951a-8c2985004749.PNG)

**UPDATE: I was told chances are this is probably a bug.

### What steps will reproduce the problem?

1. Opening Spyder in or out of created conda environment
2. Clicking the "open file" tab in top left of editor
3. Trying to open or save a file. I also tried dragging the file in place but I'm unable to edit or scroll down.

**## Package Versions**

* Spyder: 3.2.8
* Python: 2.7 
* Qt: 5.6.2

### Dependencies

IPython >=4.0;<6.0:  5.3.0 (OK)
cython >=0.21     :  0.25.2 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.1.1 (OK)
numpy >=1.7       :  1.12.1 (OK)
pandas >=0.13.1   :  0.20.1 (OK)
psutil >=0.3      :  5.2.2 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.5.0  :  1.5.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.6.4 (OK)
qtconsole >=4.2.0 :  4.3.0 (OK)
rope >=0.9.4      :  0.9.4 (OK)
sphinx >=0.6.6    :  1.5.6 (OK)
sympy >=0.7.3     :  1.0 (OK)

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. Seems rather unlikely to be a Spyder bug and rather something specific to your machine/environment/filesystem. You OS and version isn't listed above as is requested by the issue template, although from your screenshots its clearly Linux of some sort. Are you using a NFS filesystem of some sort? Some googling suggested making sure your disk isn't nearly full, and starting the lock service with e.g. ``sudo systemctl start rpc-statd`` Beyond that, please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

If it still isn't working, please describe in detail the circumstances in which the error occurred, and post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Calling for Help section as a comment to this issue, and we'll try to help if we can. Otherwise, your issue will likely have to be closed after one week (7 days). Thanks, and best of luck!

**Comment by ccordoba12** [comment]
Is your home mounted in an NFS file system?

**Comment by ariannajojo** [comment]
Hi everyone, my issue was solved; turns out there was a configuration

**Comment by CAM-Gerlach** [comment]
Glad you got it fixed @ariannajojo !
