### ISSUE TITLE
Spyder will not write to a directory

### ISSUE THREAD

**Issue by Kfried** [spyder-ide/spyder#7019]
## Description
I've recently installed spyder, I have a file which I can edit and save using pycharm. When I try using spyder it loads and executes the script but if I modify it and try and save then I am getting save permission errors [Errno 13] Permission denied. 

I have tried to save as and that is not working either, for example I tried to create a new folder and it creates multiple new folders.  When I try to save into one of the folders created I get permission errors again.

**What steps will reproduce the problem?**

**Given** a new python file created in Spyder
**When** I save the file 
**Then** the file saves without error

**Actual behaviour** If it is an existing file then I get Error 13, if it is a new file then I am told I don't have permissions to write to the directory and it is suggested that I save in the documents directory, it won't save there either

**Please provide any additional information below**
I have uninstalled and re-installed Anaconda multiple times. 

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. Clearly, this is a permissions problem of some sort with Spyder on your machine, and probably isn't one we can fix on the Spyder side. My guess would be its due to either Spyder being somehow installed or launched with the wrong permissions/user account ownership, or something wierd with your filesystem or its permissions—even if it is in fact something Spyder can fix, its almost certainly *something* somewhere in your environment that's triggering it—can you think of anything unusual about your machine, environment, filesystem, install, etc?

In any case, please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), particularly the [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) section, which has a good chance of resolving it—especially the different install and launch options.

**Comment by Kfried** [comment]
Thanks for the response, after much messing about I noted that the files in the folder were marked as read only. I have no idea why this is the case, potentially BitDefender did something but I cannot explicitly give an answer. Please close this it is not a bug.

**Comment by CAM-Gerlach** [comment]
Thanks for the quick followup, and glad you got it working!
