### ISSUE TITLE
Grouping cells in Outline without code indentation

### ISSUE THREAD

**Issue by max3-2** [spyder-ide/spyder#7086]
## Problem Description

Spyders Outline works well most of the time with cells and grouping by indentation to represent the code. Sometimes, manual setting would be advantageous (e.g. group functions desfined at top). See example..

### What steps reproduce the problem?

Add the following to spyder. See Outline. 

```
#%%a simple cell with some code
def withAFunction(x):
    return x
y = withAFunction(x)

#%%another cell with a function which gets grouped, but produces indentation error
    def withAnotherFunction(x):
        return x
    y = withAFunction(x)
```

### What is the expected output? What do you see instead?
First one expected, second would be good sometimes I think. However, getting second forces a wrong ident in code.

### Paste Traceback/Error Below (if applicable)
No traceback

## Versions

Python 3.6.3 64bits, Qt 5.9.4, PyQt5 5.9.2 on Windows 
* Spyder version:  3.2.8
* Python version: 3.6.3
* Qt version: 5.9.4
* PyQt version: 5.9.2
* Operating System name/version: Win10 x64

**Comment by ccordoba12** [comment]
So you want to define cells with indented code? Sorry, but I don't follow exactly what you mean.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 I believe what the OP is suggesting is a way to get functions (etc.) grouped into collapsible sections by cell, like Cell 2 in the screenshot, without having to manually indent the code. Perhaps an option to that effect ("Group by cell") in the drop down outline menu to turn on/off the behavior would be the best way to accomplish that, assuming someone had time to implement it. @max3-2 , if you're interested and @ccordoba12 agrees, perhaps that someone could be you. Otherwise, due to our current funding situation, it might not get done anytime soon, unfortunately.

Screenshot of the resulting behavior, for reference.

![image](https://user-images.githubusercontent.com/17051931/39796922-0c0567b2-531f-11e8-850c-98c2fdb59d3b.png)

**Comment by ccordoba12** [comment]
> I believe what the OP is suggesting is a way to get functions (etc.) grouped into collapsible sections by cell

Ok, but it doesn't seem easy to implement.

**Comment by max3-2** [comment]
Yeah that was the idea. If you have a large function library in front of your code or in an ext. file this would help grouping and organizing. I'll leave this open and check if I find the time to take a closer look myself. Havent worked / contributed to spyder yet so its starting from 0...

**Comment by CAM-Gerlach** [comment]
Thanks @max3-2 , we'd be glad to look at your contribution! Check out our [Contributing Guide](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md) to get started, and let us know if you'd like pointers.

**Comment by bcolsen** [comment]
@max3-2 This would help organize the outline.

As for syntax, you shouldn't need to play with the code in the file at all, so the grouping needs to be done in the block comment.

I would suggest this because it's sort of like markdown header hierarchy: 

```python
# %% Top level cell
def withAFunction(x):
    return x
y = withAFunction(x)

# %%% A grouped cell
def withAnotherFunction(x):
    return x
y = withAFunction(x)
```
Top level cells have 2 `%` and grouped cell have 3 `%`. You could even go down another level to 4 `%`

Grouped cells also open up the possibility to run the whole group or just the one cell.  That would get quite complicated.

**Comment by ccordoba12** [comment]
> I would suggest this because it's sort of like markdown header hierarchy

Really nice suggestion! Would you like to implement it @bcolsen?
