### ISSUE TITLE
issue with spyder in anaconda3

### ISSUE THREAD

**Issue by mgmritunjai** [spyder-ide/spyder#7090]
Install on a win 7 32 bit os.
Python works and ipython works.
When i try to launch Spyder, when it gets to "loading file history" it close and says that python.exe (or sometime pythonw.exe) has stopped working.

**Comment by ccordoba12** [comment]
Please open a system terminal (cmd.exe)

    spyder --reset

and try again.

**Comment by CAM-Gerlach** [comment]
Maybe related to #7080 , by chance?

**Comment by mgmritunjai** [comment]
I didn't understand

**Comment by mgmritunjai** [comment]
I did this...then also the same error is coming.

**Comment by CAM-Gerlach** [comment]
Please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

If it still isn't working, please describe in detail the circumstances in which the error occurred, and post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Calling for Help section as a comment to this issue, and we'll try to help if we can. Otherwise, your issue will likely have to be closed after one week (7 days). Thanks, and best of luck!

**Comment by CAM-Gerlach** [comment]
@mgmritunjai Any luck? Did you go through all the steps selected in the troubleshooting guide? Did you read the other issue? If we don't hear from you, we'll close this shortly. Thanks.

**Comment by mgmritunjai** [comment]
Ya I got it.thanks

**Comment by CAM-Gerlach** [comment]
So by that do you mean you resolved the issue, and this can thus be closed?

**Comment by mgmritunjai** [comment]
Yes.it can be closed

**Comment by CAM-Gerlach** [comment]
Thanks, and glad to hear it has been resolved.
