### ISSUE TITLE
"Help > Report Issue" goes to a broken link if not logged into GitHub

### ISSUE THREAD

**Issue by serg3y** [spyder-ide/spyder#7101]
Spyder>Help>Report Issue... loads a page with "Ooops!!! 500" error.
I think because I was not logged into GitHub.
After i logged into GitHub Help>Report Issue... started working and brought me here.

To a beginner trying to report a problem (me) solution was not obvious/disconcerting.

The URL was:
https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Fspyder-ide%2Fspyder%2Fissues%2Fnew%3Fbody%3D%253C%2521---%2520%252A%252APLEASE%2520READ%253A%252A%252A%2520Before%2520submitting%2520here%252C%2520please%2520carefully%2520consult%2520our%2520%252ATroubleshooting%2520Guide%252A%253A%2520https%253A%2F%2Fgithub.com%2Fspyder-ide%2Fspyder%2Fwiki%2FTroubleshooting-Guide-and-FAQ%2520and%2520search%2520the%2520issues%2520page%2520for%2520your%2520error%2Fproblem%252C%2520as%2520most%2520posted%2520bugs%2520are%2520duplicates%2520or%2520easy%2520fixes.%250A%250AIf%2520you%2520don%2527t%2520find%2520anything%252C%2520please%2520provide%2520a%2520detailed%2520step-by-step%2520description%2520%2528in%2520English%2529%2520of%2520the%2520problem%2520and%2520what%2520led%2520up%2520to%2520it%2520below.%2520Issue%2520reports%2520without%2520a%2520clear%2520way%2520to%2520reproduce%2520them%2520will%2520be%2520closed.%2520Thanks%2521%2520---%253E%250A%250A%2523%2523%2520Problem%2520Description%250A%250A%2523%2523%2523%2520What%2520steps%2520will%2520reproduce%2520the%2520problem%253F%250A%250A%250A%250A%2523%2523%2520Package%2520Versions%250A%250A%252A%2520Spyder%2520version%253A%25203.2.8%2520%250A%252A%2520Python%2520version%253A%25203.6.4%250A%252A%2520Qt%2520version%253A%25205.6.2%250A%252A%2520PyQt5%2520version%253A%25205.6%250A%252A%2520Operating%2520system%253A%2520Windows%25207%250A%250A%2523%2523%2523%2520Dependencies%250A%250A%2560%2560%2560%250Apyflakes%2520%253E%253D0.6.0%2520%253A%2520%25201.6.0%2520%2528OK%2529%250D%250Apycodestyle%2520%253E%253D2.3%253A%2520%25202.3.1%2520%2528OK%2529%250D%250Apygments%2520%253E%253D2.0%2520%2520%2520%253A%2520%25202.2.0%2520%2528OK%2529%250D%250Apandas%2520%253E%253D0.13.1%2520%2520%253A%2520%25200.22.0%2520%2528OK%2529%250D%250Anumpy%2520%253E%253D1.7%2520%2520%2520%2520%2520%2520%253A%2520%25201.14.0%2520%2528OK%2529%250D%250Asphinx%2520%253E%253D0.6.6%2520%2520%2520%253A%2520%25201.6.6%2520%2528OK%2529%250D%250Arope%2520%253E%253D0.9.4%2520%2520%2520%2520%2520%253A%2520%25200.10.7%2520%2528OK%2529%250D%250Ajedi%2520%253E%253D0.9.0%2520%2520%2520%2520%2520%253A%2520%25200.11.1%2520%2528OK%2529%250D%250Anbconvert%2520%253E%253D4.0%2520%2520%253A%2520%25205.3.1%2520%2528OK%2529%250D%250Asympy%2520%253E%253D0.7.3%2520%2520%2520%2520%253A%2520%25201.1.1%2520%2528OK%2529%250D%250Acython%2520%253E%253D0.21%2520%2520%2520%2520%253A%2520%25200.27.3%2520%2528OK%2529%250D%250Aqtconsole%2520%253E%253D4.2.0%253A%2520%25204.3.1%2520%2528OK%2529%250D%250AIPython%2520%253E%253D4.0%2520%2520%2520%2520%253A%2520%25206.2.1%2520%2528OK%2529%250D%250Apylint%2520%253E%253D0.25%2520%2520%2520%2520%253A%2520%25201.8.2%2520%2528OK%2529%250D%250A%2560%2560%2560%250A

## Package Versions
* Spyder version: 3.2.8 
* Python version: 3.6.4
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating system: Windows 7

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. We're in the process of improving how users report issues to Github, so we'll fix this as part of that.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 The trouble here is that due to having to pass the full URL as a parameter, even more things are percent encoded, making the length even longer, in addition to the marginal additional length of the actual URL content. 

The solutions here are basically what I outlined in #6870 . The best way to really make a big dent in the length is to greatly cut down on the spaces and special characters in the deps section (e.g. min versions, since with the OK they are redundant, extra spaces before and after : , parens around OK, etc.) and cut any deps if possible that have never posed a troubleshooting issue and are unlikely to (``psutil`` on macOS/Linux, ``sympy``? ``nbconvert``? ``pygments`` ?). This will have far more bang for the buck in cutting down on characters than removing any more from the existing text, which has already been cut to the bone (though any more we can remove won't hurt); just doing the above suggestions will cut down the total length by around 1/3 while sacrificing little to no valuable information. 

The alternative is making the menu option use the new error report dialog as well, but that adds extra complexity and time for the user which can likely be avoided.

**Comment by ccordoba12** [comment]
Yeah, my idea is to use the new report error dialog to handle the *Report issue...* action too.
