### ISSUE TITLE
'IPython console' no detecting changes to files (running old versions)

### ISSUE THREAD

**Issue by serg3y** [spyder-ide/spyder#7102]
Keep in mind I am new to this... this may be by design, if so please redesign..

Running a script/function from the editor produces different results to running same script/function from IPython console. It appears IPython console is running the old version of the file.

To a beginner (me) this is most difficult to unravel/grasp. This makes switching from MatLab to python most unrewarding.

Is there a way to make IPython console detect weather or not a file has changed since it was last run and recompile (or whatever) to run the current version, not the old version?

Example:
1) Create test.py
2) put in it "def temp():print('OLD')"
3) run from editor using F5
4) change to "def temp():print('NEW')" and SAVE
5) run from "IPython conosel" window by typing "temp()", result is it "OLD"

I don't even know howto (it is not obvious) compile all files before running something from console, only way I know is to hit F5 on each file first, and if I forget it gets confusing.

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.4
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating system: Windows 7

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)
```

**Comment by ccordoba12** [comment]
I think you need to import `temp` from your `test` file first, before changes to `temp` are automatically reloaded by our IPython consoles.

Could you do that and let us know if that works for you? Thanks!

**Comment by CAM-Gerlach** [comment]
> I think you need to import `temp` from your `test` file first, before changes to `temp` are automatically reloaded by our IPython consoles.

This works perfectly, without runfile or otherwise running the block in between; tested with the OP's code.

> this may be by design, if so please redesign..

Perhaps I misunderstand, but to do what you ask without first importing the file and calling a reference to that imported function would not only require a redesign, but essentially a bunch of implicit assumptions (perhaps even rising to the degree of "magic") that would probably be bad practice (and encourage more of the same), potentially cause huge performance issues, and even break code/workflows. 

Essentially, ``runfile`` runs a file as a script, in the __main__ namespace, in a similar (although not exactly identical) manner as running the individual lines at the prompt. There is no explicit mechanism, either technical *or conceptual*, that links the objects (e.g. functions) that said script creates with the file that created them, as they exist only in the ``__main__`` namespace. Therefore, Spyder itself would have to somehow keep track of exactly what script created them, and check and re-run that script every time that object was called. 

Aside from time, complexity and potential bugs inherent in such a system, even if working 100% as intended this would have a number of issues—if you called any object from any script that had a change, no matter how trivial, the whole script would need to be re-run, which (particularly in the data analysis domain) can be a very expensive operation and highly undesired in most cases. Furthermore, you'd be automatically re-writing any objects (beyond just functions) in the environment (and even on disk, if any I/O was involved in your script), causing possible session and data loss unintentionally, and possibly breaking the results of code (if e.g. scripts were intended to be called in a particular order, or you made a partial change in a function). Along with that, the reload itself could break entirely if the saved version of the file had something partially implemented that was not intended to be run yet, or that file had not been refactored while others had,  etc. 

Even further, there are a number of edge cases that would not have unambigous solutions—how to handle objects that function called that were loaded via other scripts? What if a file was moved or deleted? What if the function no longer exists in the script, or was renamed? What if two scripts had the same function? What if the user had subsequently defined an object via run line or directly in the console with the same name? Etc. etc. etc.

So, I hope this demonstrates why such a process is a bad idea, and provides an outline of why the whole data science workflow Spyder was built to encourage—separating your code base into a moduler package with generalized functions that do the grunt work, and short, specific analysis scripts that import and call them—is a Good Idea™.

**Comment by serg3y** [comment]
Sorry, just a bit new to this...

I think, I understand the big difference between MatLab and Python now. In MatLab the .m files on the paths define the namespace in a way, that's why it has to monitor and react to changes to files, but I can see why that cannot and should not be done in a language where namespace is not defined by the files, but rather through "import" etc.

Thank you for the explanation!
I hope other MatLab-ers will benefit from it also.

**Comment by CAM-Gerlach** [comment]
>  In MatLab the .m files on the path define the namespace in a way

> but I can see why that cannot and should not be done in a language where namespace is not defined by the files, but rather through "import" etc.

Mmm, I see. Well, it and it isn't; in Python, the file hierarchy of a package/working directly defines the namespaces they get mapped in to on a plain ``import``, but you can also control things within the language with the ``as`` and ``from`` keywords. In exchange for a small amount of explicit effort upfront (``import``ing modules you need), you can avoid all kinds of problems and ambiguities, get better performance (no need to import/compile what you don't), make your code much clearer, and gain finer control over your namespaces. It all fits with the Python philosophy: explicit is better than implicit.
