### ISSUE TITLE
Could not import the data

### ISSUE THREAD

**Issue by adhikarirajan** [spyder-ide/spyder#7118]
## Description

**What steps will reproduce the problem?**

1. click on import icon
2. navigate the data file location
3. click the run button

**What is the expected output? What do you see instead?**
The expected output was the data table imported on spyder.

**Please provide any additional information below**

MemoryError

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by CAM-Gerlach** [comment]
Thanks for the report. I just tested it now with Spyder 3.2.8 (the latest version, to which you should upgrade with ``conda update spyder``), and the same Py and Qt versions as you, on Windows 8.1, and everything worked fine when importing a fixed width file. Therefore, in order for us to be able to reproduce and hopefully fix it, assuming it isn't something with your installation, we'll need to know:

* Exactly what steps you took (since after navigating to the data file location in the Windows file picker, "Run" is not an option, only "Open" or "Cancel"), 
* Where you are storing the files relative to your project/working dir and your Spyder install (are they on another drive, for instance?), and, most importantly,
* An example of a data file that results in the problem occurring on your machine under the above two conditions

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.
