### ISSUE TITLE
Spider photographs for Spyder 4.0

### ISSUE THREAD

**Issue by RodrigoDon** [spyder-ide/spyder#7217]
Dear Spyder Development team, collaborators, key persons and other people of interest. 

I have read the information below but find most of it unapplicable in relation to what I want to bring to the table. 

I am a photographer who has taken a couple of **photos of spiders**, in Stockholm, Sweden where I live and in Mexico, respectively. I have suggested to some individuals in the Spyder Development team to upgrade the spider web photo to a spider web photo with an actual spider. A spider photograph for a software called "Spyder" would not do harm to the brand if the photographic job has been well executed, in my personal opinion. But you be the judge. I simply want to help by doing good to this formidable software. 

In this message I therefore ask of the opinion about some photographs of spiders that I have taken. I will try to attach a file with 14 thumbnails. 

My name is Rodrigo and although I am not a professional programmer, I can as a chemistry student appreciate the software, GUI and see potential to Spyders future. 

Best Regards,
Rodrigo
![spiders2018](https://user-images.githubusercontent.com/34109274/40623005-ceb344ca-62a4-11e8-934d-c07590971de9.png)

**Comment by ccordoba12** [comment]
Thanks a lot Rodrigo!

@spyder-ide/core-developers, @spyder-ide/junior-developers, please chime in to give your opinion.

**Comment by CAM-Gerlach** [comment]
Thanks @RodrigoDon ! 

I will adopt the convention of referring to the images by their row and column positions, 1-indexed; i.e. the center image would be (2, 3).

The big consideration, IMO, is that it has to be a good background image, without a too prominent subject (like a large spyder) or too high contrast that would conflict with the text overlaid on top of it. Our current image is very good, IMO, in that regard and has great colors, but a little more "punch" might not be bad, not to mention just having a different look for Spyder 4's in general so people can visually distinguish them at a glance and help communicate the many major changes in that version.

Of his images, my thought is that either (1, 2), or (3, 3)  would likely work best, for different reasons. Most of the rest have the spider too large/centered in the frame for us to overly the text properly (we'd probably want the spider to the left of the text/logo). The 1,2 image would be a more dramatic departure from our current image but would fit perfectly with the white on black bg dark theme to be introduced for Spyder 4; a tight crop with the center spider(s) to the left of the frame might be very nice.

On the other hand, the 3,3 one has nice colors and a refined web very similar to our current one; in that case we'd want to crop it so the spider was to the right of the frame. Its a little busy though (to the point where its hard to tell exactly what's going on at that small size), and doesn't look too different from first glance vs. our current image other than having a spider, so that's also a downside since a new look might not be bad to clearly separate the versions and communicate the significance of the many major changes in Spyder 4. I'm also a bit infatuated with 1,2's colors matching those of the white on black of the eventual dark theme, one of the major additions for Spyder 4, but maybe the more conservative choice (3,3) is the better one overall...not sure, I'd have to see it larger.

I suppose some variation of (2, 2) could also work, with the spider cropped to near the right margin; it has a colored spider but less interesting/detailed web vs. top left so not sure its better over all. It or bottom right we could rotate/flip to make the spider face up or be on the left if desired. That one in particular, and to a lesser extent 3,3, has the problem as @jnsebgosselin pointed out that it could provide a negative reaction from people with arachnophobia, quite the opposite of the impression we want to send. Estimates are that between 3.5 and 6.1% of the population has arachnophobia, so we don't want to put them off. In that case, 1,2 would be the one to go with if we were to use one, since its mostly just the web and you only see a bare outline/silhouette of a spider, with a very abstract and almost symbolic level of detail.

Thoughts?

**Comment by bcolsen** [comment]
> could provide a negative reaction from people with arachnophobia, quite the opposite of the impression we want to send.

I know a few people who wouldn't feel comfortable(maybe even a panic attack) if a image of an actual spider popped up at them.

**Comment by CAM-Gerlach** [comment]
Right, and the above cited statistics indicate that's indeed a non-negligable percentage of the population who have arachnophobia, and likely an order of magnitude more who have at least some discomfort of them and would prefer to not be shown an image of them. Recall, given these statistics are about those who posses the the *phobia*, which contrary to the incorrect popular usage implies the specific stimulus provokes a very extreme reaction, often amounting to a panic attack. Personally, I've actually always liked spiders (except for dead or highly poisonous ones), but am in a distinct minority.

**Comment by ccordoba12** [comment]
Closign because we really don't like this approach. But thanks for your input @RodrigoDon!
