### ISSUE TITLE
Clearing the variables in a console also clears Pylab and SymPy name spaces and variables

### ISSUE THREAD

**Issue by bcolsen** [spyder-ide/spyder#7224]
## Issue:

Currently on 3.x if you have automatically load NumPy and Matplotlib(aka Pylab) or SymPy enabled in the IPython configuration variables and namespaces associated with those packages will be removed when you clear all the variables. This would come as a surprise to most uses because they would consider that a property of the console not a user defined variable.

## What happens in similar software:

As a reference starting ipython with the --pylab option and then running %reset removes all of pylab.  Even in isympy running %reset removes SymPy. Octave, Matlab, R and Julia don't do this because those options are in the base language.   

## Options:

All of the options below would need a way to find out the options of the current console stored in its environment variables.

1. The simplest would be to remap clearing the variables to a kernel restart on console with these options enabled.

I find that the console restarts in less than a second on my computer but it seem this is not the case on every platform. 

2. Reload the features after the variables are removed.

Should be faster than a full restart, but I fear there will be code duplication here

3. Remove only user defined variables and not the pre-imported packages

I think that this would be quite difficult and fragile

**Comment by CAM-Gerlach** [comment]
> The simplest would be to remap clearing the variables to a kernel restart on console with these options enabled.

The issue with this is that it is functionally quite different from just clearing user-defined variables as the user requested; it also wipes any loaded packages/modules, terminates any attaches processes, doesn't reflect any IPython magics (e.g. automatic ``pdb`` calling with ``pdb``, options to the matplotlib backend, etc), clears all scrollback including displayed input, output, and plots, resets the runtime and prompt counters, and otherwise discards all state). This is totally different from what the user expects and what it is "supposed" to do, and is more destructive than anticipated to boot. In fact, I'd consider this a bigger problem than the one it 

Why not just silently run the ``pylab`` command after clearing variables as normal, assuming you've implemented

>  a way to find out the options of the current console stored in its environment variables.

as you say all three require? That seems to be simpler, faster and cleaner than any of them

**Comment by CAM-Gerlach** [comment]
For sympy, the commands it needs to execute are pretty simple, but perhaps there is a straightforward way to call them from an existing function without a full restart.

So, basically I'm suggesting a variant of 2. I share your concerns about 3., and have even graver reservations about 1. as stated above.

**Comment by bcolsen** [comment]
The first option wouldn't work anyway because the clear variable option was made because the restarts were too slow.

> So, basically I'm suggesting a variant of 2.

I think this is way to go as well.  The current functions that run pylab and sympy just run those simple commands which are unlikely to change, but there is some code that deals with matplotlib backend selection that is a bit more complicated. I looks like the setting for the inline figures are still there after clearing all variables.  So that might be just fine.
