### ISSUE TITLE
Automatic help page update steals focus from editor

### ISSUE THREAD

**Issue by BurnNote** [spyder-ide/spyder#7423]
## Problem Description
 In my layout, the editor and help are on different tabs in the same pane. This leads to issues with the way the help updates with the automatic connections option. Adding '(' behind the name of any function in the editor takes me to the help/documentation page for that function, unless that page was already called up. But now I can't actually see the code anymore. 

The same thing happens with any pane where the help is just one tab. A soon as it updates, it becomes the active tab. For me that makes the feature unusable, because stuff I want to see goes away whenever I type a function. 

### What steps will reproduce the problem?
The help page and editor have to share a pane. Automatic connections option for the editor is active. In a new file:

def test(): 
   pass

Run it to add the function to variables. 'test( ' in editor will switch to help. 

## Package Versions

* Spyder version: 3.2.8 
* Python version: 2.7.15
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating system: Windows 7

### Dependencies

```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.23.0 (OK)
numpy >=1.7       :  1.14.5 (OK)
sphinx >=0.6.6    :  1.7.4 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.12.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.7.0 (OK)
pylint >=0.25     :  1.8.4 (OK)
```

**Comment by bcolsen** [comment]
If I understand this correctly you have the help and the editor in the same tab. So the help pops up over the editor when you have automatic help on.

What would you like it to do? We could make a check not to pop up help over the editor, but I think that's not going to be a high priority. 

You can disable the automatic help and use `ctrl + i` while your cursor is on the name of of a function to see the help. That way the interface wouldn't change unexpectedly.

Ideally there would be all the information most people would want in the function signature box that pops up in the editor.

**Comment by BurnNote** [comment]
You've got it essentially right. But I think the problem is a bit broader. Like, if the help and anything else (outline, vairable viewer) share tabs, the help also pops up over them. It's not as distracting as when it hides the editor, but it's still a bit annoying. 

My suggestion would be to change it so the help doesn't change which tabs are visible in general, or for people who prefer the current behavior, add an option where you can choose it when checking automatic help.

**Comment by bcolsen** [comment]
>My suggestion would be to change it so the help doesn't change which tabs are visible in general, or for people who prefer the current behavior, add an option where you can choose it when checking automatic help.

So your proposal here is to have automatic connections to help but not make it pop up so it's there when you have the help tab visible and not when when the help tab isn't visible you wouldn't know it's happening. Using the `Ctrl + Shift +H` shortcut to change to the help  tab would be pretty useful here.

I think there will be only a few people who would want this option considering the `ctrl+i` shortcut would more or less equivalent since you would need to use a shortcut to see the help already. 

For the mouse users this could be neat but a not implemented right-click on a function -> see documentation would be better for most people.

All this being said it wouldn't be hard to do likely an if statement around the part that pops the help up and a check box in the options to activate the if statement.

I don't speak for accepting code into the project, but you could submit a PR for this. Spyder is all written in python so it's pretty easy to change.

**Comment by CAM-Gerlach** [comment]
@bcolsen @BurnNote Thanks much for your detailed analysis of the situation.

> All this being said it wouldn't be hard to do likely an if statement around the part that pops the help up and a check box in the options to activate the if statement.

The difficulty is that once the call gets to the point where the the help pane is brought to the front ([here](https://github.com/spyder-ide/spyder/blob/59874debd377c0919ea6308d2ce668b6d10737dc/spyder/plugins/help.py#L811), or [here](https://github.com/spyder-ide/spyder/blob/59874debd377c0919ea6308d2ce668b6d10737dc/spyder/widgets/mixins.py#L682)), it doesn't seem that it necessarily knows whether it was triggered on-demand or automatically; if triggered on-demand we'd still obviously want to show the window since the user explicitly requested to see it. So, you'd have to follow the various execution paths (there are several, and its a bit confusing) to make sure that state was propagated as function parameters, etc. to one of the two above points where it could be acted upon (aside from handling and checking the relevant preferences setting at the latter point(s).

**Comment by ccordoba12** [comment]
> In my layout, the editor and help are on different tabs in the same pane. This leads to issues with the way the help updates with the automatic connections option. Adding '(' behind the name of any function in the editor takes me to the help/documentation page for that function, unless that page was already called up. But now I can't actually see the code anymore.

The solution is very simple: you need to go to

    Tools > Preferences > Help > Automatic connections

and deactivate the `Editor` option.

That way Help will only be called on demand, i.e. when you press `Ctrl+I` in front of an object.

**Comment by CAM-Gerlach** [comment]
> The solution is very simple: 

As @BurnNote and @bcolsen have discussed above at some length, it is not in fact so simple if the user actually wants to use said feature, as they do here. It may not be a huge usecase (sufficient to motivate us to spend our time addressing it), but it does address a non-trivial user need and add value for several use cases, and @BurnNote stated they are willing to work on it to add the appropriate option and submit a PR for our consideration. 

Therefore, in fairness to that, I don't see why this should be closed, unless we have already decided we are conclusively against even adding it as a non-default option.

**Comment by ccordoba12** [comment]
@BurnNote is welcome to send us a PR to address this. If that happens, this will be reopened, else it makes no sense to keep it open since the current behavior is simple: either you opt-in or out of the automatic connections option.
