### ISSUE TITLE
win spyder 3.3.0 not yet on conda main

### ISSUE THREAD

**Issue by wtheis** [spyder-ide/spyder#7496]
I notice that in the past all os versions of spyder have typically been uploaded to conda on the same day. For 3.3.0 the windows versions are still missing 5 days after the other uploads. Did something go wrong on their side?

We are preparing to roll out spyder 3.3.x across campus for the 2018/19 academic year, otherwise I would have waited a few more weeks before asking.

**Comment by ccordoba12** [comment]
@mingwandroind, @jjhelmus, could you help us with this one? It has been 12 days since we released 3.3.0... (I know packages are already available for Linux and macOS, and thanks a lot for that!)

**Comment by ColWriter** [comment]
Waiting for much more than 5 days.
Who knows?

**Comment by ccordoba12** [comment]
Spyder is not affiliated with Anaconda (we were from 2015 to 2017, but not anymore), so we don't have any control on release dates for new conda packages.

All I know is their topmost priority right now is to create new packages for Python 3.7, which delayed the release of new packages for Spyder (that's what they told me). My guess is that they are having problems to compile some Spyder dependencies for Windows/Python 3.7 (pyqt, pyzmq?)

Of course, this has nothing to do with releasing new packages for older Python versions, but it's their choice, not ours.

**Comment by VanitarNordic** [comment]
@ColWriter 

Remove Spyder from the main conda. I mean when you are in the root. 

`conda remove spyder`

Then create an environment for your need and install the Spyder by Pip in your environment. that's what I did to have the Spyder 3.3.0 for windows for now at least.

**Comment by ColWriter** [comment]
I understand - competition between Anaconda and Spyder.
Anaconda gives us every startup of Spyder messages to update Spyder but there is no update
because they are busy with Python.
Perhaps Spyder and Anaconda has to talk with each other about this strange situation because this is most irritating. 
Anyway Anaconda has to end startup messages for updating Spyder.

**Comment by ccordoba12** [comment]
> I understand - competition between Anaconda and Spyder.

There's no competition, it's just that sometimes they took longer than usual to upload their packages.

> Anaconda gives us every startup of Spyder messages to update Spyder but there is no update
because they are busy with Python.

You can disable those messages by going to

    Tools > Preferences > General > Advanced Settings

and disabling the option called

    Check for updates on startup

----

Anyway, due to this problem, we decided to directly verify the availability of new Anaconda packages in their own repositories, instead of doing it through Github.

This fix will be available since our **3.3.1** version.

**Comment by paulgureghian** [comment]
whats the process  for creating packages for spyder for conda, and python for conda... does it entails lots of complex coding/compiling/tooling .... or just some clicks in a gui environment ?

**Comment by ccordoba12** [comment]
No, the process is quite simple, but (as I said) Anaconda guys prioritized creating packages for Python 3.7 instead of Spyder ones.

**Comment by jjhelmus** [comment]
Spyder 3.3.0 is now available for win-32 and win-64 in `defaults`.  We are still working on a version for Python 3.7 on Windows but 2.7, 3.5 and 3.6 are available.  Sorry for the delay.

**Comment by ccordoba12** [comment]
Thanks a lot @jjhelmus!! I can confirm new Windows packages are already available, so this one can be closed.
