### ISSUE TITLE
Improve selection of custom Python interpreter in Preferences

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#7529]
There are three things I'd like to see improved over our current process in `Preferences > Python Interpreter > Use the following interpreter`:

1. We should save the list of all interpreters users have introduced there. This would make their life easier when they want to select previous interpreters for different conda/venvs.
2. Having that list, we could show it in a combox of options, along with the current text field.
3. The validation to see if a file is a real Python interpreter needs to be done when users press *Apply* or *Ok*, not when they're writing a path by hand. I've been bitten by this usability error a lot of times (for example when changing a conda env).

@dalthviz, please work on this one.

**Comment by CAM-Gerlach** [comment]
Can this wait for 3.3.2, perchance? It is a very nice feature to have, but not essential or a bug fix, and the sooner we got 3.3.1 out the better. Also, if any UI text is changed related to this, it would trigger a new round of translations (though its not clear that would be the case). Furthermore, it means we'll have to add yet another ~paragraph to the already very long 3.3.0/3.3.1 post and update the screenshots accordingly, rather than properly giving it its due in the 3.3.2 release post. But if you really think it needs to be in 3.3.1 then I'll do what I have too; it isn't *that* bad.

**Comment by ccordoba12** [comment]
> Can this wait for 3.3.2, perchance?

The thing is if we start to promote the modular approach with `spyder-kernels`, we definitely need to provide a better UI to switch among envs.

Besides, I don't think this one is too hard. It should take @dalthviz a couple of days of work.

> rather than properly giving it its due in the 3.3.2 release post

I don't think minor releases deserve a blog post. They are usually focused on bugfixes only.

**Comment by CAM-Gerlach** [comment]
> The thing is if we start to promote the modular approach with spyder-kernels, we definitely need to provide a better UI to switch among envs.

Yeah, that makes sense, and I really like the idea of this change overall.

> I don't think minor releases deserve a blog post. They are usually focused on bugfixes only.

Well, if they really do have purely bug fixes and are not too far apart, then I guess I agree (as we're doing with combining 3.3.0 and 3.3.1, essentially). However, if they have actual enhancements or other user-visible changes (i.e. most of what you summarize in the top section of the release announcements, other than under-the-hood changes that have no obvious impacts on users). then it is a good idea to do at least a short blog post, because:

* It highlights what we've been working on with Spyder and that the project is still active, and provides something to link to in our OC updates to our backers to promote full transparency
* It lets users know what to expect in the new version, and how to best use the enhancements/changes
* It builds additional traffic to our website and blog and gives them more regular content
* It reminds users to update and gives them incentive to do so
* It serves as a visual, descriptive archive of any significant UI changes, which also helps us keep track of which screenshots to update in our docs

**Comment by ccordoba12** [comment]
> if they have actual enhancements or other user-visible changes ...

After we merge `split-plugins`, I plan to do no more enhancements, just bugfixes (and mainly critical or easy ones).

**Comment by CAM-Gerlach** [comment]
Right; is that still scheduled for before/around the 3.3.2 timeframe? This isn't too bad in this case since the feature preview, status update, beta release, etc. blog posts for Spyder 4 beta 1 will help take up the slack.

**Comment by ccordoba12** [comment]
> before/around the 3.3.2 timeframe?

Right after 3.3.1

> This isn't too bad in this case since the feature preview, status update, beta release, etc. blog posts for Spyder 4 beta 1 will help take up the slack.

Yes, that's my idea too. All publicity should be focused in Spyder 4 from now on, to generate as most expectations for that release as possible.

**Comment by CAM-Gerlach** [comment]
Okay, thanks!
