### ISSUE TITLE
AttributeError: module 'spyder_kernels.utils.iofuncs' has no attribute 'iofunctions'

### ISSUE THREAD

**Issue by adaaaaaa** [spyder-ide/spyder#7532]
can not open spyder3.3.0 in Manjaro x64
error here:
[captain@captain-pc ~]$ spyder3
Traceback (most recent call last):
  File "/usr/sbin/spyder3", line 7, in <module>
    from spyder.app.start import main
  File "/usr/lib/python3.6/site-packages/spyder/app/start.py", line 27, in <module>
    from spyder.config.main import CONF
  File "/usr/lib/python3.6/site-packages/spyder/config/main.py", line 21, in <module>
    from spyder.config.fonts import BIG, MEDIUM, MONOSPACE, SANS_SERIF
  File "/usr/lib/python3.6/site-packages/spyder/config/fonts.py", line 14, in <module>
    from spyder.config.utils import is_ubuntu
  File "/usr/lib/python3.6/site-packages/spyder/config/utils.py", line 56, in <module>
    IMPORT_EXT = list(iofuncs.iofunctions.load_extensions.values())
AttributeError: module 'spyder_kernels.utils.iofuncs' has no attribute 'iofunctions'

**Comment by ccordoba12** [comment]
Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.

**Comment by adaaaaaa** [comment]
success to start spyder3.2.8,but fail to start spyder3.3.0.

**Comment by ccordoba12** [comment]
As I said, if you're unwilling to use Anaconda, you're basically on your own. Sorry, but we have to save our time to solve the long list of bugs users have reported and implement new features.
