### ISSUE TITLE
Availability of DMG installers?

### ISSUE THREAD

**Issue by kannes** [spyder-ide/spyder#7534]
### Issue Report Checklist

* [y] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports

https://pythonhosted.org/spyder/installation.html#installing-on-macos-x links to https://github.com/spyder-ide/spyder/releases, saying there should be DMG installers.

I can not find any DMG files there.

**Comment by ccordoba12** [comment]
> https://pythonhosted.org/spyder/installation.html#installing-on-macos-x

This documentation is outdated, but unfortunately we can't update it anymore. We'll remove in 3 to 6 months.

Our new docs are available here

http://docs.spyder-ide.org/

----

> I can not find any DMG files there.

We don't create DMGs anymore because it takes a lot of time. Now we instruct people to install Anaconda instead:

https://www.anaconda.com/download/
