### ISSUE TITLE
This happened to me while trying to open spyder

### ISSUE THREAD

**Issue by CajitaFeliz** [spyder-ide/spyder#7584]
## Description

**What steps will reproduce the problem?**

1. Trying to upgrade spyder by ignoring iphyton
2.  Upgrade was unsuccesful because it couldn't uninstall ipython.  I used this command on command prompt: pip3 install --upgrade --force-reinstall --no-cache-dir Spyder
3. Opening Spyder

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

    plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.9.3, PyQt5 5.9.2 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  2.0.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by dalthviz** [comment]
Hi @CajitaFeliz to not see such a message you need to retry the update to `Spyder 3.3.0` or uninstall  the package `spyder-kernels`. Since you are using Spyder `3.2.6` it detects the new `spyder-kernels` package as a plugin, and shows you the error message you describe while trying to load it (`spyder-kernels` is a dependency for `Spyder 3.3.x`, and probably it was installed when you tried the update).

**Comment by ccordoba12** [comment]
@dalthviz is right.
