### ISSUE TITLE
Add a shortcut to create a new cell

### ISSUE THREAD

**Issue by isalirezag** [spyder-ide/spyder#7609]
Is ther any shortcut to create cell (`# %%`)?

**Comment by ccordoba12** [comment]
No, there isn't and since it's very simple to create a cell, we don't plan to add it, sorry.

**Comment by mluerig** [comment]
great news!

maybe CTRL + 2, since 1 is toggle comment? I think of code cells as in structuring elements, like comments, to annotate code, so I think it might be meaningful to have it close by. but not super imporant since we can always modify the shortcut to our needs...

is the button going to be "toggle" or "insert" code cell?

**Comment by ccordoba12** [comment]
> maybe CTRL + 2, since 1 is toggle comment?

You'll be pleased to know what I just found out: the new button to create cells already has a shortcut and it's precisely `Ctrl+2`!

![image](https://github.com/spyder-ide/spyder/assets/365293/670dea45-17d7-4d34-b230-94e101d4475d)

So, I'd say this issue is already solved.

> is the button going to be "toggle" or "insert" code cell?

Insert cell. Is that ok?

**Comment by dalthviz** [comment]
Just in case, the PR that probably fixed this: https://github.com/spyder-ide/spyder/pull/20509

**Comment by mluerig** [comment]
wow, minds thinking alike 👍 

> Insert cell. Is that ok?
I think so. need to try first

**Comment by ccordoba12** [comment]
> I think so. need to try first

Ok, I'm going to close this issue for now. Please open a new one once Spyder 6 is released if that's not the behavior you'd expect.

**Comment by ccordoba12** [comment]
That button will be available in Spyder 6, to be released in a month or so.
