### ISSUE TITLE
Win spyder 3.3.1 not yet on conda main

### ISSUE THREAD

**Issue by ColWriter** [spyder-ide/spyder#7685]
Just as on 7/21 at start up "Spyder 3.3.1 is available" but when using Conda NOTHING

**Comment by ccordoba12** [comment]
Yeah, we know, but this is not something we can address because none of us work for Anaconda anymore. Please be patient or deactivate the functionality that informs you about new releases.

However, we fixed this issue in 3.3.1 by searching for new releases in Anaconda's channels instead of by inspecting our Github releases page.

**Comment by ColWriter** [comment]
Thanks - it was there now
