### ISSUE TITLE
Spyder not opening: ERROR:broker_win.cc(59)] Error reading broker pipe

### ISSUE THREAD

**Issue by panzerfist** [spyder-ide/spyder#7690]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder cannot launch correctly from Anaconda Navigator or cmd or GitBash. Antivirus offloaded, only Windows defence on, all other tools and IDEs on Anaconda work well.Tried multiple other ways entioned on github (restart, reinstall, pyqt, reset, update, downgrade) but still doesn't work.

### What steps reproduce the problem?

1. Starting Spyder from Anaconda Navigator/cmd/GitBash
2. 
3. 

### What is the expected output? What do you see instead?
Expecting Spyder to launch, but it failed to. The Spyder launching interface loaded at first and it said "initialization", "starting editor" etc, and the bigger UI window poped out (without any content), but it then it "no response" and the whole window just crashed, error msg in console was:
```
ERROR:broker_win.cc(59)] Error reading broker pipe
```

### Paste Traceback/Error Below (if applicable)

```
ERROR:broker_win.cc(59)] Error reading broker pipe
```
```

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

```
$ conda info

     active environment : None
       user config file : C:\Users\zhouz\.condarc
 populated config files : C:\Users\zhouz\.condarc
          conda version : 4.5.9
    conda-build version : 3.10.5
         python version : 3.6.6.final.0
       base environment : H:\ProfessionalSoftware\Anaconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : H:\ProfessionalSoftware\Anaconda\pkgs
                          C:\Users\zhouz\AppData\Local\conda\conda\pkgs
       envs directories : H:\ProfessionalSoftware\Anaconda\envs
                          C:\Users\zhouz\AppData\Local\conda\conda\envs
                          C:\Users\zhouz\.conda\envs
               platform : win-64
             user-agent : conda/4.5.9 requests/2.18.4 CPython/3.6.6 Windows/10 W                       indows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False

```

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
> Antivirus offloaded, only Windows defence on

The only thing we know about this problem is that it's caused by firewalls and/or antivirus. Sorry but there's nothing else we can do to help you.

**Comment by panzerfist** [comment]
Solved the problem by disabling the integrated graphics.

**Comment by ccordoba12** [comment]
What do you mean by that exactly? Please explain it in more detail so we can help others.

**Comment by panzerfist** [comment]
So my laptop has an intergrated Intel UHD graphics card and an independent GTX graphics card. So I just opened device manager and disabled the Intel GPU and that fixed the Spyder launching issue. I suspect the problem was caused by some compatibility error between Spyder/intergrated GPU drive/Windows.

**Comment by ccordoba12** [comment]
Ok, thanks a lot for that!

**Comment by CAM-Gerlach** [comment]
@ccordoba12 FYI, I reproduced the same behavior on my (factory-fresh, clean-installed) Windows 10 (1803) test machine with only the default Windows Defender and firewall disabled, and regardless of which GPU was enabled or how I'd installed Spyder 4. It only occurred with Spyder 4 (not when downgrading to 3.3.1 in the same env), and did not experience the same issue running through the identical procedure and environment on my Windows 8.1 machine even with Windows Firewall enabled. The above fix did not work, despite also have a similar Intel/Nvidia GPU setup.

However, when I then ran ``conda install pyqt=5.6`` (which downgraded Qt, PyQt, QtConsole and sip) and then ``spyder`` or ``bootstrap,py spyder`` agian, the problem did not occur, and most strangely when I upgraded all the way back to PyQt 5.9.2, Qt 5.9.6 and QtConsole 4.4, everything worked fine. Even creating a new environment following the identical procedure resulted in everything working this time. So, I'm not 100% sure what's going on, but users experiencing this can try ``conda install pyqt=5.6``, then make sure Spyder works, then upgrade back with ``conda update pyqt qt qtconsole``

More details about what I tried, what worked and what didn't:

<details>

Problem occurred on:
**Windows 10 (1803)**
**Spyder 4.0.0beta1 (``-c spyder-ide``)/``git checkout master``**
Python 3.6.5-3.6.6
**PyQt 5.9.2/Qt 5.9.6**


Things that made no difference both when Spyder worked and when it didn't:
* Firewall settings
* Disabling/enabling Intel/Nvidia GPUs, either through Device Management or Nvidia Control panel
* How I launched Spyder (bootstrap.py vs. pre-packaged ``spyder``)
* Resetting preferences


More details:

Both those machines have identical hardware (they're two copies of the same laptop model), with a Nvidia GTX 670M and an Intel HD4000, and Spyder was installed in brand-new, identical clean environments on each (just ``conda install -c spyder-ide spyder ``) both starting from the packaged beta via ``spyder``, and running from a Github clone of the latest ``master``.

I tried both setting the Nvidia GPU as the global preferred GPU for everything in the Nvidia control panel, as well as disabling the Intel one in device manager, but even after restarting Anaconda prompt and trying to launch Spyder via the above methods, the problem still reoccurred. Switching to Spyder 3.3.1 in the same environment with ``conda install -c defaults spyder spyder-kernels=0`` on the Win 10 machine, it launched normally with or without any of the above.

Finally, I checked out an older ``master`` version from before the spyder-kernels changes; specifically, the commit merging the ``Release 3.2.8`` commit to ``master`` (``02ec24d1``), and again experienced the issue. Checking out the aforementioned commit on the 3.x branch, the one tagged v3.2.8 (``801d2732``), the problem is again gone, and I can even launched (more or less successfully) a checkout from the first commit of the master branch that diverged from 3.x (as of Spyder 3.0.0). This was all before trying to downgrade Qt/PyQt which resulted in the problem not re-occuring even tin the same configuration. So there was *something* unique to the master codebase from before that time that was triggering the issue. If I could actually make it start happening again, I could ``git bisect`` and find it but it seems not worth the effort at this point.

</details>

**Comment by ccordoba12** [comment]
@CAM-Gerlach, the new `software` option for opengl could be of help here. Could you try it and let me know if it works for you? Thanks!

**Comment by ccordoba12** [comment]
Please see PR #7700 to see how to use it.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Thanks. I actually saw that after I wrote the post, and wondered if that might have made an impact. However, as I mentioned above, I've been unable to reproduce the issue again after, at the very end of trying the steps described in the "Details" dropdown without success, I downgraded Qt/PyQt and upgraded again in that environment, even in a totally new environment following the exact same steps that produced the problem originally. If I do run into other Qt-related issues in the future, I'll be sure to try that, and if it is a common solution to a common issue, we can add it to the Troubleshooting Guide.

Qt WebEngine-wise I do get command-line warnings on either machine about being unable to move the WebEngine cache if I have another copy of Spyder open (since it's using it), but it doesn't cause any actual issues and in any case is presumably entirely unrelated.

**Comment by Tiiiiii** [comment]
> FYI, I ran into the same problem on my (factory-fresh, clean-installed) Windows 10 (1803) test machine with only the default Windows Defender and firewall disabled, and regardless of which GPU was enabled or how I'd installed Spyder 4. It only occurred with Spyder 4 (not when downgrading to 3.3.1 in the same env), and did not experience the same issue running through the identical procedure and environment on my Windows 8.1 machine even with Windows Firewall enabled. The above fix did not work, despite also have a similar Intel/Nvidia GPU setup.
> 
> However, when I then ran `conda install pyqt=5.6` (which downgraded Qt, PyQt, QtConsole and sip) and then `spyder` or `bootstrap,py spyder` agian, the problem did not occur, and most strangely when I upgraded all the way back to PyQt 5.9.2, Qt 5.9.6 and QtConsole 4.4, everything worked fine. Even creating a new environment following the identical procedure resulted in everything working this time. So, I'm not 100% sure what's going on, but users experiencing this can try `conda install pyqt=5.6`, then make sure Spyder works, then upgrade back with `conda update pyqt qt qtconsole`
> 
> More details about what I tried, what worked and what didn't:

Thanks and it surprisingly works

**Comment by CAM-Gerlach** [comment]
As a general FYI for anyone else with this problem reading this thread, @Antzxz mentioned on  #8211 that uninstalling "Dell Backup and Recovery" (which is known to cause many conflicts with other software, including Spyder) and reinstalling Anaconda solved this problem for them.

**Comment by andywinhold** [comment]
Should it help anyone else:
I compared the packages in my base environment (where spyder 5 works) with my environment that had this issue opening spyder 4. I changed qtawesome from 1.2.2 (issue env) to 1.0.3 (base env) and that looks to have solved the issue. I should look at updating to 5 for this env. 
Thanks for the help on this thread!
