### ISSUE TITLE
Maximize current plane works wrong

### ISSUE THREAD

**Issue by mlearnx** [spyder-ide/spyder#7693]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I frequently use maximize the pane to switch between different ones for productivity. 
Since the begining of Spyder 3.3 it does not properly maximize a pane of my interest (command window, text editor and all others).   

I updated to the recent version v 3.3.1 but still the problem exists.

I tested Spyder on two machines: Windows 10 and Windows 7. 
Thank you so much for your help. 

### What steps reproduce the problem?
1.  Click the maximize pane from the main window or use a shortcut. 
2. 
3. 

### What is the expected output? What do you see instead?
Please see the image below. The problem is that it has big white spaces.

![a1](https://user-images.githubusercontent.com/11430933/44136686-79fd6180-a08f-11e8-888b-43fdf195c9df.png)
![a2](https://user-images.githubusercontent.com/11430933/44136687-7a2020f8-a08f-11e8-86c6-411f66b1bcd8.png)

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3.1
* Python version: 3.6.6
* Qt version: 5.9.6
* PyQt version:  5.9.2
* Operating System name/version:  Windows 7 and Window 10

### Dependencies

```
IPython >=4.0     :  6.5.0 (OK)
cython >=0.21     :  0.28.4 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.15.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.6.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.9.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
sphinx >=0.6.6    :  1.7.6 (OK)
sympy >=0.7.3     :  None (NOK)
```

**Comment by jitseniesen** [comment]
After mdtjan mentioned on gitter they had the same problem on Ubuntu, I had a look on my Linux Fedora computer. I see the same problem on a fresh environment created with `conda create spyder`, which installs Python 5.7.0, Qt 5.9.6 and PyQt 5.9.2. The problem disappears after `conda install qt=5.9.5`, which downgrades to Python to 5.6.6 (and Qt to 5.9.5, obviously) and leaves PyQt unchanged.

**Comment by CAM-Gerlach** [comment]
@jitseniesen I tested the maximize command on various panes of a number of configurations.

The upshot is that the one variable that caused this problem is going from Qt 5.9.4 to 5.9.5; Python version, platform, install method, pyopengl, and Spyder version all didn't make a difference in my testing.

The only changes between Fedora 28 configs that didn't work maximizing, and the one that did, were:

```
fongconfig:
2.13.0 -> 2.12.6
freetype:
2.9.1 -> 2.8
qt:
5.9.6 -> 5.9.5
```

and on Windows 8.1 x64, it was just the qt 5.9.5 -> 5.9.6 change.


Probably unrelated, but the Spyder About dialog and the ``bootstrap.py`` script (all versions tested) reports Qt 5.9.4 was installed even if 5.9.5 or 5.9.6 is the actual Qt version, e.g. as found by ``conda list qt``, on both Fedora 28 and Windows 8.1.

Full platforms tested list:

WORKS:
Spyder 3.2.8 Miniconda Defaults
Python 3.6.5 x64 | Qt 5.9.4 | PyQt 5.9.2 | Fedora 28 x64

Spyder 3.3.1 Miniconda Defaults
Python 3.6.5 x64 | Qt 5.9.4 | PyQt 5.9.2 | Fedora 28 x64

Spyder 3.3.1 Miniconda Defaults
Python 3.6.5 x64 | Qt 5.9.5 | PyQt 5.9.2 | Fedora 28 x64

Spyder 3.3.1 (Github checkout of release commit)
Python 3.6.6 x64 | Qt 5.9.4 | PyQt 5.9.2 | Windows 8.1 x64

Spyder 3.3.1 (Github checkout of release commit)
Python 3.6.6 x64 | Qt 5.9.5 | PyQt 5.9.2 | Windows 8.1 x64


MAXIMIZE PROBLEM:
Spyder 3.2.8 Miniconda Defaults
Python 3.6.5 x64 | Qt 5.9.6 | PyQt 5.9.2 | Fedora 28 x64

Spyder 3.3.1 Miniconda Defaults
Python 3.6.5 x64 | Qt 5.9.6 | PyQt 5.9.2 | Fedora 28 x64

Spyder 3.2.8 Anaconda Defaults
Python 3.6.6 x64 | Qt 5.9.6 | PyQt 5.9.2 | Windows 8.1 x64

Spyder 3.3.1 Anaconda Defaults
Python 3.6.6 x64 | Qt 5.9.6 | PyQt 5.9.2 | Windows 8.1 x64

Spyder 3.3.1 (Github checkout of release commit)
Python 3.6.6 x64 | Qt 5.9.6 | PyQt 5.9.2 | Windows 8.1 x64


To note, ``conda install qt=5.9.5`` on Fedora 28 worked when updating from qt 5.9.4, but when downgrading from 5.9.6 (and performing the same operations) Spyder wouldn't start and I got the following error:

Inconsistency detected by ld.so: ../elf/dl-tls.c: 481: _dl_allocate_tls_init: Assertion 'listp->slotinfo|cnt].gen <= GLidl_tls_generation]' failed!

However it is pretty clearly not related to Spyder or this issue.

**Comment by CAM-Gerlach** [comment]
Also, for the record I tested PyQt 5.6.0 | Qt 5.6.2 and it also works.

**Comment by ccordoba12** [comment]
Pinging @mingwandroid about this one. It looks like a Qt bug introduced in its latest release.

**Comment by CAM-Gerlach** [comment]
And no @mingwandroid I didn't screw up and use ``conda-forge`` this time, haha! I've made sure to stay away from that since you gave me that advice.

**Comment by CAM-Gerlach** [comment]
> The problem is resolved by following the @jitseniesen suggestion, and the maximize pane works like a charm.

Glad to hear it works for you, @mlearnx . Just to be clear, this is only a temporary and per-user workaround, and will not suffice for many use cases going forward if not addressed properly.

**Comment by mingwandroid** [comment]
For people using 5.6.6, a workaround for this is that after maximiizing the pane, go to the divider line and move it a pixel, the Window should then get maximized correctly.

**Comment by ccordoba12** [comment]
Thanks a lot Ray for helping us with this one!

**Comment by mingwandroid** [comment]
I built Qt locally with this change and can confirm it fixes this issue for me. I have a few loose ends with Qt to tie up (looking at adding QtCharts and a Designer plugin bug) before I release it though.

**Comment by mingwandroid** [comment]
No problem @ccordoba12, good to shake these bugs out.

**Comment by CAM-Gerlach** [comment]
Thanks so much @mingwandroid !

**Comment by ccordoba12** [comment]
Closing because this is not a Spyder problem. As Ray said, it should be fixed once new Qt packages are uploaded by Anaconda.
