### ISSUE TITLE
Translation to Arabic

### ISSUE THREAD

**Issue by geohadab** [spyder-ide/spyder#7756]
hello, 

I want to help in translating spyder to Arabic .

**Comment by ccordoba12** [comment]
Thanks for offering your help to do that. Two recommendations:

1. Please do your work against our master branch and not our 3.x one.
2. You should use a special program to facilitate the translation process. The only one I know is called Poedit. It works pretty well on Linux, I don't know in other platforms.
3. You need to load [this file](https://github.com/spyder-ide/spyder/blob/master/spyder/locale/spyder.pot) in your translation program ad start doing it.
4. You need to be available to update your translation every couple of months or so.

I'm going to close this issue because it's not really a bug report, but please feel free to keep posting comments here in case you have doubts.
