### ISSUE TITLE
Spyder Debug Error -- Crashes spyder app from desktop 

### ISSUE THREAD

**Issue by Sirish6484** [spyder-ide/spyder#7763]
Open Anaconda Prompt

Browse through Anaconda instalatino folder from the prompt

type in the below command

pip instal -U spyder

**Comment by ccordoba12** [comment]
You must never use pip to update Spyder when using Anaconda. We loudly warn about this, for example here:

https://github.com/spyder-ide/spyder/releases/tag/v3.3.1

I'm afraid you'll need to uninstall and reinstall Anaconda to fix any problems you're seeing because using pip most probably corrupted your installation.
