### ISSUE TITLE
Connect to remote kernel: Have a choice between password or keyfile

### ISSUE THREAD

**Issue by bcolsen** [spyder-ide/spyder#7905]
Feature Request:

As discussed in #7898 

![image](https://user-images.githubusercontent.com/10513354/45583606-b06d1c00-b882-11e8-8b64-7638b64ebbcb.png)
![image](https://user-images.githubusercontent.com/10513354/45583611-c2e75580-b882-11e8-988f-ace5f392ad4f.png)

**Comment by bcolsen** [comment]
@ccordoba12 @CAM-Gerlach 

I cleaned up the layout with a grid and since we are going in master I separated out the host, port and user so there is no special host name syntax. I even got rid of the place holder text because it was mostly noise at this point. The port number is set to 22 as a default value when the dialog is created.

Potential downside: If you're connecting to a local kernel now there will be even more grayed out stuff at the bottom, but thats mostly aesthetics. 

Any comments or suggestions?

![image](https://user-images.githubusercontent.com/10513354/45593411-757eed00-b943-11e8-8fd3-e55e32980345.png)

**Comment by CAM-Gerlach** [comment]
On one hand, its somewhat more clear and explicit splitting the components up, and allows you to put in ``22`` by default (which I didn't really have a way to do otherwise before). On the other hand, it is a lot of fields all densely packed together, many of which don't require the amount of space they are given.

Overall, I suggest the following tweaks:

* Hostname and username are typically one word, by convention
* You could put ``Port:`` to the right of the ``Hostname`` field, like so:
  Hostname: ``____________________________``  Port: ``______``
* Add a half-newline or so worth of vertical seperation between Hostname/Port number and username, to group username more closely visually with its accompanying credentials and break up the dense block of text entry fields

**Comment by bcolsen** [comment]
How about now?

![image](https://user-images.githubusercontent.com/10513354/45593865-78321000-b94c-11e8-883f-2e4403817bad.png)

**Comment by CAM-Gerlach** [comment]
Looking much better IMO, thanks!

Now that I see it, it makes more sense to put the break between Username and the credential options rather than Hostname and Username, both conceptually and in terms of visual balance. Also, you could make the port number field around ~2 characters bigger so it looks less cramped, and can fit a full 6-digit port number with a bit of additional margin.

**Comment by bcolsen** [comment]
@CAM-Gerlach Thanks for the suggestions to make this better.

I thought I'd give groups a try to give the separation you're talking about. There is more white space than without groups but I think the clarity of the authentication options has increased. What do you think?

![image](https://user-images.githubusercontent.com/10513354/45607853-5bf5a800-ba0c-11e8-8bed-2b11da7d69b0.png)

**Comment by CAM-Gerlach** [comment]
I agree, it looks much nicer with the groups; the separation is cleaner and it groups the two options, while also breaking up the dialog visually so it isn't such a large block of contiguous fields. Great idea!

**Comment by ccordoba12** [comment]
I really like this! Thanks a lot @bcolsen!

I only have a couple of suggestions:

1. Add some vertical space between the top QLabel and `Kernel ID/Connection file` and also between the last one and `This is a remote kernel`. You can take a look at our Git authentication dialog to see how to do it.
2. Please restore the default text in `Hostname`, without the port part, of course.

**Comment by CAM-Gerlach** [comment]
Now that I think of it, its best to shorten ``Kernel ID/Connection file`` to ``Kernel ID/file:`` since otherwise the placeholder text doesn't fit by default, and it is described more completely in said placeholder text as well as the label.

> You can take a look at our Git authentication dialog to see how to do it.

What you previously did between ``Hostname`` and ``Username`` should be fine between the top label and the ``Kernel ID`` field, while double that might be better between the latter and the checkbox (since the top label directly describes that field in particular, so we want to create the appropriate visual association there).

> 2. Please restore the default text in `Hostname`, without the port part, of course.

@ccordoba12 Huh? The default text in the current version is ``username@hostname:port``. Now that ``username`` and ``hostname`` are each separated out into their own fields, the all that's left of the default text is just ``hostname``, which merely repeats the exact same text as the field title, serving no purpose except looking needlessly repetitive.

**Comment by ccordoba12** [comment]
> Huh? The default text in the original version is username@hostname:port

Sorry, you're right.

**Comment by ccordoba12** [comment]
@bcolsen, we should also add a link to our documentation in a note below `This is a remote kernel`. This way people will find more easily how this process works.

**Comment by CAM-Gerlach** [comment]
Good thinking; [this](https://docs.spyder-ide.org/ipythonconsole.html#connect-to-an-external-kernel) would be the section to link to. It would make sense to just incorporate the link directly into the checkbox label, thus 

> [ ] This is a remote kernel ([more details](https://docs.spyder-ide.org/ipythonconsole.html#connect-to-an-external-kernel))

Also, since you have the space anyway, change ``Keyfile`` to ``SSH keyfile`` for clarity.
