### ISSUE TITLE
Show files that are not Python files in the Outline Explorer

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#7982]
## Problem Description
As suggested by @CAM-Gerlach in https://github.com/spyder-ide/spyder/pull/7968#discussion_r221500554, text files that are not python files should be visible in the Outline Explorer. 

This would be another step forward into making the Outline Explorer a viable proxy for a vertical tabbar for the Editor Stack.

![text_file_in_oe](https://user-images.githubusercontent.com/10170372/46361316-48b52000-c63b-11e8-8a56-2696cc41c8d6.gif)

@ccordoba12

First thing first, do you agree with this?

Second, do you want to add this as an additional options in the context menu of the outline explorer or be the default behavior? If you ask me, I do not see the added benefit in adding another option for this.

**Comment by CAM-Gerlach** [comment]
As a further comment, even when "Show all files" is enabled, the outline explorer is completely disabled when on a non-Python file so the user can't even switch to any Python file that is shown there. Should this be part of this issue, or a separate one?

> Second, do you want to add this as an additional options in the context menu of the outline explorer or be the default behavior? 

For what its worth, I agree with you here, since I really don't see the use case where "Show all files" is selected but the relatively modest additional space occupied by one-line entries for non Python files would be a significant hindrance. Furthermore, that entry does say "show *all* files", not *show all *Python* files" so its already implied.

**Comment by jnsebgosselin** [comment]
> As a further comment, even when "Show all files" is enabled, the outline explorer is completely disabled when on a non-Python file so the user can't even switch to any Python file that is shown there. Should this be part of this issue, or a separate one?

As part of this issue is alright I think. No matter what, this is going to be fixed as part of this enhancement proposal.

**Comment by CAM-Gerlach** [comment]
Yeah, either part of this one or your Epic.

**Comment by ccordoba12** [comment]
I agree with this and I don't see the need of adding another option for this.

In the future, we could add code folding for other file types and show that info in the outline explorer too.
