### ISSUE TITLE
Order of root file items in the Outline Explorer should be synced with that of the current EditorStack

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#7993]
## Problem Description

As mentioned by @CAM-Gerlach in https://github.com/spyder-ide/spyder/pull/7968#discussion_r221500554, the outline explorer is still ordered alphabetically, rather than the order of the tabs in the Editor. It would be nice to have the option to either alphabetize it or make it follow the order of the editor, since both could potentially be useful depending on one's workflow.

This would be another step forward into making the Outline Explorer a viable proxy for a vertical tabbar for the Editor Stack.

@ccordoba12 @CAM-Gerlach

- Should we add an option in the context menu for this? Something like: `Show files sorted alphabetically` or something like that? Checking or unchecking this option would not impact the order of the files in the tabbar of the current EditorStack, only the order of the root file items in the Outline Explorer.

- Alternatively (or additionally), we could add an action in the context menu (with a corresponding button in the Outline Explorer toolbar) to actually sort the files alphabetically in the Outline Explorer and in the tabbar of the current EditorStack.

Also, do you think that one of the above suggestions could be a valid solution for Issue #5911?

**Comment by ccordoba12** [comment]
> Alternatively (or additionally), we could add an action in the context menu (with a corresponding button in the Outline Explorer toolbar) to actually sort the files alphabetically in the Outline Explorer and in the tabbar of the current EditorStack.

I'd prefer to implement this option.

> Also, do you think that one of the above suggestions could be a valid solution for Issue #5911?

If we decided to implement my suggestion, then sure.

**Comment by CAM-Gerlach** [comment]
I'd strongly favor the first option *for the outline explorer* (I have no issues with a distinct *Editor* option to sort tabs alphabetically, either temporarily or enforced, but that's secondary to this particular enhancement and IMO is rendered largely unnecessary by it). It is rather jarring and unexpected UX, serves a distinct purpose from this feature, would break one of the two major use-cases for it and the former approach (along with the other changes to the Outline Explorer @jnsebgosselin 's been making) in fact appears to more directly address the actual underlying user problem expressed in #5911, which is

> When a project consists of 10 or more .py-files, at some point searching for the correct tabs becomes really unhandy...

This, of course, is the *precise* use case with these changes that the Outline Explorer, *not the tab bar itself*, has been explicitly designed to fill. With regard to the alphabetization specifically, the reporter elaborates

> When my currently activated tab is in the middle of, say, 10 open tabs and I'm looking for a module which I cannot see directly in the tab row, I have to search for it, since I don't know whether it is located to the left or to the right from my current tab position.

Of course, the Outline Explorer now essentially bypasses that motivating problem—there's no longer a need to scroll to find the file, as they are all visible (at least to a reasonable number). However, particularly with a lot of files, it is still useful to sort it alphabetically to make scanning for a file faster, for the same reasons.

Thus, one of the two use-cases I was envisioning when I suggested retaining both options is, in fact, very similar to what is suggested in the linked issue—wanting to quickly browse through the list alphabetically to find a particular file, toggling alphabetical mode on and then off when needed (the latter of which would restore the original order, i.e. the user-set order of the tab bar). For this, a toggle button on the toolbar would indeed be particularly helpful.

Meanwhile, however, as the user is already using the Outline Explorer to find the file anyway (the reason they toggled the alphabetical mode there after all), sorting the tab bar too serves no real purpose for this and could confuse or even panic the user if their familiar, user-set tab order is suddenly disrupted with no obvious warning (as it is not at all intuitive that a setting within the Outline Explorer would affect their Editor tabs). In fact, they may be doing so in order to move the tab to a different spot in the list, which requires toggling alphabetical mode back off (or else a lot of user frustration).

The other use case is to keep the outline explorer on alphabetical mode permanently for a project per the user's preference for using it that way, while arranging their editor tabs as normal  (which, I note, is exactly how Spyder currently works). This simply does not work if alphabetical mode in the outline explorer and alphabetizing editor tab order are inexorably linked like this, as this suggestion explicitly links the two.

Therefore (TLDR) the first option solves the actual underlying problem in that thread, while the second option (mandatory linking the two orders) offers minimal or no direct benefit for the use cases presented here and in the linked issue, while offering serious downsides or completely breaking them.

**Comment by jnsebgosselin** [comment]
I agree with @CAM-Gerlach on this.

I also think we should go with the first option I've proposed, i.e adding an option to sort items of the `Outline Explorer` alphabetically, without altering the Editor tabbar.

I also agree that going with the second option would add Ux confusion if added to the `Outline Editor`. A `sort files` action should be added in the cog menu of the Editor instead, but that is for another issue.

**Comment by CAM-Gerlach** [comment]
Somewhat related—with the number of different options, particularly toggable ones that the Outline Explorer has acquired, shouldn't it have a "cog"/"gear" menu as well to make them more obvious to the user? If they didn't happen to check the context menu, users might never know they are there otherwise. Is there a general convention we follow in these sorts of situations as to when and what to put in a cog/gear menu?

**Comment by jnsebgosselin** [comment]
> Somewhat related—with the number of different options, particularly toggable ones that the Outline Explorer has acquired, shouldn't it have a "cog"/"gear" menu as well to make them more obvious to the user? If they didn't happen to check the context menu, users might never know they are there otherwise. Is there a general convention we follow in these sorts of situations as to when and what to put in a cog/gear menu?

It already has one, with the same options/actions as in the context menu.

![image](https://user-images.githubusercontent.com/10170372/46444132-8c448280-c73e-11e8-977a-c1624019dba2.png)

**Comment by CAM-Gerlach** [comment]
My bad, I though I checked in Spyder 4, but it must have been Spyder 3 instead. Thanks for the catch.

**Comment by jnsebgosselin** [comment]
This was added recently in PR #7866, but this also introduced a glitch when starting Spyder where the new cog menus are stacked and displayed in the top left corner of Spyder for 2-3 seconds while the plugins are being generated.

**Comment by ccordoba12** [comment]
> I agree with @CAM-Gerlach on this.

Ok, no problem.

**Comment by jnsebgosselin** [comment]
> This was added recently in PR #7866, but this also introduced a glitch when starting Spyder where the new cog menus are stacked and displayed in the top left corner of Spyder for 2-3 seconds while the plugins are being generated.

I was wrong, the glitch was introduced by the LSP patch.

**Comment by luciansmith** [comment]
I was asked to comment as to whether this proposal would fix my issue with #5911, and for me, it does:  the actual tab order in the editor is left alone, but the list of files in the Outline Explorer can be sorted alphabetically.  That would be perfect!

**Comment by fgotzens** [comment]
I was also asked to comment: I really like the proposed solution, so to this end, one can have at least the outline explorer always in alphabetical order or synced to the tab order, which I think is a huge step forward. However, in contrast to @luciansmith this does not entirely fix issue #5911 since I would still be happy if a one-way option to sort the tabs (so no toggling!) would be provided in a future version. Nonetheless: Thank you for your great work so far!

**Comment by jnsebgosselin** [comment]
Thank you both for your feedback @luciansmith and @fgotzens 

> However, in contrast to @luciansmith this does not entirely fix issue #5911 since I would still be happy if a one-way option to sort the tabs (so no toggling!) would be provided in a future version. Nonetheless: Thank you for your great work so far!

OK thank you, so I will leave #5911 opened until I implement an action to sort the tabs permanently in the cog menu of the Editor.
