### ISSUE TITLE
Restore option to open a new editor window

### ISSUE THREAD

**Issue by gerazov** [spyder-ide/spyder#8011]
Hi guys,

First let me say kudos to the whole team and community for version 4! Even though it is still in beta I've been using it with no problems and it's amazing! I just love the new features in the editor e.g. the foldable code, the vertical guides and scrolling past the end! Great job!

I am missing one feature from Spyder3 though - the option to open a new window of the editor - it was extremely convenient when using a dual monitor display. Is it possible to put it back?

Thanks for all your hard work!

**Comment by jnsebgosselin** [comment]
Thanks for the report and the kind words

>I am missing one feature from Spyder3 though - the option to open a new window of the editor - it was extremely convenient when using a dual monitor display. Is it possible to put it back?

You mean the option to have an Editor in the main window, and another Editor in a detached window?

**Comment by bgerazov** [comment]
Hmm that's a bummer - because this bounds us to edit on one monitor ...

I think it should be doable though - yesterday I succeeded in undocking the Editor and then re-instantiating a new one using the `View > Panes > Editor` which was unchecked. So I had an Editor in a separate window plus the docked one. Also the undocked Editor actually had the Window Manager title bar - so it was really a window on its own.

Today however when I undock the Editor pane it doesn't have the WM title bar and the Editor pane option remains checked so I can't replicate :disappointed:

**Comment by jnsebgosselin** [comment]
> I think it should be doable though - yesterday I succeeded in undocking the Editor and then re-instantiating a new one using the `View > Panes > Editor` which was unchecked. So I had an Editor in a separate window plus the docked one. Also the undocked Editor actually had the Window Manager title bar - so it was really a window on its own.
> 
> Today however when I undock the Editor pane it doesn't have the WM title bar and the Editor pane option remains checked so I can't replicate 😞

What you are describing is not intended by design, but if its a valid workaround for your problem, why not exploit it!

To reproduce what you were able to do yesterday, make sure the option `View > Lock Panes` is checked, then detach the `Editor` with the little icon in the Editor toolbar, not through the `Undock Editor Window` action in the Cog menu, then show the docked editor back with `View > Panes > Editor`. In fact, you can create the number of detached Editor you want with this method :)

IMO, the way undocking and creating new windows is working currently in Spyder 4 is very confusing.

![image](https://user-images.githubusercontent.com/10170372/46536513-c156ef00-c87c-11e8-8331-ff2afb4a171b.png)

**Comment by ccordoba12** [comment]
Jean, this looks like a bug. What should we do to fix it?

**Comment by bgerazov** [comment]
Ahaha :smiley: sweet!

It would be nice if this stays as an option. (Please don't fix it :+1: )

And the Outline works! - but if you go for `Maximize current pane` in the main window - then that Outline links only for the first undocked window.

**Comment by ccordoba12** [comment]
> IMO, the way undocking and creating new windows is working currently in Spyder 4 is very confusing.

I think I know what you mean: we should switch the behavior on the *Undock* action and the little button that undocks in dock widgets, right?

**Comment by jnsebgosselin** [comment]
> Jean, this looks like a bug. What should we do to fix it?

Yes, this is a bug, but this doesn't seem to cause any error.

> > IMO, the way undocking and creating new windows is working currently in Spyder 4 is very confusing.
> 
> I think I know what you mean: we should switch the behavior on the _Undock_ action and the little button that undocks in dock widgets, right?

I think that this is a good solution.

It is confusing currently because clicking on the _restore_ button in the titlebar of the dockwidgets creates a new window if _Lock panes_ is checked and undocks the plugin if _Lock panes_  is not checked. IMO this is confusing and there is no way to know that the behavior of the _restore_ button is linked with the _Lock panes_ action.

 So I think:
- Clicking on the  _restore_ button should always undock plugins, not matter what is the state of the _Lock panes_ option.
- A _New Window_ action should be added to each plugin cog menu.

**Comment by ccordoba12** [comment]
This is basically a duplicate of #5515.

**Comment by ccordoba12** [comment]
Sorry, I read carefully this issue and I think this is a valid request, given the significance of the Editor over the other plugins.

Therefore, I'll restore this option in PR #8192.

**Comment by Amishaaaaaa** [comment]
![IMG20221002152828.jpg](https://user-images.githubusercontent.com/104100030/193448481-ab6079e1-f475-4ace-bc70-11319c3325a4.jpg)

How to get a new editor...i cannot find where to code since closed both the editor and the kernel. Dont know how to get it back.

**Comment by ccordoba12** [comment]
You need to go to the menu `View > Panes` to restore closed panes.

**Comment by Amishaaaaaa** [comment]
done. Thankyou soo much!
