### ISSUE TITLE
error occured after failure of spyder update

### ISSUE THREAD

**Issue by kafkapple** [spyder-ide/spyder#8036]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

    plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.9.4, PyQt5 5.9.2 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.4 (OK)
numpy >=1.7      :  1.15.0 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
To fix this you need to do the following steps:

1. Stop using `conda update --all` in the future, in case you're using it, because that's what's breaking Spyder.
2. Close Spyder.
3. Open an Anaconda Prompt
4. Run there

        conda remove spyder-kernels
        conda install spyder-kernels=0.*
        conda update spyder

5. Start Spyder again.

That should update Spyder correctly and fix the error you reported above.
