### ISSUE TITLE
spyder update Automatic error report

### ISSUE THREAD

**Issue by savvys84** [spyder-ide/spyder#8157]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
used pip install -U spyder

error says found already installed spyder 3.2.8 cannot uninstall this

**Comment by ccordoba12** [comment]
Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.

**Comment by ccordoba12** [comment]
Then you don't need pip to update Spyder but conda:

    conda update spyder

We warn about this in several places: https://github.com/spyder-ide/spyder/releases/tag/v3.3.1

If you used pip before to update other packages, I'm almost sure you corrupted your Anaconda installation. So please uninstall it and reinstall it again.
