### ISSUE TITLE
Warnings and errors from PyLS don't go away after fixing them, even when saving file

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#8172]
## Problem Description

PyLS errors and warnings (e.g. from pycodestyle, pyflakes, etc) don't go away after fixing their cause; even after saving and waiting 10-20+ seconds, they only disappear when deleting the entire line. This does not occur, obviously, in Spyder 3.

### What steps reproduce the problem?

1. Write a line of code that prompts a PyLS (pycodestyle, pyflakes, etc) error or warning. Save.
2. Modify line to fix error/warning. Save.
3. Delete entire line. Save.

### What is the expected output? What do you see instead?

Expected error to go away after step 2. Instead, only disappeared after step 3.

## Versions

* Spyder version: master (latest as of the post date)
* Python version: 3.6.6
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 8.1 x64

PyLS 0.19.0 (``pip`` install in conda env)

**Comment by emanspeaks** [comment]
I added the following line to `spyder.plugins.editor.widgets.editor.save` inside the try block, around line 1670: `finfo.editor.document_did_change()` 

That fixed it for me.

**Comment by emanspeaks** [comment]
There is also call to `notify_save()` above that, but that call effectively does nothing because `will_save_notify` defaults to False in the `CodeEditor` constructor.  Also because it looks like PyLS isn't coded to respond to the `willSave` request.  PyLS is, however, configured to respond to `didSave`, which calls the linter.  

I'd recommend updating `notify_save` method in the CodeEditor to submit a `didSave` request instead of `willSave`.  And either remove the `if will_save_notify` wrapper  or make it default to True.

**Comment by ccordoba12** [comment]
Thanks @emanspeaks for digging into this one! Could you prepare a PR with your recommendations? Thanks!

**Comment by emanspeaks** [comment]
@ccordoba12 just an updated, I have been working on this.  I have a number of LSP-related updates I am trying to gather up into one PR once I get everything working.

**Comment by ccordoba12** [comment]
Thanks a lot for your help!
