### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by enAnne** [spyder-ide/spyder#8210]
I just type "python -m pip install --pre -U spyder" in my CMD.exe.
Then it gave the error:
Found existing installation: spyder 3.2.8
Cannot uninstall 'spyder'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by ccordoba12** [comment]
Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.
