### ISSUE TITLE
Title field of error dialog is too small in macOS

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#8344]
This can be clearly seen in the following image:

![imagen](https://user-images.githubusercontent.com/365293/49333052-faae9100-f585-11e8-96a7-3033fbd160c8.png)

----

@juanis2112, this field is defined here:

https://github.com/spyder-ide/spyder/blob/master/spyder/widgets/reporterror.py#L158

I don't know exactly how to do this, but QLineEdit has several methods to define its size (e.g. `setMinimumWidth` or `setMaximumWidth`). You can find the full list here:

http://doc.qt.io/qt-5/qlineedit-members.html

I'm sure one of them will allow us to set the QLineEdit width to expand to the size of the report error dialog.

**Comment by jnsebgosselin** [comment]
Maybe another way to address this would be to explicitly set the [FieldGrowthPolicy](http://doc.qt.io/qt-5/qformlayout.html#fieldGrowthPolicy-prop) of the `QFormLayout` to `QFormLayout.ExpandingFieldsGrow`. By default, it is set to `FieldsStayAtSizeHint` for MacOS.

If you still want to go with the `setMinimumWidth`, I suggest to calculate the width with `QFontMetrics` instead of harcoding a value.

**Comment by ccordoba12** [comment]
Thanks for the tip @jnsebgosselin!
