### ISSUE TITLE
when switching  inline to automatic in ipython console graph section, 2 or three graph shows in one window and overlap , instead of showing two seperate graph window.  :(

### ISSUE THREAD

**Issue by applemorshed** [spyder-ide/spyder#8463]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
when switching  inline to automatic in ipython console graph section, 2 or three graph shows in one window and overlap , instead of showing two seperate graph window.  :(
i am new here.

### What steps reproduce the problem?

1. when using inline ipython console show properly.

2. when use automatic , seperate graph window shows all graph in one graph and all graph overlap.
3. for example
import matplotlib.pyplot as plt
a=[1,2,3,4]
b=[5,6,3,8]
c=[4,2,6,7]
d=[3,6,3,3]
plt.scatter(a, b)
plt.xlabel("boston housing price t_test")
plt.ylabel("Predictions")
plt.title("For Single feature")
plt.show()

plt.scatter(c, d )
plt.xlabel("boston housing price t_test")
plt.ylabel("Predictions")
plt.title("For all features")
plt.show()

when you run it you see both of the graphs in one window instead of a two separate window.

### What is the expected output? What do you see instead?
two seperate graph window.  one graph window showing all graph.
### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by bcolsen** [comment]
Thanks for reporting this issue but this is not a Spyder bug. There is a problem in your code. Please be sure to test your script in the anaconda prompt with `python myscript.py` and from the `jupyter-qtconsole` at least before reporting bugs here in the future.

But since this is your first bug report I'll help you out!

Your code has actually found an edge case in Matplotlib's interactive mode when using `plt.show()` twice in a script. This is why you should only use `plt.show()` once at the end of the script. Matplotlib will keep plotting on the same figure until a new figure is made with `plt.figure()`. To fix your code remove the middle `plt.show()` and place `plt.figure('single feature', clear=True)` before your first scatter and `plt.figure('all features', clear=True)` before your second.

**Comment by applemorshed** [comment]
Thank you for helping me out. I was wandering and thought it was a bug
because when I use my code directly to python instead of ipython it does
not overlap and its just work fine for me. and I did not find any place to
write or any email. Is not it that all platform of python should work
exactly same way.

**Comment by applemorshed** [comment]
Thank you very much for your help.
