### ISSUE TITLE
Improve IPython console Options menu

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#8478]
The Options menu of the IPython console has grown a lot lately:

![seleccion_001](https://user-images.githubusercontent.com/365293/50369667-5063d100-0567-11e9-8860-59bbc669b9a2.png)

My idea is to shrink it a bit, like this:

```
New console
Specialized consoles > Pylab / Sympy / Cython
----
Restart kernel
Connect to an existing kernel
Remove all variables
----
Rename tab
Show env vars
Show sys.path contents
Show elapsed time
```

Notes:
* `Specialized consoles` would be a submenu but only of the IPython console options menu. The main `Consoles` menu wouldn't have it.
* The last two actions in the screenshot above will be added to all plugins after PR #8192.

@spyder-ide/core-developers, what do you think?

**Comment by CAM-Gerlach** [comment]
Good thinking; what you have so far is a major improvement. Would these changes also affect the context menu similarly? 

A few comments:

* ``Connect to an existing kernel`` should definitely be in the first group, under ``Specialized consoles``, since it relates to opening a new Console tab (as does the first group) rather than modifying an existing one (as do the other actions in the second group).
* Similarly, since ``Rename Tab`` modifies the current Console tab, rather than is a general action (like the others in its group), it should go in the second group,
* What's the reason for including the ``Specialized consoles`` submenu in the context/options menu but not the main Consoles menu?

Also, a a detail note, I'd suggest naming it something like ``New IPython console``/``New specialized console`` for clarity and parallelism.

**Comment by bcolsen** [comment]
Generally I like this.

> What's the reason for including the Specialized consoles submenu in the context/options menu but not the main Consoles menu?

Do we even need a main Console menu? If we do it need it might as well have more things in it. 

I've always wondered why the stop command isn't in the menu and the remove variables is.

This might be out of scope but a restart kernel button next to the remove variables could be useful. I've been trapped in a live updating plot and the stop button wouldn't stop it but restart did trick. But it was hard to get focus long enough to click the drop down with a new figure popping up every second :-)

**Comment by CAM-Gerlach** [comment]
> Do we even need a main Console menu?

Yeah, I've always wondered that, since it relates to a particular pane. A few core functions from each pane (run profiler, run static analysis, open project, etc) are present in the menus, but the Consoles pane is the only one that gets its own menu, which is just a curiously abbreviated version of the main Consoles menu. IMO since its dedicated to one and only one pane and is based directly off that pane's menu rather than taking up space in another, we should either just make it identical (ideally sharing the same codebase) to reduce maintenance burden and user confusion, or remove it entirely.

> This might be out of scope but a restart kernel button next to the remove variables could be useful.

Maybe out of scope, but agreed—I almost never use Remove Variables but use Restart Kernel all the time.

**Comment by ccordoba12** [comment]
Ok, so let's go with

```
New console
Specialized consoles > Pylab / Sympy / Cython
Connect to an existing kernel
----
Restart kernel
Remove all variables
Rename tab
----
Show env vars
Show sys.path contents
Show elapsed time
```

> What's the reason for including the Specialized consoles submenu in the context/options menu but not the main Consoles menu?

Because the `Consoles` menu can be much taller than the Options one.

> Also, a a detail note, I'd suggest naming it something like New IPython console/New specialized console for clarity and parallelism.

I think that's too detailed and it'd also make the menu too wide.

**Comment by ccordoba12** [comment]
About your other comments:

> I've always wondered why the stop command isn't in the menu and the remove variables is.

I thought it was enough with the stop button. Do you think we should add it? (I'm a bit -1 on it).

> This might be out of scope but a restart kernel button next to the remove variables could be useful.

The thing the restart kernel action is blocking (i.e. it freezes the entire interface) so I wouldn't like people to start using it all the time. But if you feel this is important, please open a new issue about it.

**Comment by ccordoba12** [comment]
> I'm confused; that seems backward—you mentioned the Consoles menu wouldn't have it, while the option one would, yet its the Console menu that can be much taller as you say.

Yes, we don't need to create a submenu in the Consoles menu because it can be much taller.

> How about New special console

Ok, no problem.

> but IMO there should either be a clear rationale for why Remove all variables is in the options menu while the stop button isn't

There's no rationale. I just thought it was not necessary. So let's add it with this work.

**Comment by ccordoba12** [comment]
@juanis2112, let's go with this for the Options menu:

```
New console (default settings)
New special console >
    New Pylab console (data plotting)
    New SymPy console (symbolic math)
    New Cython console (Python with C extensions)
Connect to an existing kernel
----
Restart kernel
Interrupt kernel (<- This action will trigger the same action as the stop button)
Remove all variables
Rename tab
----
Show env vars
Show sys.path contents
Show elapsed time
```

And for the `Consoles` menu on top, please organize it like this

```
New console (default settings)
New Pylab console (data plotting)
New SymPy console (symbolic math)
New Cython console (Python with C extensions)
Connect to an existing kernel
----
Restart kernel
Interrupt kernel
Remove all variables
```

**Comment by CAM-Gerlach** [comment]
I suggest placing ``Interrupt kernel`` above ``Restart kernel``; IMO just seems more intuitive and natural to have interrupt above a complete restart but maybe that's just me.

Is there currently a clear distinction for what goes on the Consoles top-level menu vs. the Consoles pane options menu? If not, I'd consider putting commands that aren't specific to a particular Console sub-tab (e.g. the middle section) only on the Console pane options menu, while including global (first section) or quasi-global (third section) options on both; this also ensures the common sections are identical. Alternatively, if there isn't a clear distinction other than subjection personal perception, since the Consoles menu can be longer anyway I'd just make then identical to be consistent. 

> Yes, we don't need to create a submenu in the Consoles menu because it can be much taller.

Oh, I see—I interpreted your original comment to mean those options wouldn't be included at all.

> There's no rationale. I just thought it was not necessary. So let's add it with this work.

Okay, sure, if you think so.

**Comment by ccordoba12** [comment]
> I suggest placing Interrupt kernel above Restart kernel

Ok, let's go with this.

> Is there currently a clear distinction for what goes on the Consoles top-level menu vs. the Consoles pane options menu?

I'd like to leave the third section in the Options menu because that's pretty specific to each console.

**Comment by CAM-Gerlach** [comment]
> I'd like to leave the third section in the Options menu because that's pretty specific to each console.

Well, Sys.Path and Environment variables might vary somewhat from console to console, but not always dramatically so (thus "quasi-global"), while "Show elapsed time" is a Console-global option. Meanwhile, Restart. Interrupt and Remove all variables (along with Rename Tab) take explicitly console-specific actions.

**Comment by CAM-Gerlach** [comment]
> Sys.Path and Environment variables might vary somewhat from console to console, but not always dramatically so (thus "quasi-global"), while "Show elapsed time" is a Console-global option. Meanwhile, Restart. Interrupt and Remove all variables (along with Rename Tab) take explicitly console-specific actions.

Alternatively if you don't agree with that @ccordoba12 , we could apply the standard of "Is this option specific to the Console pane UI or does it have a broader effect?". Going that route, if we're going to have the latter three each-console-specific options, we may as well at least have Sys.Path and Env Variables in a third section of the global menu, since they're more clearly of potentially global interest and bring up dialogs separate from the Console pane itself regardless of its visibility. "Show elapsed time" is specific to the Console pane UI and is rather minor so its justifiable to not include it by that standard.

Either way, we need to decide on *some* reasonable convention for what goes on each menu and apply it consistently, to avoid user (and developer) confusion over the matter.
