### ISSUE TITLE
Kernel Connection

### ISSUE THREAD

**Issue by awebber20** [spyder-ide/spyder#8543]
### What steps will reproduce the problem?

Installed spyder using pip install spyder, kernel fails to connect.

### Traceback
```python-traceback
  File "D:\Apps\Python\Python-3.6.8\lib\site-packages\spyder\plugins\__init__.py", line 515, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "D:\Apps\Python\Python-3.6.8\lib\site-packages\spyder\plugins\ipythonconsole.py", line 771, in toggle_view
    self.create_new_client(give_focus=False)
  File "D:\Apps\Python\Python-3.6.8\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1093, in create_new_client
    version='<1.0.0')
  File "D:\Apps\Python\Python-3.6.8\lib\site-packages\spyder\utils\programs.py", line 454, in is_module_installed
    return eval(output.decode())
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
```

## Versions

* Spyder version: 3.3.2 
* Python version: 3.6.8
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.3 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.
