### ISSUE TITLE
New line whitespaces conflict with PEP

### ISSUE THREAD

**Issue by max3-2** [spyder-ide/spyder#8564]
### Issue Report Checklist

* [ x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ x ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When creating a new line by `return` in an indented environment, spyder makes whitespaces to keep the indentation. However, when subsequently keeping the line empty by pressing `return` again, those whitespaces make a PEP 8 warning .

### What steps reproduce the problem?

1. Open a new file
2. Create an indentation, e.g. using an `if`
3 .Add some code
3. Have a blank line by double tapping return and then some more code

### What is the expected output? What do you see instead?

A PEP8 warning occurs with whitespaces in blank line. My suggestion would be to catch if a line is intentionally blank and then remove the whitespaces needed for indentation. However, when the user decide to add code, the whitespaces  have to be added manually to be on the right indentation which may be tedious.

**Comment by jnsebgosselin** [comment]
Please fill out the info about your OS, Qt, PyQt and Spyder version.

**Comment by ccordoba12** [comment]
This is a valid concern, but unfortunately we don't have time to address it right now. However, help is welcome to fix it.

**Comment by jnsebgosselin** [comment]
Forget about my comment @max3-2, I misunderstood what you were reporting and thought this was a bug report instead of an enhancement request.

**Comment by bcolsen** [comment]
@CAM-Gerlach @impact27 I haven't tested the code in #8734 but from the comments it seems like it might take whitespace removal too far with unexpected consequences for those using version control systems.

I think all we need to do to fix this is to detected if enter is pressed twice(or multiple times) in a row then remove the tabs that were automatically put and that is all. If the cursor is moved or any other text is changed then the spaces will have to be removed by the user.

**Comment by ccordoba12** [comment]
@impact27, after a second thought, I agree with @bcolsen here.

**Comment by impact27** [comment]
I don't totally agree: What if I have this code:
```
if i == 1:
    a = 2
    b = 3
```
and I want to add a blank line between `a` and `b`? Then I would have four useless spaces.
For this particular problem I would probably have something like:
If I leave a line (by any mean) without having done anything, the the automatic indentation should be removed. 
Then for #8734 maybe one should add an option that says: "automatically remove trailing white spaces upon leaving line" that would be disabled by default?
I would see something like this in left_line: 
- If the option is enabled then rstrip the line.
- else if the previous key was a return then rstrip the line. (because any white spaces has to come from automatic indentation)

**Comment by impact27** [comment]
And if the user wants to keep the 4 spaces, he can still go back on the line and add them manually.

But I think removing an unused automatic indentation, regardless of how the user leaves the line, should be the default. (If you even want to leave the option to leave an empty automatic indentation.)

**Comment by CAM-Gerlach** [comment]
In general, I like this solution for the default case (removing added automatic indentation:

> if the previous key was a return then rstrip the line. (because any white spaces has to come from automatic indentation)

since it covers the many cases where automatic indentation is added and not desired/conformant with PEP 8, but the user navigated off the line by something other than adding another line, while taking care to ensure the whitespace must have been added by Spyder (other than extremely unlikely case where the user added whitespace themselves, left the line, and wanted it to stay for some reason). There may be one reason why

> If you even want to leave the option to leave an empty automatic indentation.

When using the mouse or arrow keys to move away from a line; namely, if one had added a line, moved to another line to make a change, and then wanted to go back to the automatic indent level in the previous line; However, this case is likely far less common than the many cases where this was not desired, and if so they could add back the automatic indent with one tap of the ``Tab`` key. 

> If the option is enabled then rstrip the line.

This option serves a different purpose than just solving this issue, but (IMO) a quite valuable one—preventing the user from adding new trailing whitespace when editing files, like Spyder's codebase, that already have a lot that can't just be stripped out on save lest merge conflicts result and diffs become hard to read. Since its already implemented in the PR, and its a useful feature, we may as well implement it as an option as discussed above.

There is a bit of an issue with it as stated, though—as I mentioned in the PR review, it means that any line the user places their cursor on (even for a moment), regardless of whether its actually modified, gets its trailing whitespace invisibly stripped. As this is exactly what users are presumably trying to avoid in the first place in this feature's primary usecase, is there a way you can limit it to only lines on which either lines that have been modified while the user has been on them, or if ``Enter`` is used to leave them?

**Comment by bcolsen** [comment]
> Then for #8734 maybe one should add an option that says: "automatically remove trailing white spaces upon leaving line" that would be disabled by default?
I would see something like this in left_line:
>
>- If the option is enabled then rstrip the line.
>- else if the previous key was a return then rstrip the line. (because any white spaces has to come from automatic indentation)

This seems good to me.

I think this can be enabled by default as long pressing enter multiple times leaves me at the same indentation level.

**Comment by bcolsen** [comment]
@CAM-Gerlach says:
>There is a bit of an issue with it as stated, though—as I mentioned in the PR review, it means that any line the user places their cursor on (even for a moment), regardless of whether its actually modified, gets its trailing whitespace invisibly stripped. As this is exactly what users are presumably trying to avoid in the first place in this feature's primary usecase, is there a way you can limit it to only lines on which either lines that have been modified while the user has been on them, or if Enter is used to leave them?

Always stripping the trailing whitespace when pressing enter is a good idea. There would be a change there anyways.

I think the default logic could be:
- whenever you press enter strip the trailing whitespace on that line and add an indent to the next
- also if enter was the previous key and the cursor is moved to a new line strip the trailing whitespace of the last line

We would still need to have pressing enter multiple times keeping the same indentation level.

I'm still not sure about the removal of whitespace when moving the cursor around. I think that the remove all trailing whitespace command would cover that

**Comment by CAM-Gerlach** [comment]
> also if enter was the previous key and the cursor is moved to a new line strip the trailing whitespace of the last line

This would also need to take into account mouse-triggered line changes as well, or the user could press enter, click on another line, then move off it and the whitespace would get stripped.

> I'm still not sure about the removal of whitespace when moving the cursor around. I think that the remove all trailing whitespace command would cover that

Not exactly, since as I've discussed the primary use case for this option is with files (like Spyder's) that have existing whitespace that should not be removed while stripping it on any changed lines. Furthermore, users like myself in such scenarios have to keep the "strip whitespace on save" option off for *everything* to avoid accidentally stripping whitespace in a Spyder file (due to lack of project-specific preferences), so this feature allows them to avoid having to remember to manually trigger this all the time on anything else.  If changes were made on any existing line and the cursor was moved by means other than return, whitespace would not be removed as it should.

Therefore, in addition to stripping whitespace on move if the previous key was enter, we should offer the option (enabled by default, presumably) to strip whitespace if either enter was pressed to change lines, or the line was modified since the last line change (perhaps after each line change, store the current line and compare against it on the next change).

**Comment by bcolsen** [comment]
Here's a simple idea, we could track `text_changed` in the editor and every time text changes in a line we strip the trailing whitespace. If that's too heavy, then only strip if text changes and the line changes 

https://github.com/spyder-ide/spyder/blob/8d66f28b5b7d1f7d8888bf26a0cafb54af2aaa75/spyder/plugins/editor/widgets/editor.py#L194

**Comment by CAM-Gerlach** [comment]
> every time text changes in a line we strip the trailing whitespace.

Well, if we did that immediately rather than at least waiting for a line change, you wouldn't be able to add *any* whitespace at all that wasn't to the left of some existing text, heh. Besides, we don't want to be messing with a line while a user is changing it; doing so when moving away from it after a change is as aggressive as I'd even consider getting (and that should be an option, with the alternative being only on new blank lines).

**Comment by bcolsen** [comment]
> you wouldn't be able to add any whitespace at all

Yeah I thought that sounded too easy.

**Comment by bcolsen** [comment]
So should we do this?:

- right strip if text changes and the cursor line changes

I think that could be on by default. I also don't think we would need two options. Just something like "Strip trailing whitespace when a line is edited"

I would have to play with it a bit to be sure but it sounds simple enough not to get in the way.

**Comment by CAM-Gerlach** [comment]
> So should we do this?:

>    * right strip if text changes and the cursor line changes

Yes, agreed. We would want to make sure changes effected by pressing ``Enter`` somewhere that's not the end of the line are still detected (i.e. if I were to press Enter at the ``|`` in ``test_list = [obj_1, obj_2, |obj_3]`` the whitespace should be stripped from ``test_list = [obj_1, obj_2, ``) are detected properly. We would also want to make sure new lines created using ``Enter`` are detected and have their whitespace stripped on leaving (which would handle the specific case originally discussed in this issue).

> I think that could be on by default.

I certainly don't mind, and I don't see too much of downside so long as it checks for single or triple-quoted strings, but its ultimately up to @ccordoba12 .

> I also don't think we would need two options.

Sorry, I didn't meant to imply n my comments here that we should have two; rather, just one checkbox, named along the lines of what you suggested. When checked, it would do the above, while when unchecked, it would only strip whitespace ``if enter was the previous key, the cursor is moved to a new line`` and the line in question contained only whitespace, because any whitespace would have been necessarily added by Spyder, not the user, and thus all it would do is make Spyder's existing auto-indent behavior smarter and respect PEP 8 with no downsides.

**Comment by CAM-Gerlach** [comment]
Aside from making it an option, it seems like a smarter version of this is exactly what the PR now implements.

**Comment by bcolsen** [comment]
I don't think that striping trailing white space can be enabled by default, since spaces before newline characters are important in non-python files like that silly double space at the end of a line in markdown for a line break

**Comment by CAM-Gerlach** [comment]
@bcolsen Okay, that makes sense. I always use ``<br>`` in Markdown personally, but its best to air on the side of caution when modifying what the user inputs by default.
