### ISSUE TITLE
Can't Open Varibels

### ISSUE THREAD

**Issue by OsamaAnmar** [spyder-ide/spyder#8586]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
I Can't Open Any Variables Like, X, Y , .... From Variable Explore, But If I Use Spyder From Anacond I Can Open It

**Comment by ccordoba12** [comment]
> But If I Use Spyder From Anacond I Can Open It 

*Short answer*: then please keep using Anaconda.

----

*Long answer*:

Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.
