### ISSUE TITLE
Run file (F5) command does not work

### ISSUE THREAD

**Issue by loic25** [spyder-ide/spyder#8772]
### What steps will reproduce the problem?

- hit F5 to execute a script in Spyder fails and execution in Spyder's IPython console is stalled
- runfile(filename) command in Spyder's IPython console does not work either 
- %run filename.py in Spyder's Ipython console does work properly in Spyder
- executing python filename.py in a terminal does work perfectly as well

I am completely lost about what I must do to solve this.

Thanks for your help...

## Versions

* Spyder version: 3.3.3 
* Python version: 2.7.13
* Qt version: 5.7.1
* PyQt5 version: 5.7
* Operating System: Linux 4.9.0-8-amd64

### Dependencies

```
IPython >=4.0;<6.0:  5.8.0 (OK)
cython >=0.21     :  None (NOK)
jedi >=0.9.0      :  0.11.1 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.16.1 (OK)
pandas >=0.13.1   :  0.19.2 (OK)
psutil >=0.3      :  5.4.3 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.5.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.8.3 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
sphinx >=0.6.6    :  1.7.2 (OK)
sympy >=0.7.3     :  None (NOK)
```

**Comment by loic25** [comment]
It never happened before I upgraded to **v3.3.3** a couple of days ago. So I tried to downgrade back to **v3.3.2** but I still have the same issue. Whatever the script contains (for example a simple: print 'hello world!'), the "Run file" button (or F5 on the keyboard) makes the execution to stall and I have to close the console to be able to do anything again in Spyder.

**Comment by ccordoba12** [comment]
> And also I installed Spyder via **pip**

Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.

**Comment by loic25** [comment]
OK, thanks for your reply.
