### ISSUE TITLE
Change "Clear variables" to "Remove variables" in French translation

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#8927]
We should use `supprimer` instead of `effacer`, as suggested by @jproy on Gitter.

**Comment by jproy** [comment]
Thanks for us, but it would be interesting that this means not only `%reset` but a true `Restart Kernel` ?

**Comment by ccordoba12** [comment]
That's a different kind of operation. The problem with a kernel restart is that it blocks the entire interface, so that's why we decided to not provide an option to do it on every run.

**Comment by jproy** [comment]
Well, they do that in Jupyter, and it's cool. Leave the user the decision ?

**Comment by ccordoba12** [comment]
We don't provide an automatic option to do it neither does the notebook, so I don't understand your request. In Spyder you need press `Ctrl+.` in a console to restart the kernel and in the notebook you need to go to an entry in the Kernel menu. So in both interfaces you have to restart the kernel manually.

**Comment by jproy** [comment]
In Jupyter there is a menu `Restart Kernel and Run All`, maybe could you add this one to the Spyder option button of the console ? I do not know enough of Jupyter or Spyder, is there a way to configure them so that the `Exec` arrow button is associated to `Restart Kernel and Run All` ?That is what I would have liked.
