### ISSUE TITLE
Cannot Connect to Kernel

### ISSUE THREAD

**Issue by HJLBX** [spyder-ide/spyder#8979]
### What steps will reproduce the problem?

All of a sudden, Spyder cannot connect to the kernel:

https://imgur.com/a/seNQMid

## Versions

* Spyder version: 3.3.3 
* Python version: 3.7.2
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
rope >=0.9.4      :  0.12.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.3.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
It seems you replaced the contents of one of our files with your own code. Please run this command in the Anaconda Prompt to fix it

    conda install -f spyder-kernels

**Comment by HJLBX** [comment]
The above command did not fix the issue.

I also uninstalled and re-installed, but the very same thing is happening after doing so.

**Comment by ccordoba12** [comment]
Please post the contents of this file here:

![Selección_012](https://user-images.githubusercontent.com/365293/54606973-7a853c00-4a4d-11e9-9974-f25407869ce1.png)

**Comment by HJLBX** [comment]
One again I uninstalled and reinstalled Spyder, but a complete uninstall-reinstall does not fix the issue.

I am expecting an uninstall-reinstall to fix the problem... if there is a problem file then it should be deleted.

I am just a student trying to set up my system to learn python. I have Python, PyCharm and Anaconda installed because that is what I need.

None of this is inspiring confidence give the fact that I have just spent 5 hours trying to sort out one problem after another.

x=1
if x:
    y=2
    if y:
        print('block2)
x=3
  print('block1')
print('bloc0')

**Comment by HJLBX** [comment]
Video::

https://mega.nz/#!0N5X3QpI!PdvuIxiUa8vUnDPGSDOc7_mI-MBjMukyBWF8YJt_HvI

**Comment by ccordoba12** [comment]
As I suspected, you modified the contents of your `spydercustomize.py` file by some other contents.

But I really don't understand why that's not fixed by an Anaconda reinstallation. Please try again to do that, but this time:

1. Remove the directory `C:\ProgramData\Anaconda3` completely.
2. Only install Anaconda for your user instead of for all users.

**Comment by HJLBX** [comment]
You keep saying I modified the contents of that file. I didn't modify anything. I was just doing an online tutorial at Python.org and then the issue started.

In any case, I've unisntalled and reinstalled Anaconda numerous times. Now, it won't update Spyder. No matter which method I use, it just sits there doing nothing while the system CPU goes really high and, stays there:

https://imgur.com/a/MWrKjaD

I know it is an Ananconda issue, but there are just so many that I'm just not interested in spending hours reporting all of them.

**Comment by ccordoba12** [comment]
> You keep saying I modified the contents of that file

Look, the contents of that file are these:

https://github.com/spyder-ide/spyder-kernels/blob/0.x/spyder_kernels/customize/spydercustomize.py

which obviously differ a lot from the contents you posted above. And I can assure you Anaconda is not distributing that file with the wrong contents.

So if you didn't modify that file manually, then your computer is touching it somehow because there's no other explanation.

> I know it is an Ananconda issue, but there are just so many that I'm just not interested in spending hours reporting all of them.

Ok, sorry but I'm going to close this issue because I guess there's something really wrong with your computer given all the problems you reported.

Besides, in your last screenshot I can clearly see you reinstalled Anaconda as Administrator instead of doing it only for your current user (against my previous advice). So my last advice is to remove Anaconda again and install it for your user.
