### ISSUE TITLE
Problem version 3.3.4 ubuntu install

### ISSUE THREAD

**Issue by Mantxurreta** [spyder-ide/spyder#9090]
### What steps will reproduce the problem?

Update to 3.3.4 in linux Ubuntu 18.04 creates incompatibilities with pyqt5 version 5.12 required. Perhaps with pyzmq as well. Spyder 3.3.4 would not start. I had to uninstall all related packages and clean install pyqt5 v5.9 and force spyder v3.3.3 to make it work. 

## Versions

* Spyder version: 3.3.0 
* Python version: 3.6.7
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Linux 5.0.0-050000-generic

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  2.0.0 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
psutil >=0.3      :  5.6.1 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by Mantxurreta** [comment]
Clarification: Apparently I forced spyder v3.3.0 in this computer. I had to do the same in another in which I forced spyder v3.3.3.

**Comment by ccordoba12** [comment]
From your description it seems that you're mixing system packages with packages installed by pip.

What command did you use to install Spyder?

**Comment by Mantxurreta** [comment]
You might be right. I am not an expert on this matter.
I cannot tell what I used to install the first version of Spyder. What I did when this problem come across was updating it. For this update I used:
 sudo -H python3 -m pip install --upgrade spyder
I got a warning saying that pyqt5 v5.12 was required but incompatible or something like that. Then I tried to update pyqt5 and I succeeded. After that I run the upgrade command again. I think that the warning also said something about some package being installed by the system so it could not be uninstalled for update. I am not sure which, perhaps the pyzmq or maybe pyqt5. Therefore I tried to update separately with pip and/or with apt-get those packages. Apparently I managed to do that but I could not make Spyder 3.3.4 open.

**Comment by ccordoba12** [comment]
> sudo -H python3 -m pip install --upgrade spyder

As I imagined, this is the problem. By running this command, you're forcing a mix of your system packages with the packages installed by pip, which is really bad because it causes the kind of conflicts you're seeing.

This is not a problem with Spyder, so there's nothing we can do about it. My recommendation is for you to uninstall all packages you installed with pip that way, then create a virtualenv in your home directory and finally install everything there with pip.

Please google how to use virtualenvs and try to not mess with your system packages in that way again (not only for Spyder but for any other Python package).
