### ISSUE TITLE
ubuntu spyder won't connect to anaconda console/iPython

### ISSUE THREAD

**Issue by iNiketan** [spyder-ide/spyder#9100]
## Description

**What steps will reproduce the problem?**

1. spyder won't run anaconda python
2. pandas numpy not found error even if anaconda is installed (ubuntu)
3. 

**What is the expected output? What do you see instead?**
spyder to use anaconda python install on my system.

**Please provide any additional information below**

  File "/usr/lib/python3/dist-packages/spyder/plugins/ipythonconsole.py", line 1047, in create_client_for_kernel
    password)
  File "/usr/lib/python3/dist-packages/spyder/plugins/ipythonconsole.py", line 1724, in _create_client_for_kernel
    kernel_client.load_connection_file()
  File "/usr/lib/python3/dist-packages/jupyter_client/connect.py", line 493, in load_connection_file
    with open(connection_file) as f:
IsADirectoryError: [Errno 21] Is a directory: '/home/niketan/anaconda3/lib/python3.7'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.7
* Qt Versions: 5.9.5, PyQt5 5.10.1 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  None (NOK)
sphinx >=0.6.6   :  1.6.7 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  5.5.0 (OK)
pylint >=0.25    :  1.8.3 (OK)

```

**Comment by ccordoba12** [comment]
> spyder won't run anaconda python

What does this mean? Please be more clear.

> pandas numpy not found error even if anaconda is installed (ubuntu)

This is not something we can fix in Spyder.

> File "/usr/lib/python3/dist-packages/spyder/plugins/ipythonconsole.py", line 1047, in create_client_for_kernel
password)
File "/usr/lib/python3/dist-packages/spyder/plugins/ipythonconsole.py", line 1724, in _create_client_for_kernel
kernel_client.load_connection_file()
File "/usr/lib/python3/dist-packages/jupyter_client/connect.py", line 493, in load_connection_file
with open(connection_file) as f:
IsADirectoryError: [Errno 21] Is a directory: '/home/niketan/anaconda3/lib/python3.7'

How did you get this error?

**Comment by hellomynameispython** [comment]
I have also similar problem, maybe I can write more clear instead of openning new issue. 
I installed spyder3 from ubuntu software center and there was no problem. I always used default Ipython console and it works properly. Today I closed the ipython console (by pressing ctrl+w) by mistake. Then I couldn't open it again because when I right click on the console dock there is no 'open a ipython console' option (only 'open a python console' and 'open a terminal'). 
I tried update-upgrade-remove and reinstall the spyder but it didn't work. I also reinstall the pip and ipython3-qtconsole, python3-zmq, ipykernel, sympy but nothing is changed. How can I bring Ipython console back on ubuntu?
I also closed 'history' tab to try to reopen but couldn't do it.

![image](https://user-images.githubusercontent.com/49391456/55710451-9ca72400-5a25-11e9-9e70-ea13727eba29.png)
![image](https://user-images.githubusercontent.com/49391456/55710655-04f60580-5a26-11e9-82ed-761d44c854e5.png)

**Comment by bcolsen** [comment]
> How can I bring Ipython console back on ubuntu?

In the menu (in the header bar in ubuntu) go to `View > Panes > IPython Console` or `Ctrl-Shift-I`

**Comment by ccordoba12** [comment]
@hellomynameispython, you're using a very, very old version of Spyder. Please use Anaconda to update to our latest version,

**Comment by iNiketan** [comment]
@ccordoba12 @hellomynameispython 
accidentally found a solution type this code in terminal it will automatically config spyder to run anaconda python
conda run spyder
