### ISSUE TITLE
Autosave recovery dialog expands beyond screen instead of using scrollbars with too many items

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#9125]
If I have more autosave files than will fit on my monitor (I have a 1200p one and just had it happen), then the dialog just expands outside of the visible screen (making it impossible to interact with the rest) rather than limiting its size and adding a scroll bar to the file list. Therefore, we should limit the size of the dialog, or the number of list items shown on screen accordingly to comfortably fit on a 720p monitor (or the current size, if practicable) and add a scroll bar widget to show the rest if that is the case. @jitseniesen take note, thanks!

**Comment by ccordoba12** [comment]
@juanis2112, please take a look at this one. You can use this info as a starting point:

https://stackoverflow.com/questions/6821990/qdialog-with-scrollarea-and-gridlayout

To generate this problem, first you need to go to

    Preferences > Editor > Advanced settings

and change `Autosave interval` to `5` seconds.

Then you need to open 10 or 20 already existing files, make a small change to them and kill Spyder forcefully. To do the last thing, you need to open a different console, run in there this command:

    ps aux | grep bootstrap.py

which should generate something like

    carlos   32398 10.5  1.6 2992380 277308 pts/2  Sl+  20:27   0:07 python bootstrap.py

select the first number from left to right and pass it to the next command

    kill -9 32398

After you do that and open Spyder again, you should see the autosave recovery dialog with all the files you modified and left unsaved.

**Comment by ccordoba12** [comment]
By the way, the number `32398` above is called the `pid` of a process (I think it stands for `process id`).

**Comment by ccordoba12** [comment]
And I forgot to tell you that the recovery dialog is placed here:

https://github.com/spyder-ide/spyder/blob/master/spyder/plugins/editor/widgets/recover.py

**Comment by jitseniesen** [comment]
In fact, I already started working on this about a month ago, but I decided to fix some higher priority stuff first instead of finishing it. If you want, I can show you what I have. I am not sure I can finish it myself before beta3, I want to first fix the autosave bugs when opening  multiple Spyder instances.

**Comment by ccordoba12** [comment]
Sure, thanks @jitseniesen! Would you like to open a WIP PR that @juanis2112 could finish or just post here a patch of what you have?

**Comment by jitseniesen** [comment]
@juanis2112 Here is a commit of what I have: 910ba168fe4. The idea is to check the size of the dialog window, and if it is too big, replace the table containing filenames with a scroll area which contains that table. I am not sure this is the right approach; it is not clear to me when Qt does the layout for the dialog window and thus when to check the size. I decided to check the size as late as possible (i.e., the first time the window is displayed). I included loads of print statements to find out what's happening; these need of course be removed eventually.

I seem to remember that it basically worked. One problem is that if there are too many files so that the window is too tall, then the current implementation shrinks the height, which leads to a vertical scrollbar being added next to the table. This scrollbar then means that the scroll area is slightly too narrow. Ideally, if the window is too tall, the height should be decreased but the width should be increased with the width of the scrollbar. However, this may not be worth the effort. Hopefully, the recovery dialog is rarely shown, so it seems less of a priority to fine tune its appearance.

I only tested it on Linux, so we should make sure it works on Windows and Mac as well. The easiest way to test is to run the file `recover.py`; this makes a temporary directory with autosave files and displays the recovery dialog window (you can easily adapt this to add more files so that the window expands beyond the screen). It would be good to add automatic tests, but that may be difficult. Maybe we should just add a test which displays the dialog with many files without any asserts - this would make sure that at least the code runs.

Do ask if anything is unclear.

**Comment by ccordoba12** [comment]
@jitseniesen, what if we use a fixed size for the dialog and a scrollbar? I think that would be the simplest thing to achieve, no?

**Comment by jitseniesen** [comment]
Indeed, that's perfectly fine, and much easier.
