### ISSUE TITLE
in macOS Mojave v 10.14.4 I launch spyder from terminal

### ISSUE THREAD

**Issue by fraPython** [spyder-ide/spyder#9132]
$ spyder
Traceback (most recent call last):
File "/anaconda3/lib/python3.7/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in
from PyQt5.QtWebEngineWidgets import QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/anaconda3/bin/spyder", line 11, in
sys.exit(main())
File "/anaconda3/lib/python3.7/site-packages/spyder/app/start.py", line 186, in main
from spyder.app import mainwindow
File "/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 90, in
from qtpy import QtWebEngineWidgets # analysis:ignore
File "/anaconda3/lib/python3.7/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in
from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

**Comment by ccordoba12** [comment]
Did you use pip to install/update Spyder?

**Comment by fraPython** [comment]
I try in different way but usually with conda

**Comment by ccordoba12** [comment]
> I try in different way in accord with all the posts and all your suggestions for these problems with spyder.

Please remove and reinstall Anaconda again. Most probably one of the commands you used corrupted your installation and that's why you're getting that error.

**Comment by dazinger92** [comment]
@ccordoba12 Please forgive me, but what exactly do you refer to when you said "corruption?"

Things I'm aware of:

-QTWebKitWidgets is no longer a part of PyQt5, and is now its own package
-This problem was addressed in the latest version of Spyder, but not the one before that (hence it was broken in the previous version if you had updated your PyQt5)
-The problem itself refers to only objects resting in site-packages

So, is what's corrupted probably in site-packages or the spyder library?

**Comment by ccordoba12** [comment]
> -QTWebEngine is no longer a part of PyQt5, and is now its own package

Exactly to this statement: the conda and pip packages for PyQt5 are incompatible (so you can't mix them), and this problem only happens with the pip packages. According to the initial traceback, @fraPython is using Anaconda and not pip.

> EDIT 1/2: if I had to make a guess, maybe this problem has to do with referencing PyQt5.QtWebEngineWidgets as opposed to simply QtWebEngineWidgets?

No, that's not true. Things are working perfectly fine with pip (because we run all our tests by installing *everything* with it), as long as you use it properly.

**Comment by fraPython** [comment]
I reinstall anaconda but the problem with spyder persists.

**Comment by ccordoba12** [comment]
Please post your problem in our Gitter channel:

https://gitter.im/spyder-ide/public

You'll receive help there.
