### ISSUE TITLE
Add information on the current environment (conda) and provide a switcher

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#9139]
Display the current environment in use as a StatusBar Widget. Allow to select the environments found from there.

This work will tie with the projects refactoring

See https://github.com/spyder-ide/spyder/pull/5947 for reference

**Comment by goanpeca** [comment]
Unifying over https://github.com/spyder-ide/spyder/issues/9008

**Comment by mrclary** [comment]
I realize this issue is closed, but I thought I'd report one issue and relevant information for a "switcher". For reference, this feature was added in #9778 for 4.0.0b4.
* As of 4.0.0b5 the status bar does not update to reflect a change in the conda environment when switching python interpreters in the preferences.
* Also, I don't know if it's possible to have the status bar reflect the conda environment of the current console tab? Similar to the git branch status of the active editor tab...
* I ran into a corner case involving a package (`fenics`, a PDE solver) that relies on subprocesses where some paths were not found. I resolved this by using the following script in Preferences->iPython console->Startup
```python
import os
import sys

if 'anaconda' in sys.executable:
    # user intends to use anaconda environment...
    os.environ.update({'PATH': os.path.dirname(sys.executable) + ':' + os.environ['PATH'],
                       'CONDA_PREFIX': sys.exec_prefix})

del os, sys
```
These were the minimum conda environment variables I needed to change to get everything working properly, but I can't be certain that it perfectly emulates all that's performed by `conda activate`, so there may be other edge cases out there. I thought this may be useful information for any implementation of a "switcher".

**Comment by milindsmart** [comment]
So is there an environment *switcher* in Spyder or is there not? I can see the current environment, but cannot see any switcher... Manually changing python interpreter makes me nervous, I would much prefer something safer that can read conda environments.

**Comment by goanpeca** [comment]
@milindsmart no it is not yet implemented. 

@mrclary could you open a new issue with your suggestion (follow and show the current console env)? Also could you open an issue for the environment switcher, I guess the idea would be to not use preferences at all for that, but provide a click on the env and display found envs plus an option to select an env right there? 

Thanks!

**Comment by mrclary** [comment]
I created #13318

**Comment by mrclary** [comment]
Actually, I already opened #12200, closing #13318
