### ISSUE TITLE
Rename plugins for a simpler, less crowded interface

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#9207]
- [ ] `Find in files` -> `Find`
- [ ] `History Log` -> `History`
- [ ] `File Explorer` -> `Files`
- [ ] `Project Explorer` -> `Project` (Projects when we support multiple projects)
- [ ] `Static Code Analysis` -> `Code Analysis`

**Comment by ccordoba12** [comment]
Thanks for opening this @goanpeca. Question: should the rename also involve renaming the main classes related to the affected plugins? Or should we only rename the plugins' titles?

I mean, I think for beta2 we should rename just the titles because it's extremely simple and it would let people know how things are going to look in the final release. And we could leave refactoring the code for beta3.

What do you think?

**Comment by goanpeca** [comment]
>Or should we only rename the plugins' titles?

Just titles :-) for now

**Comment by ccordoba12** [comment]
> Just titles :-) for now

Ok, then let's leave that task to @juanis2112. Juanita, please rename our plugins according to the list in @goanpeca's first comment above.

Note: I edited that list to reflect the actual changes we want.
