### ISSUE TITLE
Auto-format Spyder code with an available tool

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#9272]
I have advocated in the past (and I still do) to use tools like [yapf](https://github.com/google/yapf) so we do not have to worry too much about these discussions that keep appearing on different PRs.

We could then commit to a style almost all feel comfortable with (as it is impossible to get a perfect style that fits all of the needs of every developer). It is much easier to run `yapf <file-name>.py` before every commit (or as part of CI) and use the time saved in coding. I will add this to the CI of some of the smaller projects we maintain as a Proof of Concept so we ca actually see how it works (I have implemented this in other projects I have mainatined in the past)

The additional benefit is that we can also enforce this for every other project we maintain (which kees growing!).

As we keep growing we can not really continue reviewing style issues by hand or by leaving it to the author preference when there is _no clear rule_. PEP8 are recommendations but that does not mean that we do not pick the rules we want to enforce as part of the overall family of projects we curate/maintain.

>The ultimate goal is that the code YAPF produces is as good as the code that a programmer would write if they were following the style guide. It takes away some of the drudgery of maintaining your code.

See example:

- https://github.com/spyder-ide/qtsass/blob/master/run_checks_and_format.py
- https://github.com/spyder-ide/qtsass/blob/master/setup.cfg

**Comment by CAM-Gerlach** [comment]
I agree with this approach; it neatly solves the two major downsides that have been cited with enforcing more stringent style guidelines, namely additional work by ourselves and the contributor when reviewing PRs, and deciding on one consistent, VCS-, clarity and correctness-optimal style independent of each contributor's personal preferences and what they're familiar/comfortable with.

It would naively seem better to do so on the contributor side (vs. with the CIs; we could include it prominently on the PR template) so the code we actually see is clean and readable, extra commits/changes, etc don't get injected, PEP8Speaks doesn't complain, etc. Its also more comfortable both for contributors and reviewers since they know they are seeing the final code that will actually be committed.

@goanpeca Since you seem to be the most familiar with these tools (I've always just written PEP8+-conformant code by hand myself, since its just what I'm already familiar with) do you think you might be able to briefly outline the benefits/downsides of the major tools available (``yapf``, ``autopep8``, etc) in terms of their comprehensiveness, configurability (by us), and ease of installation/use?

What would be ideal is to actually integrate one of them into Spyder, and just tell contributors to use that; there is currently the unmaintained ``spyder-autopep8`` plugin and I recall integrating something like that into Spyder (via LSP?) being discussed recently.

**Comment by CAM-Gerlach** [comment]
The one important consideration is that I assume it would require running our entire codebase through the formatter as a first step, which would presumably have be done at a carefully chosen time when all major PRs are in before e.g. the Spyder 4 release; we could also do the conform to ``LF``, remove trailing whitespace and standardize the license headers at the time, which we've already been discussing.

Relevant snippit from YAPF readme:

> The idea is also similar to the 'gofmt' tool for the Go programming language: end all holy wars about formatting - if the whole codebase of a project is simply piped through YAPF whenever modifications are made, the style remains consistent throughout the project and there's no point arguing about style in every code review.

**Comment by ccordoba12** [comment]
We tried this before and it didn't work. On the one hand, it's a terrible burden for first-time contributors to see their PRs flagged as failing due to stylistic issues. On the other hand, even first-class programmers (like MinRK, from Jupyter fame and who has helped us several times) find annoying the suggestions of pep8speaks.

So for now we'll continue with Pep8speaks (which I find a good compromise) and we'll start to use Github suggestions to avoid boring contributors with periods, commas and other picky stuff that you (specially @CAM-Gerlach) find important but I don't.

**Comment by ccordoba12** [comment]
And @goanpeca, please don't apply yapf to the other projects I maintain (qtpy, qtawesome, loghub, etc). I had to spent some time removing similar things you added to them in the past and (to be honest) I really don't like them.

However, I agree if you want to setup Pep8speals for them or the entire organization.

**Comment by ccordoba12** [comment]
Closing because there's nothing else to discuss here.

**Comment by CAM-Gerlach** [comment]
> On the one hand, it's a terrible burden for first-time contributors to see their PRs flagged as failing due to stylistic issues.

Sorry, but I don't see how this doesn't make any sense. Its somehow a "terrible burden" for contributors to type ``python run_checks_and_format.py`` before submitting their PR, yet somehow its not to see and have to manually deal with dozens of PEP8Speakes warnings, and for you, me and @goanpeca to barrage them with comments about all the little PEP 8, PEP 257, and general formatting issues with their code (and as often as not rehash a stupid argument over it)? The *entire point* of this approach is to eliminate all of that in favor of a simple, fully automated command that could even be built into Spyder itself and triggered with a hotkey.

> even first-class programmers (like MinRK, from Jupyter fame and who has helped us several times) find annoying the suggestions of pep8speaks.

> However, I agree if you want to setup Pep8speals for them or the entire organization.

So wait, some top contributors find pep8speaks annoying, so we're going to *implement it across all our projects*—instead of a tool that would handle that automatically without annoying them about nitpicks and allow them to code in whatever style they prefer? Um, what?

> I really don't like them.

And you *like* having to nitpick every new contributor's PR for these issues, argue about them with us, and having to worry about and fix them all manually in your code every time?

**Comment by ccordoba12** [comment]
> Sorry, but I don't see how this doesn't make any sense. Its somehow a "terrible burden" for contributors to type python run_checks_and_format.py before submitting their PR

That's not what @goanpeca was suggesting, but adding yapf to our CIs (see above):

> > It is much easier to run yapf <file-name>.py before every commit (or as part of CI)

As I said, we implemented that before and it didn't work.

> So wait, some top contributors find pep8speaks annoying, so we're going to implement it across all our projects

What I meant is that even first-class programmers find annoying to deal with stylistic stuff. So what can we expect from first-time and/or occasional contributors.

> And you like having to nitpick every new contributor's PR for these issues, argue about them with us

I'm not the one who's nitpicking contributors with stylistic stuff, you are. And to avoid that is that I suggested to use "Github suggestions" instead, so contributors can apply whatever you or someone else want to nitpick about without worrying about it.

That way it's our responsibility as maintainers to take care about keeping a (more or less) nice code style and for contributors to implement new features or fix bugs.

**Comment by ccordoba12** [comment]
> so not liking the style it produces is not a valid argument for or against it.

Sorry, I really don't care about what you find a valid argument. And I'm not going to change my stance on this.

**Comment by CAM-Gerlach** [comment]
I think there may be a major misunderstanding of what's being proposed here.

> That's not what @goanpeca was suggesting, but adding yapf to our CIs (see above):

That was one option, but the other (as both him and I have discussed, and I advocated for) was having contributors run the script themselves before submitting their PRs. Furthermore, either way CIs *won't* fail new contributors code; the whole point of it is actually to fix those problems *for* contributors without annoying warnings or making them solve the issues manually.

> As I said, we implemented that before and it didn't work.

Okay, well what didn't work about it last time? Are we really just assuming it will be the same and just giving up instead of at least considering how to work around or solve the problems with it?

> What I meant is that even first-class programmers find annoying to deal with stylistic stuff. 

The **point** of this whole thing is so both contributors and reviewers **don't** have to deal with all the stylistic stuff (which *is* the case right now), and you can write your code in any style you want and yapf does the rest.

> I'm not the one who's nitpicking contributors with stylistic stuff, you are.

Sure you do, perhaps even as much as anyone except me. You do so for [following](https://github.com/spyder-ide/spyder/pull/9266#discussion_r281008239) PEP [257](https://github.com/spyder-ide/spyder/pull/9266#discussion_r281008002) in [docstrings](https://github.com/spyder-ide/spyder/pull/9266#discussion_r281008002), for [implict](https://github.com/spyder-ide/spyder/pull/8481#discussion_r269984678) line [continuations](https://github.com/spyder-ide/spyder/pull/8734#discussion_r255311557), for [2 lines between functions](https://github.com/spyder-ide/spyder/pull/8734#discussion_r255311779), to [remind contributors of their PEP 8 speaks issues and even  manually telling them how to fix them](https://github.com/spyder-ide/spyder/pull/9230#discussion_r279305577), telling them (including myself) not to change/remove trailing [whitespace or line endings](https://github.com/spyder-ide/spyder/pull/8257#discussion_r234357676), And so does @goanpeca (e.g. in the original comment that started this whole thing), Daniel, and others. I'm one of the more active reviewers of new contributors' PRs so I run into it more often and tend to notice them more, but it was you who agreed we should enforce PEP 8 and PEP 257 to begin with. Furthermore, we both agree that ``PEP8Speaks`` most certainly does, and *you said yourself* that it can be annoying to some developers, making our very point.

> And to avoid that is that I suggested to use "Github suggestions" instead, so contributors can apply whatever you or someone else want to nitpick about without worrying about it.

I tried using them as soon as they got introduced, but most of the changes I suggest span more than one line (so they don't work), and the contributors I tried using on actually refused to accept them and made the changes manually instead. They still involve the same amount of pointless work on our end, and some amount on the contributor's end to review and accept them, while PEP8SPeaks isn't much work for us but a lot for contributors.

> That way it's our responsibility as maintainers to take care about keeping a (more or less) nice code style and for contributors to implement new features or fix bugs.

With the proposal here, the automated script takes care of all the tedious style stuff so neither reviewers *nor* contributors need to do any extra work, saving *everybody* time while ensuring our final code maintains a consistently high standard of quality.

> Sorry, I really don't care about what you find a valid argument. 

Yes, I'm well aware you don't care about what I think; what I'm saying is the reasoning is *objectively* not  applicable if what you "don't like" has to do with its style, because YAPF is extensively customizable to enforce virtually any style you **do** like.
