### ISSUE TITLE
methods separated from classes in outline explorer

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#9337]
## Description
The methods are separated from the class if you add a cell.

### What steps will reproduce the problem?

```python
# %% class
class a():
# %% method
    def b(self):
        pass
```
<img width="125" alt="with cell" src="https://user-images.githubusercontent.com/6740194/57639295-856cd080-75a7-11e9-915f-8e10ca4ea33f.png">

```python
# %% class
class a():
    def b(self):
        pass
```
<img width="145" alt="without cell" src="https://user-images.githubusercontent.com/6740194/57639282-7e45c280-75a7-11e9-8e95-64fb0bf35a09.png">

## Versions

* Spyder version: 4.0.0.dev0 00fe1655e
* Python version: 3.7.3
* Qt version: 5.9.1
* PyQt5 version: 5.9
* Operating System: Darwin 18.5.0

### Dependencies

```
pygments >=2.0     :  2.3.1 (OK)
qdarkstyle >=2.6.4 :  2.6.5 (OK)
sphinx >=0.6.6     :  1.8.5 (OK)
psutil >=0.3       :  5.6.1 (OK)
pyls >=0.19.0;<0.25:  0.25.0 (NOK)
nbconvert >=4.0    :  5.4.1 (OK)
pandas >=0.13.1    :  0.24.2 (OK)
numpy >=1.7        :  1.16.2 (OK)
sympy >=0.7.3      :  1.3 (OK)
cython >=0.21      :  0.29.6 (OK)
qtconsole >=4.2.0  :  4.5.0.dev0 (OK)
IPython >=4.0      :  7.3.0 (OK)
matplotlib >=2.0.0 :  3.0.3 (OK)
pylint >=0.25      :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting @impact27. Is this working in Spyder 3?

**Comment by bcolsen** [comment]
@impact27 This is because the the code cells are the top level objects when "group code cells" is activated. 

Why would you want to put a code cell in a method?

What do you want the outline explorer to show if "group code cells" is active and you place a code cell in a method?

I consider code cells to be top level operators in my code so they are able to run in the global name space. It gets really messy when you put a code cell in the middle of a function or a loop. Spyder allows you to do such things but it most likely won't work.

One solution to this would be to not let users place code cells in other code blocks, but I don't know how we would stop them.

**Comment by impact27** [comment]
Looks fixed:
![image](https://user-images.githubusercontent.com/6740194/113007475-89dc0b80-9176-11eb-89e8-74ae4fb26423.png)
