### ISSUE TITLE
"black" formatter option ?

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/spyder#9359]
I discover the black formatter from Python-3.8 release manager Łukasz Langa

https://github.com/python/black

https://www.youtube.com/watch?v=esZLCuWs_2Y

Is it something complex to integrate as an option in the editor ? maybe it's not pertinent in Spyder +LSP, but in this prototype for ipython console,  it looks simple 

https://github.com/ipython/ipython/pull/11734/files#diff-e9a59ec7c6360d84aafa289edca1c50b

![GIF](https://user-images.githubusercontent.com/4312421/57969053-6b9a0780-7972-11e9-9975-50da3619c0e9.gif)

**Comment by goanpeca** [comment]
Hi @stonebig. I believe there is a plugin for black for the pyls server we use so it should be pretty straightforward

**Comment by stonebig** [comment]
So you mean in coming beta2... can we switch to Spyder4 beta2 now ? Or is still recommended to remain on Spyder-3 ?

**Comment by goanpeca** [comment]
Yes in coming beta 2? Hmm well if you could give it a try that would help us a lot :-)

**Comment by stonebig** [comment]
and why python-language-server[all] <0.25 ?

**Comment by stonebig** [comment]
hum, I would prefer the default them to go back to "spyder", instead of "spyder/black", tp smooth transition

**Comment by goanpeca** [comment]
I have no strong opinions on this one @ccordoba12, What we really need is a messagebox to highlight the changes so people know about this on startup.

**Comment by stonebig** [comment]
the problem I see, on my PC, is:
- the long time it takes to go to the black/white option, and the long time it takes to apply it.
- the other problem https://github.com/spyder-ide/spyder/issues/9357.
- and so the painfull 1rst minutes for users of Spyder3,

**Comment by ccordoba12** [comment]
> So you mean in coming beta2... can we switch to Spyder4 beta2 now ?

As I said before, I *strongly* disagree with this, unless you are packaging our beta with a beta of WinPython.

> hum, I would prefer the default them to go back to "spyder", instead of "spyder/dark", to smooth transition.

Please don't do that either. Right now the dark theme is better supported than the light one because everything is tested against it. There are still minor issues (like #9357), but those will be fixed in the next betas.

If you're going to provide something different than we're trying to accomplish in Spyder 4, then I'd really prefer if you don't package our betas at all. Sorry to say it, but that's not different from Linux distributions that patch software in the best interests of the distro or their users without taking into consideration what the original authors of the project decided.

**Comment by stonebig** [comment]
So:
- in current build3 it's in white because of bug 9357 and smoother transition,
- in next build Spyder-4 will be removed again, so you're not annoyed.

**Comment by ccordoba12** [comment]
Ok, thanks :+1:

**Comment by stonebig** [comment]
as a remark for other users "Black" formats in a way that is only read-compatible with Python-3.6+.
![image](https://user-images.githubusercontent.com/4312421/57986357-22ca7780-7a74-11e9-8ac0-c37d635b404d.png)
