### ISSUE TITLE
FileNotFoundError when closing a file that's opened in several Spyder instances

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#9420]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Error when closing a tab whose autosave file was destroyed.

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback
ERROR:spyder.plugins.editor.widgets.autosaveerror:<class 'FileNotFoundError'> while removing autosave file /Users/quentinpeter/.spyder-py3-dev/autosave/spydercommbase.py
Traceback (most recent call last):
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/editor/utils/autosave.py", line 165, in remove_autosave_file
    os.remove(autosave_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/quentinpeter/.spyder-py3-dev/autosave/spydercommbase.py'
```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Could you describe when or how this problem happens?

**Comment by impact27** [comment]
This happens when the autosave file is deleted by an other program. (I am debugging spyder with spyder). The problem is that I have the window telling me the file was deleted, as I expect, but also the internal exception window.

**Comment by ccordoba12** [comment]
I see, that's something that can happen to any of us that are developing Spyder with Spyder, but also to people that are running multiple instances of Spyder and have the same file opened in them.

@jitseniesen, what do you think we should do about this?

**Comment by jitseniesen** [comment]
To be honest, I never thought of the possibility of having multiple Spyder instances. What happens with the Spyder configuration in that case? I have a vague recollection that there is some code that does something special in this case.

**Comment by ccordoba12** [comment]
The configuration directory and files are shared between all instances.

**Comment by jitseniesen** [comment]
That's not good. It means that when you start a second instance, that instance finds the autosave files and offers to recover the original files from them, which is probably quite confusing to our users. I just tried it out and that is indeed what happens. I need to fix this.

**Comment by ccordoba12** [comment]
Thanks a lot @jitseniesen!

**Comment by CAM-Gerlach** [comment]
@jitseniesen This is a known result of PR #9327 . It excepts and passes removal errors when cleanly closing the Editor itself (i.e. Spyder), as it needs to iterate across all Editorstacks as they are not in sync due to #9265 and possibly other errors (which will be fixed by your PR #9485), and thus will encounter the error with >2 editorstacks as well as opening and closing another Spyder instance with the same files.

I knowingly didn't suppress the error on closing an individual files, as I (perhaps incorrectly) considered that use case to be less likely and impactful on the user side. This probably was the wrong decision (which I questioned even at the time); to ignore errors here as well and resolve this issue, just pass ``errors="ignore"`` to ``remove_autosave_file()`` on [Line 1521 of spyder/plugins/editor/widgets/editor.py](https://github.com/spyder-ide/spyder/blob/master/spyder/plugins/editor/widgets/editor.py#L1521).

However, this is rather redundant if you are removing this line and [lines 394-396 of spyder/plugins/editor/plugin.py](https://github.com/spyder-ide/spyder/blob/master/spyder/plugins/editor/plugin.py#L394) to disable removing autosaves as no longer necessary with your more robust changes.

**Comment by jitseniesen** [comment]
> The configuration directory and files are shared between all instances.

I think I misunderstood how this sharing works.

As I understand it now, updates from one instance are not shared with another instance. Concretely, if I open two instances, and then instance 1 changes a config option, then this change will not be reflected in instance 2. Instance 2 will continue using the config option as it was when it read the config file when it was started, and the next time it saves to the config file, it will overwrite the change from instance 1.

@ccordoba12 Is this correct?

**Comment by ccordoba12** [comment]
Yes, that's correct.

**Comment by jitseniesen** [comment]
Thanks. Then I need to use a different approach. I will submit a stop gap PR, disabling autosave on a second Spyder instance, for beta 3 today or tomorrow. I will then work on a better solution for the next beta, but that will take at least a week.

**Comment by ccordoba12** [comment]
Ok, no problem. Thanks @jitseniesen!
