### ISSUE TITLE
Dependencies dialog should provide correct package name

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#9714]
For issues when users have an incorrect dependency in the case of the `pyls` package:

<img width="818" alt="Screen Shot 2019-06-28 at 11 15 48" src="https://user-images.githubusercontent.com/3627835/60369111-3a244b00-99b8-11e9-933a-05bdcff91488.png">

My immediate action is to do something like

```bash
$ conda install pyls -c spyder-ide
```

But this will not work as the actual package name is `python-language-server`. I see this happening to users trying to do `pip install pyls`

Could we either change the name of the package or add an extra column for package name? (which is not always the same as module name?)

---

Also we should be able to provide more help on the command users need to run to fix this

**Comment by ccordoba12** [comment]
> Could we either change the name of the package

This is not possible because we're using `is_module_installed` to detect if a module is installed or not.

> or add an extra column for package name?

This is fine with me.

**Comment by oscargus** [comment]
I can just confirm that exactly this happened to me. Took me a bit of googling to figure out the correct package name.

**Comment by goanpeca** [comment]
@oscargus any suggestion on that you think would have been helpful?

@jnsgoselin ideas here?

**Comment by jnsebgosselin** [comment]
I also confirm that installing and updating `pyls` is confusing, especially since it is not on the default channel of Anaconda. So you need to provide the channel for installing it, which is not something that is obvious for a lot of users, especially if you are installing stuff through the Anaconda gui.

So to install `pyls` you have first to figure out that it is not `pyls` but `python-language-server`, then you need to figure out that it is not on the default channel of Anaconda, so that you need to use pip or provide another channel for installing it through conda... not easy for a beginner honestly.

So adding the name of the package would be a very good improvement IMO. Also, maybe the name of the package could be a clickable url link to the documentation or github repository of the package where instructions to install them are almost always provided.

In addition, maybe we could add our recommended way of installing the package in a tooltip.

**Comment by ccordoba12** [comment]
> I also confirm that installing and updating pyls is confusing, especially since it is not on the default channel of Anaconda. So you need to provide the channel for installing it, which is not something that is obvious for a lot of users, especially if you are installing stuff through the Anacond

Let me reiterate that this is only an issue for users running Spyder directly from master. Otherwise it's very simple to install our beta's and get the right dependencies along the way.

Besides, all new packages not present in Anaconda are added to our own [channel](https://anaconda.org/spyder-ide/), so you can just install them from there.

> Also, maybe the name of the package could be a clickable url link to the documentation or github repository of the package where instructions to install them are almost always provided.

Good idea! The main document that describes how to use things from master is our Contributing guide. So I think only a link to it (when `DEV=True`) is all that's needed.

**Comment by oscargus** [comment]
If is only a problem running master it may just be better to update the Wiki pages and/or CONTRIBUTING.md (I also left some comments on gitter about similar things that are missing the other day).

It took me a while to find `conda update -all` (or rather getting the idea to google for it...), but as long as the conda dist gives you at least the version that is required (which it should), I guess that the minor issue of not being obvious how to update pyls and only pyls to the latest version is indeed quite minor.

**Comment by ccordoba12** [comment]
> If is only a problem running master it may just be better to update the Wiki pages and/or CONTRIBUTING.md

Agreed. I think everything should be consolidated around CONTRIBUTING.md and remove the old Wiki pages (or make them point to CONTRIBUTING.md). I was not even aware that those pages existed!

Could you help us with that @oscargus?

**Comment by goanpeca** [comment]
@ccordoba12 the wiki currently contains a lot of information https://github.com/spyder-ide/spyder/wiki

>I think everything should be consolidated around CONTRIBUTING.md 

There are many things around contributing that are not currently in CONTRIBUTING.md and adding them to a single file would be too much. So just to understand:

Is the plan to not use the Wiki at all and move the relevant (minimal) information to CONTRIBUTING.md and move the rest to the website to a section devoted to what is currently covered in the wiki?

**Comment by ccordoba12** [comment]
> There are many things around contributing that are not currently in CONTRIBUTING.md

Which ones?

**Comment by goanpeca** [comment]
https://github.com/spyder-ide/spyder/wiki/Contributing-to-Spyder
https://github.com/spyder-ide/spyder/wiki/Dev%3A-Index

**Comment by ccordoba12** [comment]
> https://github.com/spyder-ide/spyder/wiki/Contributing-to-Spyder

This one can be clearly removed.

> https://github.com/spyder-ide/spyder/wiki/Dev%3A-Index

You started those pages several years ago and no one else has updated them. Please remove the ones you consider unnecessary.

**Comment by goanpeca** [comment]
I think they could me updated and moved to the website so we can close the wiki for good and consolidate it in one place

**Comment by oscargus** [comment]
> Could you help us with that @oscargus?

I can definitely add the things I found missing if I can get access to the Wiki. I'll try to recap what it was and add to CONTRIBUTING.md as a start and then we can see what remains of the Wiki.

**Comment by ccordoba12** [comment]
> I think they could me updated and moved to the website so we can close the wiki for good and consolidate it in one place

I really think we should remove as much as possible of the docs present in the wiki, update and not move the rest to our website.

The thing is at least the procedure described in our Contributing guide is being tested, because we're using it in our CIs. Any other resource (most probably) is going to be outdated at some point or another.

**Comment by ccordoba12** [comment]
> I can definitely add the things I found missing if I can get access to the Wiki

Don't you have access right now @oscargus?

**Comment by goanpeca** [comment]
See https://github.com/spyder-ide/spyder/issues/9767 @ccordoba12 @oscargus

**Comment by oscargus** [comment]
@ccordoba12 No, it seems like the Wiki edit access is limited. (Even before the removal.) No "Edit" buttons in sight.

**Comment by ccordoba12** [comment]
Ok, I'll see what i can do about it.

**Comment by oscargus** [comment]
I had a look at it now. Somehow, I must have missed the requirement-files and did try to follow the explicitly given packages here: https://github.com/spyder-ide/spyder/wiki/Dev:-Testing Changing that information to the one in Contributing under "Running Tests" should solve the issues I reported on Gitter.

The only thing possibly to be updated in Contributing is the clone-approach. If a new potential developer should clone to a personal Github account before cloning and describing an upstream/origin approach already in this document.
