### ISSUE TITLE
Align plugin tabs to the left and center dockwidget tabs for all OSes

### ISSUE THREAD

**Issue by juanis2112** [spyder-ide/spyder#9763]
## Problem Description
Plugin tabs are not aligned to the left in Mac OS

![Screen Shot 2019-07-05 at 7 27 06 PM](https://user-images.githubusercontent.com/18587879/60749132-3a45bd00-9f5b-11e9-936f-6d720a8b448a.png)

**Comment by ccordoba12** [comment]
As an additional note, we also decided to center DockWidget tabs to differentiate them from Plugin tabs.

**Comment by ccordoba12** [comment]
This was @juanis2112 suggestion, and I think it's very good one. Thanks @juanis2112 for that!

**Comment by battaglia01** [comment]
@ccordoba12 for whatever reason, I just upgraded to Spyder 5.4.2 on macOS Monterey and tabs now look like this. From looking at this bug, do I guess correctly that this change was not intentional?

Here is what it looks like:
<img width="1129" alt="Screen Shot 2023-02-07 at 11 19 32 PM" src="https://user-images.githubusercontent.com/1020594/217432666-54ca02b9-bde1-4a3b-bd57-7d38204c2af2.png">

**Comment by ccordoba12** [comment]
This issue was closed more than three years ago, so it's totally unrelated to your current problem. Instead, please open a new issue for it and don't forget to include all the information we require in our issue template.

Also, please do the same in the future if you're considering to post to an issue that's more than a year old.

**Comment by battaglia01** [comment]
Thanks for explaining that to me. It's wonderful that you folks have such clear methods for keeping things organized. I will make a new issue for it at once.

**Comment by ccordoba12** [comment]
Great! Thanks for understanding and your considerate answer.
