### ISSUE TITLE
Spyder crashed during last session

### ISSUE THREAD

**Issue by yousefoleyaei** [spyder-ide/spyder#9828]
I am submitting this issue here because couldn't find any related document in Spyder. reinstalling and pip install -U sypyder it did not solve the problem Any insight into this issue kindly apprediated, Thanks! 

(mypy) sudo -H spyder3
I am getting error 
"Attribute Qt::AA_ShareOpenGLContexts must be set before QCoreApplication is created.
Attribute Qt::AA_UseSoftwareOpenGL must be set before QCoreApplication is created."
and crashing spyder even before I could use it for once.
I've all dependencies installed or at least I assume they are confirm correctly about the spyder.
I used a virtual environment in the command line of mac. I have found it might be related to ipykernel, so I downgraded by uninstalling and reinstalling the older version.
my version  
spyder                        4.0.0.dev0 

thank you in advance.

**Comment by ccordoba12** [comment]
> (mypy) sudo -H spyder3

This is totally unnecessary because you're trying to run Spyder as root, which is the most probable cause for your crash.

> "Attribute Qt::AA_ShareOpenGLContexts must be set before QCoreApplication is created.
Attribute Qt::AA_UseSoftwareOpenGL must be set before QCoreApplication is created."

These are warnings, so they don't have anything to do with your problem.

----

Since it seems you don't know very well how Linux works, we recommend you to use Anaconda instead. Otherwise it's up to you to solve this problem, because we don't have the time nor the resources to help people with other kind of installations, sorry.

**Comment by jcdives** [comment]
That wasn't necessary! You don't have to be rude and condescending!

**Comment by yousefoleyaei** [comment]
I am sorry I don't know what you are talking about. That issue might send it to you what is generated by itself.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
