### ISSUE TITLE
[4.0.0b1] Editor features stopped working properly

### ISSUE THREAD

**Issue by ivstog** [spyder-ide/spyder#9883]
After the last system upgrade some features stopped working properly in the editor. 
E.g. "mooving line up" now deletes the lines, "duplicate line" doesn't work etc. 
What can be the reason for that?

Spyder 4.0.0b1 
pyflakes >=0.5.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  1.7.7 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.11.0     :  0.13.3 (OK)
psutil >=0.3      :  5.4.7 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.24.1 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0;<6.0:  5.5.0 (OK)
matplotlib >=2.0.0:  2.2.4 (OK)

**Comment by ccordoba12** [comment]
Spyder 4.0.0b1 is no longer supported. Please update to b3 and try again.

Besides, how did you install Spyder?

**Comment by ivstog** [comment]
I installed it with pip... 
Ok, closing the issue, then.

**Comment by ivstog** [comment]
Checked on b3 -- the same issue. 
Additionally, some magic commands in qtconsole hang it, e.g "ls".

**Comment by ccordoba12** [comment]
Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.

**Comment by ivstog** [comment]
The solution was to downgrade pyqt5 back to 5.12.3-2

**Comment by ccordoba12** [comment]
We still don't support PyQt 5.13, and that's clearly declared in our setup.py. So I don't know how you ended up with it.
