### ISSUE TITLE
Variable explorer search button keeps pressed after hiding the search field with Esc

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#9893]
@dalthviz, this is a small bug I noticed after merging PR #9384: if you hide the search field with `Esc`, then the search button keeps pressed in the interface, as shown in this screenshot (I took it in the light interface theme because it's easier to see):

![Selección_002](https://user-images.githubusercontent.com/365293/61795017-c5132c80-ae22-11e9-95dc-684835e74376.png)

However, that shouldn't be the case because it's confusing. So after pressing `Esc` the search button also needs to appear as not pressed.

**Comment by dalthviz** [comment]
Should we instead of the `Search:` label show and `x` button as in the Find widget? What do you guys think @ccordoba12 @goanpeca ?

### Variable Explorer:
![imagen](https://user-images.githubusercontent.com/16781833/61817697-c2a9d600-ae14-11e9-94c2-817303a0ba10.png)

### Find Widget:
![imagen](https://user-images.githubusercontent.com/16781833/61817637-99894580-ae14-11e9-9d02-3d8653e26c21.png)

**Comment by ccordoba12** [comment]
I'm +1 so that users quickly realize that the new field in the Variable Explorer is just like any other search field.

**Comment by goanpeca** [comment]
I like the idea of keeping the search/find uniform so go for it :-)
